In [ ]:
import sys
import os
import torch

In [ ]:
# from federated_learning_cuda import load_configuration, main_experiment
from run import load_configuration, main_experiment

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")   
from run import load_and_split_with_khop, load_and_split_with_feature_prop
dataset_name = "Cora"
num_clients = 10
beta = 1
hop = 1
data_loading_option = "full"
fulltraining_flag = False

In [ ]:
cora_data = load_and_split_with_khop(dataset_name, device, num_clients, beta, hop=hop, imputation_method=data_loading_option, fulltraining_flag=fulltraining_flag)

In [ ]:
len(cora_data)

In [ ]:
# check client 0 data
print(clients_data[0])
# check number of nodes in client 0 with zerof feature vectors
# also check train/test/val nodes the number
#total nodes in client 0
total_nodes = clients_data[0].x.shape[0]
#nodes with zero feature vectors
zfv_nodes = torch.sum(clients_data[0].x == 0)
print(f"Number of nodes in client 0 with zero feature vectors: {torch.sum(clients_data[0].x == 0)}")
print(f"Number of train nodes in client 0: {torch.sum(clients_data[0].train_mask)}")
print(f"Number of test nodes in client 0: {torch.sum(clients_data[0].test_mask)}")
print(f"Number of val nodes in client 0: {torch.sum(clients_data[0].val_mask)}")

In [ ]:
# load with fp and check the same things
data, dataset, clients_data, test_data,  = load_and_split_with_feature_prop("Citeseer", device, num_clients=10, beta=0.5, hop=1)

# check client 0 data
print(clients_data[0])
# check number of nodes in client 0 with zerof feature vectors
print(f"Number of nodes in client 0 with zero feature vectors: {torch.sum(clients_data[0].x == 0)}")
print(f"Number of train nodes in client 0: {torch.sum(clients_data[0].train_mask)}")
print(f"Number of test nodes in client 0: {torch.sum(clients_data[0].test_mask)}")
print(f"Number of val nodes in client 0: {torch.sum(clients_data[0].val_mask)}")

In [ ]:
import torch

print(f"Number of GPUs available: {torch.cuda.device_count()}")

if torch.cuda.is_available():
    for i in range(torch.cuda.device_count()):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
else:
    print("No GPU available")

In [1]:
# from federated_learning_cuda import load_configuration, main_experiment
from run import load_configuration, main_experiment
import os
import ray
ray.shutdown()

if __name__ == "__main__":
    # Define all options in a list
    data_loading_options = ["full", "adjacency", "diffusion", ]
    model_types = ["GCN"]
        
    # Load configuration once since it's common for all runs
    clients_num, beta, cfg = load_configuration()

    beta = 10000

    clients_num = 10

    # Main results directory
    main_dir = 'Central_results4'
    dataset_name = "Pubmed"  # You can change this if you have different datasets

    # Loop over all combinations of data_loading_option and model_type
    for data_loading_option in data_loading_options:
        for model_type in model_types:
            # Create a structured directory for each experiment
            result_name = f"{dataset_name}_{data_loading_option}_{model_type}"
            results_dir = os.path.join(main_dir, result_name)

            # Create the directory if it doesn't exist
            os.makedirs(results_dir, exist_ok=True)

            print(f"Running experiment with data_loading_option: {data_loading_option}, model_type: {model_type}")
            result, output = main_experiment(clients_num, beta, data_loading_option, model_type, cfg, dataset_name=dataset_name, hop=1)
            
            # Replace literal '\n' with actual newline characters if necessary
            # Convert result dictionary to string representation first
            result_str = str(result)
            result_with_newlines = result_str.replace('\\n', '\n')
            
            # Create a unique filename for each combination
            filename = f'results_{dataset_name}_{data_loading_option}_{model_type}.txt'
            filepath = os.path.join(results_dir, filename)
            
            # Write the result to the text file
            with open(filepath, 'w') as f:
                f.write(result_with_newlines)
            
            print(f"Results saved to {filepath}\n")

Running experiment with data_loading_option: full, model_type: GCN
DEVICE: cuda
Data loading option is full
Model type is GCN

2025-04-11 09:00:08,473	INFO worker.py:1816 -- Started a local Ray instance.

data_loading_option: full
Data loaded
Device is cuda
Pubmed()
10

(FLClient pid=2851377) 2025-04-11 09:00:15,184 - INFO - Epoch   0| Train Loss: 1.091| Train Accuracy: 0.500
(FLClient pid=2851377) 2025-04-11 09:00:15,188 - INFO - Epoch   1| Train Loss: 0.795| Train Accuracy: 0.750
(FLClient pid=2851377) 2025-04-11 09:00:15,191 - INFO - Epoch   2| Train Loss: 0.691| Train Accuracy: 0.750
(FLClient pid=2851377) 2025-04-11 09:00:15,199 - INFO - Epoch   2| Validation Loss: 1.384, Validation Accuracy: 0.295
(FLClient pid=2851377) 2025-04-11 09:00:20,231 - INFO - Epoch   2| Train Loss: 0.639| Train Accuracy: 0.750 [repeated 360x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(FLClient pid=2851377) 2025-04-11 09:00:20,239 - INFO - Epoch   2| Validation Loss: 1.526, Validation Accuracy: 0.295 [repeated 120x across cluster]
(FLClient pid=2851377) 2025-04-11 09:00:25,319 - INFO - Epoch   2| Train Loss: 0.603| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2851377) 2025-04-11 09:00:25,322 - INFO - Epoch   2| Validation Loss: 1.466, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2851377) 2025-04-11 09:00:30,416 - INFO - Epoch   2| Train Loss: 0.447| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2851391) 2025-04-11 09:00:30,082 - INFO - Epoch   2| Validation Loss: 0.976, Validation Accuracy: 0.531 [repeated 149x across cluster]
(FLClient pid=2851377) 2025-04-11 09:00:35,533 - INFO - Epoch   1| Train Loss: 0.526| Train Accuracy: 0.750 [repeated 449x across cluster]
(FLClient pid=2851391) 2025-04-11 09:00:35,212 - INFO - Epoch   2| Validation Loss: 1.165, Validation Accuracy: 0.250 [repeated 150x across cluster]
(FLClient pid=2851377) 2025-04-11 09:00:40,645 - INFO - Epoch   2| Train Loss: 0.517| Train Accuracy: 0.750 [repeated 451x across cluster]
(FLClient pid=2851377) 2025-04-11 09:00:40,653 - INFO - Epoch   2| Validation Loss: 1.162, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2851377) 2025-04-11 09:00:45,752 - INFO - Epoch   2| Train Loss: 0.456| Train Accuracy: 1.000 [repeated 450x across cluster]
(FLClient pid=2851377) 2025-04-11 09:00:45,760 - INFO - Epoch   2| Validation Loss: 1.204, Validation Accuracy: 0.295 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.384, Train Accuracy: 0.750
Train Loss: 1.084, Train Accuracy: 0.500
Train Loss: 1.078, Train Accuracy: 0.400
Train Loss: 1.305, Train Accuracy: 0.600
Train Loss: 1.181, Train Accuracy: 0.625
Train Loss: 1.369, Train Accuracy: 0.800
Train Loss: 1.305, Train Accuracy: 0.500
Train Loss: 1.157, Train Accuracy: 0.400
Train Loss: 1.526, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.300
Round 2
Train Loss: 1.451, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.500
Train Loss: 1.065, Train Accuracy: 0.400
Train Loss: 1.338, Train Accuracy: 0.600
Train Loss: 1.202, Train Accuracy: 0.625
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.315, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.400
Train Loss: 1.647, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.400
Round 3
Train Loss: 1.433, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.059, Train Accuracy: 0.200
Train Loss: 1.320, Train Accuracy: 0.600
Train Loss: 1.216, Train Accuracy: 0.625
Train Loss: 1.298, Train Accuracy: 0.800
Train Loss: 1.378, Train Accuracy: 0.500
Train Loss: 1.153, Train Accuracy: 0.400
Train Loss: 1.693, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.300
Round 4
Train Loss: 1.343, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.500
Train Loss: 1.052, Train Accuracy: 0.400
Train Loss: 1.368, Train Accuracy: 0.600
Train Loss: 1.244, Train Accuracy: 0.625
Train Loss: 1.291, Train Accuracy: 0.800
Train Loss: 1.423, Train Accuracy: 0.500
Train Loss: 1.156, Train Accuracy: 0.400
Train Loss: 1.721, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.300
Round 5
Train Loss: 1.336, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.600
Train Loss: 1.042, Train Accuracy: 0.400
Train Loss: 1.333, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.394, Train Accuracy: 0.500
Train Loss: 1.187, Train Accuracy: 0.400
Train Loss: 1.842, Train Accuracy: 0.750
Train Loss: 1.175, Train Accuracy: 0.500
Round 6
Train Loss: 1.393, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.600
Train Loss: 1.042, Train Accuracy: 0.400
Train Loss: 1.417, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.455, Train Accuracy: 0.500
Train Loss: 1.181, Train Accuracy: 0.800
Train Loss: 1.801, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 0.300
Round 7
Train Loss: 1.458, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.344, Train Accuracy: 0.600
Train Loss: 1.251, Train Accuracy: 0.625
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.413, Train Accuracy: 0.500
Train Loss: 1.209, Train Accuracy: 0.800
Train Loss: 1.810, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.300
Round 8
Train Loss: 1.363, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.400
Train Loss: 1.034, Train Accuracy: 0.400
Train Loss: 1.398, Train Accuracy: 0.600
Train Loss: 1.254, Train Accuracy: 0.625
Train Loss: 1.284, Train Accuracy: 0.800
Train Loss: 1.455, Train Accuracy: 0.500
Train Loss: 1.183, Train Accuracy: 0.800
Train Loss: 1.849, Train Accuracy: 0.750
Train Loss: 1.218, Train Accuracy: 0.300
Round 9
Train Loss: 1.294, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.390, Train Accuracy: 0.600
Train Loss: 1.218, Train Accuracy: 0.625
Train Loss: 1.313, Train Accuracy: 0.800
Train Loss: 1.480, Train Accuracy: 0.500
Train Loss: 1.174, Train Accuracy: 0.400
Train Loss: 1.797, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.400
Round 10
Train Loss: 1.458, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.500
Train Loss: 1.036, Train Accuracy: 0.400
Train Loss: 1.412, Train Accuracy: 0.600
Train Loss: 1.261, Train Accuracy: 0.625
Train Loss: 1.369, Train Accuracy: 0.800
Train Loss: 1.482, Train Accuracy: 0.500
Train Loss: 1.179, Train Accuracy: 0.600
Train Loss: 1.971, Train Accuracy: 0.750
Train Loss: 1.115, Train Accuracy: 0.200
Round 11
Train Loss: 1.325, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.461, Train Accuracy: 0.600
Train Loss: 1.234, Train Accuracy: 0.625
Train Loss: 1.453, Train Accuracy: 0.800
Train Loss: 1.503, Train Accuracy: 0.250
Train Loss: 1.211, Train Accuracy: 0.400
Train Loss: 1.909, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.500
Round 12
Train Loss: 1.376, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.600
Train Loss: 1.026, Train Accuracy: 0.400
Train Loss: 1.355, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.321, Train Accuracy: 0.800
Train Loss: 1.484, Train Accuracy: 0.250
Train Loss: 1.206, Train Accuracy: 0.600
Train Loss: 1.984, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.500
Round 13
Train Loss: 1.526, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.700
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.436, Train Accuracy: 0.800
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.393, Train Accuracy: 0.800
Train Loss: 1.559, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.400
Train Loss: 1.917, Train Accuracy: 0.750
Train Loss: 1.203, Train Accuracy: 0.300
Round 14
Train Loss: 1.329, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.500
Train Loss: 1.011, Train Accuracy: 0.600
Train Loss: 1.386, Train Accuracy: 0.600
Train Loss: 1.242, Train Accuracy: 0.750
Train Loss: 1.419, Train Accuracy: 0.800
Train Loss: 1.464, Train Accuracy: 0.750
Train Loss: 1.189, Train Accuracy: 0.400
Train Loss: 1.877, Train Accuracy: 0.750
Train Loss: 1.121, Train Accuracy: 0.400
Round 15
Train Loss: 1.370, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.600
Train Loss: 1.018, Train Accuracy: 0.400
Train Loss: 1.479, Train Accuracy: 0.800
Train Loss: 1.222, Train Accuracy: 0.625
Train Loss: 1.356, Train Accuracy: 0.800
Train Loss: 1.495, Train Accuracy: 0.500
Train Loss: 1.172, Train Accuracy: 0.600
Train Loss: 1.947, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.400
Round 16
Train Loss: 1.187, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.500
Train Loss: 1.007, Train Accuracy: 0.600
Train Loss: 1.359, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.750
Train Loss: 1.313, Train Accuracy: 0.800
Train Loss: 1.475, Train Accuracy: 0.500
Train Loss: 1.221, Train Accuracy: 0.800
Train Loss: 1.903, Train Accuracy: 0.750
Train Loss: 1.123, Train Accuracy: 0.500
Round 17
Train Loss: 1.348, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 1.000, Train Accuracy: 0.400
Train Loss: 1.469, Train Accuracy: 0.800
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.411, Train Accuracy: 0.800
Train Loss: 1.488, Train Accuracy: 0.500
Train Loss: 1.132, Train Accuracy: 0.600
Train Loss: 1.950, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.500
Round 18
Train Loss: 1.276, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.700
Train Loss: 1.003, Train Accuracy: 0.400
Train Loss: 1.343, Train Accuracy: 0.600
Train Loss: 1.218, Train Accuracy: 0.625
Train Loss: 1.396, Train Accuracy: 0.800
Train Loss: 1.509, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.600
Train Loss: 1.988, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.400
Round 19
Train Loss: 1.489, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 0.996, Train Accuracy: 0.200
Train Loss: 1.447, Train Accuracy: 0.800
Train Loss: 1.184, Train Accuracy: 0.750
Train Loss: 1.298, Train Accuracy: 0.800
Train Loss: 1.507, Train Accuracy: 0.500
Train Loss: 1.231, Train Accuracy: 0.800
Train Loss: 1.859, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.200
Round 20
Train Loss: 1.214, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.700
Train Loss: 0.990, Train Accuracy: 0.400
Train Loss: 1.291, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.377, Train Accuracy: 0.800
Train Loss: 1.498, Train Accuracy: 0.500
Train Loss: 1.167, Train Accuracy: 0.600
Train Loss: 2.143, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.800
Round 21
Train Loss: 1.402, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.600
Train Loss: 0.988, Train Accuracy: 0.400
Train Loss: 1.413, Train Accuracy: 0.800
Train Loss: 1.265, Train Accuracy: 0.750
Train Loss: 1.315, Train Accuracy: 0.800
Train Loss: 1.532, Train Accuracy: 1.000
Train Loss: 1.108, Train Accuracy: 0.400
Train Loss: 1.854, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.400
Round 22
Train Loss: 1.485, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.500
Train Loss: 0.986, Train Accuracy: 0.200
Train Loss: 1.389, Train Accuracy: 0.600
Train Loss: 1.229, Train Accuracy: 0.625
Train Loss: 1.238, Train Accuracy: 0.800
Train Loss: 1.567, Train Accuracy: 0.500
Train Loss: 1.130, Train Accuracy: 0.800
Train Loss: 1.973, Train Accuracy: 0.750
Train Loss: 1.092, Train Accuracy: 0.500
Round 23
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 1.022, Train Accuracy: 0.600
Train Loss: 1.004, Train Accuracy: 0.400
Train Loss: 1.367, Train Accuracy: 0.600
Train Loss: 1.184, Train Accuracy: 0.750
Train Loss: 1.371, Train Accuracy: 0.800
Train Loss: 1.500, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.600
Train Loss: 1.843, Train Accuracy: 0.750
Train Loss: 1.114, Train Accuracy: 0.700
Round 24
Train Loss: 1.553, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.700
Train Loss: 0.973, Train Accuracy: 0.400
Train Loss: 1.371, Train Accuracy: 0.800
Train Loss: 1.234, Train Accuracy: 0.625
Train Loss: 1.373, Train Accuracy: 0.800
Train Loss: 1.618, Train Accuracy: 1.000
Train Loss: 1.064, Train Accuracy: 0.600
Train Loss: 1.930, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Round 25
Train Loss: 1.469, Train Accuracy: 0.750
Train Loss: 1.025, Train Accuracy: 0.600
Train Loss: 0.979, Train Accuracy: 0.600
Train Loss: 1.322, Train Accuracy: 0.800
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.386, Train Accuracy: 0.800
Train Loss: 1.660, Train Accuracy: 0.500
Train Loss: 1.113, Train Accuracy: 0.800
Train Loss: 2.109, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.600
Round 26
Train Loss: 1.408, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.700
Train Loss: 0.984, Train Accuracy: 0.400
Train Loss: 1.379, Train Accuracy: 0.600
Train Loss: 1.210, Train Accuracy: 0.625
Train Loss: 1.398, Train Accuracy: 0.800
Train Loss: 1.620, Train Accuracy: 0.750
Train Loss: 1.253, Train Accuracy: 0.400
Train Loss: 1.892, Train Accuracy: 0.750
Train Loss: 1.146, Train Accuracy: 0.700
Round 27
Train Loss: 1.155, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.600
Train Loss: 0.959, Train Accuracy: 0.400
Train Loss: 1.437, Train Accuracy: 0.600
Train Loss: 1.162, Train Accuracy: 0.750
Train Loss: 1.401, Train Accuracy: 0.800
Train Loss: 1.518, Train Accuracy: 0.500
Train Loss: 1.295, Train Accuracy: 0.600
Train Loss: 2.024, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.500
Round 28
Train Loss: 1.466, Train Accuracy: 0.750
Train Loss: 1.004, Train Accuracy: 0.600
Train Loss: 0.964, Train Accuracy: 0.400
Train Loss: 1.247, Train Accuracy: 0.400
Train Loss: 1.109, Train Accuracy: 0.750
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.431, Train Accuracy: 0.500
Train Loss: 1.100, Train Accuracy: 0.600
Train Loss: 2.008, Train Accuracy: 0.750
Train Loss: 1.103, Train Accuracy: 0.400
Round 29
Train Loss: 1.204, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.700
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 1.357, Train Accuracy: 0.800
Train Loss: 1.210, Train Accuracy: 0.625
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.513, Train Accuracy: 0.750
Train Loss: 1.114, Train Accuracy: 0.400
Train Loss: 1.883, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.600
Round 30
Train Loss: 1.360, Train Accuracy: 0.750
Train Loss: 0.988, Train Accuracy: 0.700
Train Loss: 0.948, Train Accuracy: 0.400
Train Loss: 1.338, Train Accuracy: 0.600
Train Loss: 1.134, Train Accuracy: 0.750
Train Loss: 1.266, Train Accuracy: 0.800
Train Loss: 1.395, Train Accuracy: 0.500
Train Loss: 1.090, Train Accuracy: 0.800
Train Loss: 2.023, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.600
Round 31
Train Loss: 1.205, Train Accuracy: 0.750
Train Loss: 0.988, Train Accuracy: 0.700
Train Loss: 0.966, Train Accuracy: 0.200
Train Loss: 1.356, Train Accuracy: 0.600
Train Loss: 1.165, Train Accuracy: 0.750
Train Loss: 1.349, Train Accuracy: 1.000
Train Loss: 1.467, Train Accuracy: 0.500
Train Loss: 1.331, Train Accuracy: 0.200
Train Loss: 1.944, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.600
Round 32
Train Loss: 1.337, Train Accuracy: 0.750
Train Loss: 0.984, Train Accuracy: 0.700
Train Loss: 0.957, Train Accuracy: 0.600
Train Loss: 1.240, Train Accuracy: 0.600
Train Loss: 1.121, Train Accuracy: 0.750
Train Loss: 1.231, Train Accuracy: 0.800
Train Loss: 1.487, Train Accuracy: 0.500
Train Loss: 1.056, Train Accuracy: 0.800
Train Loss: 2.012, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.700
Round 33
Train Loss: 1.410, Train Accuracy: 0.750
Train Loss: 0.998, Train Accuracy: 0.600
Train Loss: 0.934, Train Accuracy: 0.600
Train Loss: 1.218, Train Accuracy: 0.600
Train Loss: 1.138, Train Accuracy: 0.750
Train Loss: 1.293, Train Accuracy: 0.800
Train Loss: 1.480, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.600
Train Loss: 1.713, Train Accuracy: 0.750
Train Loss: 1.084, Train Accuracy: 0.700
Round 34
Train Loss: 1.242, Train Accuracy: 0.750
Train Loss: 0.972, Train Accuracy: 0.600
Train Loss: 0.956, Train Accuracy: 0.400
Train Loss: 1.379, Train Accuracy: 1.000
Train Loss: 1.164, Train Accuracy: 0.750
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.567, Train Accuracy: 0.500
Train Loss: 1.147, Train Accuracy: 0.800
Train Loss: 2.134, Train Accuracy: 1.000
Train Loss: 0.989, Train Accuracy: 0.600
Round 35
Train Loss: 1.237, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.700
Train Loss: 0.926, Train Accuracy: 0.400
Train Loss: 1.347, Train Accuracy: 1.000
Train Loss: 1.143, Train Accuracy: 0.750
Train Loss: 1.220, Train Accuracy: 0.800
Train Loss: 1.699, Train Accuracy: 0.500
Train Loss: 1.111, Train Accuracy: 0.800
Train Loss: 2.123, Train Accuracy: 1.000
Train Loss: 1.141, Train Accuracy: 0.700
Round 36
Train Loss: 1.342, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.500
Train Loss: 0.920, Train Accuracy: 0.400
Train Loss: 1.224, Train Accuracy: 0.800
Train Loss: 1.108, Train Accuracy: 0.750
Train Loss: 1.416, Train Accuracy: 0.800
Train Loss: 1.541, Train Accuracy: 0.500
Train Loss: 1.127, Train Accuracy: 0.800
Train Loss: 2.082, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.600
Round 37
Train Loss: 1.365, Train Accuracy: 0.750
Train Loss: 0.958, Train Accuracy: 0.700
Train Loss: 0.955, Train Accuracy: 0.600
Train Loss: 1.344, Train Accuracy: 0.600
Train Loss: 1.244, Train Accuracy: 0.625
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.483, Train Accuracy: 0.750
Train Loss: 0.978, Train Accuracy: 0.600
Train Loss: 2.176, Train Accuracy: 1.000
Train Loss: 1.009, Train Accuracy: 0.700
Round 38
Train Loss: 1.245, Train Accuracy: 0.750
Train Loss: 1.020, Train Accuracy: 0.800
Train Loss: 0.936, Train Accuracy: 0.600
Train Loss: 1.342, Train Accuracy: 0.800
Train Loss: 1.140, Train Accuracy: 0.875
Train Loss: 1.541, Train Accuracy: 0.800
Train Loss: 1.390, Train Accuracy: 0.500
Train Loss: 1.094, Train Accuracy: 0.800
Train Loss: 2.144, Train Accuracy: 1.000
Train Loss: 1.034, Train Accuracy: 0.700
Round 39
Train Loss: 1.176, Train Accuracy: 0.750
Train Loss: 0.940, Train Accuracy: 0.700
Train Loss: 1.014, Train Accuracy: 0.600
Train Loss: 1.423, Train Accuracy: 0.600
Train Loss: 1.182, Train Accuracy: 0.625
Train Loss: 1.319, Train Accuracy: 0.800
Train Loss: 1.644, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.800
Train Loss: 2.153, Train Accuracy: 1.000
Train Loss: 1.068, Train Accuracy: 0.800
Round 40
Train Loss: 1.381, Train Accuracy: 0.750
Train Loss: 0.950, Train Accuracy: 0.500
Train Loss: 0.916, Train Accuracy: 0.400
Train Loss: 1.365, Train Accuracy: 0.800
Train Loss: 1.095, Train Accuracy: 0.875
Train Loss: 1.324, Train Accuracy: 0.800
Train Loss: 1.486, Train Accuracy: 1.000
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.956, Train Accuracy: 0.750
Train Loss: 0.960, Train Accuracy: 0.300
Round 41
Train Loss: 1.053, Train Accuracy: 0.750
Train Loss: 0.926, Train Accuracy: 0.600
Train Loss: 0.894, Train Accuracy: 0.400
Train Loss: 1.259, Train Accuracy: 1.000
Train Loss: 1.070, Train Accuracy: 0.750
Train Loss: 1.456, Train Accuracy: 0.800
Train Loss: 1.672, Train Accuracy: 0.500
Train Loss: 1.071, Train Accuracy: 0.600
Train Loss: 2.162, Train Accuracy: 0.750
Train Loss: 1.050, Train Accuracy: 0.900
Round 42
Train Loss: 1.325, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.600
Train Loss: 0.926, Train Accuracy: 0.800
Train Loss: 1.246, Train Accuracy: 1.000
Train Loss: 1.140, Train Accuracy: 0.750
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.970, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.800
Train Loss: 1.838, Train Accuracy: 1.000
Train Loss: 0.976, Train Accuracy: 0.800
Round 43
Train Loss: 1.114, Train Accuracy: 0.750
Train Loss: 0.963, Train Accuracy: 0.400
Train Loss: 0.899, Train Accuracy: 0.200
Train Loss: 1.170, Train Accuracy: 1.000
Train Loss: 1.079, Train Accuracy: 0.750
Train Loss: 1.322, Train Accuracy: 0.800
Train Loss: 1.726, Train Accuracy: 0.500
Train Loss: 1.040, Train Accuracy: 0.800
Train Loss: 2.110, Train Accuracy: 1.000
Train Loss: 0.998, Train Accuracy: 0.600
Round 44
Train Loss: 1.608, Train Accuracy: 0.500
Train Loss: 0.926, Train Accuracy: 0.600
Train Loss: 0.915, Train Accuracy: 0.600
Train Loss: 1.130, Train Accuracy: 0.600
Train Loss: 1.078, Train Accuracy: 0.750
Train Loss: 1.296, Train Accuracy: 0.800
Train Loss: 1.340, Train Accuracy: 0.500
Train Loss: 1.099, Train Accuracy: 0.800
Train Loss: 1.854, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.600
Round 45
Train Loss: 1.035, Train Accuracy: 0.750
Train Loss: 1.007, Train Accuracy: 0.800
Train Loss: 0.898, Train Accuracy: 0.600
Train Loss: 1.164, Train Accuracy: 0.800
Train Loss: 1.058, Train Accuracy: 0.750
Train Loss: 1.293, Train Accuracy: 0.800
Train Loss: 1.327, Train Accuracy: 0.750
Train Loss: 1.011, Train Accuracy: 0.800
Train Loss: 2.071, Train Accuracy: 1.000
Train Loss: 0.985, Train Accuracy: 0.600
Round 46
Train Loss: 1.380, Train Accuracy: 0.750
Train Loss: 0.964, Train Accuracy: 0.800
Train Loss: 0.912, Train Accuracy: 0.200
Train Loss: 1.244, Train Accuracy: 0.800
Train Loss: 1.158, Train Accuracy: 0.750
Train Loss: 1.442, Train Accuracy: 0.800
Train Loss: 1.896, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 1.000
Train Loss: 1.932, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.700
Round 47
Train Loss: 1.316, Train Accuracy: 0.250
Train Loss: 0.915, Train Accuracy: 0.700
Train Loss: 0.868, Train Accuracy: 0.600
Train Loss: 1.199, Train Accuracy: 0.800
Train Loss: 1.105, Train Accuracy: 0.625
Train Loss: 1.124, Train Accuracy: 0.800
Train Loss: 1.369, Train Accuracy: 0.500
Train Loss: 1.050, Train Accuracy: 1.000
Train Loss: 2.381, Train Accuracy: 0.750
Train Loss: 0.983, Train Accuracy: 0.700
Round 48
Train Loss: 1.278, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.700
Train Loss: 0.927, Train Accuracy: 0.600
Train Loss: 1.121, Train Accuracy: 0.800
Train Loss: 1.025, Train Accuracy: 0.750
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.710, Train Accuracy: 0.750

(FLClient pid=2851384) 2025-04-11 09:00:57,566 - INFO - Epoch   2| Train Loss: 0.747| Train Accuracy: 0.750 [repeated 390x across cluster]
(FLClient pid=2851384) 2025-04-11 09:00:57,575 - INFO - Epoch   2| Validation Loss: 1.285, Validation Accuracy: 0.295 [repeated 130x across cluster]
(FLClient pid=2851390) 2025-04-11 09:01:02,663 - INFO - Epoch   2| Train Loss: 0.970| Train Accuracy: 0.400 [repeated 390x across cluster]
(FLClient pid=2851390) 2025-04-11 09:01:02,671 - INFO - Epoch   2| Validation Loss: 1.061, Validation Accuracy: 0.467 [repeated 130x across cluster]
(FLClient pid=2851390) 2025-04-11 09:01:07,757 - INFO - Epoch   2| Train Loss: 0.869| Train Accuracy: 0.600 [repeated 450x across cluster]
(FLClient pid=2851392) 2025-04-11 09:01:07,428 - INFO - Epoch   2| Validation Loss: 1.791, Validation Accuracy: 0.233 [repeated 149x across cluster]
(FLClient pid=2851390) 2025-04-11 09:01:12,842 - INFO - Epoch   2| Train Loss: 0.845| Train Accuracy: 0.500 [repeated 450x across cluster]
(FLClient pid=2851390) 2025-04-11 09:01:12,849 - INFO - Epoch   2| Validation Loss: 0.980, Validation Accuracy: 0.467 [repeated 151x across cluster]
(FLClient pid=2851390) 2025-04-11 09:01:17,934 - INFO - Epoch   2| Train Loss: 0.592| Train Accuracy: 0.900 [repeated 450x across cluster]
(FLClient pid=2851390) 2025-04-11 09:01:17,942 - INFO - Epoch   2| Validation Loss: 0.868, Validation Accuracy: 0.511 [repeated 150x across cluster]
(FLClient pid=2851390) 2025-04-11 09:01:23,015 - INFO - Epoch   0| Train Loss: 0.818| Train Accuracy: 0.500 [repeated 448x across cluster]
(FLClient pid=2851392) 2025-04-11 09:01:22,708 - INFO - Epoch   2| Validation Loss: 1.955, Validation Accuracy: 0.233 [repeated 149x across cluster]
(FLClient pid=2851390) 2025-04-11 09:01:28,100 - INFO - Epoch   2| Train Loss: 0.563| Train Accuracy: 0.700 [repeated 452x across cluster]
(FLClient pid=2851390) 2025-04-11 09:01:28,107 - INFO - Epoch   2| Validation Loss: 0.784, Validation Accuracy: 0.578 [repeated 151x across cluster]

Training done
Round 1
Train Loss: 1.285, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.064, Train Accuracy: 0.400
Train Loss: 1.191, Train Accuracy: 0.600
Train Loss: 1.177, Train Accuracy: 0.625
Train Loss: 1.236, Train Accuracy: 0.800
Train Loss: 1.312, Train Accuracy: 0.500
Train Loss: 1.128, Train Accuracy: 0.000
Train Loss: 1.351, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.500
Round 2
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.050, Train Accuracy: 0.400
Train Loss: 1.200, Train Accuracy: 0.600
Train Loss: 1.201, Train Accuracy: 0.625
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.342, Train Accuracy: 0.250
Train Loss: 1.141, Train Accuracy: 0.400
Train Loss: 1.416, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.300
Round 3
Train Loss: 1.236, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.050, Train Accuracy: 0.400
Train Loss: 1.238, Train Accuracy: 0.600
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.371, Train Accuracy: 0.500
Train Loss: 1.156, Train Accuracy: 0.600
Train Loss: 1.468, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.300
Round 4
Train Loss: 1.347, Train Accuracy: 0.750
Train Loss: 1.091, Train Accuracy: 0.500
Train Loss: 1.049, Train Accuracy: 0.400
Train Loss: 1.261, Train Accuracy: 0.600
Train Loss: 1.240, Train Accuracy: 0.625
Train Loss: 1.296, Train Accuracy: 0.800
Train Loss: 1.390, Train Accuracy: 0.500
Train Loss: 1.159, Train Accuracy: 0.600
Train Loss: 1.511, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.300
Round 5
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.400
Train Loss: 1.285, Train Accuracy: 0.600
Train Loss: 1.221, Train Accuracy: 0.625
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.410, Train Accuracy: 0.500
Train Loss: 1.168, Train Accuracy: 0.200
Train Loss: 1.594, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.500
Round 6
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.400
Train Loss: 1.288, Train Accuracy: 0.600
Train Loss: 1.244, Train Accuracy: 0.625
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.444, Train Accuracy: 0.250
Train Loss: 1.186, Train Accuracy: 0.600
Train Loss: 1.567, Train Accuracy: 0.750
Train Loss: 1.189, Train Accuracy: 0.400
Round 7
Train Loss: 1.255, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.322, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.625
Train Loss: 1.296, Train Accuracy: 0.800
Train Loss: 1.466, Train Accuracy: 0.500
Train Loss: 1.182, Train Accuracy: 0.800
Train Loss: 1.628, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.500
Round 8
Train Loss: 1.320, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.296, Train Accuracy: 0.600
Train Loss: 1.240, Train Accuracy: 0.625
Train Loss: 1.296, Train Accuracy: 0.800
Train Loss: 1.446, Train Accuracy: 0.500
Train Loss: 1.141, Train Accuracy: 0.600
Train Loss: 1.644, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.400
Round 9
Train Loss: 1.312, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.400
Train Loss: 1.028, Train Accuracy: 0.800
Train Loss: 1.337, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.319, Train Accuracy: 0.800
Train Loss: 1.454, Train Accuracy: 0.500
Train Loss: 1.190, Train Accuracy: 0.800
Train Loss: 1.679, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.500
Round 10
Train Loss: 1.389, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.021, Train Accuracy: 0.400
Train Loss: 1.347, Train Accuracy: 0.600
Train Loss: 1.268, Train Accuracy: 0.625
Train Loss: 1.262, Train Accuracy: 0.800
Train Loss: 1.455, Train Accuracy: 0.500
Train Loss: 1.194, Train Accuracy: 0.600
Train Loss: 1.743, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.300
Round 11
Train Loss: 1.388, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.021, Train Accuracy: 0.400
Train Loss: 1.380, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.506, Train Accuracy: 0.500
Train Loss: 1.187, Train Accuracy: 0.400
Train Loss: 1.810, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.400
Round 12
Train Loss: 1.317, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.500
Train Loss: 1.020, Train Accuracy: 0.400
Train Loss: 1.389, Train Accuracy: 0.600
Train Loss: 1.263, Train Accuracy: 0.625
Train Loss: 1.329, Train Accuracy: 0.800
Train Loss: 1.471, Train Accuracy: 0.500
Train Loss: 1.127, Train Accuracy: 0.800
Train Loss: 1.745, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.400
Round 13
Train Loss: 1.333, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.500
Train Loss: 1.020, Train Accuracy: 0.400
Train Loss: 1.278, Train Accuracy: 0.600
Train Loss: 1.265, Train Accuracy: 0.625
Train Loss: 1.260, Train Accuracy: 0.800
Train Loss: 1.496, Train Accuracy: 0.500
Train Loss: 1.196, Train Accuracy: 0.600
Train Loss: 1.759, Train Accuracy: 0.750
Train Loss: 1.217, Train Accuracy: 0.500
Round 14
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.400
Train Loss: 1.019, Train Accuracy: 0.400
Train Loss: 1.376, Train Accuracy: 0.400
Train Loss: 1.283, Train Accuracy: 0.625
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.518, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.800
Train Loss: 1.697, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.400
Round 15
Train Loss: 1.241, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.600
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.378, Train Accuracy: 0.800
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.671, Train Accuracy: 0.500
Train Loss: 1.155, Train Accuracy: 0.400
Train Loss: 1.865, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.400
Round 16
Train Loss: 1.419, Train Accuracy: 0.750
Train Loss: 1.050, Train Accuracy: 0.400
Train Loss: 1.016, Train Accuracy: 0.600
Train Loss: 1.364, Train Accuracy: 0.600
Train Loss: 1.239, Train Accuracy: 0.750
Train Loss: 1.327, Train Accuracy: 0.800
Train Loss: 1.552, Train Accuracy: 0.500
Train Loss: 1.185, Train Accuracy: 0.800
Train Loss: 1.772, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.400
Round 17
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.007, Train Accuracy: 0.400
Train Loss: 1.458, Train Accuracy: 0.800
Train Loss: 1.251, Train Accuracy: 0.500
Train Loss: 1.301, Train Accuracy: 0.800
Train Loss: 1.504, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.400
Train Loss: 1.892, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.400
Round 18
Train Loss: 1.269, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.500
Train Loss: 1.007, Train Accuracy: 0.400
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.225, Train Accuracy: 0.500
Train Loss: 1.321, Train Accuracy: 0.800
Train Loss: 1.507, Train Accuracy: 0.500
Train Loss: 1.093, Train Accuracy: 0.400
Train Loss: 1.864, Train Accuracy: 0.750
Train Loss: 1.148, Train Accuracy: 0.600
Round 19
Train Loss: 1.341, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.397, Train Accuracy: 0.600
Train Loss: 1.176, Train Accuracy: 0.875
Train Loss: 1.296, Train Accuracy: 0.800
Train Loss: 1.525, Train Accuracy: 0.500
Train Loss: 1.101, Train Accuracy: 0.400
Train Loss: 1.810, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.300
Round 20
Train Loss: 1.278, Train Accuracy: 0.750
Train Loss: 1.046, Train Accuracy: 0.700
Train Loss: 1.004, Train Accuracy: 0.400
Train Loss: 1.415, Train Accuracy: 0.600
Train Loss: 1.260, Train Accuracy: 0.625
Train Loss: 1.268, Train Accuracy: 0.800
Train Loss: 1.511, Train Accuracy: 0.500
Train Loss: 1.155, Train Accuracy: 0.800
Train Loss: 1.927, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.500
Round 21
Train Loss: 1.338, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.400
Train Loss: 0.988, Train Accuracy: 0.400
Train Loss: 1.385, Train Accuracy: 0.600
Train Loss: 1.202, Train Accuracy: 0.625
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.491, Train Accuracy: 0.500
Train Loss: 1.115, Train Accuracy: 0.600
Train Loss: 1.810, Train Accuracy: 0.750
Train Loss: 1.205, Train Accuracy: 0.700
Round 22
Train Loss: 1.194, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.600
Train Loss: 1.002, Train Accuracy: 0.400
Train Loss: 1.303, Train Accuracy: 0.600
Train Loss: 1.212, Train Accuracy: 0.625
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.463, Train Accuracy: 0.750
Train Loss: 1.277, Train Accuracy: 0.600
Train Loss: 1.719, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.600
Round 23
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.500
Train Loss: 0.990, Train Accuracy: 0.600
Train Loss: 1.319, Train Accuracy: 0.600
Train Loss: 1.202, Train Accuracy: 0.625
Train Loss: 1.284, Train Accuracy: 0.800
Train Loss: 1.432, Train Accuracy: 0.500
Train Loss: 1.115, Train Accuracy: 0.400
Train Loss: 1.737, Train Accuracy: 0.750
Train Loss: 1.114, Train Accuracy: 0.500
Round 24
Train Loss: 1.416, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.400
Train Loss: 0.997, Train Accuracy: 0.400
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.179, Train Accuracy: 0.625
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.512, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.800
Train Loss: 1.834, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.700
Round 25
Train Loss: 1.306, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.700
Train Loss: 0.974, Train Accuracy: 0.400
Train Loss: 1.322, Train Accuracy: 0.800
Train Loss: 1.216, Train Accuracy: 0.500
Train Loss: 1.251, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.400
Train Loss: 1.980, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.400
Round 26
Train Loss: 1.392, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.700
Train Loss: 0.993, Train Accuracy: 0.400
Train Loss: 1.435, Train Accuracy: 0.800
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.345, Train Accuracy: 0.800
Train Loss: 1.585, Train Accuracy: 0.500
Train Loss: 1.235, Train Accuracy: 0.400
Train Loss: 1.942, Train Accuracy: 0.750
Train Loss: 1.105, Train Accuracy: 0.400
Round 27
Train Loss: 1.348, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.700
Train Loss: 0.978, Train Accuracy: 0.600
Train Loss: 1.312, Train Accuracy: 1.000
Train Loss: 1.217, Train Accuracy: 0.750
Train Loss: 1.318, Train Accuracy: 0.800
Train Loss: 1.487, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.400
Train Loss: 1.831, Train Accuracy: 0.750
Train Loss: 1.123, Train Accuracy: 0.800
Round 28
Train Loss: 1.450, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.600
Train Loss: 0.978, Train Accuracy: 0.600
Train Loss: 1.324, Train Accuracy: 0.800
Train Loss: 1.203, Train Accuracy: 0.750
Train Loss: 1.307, Train Accuracy: 0.800
Train Loss: 1.497, Train Accuracy: 0.500
Train Loss: 1.176, Train Accuracy: 0.600
Train Loss: 1.791, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.600
Round 29
Train Loss: 1.289, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.600
Train Loss: 0.986, Train Accuracy: 0.800
Train Loss: 1.427, Train Accuracy: 1.000
Train Loss: 1.148, Train Accuracy: 0.875
Train Loss: 1.396, Train Accuracy: 0.800
Train Loss: 1.576, Train Accuracy: 0.500
Train Loss: 1.104, Train Accuracy: 0.600
Train Loss: 1.898, Train Accuracy: 0.750
Train Loss: 1.046, Train Accuracy: 0.500
Round 30
Train Loss: 1.315, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.700
Train Loss: 0.951, Train Accuracy: 0.800
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.222, Train Accuracy: 0.625
Train Loss: 1.312, Train Accuracy: 0.800
Train Loss: 1.628, Train Accuracy: 1.000
Train Loss: 1.101, Train Accuracy: 0.600
Train Loss: 1.896, Train Accuracy: 0.750
Train Loss: 1.121, Train Accuracy: 0.600
Round 31
Train Loss: 1.295, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.800
Train Loss: 0.953, Train Accuracy: 0.400
Train Loss: 1.324, Train Accuracy: 0.800
Train Loss: 1.185, Train Accuracy: 0.750
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.451, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.600
Train Loss: 1.669, Train Accuracy: 0.750
Train Loss: 1.092, Train Accuracy: 0.600
Round 32
Train Loss: 1.368, Train Accuracy: 0.750
Train Loss: 0.992, Train Accuracy: 0.700
Train Loss: 0.949, Train Accuracy: 0.400
Train Loss: 1.362, Train Accuracy: 0.800
Train Loss: 1.221, Train Accuracy: 0.750
Train Loss: 1.234, Train Accuracy: 0.800
Train Loss: 1.570, Train Accuracy: 0.500
Train Loss: 1.034, Train Accuracy: 0.800
Train Loss: 1.689, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.400
Round 33
Train Loss: 1.261, Train Accuracy: 0.750
Train Loss: 0.989, Train Accuracy: 0.400
Train Loss: 0.959, Train Accuracy: 0.600
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.197, Train Accuracy: 0.500
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.544, Train Accuracy: 0.500
Train Loss: 1.201, Train Accuracy: 0.400
Train Loss: 1.692, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.500
Round 34
Train Loss: 1.212, Train Accuracy: 0.750
Train Loss: 1.011, Train Accuracy: 0.500
Train Loss: 0.951, Train Accuracy: 0.400
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.160, Train Accuracy: 0.750
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.506, Train Accuracy: 1.000
Train Loss: 1.068, Train Accuracy: 0.600
Train Loss: 1.717, Train Accuracy: 0.750
Train Loss: 1.050, Train Accuracy: 0.700
Round 35
Train Loss: 1.131, Train Accuracy: 0.750
Train Loss: 1.004, Train Accuracy: 0.600
Train Loss: 0.951, Train Accuracy: 0.600
Train Loss: 1.361, Train Accuracy: 0.800
Train Loss: 1.190, Train Accuracy: 0.750
Train Loss: 1.283, Train Accuracy: 0.800
Train Loss: 1.497, Train Accuracy: 1.000
Train Loss: 1.075, Train Accuracy: 0.600
Train Loss: 1.905, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.400
Round 36
Train Loss: 1.180, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.600
Train Loss: 0.955, Train Accuracy: 0.600
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.148, Train Accuracy: 0.500
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.839, Train Accuracy: 0.500
Train Loss: 1.076, Train Accuracy: 0.800
Train Loss: 1.875, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.700
Round 37
Train Loss: 1.132, Train Accuracy: 0.750
Train Loss: 0.979, Train Accuracy: 0.600
Train Loss: 0.926, Train Accuracy: 0.600
Train Loss: 1.267, Train Accuracy: 1.000
Train Loss: 1.247, Train Accuracy: 0.875
Train Loss: 1.361, Train Accuracy: 0.800
Train Loss: 1.529, Train Accuracy: 1.000
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 1.722, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.600
Round 38
Train Loss: 1.195, Train Accuracy: 0.750
Train Loss: 0.963, Train Accuracy: 0.600
Train Loss: 0.954, Train Accuracy: 0.600
Train Loss: 1.379, Train Accuracy: 0.800
Train Loss: 1.090, Train Accuracy: 0.875
Train Loss: 1.329, Train Accuracy: 0.800
Train Loss: 1.517, Train Accuracy: 0.500
Train Loss: 1.362, Train Accuracy: 0.600
Train Loss: 1.924, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.600
Round 39
Train Loss: 1.053, Train Accuracy: 0.750
Train Loss: 0.968, Train Accuracy: 0.800
Train Loss: 0.936, Train Accuracy: 0.800
Train Loss: 1.276, Train Accuracy: 0.800
Train Loss: 1.213, Train Accuracy: 0.750
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.497, Train Accuracy: 0.500
Train Loss: 1.109, Train Accuracy: 0.600
Train Loss: 1.949, Train Accuracy: 0.750
Train Loss: 1.118, Train Accuracy: 0.800
Round 40
Train Loss: 1.270, Train Accuracy: 0.750
Train Loss: 0.954, Train Accuracy: 0.600
Train Loss: 0.955, Train Accuracy: 0.600
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.115, Train Accuracy: 0.750
Train Loss: 1.394, Train Accuracy: 0.800
Train Loss: 1.507, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.800
Train Loss: 1.939, Train Accuracy: 0.750
Train Loss: 1.109, Train Accuracy: 0.700
Round 41
Train Loss: 1.364, Train Accuracy: 0.750
Train Loss: 0.989, Train Accuracy: 0.600
Train Loss: 0.893, Train Accuracy: 0.400
Train Loss: 1.275, Train Accuracy: 1.000
Train Loss: 1.121, Train Accuracy: 0.750
Train Loss: 1.339, Train Accuracy: 0.800
Train Loss: 1.589, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.800
Train Loss: 1.770, Train Accuracy: 0.750
Train Loss: 1.214, Train Accuracy: 0.400
Round 42
Train Loss: 1.251, Train Accuracy: 0.750
Train Loss: 0.967, Train Accuracy: 0.600
Train Loss: 0.949, Train Accuracy: 0.800
Train Loss: 1.520, Train Accuracy: 0.800
Train Loss: 1.114, Train Accuracy: 0.750
Train Loss: 1.360, Train Accuracy: 0.800
Train Loss: 1.636, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.600
Train Loss: 1.975, Train Accuracy: 0.750
Train Loss: 1.005, Train Accuracy: 0.600
Round 43
Train Loss: 1.136, Train Accuracy: 0.750
Train Loss: 0.948, Train Accuracy: 0.600
Train Loss: 0.908, Train Accuracy: 0.800
Train Loss: 1.261, Train Accuracy: 1.000
Train Loss: 1.269, Train Accuracy: 0.625
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.328, Train Accuracy: 1.000
Train Loss: 1.058, Train Accuracy: 0.600
Train Loss: 2.054, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.800
Round 44
Train Loss: 1.226, Train Accuracy: 0.750
Train Loss: 0.980, Train Accuracy: 0.500
Train Loss: 0.911, Train Accuracy: 0.600
Train Loss: 1.686, Train Accuracy: 0.800
Train Loss: 1.212, Train Accuracy: 0.750
Train Loss: 1.353, Train Accuracy: 0.800
Train Loss: 1.384, Train Accuracy: 1.000
Train Loss: 1.160, Train Accuracy: 0.600
Train Loss: 1.723, Train Accuracy: 0.750
Train Loss: 1.252, Train Accuracy: 0.600
Round 45
Train Loss: 1.293, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.500
Train Loss: 0.895, Train Accuracy: 0.400
Train Loss: 1.250, Train Accuracy: 1.000
Train Loss: 1.194, Train Accuracy: 0.875
Train Loss: 1.238, Train Accuracy: 0.800
Train Loss: 1.849, Train Accuracy: 0.750
Train Loss: 0.998, Train Accuracy: 0.600
Train Loss: 1.979, Train Accuracy: 1.000
Train Loss: 1.184, Train Accuracy: 1.000
Round 46
Train Loss: 1.155, Train Accuracy: 0.750
Train Loss: 0.943, Train Accuracy: 0.600
Train Loss: 0.900, Train Accuracy: 0.200
Train Loss: 1.275, Train Accuracy: 1.000
Train Loss: 1.157, Train Accuracy: 0.500
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.562, Train Accuracy: 1.000
Train Loss: 1.075, Train Accuracy: 1.000
Train Loss: 1.932, Train Accuracy: 0.750
Train Loss: 1.102, Train Accuracy: 0.700
Round 47
Train Loss: 1.372, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.500
Train Loss: 0.917, Train Accuracy: 0.800
Train Loss: 1.313, Train Accuracy: 1.000
Train Loss: 1.201, Train Accuracy: 0.375
Train Loss: 1.270, Train Accuracy: 0.800
Train Loss: 1.525, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.400
Train Loss: 1.765, Train Accuracy: 0.750
Train Loss: 1.148, Train Accuracy: 0.900
Round 48
Train Loss: 1.194, Train Accuracy: 0.750
Train Loss: 0.920, Train Accuracy: 0.600
Train Loss: 0.927, Train Accuracy: 0.600
Train Loss: 1.363, Train Accuracy: 0.800
Train Loss: 1.110, Train Accuracy: 0.375
Train Loss: 1.237, Train Accuracy: 0.800
Train Loss: 1.507, Train Accuracy: 1.000

(FLClient pid=2851393) 2025-04-11 09:01:39,374 - INFO - Epoch   2| Train Loss: 0.737| Train Accuracy: 0.750 [repeated 360x across cluster]
(FLClient pid=2851393) 2025-04-11 09:01:39,382 - INFO - Epoch   2| Validation Loss: 1.300, Validation Accuracy: 0.295 [repeated 120x across cluster]
(FLClient pid=2851393) 2025-04-11 09:01:44,682 - INFO - Epoch   2| Train Loss: 0.524| Train Accuracy: 0.750 [repeated 390x across cluster]
(FLClient pid=2851393) 2025-04-11 09:01:44,690 - INFO - Epoch   2| Validation Loss: 1.365, Validation Accuracy: 0.295 [repeated 130x across cluster]
(FLClient pid=2851393) 2025-04-11 09:01:49,775 - INFO - Epoch   2| Train Loss: 0.676| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2851393) 2025-04-11 09:01:49,784 - INFO - Epoch   2| Validation Loss: 1.449, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2851393) 2025-04-11 09:01:54,875 - INFO - Epoch   2| Train Loss: 0.462| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2853815) 2025-04-11 09:01:54,538 - INFO - Epoch   2| Validation Loss: 1.013, Validation Accuracy: 0.453 [repeated 149x across cluster]
(FLClient pid=2851393) 2025-04-11 09:01:59,973 - INFO - Epoch   2| Train Loss: 0.532| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2851393) 2025-04-11 09:01:59,981 - INFO - Epoch   2| Validation Loss: 1.159, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2851393) 2025-04-11 09:02:05,058 - INFO - Epoch   2| Train Loss: 0.557| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2851393) 2025-04-11 09:02:05,066 - INFO - Epoch   2| Validation Loss: 1.464, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2851393) 2025-04-11 09:02:10,148 - INFO - Epoch   2| Train Loss: 0.423| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2851393) 2025-04-11 09:02:10,156 - INFO - Epoch   2| Validation Loss: 0.927, Validation Accuracy: 0.386 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.300, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.500
Train Loss: 1.083, Train Accuracy: 0.400
Train Loss: 1.246, Train Accuracy: 0.600
Train Loss: 1.172, Train Accuracy: 0.625
Train Loss: 1.313, Train Accuracy: 0.800
Train Loss: 1.275, Train Accuracy: 0.500
Train Loss: 1.164, Train Accuracy: 0.600
Train Loss: 1.556, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.600
Round 2
Train Loss: 1.359, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.500
Train Loss: 1.059, Train Accuracy: 0.200
Train Loss: 1.304, Train Accuracy: 0.600
Train Loss: 1.178, Train Accuracy: 0.625
Train Loss: 1.339, Train Accuracy: 0.800
Train Loss: 1.306, Train Accuracy: 0.000
Train Loss: 1.180, Train Accuracy: 0.800
Train Loss: 1.673, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.400
Round 3
Train Loss: 1.395, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.500
Train Loss: 1.054, Train Accuracy: 0.000
Train Loss: 1.333, Train Accuracy: 0.600
Train Loss: 1.190, Train Accuracy: 0.625
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.384, Train Accuracy: 0.750
Train Loss: 1.158, Train Accuracy: 0.600
Train Loss: 1.741, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.500
Round 4
Train Loss: 1.295, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.500
Train Loss: 1.045, Train Accuracy: 0.400
Train Loss: 1.309, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.371, Train Accuracy: 0.800
Train Loss: 1.362, Train Accuracy: 0.500
Train Loss: 1.190, Train Accuracy: 0.400
Train Loss: 1.792, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.400
Round 5
Train Loss: 1.419, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.400
Train Loss: 1.036, Train Accuracy: 0.200
Train Loss: 1.328, Train Accuracy: 0.600
Train Loss: 1.221, Train Accuracy: 0.625
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.409, Train Accuracy: 0.500
Train Loss: 1.119, Train Accuracy: 0.200
Train Loss: 1.801, Train Accuracy: 0.750
Train Loss: 1.199, Train Accuracy: 0.500
Round 6
Train Loss: 1.354, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.400
Train Loss: 1.036, Train Accuracy: 0.400
Train Loss: 1.386, Train Accuracy: 0.600
Train Loss: 1.211, Train Accuracy: 0.625
Train Loss: 1.306, Train Accuracy: 0.800
Train Loss: 1.412, Train Accuracy: 0.500
Train Loss: 1.172, Train Accuracy: 0.400
Train Loss: 1.758, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.700
Round 7
Train Loss: 1.383, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 1.327, Train Accuracy: 0.600
Train Loss: 1.215, Train Accuracy: 0.625
Train Loss: 1.361, Train Accuracy: 0.800
Train Loss: 1.464, Train Accuracy: 0.750
Train Loss: 1.228, Train Accuracy: 0.200
Train Loss: 1.647, Train Accuracy: 0.750
Train Loss: 1.130, Train Accuracy: 0.500
Round 8
Train Loss: 1.326, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.500
Train Loss: 1.027, Train Accuracy: 0.400
Train Loss: 1.349, Train Accuracy: 0.600
Train Loss: 1.206, Train Accuracy: 0.625
Train Loss: 1.375, Train Accuracy: 0.800
Train Loss: 1.458, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.600
Train Loss: 1.763, Train Accuracy: 0.750
Train Loss: 1.112, Train Accuracy: 0.600
Round 9
Train Loss: 1.488, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.300
Train Loss: 1.043, Train Accuracy: 0.400
Train Loss: 1.381, Train Accuracy: 0.600
Train Loss: 1.221, Train Accuracy: 0.750
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.434, Train Accuracy: 0.500
Train Loss: 1.178, Train Accuracy: 0.600
Train Loss: 1.888, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.600
Round 10
Train Loss: 1.335, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.500
Train Loss: 1.015, Train Accuracy: 0.200
Train Loss: 1.369, Train Accuracy: 0.600
Train Loss: 1.261, Train Accuracy: 0.625
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.404, Train Accuracy: 0.500
Train Loss: 1.138, Train Accuracy: 0.800
Train Loss: 1.959, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.400
Round 11
Train Loss: 1.451, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.500
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.225, Train Accuracy: 0.625
Train Loss: 1.371, Train Accuracy: 0.800
Train Loss: 1.467, Train Accuracy: 0.500
Train Loss: 1.139, Train Accuracy: 0.200
Train Loss: 1.929, Train Accuracy: 0.750
Train Loss: 1.118, Train Accuracy: 0.600
Round 12
Train Loss: 1.461, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.600
Train Loss: 1.007, Train Accuracy: 0.400
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.225, Train Accuracy: 0.625
Train Loss: 1.367, Train Accuracy: 0.800
Train Loss: 1.506, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.600
Train Loss: 1.942, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.500
Round 13
Train Loss: 1.337, Train Accuracy: 0.750
Train Loss: 1.033, Train Accuracy: 0.600
Train Loss: 1.013, Train Accuracy: 0.200
Train Loss: 1.241, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.412, Train Accuracy: 0.800
Train Loss: 1.441, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.600
Train Loss: 1.805, Train Accuracy: 0.750
Train Loss: 1.127, Train Accuracy: 0.300
Round 14
Train Loss: 1.365, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.500
Train Loss: 1.003, Train Accuracy: 0.400
Train Loss: 1.350, Train Accuracy: 0.600
Train Loss: 1.247, Train Accuracy: 0.625
Train Loss: 1.369, Train Accuracy: 0.800
Train Loss: 1.483, Train Accuracy: 0.500
Train Loss: 1.151, Train Accuracy: 0.800
Train Loss: 1.989, Train Accuracy: 1.000
Train Loss: 1.142, Train Accuracy: 0.600
Round 15
Train Loss: 1.392, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.500
Train Loss: 1.003, Train Accuracy: 0.800
Train Loss: 1.404, Train Accuracy: 0.600
Train Loss: 1.252, Train Accuracy: 0.750
Train Loss: 1.314, Train Accuracy: 0.800
Train Loss: 1.440, Train Accuracy: 0.250
Train Loss: 1.192, Train Accuracy: 0.400
Train Loss: 1.769, Train Accuracy: 0.750
Train Loss: 1.111, Train Accuracy: 0.200
Round 16
Train Loss: 1.267, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.700
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.190, Train Accuracy: 0.750
Train Loss: 1.379, Train Accuracy: 0.800
Train Loss: 1.522, Train Accuracy: 0.750
Train Loss: 1.131, Train Accuracy: 0.400
Train Loss: 1.699, Train Accuracy: 0.750
Train Loss: 1.129, Train Accuracy: 0.500
Round 17
Train Loss: 1.439, Train Accuracy: 0.750
Train Loss: 1.022, Train Accuracy: 0.700
Train Loss: 0.994, Train Accuracy: 0.000
Train Loss: 1.401, Train Accuracy: 0.800
Train Loss: 1.237, Train Accuracy: 0.750
Train Loss: 1.281, Train Accuracy: 0.800
Train Loss: 1.444, Train Accuracy: 0.750
Train Loss: 1.097, Train Accuracy: 0.400
Train Loss: 1.783, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.500
Round 18
Train Loss: 1.425, Train Accuracy: 0.750
Train Loss: 1.018, Train Accuracy: 0.600
Train Loss: 0.991, Train Accuracy: 0.400
Train Loss: 1.462, Train Accuracy: 0.600
Train Loss: 1.143, Train Accuracy: 0.750
Train Loss: 1.400, Train Accuracy: 0.800
Train Loss: 1.466, Train Accuracy: 0.500
Train Loss: 1.238, Train Accuracy: 0.600
Train Loss: 1.753, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.600
Round 19
Train Loss: 1.521, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.600
Train Loss: 0.990, Train Accuracy: 0.400
Train Loss: 1.240, Train Accuracy: 0.600
Train Loss: 1.260, Train Accuracy: 0.750
Train Loss: 1.399, Train Accuracy: 0.800
Train Loss: 1.384, Train Accuracy: 0.750
Train Loss: 1.102, Train Accuracy: 0.800
Train Loss: 2.048, Train Accuracy: 0.750
Train Loss: 1.091, Train Accuracy: 0.600
Round 20
Train Loss: 1.358, Train Accuracy: 0.750
Train Loss: 1.003, Train Accuracy: 0.700
Train Loss: 0.977, Train Accuracy: 0.400
Train Loss: 1.252, Train Accuracy: 0.600
Train Loss: 1.134, Train Accuracy: 0.750
Train Loss: 1.293, Train Accuracy: 0.800
Train Loss: 1.409, Train Accuracy: 0.500
Train Loss: 1.081, Train Accuracy: 0.400
Train Loss: 1.900, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.300
Round 21
Train Loss: 1.453, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.500
Train Loss: 0.984, Train Accuracy: 0.600
Train Loss: 1.321, Train Accuracy: 0.800
Train Loss: 1.167, Train Accuracy: 0.750
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.459, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.800
Train Loss: 1.674, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.700
Round 22
Train Loss: 1.343, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.600
Train Loss: 0.976, Train Accuracy: 0.400
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.184, Train Accuracy: 0.750
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.530, Train Accuracy: 0.500
Train Loss: 1.130, Train Accuracy: 0.400
Train Loss: 1.892, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.600
Round 23
Train Loss: 1.370, Train Accuracy: 0.750
Train Loss: 1.022, Train Accuracy: 0.700
Train Loss: 0.959, Train Accuracy: 0.400
Train Loss: 1.348, Train Accuracy: 0.400
Train Loss: 1.178, Train Accuracy: 0.625
Train Loss: 1.426, Train Accuracy: 0.800
Train Loss: 1.497, Train Accuracy: 0.750
Train Loss: 1.116, Train Accuracy: 0.600
Train Loss: 1.824, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.700
Round 24
Train Loss: 1.279, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.600
Train Loss: 0.968, Train Accuracy: 0.200
Train Loss: 1.234, Train Accuracy: 0.800
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.356, Train Accuracy: 0.800
Train Loss: 1.548, Train Accuracy: 0.750
Train Loss: 1.213, Train Accuracy: 0.800
Train Loss: 2.260, Train Accuracy: 1.000
Train Loss: 1.249, Train Accuracy: 0.400
Round 25
Train Loss: 1.400, Train Accuracy: 0.750
Train Loss: 0.992, Train Accuracy: 0.700
Train Loss: 0.955, Train Accuracy: 0.200
Train Loss: 1.400, Train Accuracy: 1.000
Train Loss: 1.148, Train Accuracy: 0.750
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.505, Train Accuracy: 0.500
Train Loss: 1.169, Train Accuracy: 0.600
Train Loss: 1.866, Train Accuracy: 0.750
Train Loss: 1.106, Train Accuracy: 0.600
Round 26
Train Loss: 1.443, Train Accuracy: 0.750
Train Loss: 0.984, Train Accuracy: 0.600
Train Loss: 0.963, Train Accuracy: 0.400
Train Loss: 1.269, Train Accuracy: 0.600
Train Loss: 1.142, Train Accuracy: 0.750
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.359, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.600
Train Loss: 2.069, Train Accuracy: 1.000
Train Loss: 1.223, Train Accuracy: 0.700
Round 27
Train Loss: 1.372, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.500
Train Loss: 0.940, Train Accuracy: 0.400
Train Loss: 1.400, Train Accuracy: 0.800
Train Loss: 1.165, Train Accuracy: 0.750
Train Loss: 1.418, Train Accuracy: 0.800
Train Loss: 1.490, Train Accuracy: 0.500
Train Loss: 1.155, Train Accuracy: 0.600
Train Loss: 1.799, Train Accuracy: 0.750
Train Loss: 1.007, Train Accuracy: 0.500
Round 28
Train Loss: 1.294, Train Accuracy: 0.750
Train Loss: 0.985, Train Accuracy: 0.700
Train Loss: 0.988, Train Accuracy: 0.400
Train Loss: 1.161, Train Accuracy: 0.600
Train Loss: 1.147, Train Accuracy: 0.750
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.430, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.600
Train Loss: 1.830, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.700
Round 29
Train Loss: 1.449, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.800
Train Loss: 0.948, Train Accuracy: 0.600
Train Loss: 1.267, Train Accuracy: 1.000
Train Loss: 1.100, Train Accuracy: 0.750
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.610, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.930, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.600
Round 30
Train Loss: 1.255, Train Accuracy: 0.750
Train Loss: 0.987, Train Accuracy: 0.700
Train Loss: 0.920, Train Accuracy: 0.400
Train Loss: 1.308, Train Accuracy: 1.000
Train Loss: 1.138, Train Accuracy: 0.750
Train Loss: 1.304, Train Accuracy: 0.800
Train Loss: 1.562, Train Accuracy: 0.750
Train Loss: 1.128, Train Accuracy: 0.200
Train Loss: 1.861, Train Accuracy: 0.750
Train Loss: 1.108, Train Accuracy: 0.600
Round 31
Train Loss: 1.236, Train Accuracy: 0.500
Train Loss: 1.024, Train Accuracy: 0.500
Train Loss: 0.994, Train Accuracy: 0.600
Train Loss: 1.131, Train Accuracy: 0.800
Train Loss: 1.086, Train Accuracy: 0.750
Train Loss: 1.470, Train Accuracy: 0.800
Train Loss: 1.656, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.400
Train Loss: 1.840, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.500
Round 32
Train Loss: 1.387, Train Accuracy: 0.750
Train Loss: 0.972, Train Accuracy: 0.500
Train Loss: 0.935, Train Accuracy: 0.400
Train Loss: 1.116, Train Accuracy: 0.600
Train Loss: 1.152, Train Accuracy: 0.750
Train Loss: 1.407, Train Accuracy: 0.800
Train Loss: 1.537, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.600
Train Loss: 2.140, Train Accuracy: 1.000
Train Loss: 1.023, Train Accuracy: 0.600
Round 33
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.600
Train Loss: 0.940, Train Accuracy: 0.600
Train Loss: 1.298, Train Accuracy: 1.000
Train Loss: 1.079, Train Accuracy: 0.750
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.336, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.800
Train Loss: 1.938, Train Accuracy: 0.750
Train Loss: 1.091, Train Accuracy: 0.800
Round 34
Train Loss: 1.333, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.500
Train Loss: 0.938, Train Accuracy: 0.400
Train Loss: 1.418, Train Accuracy: 0.600
Train Loss: 1.055, Train Accuracy: 0.750
Train Loss: 1.254, Train Accuracy: 0.800
Train Loss: 1.629, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.600
Train Loss: 1.729, Train Accuracy: 0.750
Train Loss: 0.970, Train Accuracy: 0.600
Round 35
Train Loss: 1.312, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.700
Train Loss: 0.904, Train Accuracy: 0.600
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.108, Train Accuracy: 0.750
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.591, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.600
Train Loss: 1.944, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.700
Round 36
Train Loss: 1.208, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 0.925, Train Accuracy: 0.600
Train Loss: 1.135, Train Accuracy: 0.400
Train Loss: 1.098, Train Accuracy: 0.750
Train Loss: 1.246, Train Accuracy: 0.800
Train Loss: 1.354, Train Accuracy: 0.500
Train Loss: 1.040, Train Accuracy: 0.800
Train Loss: 1.848, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.500
Round 37
Train Loss: 1.306, Train Accuracy: 0.750
Train Loss: 0.945, Train Accuracy: 0.700
Train Loss: 0.899, Train Accuracy: 0.400
Train Loss: 1.259, Train Accuracy: 0.800
Train Loss: 1.140, Train Accuracy: 0.750
Train Loss: 1.315, Train Accuracy: 1.000
Train Loss: 1.722, Train Accuracy: 0.500
Train Loss: 1.059, Train Accuracy: 0.800
Train Loss: 1.825, Train Accuracy: 0.750
Train Loss: 1.139, Train Accuracy: 0.600
Round 38
Train Loss: 1.311, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 0.886, Train Accuracy: 0.400
Train Loss: 1.150, Train Accuracy: 1.000
Train Loss: 1.087, Train Accuracy: 0.875
Train Loss: 1.285, Train Accuracy: 0.800
Train Loss: 1.622, Train Accuracy: 0.500
Train Loss: 0.963, Train Accuracy: 0.400
Train Loss: 1.577, Train Accuracy: 0.750
Train Loss: 1.288, Train Accuracy: 0.400
Round 39
Train Loss: 1.142, Train Accuracy: 0.750
Train Loss: 0.944, Train Accuracy: 0.900
Train Loss: 0.960, Train Accuracy: 0.600
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.150, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.800
Train Loss: 1.305, Train Accuracy: 0.500
Train Loss: 1.023, Train Accuracy: 0.600
Train Loss: 2.026, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 0.600
Round 40
Train Loss: 1.350, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.700
Train Loss: 0.921, Train Accuracy: 0.400
Train Loss: 1.478, Train Accuracy: 0.800
Train Loss: 1.110, Train Accuracy: 0.875
Train Loss: 1.304, Train Accuracy: 0.800
Train Loss: 1.596, Train Accuracy: 0.500
Train Loss: 0.977, Train Accuracy: 0.600
Train Loss: 1.985, Train Accuracy: 0.750
Train Loss: 1.326, Train Accuracy: 0.600
Round 41
Train Loss: 1.318, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.300
Train Loss: 0.901, Train Accuracy: 0.600
Train Loss: 1.163, Train Accuracy: 1.000
Train Loss: 1.065, Train Accuracy: 0.625
Train Loss: 1.221, Train Accuracy: 0.800
Train Loss: 1.417, Train Accuracy: 1.000
Train Loss: 1.001, Train Accuracy: 0.800
Train Loss: 2.315, Train Accuracy: 1.000
Train Loss: 0.969, Train Accuracy: 0.700
Round 42
Train Loss: 1.332, Train Accuracy: 0.750
Train Loss: 0.915, Train Accuracy: 0.700
Train Loss: 0.877, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 1.000
Train Loss: 1.181, Train Accuracy: 0.750
Train Loss: 1.256, Train Accuracy: 0.800
Train Loss: 1.949, Train Accuracy: 0.750
Train Loss: 0.944, Train Accuracy: 0.400
Train Loss: 1.952, Train Accuracy: 0.750
Train Loss: 1.301, Train Accuracy: 0.500
Round 43
Train Loss: 1.238, Train Accuracy: 0.750
Train Loss: 0.918, Train Accuracy: 0.700
Train Loss: 0.881, Train Accuracy: 0.400
Train Loss: 1.268, Train Accuracy: 1.000
Train Loss: 1.079, Train Accuracy: 0.750
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.520, Train Accuracy: 0.500
Train Loss: 0.983, Train Accuracy: 0.800
Train Loss: 2.468, Train Accuracy: 1.000
Train Loss: 1.013, Train Accuracy: 0.700
Round 44
Train Loss: 1.293, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.600
Train Loss: 0.932, Train Accuracy: 0.600
Train Loss: 1.475, Train Accuracy: 0.600
Train Loss: 1.050, Train Accuracy: 0.625
Train Loss: 1.262, Train Accuracy: 0.800
Train Loss: 1.646, Train Accuracy: 0.500
Train Loss: 1.038, Train Accuracy: 0.600
Train Loss: 2.063, Train Accuracy: 1.000
Train Loss: 0.936, Train Accuracy: 0.700
Round 45
Train Loss: 1.407, Train Accuracy: 0.750
Train Loss: 0.927, Train Accuracy: 0.700
Train Loss: 0.850, Train Accuracy: 0.400
Train Loss: 1.091, Train Accuracy: 1.000
Train Loss: 1.162, Train Accuracy: 0.750
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.509, Train Accuracy: 0.500
Train Loss: 1.084, Train Accuracy: 0.800
Train Loss: 1.953, Train Accuracy: 0.750
Train Loss: 1.114, Train Accuracy: 0.400
Round 46
Train Loss: 1.433, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 0.867, Train Accuracy: 0.400
Train Loss: 1.108, Train Accuracy: 0.800
Train Loss: 1.092, Train Accuracy: 0.875
Train Loss: 1.189, Train Accuracy: 0.800
Train Loss: 1.671, Train Accuracy: 0.500
Train Loss: 0.999, Train Accuracy: 0.800
Train Loss: 1.884, Train Accuracy: 0.750
Train Loss: 0.908, Train Accuracy: 0.600
Round 47
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.500
Train Loss: 0.871, Train Accuracy: 0.800
Train Loss: 1.249, Train Accuracy: 0.600
Train Loss: 1.086, Train Accuracy: 0.875
Train Loss: 1.333, Train Accuracy: 0.800
Train Loss: 1.610, Train Accuracy: 1.000
Train Loss: 0.982, Train Accuracy: 0.800
Train Loss: 2.084, Train Accuracy: 1.000
Train Loss: 0.926, Train Accuracy: 0.800
Round 48
Train Loss: 1.179, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.600
Train Loss: 0.881, Train Accuracy: 0.600
Train Loss: 1.076, Train Accuracy: 1.000
Train Loss: 1.098, Train Accuracy: 0.750
Train Loss: 1.292, Train Accuracy: 1.000
Train Loss: 1.328, Train Accuracy: 1.000

(FLClient pid=2854535) 2025-04-11 09:02:21,468 - INFO - Epoch   2| Train Loss: 0.670| Train Accuracy: 0.750 [repeated 360x across cluster]
(FLClient pid=2854535) 2025-04-11 09:02:21,481 - INFO - Epoch   2| Validation Loss: 1.387, Validation Accuracy: 0.295 [repeated 120x across cluster]
(FLClient pid=2854536) 2025-04-11 09:02:26,679 - INFO - Epoch   0| Train Loss: 1.203| Train Accuracy: 0.300 [repeated 388x across cluster]
(FLClient pid=2854798) 2025-04-11 09:02:26,371 - INFO - Epoch   2| Validation Loss: 1.218, Validation Accuracy: 0.156 [repeated 129x across cluster]
(FLClient pid=2854535) 2025-04-11 09:02:31,834 - INFO - Epoch   2| Train Loss: 0.535| Train Accuracy: 0.750 [repeated 452x across cluster]
(FLClient pid=2854535) 2025-04-11 09:02:31,842 - INFO - Epoch   2| Validation Loss: 1.542, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2854535) 2025-04-11 09:02:36,937 - INFO - Epoch   2| Train Loss: 0.467| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2854535) 2025-04-11 09:02:36,943 - INFO - Epoch   2| Validation Loss: 1.243, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2854535) 2025-04-11 09:02:42,051 - INFO - Epoch   1| Train Loss: 0.554| Train Accuracy: 0.750 [repeated 449x across cluster]
(FLClient pid=2854798) 2025-04-11 09:02:41,725 - INFO - Epoch   2| Validation Loss: 0.956, Validation Accuracy: 0.500 [repeated 149x across cluster]
(FLClient pid=2854536) 2025-04-11 09:02:47,122 - INFO - Epoch   0| Train Loss: 0.726| Train Accuracy: 0.600 [repeated 449x across cluster]
(FLClient pid=2854535) 2025-04-11 09:02:46,817 - INFO - Epoch   2| Validation Loss: 1.262, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2854536) 2025-04-11 09:02:52,209 - INFO - Epoch   0| Train Loss: 0.607| Train Accuracy: 0.700 [repeated 450x across cluster]
(FLClient pid=2854644) 2025-04-11 09:02:51,902 - INFO - Epoch   2| Validation Loss: 1.887, Validation Accuracy: 0.294 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.387, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.065, Train Accuracy: 0.400
Train Loss: 1.193, Train Accuracy: 0.600
Train Loss: 1.179, Train Accuracy: 0.625
Train Loss: 1.343, Train Accuracy: 0.800
Train Loss: 1.346, Train Accuracy: 0.250
Train Loss: 1.156, Train Accuracy: 0.200
Train Loss: 1.419, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.400
Round 2
Train Loss: 1.326, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.051, Train Accuracy: 0.400
Train Loss: 1.252, Train Accuracy: 0.600
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.396, Train Accuracy: 0.500
Train Loss: 1.150, Train Accuracy: 0.600
Train Loss: 1.550, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.500
Round 3
Train Loss: 1.312, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.400
Train Loss: 1.306, Train Accuracy: 0.600
Train Loss: 1.234, Train Accuracy: 0.625
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.407, Train Accuracy: 0.500
Train Loss: 1.169, Train Accuracy: 0.400
Train Loss: 1.563, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.400
Round 4
Train Loss: 1.339, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.051, Train Accuracy: 0.400
Train Loss: 1.325, Train Accuracy: 0.600
Train Loss: 1.250, Train Accuracy: 0.625
Train Loss: 1.314, Train Accuracy: 0.800
Train Loss: 1.426, Train Accuracy: 0.250
Train Loss: 1.183, Train Accuracy: 0.400
Train Loss: 1.693, Train Accuracy: 0.750
Train Loss: 1.192, Train Accuracy: 0.400
Round 5
Train Loss: 1.448, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.052, Train Accuracy: 0.200
Train Loss: 1.332, Train Accuracy: 0.600
Train Loss: 1.250, Train Accuracy: 0.625
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.451, Train Accuracy: 0.500
Train Loss: 1.179, Train Accuracy: 0.600
Train Loss: 1.730, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.600
Round 6
Train Loss: 1.378, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 1.389, Train Accuracy: 0.600
Train Loss: 1.269, Train Accuracy: 0.625
Train Loss: 1.413, Train Accuracy: 0.800
Train Loss: 1.504, Train Accuracy: 0.500
Train Loss: 1.188, Train Accuracy: 0.400
Train Loss: 1.792, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.400
Round 7
Train Loss: 1.352, Train Accuracy: 0.750
Train Loss: 1.088, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 1.420, Train Accuracy: 0.600
Train Loss: 1.281, Train Accuracy: 0.625
Train Loss: 1.401, Train Accuracy: 0.800
Train Loss: 1.487, Train Accuracy: 0.500
Train Loss: 1.168, Train Accuracy: 0.400
Train Loss: 1.795, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.600
Round 8
Train Loss: 1.474, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.500
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 1.401, Train Accuracy: 0.600
Train Loss: 1.270, Train Accuracy: 0.625
Train Loss: 1.302, Train Accuracy: 0.800
Train Loss: 1.484, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.400
Train Loss: 1.829, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.400
Round 9
Train Loss: 1.441, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.032, Train Accuracy: 0.400
Train Loss: 1.395, Train Accuracy: 0.600
Train Loss: 1.261, Train Accuracy: 0.625
Train Loss: 1.458, Train Accuracy: 0.800
Train Loss: 1.509, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.400
Train Loss: 1.857, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.400
Round 10
Train Loss: 1.366, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.600
Train Loss: 1.027, Train Accuracy: 0.400
Train Loss: 1.383, Train Accuracy: 0.600
Train Loss: 1.287, Train Accuracy: 0.625
Train Loss: 1.383, Train Accuracy: 0.800
Train Loss: 1.534, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.400
Train Loss: 1.814, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.600
Round 11
Train Loss: 1.381, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.600
Train Loss: 1.024, Train Accuracy: 0.400
Train Loss: 1.379, Train Accuracy: 0.600
Train Loss: 1.267, Train Accuracy: 0.625
Train Loss: 1.400, Train Accuracy: 0.800
Train Loss: 1.543, Train Accuracy: 0.750
Train Loss: 1.130, Train Accuracy: 0.600
Train Loss: 1.860, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.700
Round 12
Train Loss: 1.317, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.800
Train Loss: 1.408, Train Accuracy: 0.600
Train Loss: 1.274, Train Accuracy: 0.625
Train Loss: 1.307, Train Accuracy: 0.800
Train Loss: 1.603, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.200
Train Loss: 1.872, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.600
Round 13
Train Loss: 1.492, Train Accuracy: 0.750
Train Loss: 1.062, Train Accuracy: 0.600
Train Loss: 1.008, Train Accuracy: 0.400
Train Loss: 1.470, Train Accuracy: 0.600
Train Loss: 1.213, Train Accuracy: 0.750
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.533, Train Accuracy: 0.500
Train Loss: 1.180, Train Accuracy: 0.600
Train Loss: 1.835, Train Accuracy: 0.750
Train Loss: 1.218, Train Accuracy: 0.600
Round 14
Train Loss: 1.354, Train Accuracy: 0.750
Train Loss: 1.062, Train Accuracy: 0.600
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 1.407, Train Accuracy: 0.600
Train Loss: 1.289, Train Accuracy: 0.625
Train Loss: 1.390, Train Accuracy: 0.800
Train Loss: 1.591, Train Accuracy: 0.500
Train Loss: 1.102, Train Accuracy: 0.400
Train Loss: 1.952, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.500
Round 15
Train Loss: 1.503, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.400
Train Loss: 1.004, Train Accuracy: 0.400
Train Loss: 1.452, Train Accuracy: 0.600
Train Loss: 1.256, Train Accuracy: 0.625
Train Loss: 1.446, Train Accuracy: 0.800
Train Loss: 1.535, Train Accuracy: 0.750
Train Loss: 1.205, Train Accuracy: 0.400
Train Loss: 1.833, Train Accuracy: 0.750
Train Loss: 1.125, Train Accuracy: 0.400
Round 16
Train Loss: 1.404, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 0.999, Train Accuracy: 0.600
Train Loss: 1.449, Train Accuracy: 0.600
Train Loss: 1.214, Train Accuracy: 0.750
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.600, Train Accuracy: 0.750
Train Loss: 1.256, Train Accuracy: 0.400
Train Loss: 1.928, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.600
Round 17
Train Loss: 1.408, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.700
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.401, Train Accuracy: 0.600
Train Loss: 1.199, Train Accuracy: 0.625
Train Loss: 1.362, Train Accuracy: 0.800
Train Loss: 1.516, Train Accuracy: 0.750
Train Loss: 1.090, Train Accuracy: 0.600
Train Loss: 1.906, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.300
Round 18
Train Loss: 1.365, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.600
Train Loss: 0.991, Train Accuracy: 0.400
Train Loss: 1.440, Train Accuracy: 0.600
Train Loss: 1.292, Train Accuracy: 0.625
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.537, Train Accuracy: 1.000
Train Loss: 1.146, Train Accuracy: 0.400
Train Loss: 1.924, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.400
Round 19
Train Loss: 1.280, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.700
Train Loss: 0.985, Train Accuracy: 0.600
Train Loss: 1.419, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.750
Train Loss: 1.413, Train Accuracy: 0.800
Train Loss: 1.597, Train Accuracy: 1.000
Train Loss: 1.114, Train Accuracy: 0.400
Train Loss: 1.865, Train Accuracy: 0.750
Train Loss: 1.131, Train Accuracy: 0.600
Round 20
Train Loss: 1.438, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.700
Train Loss: 0.997, Train Accuracy: 0.600
Train Loss: 1.468, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.625
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.510, Train Accuracy: 0.750
Train Loss: 1.258, Train Accuracy: 0.400
Train Loss: 1.941, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Round 21
Train Loss: 1.352, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.700
Train Loss: 0.979, Train Accuracy: 0.600
Train Loss: 1.394, Train Accuracy: 0.600
Train Loss: 1.192, Train Accuracy: 0.625
Train Loss: 1.307, Train Accuracy: 0.800
Train Loss: 1.540, Train Accuracy: 0.750
Train Loss: 1.107, Train Accuracy: 0.400
Train Loss: 1.851, Train Accuracy: 0.750
Train Loss: 1.113, Train Accuracy: 0.700
Round 22
Train Loss: 1.292, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.500
Train Loss: 0.981, Train Accuracy: 0.200
Train Loss: 1.419, Train Accuracy: 0.600
Train Loss: 1.220, Train Accuracy: 0.625
Train Loss: 1.457, Train Accuracy: 0.800
Train Loss: 1.585, Train Accuracy: 0.500
Train Loss: 1.161, Train Accuracy: 0.600
Train Loss: 2.115, Train Accuracy: 0.750
Train Loss: 1.121, Train Accuracy: 0.400
Round 23
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.700
Train Loss: 0.976, Train Accuracy: 0.600
Train Loss: 1.361, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 0.625
Train Loss: 1.348, Train Accuracy: 0.800
Train Loss: 1.496, Train Accuracy: 1.000
Train Loss: 1.095, Train Accuracy: 0.800
Train Loss: 2.105, Train Accuracy: 1.000
Train Loss: 1.139, Train Accuracy: 0.700
Round 24
Train Loss: 1.193, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.700
Train Loss: 0.970, Train Accuracy: 0.400
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.223, Train Accuracy: 0.750
Train Loss: 1.324, Train Accuracy: 0.800
Train Loss: 1.513, Train Accuracy: 0.750
Train Loss: 1.123, Train Accuracy: 0.600
Train Loss: 1.925, Train Accuracy: 0.750
Train Loss: 1.100, Train Accuracy: 0.300
Round 25
Train Loss: 1.260, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.600
Train Loss: 0.974, Train Accuracy: 0.400
Train Loss: 1.395, Train Accuracy: 0.800
Train Loss: 1.192, Train Accuracy: 0.750
Train Loss: 1.399, Train Accuracy: 0.800
Train Loss: 1.629, Train Accuracy: 0.500
Train Loss: 1.206, Train Accuracy: 0.800
Train Loss: 2.089, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.600
Round 26
Train Loss: 1.352, Train Accuracy: 0.750
Train Loss: 1.017, Train Accuracy: 0.400
Train Loss: 0.967, Train Accuracy: 0.800
Train Loss: 1.432, Train Accuracy: 0.800
Train Loss: 1.152, Train Accuracy: 0.750
Train Loss: 1.436, Train Accuracy: 0.800
Train Loss: 1.529, Train Accuracy: 1.000
Train Loss: 1.158, Train Accuracy: 0.600
Train Loss: 1.860, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.800
Round 27
Train Loss: 1.385, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.300
Train Loss: 0.955, Train Accuracy: 0.600
Train Loss: 1.264, Train Accuracy: 0.800
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.464, Train Accuracy: 0.800
Train Loss: 1.538, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.800
Train Loss: 1.868, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.600
Round 28
Train Loss: 1.393, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.400
Train Loss: 0.943, Train Accuracy: 0.400
Train Loss: 1.412, Train Accuracy: 0.800
Train Loss: 1.209, Train Accuracy: 0.750
Train Loss: 1.322, Train Accuracy: 0.800
Train Loss: 1.521, Train Accuracy: 1.000
Train Loss: 1.111, Train Accuracy: 0.800
Train Loss: 2.036, Train Accuracy: 0.750
Train Loss: 1.118, Train Accuracy: 0.600
Round 29
Train Loss: 1.542, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.700
Train Loss: 0.940, Train Accuracy: 0.600
Train Loss: 1.314, Train Accuracy: 0.600
Train Loss: 1.174, Train Accuracy: 0.750
Train Loss: 1.243, Train Accuracy: 0.800
Train Loss: 1.540, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.400
Train Loss: 2.131, Train Accuracy: 0.750
Train Loss: 0.998, Train Accuracy: 0.500
Round 30
Train Loss: 1.326, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.500
Train Loss: 0.936, Train Accuracy: 0.600
Train Loss: 1.448, Train Accuracy: 1.000
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.382, Train Accuracy: 0.800
Train Loss: 1.540, Train Accuracy: 0.750
Train Loss: 1.125, Train Accuracy: 0.600
Train Loss: 1.804, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.900
Round 31
Train Loss: 1.405, Train Accuracy: 0.500
Train Loss: 0.989, Train Accuracy: 0.600
Train Loss: 0.930, Train Accuracy: 0.400
Train Loss: 1.369, Train Accuracy: 0.800
Train Loss: 1.079, Train Accuracy: 0.750
Train Loss: 1.586, Train Accuracy: 1.000
Train Loss: 1.617, Train Accuracy: 0.500
Train Loss: 1.034, Train Accuracy: 0.400
Train Loss: 1.882, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.500
Round 32
Train Loss: 1.279, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 0.946, Train Accuracy: 0.600
Train Loss: 1.268, Train Accuracy: 0.600
Train Loss: 1.138, Train Accuracy: 0.750
Train Loss: 1.295, Train Accuracy: 0.800
Train Loss: 1.610, Train Accuracy: 1.000
Train Loss: 1.035, Train Accuracy: 0.200
Train Loss: 1.942, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.700
Round 33
Train Loss: 1.295, Train Accuracy: 0.750
Train Loss: 1.013, Train Accuracy: 0.500
Train Loss: 0.967, Train Accuracy: 0.200
Train Loss: 1.321, Train Accuracy: 1.000
Train Loss: 1.179, Train Accuracy: 0.625
Train Loss: 1.410, Train Accuracy: 1.000
Train Loss: 1.393, Train Accuracy: 0.500
Train Loss: 1.008, Train Accuracy: 0.400
Train Loss: 2.159, Train Accuracy: 1.000
Train Loss: 1.086, Train Accuracy: 0.600
Round 34
Train Loss: 1.427, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.700
Train Loss: 0.934, Train Accuracy: 0.400
Train Loss: 1.441, Train Accuracy: 1.000
Train Loss: 1.200, Train Accuracy: 0.750
Train Loss: 1.226, Train Accuracy: 0.800
Train Loss: 1.602, Train Accuracy: 0.500
Train Loss: 1.051, Train Accuracy: 0.600
Train Loss: 1.882, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.800
Round 35
Train Loss: 1.318, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.600
Train Loss: 0.902, Train Accuracy: 0.400
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.141, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.800
Train Loss: 1.559, Train Accuracy: 0.500
Train Loss: 0.976, Train Accuracy: 0.600
Train Loss: 1.902, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.600
Round 36
Train Loss: 1.516, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.700
Train Loss: 0.923, Train Accuracy: 0.600
Train Loss: 1.255, Train Accuracy: 0.600
Train Loss: 1.137, Train Accuracy: 0.875
Train Loss: 1.273, Train Accuracy: 0.800
Train Loss: 1.611, Train Accuracy: 0.500
Train Loss: 1.088, Train Accuracy: 1.000
Train Loss: 1.965, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 0.600
Round 37
Train Loss: 1.482, Train Accuracy: 0.500
Train Loss: 0.969, Train Accuracy: 0.500
Train Loss: 0.913, Train Accuracy: 0.600
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.069, Train Accuracy: 0.750
Train Loss: 1.348, Train Accuracy: 0.800
Train Loss: 1.637, Train Accuracy: 0.500
Train Loss: 1.042, Train Accuracy: 0.600
Train Loss: 2.050, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.600
Round 38
Train Loss: 1.201, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.700
Train Loss: 0.925, Train Accuracy: 0.600
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.099, Train Accuracy: 0.750
Train Loss: 1.358, Train Accuracy: 0.800
Train Loss: 1.682, Train Accuracy: 0.750
Train Loss: 0.978, Train Accuracy: 0.400
Train Loss: 2.113, Train Accuracy: 0.750
Train Loss: 1.113, Train Accuracy: 0.500
Round 39
Train Loss: 1.474, Train Accuracy: 0.750
Train Loss: 0.950, Train Accuracy: 0.700
Train Loss: 0.915, Train Accuracy: 0.400
Train Loss: 1.377, Train Accuracy: 1.000
Train Loss: 1.167, Train Accuracy: 0.750
Train Loss: 1.408, Train Accuracy: 0.800
Train Loss: 1.536, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 1.000
Train Loss: 1.716, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.700
Round 40
Train Loss: 1.366, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.600
Train Loss: 0.896, Train Accuracy: 0.600
Train Loss: 1.407, Train Accuracy: 0.800
Train Loss: 1.095, Train Accuracy: 0.875
Train Loss: 1.486, Train Accuracy: 0.800
Train Loss: 1.609, Train Accuracy: 0.500
Train Loss: 0.964, Train Accuracy: 0.600
Train Loss: 2.197, Train Accuracy: 1.000
Train Loss: 1.146, Train Accuracy: 0.600
Round 41
Train Loss: 1.125, Train Accuracy: 0.750
Train Loss: 0.981, Train Accuracy: 0.500
Train Loss: 0.884, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 1.000
Train Loss: 1.076, Train Accuracy: 0.625
Train Loss: 1.277, Train Accuracy: 0.600
Train Loss: 1.625, Train Accuracy: 0.500
Train Loss: 0.998, Train Accuracy: 0.800
Train Loss: 1.891, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.700
Round 42
Train Loss: 1.278, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.500
Train Loss: 0.902, Train Accuracy: 0.600
Train Loss: 1.647, Train Accuracy: 0.800
Train Loss: 1.116, Train Accuracy: 0.750
Train Loss: 1.359, Train Accuracy: 0.800
Train Loss: 1.769, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.800
Train Loss: 1.953, Train Accuracy: 0.750
Train Loss: 0.936, Train Accuracy: 0.600
Round 43
Train Loss: 1.225, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.400
Train Loss: 0.881, Train Accuracy: 0.800
Train Loss: 1.445, Train Accuracy: 0.800
Train Loss: 1.151, Train Accuracy: 0.750
Train Loss: 1.257, Train Accuracy: 0.800
Train Loss: 1.549, Train Accuracy: 1.000
Train Loss: 1.068, Train Accuracy: 0.600
Train Loss: 2.024, Train Accuracy: 0.750
Train Loss: 1.030, Train Accuracy: 0.700
Round 44
Train Loss: 1.243, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 0.868, Train Accuracy: 0.600
Train Loss: 1.520, Train Accuracy: 0.800
Train Loss: 1.111, Train Accuracy: 0.875
Train Loss: 1.382, Train Accuracy: 0.800
Train Loss: 1.655, Train Accuracy: 0.750
Train Loss: 1.132, Train Accuracy: 0.800
Train Loss: 1.629, Train Accuracy: 0.750
Train Loss: 1.307, Train Accuracy: 0.600
Round 45
Train Loss: 1.173, Train Accuracy: 0.750
Train Loss: 0.940, Train Accuracy: 0.700
Train Loss: 0.879, Train Accuracy: 0.600
Train Loss: 1.172, Train Accuracy: 1.000
Train Loss: 1.092, Train Accuracy: 0.875
Train Loss: 1.248, Train Accuracy: 0.800
Train Loss: 1.596, Train Accuracy: 1.000
Train Loss: 1.110, Train Accuracy: 0.600
Train Loss: 1.701, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.900
Round 46
Train Loss: 1.149, Train Accuracy: 0.750
Train Loss: 0.956, Train Accuracy: 0.600
Train Loss: 0.887, Train Accuracy: 0.600
Train Loss: 1.413, Train Accuracy: 1.000
Train Loss: 1.072, Train Accuracy: 0.625
Train Loss: 1.256, Train Accuracy: 0.800
Train Loss: 1.641, Train Accuracy: 0.500
Train Loss: 1.046, Train Accuracy: 0.800
Train Loss: 1.651, Train Accuracy: 0.750
Train Loss: 0.967, Train Accuracy: 0.800
Round 47
Train Loss: 1.025, Train Accuracy: 0.750
Train Loss: 0.928, Train Accuracy: 0.600
Train Loss: 0.929, Train Accuracy: 0.400
Train Loss: 1.242, Train Accuracy: 0.800
Train Loss: 1.190, Train Accuracy: 0.875
Train Loss: 1.244, Train Accuracy: 0.800
Train Loss: 1.896, Train Accuracy: 0.750
Train Loss: 0.968, Train Accuracy: 0.400
Train Loss: 1.777, Train Accuracy: 0.750
Train Loss: 1.278, Train Accuracy: 0.500
Round 48
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 0.910, Train Accuracy: 0.500
Train Loss: 0.927, Train Accuracy: 0.600
Train Loss: 1.672, Train Accuracy: 0.600
Train Loss: 0.990, Train Accuracy: 0.875
Train Loss: 1.160, Train Accuracy: 0.800
Train Loss: 1.636, Train Accuracy: 0.500

(FLClient pid=2855526) 2025-04-11 09:03:03,805 - INFO - Epoch   2| Train Loss: 0.730| Train Accuracy: 0.750 [repeated 362x across cluster]
(FLClient pid=2855526) 2025-04-11 09:03:03,814 - INFO - Epoch   2| Validation Loss: 1.281, Validation Accuracy: 0.295 [repeated 121x across cluster]
(FLClient pid=2855526) 2025-04-11 09:03:09,028 - INFO - Epoch   2| Train Loss: 0.607| Train Accuracy: 0.750 [repeated 420x across cluster]
(FLClient pid=2855526) 2025-04-11 09:03:09,033 - INFO - Epoch   2| Validation Loss: 1.433, Validation Accuracy: 0.295 [repeated 140x across cluster]
(FLClient pid=2855526) 2025-04-11 09:03:14,125 - INFO - Epoch   2| Train Loss: 0.517| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2855526) 2025-04-11 09:03:14,133 - INFO - Epoch   2| Validation Loss: 1.191, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2855526) 2025-04-11 09:03:19,201 - INFO - Epoch   0| Train Loss: 1.081| Train Accuracy: 0.500 [repeated 448x across cluster]
(FLClient pid=2855740) 2025-04-11 09:03:18,894 - INFO - Epoch   2| Validation Loss: 1.093, Validation Accuracy: 0.312 [repeated 149x across cluster]
(FLClient pid=2855526) 2025-04-11 09:03:24,309 - INFO - Epoch   0| Train Loss: 0.895| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2855527) 2025-04-11 09:03:24,002 - INFO - Epoch   2| Validation Loss: 0.950, Validation Accuracy: 0.467 [repeated 150x across cluster]
(FLClient pid=2855526) 2025-04-11 09:03:29,444 - INFO - Epoch   2| Train Loss: 0.534| Train Accuracy: 0.750 [repeated 452x across cluster]
(FLClient pid=2855526) 2025-04-11 09:03:29,452 - INFO - Epoch   2| Validation Loss: 1.268, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2855526) 2025-04-11 09:03:34,534 - INFO - Epoch   2| Train Loss: 0.517| Train Accuracy: 0.500 [repeated 450x across cluster]
(FLClient pid=2855740) 2025-04-11 09:03:34,201 - INFO - Epoch   2| Validation Loss: 0.869, Validation Accuracy: 0.422 [repeated 149x across cluster]

Training done
Round 1
Train Loss: 1.281, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.058, Train Accuracy: 0.200
Train Loss: 1.281, Train Accuracy: 0.600
Train Loss: 1.221, Train Accuracy: 0.625
Train Loss: 1.259, Train Accuracy: 0.800
Train Loss: 1.310, Train Accuracy: 0.250
Train Loss: 1.140, Train Accuracy: 0.200
Train Loss: 1.573, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.500
Round 2
Train Loss: 1.302, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.500
Train Loss: 1.051, Train Accuracy: 0.400
Train Loss: 1.340, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.246, Train Accuracy: 0.800
Train Loss: 1.377, Train Accuracy: 0.250
Train Loss: 1.154, Train Accuracy: 0.200
Train Loss: 1.633, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.600
Round 3
Train Loss: 1.361, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.045, Train Accuracy: 0.200
Train Loss: 1.327, Train Accuracy: 0.600
Train Loss: 1.232, Train Accuracy: 0.625
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.410, Train Accuracy: 0.500
Train Loss: 1.179, Train Accuracy: 0.600
Train Loss: 1.694, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.500
Round 4
Train Loss: 1.285, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.043, Train Accuracy: 0.400
Train Loss: 1.368, Train Accuracy: 0.600
Train Loss: 1.264, Train Accuracy: 0.625
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.454, Train Accuracy: 0.750
Train Loss: 1.175, Train Accuracy: 0.400
Train Loss: 1.727, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.400
Round 5
Train Loss: 1.408, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.600
Train Loss: 1.028, Train Accuracy: 0.800
Train Loss: 1.430, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.625
Train Loss: 1.283, Train Accuracy: 0.800
Train Loss: 1.495, Train Accuracy: 0.250
Train Loss: 1.203, Train Accuracy: 0.400
Train Loss: 1.759, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.700
Round 6
Train Loss: 1.342, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.700
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.410, Train Accuracy: 0.600
Train Loss: 1.268, Train Accuracy: 0.625
Train Loss: 1.360, Train Accuracy: 0.800
Train Loss: 1.521, Train Accuracy: 0.500
Train Loss: 1.156, Train Accuracy: 0.400
Train Loss: 1.877, Train Accuracy: 0.750
Train Loss: 1.175, Train Accuracy: 0.200
Round 7
Train Loss: 1.325, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.400
Train Loss: 1.026, Train Accuracy: 0.000
Train Loss: 1.413, Train Accuracy: 0.600
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 0.500
Train Loss: 1.198, Train Accuracy: 0.600
Train Loss: 1.803, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.400
Round 8
Train Loss: 1.271, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.400
Train Loss: 1.015, Train Accuracy: 0.400
Train Loss: 1.464, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.339, Train Accuracy: 0.800
Train Loss: 1.527, Train Accuracy: 0.750
Train Loss: 1.215, Train Accuracy: 0.600
Train Loss: 1.868, Train Accuracy: 0.750
Train Loss: 1.123, Train Accuracy: 0.500
Round 9
Train Loss: 1.323, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.500
Train Loss: 1.019, Train Accuracy: 0.400
Train Loss: 1.347, Train Accuracy: 0.600
Train Loss: 1.275, Train Accuracy: 0.625
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 0.500
Train Loss: 1.208, Train Accuracy: 0.600
Train Loss: 1.766, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.600
Round 10
Train Loss: 1.238, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.500
Train Loss: 1.012, Train Accuracy: 0.400
Train Loss: 1.416, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.478, Train Accuracy: 0.500
Train Loss: 1.131, Train Accuracy: 0.200
Train Loss: 1.905, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.400
Round 11
Train Loss: 1.430, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.700
Train Loss: 1.006, Train Accuracy: 0.200
Train Loss: 1.388, Train Accuracy: 0.600
Train Loss: 1.258, Train Accuracy: 0.625
Train Loss: 1.361, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 0.500
Train Loss: 1.104, Train Accuracy: 0.400
Train Loss: 1.809, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.500
Round 12
Train Loss: 1.452, Train Accuracy: 1.000
Train Loss: 1.061, Train Accuracy: 0.600
Train Loss: 1.001, Train Accuracy: 0.400
Train Loss: 1.392, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.625
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.659, Train Accuracy: 0.500
Train Loss: 1.177, Train Accuracy: 0.400
Train Loss: 1.878, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.600
Round 13
Train Loss: 1.280, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.500
Train Loss: 1.000, Train Accuracy: 0.800
Train Loss: 1.425, Train Accuracy: 0.600
Train Loss: 1.248, Train Accuracy: 0.625
Train Loss: 1.363, Train Accuracy: 0.800
Train Loss: 1.574, Train Accuracy: 0.500
Train Loss: 1.202, Train Accuracy: 0.600
Train Loss: 1.798, Train Accuracy: 0.750
Train Loss: 1.229, Train Accuracy: 0.800
Round 14
Train Loss: 1.335, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.500
Train Loss: 0.997, Train Accuracy: 0.400
Train Loss: 1.467, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.384, Train Accuracy: 0.800
Train Loss: 1.527, Train Accuracy: 0.500
Train Loss: 1.148, Train Accuracy: 0.400
Train Loss: 1.943, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.600
Round 15
Train Loss: 1.433, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 1.002, Train Accuracy: 0.600
Train Loss: 1.471, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.750
Train Loss: 1.296, Train Accuracy: 0.800
Train Loss: 1.521, Train Accuracy: 0.500
Train Loss: 1.122, Train Accuracy: 0.800
Train Loss: 1.963, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.500
Round 16
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.500
Train Loss: 0.988, Train Accuracy: 0.400
Train Loss: 1.499, Train Accuracy: 0.800
Train Loss: 1.232, Train Accuracy: 0.750
Train Loss: 1.346, Train Accuracy: 0.800
Train Loss: 1.648, Train Accuracy: 1.000
Train Loss: 1.122, Train Accuracy: 0.400
Train Loss: 1.891, Train Accuracy: 0.750
Train Loss: 1.097, Train Accuracy: 0.400
Round 17
Train Loss: 1.361, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.400
Train Loss: 0.998, Train Accuracy: 0.600
Train Loss: 1.470, Train Accuracy: 0.600
Train Loss: 1.180, Train Accuracy: 0.625
Train Loss: 1.272, Train Accuracy: 0.800
Train Loss: 1.591, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.600
Train Loss: 2.080, Train Accuracy: 0.750
Train Loss: 1.214, Train Accuracy: 0.700
Round 18
Train Loss: 1.255, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.700
Train Loss: 0.991, Train Accuracy: 0.400
Train Loss: 1.519, Train Accuracy: 0.600
Train Loss: 1.151, Train Accuracy: 0.750
Train Loss: 1.402, Train Accuracy: 0.800
Train Loss: 1.580, Train Accuracy: 0.500
Train Loss: 1.075, Train Accuracy: 0.800
Train Loss: 1.883, Train Accuracy: 0.750
Train Loss: 1.129, Train Accuracy: 0.600
Round 19
Train Loss: 1.273, Train Accuracy: 0.750
Train Loss: 1.020, Train Accuracy: 0.600
Train Loss: 0.972, Train Accuracy: 0.600
Train Loss: 1.312, Train Accuracy: 0.600
Train Loss: 1.153, Train Accuracy: 0.750
Train Loss: 1.270, Train Accuracy: 0.800
Train Loss: 1.501, Train Accuracy: 1.000
Train Loss: 1.117, Train Accuracy: 0.400
Train Loss: 1.805, Train Accuracy: 0.750
Train Loss: 1.124, Train Accuracy: 0.400
Round 20
Train Loss: 1.297, Train Accuracy: 0.750
Train Loss: 1.025, Train Accuracy: 0.600
Train Loss: 0.982, Train Accuracy: 0.400
Train Loss: 1.399, Train Accuracy: 0.600
Train Loss: 1.180, Train Accuracy: 0.750
Train Loss: 1.401, Train Accuracy: 0.800
Train Loss: 1.530, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.400
Train Loss: 1.978, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.700
Round 21
Train Loss: 1.477, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.600
Train Loss: 0.984, Train Accuracy: 0.400
Train Loss: 1.411, Train Accuracy: 0.600
Train Loss: 1.174, Train Accuracy: 0.625
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.654, Train Accuracy: 0.500
Train Loss: 1.102, Train Accuracy: 0.800
Train Loss: 2.167, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.600
Round 22
Train Loss: 1.382, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.500
Train Loss: 0.987, Train Accuracy: 0.400
Train Loss: 1.366, Train Accuracy: 0.800
Train Loss: 1.168, Train Accuracy: 0.750
Train Loss: 1.400, Train Accuracy: 0.800
Train Loss: 1.555, Train Accuracy: 1.000
Train Loss: 1.100, Train Accuracy: 0.800
Train Loss: 1.822, Train Accuracy: 0.750
Train Loss: 1.128, Train Accuracy: 0.500
Round 23
Train Loss: 1.342, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.500
Train Loss: 0.973, Train Accuracy: 0.400
Train Loss: 1.395, Train Accuracy: 0.800
Train Loss: 1.155, Train Accuracy: 0.500
Train Loss: 1.313, Train Accuracy: 0.800
Train Loss: 1.593, Train Accuracy: 0.500
Train Loss: 1.094, Train Accuracy: 0.800
Train Loss: 1.903, Train Accuracy: 0.750
Train Loss: 1.108, Train Accuracy: 0.500
Round 24
Train Loss: 1.338, Train Accuracy: 0.750
Train Loss: 1.003, Train Accuracy: 0.600
Train Loss: 0.952, Train Accuracy: 0.800
Train Loss: 1.465, Train Accuracy: 0.800
Train Loss: 1.175, Train Accuracy: 0.750
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.557, Train Accuracy: 0.500
Train Loss: 1.076, Train Accuracy: 0.400
Train Loss: 2.075, Train Accuracy: 0.750
Train Loss: 1.110, Train Accuracy: 0.600
Round 25
Train Loss: 1.399, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.500
Train Loss: 0.946, Train Accuracy: 0.400
Train Loss: 1.224, Train Accuracy: 0.600
Train Loss: 1.113, Train Accuracy: 0.625
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.564, Train Accuracy: 1.000
Train Loss: 1.057, Train Accuracy: 0.600
Train Loss: 2.049, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.600
Round 26
Train Loss: 1.295, Train Accuracy: 0.750
Train Loss: 0.996, Train Accuracy: 0.500
Train Loss: 0.964, Train Accuracy: 0.600
Train Loss: 1.457, Train Accuracy: 1.000
Train Loss: 1.148, Train Accuracy: 0.750
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.602, Train Accuracy: 1.000
Train Loss: 1.146, Train Accuracy: 0.800
Train Loss: 1.951, Train Accuracy: 0.750
Train Loss: 1.203, Train Accuracy: 0.500
Round 27
Train Loss: 1.309, Train Accuracy: 0.750
Train Loss: 1.013, Train Accuracy: 0.500
Train Loss: 0.938, Train Accuracy: 0.600
Train Loss: 1.359, Train Accuracy: 0.800
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.522, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.600
Train Loss: 2.171, Train Accuracy: 0.750
Train Loss: 1.116, Train Accuracy: 0.600
Round 28
Train Loss: 1.282, Train Accuracy: 0.750
Train Loss: 0.984, Train Accuracy: 0.700
Train Loss: 0.928, Train Accuracy: 0.600
Train Loss: 1.437, Train Accuracy: 1.000
Train Loss: 1.145, Train Accuracy: 0.750
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.589, Train Accuracy: 0.500
Train Loss: 1.048, Train Accuracy: 0.600
Train Loss: 1.902, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.400
Round 29
Train Loss: 1.221, Train Accuracy: 0.750
Train Loss: 1.020, Train Accuracy: 0.200
Train Loss: 0.944, Train Accuracy: 1.000
Train Loss: 1.404, Train Accuracy: 1.000
Train Loss: 1.152, Train Accuracy: 0.750
Train Loss: 1.359, Train Accuracy: 0.800
Train Loss: 1.503, Train Accuracy: 1.000
Train Loss: 1.070, Train Accuracy: 0.600
Train Loss: 2.179, Train Accuracy: 1.000
Train Loss: 1.061, Train Accuracy: 0.800
Round 30
Train Loss: 1.191, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.700
Train Loss: 0.923, Train Accuracy: 0.600
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.212, Train Accuracy: 0.750
Train Loss: 1.359, Train Accuracy: 0.800
Train Loss: 1.433, Train Accuracy: 0.750
Train Loss: 1.098, Train Accuracy: 0.800
Train Loss: 2.199, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.700
Round 31
Train Loss: 1.233, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.600
Train Loss: 0.923, Train Accuracy: 0.600
Train Loss: 1.352, Train Accuracy: 0.600
Train Loss: 1.112, Train Accuracy: 0.750
Train Loss: 1.336, Train Accuracy: 0.800
Train Loss: 1.528, Train Accuracy: 0.500
Train Loss: 1.109, Train Accuracy: 0.600
Train Loss: 1.841, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.700
Round 32
Train Loss: 1.240, Train Accuracy: 0.500
Train Loss: 0.966, Train Accuracy: 0.800
Train Loss: 0.912, Train Accuracy: 0.400
Train Loss: 1.304, Train Accuracy: 1.000
Train Loss: 1.122, Train Accuracy: 0.875
Train Loss: 1.356, Train Accuracy: 0.800
Train Loss: 1.559, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.800
Train Loss: 2.079, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.400
Round 33
Train Loss: 1.257, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.600
Train Loss: 0.916, Train Accuracy: 0.600
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.087, Train Accuracy: 0.750
Train Loss: 1.336, Train Accuracy: 0.800
Train Loss: 1.711, Train Accuracy: 0.500
Train Loss: 0.987, Train Accuracy: 0.600
Train Loss: 1.917, Train Accuracy: 0.750
Train Loss: 1.122, Train Accuracy: 0.500
Round 34
Train Loss: 1.421, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.500
Train Loss: 0.895, Train Accuracy: 0.400
Train Loss: 1.396, Train Accuracy: 1.000
Train Loss: 1.100, Train Accuracy: 0.875
Train Loss: 1.288, Train Accuracy: 0.800
Train Loss: 1.482, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.800
Train Loss: 2.011, Train Accuracy: 1.000
Train Loss: 1.138, Train Accuracy: 0.800
Round 35
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 0.968, Train Accuracy: 0.800
Train Loss: 0.917, Train Accuracy: 0.600
Train Loss: 1.398, Train Accuracy: 0.800
Train Loss: 1.072, Train Accuracy: 0.875
Train Loss: 1.372, Train Accuracy: 0.800
Train Loss: 1.427, Train Accuracy: 1.000
Train Loss: 1.031, Train Accuracy: 0.600
Train Loss: 2.042, Train Accuracy: 1.000
Train Loss: 1.084, Train Accuracy: 0.600
Round 36
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.600
Train Loss: 0.896, Train Accuracy: 0.800
Train Loss: 1.360, Train Accuracy: 1.000
Train Loss: 1.176, Train Accuracy: 0.625
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.614, Train Accuracy: 0.750
Train Loss: 1.022, Train Accuracy: 0.800
Train Loss: 1.760, Train Accuracy: 0.750
Train Loss: 1.107, Train Accuracy: 0.800
Round 37
Train Loss: 1.395, Train Accuracy: 1.000
Train Loss: 0.981, Train Accuracy: 0.300
Train Loss: 0.919, Train Accuracy: 0.600
Train Loss: 1.209, Train Accuracy: 0.600
Train Loss: 1.121, Train Accuracy: 0.375
Train Loss: 1.335, Train Accuracy: 0.800
Train Loss: 1.863, Train Accuracy: 0.750
Train Loss: 1.380, Train Accuracy: 0.800
Train Loss: 2.186, Train Accuracy: 1.000
Train Loss: 1.192, Train Accuracy: 0.700
Round 38
Train Loss: 1.222, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 0.942, Train Accuracy: 0.600
Train Loss: 1.568, Train Accuracy: 0.800
Train Loss: 1.164, Train Accuracy: 0.750
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.576, Train Accuracy: 1.000
Train Loss: 0.932, Train Accuracy: 0.600
Train Loss: 2.132, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.700
Round 39
Train Loss: 1.344, Train Accuracy: 0.750
Train Loss: 0.976, Train Accuracy: 0.700
Train Loss: 0.936, Train Accuracy: 0.400
Train Loss: 1.175, Train Accuracy: 1.000
Train Loss: 1.068, Train Accuracy: 0.875
Train Loss: 1.368, Train Accuracy: 1.000
Train Loss: 1.667, Train Accuracy: 1.000
Train Loss: 1.059, Train Accuracy: 0.800
Train Loss: 2.016, Train Accuracy: 0.750
Train Loss: 0.988, Train Accuracy: 0.800
Round 40
Train Loss: 1.145, Train Accuracy: 0.750
Train Loss: 0.927, Train Accuracy: 0.600
Train Loss: 0.870, Train Accuracy: 0.600
Train Loss: 1.381, Train Accuracy: 1.000
Train Loss: 1.108, Train Accuracy: 0.500
Train Loss: 1.267, Train Accuracy: 0.800
Train Loss: 1.531, Train Accuracy: 1.000
Train Loss: 0.989, Train Accuracy: 0.800
Train Loss: 2.236, Train Accuracy: 1.000
Train Loss: 1.183, Train Accuracy: 0.500
Round 41
Train Loss: 1.178, Train Accuracy: 0.750
Train Loss: 0.959, Train Accuracy: 0.600
Train Loss: 0.938, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.800
Train Loss: 1.150, Train Accuracy: 0.625
Train Loss: 1.321, Train Accuracy: 0.800
Train Loss: 1.955, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.800
Train Loss: 2.065, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.800
Round 42
Train Loss: 1.495, Train Accuracy: 0.750
Train Loss: 0.947, Train Accuracy: 0.500
Train Loss: 0.839, Train Accuracy: 0.600
Train Loss: 1.635, Train Accuracy: 0.800
Train Loss: 1.138, Train Accuracy: 0.625
Train Loss: 1.302, Train Accuracy: 0.800
Train Loss: 1.389, Train Accuracy: 0.500
Train Loss: 1.070, Train Accuracy: 0.200
Train Loss: 2.278, Train Accuracy: 1.000
Train Loss: 1.105, Train Accuracy: 0.700
Round 43
Train Loss: 1.156, Train Accuracy: 0.750
Train Loss: 0.920, Train Accuracy: 0.500
Train Loss: 0.870, Train Accuracy: 0.800
Train Loss: 1.388, Train Accuracy: 0.800
Train Loss: 1.103, Train Accuracy: 0.875
Train Loss: 1.207, Train Accuracy: 0.800
Train Loss: 1.650, Train Accuracy: 0.750
Train Loss: 0.951, Train Accuracy: 0.600
Train Loss: 2.113, Train Accuracy: 1.000
Train Loss: 1.178, Train Accuracy: 0.600
Round 44
Train Loss: 1.426, Train Accuracy: 0.750
Train Loss: 0.960, Train Accuracy: 0.600
Train Loss: 0.885, Train Accuracy: 0.800
Train Loss: 1.476, Train Accuracy: 0.800
Train Loss: 1.199, Train Accuracy: 0.875
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.521, Train Accuracy: 0.500
Train Loss: 0.955, Train Accuracy: 0.800
Train Loss: 2.158, Train Accuracy: 1.000
Train Loss: 1.093, Train Accuracy: 0.800
Round 45
Train Loss: 1.041, Train Accuracy: 0.750
Train Loss: 0.891, Train Accuracy: 0.800
Train Loss: 0.844, Train Accuracy: 0.800
Train Loss: 1.202, Train Accuracy: 0.600
Train Loss: 1.050, Train Accuracy: 0.375
Train Loss: 1.201, Train Accuracy: 0.800
Train Loss: 1.437, Train Accuracy: 1.000
Train Loss: 1.162, Train Accuracy: 0.800
Train Loss: 1.716, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.900
Round 46
Train Loss: 1.107, Train Accuracy: 0.750
Train Loss: 0.910, Train Accuracy: 0.700
Train Loss: 0.842, Train Accuracy: 1.000
Train Loss: 1.273, Train Accuracy: 1.000
Train Loss: 1.061, Train Accuracy: 0.625
Train Loss: 1.145, Train Accuracy: 0.800
Train Loss: 1.592, Train Accuracy: 0.750
Train Loss: 0.960, Train Accuracy: 0.600
Train Loss: 2.034, Train Accuracy: 1.000
Train Loss: 1.162, Train Accuracy: 0.800
Round 47
Train Loss: 1.224, Train Accuracy: 0.750
Train Loss: 0.941, Train Accuracy: 0.600
Train Loss: 0.836, Train Accuracy: 0.400
Train Loss: 1.597, Train Accuracy: 0.800
Train Loss: 1.156, Train Accuracy: 0.875
Train Loss: 1.193, Train Accuracy: 0.800
Train Loss: 1.612, Train Accuracy: 0.500
Train Loss: 1.057, Train Accuracy: 0.800
Train Loss: 1.536, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 1.000
Round 48
Train Loss: 1.336, Train Accuracy: 0.750
Train Loss: 0.963, Train Accuracy: 0.400
Train Loss: 0.889, Train Accuracy: 0.800
Train Loss: 1.220, Train Accuracy: 1.000
Train Loss: 1.115, Train Accuracy: 0.875
Train Loss: 1.255, Train Accuracy: 0.800
Train Loss: 1.667, Train Accuracy: 0.750

(FLClient pid=2856554) 2025-04-11 09:03:45,752 - INFO - Epoch   0| Train Loss: 1.102| Train Accuracy: 0.250 [repeated 328x across cluster]
(FLClient pid=2855740) 2025-04-11 09:03:37,951 - INFO - Epoch   2| Validation Loss: 0.852, Validation Accuracy: 0.578 [repeated 110x across cluster]
(FLClient pid=2856554) 2025-04-11 09:03:50,865 - INFO - Epoch   1| Train Loss: 0.733| Train Accuracy: 0.750 [repeated 421x across cluster]
(FLClient pid=2856763) 2025-04-11 09:03:50,546 - INFO - Epoch   2| Validation Loss: 1.161, Validation Accuracy: 0.344 [repeated 140x across cluster]
(FLClient pid=2856554) 2025-04-11 09:03:56,005 - INFO - Epoch   2| Train Loss: 0.660| Train Accuracy: 0.750 [repeated 451x across cluster]
(FLClient pid=2856763) 2025-04-11 09:03:55,675 - INFO - Epoch   2| Validation Loss: 1.097, Validation Accuracy: 0.484 [repeated 150x across cluster]
(FLClient pid=2856554) 2025-04-11 09:04:01,098 - INFO - Epoch   2| Train Loss: 0.680| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2856554) 2025-04-11 09:04:01,105 - INFO - Epoch   2| Validation Loss: 1.169, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2856555) 2025-04-11 09:04:06,188 - INFO - Epoch   0| Train Loss: 0.725| Train Accuracy: 0.700 [repeated 448x across cluster]
(FLClient pid=2856554) 2025-04-11 09:04:05,882 - INFO - Epoch   2| Validation Loss: 1.186, Validation Accuracy: 0.295 [repeated 149x across cluster]
(FLClient pid=2856554) 2025-04-11 09:04:11,305 - INFO - Epoch   2| Train Loss: 0.363| Train Accuracy: 1.000 [repeated 452x across cluster]
(FLClient pid=2856554) 2025-04-11 09:04:11,313 - INFO - Epoch   2| Validation Loss: 1.419, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2856554) 2025-04-11 09:04:16,376 - INFO - Epoch   1| Train Loss: 0.474| Train Accuracy: 0.750 [repeated 449x across cluster]
(FLClient pid=2856763) 2025-04-11 09:04:16,059 - INFO - Epoch   2| Validation Loss: 0.796, Validation Accuracy: 0.516 [repeated 149x across cluster]

Training done
Round 1
Train Loss: 1.181, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.051, Train Accuracy: 0.400
Train Loss: 1.203, Train Accuracy: 0.600
Train Loss: 1.155, Train Accuracy: 0.625
Train Loss: 1.243, Train Accuracy: 0.800
Train Loss: 1.281, Train Accuracy: 0.500
Train Loss: 1.137, Train Accuracy: 0.600
Train Loss: 1.419, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.400
Round 2
Train Loss: 1.245, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.047, Train Accuracy: 0.400
Train Loss: 1.253, Train Accuracy: 0.600
Train Loss: 1.187, Train Accuracy: 0.625
Train Loss: 1.271, Train Accuracy: 0.800
Train Loss: 1.341, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.400
Train Loss: 1.472, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.400
Round 3
Train Loss: 1.262, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.400
Train Loss: 1.274, Train Accuracy: 0.600
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.284, Train Accuracy: 0.800
Train Loss: 1.334, Train Accuracy: 0.500
Train Loss: 1.163, Train Accuracy: 0.400
Train Loss: 1.572, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.400
Round 4
Train Loss: 1.242, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.400
Train Loss: 1.287, Train Accuracy: 0.600
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.241, Train Accuracy: 0.800
Train Loss: 1.407, Train Accuracy: 0.500
Train Loss: 1.175, Train Accuracy: 0.600
Train Loss: 1.588, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.400
Round 5
Train Loss: 1.246, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 1.301, Train Accuracy: 0.600
Train Loss: 1.208, Train Accuracy: 0.625
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.437, Train Accuracy: 0.500
Train Loss: 1.152, Train Accuracy: 0.600
Train Loss: 1.658, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.500
Round 6
Train Loss: 1.268, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.036, Train Accuracy: 0.400
Train Loss: 1.368, Train Accuracy: 0.600
Train Loss: 1.243, Train Accuracy: 0.625
Train Loss: 1.261, Train Accuracy: 0.800
Train Loss: 1.424, Train Accuracy: 1.000
Train Loss: 1.147, Train Accuracy: 0.600
Train Loss: 1.734, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.400
Round 7
Train Loss: 1.319, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.600
Train Loss: 1.028, Train Accuracy: 0.600
Train Loss: 1.309, Train Accuracy: 0.600
Train Loss: 1.260, Train Accuracy: 0.625
Train Loss: 1.285, Train Accuracy: 0.800
Train Loss: 1.439, Train Accuracy: 0.250
Train Loss: 1.174, Train Accuracy: 0.600
Train Loss: 1.672, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.500
Round 8
Train Loss: 1.266, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.500
Train Loss: 1.017, Train Accuracy: 0.400
Train Loss: 1.344, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.625
Train Loss: 1.288, Train Accuracy: 0.800
Train Loss: 1.520, Train Accuracy: 0.750
Train Loss: 1.158, Train Accuracy: 0.600
Train Loss: 1.740, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.400
Round 9
Train Loss: 1.306, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.600
Train Loss: 1.015, Train Accuracy: 0.400
Train Loss: 1.412, Train Accuracy: 0.600
Train Loss: 1.220, Train Accuracy: 0.625
Train Loss: 1.241, Train Accuracy: 0.800
Train Loss: 1.448, Train Accuracy: 0.500
Train Loss: 1.156, Train Accuracy: 0.600
Train Loss: 1.851, Train Accuracy: 0.750
Train Loss: 1.207, Train Accuracy: 0.600
Round 10
Train Loss: 1.272, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.500
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.394, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.750
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.449, Train Accuracy: 0.500
Train Loss: 1.129, Train Accuracy: 0.600
Train Loss: 1.751, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.400
Round 11
Train Loss: 1.283, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.600
Train Loss: 1.018, Train Accuracy: 0.400
Train Loss: 1.446, Train Accuracy: 0.600
Train Loss: 1.210, Train Accuracy: 0.750
Train Loss: 1.304, Train Accuracy: 0.800
Train Loss: 1.450, Train Accuracy: 0.500
Train Loss: 1.130, Train Accuracy: 0.400
Train Loss: 1.813, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 0.600
Round 12
Train Loss: 1.354, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.500
Train Loss: 1.012, Train Accuracy: 0.200
Train Loss: 1.295, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.249, Train Accuracy: 0.800
Train Loss: 1.456, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.800
Train Loss: 1.907, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.300
Round 13
Train Loss: 1.445, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.600
Train Loss: 1.006, Train Accuracy: 0.200
Train Loss: 1.346, Train Accuracy: 0.600
Train Loss: 1.260, Train Accuracy: 0.625
Train Loss: 1.286, Train Accuracy: 0.800
Train Loss: 1.481, Train Accuracy: 0.500
Train Loss: 1.143, Train Accuracy: 0.400
Train Loss: 1.830, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.600
Round 14
Train Loss: 1.332, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.600
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.372, Train Accuracy: 0.600
Train Loss: 1.228, Train Accuracy: 0.750
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.481, Train Accuracy: 0.250
Train Loss: 1.196, Train Accuracy: 0.600
Train Loss: 1.837, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.400
Round 15
Train Loss: 1.411, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.600
Train Loss: 1.002, Train Accuracy: 0.400
Train Loss: 1.365, Train Accuracy: 0.800
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.509, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.600
Train Loss: 1.785, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.600
Round 16
Train Loss: 1.379, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.500
Train Loss: 0.988, Train Accuracy: 0.600
Train Loss: 1.357, Train Accuracy: 0.600
Train Loss: 1.206, Train Accuracy: 0.625
Train Loss: 1.217, Train Accuracy: 0.800
Train Loss: 1.562, Train Accuracy: 0.500
Train Loss: 1.198, Train Accuracy: 0.800
Train Loss: 1.774, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.700
Round 17
Train Loss: 1.405, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.600
Train Loss: 0.992, Train Accuracy: 0.400
Train Loss: 1.255, Train Accuracy: 0.600
Train Loss: 1.196, Train Accuracy: 0.750
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.463, Train Accuracy: 0.500
Train Loss: 1.182, Train Accuracy: 0.600
Train Loss: 1.856, Train Accuracy: 0.750
Train Loss: 1.226, Train Accuracy: 0.500
Round 18
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.600
Train Loss: 0.988, Train Accuracy: 0.600
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.196, Train Accuracy: 0.750
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.565, Train Accuracy: 0.500
Train Loss: 1.094, Train Accuracy: 0.400
Train Loss: 1.895, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.600
Round 19
Train Loss: 1.366, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.600
Train Loss: 0.989, Train Accuracy: 0.200
Train Loss: 1.373, Train Accuracy: 0.600
Train Loss: 1.222, Train Accuracy: 0.625
Train Loss: 1.245, Train Accuracy: 0.800
Train Loss: 1.492, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.600
Train Loss: 1.835, Train Accuracy: 0.750
Train Loss: 1.148, Train Accuracy: 0.500
Round 20
Train Loss: 1.378, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.600
Train Loss: 0.988, Train Accuracy: 0.200
Train Loss: 1.360, Train Accuracy: 0.600
Train Loss: 1.162, Train Accuracy: 0.625
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.619, Train Accuracy: 0.500
Train Loss: 1.078, Train Accuracy: 0.400
Train Loss: 1.950, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.400
Round 21
Train Loss: 1.431, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.500
Train Loss: 0.991, Train Accuracy: 0.800
Train Loss: 1.261, Train Accuracy: 0.600
Train Loss: 1.195, Train Accuracy: 0.750
Train Loss: 1.322, Train Accuracy: 0.800
Train Loss: 1.447, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.400
Train Loss: 1.804, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.500
Round 22
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.017, Train Accuracy: 0.800
Train Loss: 0.971, Train Accuracy: 0.400
Train Loss: 1.467, Train Accuracy: 0.800
Train Loss: 1.157, Train Accuracy: 0.625
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.483, Train Accuracy: 0.500
Train Loss: 1.125, Train Accuracy: 0.800
Train Loss: 1.738, Train Accuracy: 0.750
Train Loss: 1.128, Train Accuracy: 0.500
Round 23
Train Loss: 1.325, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.600
Train Loss: 0.980, Train Accuracy: 0.200
Train Loss: 1.239, Train Accuracy: 0.800
Train Loss: 1.159, Train Accuracy: 0.625
Train Loss: 1.370, Train Accuracy: 0.800
Train Loss: 1.538, Train Accuracy: 0.500
Train Loss: 1.086, Train Accuracy: 0.600
Train Loss: 1.947, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.600
Round 24
Train Loss: 1.241, Train Accuracy: 0.750
Train Loss: 1.018, Train Accuracy: 0.600
Train Loss: 0.958, Train Accuracy: 0.400
Train Loss: 1.379, Train Accuracy: 0.600
Train Loss: 1.189, Train Accuracy: 0.750
Train Loss: 1.232, Train Accuracy: 0.800
Train Loss: 1.626, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 1.868, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.700
Round 25
Train Loss: 1.314, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 0.976, Train Accuracy: 0.400
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.152, Train Accuracy: 0.625
Train Loss: 1.360, Train Accuracy: 0.800
Train Loss: 1.591, Train Accuracy: 0.500
Train Loss: 1.070, Train Accuracy: 0.600
Train Loss: 1.857, Train Accuracy: 0.750
Train Loss: 1.101, Train Accuracy: 0.400
Round 26
Train Loss: 1.412, Train Accuracy: 0.750
Train Loss: 0.994, Train Accuracy: 0.800
Train Loss: 0.951, Train Accuracy: 0.800
Train Loss: 1.535, Train Accuracy: 1.000
Train Loss: 1.207, Train Accuracy: 0.875
Train Loss: 1.271, Train Accuracy: 0.800
Train Loss: 1.577, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.600
Train Loss: 1.628, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.600
Round 27
Train Loss: 1.329, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 0.950, Train Accuracy: 0.600
Train Loss: 1.289, Train Accuracy: 0.600
Train Loss: 1.156, Train Accuracy: 0.875
Train Loss: 1.267, Train Accuracy: 0.800
Train Loss: 1.357, Train Accuracy: 0.750
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.900, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.600
Round 28
Train Loss: 1.164, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.600
Train Loss: 0.990, Train Accuracy: 0.400
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.198, Train Accuracy: 0.750
Train Loss: 1.386, Train Accuracy: 0.800
Train Loss: 1.570, Train Accuracy: 1.000
Train Loss: 1.093, Train Accuracy: 0.600
Train Loss: 1.758, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.400
Round 29
Train Loss: 1.169, Train Accuracy: 0.750
Train Loss: 0.992, Train Accuracy: 0.600
Train Loss: 0.943, Train Accuracy: 0.200
Train Loss: 1.407, Train Accuracy: 1.000
Train Loss: 1.188, Train Accuracy: 0.750
Train Loss: 1.264, Train Accuracy: 0.800
Train Loss: 1.626, Train Accuracy: 1.000
Train Loss: 1.055, Train Accuracy: 0.800
Train Loss: 1.993, Train Accuracy: 0.750
Train Loss: 1.097, Train Accuracy: 0.700
Round 30
Train Loss: 1.219, Train Accuracy: 0.750
Train Loss: 0.983, Train Accuracy: 0.600
Train Loss: 0.945, Train Accuracy: 0.400
Train Loss: 1.332, Train Accuracy: 1.000
Train Loss: 1.183, Train Accuracy: 0.750
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 1.000
Train Loss: 1.239, Train Accuracy: 0.800
Train Loss: 1.977, Train Accuracy: 0.750
Train Loss: 1.084, Train Accuracy: 0.600
Round 31
Train Loss: 1.211, Train Accuracy: 0.750
Train Loss: 0.982, Train Accuracy: 0.600
Train Loss: 0.934, Train Accuracy: 0.600
Train Loss: 1.365, Train Accuracy: 0.600
Train Loss: 1.149, Train Accuracy: 0.750
Train Loss: 1.291, Train Accuracy: 0.800
Train Loss: 1.520, Train Accuracy: 0.750
Train Loss: 1.014, Train Accuracy: 0.800
Train Loss: 1.991, Train Accuracy: 0.750
Train Loss: 1.106, Train Accuracy: 0.600
Round 32
Train Loss: 1.118, Train Accuracy: 0.500
Train Loss: 0.968, Train Accuracy: 0.700
Train Loss: 0.927, Train Accuracy: 0.600
Train Loss: 1.373, Train Accuracy: 0.600
Train Loss: 1.165, Train Accuracy: 0.625
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.568, Train Accuracy: 0.500
Train Loss: 1.078, Train Accuracy: 0.400
Train Loss: 1.930, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.800
Round 33
Train Loss: 1.313, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.700
Train Loss: 0.963, Train Accuracy: 0.400
Train Loss: 1.222, Train Accuracy: 1.000
Train Loss: 1.249, Train Accuracy: 0.625
Train Loss: 1.276, Train Accuracy: 0.800
Train Loss: 1.466, Train Accuracy: 1.000
Train Loss: 1.101, Train Accuracy: 1.000
Train Loss: 1.745, Train Accuracy: 0.750
Train Loss: 1.088, Train Accuracy: 0.700
Round 34
Train Loss: 1.411, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.600
Train Loss: 0.946, Train Accuracy: 0.800
Train Loss: 1.288, Train Accuracy: 1.000
Train Loss: 1.143, Train Accuracy: 0.750
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.593, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.800
Train Loss: 1.768, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.600
Round 35
Train Loss: 1.180, Train Accuracy: 0.750
Train Loss: 0.987, Train Accuracy: 0.600
Train Loss: 0.945, Train Accuracy: 0.400
Train Loss: 1.372, Train Accuracy: 1.000
Train Loss: 1.165, Train Accuracy: 0.625
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.464, Train Accuracy: 0.500
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 1.709, Train Accuracy: 0.500
Train Loss: 1.013, Train Accuracy: 0.700
Round 36
Train Loss: 1.505, Train Accuracy: 0.750
Train Loss: 0.967, Train Accuracy: 0.600
Train Loss: 0.889, Train Accuracy: 1.000
Train Loss: 1.204, Train Accuracy: 1.000
Train Loss: 1.149, Train Accuracy: 0.875
Train Loss: 1.264, Train Accuracy: 0.800
Train Loss: 1.522, Train Accuracy: 1.000
Train Loss: 1.061, Train Accuracy: 0.400
Train Loss: 1.637, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.600
Round 37
Train Loss: 1.403, Train Accuracy: 0.750
Train Loss: 0.963, Train Accuracy: 0.700
Train Loss: 0.907, Train Accuracy: 0.600
Train Loss: 1.266, Train Accuracy: 0.800
Train Loss: 1.129, Train Accuracy: 0.750
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.454, Train Accuracy: 0.750
Train Loss: 1.098, Train Accuracy: 0.400
Train Loss: 1.935, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.600
Round 38
Train Loss: 1.400, Train Accuracy: 0.750
Train Loss: 0.983, Train Accuracy: 0.600
Train Loss: 0.918, Train Accuracy: 0.600
Train Loss: 1.161, Train Accuracy: 1.000
Train Loss: 1.148, Train Accuracy: 0.625
Train Loss: 1.237, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 1.000
Train Loss: 1.109, Train Accuracy: 0.800
Train Loss: 1.659, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.700
Round 39
Train Loss: 1.370, Train Accuracy: 0.750
Train Loss: 0.933, Train Accuracy: 0.600
Train Loss: 0.869, Train Accuracy: 0.400
Train Loss: 1.196, Train Accuracy: 1.000
Train Loss: 1.146, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.800
Train Loss: 1.634, Train Accuracy: 1.000
Train Loss: 1.002, Train Accuracy: 0.600
Train Loss: 1.935, Train Accuracy: 0.750
Train Loss: 0.992, Train Accuracy: 0.700
Round 40
Train Loss: 1.230, Train Accuracy: 0.500
Train Loss: 0.944, Train Accuracy: 0.600
Train Loss: 0.882, Train Accuracy: 0.400
Train Loss: 1.461, Train Accuracy: 0.800
Train Loss: 1.154, Train Accuracy: 0.750
Train Loss: 1.374, Train Accuracy: 0.800
Train Loss: 1.532, Train Accuracy: 0.500
Train Loss: 1.052, Train Accuracy: 0.600
Train Loss: 1.823, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.600
Round 41
Train Loss: 1.266, Train Accuracy: 0.750
Train Loss: 0.924, Train Accuracy: 0.700
Train Loss: 0.901, Train Accuracy: 0.600
Train Loss: 1.159, Train Accuracy: 0.800
Train Loss: 1.112, Train Accuracy: 0.625
Train Loss: 1.206, Train Accuracy: 0.800
Train Loss: 1.630, Train Accuracy: 0.500
Train Loss: 1.206, Train Accuracy: 0.400
Train Loss: 2.316, Train Accuracy: 1.000
Train Loss: 0.971, Train Accuracy: 0.900
Round 42
Train Loss: 1.038, Train Accuracy: 0.750
Train Loss: 0.930, Train Accuracy: 0.800
Train Loss: 0.869, Train Accuracy: 0.800
Train Loss: 1.162, Train Accuracy: 0.600
Train Loss: 1.125, Train Accuracy: 0.500
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.604, Train Accuracy: 1.000
Train Loss: 0.977, Train Accuracy: 0.800
Train Loss: 1.930, Train Accuracy: 0.750
Train Loss: 1.096, Train Accuracy: 0.700
Round 43
Train Loss: 1.229, Train Accuracy: 0.750
Train Loss: 0.934, Train Accuracy: 0.700
Train Loss: 0.877, Train Accuracy: 0.800
Train Loss: 1.188, Train Accuracy: 0.600
Train Loss: 1.165, Train Accuracy: 0.625
Train Loss: 1.213, Train Accuracy: 0.800
Train Loss: 1.608, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.800
Train Loss: 1.872, Train Accuracy: 1.000
Train Loss: 1.130, Train Accuracy: 0.600
Round 44
Train Loss: 1.276, Train Accuracy: 0.500
Train Loss: 0.936, Train Accuracy: 0.700
Train Loss: 0.965, Train Accuracy: 0.400
Train Loss: 1.176, Train Accuracy: 1.000
Train Loss: 1.133, Train Accuracy: 0.875
Train Loss: 1.174, Train Accuracy: 0.800
Train Loss: 1.692, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 1.000
Train Loss: 1.492, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.900
Round 45
Train Loss: 1.169, Train Accuracy: 0.750
Train Loss: 0.946, Train Accuracy: 0.700
Train Loss: 0.873, Train Accuracy: 0.800
Train Loss: 1.200, Train Accuracy: 1.000
Train Loss: 1.165, Train Accuracy: 0.875
Train Loss: 1.295, Train Accuracy: 0.800
Train Loss: 1.632, Train Accuracy: 0.750
Train Loss: 1.095, Train Accuracy: 0.600
Train Loss: 1.717, Train Accuracy: 0.750
Train Loss: 1.257, Train Accuracy: 0.700
Round 46
Train Loss: 1.413, Train Accuracy: 0.750
Train Loss: 0.899, Train Accuracy: 0.600
Train Loss: 0.920, Train Accuracy: 0.800
Train Loss: 1.152, Train Accuracy: 1.000
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.104, Train Accuracy: 0.800
Train Loss: 1.479, Train Accuracy: 0.500
Train Loss: 1.056, Train Accuracy: 0.800
Train Loss: 1.943, Train Accuracy: 0.750
Train Loss: 1.088, Train Accuracy: 0.600
Round 47
Train Loss: 1.252, Train Accuracy: 0.750
Train Loss: 0.919, Train Accuracy: 0.800
Train Loss: 0.836, Train Accuracy: 0.600
Train Loss: 1.162, Train Accuracy: 1.000
Train Loss: 1.065, Train Accuracy: 0.250
Train Loss: 1.201, Train Accuracy: 0.800
Train Loss: 1.497, Train Accuracy: 0.500
Train Loss: 0.994, Train Accuracy: 0.800
Train Loss: 1.927, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.400
Round 48
Train Loss: 1.233, Train Accuracy: 0.750
Train Loss: 0.952, Train Accuracy: 0.600
Train Loss: 0.881, Train Accuracy: 0.800
Train Loss: 1.542, Train Accuracy: 0.800
Train Loss: 1.119, Train Accuracy: 0.500
Train Loss: 1.225, Train Accuracy: 0.800
Train Loss: 1.616, Train Accuracy: 1.000

(FLClient pid=2857571) 2025-04-11 09:04:27,189 - INFO - Epoch   2| Train Loss: 0.775| Train Accuracy: 0.750 [repeated 331x across cluster]
(FLClient pid=2857571) 2025-04-11 09:04:27,198 - INFO - Epoch   2| Validation Loss: 1.197, Validation Accuracy: 0.295 [repeated 111x across cluster]
(FLClient pid=2857572) 2025-04-11 09:04:32,406 - INFO - Epoch   2| Train Loss: 1.021| Train Accuracy: 0.500 [repeated 390x across cluster]
(FLClient pid=2857572) 2025-04-11 09:04:32,410 - INFO - Epoch   2| Validation Loss: 1.039, Validation Accuracy: 0.467 [repeated 130x across cluster]
(FLClient pid=2857572) 2025-04-11 09:04:37,486 - INFO - Epoch   2| Train Loss: 0.877| Train Accuracy: 0.600 [repeated 450x across cluster]
(FLClient pid=2857572) 2025-04-11 09:04:37,494 - INFO - Epoch   2| Validation Loss: 1.000, Validation Accuracy: 0.467 [repeated 150x across cluster]
(FLClient pid=2857572) 2025-04-11 09:04:42,555 - INFO - Epoch   0| Train Loss: 0.772| Train Accuracy: 0.600 [repeated 448x across cluster]
(FLClient pid=2857780) 2025-04-11 09:04:42,247 - INFO - Epoch   2| Validation Loss: 1.234, Validation Accuracy: 0.156 [repeated 149x across cluster]
(FLClient pid=2857572) 2025-04-11 09:04:47,698 - INFO - Epoch   2| Train Loss: 0.734| Train Accuracy: 0.600 [repeated 452x across cluster]
(FLClient pid=2857572) 2025-04-11 09:04:47,706 - INFO - Epoch   2| Validation Loss: 0.989, Validation Accuracy: 0.467 [repeated 151x across cluster]
(FLClient pid=2857572) 2025-04-11 09:04:52,790 - INFO - Epoch   0| Train Loss: 0.674| Train Accuracy: 0.700 [repeated 448x across cluster]
(FLClient pid=2857572) 2025-04-11 09:04:52,483 - INFO - Epoch   2| Validation Loss: 0.902, Validation Accuracy: 0.467 [repeated 149x across cluster]
(FLClient pid=2857572) 2025-04-11 09:04:57,917 - INFO - Epoch   2| Train Loss: 0.579| Train Accuracy: 0.800 [repeated 452x across cluster]
(FLClient pid=2857572) 2025-04-11 09:04:57,924 - INFO - Epoch   2| Validation Loss: 0.778, Validation Accuracy: 0.578 [repeated 151x across cluster]

Training done
Round 1
Train Loss: 1.197, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.055, Train Accuracy: 0.600
Train Loss: 1.244, Train Accuracy: 0.600
Train Loss: 1.203, Train Accuracy: 0.625
Train Loss: 1.213, Train Accuracy: 0.800
Train Loss: 1.353, Train Accuracy: 1.000
Train Loss: 1.138, Train Accuracy: 0.600
Train Loss: 1.611, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.400
Round 2
Train Loss: 1.176, Train Accuracy: 0.750
Train Loss: 1.083, Train Accuracy: 0.500
Train Loss: 1.046, Train Accuracy: 0.400
Train Loss: 1.304, Train Accuracy: 0.600
Train Loss: 1.239, Train Accuracy: 0.625
Train Loss: 1.215, Train Accuracy: 0.800
Train Loss: 1.354, Train Accuracy: 0.500
Train Loss: 1.175, Train Accuracy: 0.400
Train Loss: 1.773, Train Accuracy: 0.750
Train Loss: 1.221, Train Accuracy: 0.400
Round 3
Train Loss: 1.194, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.600
Train Loss: 1.040, Train Accuracy: 0.400
Train Loss: 1.333, Train Accuracy: 0.600
Train Loss: 1.201, Train Accuracy: 0.625
Train Loss: 1.232, Train Accuracy: 0.800
Train Loss: 1.361, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.400
Train Loss: 1.743, Train Accuracy: 0.750
Train Loss: 1.158, Train Accuracy: 0.500
Round 4
Train Loss: 1.177, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.500
Train Loss: 1.051, Train Accuracy: 0.400
Train Loss: 1.338, Train Accuracy: 0.600
Train Loss: 1.208, Train Accuracy: 0.625
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.393, Train Accuracy: 0.500
Train Loss: 1.234, Train Accuracy: 0.600
Train Loss: 1.667, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.400
Round 5
Train Loss: 1.240, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.400
Train Loss: 1.349, Train Accuracy: 0.600
Train Loss: 1.201, Train Accuracy: 0.625
Train Loss: 1.266, Train Accuracy: 0.800
Train Loss: 1.420, Train Accuracy: 0.500
Train Loss: 1.164, Train Accuracy: 0.200
Train Loss: 1.876, Train Accuracy: 0.750
Train Loss: 1.199, Train Accuracy: 0.500
Round 6
Train Loss: 1.277, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.500
Train Loss: 1.034, Train Accuracy: 0.600
Train Loss: 1.341, Train Accuracy: 0.600
Train Loss: 1.207, Train Accuracy: 0.625
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.509, Train Accuracy: 0.500
Train Loss: 1.181, Train Accuracy: 0.400
Train Loss: 1.757, Train Accuracy: 0.750
Train Loss: 1.279, Train Accuracy: 0.600
Round 7
Train Loss: 1.249, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.600
Train Loss: 1.026, Train Accuracy: 0.400
Train Loss: 1.370, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 0.625
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.404, Train Accuracy: 0.750
Train Loss: 1.214, Train Accuracy: 0.600
Train Loss: 1.769, Train Accuracy: 0.750
Train Loss: 1.221, Train Accuracy: 0.600
Round 8
Train Loss: 1.272, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.500
Train Loss: 1.032, Train Accuracy: 0.400
Train Loss: 1.370, Train Accuracy: 0.600
Train Loss: 1.218, Train Accuracy: 0.625
Train Loss: 1.315, Train Accuracy: 0.800
Train Loss: 1.446, Train Accuracy: 1.000
Train Loss: 1.237, Train Accuracy: 0.600
Train Loss: 1.825, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.400
Round 9
Train Loss: 1.316, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.600
Train Loss: 1.025, Train Accuracy: 0.200
Train Loss: 1.320, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 0.625
Train Loss: 1.260, Train Accuracy: 0.800
Train Loss: 1.436, Train Accuracy: 0.250
Train Loss: 1.123, Train Accuracy: 0.400
Train Loss: 1.755, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.400
Round 10
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.397, Train Accuracy: 0.600
Train Loss: 1.207, Train Accuracy: 0.750
Train Loss: 1.298, Train Accuracy: 0.800
Train Loss: 1.424, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.600
Train Loss: 1.921, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.500
Round 11
Train Loss: 1.253, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.036, Train Accuracy: 0.400
Train Loss: 1.374, Train Accuracy: 0.600
Train Loss: 1.198, Train Accuracy: 0.750
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.485, Train Accuracy: 0.500
Train Loss: 1.146, Train Accuracy: 0.600
Train Loss: 1.932, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 0.400
Round 12
Train Loss: 1.341, Train Accuracy: 0.750
Train Loss: 1.040, Train Accuracy: 0.600
Train Loss: 1.023, Train Accuracy: 0.400
Train Loss: 1.485, Train Accuracy: 0.800
Train Loss: 1.211, Train Accuracy: 0.625
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.505, Train Accuracy: 0.500
Train Loss: 1.136, Train Accuracy: 0.600
Train Loss: 1.884, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.500
Round 13
Train Loss: 1.309, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.200
Train Loss: 1.373, Train Accuracy: 0.600
Train Loss: 1.253, Train Accuracy: 0.625
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.459, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.600
Train Loss: 1.962, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.400
Round 14
Train Loss: 1.311, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.500
Train Loss: 1.013, Train Accuracy: 0.400
Train Loss: 1.372, Train Accuracy: 0.600
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.401, Train Accuracy: 0.800
Train Loss: 1.446, Train Accuracy: 0.250
Train Loss: 1.179, Train Accuracy: 0.600
Train Loss: 1.855, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.500
Round 15
Train Loss: 1.359, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.500
Train Loss: 0.990, Train Accuracy: 0.600
Train Loss: 1.480, Train Accuracy: 0.600
Train Loss: 1.164, Train Accuracy: 0.750
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.427, Train Accuracy: 0.750
Train Loss: 1.105, Train Accuracy: 0.400
Train Loss: 2.139, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.500
Round 16
Train Loss: 1.286, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.500
Train Loss: 0.992, Train Accuracy: 0.400
Train Loss: 1.419, Train Accuracy: 0.800
Train Loss: 1.204, Train Accuracy: 0.750
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.620, Train Accuracy: 0.500
Train Loss: 1.153, Train Accuracy: 0.600
Train Loss: 2.002, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.600
Round 17
Train Loss: 1.341, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.700
Train Loss: 0.992, Train Accuracy: 0.800
Train Loss: 1.398, Train Accuracy: 1.000
Train Loss: 1.172, Train Accuracy: 0.625
Train Loss: 1.235, Train Accuracy: 0.800
Train Loss: 1.582, Train Accuracy: 0.500
Train Loss: 1.083, Train Accuracy: 0.600
Train Loss: 2.148, Train Accuracy: 0.750
Train Loss: 1.130, Train Accuracy: 0.400
Round 18
Train Loss: 1.403, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 1.391, Train Accuracy: 0.800
Train Loss: 1.240, Train Accuracy: 0.750
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.448, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.800
Train Loss: 2.024, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.600
Round 19
Train Loss: 1.254, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.700
Train Loss: 0.997, Train Accuracy: 0.600
Train Loss: 1.307, Train Accuracy: 0.800
Train Loss: 1.188, Train Accuracy: 0.750
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.478, Train Accuracy: 0.500
Train Loss: 1.187, Train Accuracy: 0.800
Train Loss: 2.037, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.400
Round 20
Train Loss: 1.342, Train Accuracy: 0.750
Train Loss: 1.018, Train Accuracy: 0.600
Train Loss: 0.981, Train Accuracy: 0.400
Train Loss: 1.195, Train Accuracy: 0.600
Train Loss: 1.206, Train Accuracy: 0.625
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.492, Train Accuracy: 1.000
Train Loss: 1.110, Train Accuracy: 0.600
Train Loss: 1.866, Train Accuracy: 0.750
Train Loss: 1.122, Train Accuracy: 0.700
Round 21
Train Loss: 1.234, Train Accuracy: 0.750
Train Loss: 1.007, Train Accuracy: 0.800
Train Loss: 0.987, Train Accuracy: 0.400
Train Loss: 1.285, Train Accuracy: 0.600
Train Loss: 1.227, Train Accuracy: 0.625
Train Loss: 1.304, Train Accuracy: 0.800
Train Loss: 1.418, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.400
Train Loss: 1.673, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.500
Round 22
Train Loss: 1.283, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.800
Train Loss: 0.967, Train Accuracy: 0.400
Train Loss: 1.361, Train Accuracy: 0.800
Train Loss: 1.200, Train Accuracy: 0.750
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.479, Train Accuracy: 0.750
Train Loss: 1.091, Train Accuracy: 0.400
Train Loss: 2.153, Train Accuracy: 1.000
Train Loss: 1.110, Train Accuracy: 0.600
Round 23
Train Loss: 1.336, Train Accuracy: 0.750
Train Loss: 1.013, Train Accuracy: 0.600
Train Loss: 0.959, Train Accuracy: 0.400
Train Loss: 1.221, Train Accuracy: 0.800
Train Loss: 1.176, Train Accuracy: 0.750
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.744, Train Accuracy: 0.500
Train Loss: 1.090, Train Accuracy: 0.600
Train Loss: 1.755, Train Accuracy: 0.750
Train Loss: 1.333, Train Accuracy: 0.500
Round 24
Train Loss: 1.276, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.500
Train Loss: 0.963, Train Accuracy: 0.400
Train Loss: 1.273, Train Accuracy: 0.800
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.540, Train Accuracy: 0.500
Train Loss: 1.091, Train Accuracy: 0.400
Train Loss: 2.053, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.700
Round 25
Train Loss: 1.362, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.700
Train Loss: 0.954, Train Accuracy: 0.600
Train Loss: 1.386, Train Accuracy: 1.000
Train Loss: 1.162, Train Accuracy: 0.750
Train Loss: 1.265, Train Accuracy: 0.800
Train Loss: 1.528, Train Accuracy: 0.500
Train Loss: 1.081, Train Accuracy: 0.800
Train Loss: 2.024, Train Accuracy: 0.750
Train Loss: 1.096, Train Accuracy: 0.700
Round 26
Train Loss: 1.322, Train Accuracy: 0.750
Train Loss: 0.998, Train Accuracy: 0.700
Train Loss: 0.963, Train Accuracy: 0.600
Train Loss: 1.243, Train Accuracy: 0.800
Train Loss: 1.197, Train Accuracy: 0.750
Train Loss: 1.295, Train Accuracy: 0.800
Train Loss: 1.631, Train Accuracy: 0.500
Train Loss: 1.108, Train Accuracy: 0.800
Train Loss: 1.690, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.700
Round 27
Train Loss: 1.254, Train Accuracy: 0.750
Train Loss: 1.005, Train Accuracy: 0.600
Train Loss: 0.964, Train Accuracy: 0.600
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.173, Train Accuracy: 0.750
Train Loss: 1.295, Train Accuracy: 0.800
Train Loss: 1.480, Train Accuracy: 0.750
Train Loss: 1.104, Train Accuracy: 0.600
Train Loss: 1.852, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.600
Round 28
Train Loss: 1.378, Train Accuracy: 0.750
Train Loss: 0.983, Train Accuracy: 0.600
Train Loss: 0.929, Train Accuracy: 0.600
Train Loss: 1.373, Train Accuracy: 1.000
Train Loss: 1.168, Train Accuracy: 0.750
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.475, Train Accuracy: 0.750
Train Loss: 1.017, Train Accuracy: 0.600
Train Loss: 1.934, Train Accuracy: 0.750
Train Loss: 1.046, Train Accuracy: 0.600
Round 29
Train Loss: 1.232, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.600
Train Loss: 0.925, Train Accuracy: 0.600
Train Loss: 1.553, Train Accuracy: 0.800
Train Loss: 1.214, Train Accuracy: 0.625
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.403, Train Accuracy: 0.500
Train Loss: 1.092, Train Accuracy: 0.600
Train Loss: 1.856, Train Accuracy: 0.750
Train Loss: 1.138, Train Accuracy: 0.700
Round 30
Train Loss: 1.186, Train Accuracy: 0.750
Train Loss: 0.985, Train Accuracy: 0.700
Train Loss: 0.935, Train Accuracy: 0.600
Train Loss: 1.229, Train Accuracy: 0.600
Train Loss: 1.120, Train Accuracy: 0.875
Train Loss: 1.180, Train Accuracy: 0.800
Train Loss: 1.659, Train Accuracy: 0.500
Train Loss: 1.123, Train Accuracy: 0.800
Train Loss: 2.129, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.700
Round 31
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 0.993, Train Accuracy: 0.500
Train Loss: 0.911, Train Accuracy: 0.800
Train Loss: 1.313, Train Accuracy: 1.000
Train Loss: 1.132, Train Accuracy: 0.750
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.691, Train Accuracy: 0.500
Train Loss: 1.081, Train Accuracy: 0.400
Train Loss: 2.057, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.600
Round 32
Train Loss: 1.399, Train Accuracy: 0.750
Train Loss: 0.984, Train Accuracy: 0.600
Train Loss: 0.949, Train Accuracy: 0.600
Train Loss: 1.388, Train Accuracy: 0.800
Train Loss: 1.111, Train Accuracy: 0.500
Train Loss: 1.301, Train Accuracy: 0.800
Train Loss: 1.452, Train Accuracy: 0.500
Train Loss: 0.973, Train Accuracy: 0.600
Train Loss: 1.913, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.600
Round 33
Train Loss: 1.272, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.600
Train Loss: 0.909, Train Accuracy: 0.600
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.119, Train Accuracy: 0.750
Train Loss: 1.251, Train Accuracy: 1.000
Train Loss: 1.605, Train Accuracy: 0.750
Train Loss: 1.108, Train Accuracy: 1.000
Train Loss: 1.810, Train Accuracy: 0.750
Train Loss: 1.234, Train Accuracy: 0.600
Round 34
Train Loss: 1.371, Train Accuracy: 0.750
Train Loss: 0.992, Train Accuracy: 0.500
Train Loss: 0.940, Train Accuracy: 0.400
Train Loss: 1.229, Train Accuracy: 1.000
Train Loss: 1.154, Train Accuracy: 0.625
Train Loss: 1.240, Train Accuracy: 0.800
Train Loss: 1.342, Train Accuracy: 0.750
Train Loss: 1.242, Train Accuracy: 0.600
Train Loss: 2.148, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.700
Round 35
Train Loss: 1.186, Train Accuracy: 0.750
Train Loss: 0.952, Train Accuracy: 0.700
Train Loss: 0.940, Train Accuracy: 0.600
Train Loss: 1.473, Train Accuracy: 1.000
Train Loss: 1.146, Train Accuracy: 0.750
Train Loss: 1.284, Train Accuracy: 0.800
Train Loss: 1.689, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.800
Train Loss: 2.070, Train Accuracy: 1.000
Train Loss: 0.968, Train Accuracy: 0.600
Round 36
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 1.014, Train Accuracy: 0.600
Train Loss: 0.885, Train Accuracy: 0.400
Train Loss: 1.470, Train Accuracy: 0.600
Train Loss: 1.145, Train Accuracy: 0.500
Train Loss: 1.199, Train Accuracy: 0.800
Train Loss: 1.510, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.800
Train Loss: 2.183, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.600
Round 37
Train Loss: 1.208, Train Accuracy: 0.750
Train Loss: 0.957, Train Accuracy: 0.500
Train Loss: 0.879, Train Accuracy: 0.600
Train Loss: 1.193, Train Accuracy: 1.000
Train Loss: 1.136, Train Accuracy: 0.750
Train Loss: 1.304, Train Accuracy: 0.800
Train Loss: 1.431, Train Accuracy: 0.750
Train Loss: 0.974, Train Accuracy: 0.600
Train Loss: 2.240, Train Accuracy: 1.000
Train Loss: 0.974, Train Accuracy: 0.500
Round 38
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 0.935, Train Accuracy: 0.600
Train Loss: 0.882, Train Accuracy: 0.600
Train Loss: 1.392, Train Accuracy: 1.000
Train Loss: 1.120, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.800
Train Loss: 1.563, Train Accuracy: 1.000
Train Loss: 0.994, Train Accuracy: 0.800
Train Loss: 1.631, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.600
Round 39
Train Loss: 1.125, Train Accuracy: 0.750
Train Loss: 0.972, Train Accuracy: 0.500
Train Loss: 0.899, Train Accuracy: 1.000
Train Loss: 1.195, Train Accuracy: 1.000
Train Loss: 1.123, Train Accuracy: 0.750
Train Loss: 1.242, Train Accuracy: 0.800
Train Loss: 1.440, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.986, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.600
Round 40
Train Loss: 1.181, Train Accuracy: 0.750
Train Loss: 0.942, Train Accuracy: 0.600
Train Loss: 0.960, Train Accuracy: 0.800
Train Loss: 1.358, Train Accuracy: 0.800
Train Loss: 1.019, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.800
Train Loss: 1.602, Train Accuracy: 0.500
Train Loss: 0.984, Train Accuracy: 0.600
Train Loss: 2.157, Train Accuracy: 0.750
Train Loss: 1.099, Train Accuracy: 0.700
Round 41
Train Loss: 1.205, Train Accuracy: 0.750
Train Loss: 0.961, Train Accuracy: 0.800
Train Loss: 0.934, Train Accuracy: 0.800
Train Loss: 1.302, Train Accuracy: 1.000
Train Loss: 1.116, Train Accuracy: 0.750
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.557, Train Accuracy: 1.000
Train Loss: 0.990, Train Accuracy: 0.800
Train Loss: 1.873, Train Accuracy: 0.750
Train Loss: 0.954, Train Accuracy: 0.600
Round 42
Train Loss: 1.311, Train Accuracy: 0.750
Train Loss: 0.969, Train Accuracy: 0.700
Train Loss: 0.872, Train Accuracy: 0.600
Train Loss: 1.392, Train Accuracy: 0.800
Train Loss: 1.188, Train Accuracy: 0.875
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.578, Train Accuracy: 0.750
Train Loss: 1.127, Train Accuracy: 0.800
Train Loss: 1.873, Train Accuracy: 0.750
Train Loss: 1.104, Train Accuracy: 0.700
Round 43
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 0.935, Train Accuracy: 0.800
Train Loss: 0.862, Train Accuracy: 0.600
Train Loss: 1.474, Train Accuracy: 0.600
Train Loss: 1.099, Train Accuracy: 0.500
Train Loss: 1.218, Train Accuracy: 0.800
Train Loss: 1.788, Train Accuracy: 0.750
Train Loss: 0.960, Train Accuracy: 0.800
Train Loss: 1.821, Train Accuracy: 0.750
Train Loss: 1.234, Train Accuracy: 0.700
Round 44
Train Loss: 1.451, Train Accuracy: 0.750
Train Loss: 0.975, Train Accuracy: 0.600
Train Loss: 0.891, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 1.000
Train Loss: 1.147, Train Accuracy: 0.625
Train Loss: 1.271, Train Accuracy: 0.800
Train Loss: 1.881, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.800
Train Loss: 1.577, Train Accuracy: 0.750
Train Loss: 1.392, Train Accuracy: 0.500
Round 45
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 0.941, Train Accuracy: 0.600
Train Loss: 0.833, Train Accuracy: 0.600
Train Loss: 1.487, Train Accuracy: 0.600
Train Loss: 1.115, Train Accuracy: 0.500
Train Loss: 1.146, Train Accuracy: 0.800
Train Loss: 1.515, Train Accuracy: 0.500
Train Loss: 1.030, Train Accuracy: 0.800
Train Loss: 1.977, Train Accuracy: 0.750
Train Loss: 0.944, Train Accuracy: 0.600
Round 46
Train Loss: 1.216, Train Accuracy: 0.500
Train Loss: 0.958, Train Accuracy: 0.600
Train Loss: 0.916, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 1.000
Train Loss: 1.129, Train Accuracy: 0.625
Train Loss: 1.211, Train Accuracy: 0.800
Train Loss: 1.388, Train Accuracy: 1.000
Train Loss: 1.063, Train Accuracy: 1.000
Train Loss: 2.008, Train Accuracy: 1.000
Train Loss: 0.920, Train Accuracy: 0.600
Round 47
Train Loss: 1.160, Train Accuracy: 0.750
Train Loss: 0.912, Train Accuracy: 0.600
Train Loss: 0.837, Train Accuracy: 0.800
Train Loss: 1.159, Train Accuracy: 1.000
Train Loss: 1.131, Train Accuracy: 0.750
Train Loss: 1.208, Train Accuracy: 0.800
Train Loss: 1.828, Train Accuracy: 0.750
Train Loss: 0.956, Train Accuracy: 0.400
Train Loss: 2.018, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.700
Round 48
Train Loss: 1.220, Train Accuracy: 0.750
Train Loss: 0.975, Train Accuracy: 0.500
Train Loss: 0.853, Train Accuracy: 0.800
Train Loss: 1.492, Train Accuracy: 1.000
Train Loss: 1.105, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.800
Train Loss: 1.347, Train Accuracy: 0.750

(FLClient pid=2858566) 2025-04-11 09:05:09,037 - INFO - Epoch   2| Train Loss: 0.809| Train Accuracy: 0.750 [repeated 360x across cluster]
(FLClient pid=2858566) 2025-04-11 09:05:09,048 - INFO - Epoch   2| Validation Loss: 1.255, Validation Accuracy: 0.295 [repeated 120x across cluster]
(FLClient pid=2858566) 2025-04-11 09:05:14,275 - INFO - Epoch   2| Train Loss: 0.656| Train Accuracy: 0.750 [repeated 390x across cluster]
(FLClient pid=2858566) 2025-04-11 09:05:14,283 - INFO - Epoch   2| Validation Loss: 1.405, Validation Accuracy: 0.295 [repeated 130x across cluster]
(FLClient pid=2858566) 2025-04-11 09:05:19,378 - INFO - Epoch   2| Train Loss: 0.708| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2858566) 2025-04-11 09:05:19,386 - INFO - Epoch   2| Validation Loss: 1.269, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2858566) 2025-04-11 09:05:24,500 - INFO - Epoch   2| Train Loss: 0.702| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2858566) 2025-04-11 09:05:24,508 - INFO - Epoch   2| Validation Loss: 1.193, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2858566) 2025-04-11 09:05:29,602 - INFO - Epoch   2| Train Loss: 0.557| Train Accuracy: 0.500 [repeated 450x across cluster]
(FLClient pid=2858566) 2025-04-11 09:05:29,610 - INFO - Epoch   2| Validation Loss: 1.247, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2858566) 2025-04-11 09:05:34,693 - INFO - Epoch   1| Train Loss: 0.489| Train Accuracy: 1.000 [repeated 449x across cluster]
(FLClient pid=2858882) 2025-04-11 09:05:34,364 - INFO - Epoch   2| Validation Loss: 0.870, Validation Accuracy: 0.578 [repeated 149x across cluster]
(FLClient pid=2858566) 2025-04-11 09:05:39,777 - INFO - Epoch   0| Train Loss: 0.529| Train Accuracy: 1.000 [repeated 449x across cluster]
(FLClient pid=2858622) 2025-04-11 09:05:39,469 - INFO - Epoch   2| Validation Loss: 1.174, Validation Accuracy: 0.672 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.255, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.076, Train Accuracy: 0.200
Train Loss: 1.232, Train Accuracy: 0.600
Train Loss: 1.211, Train Accuracy: 0.625
Train Loss: 1.247, Train Accuracy: 0.800
Train Loss: 1.370, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.600
Train Loss: 1.452, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.600
Round 2
Train Loss: 1.334, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.056, Train Accuracy: 0.400
Train Loss: 1.278, Train Accuracy: 0.600
Train Loss: 1.203, Train Accuracy: 0.625
Train Loss: 1.236, Train Accuracy: 0.800
Train Loss: 1.411, Train Accuracy: 0.750
Train Loss: 1.142, Train Accuracy: 0.400
Train Loss: 1.461, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.500
Round 3
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.052, Train Accuracy: 0.400
Train Loss: 1.299, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.259, Train Accuracy: 0.800
Train Loss: 1.458, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.400
Train Loss: 1.566, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.200
Round 4
Train Loss: 1.372, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.600
Train Loss: 1.334, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.460, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.400
Train Loss: 1.608, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.400
Round 5
Train Loss: 1.317, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Train Loss: 1.044, Train Accuracy: 0.600
Train Loss: 1.349, Train Accuracy: 0.600
Train Loss: 1.278, Train Accuracy: 0.625
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.493, Train Accuracy: 0.500
Train Loss: 1.204, Train Accuracy: 0.400
Train Loss: 1.663, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.300
Round 6
Train Loss: 1.355, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.408, Train Accuracy: 0.600
Train Loss: 1.234, Train Accuracy: 0.625
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 0.500
Train Loss: 1.168, Train Accuracy: 0.600
Train Loss: 1.684, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.500
Round 7
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.500
Train Loss: 1.048, Train Accuracy: 0.200
Train Loss: 1.379, Train Accuracy: 0.600
Train Loss: 1.233, Train Accuracy: 0.625
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.495, Train Accuracy: 0.500
Train Loss: 1.198, Train Accuracy: 0.400
Train Loss: 1.748, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.400
Round 8
Train Loss: 1.393, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.500
Train Loss: 1.057, Train Accuracy: 0.400
Train Loss: 1.409, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.487, Train Accuracy: 0.500
Train Loss: 1.224, Train Accuracy: 0.400
Train Loss: 1.702, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.500
Round 9
Train Loss: 1.372, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.040, Train Accuracy: 0.600
Train Loss: 1.393, Train Accuracy: 0.600
Train Loss: 1.261, Train Accuracy: 0.625
Train Loss: 1.353, Train Accuracy: 0.800
Train Loss: 1.530, Train Accuracy: 0.500
Train Loss: 1.245, Train Accuracy: 0.600
Train Loss: 1.737, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.600
Round 10
Train Loss: 1.468, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.400
Train Loss: 1.036, Train Accuracy: 0.400
Train Loss: 1.410, Train Accuracy: 0.600
Train Loss: 1.251, Train Accuracy: 0.625
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.538, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.600
Train Loss: 1.724, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.600
Round 11
Train Loss: 1.350, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.500
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.439, Train Accuracy: 0.600
Train Loss: 1.232, Train Accuracy: 0.625
Train Loss: 1.322, Train Accuracy: 0.800
Train Loss: 1.569, Train Accuracy: 0.500
Train Loss: 1.175, Train Accuracy: 0.400
Train Loss: 1.823, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.400
Round 12
Train Loss: 1.372, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.500
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 1.413, Train Accuracy: 0.600
Train Loss: 1.234, Train Accuracy: 0.625
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.528, Train Accuracy: 0.250
Train Loss: 1.162, Train Accuracy: 0.600
Train Loss: 1.752, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.400
Round 13
Train Loss: 1.313, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.500
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.411, Train Accuracy: 0.600
Train Loss: 1.220, Train Accuracy: 0.625
Train Loss: 1.366, Train Accuracy: 0.800
Train Loss: 1.507, Train Accuracy: 0.500
Train Loss: 1.193, Train Accuracy: 0.600
Train Loss: 1.805, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.500
Round 14
Train Loss: 1.405, Train Accuracy: 0.750
Train Loss: 1.050, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.400
Train Loss: 1.376, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.549, Train Accuracy: 0.500
Train Loss: 1.178, Train Accuracy: 0.400
Train Loss: 1.842, Train Accuracy: 0.750
Train Loss: 1.155, Train Accuracy: 0.200
Round 15
Train Loss: 1.273, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.500
Train Loss: 1.020, Train Accuracy: 0.600
Train Loss: 1.427, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 0.625
Train Loss: 1.298, Train Accuracy: 0.800
Train Loss: 1.533, Train Accuracy: 0.250
Train Loss: 1.176, Train Accuracy: 0.400
Train Loss: 1.818, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.600
Round 16
Train Loss: 1.262, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.500
Train Loss: 1.017, Train Accuracy: 0.600
Train Loss: 1.435, Train Accuracy: 0.600
Train Loss: 1.212, Train Accuracy: 0.625
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.532, Train Accuracy: 0.500
Train Loss: 1.137, Train Accuracy: 0.600
Train Loss: 1.868, Train Accuracy: 0.750
Train Loss: 1.127, Train Accuracy: 0.300
Round 17
Train Loss: 1.253, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.500
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.433, Train Accuracy: 0.600
Train Loss: 1.223, Train Accuracy: 0.625
Train Loss: 1.318, Train Accuracy: 0.800
Train Loss: 1.507, Train Accuracy: 0.500
Train Loss: 1.190, Train Accuracy: 0.800
Train Loss: 1.921, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.600
Round 18
Train Loss: 1.413, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.500
Train Loss: 1.012, Train Accuracy: 0.600
Train Loss: 1.415, Train Accuracy: 0.600
Train Loss: 1.243, Train Accuracy: 0.625
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.513, Train Accuracy: 0.500
Train Loss: 1.169, Train Accuracy: 0.400
Train Loss: 1.885, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.600
Round 19
Train Loss: 1.293, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.600
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.464, Train Accuracy: 0.600
Train Loss: 1.198, Train Accuracy: 0.625
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.516, Train Accuracy: 0.500
Train Loss: 1.134, Train Accuracy: 0.600
Train Loss: 1.831, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.500
Round 20
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.600
Train Loss: 1.020, Train Accuracy: 0.400
Train Loss: 1.461, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 0.625
Train Loss: 1.322, Train Accuracy: 0.800
Train Loss: 1.514, Train Accuracy: 1.000
Train Loss: 1.131, Train Accuracy: 0.600
Train Loss: 1.917, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.400
Round 21
Train Loss: 1.481, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.600
Train Loss: 1.020, Train Accuracy: 0.600
Train Loss: 1.380, Train Accuracy: 0.600
Train Loss: 1.178, Train Accuracy: 0.625
Train Loss: 1.410, Train Accuracy: 0.800
Train Loss: 1.518, Train Accuracy: 0.750
Train Loss: 1.131, Train Accuracy: 0.400
Train Loss: 1.853, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.700
Round 22
Train Loss: 1.159, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.008, Train Accuracy: 0.400
Train Loss: 1.476, Train Accuracy: 0.600
Train Loss: 1.199, Train Accuracy: 0.750
Train Loss: 1.283, Train Accuracy: 0.800
Train Loss: 1.486, Train Accuracy: 0.500
Train Loss: 1.206, Train Accuracy: 0.800
Train Loss: 1.890, Train Accuracy: 0.750
Train Loss: 1.139, Train Accuracy: 0.600
Round 23
Train Loss: 1.404, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.400
Train Loss: 0.995, Train Accuracy: 0.400
Train Loss: 1.438, Train Accuracy: 0.800
Train Loss: 1.177, Train Accuracy: 0.625
Train Loss: 1.381, Train Accuracy: 0.800
Train Loss: 1.539, Train Accuracy: 0.500
Train Loss: 1.208, Train Accuracy: 0.400
Train Loss: 1.988, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 0.400
Round 24
Train Loss: 1.517, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.600
Train Loss: 1.000, Train Accuracy: 0.400
Train Loss: 1.423, Train Accuracy: 0.800
Train Loss: 1.177, Train Accuracy: 0.625
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.628, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.400
Train Loss: 1.900, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.700
Round 25
Train Loss: 1.344, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.700
Train Loss: 0.984, Train Accuracy: 0.400
Train Loss: 1.379, Train Accuracy: 0.600
Train Loss: 1.312, Train Accuracy: 0.625
Train Loss: 1.396, Train Accuracy: 0.800
Train Loss: 1.449, Train Accuracy: 0.500
Train Loss: 1.246, Train Accuracy: 0.800
Train Loss: 1.907, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.700
Round 26
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.700
Train Loss: 0.993, Train Accuracy: 0.600
Train Loss: 1.410, Train Accuracy: 0.600
Train Loss: 1.220, Train Accuracy: 0.625
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.544, Train Accuracy: 0.750
Train Loss: 1.138, Train Accuracy: 1.000
Train Loss: 1.903, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.600
Round 27
Train Loss: 1.451, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.500
Train Loss: 0.986, Train Accuracy: 0.200
Train Loss: 1.496, Train Accuracy: 0.800
Train Loss: 1.173, Train Accuracy: 0.750
Train Loss: 1.324, Train Accuracy: 0.800
Train Loss: 1.622, Train Accuracy: 0.500
Train Loss: 1.148, Train Accuracy: 0.600
Train Loss: 1.977, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.700
Round 28
Train Loss: 1.279, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 0.975, Train Accuracy: 0.800
Train Loss: 1.378, Train Accuracy: 0.800
Train Loss: 1.176, Train Accuracy: 0.750
Train Loss: 1.312, Train Accuracy: 0.800
Train Loss: 1.558, Train Accuracy: 0.500
Train Loss: 1.214, Train Accuracy: 0.600
Train Loss: 1.834, Train Accuracy: 0.750
Train Loss: 1.132, Train Accuracy: 0.700
Round 29
Train Loss: 1.269, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.600
Train Loss: 0.973, Train Accuracy: 0.600
Train Loss: 1.431, Train Accuracy: 0.800
Train Loss: 1.160, Train Accuracy: 0.750
Train Loss: 1.272, Train Accuracy: 0.800
Train Loss: 1.533, Train Accuracy: 0.750
Train Loss: 1.281, Train Accuracy: 0.400
Train Loss: 1.917, Train Accuracy: 0.750
Train Loss: 1.114, Train Accuracy: 0.500
Round 30
Train Loss: 1.160, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.700
Train Loss: 0.973, Train Accuracy: 0.400
Train Loss: 1.392, Train Accuracy: 0.800
Train Loss: 1.184, Train Accuracy: 0.750
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.551, Train Accuracy: 0.500
Train Loss: 1.175, Train Accuracy: 0.600
Train Loss: 1.811, Train Accuracy: 0.750
Train Loss: 1.214, Train Accuracy: 0.800
Round 31
Train Loss: 1.389, Train Accuracy: 0.750
Train Loss: 0.993, Train Accuracy: 0.500
Train Loss: 0.971, Train Accuracy: 0.600
Train Loss: 1.468, Train Accuracy: 0.800
Train Loss: 1.233, Train Accuracy: 0.750
Train Loss: 1.318, Train Accuracy: 0.800
Train Loss: 1.467, Train Accuracy: 0.500
Train Loss: 1.134, Train Accuracy: 0.800
Train Loss: 1.855, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.500
Round 32
Train Loss: 1.470, Train Accuracy: 0.750
Train Loss: 0.996, Train Accuracy: 0.700
Train Loss: 0.956, Train Accuracy: 0.400
Train Loss: 1.495, Train Accuracy: 1.000
Train Loss: 1.215, Train Accuracy: 0.625
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.490, Train Accuracy: 0.500
Train Loss: 1.111, Train Accuracy: 0.600
Train Loss: 2.121, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.400
Round 33
Train Loss: 1.338, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.700
Train Loss: 0.983, Train Accuracy: 0.600
Train Loss: 1.383, Train Accuracy: 0.800
Train Loss: 1.143, Train Accuracy: 0.750
Train Loss: 1.276, Train Accuracy: 0.800
Train Loss: 1.645, Train Accuracy: 0.500
Train Loss: 1.133, Train Accuracy: 0.800
Train Loss: 2.012, Train Accuracy: 0.750
Train Loss: 1.118, Train Accuracy: 0.600
Round 34
Train Loss: 1.470, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.600
Train Loss: 0.953, Train Accuracy: 0.800
Train Loss: 1.366, Train Accuracy: 0.800
Train Loss: 1.154, Train Accuracy: 0.750
Train Loss: 1.371, Train Accuracy: 1.000
Train Loss: 1.701, Train Accuracy: 1.000
Train Loss: 1.091, Train Accuracy: 0.600
Train Loss: 2.099, Train Accuracy: 0.750
Train Loss: 1.110, Train Accuracy: 0.600
Round 35
Train Loss: 1.294, Train Accuracy: 0.750
Train Loss: 0.993, Train Accuracy: 0.600
Train Loss: 0.945, Train Accuracy: 0.400
Train Loss: 1.516, Train Accuracy: 1.000
Train Loss: 1.264, Train Accuracy: 0.750
Train Loss: 1.259, Train Accuracy: 0.800
Train Loss: 1.580, Train Accuracy: 0.500
Train Loss: 1.220, Train Accuracy: 0.600
Train Loss: 1.922, Train Accuracy: 0.750
Train Loss: 1.127, Train Accuracy: 0.600
Round 36
Train Loss: 1.264, Train Accuracy: 0.750
Train Loss: 0.975, Train Accuracy: 0.600
Train Loss: 0.958, Train Accuracy: 0.400
Train Loss: 1.396, Train Accuracy: 0.800
Train Loss: 1.138, Train Accuracy: 0.750
Train Loss: 1.380, Train Accuracy: 0.800
Train Loss: 1.713, Train Accuracy: 0.500
Train Loss: 1.093, Train Accuracy: 1.000
Train Loss: 1.840, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.600
Round 37
Train Loss: 1.190, Train Accuracy: 0.750
Train Loss: 0.998, Train Accuracy: 0.700
Train Loss: 0.932, Train Accuracy: 0.400
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.175, Train Accuracy: 0.875
Train Loss: 1.327, Train Accuracy: 0.800
Train Loss: 1.551, Train Accuracy: 0.500
Train Loss: 1.055, Train Accuracy: 0.600
Train Loss: 1.873, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.600
Round 38
Train Loss: 1.415, Train Accuracy: 0.750
Train Loss: 0.964, Train Accuracy: 0.600
Train Loss: 0.959, Train Accuracy: 0.600
Train Loss: 1.490, Train Accuracy: 0.800
Train Loss: 1.066, Train Accuracy: 0.750
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.564, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.400
Train Loss: 1.756, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.700
Round 39
Train Loss: 1.272, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.600
Train Loss: 0.964, Train Accuracy: 0.400
Train Loss: 1.326, Train Accuracy: 0.600
Train Loss: 1.089, Train Accuracy: 0.750
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.486, Train Accuracy: 0.500
Train Loss: 1.034, Train Accuracy: 0.800
Train Loss: 2.090, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.700
Round 40
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 0.969, Train Accuracy: 0.500
Train Loss: 0.939, Train Accuracy: 0.800
Train Loss: 1.398, Train Accuracy: 0.800
Train Loss: 1.179, Train Accuracy: 0.750
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.435, Train Accuracy: 0.500
Train Loss: 1.064, Train Accuracy: 0.600
Train Loss: 2.149, Train Accuracy: 0.750
Train Loss: 1.012, Train Accuracy: 0.500
Round 41
Train Loss: 1.281, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.700
Train Loss: 0.915, Train Accuracy: 0.400
Train Loss: 1.406, Train Accuracy: 0.800
Train Loss: 1.103, Train Accuracy: 0.750
Train Loss: 1.373, Train Accuracy: 0.800
Train Loss: 1.522, Train Accuracy: 1.000
Train Loss: 1.062, Train Accuracy: 0.800
Train Loss: 2.164, Train Accuracy: 1.000
Train Loss: 1.194, Train Accuracy: 0.700
Round 42
Train Loss: 1.432, Train Accuracy: 0.750
Train Loss: 0.943, Train Accuracy: 0.500
Train Loss: 0.932, Train Accuracy: 0.800
Train Loss: 1.408, Train Accuracy: 0.800
Train Loss: 1.120, Train Accuracy: 0.875
Train Loss: 1.235, Train Accuracy: 0.800
Train Loss: 1.536, Train Accuracy: 1.000
Train Loss: 1.014, Train Accuracy: 0.800
Train Loss: 1.849, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.700
Round 43
Train Loss: 1.325, Train Accuracy: 0.750
Train Loss: 0.942, Train Accuracy: 0.700
Train Loss: 0.900, Train Accuracy: 0.600
Train Loss: 1.318, Train Accuracy: 1.000
Train Loss: 1.142, Train Accuracy: 0.750
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.584, Train Accuracy: 0.500
Train Loss: 1.012, Train Accuracy: 1.000
Train Loss: 1.961, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.800
Round 44
Train Loss: 1.193, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.700
Train Loss: 0.981, Train Accuracy: 0.800
Train Loss: 1.296, Train Accuracy: 1.000
Train Loss: 1.132, Train Accuracy: 0.875
Train Loss: 1.306, Train Accuracy: 0.800
Train Loss: 1.840, Train Accuracy: 0.500
Train Loss: 0.935, Train Accuracy: 0.800
Train Loss: 1.915, Train Accuracy: 0.500
Train Loss: 1.102, Train Accuracy: 0.700
Round 45
Train Loss: 1.236, Train Accuracy: 0.750
Train Loss: 1.025, Train Accuracy: 0.300
Train Loss: 0.898, Train Accuracy: 0.400
Train Loss: 1.460, Train Accuracy: 0.800
Train Loss: 1.032, Train Accuracy: 0.875
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.508, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.800
Train Loss: 1.939, Train Accuracy: 0.750
Train Loss: 1.121, Train Accuracy: 0.700
Round 46
Train Loss: 1.110, Train Accuracy: 0.750
Train Loss: 0.912, Train Accuracy: 0.600
Train Loss: 0.907, Train Accuracy: 0.400
Train Loss: 1.176, Train Accuracy: 0.800
Train Loss: 1.114, Train Accuracy: 0.750
Train Loss: 1.271, Train Accuracy: 0.800
Train Loss: 1.475, Train Accuracy: 0.750
Train Loss: 1.148, Train Accuracy: 0.600
Train Loss: 2.044, Train Accuracy: 1.000
Train Loss: 1.222, Train Accuracy: 0.700
Round 47
Train Loss: 1.301, Train Accuracy: 0.750
Train Loss: 0.934, Train Accuracy: 0.700
Train Loss: 0.924, Train Accuracy: 0.600
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.078, Train Accuracy: 0.750
Train Loss: 1.312, Train Accuracy: 0.800
Train Loss: 1.785, Train Accuracy: 0.500
Train Loss: 1.063, Train Accuracy: 0.600
Train Loss: 2.238, Train Accuracy: 1.000
Train Loss: 1.075, Train Accuracy: 0.900
Round 48
Train Loss: 1.265, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.300
Train Loss: 0.898, Train Accuracy: 0.600
Train Loss: 1.304, Train Accuracy: 0.800
Train Loss: 1.107, Train Accuracy: 0.750
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.583, Train Accuracy: 0.750

(FLClient pid=2859636) 2025-04-11 09:05:51,176 - INFO - Epoch   2| Train Loss: 0.802| Train Accuracy: 0.750 [repeated 362x across cluster]
(FLClient pid=2859636) 2025-04-11 09:05:51,185 - INFO - Epoch   2| Validation Loss: 1.167, Validation Accuracy: 0.295 [repeated 121x across cluster]
(FLClient pid=2859636) 2025-04-11 09:05:56,469 - INFO - Epoch   2| Train Loss: 0.656| Train Accuracy: 0.750 [repeated 390x across cluster]
(FLClient pid=2859636) 2025-04-11 09:05:56,477 - INFO - Epoch   2| Validation Loss: 1.343, Validation Accuracy: 0.295 [repeated 130x across cluster]
(FLClient pid=2859636) 2025-04-11 09:06:01,563 - INFO - Epoch   2| Train Loss: 0.617| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2859796) 2025-04-11 09:06:01,235 - INFO - Epoch   2| Validation Loss: 2.045, Validation Accuracy: 0.233 [repeated 149x across cluster]
(FLClient pid=2859636) 2025-04-11 09:06:06,665 - INFO - Epoch   2| Train Loss: 0.697| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2859636) 2025-04-11 09:06:06,673 - INFO - Epoch   2| Validation Loss: 1.413, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2859636) 2025-04-11 09:06:11,668 - INFO - Epoch   2| Train Loss: 0.455| Train Accuracy: 0.750 [repeated 420x across cluster]
(FLClient pid=2859636) 2025-04-11 09:06:11,676 - INFO - Epoch   2| Validation Loss: 1.098, Validation Accuracy: 0.295 [repeated 140x across cluster]
(FLClient pid=2859636) 2025-04-11 09:06:16,903 - INFO - Epoch   2| Train Loss: 0.713| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2859796) 2025-04-11 09:06:16,570 - INFO - Epoch   2| Validation Loss: 1.813, Validation Accuracy: 0.279 [repeated 149x across cluster]
(FLClient pid=2859636) 2025-04-11 09:06:21,899 - INFO - Epoch   2| Train Loss: 0.386| Train Accuracy: 1.000 [repeated 420x across cluster]
(FLClient pid=2859636) 2025-04-11 09:06:21,907 - INFO - Epoch   2| Validation Loss: 1.344, Validation Accuracy: 0.295 [repeated 141x across cluster]

Training done
Round 1
Train Loss: 1.167, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.042, Train Accuracy: 0.400
Train Loss: 1.230, Train Accuracy: 0.600
Train Loss: 1.194, Train Accuracy: 0.625
Train Loss: 1.205, Train Accuracy: 0.800
Train Loss: 1.330, Train Accuracy: 0.500
Train Loss: 1.122, Train Accuracy: 0.400
Train Loss: 1.467, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.500
Round 2
Train Loss: 1.204, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.249, Train Accuracy: 0.600
Train Loss: 1.200, Train Accuracy: 0.625
Train Loss: 1.221, Train Accuracy: 0.800
Train Loss: 1.370, Train Accuracy: 0.500
Train Loss: 1.135, Train Accuracy: 0.200
Train Loss: 1.517, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.400
Round 3
Train Loss: 1.210, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.600
Train Loss: 1.292, Train Accuracy: 0.600
Train Loss: 1.207, Train Accuracy: 0.625
Train Loss: 1.245, Train Accuracy: 0.800
Train Loss: 1.383, Train Accuracy: 0.500
Train Loss: 1.159, Train Accuracy: 0.600
Train Loss: 1.572, Train Accuracy: 0.750
Train Loss: 1.212, Train Accuracy: 0.400
Round 4
Train Loss: 1.238, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.500
Train Loss: 1.045, Train Accuracy: 0.400
Train Loss: 1.275, Train Accuracy: 0.600
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.241, Train Accuracy: 0.800
Train Loss: 1.372, Train Accuracy: 0.500
Train Loss: 1.164, Train Accuracy: 0.600
Train Loss: 1.612, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.500
Round 5
Train Loss: 1.252, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.304, Train Accuracy: 0.600
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.252, Train Accuracy: 0.800
Train Loss: 1.371, Train Accuracy: 0.250
Train Loss: 1.130, Train Accuracy: 0.600
Train Loss: 1.671, Train Accuracy: 0.750
Train Loss: 1.205, Train Accuracy: 0.500
Round 6
Train Loss: 1.343, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.500
Train Loss: 1.031, Train Accuracy: 0.400
Train Loss: 1.299, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.625
Train Loss: 1.241, Train Accuracy: 0.800
Train Loss: 1.418, Train Accuracy: 0.500
Train Loss: 1.146, Train Accuracy: 0.600
Train Loss: 1.766, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.600
Round 7
Train Loss: 1.214, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.700
Train Loss: 1.032, Train Accuracy: 0.400
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.199, Train Accuracy: 0.625
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.374, Train Accuracy: 0.000
Train Loss: 1.115, Train Accuracy: 0.600
Train Loss: 1.768, Train Accuracy: 0.750
Train Loss: 1.192, Train Accuracy: 0.300
Round 8
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.400
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 1.343, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.438, Train Accuracy: 1.000
Train Loss: 1.167, Train Accuracy: 0.400
Train Loss: 1.724, Train Accuracy: 0.750
Train Loss: 1.208, Train Accuracy: 0.700
Round 9
Train Loss: 1.312, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.500
Train Loss: 1.026, Train Accuracy: 0.400
Train Loss: 1.347, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.282, Train Accuracy: 0.800
Train Loss: 1.445, Train Accuracy: 0.500
Train Loss: 1.131, Train Accuracy: 0.600
Train Loss: 1.737, Train Accuracy: 0.750
Train Loss: 1.210, Train Accuracy: 0.600
Round 10
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.500
Train Loss: 1.026, Train Accuracy: 0.400
Train Loss: 1.361, Train Accuracy: 0.400
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.488, Train Accuracy: 0.750
Train Loss: 1.158, Train Accuracy: 0.400
Train Loss: 1.761, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.300
Round 11
Train Loss: 1.364, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.500
Train Loss: 1.022, Train Accuracy: 0.200
Train Loss: 1.373, Train Accuracy: 0.800
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.313, Train Accuracy: 0.800
Train Loss: 1.429, Train Accuracy: 0.500
Train Loss: 1.197, Train Accuracy: 0.400
Train Loss: 1.711, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 0.500
Round 12
Train Loss: 1.322, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.600
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.377, Train Accuracy: 0.600
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.257, Train Accuracy: 0.800
Train Loss: 1.456, Train Accuracy: 0.500
Train Loss: 1.132, Train Accuracy: 0.200
Train Loss: 1.740, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.600
Round 13
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.600
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.379, Train Accuracy: 0.600
Train Loss: 1.214, Train Accuracy: 0.750
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.402, Train Accuracy: 1.000
Train Loss: 1.157, Train Accuracy: 0.800
Train Loss: 1.915, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.400
Round 14
Train Loss: 1.343, Train Accuracy: 0.750
Train Loss: 1.050, Train Accuracy: 0.500
Train Loss: 1.017, Train Accuracy: 0.400
Train Loss: 1.367, Train Accuracy: 0.800
Train Loss: 1.213, Train Accuracy: 0.750
Train Loss: 1.286, Train Accuracy: 0.800
Train Loss: 1.442, Train Accuracy: 0.750
Train Loss: 1.097, Train Accuracy: 0.600
Train Loss: 1.901, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.600
Round 15
Train Loss: 1.194, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.500
Train Loss: 1.003, Train Accuracy: 0.400
Train Loss: 1.400, Train Accuracy: 0.400
Train Loss: 1.215, Train Accuracy: 0.625
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.513, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.600
Train Loss: 1.893, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.500
Round 16
Train Loss: 1.246, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.600
Train Loss: 1.005, Train Accuracy: 0.600
Train Loss: 1.400, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.750
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.421, Train Accuracy: 0.500
Train Loss: 1.200, Train Accuracy: 0.800
Train Loss: 1.835, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 0.500
Round 17
Train Loss: 1.339, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 1.386, Train Accuracy: 0.600
Train Loss: 1.193, Train Accuracy: 0.625
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.474, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.200
Train Loss: 1.747, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.600
Round 18
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.600
Train Loss: 0.994, Train Accuracy: 0.400
Train Loss: 1.321, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.750
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.449, Train Accuracy: 0.500
Train Loss: 1.135, Train Accuracy: 0.400
Train Loss: 1.808, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.400
Round 19
Train Loss: 1.229, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.600
Train Loss: 1.009, Train Accuracy: 0.600
Train Loss: 1.336, Train Accuracy: 0.600
Train Loss: 1.205, Train Accuracy: 0.750
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.451, Train Accuracy: 0.500
Train Loss: 1.096, Train Accuracy: 0.400
Train Loss: 1.905, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.800
Round 20
Train Loss: 1.325, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.400
Train Loss: 0.993, Train Accuracy: 0.400
Train Loss: 1.403, Train Accuracy: 0.400
Train Loss: 1.182, Train Accuracy: 0.750
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.506, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.800
Train Loss: 1.736, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.700
Round 21
Train Loss: 1.333, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.800
Train Loss: 1.007, Train Accuracy: 0.600
Train Loss: 1.415, Train Accuracy: 0.800
Train Loss: 1.204, Train Accuracy: 0.750
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.495, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.600
Train Loss: 1.793, Train Accuracy: 0.750
Train Loss: 1.127, Train Accuracy: 0.600
Round 22
Train Loss: 1.356, Train Accuracy: 0.750
Train Loss: 1.022, Train Accuracy: 0.600
Train Loss: 0.978, Train Accuracy: 0.600
Train Loss: 1.333, Train Accuracy: 0.800
Train Loss: 1.205, Train Accuracy: 0.750
Train Loss: 1.369, Train Accuracy: 0.800
Train Loss: 1.470, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.800
Train Loss: 2.009, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.600
Round 23
Train Loss: 1.368, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.600
Train Loss: 0.987, Train Accuracy: 0.800
Train Loss: 1.440, Train Accuracy: 1.000
Train Loss: 1.208, Train Accuracy: 0.750
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.547, Train Accuracy: 0.500
Train Loss: 1.118, Train Accuracy: 0.800
Train Loss: 1.829, Train Accuracy: 0.750
Train Loss: 1.107, Train Accuracy: 0.600
Round 24
Train Loss: 1.345, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.600
Train Loss: 0.987, Train Accuracy: 0.800
Train Loss: 1.330, Train Accuracy: 0.600
Train Loss: 1.180, Train Accuracy: 0.625
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.695, Train Accuracy: 0.500
Train Loss: 1.097, Train Accuracy: 0.600
Train Loss: 1.980, Train Accuracy: 1.000
Train Loss: 1.111, Train Accuracy: 0.400
Round 25
Train Loss: 1.495, Train Accuracy: 0.750
Train Loss: 1.013, Train Accuracy: 0.600
Train Loss: 0.964, Train Accuracy: 0.800
Train Loss: 1.438, Train Accuracy: 1.000
Train Loss: 1.164, Train Accuracy: 0.875
Train Loss: 1.245, Train Accuracy: 0.800
Train Loss: 1.385, Train Accuracy: 0.500
Train Loss: 1.120, Train Accuracy: 0.800
Train Loss: 1.892, Train Accuracy: 1.000
Train Loss: 1.080, Train Accuracy: 0.300
Round 26
Train Loss: 1.337, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.500
Train Loss: 0.982, Train Accuracy: 0.800
Train Loss: 1.427, Train Accuracy: 1.000
Train Loss: 1.147, Train Accuracy: 0.625
Train Loss: 1.333, Train Accuracy: 0.800
Train Loss: 1.451, Train Accuracy: 0.750
Train Loss: 1.095, Train Accuracy: 0.600
Train Loss: 1.959, Train Accuracy: 0.750
Train Loss: 1.097, Train Accuracy: 0.500
Round 27
Train Loss: 1.366, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.600
Train Loss: 0.980, Train Accuracy: 0.600
Train Loss: 1.529, Train Accuracy: 1.000
Train Loss: 1.163, Train Accuracy: 0.750
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.485, Train Accuracy: 0.750
Train Loss: 1.101, Train Accuracy: 0.600
Train Loss: 2.043, Train Accuracy: 0.750
Train Loss: 1.097, Train Accuracy: 0.700
Round 28
Train Loss: 1.256, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.600
Train Loss: 0.984, Train Accuracy: 0.600
Train Loss: 1.375, Train Accuracy: 1.000
Train Loss: 1.127, Train Accuracy: 0.500
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.380, Train Accuracy: 0.500
Train Loss: 1.109, Train Accuracy: 0.800
Train Loss: 2.045, Train Accuracy: 0.750
Train Loss: 1.089, Train Accuracy: 0.600
Round 29
Train Loss: 1.353, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.700
Train Loss: 0.975, Train Accuracy: 0.800
Train Loss: 1.444, Train Accuracy: 0.800
Train Loss: 1.134, Train Accuracy: 0.375
Train Loss: 1.375, Train Accuracy: 0.800
Train Loss: 1.601, Train Accuracy: 0.750
Train Loss: 1.003, Train Accuracy: 0.600
Train Loss: 1.790, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Round 30
Train Loss: 1.298, Train Accuracy: 0.750
Train Loss: 0.998, Train Accuracy: 0.500
Train Loss: 0.965, Train Accuracy: 0.800
Train Loss: 1.312, Train Accuracy: 1.000
Train Loss: 1.196, Train Accuracy: 0.750
Train Loss: 1.266, Train Accuracy: 0.800
Train Loss: 1.367, Train Accuracy: 0.500
Train Loss: 1.054, Train Accuracy: 0.600
Train Loss: 1.939, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.400
Round 31
Train Loss: 1.276, Train Accuracy: 0.750
Train Loss: 0.988, Train Accuracy: 0.700
Train Loss: 0.962, Train Accuracy: 0.400
Train Loss: 1.333, Train Accuracy: 0.800
Train Loss: 1.228, Train Accuracy: 0.875
Train Loss: 1.275, Train Accuracy: 0.800
Train Loss: 1.503, Train Accuracy: 1.000
Train Loss: 1.022, Train Accuracy: 0.600
Train Loss: 1.780, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.500
Round 32
Train Loss: 1.273, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.700
Train Loss: 0.971, Train Accuracy: 0.600
Train Loss: 1.402, Train Accuracy: 0.800
Train Loss: 1.101, Train Accuracy: 0.875
Train Loss: 1.266, Train Accuracy: 0.800
Train Loss: 1.474, Train Accuracy: 0.500
Train Loss: 1.109, Train Accuracy: 0.600
Train Loss: 1.899, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.400
Round 33
Train Loss: 1.229, Train Accuracy: 0.750
Train Loss: 0.982, Train Accuracy: 0.700
Train Loss: 0.938, Train Accuracy: 0.600
Train Loss: 1.305, Train Accuracy: 0.800
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.345, Train Accuracy: 0.800
Train Loss: 1.638, Train Accuracy: 0.500
Train Loss: 1.069, Train Accuracy: 0.800
Train Loss: 2.235, Train Accuracy: 1.000
Train Loss: 1.108, Train Accuracy: 0.700
Round 34
Train Loss: 1.327, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.500
Train Loss: 0.956, Train Accuracy: 0.800
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.152, Train Accuracy: 0.750
Train Loss: 1.264, Train Accuracy: 0.800
Train Loss: 1.481, Train Accuracy: 1.000
Train Loss: 1.214, Train Accuracy: 0.600
Train Loss: 1.948, Train Accuracy: 0.750
Train Loss: 1.110, Train Accuracy: 0.800
Round 35
Train Loss: 1.404, Train Accuracy: 0.750
Train Loss: 0.968, Train Accuracy: 0.500
Train Loss: 0.923, Train Accuracy: 0.200
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.191, Train Accuracy: 0.500
Train Loss: 1.257, Train Accuracy: 0.800
Train Loss: 1.674, Train Accuracy: 1.000
Train Loss: 1.257, Train Accuracy: 0.800
Train Loss: 2.064, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.700
Round 36
Train Loss: 1.270, Train Accuracy: 0.750
Train Loss: 0.981, Train Accuracy: 0.600
Train Loss: 1.014, Train Accuracy: 0.800
Train Loss: 1.149, Train Accuracy: 0.600
Train Loss: 1.144, Train Accuracy: 0.500
Train Loss: 1.238, Train Accuracy: 0.800
Train Loss: 1.369, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.800
Train Loss: 1.895, Train Accuracy: 0.750
Train Loss: 1.233, Train Accuracy: 0.700
Round 37
Train Loss: 1.227, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.600
Train Loss: 0.931, Train Accuracy: 0.600
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.167, Train Accuracy: 0.375
Train Loss: 1.257, Train Accuracy: 0.800
Train Loss: 1.601, Train Accuracy: 0.500
Train Loss: 1.069, Train Accuracy: 0.600
Train Loss: 2.001, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 0.800
Round 38
Train Loss: 1.347, Train Accuracy: 0.750
Train Loss: 0.993, Train Accuracy: 0.600
Train Loss: 0.916, Train Accuracy: 0.400
Train Loss: 1.398, Train Accuracy: 0.800
Train Loss: 1.093, Train Accuracy: 0.750
Train Loss: 1.295, Train Accuracy: 0.800
Train Loss: 1.531, Train Accuracy: 1.000
Train Loss: 1.108, Train Accuracy: 0.800
Train Loss: 1.886, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.900
Round 39
Train Loss: 1.305, Train Accuracy: 0.750
Train Loss: 0.947, Train Accuracy: 0.800
Train Loss: 0.907, Train Accuracy: 0.600
Train Loss: 1.248, Train Accuracy: 1.000
Train Loss: 1.085, Train Accuracy: 0.750
Train Loss: 1.259, Train Accuracy: 0.800
Train Loss: 1.556, Train Accuracy: 0.500
Train Loss: 1.015, Train Accuracy: 0.800
Train Loss: 1.764, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.700
Round 40
Train Loss: 1.250, Train Accuracy: 0.750
Train Loss: 0.933, Train Accuracy: 0.700
Train Loss: 0.896, Train Accuracy: 0.600
Train Loss: 1.273, Train Accuracy: 1.000
Train Loss: 1.155, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.800
Train Loss: 1.467, Train Accuracy: 0.750
Train Loss: 1.094, Train Accuracy: 0.800
Train Loss: 2.112, Train Accuracy: 0.750
Train Loss: 1.128, Train Accuracy: 0.600
Round 41
Train Loss: 1.371, Train Accuracy: 0.750
Train Loss: 0.967, Train Accuracy: 0.700
Train Loss: 0.924, Train Accuracy: 0.400
Train Loss: 1.237, Train Accuracy: 0.800
Train Loss: 1.090, Train Accuracy: 0.875
Train Loss: 1.293, Train Accuracy: 0.800
Train Loss: 1.667, Train Accuracy: 1.000
Train Loss: 1.025, Train Accuracy: 0.600
Train Loss: 1.804, Train Accuracy: 0.750
Train Loss: 1.225, Train Accuracy: 0.600
Round 42
Train Loss: 1.278, Train Accuracy: 0.750
Train Loss: 0.934, Train Accuracy: 0.800
Train Loss: 0.889, Train Accuracy: 0.800
Train Loss: 1.238, Train Accuracy: 0.800
Train Loss: 1.171, Train Accuracy: 0.875
Train Loss: 1.258, Train Accuracy: 1.000
Train Loss: 1.761, Train Accuracy: 1.000
Train Loss: 0.993, Train Accuracy: 0.800
Train Loss: 1.926, Train Accuracy: 1.000
Train Loss: 1.020, Train Accuracy: 0.700
Round 43
Train Loss: 1.239, Train Accuracy: 0.750
Train Loss: 0.952, Train Accuracy: 0.600
Train Loss: 0.934, Train Accuracy: 0.800
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.116, Train Accuracy: 0.625
Train Loss: 1.243, Train Accuracy: 0.800
Train Loss: 1.546, Train Accuracy: 0.500
Train Loss: 0.961, Train Accuracy: 0.800
Train Loss: 1.658, Train Accuracy: 0.750
Train Loss: 1.089, Train Accuracy: 0.800
Round 44
Train Loss: 1.413, Train Accuracy: 0.750
Train Loss: 0.923, Train Accuracy: 0.700
Train Loss: 0.895, Train Accuracy: 0.800
Train Loss: 1.277, Train Accuracy: 1.000
Train Loss: 1.160, Train Accuracy: 0.625
Train Loss: 1.318, Train Accuracy: 0.800
Train Loss: 1.749, Train Accuracy: 0.750
Train Loss: 1.190, Train Accuracy: 1.000
Train Loss: 1.810, Train Accuracy: 0.750
Train Loss: 1.218, Train Accuracy: 0.600
Round 45
Train Loss: 1.194, Train Accuracy: 0.750
Train Loss: 0.969, Train Accuracy: 0.300
Train Loss: 0.921, Train Accuracy: 0.600
Train Loss: 1.391, Train Accuracy: 1.000
Train Loss: 1.105, Train Accuracy: 0.625
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.695, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.400
Train Loss: 2.066, Train Accuracy: 0.750
Train Loss: 0.948, Train Accuracy: 0.800
Round 46
Train Loss: 1.158, Train Accuracy: 0.750
Train Loss: 0.936, Train Accuracy: 0.800
Train Loss: 0.873, Train Accuracy: 0.600
Train Loss: 1.543, Train Accuracy: 0.800
Train Loss: 1.236, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 1.000
Train Loss: 1.690, Train Accuracy: 1.000
Train Loss: 1.044, Train Accuracy: 0.600
Train Loss: 1.807, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.700
Round 47
Train Loss: 1.383, Train Accuracy: 0.750
Train Loss: 0.906, Train Accuracy: 0.700
Train Loss: 0.855, Train Accuracy: 0.600
Train Loss: 1.317, Train Accuracy: 1.000
Train Loss: 1.211, Train Accuracy: 0.875
Train Loss: 1.305, Train Accuracy: 1.000
Train Loss: 1.600, Train Accuracy: 0.750
Train Loss: 0.983, Train Accuracy: 0.800
Train Loss: 1.818, Train Accuracy: 0.750
Train Loss: 0.968, Train Accuracy: 0.700
Round 48
Train Loss: 1.252, Train Accuracy: 0.750
Train Loss: 0.941, Train Accuracy: 0.700
Train Loss: 0.878, Train Accuracy: 0.400
Train Loss: 1.428, Train Accuracy: 1.000
Train Loss: 1.076, Train Accuracy: 0.625
Train Loss: 1.190, Train Accuracy: 0.800
Train Loss: 1.597, Train Accuracy: 1.000

(FLClient pid=2860693) 2025-04-11 09:06:33,979 - INFO - Epoch   2| Train Loss: 0.787| Train Accuracy: 0.750 [repeated 420x across cluster]
(FLClient pid=2860693) 2025-04-11 09:06:33,987 - INFO - Epoch   2| Validation Loss: 1.215, Validation Accuracy: 0.295 [repeated 140x across cluster]
(FLClient pid=2860910) 2025-04-11 09:06:39,121 - INFO - Epoch   0| Train Loss: 1.143| Train Accuracy: 0.400 [repeated 388x across cluster]
(FLClient pid=2860856) 2025-04-11 09:06:38,811 - INFO - Epoch   2| Validation Loss: 1.682, Validation Accuracy: 0.233 [repeated 129x across cluster]
(FLClient pid=2860910) 2025-04-11 09:06:44,253 - INFO - Epoch   2| Train Loss: 0.863| Train Accuracy: 0.700 [repeated 452x across cluster]
(FLClient pid=2860910) 2025-04-11 09:06:44,259 - INFO - Epoch   2| Validation Loss: 1.120, Validation Accuracy: 0.344 [repeated 151x across cluster]
(FLClient pid=2860910) 2025-04-11 09:06:49,384 - INFO - Epoch   2| Train Loss: 0.879| Train Accuracy: 0.500 [repeated 450x across cluster]
(FLClient pid=2860910) 2025-04-11 09:06:49,389 - INFO - Epoch   2| Validation Loss: 1.171, Validation Accuracy: 0.156 [repeated 150x across cluster]
(FLClient pid=2860910) 2025-04-11 09:06:54,493 - INFO - Epoch   2| Train Loss: 0.780| Train Accuracy: 0.600 [repeated 450x across cluster]
(FLClient pid=2860910) 2025-04-11 09:06:54,497 - INFO - Epoch   2| Validation Loss: 0.959, Validation Accuracy: 0.531 [repeated 150x across cluster]
(FLClient pid=2860910) 2025-04-11 09:06:59,635 - INFO - Epoch   2| Train Loss: 0.699| Train Accuracy: 0.700 [repeated 450x across cluster]
(FLClient pid=2860910) 2025-04-11 09:06:59,643 - INFO - Epoch   2| Validation Loss: 1.249, Validation Accuracy: 0.172 [repeated 150x across cluster]
(FLClient pid=2860910) 2025-04-11 09:07:04,754 - INFO - Epoch   2| Train Loss: 0.416| Train Accuracy: 1.000 [repeated 450x across cluster]
(FLClient pid=2860910) 2025-04-11 09:07:04,761 - INFO - Epoch   2| Validation Loss: 0.877, Validation Accuracy: 0.594 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.215, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.068, Train Accuracy: 0.400
Train Loss: 1.206, Train Accuracy: 0.600
Train Loss: 1.169, Train Accuracy: 0.625
Train Loss: 1.244, Train Accuracy: 0.800
Train Loss: 1.321, Train Accuracy: 0.250
Train Loss: 1.128, Train Accuracy: 0.400
Train Loss: 1.431, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.500
Round 2
Train Loss: 1.214, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.056, Train Accuracy: 0.400
Train Loss: 1.238, Train Accuracy: 0.600
Train Loss: 1.190, Train Accuracy: 0.625
Train Loss: 1.266, Train Accuracy: 0.800
Train Loss: 1.347, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.400
Train Loss: 1.508, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.300
Round 3
Train Loss: 1.225, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.049, Train Accuracy: 0.400
Train Loss: 1.265, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.625
Train Loss: 1.254, Train Accuracy: 0.800
Train Loss: 1.378, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.000
Train Loss: 1.560, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.400
Round 4
Train Loss: 1.248, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.050, Train Accuracy: 0.200
Train Loss: 1.305, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.260, Train Accuracy: 0.800
Train Loss: 1.397, Train Accuracy: 0.500
Train Loss: 1.163, Train Accuracy: 0.400
Train Loss: 1.538, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.200
Round 5
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.052, Train Accuracy: 0.400
Train Loss: 1.362, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.625
Train Loss: 1.267, Train Accuracy: 0.800
Train Loss: 1.400, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.600
Train Loss: 1.648, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.500
Round 6
Train Loss: 1.348, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 1.363, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.411, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.400
Train Loss: 1.594, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.400
Round 7
Train Loss: 1.313, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.036, Train Accuracy: 0.600
Train Loss: 1.338, Train Accuracy: 0.600
Train Loss: 1.234, Train Accuracy: 0.625
Train Loss: 1.276, Train Accuracy: 0.800
Train Loss: 1.443, Train Accuracy: 1.000
Train Loss: 1.158, Train Accuracy: 0.400
Train Loss: 1.724, Train Accuracy: 0.750
Train Loss: 1.190, Train Accuracy: 0.400
Round 8
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.032, Train Accuracy: 0.600
Train Loss: 1.336, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.257, Train Accuracy: 0.800
Train Loss: 1.435, Train Accuracy: 0.500
Train Loss: 1.156, Train Accuracy: 0.400
Train Loss: 1.675, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.600
Round 9
Train Loss: 1.312, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.031, Train Accuracy: 0.400
Train Loss: 1.389, Train Accuracy: 0.600
Train Loss: 1.248, Train Accuracy: 0.625
Train Loss: 1.242, Train Accuracy: 0.800
Train Loss: 1.488, Train Accuracy: 0.750
Train Loss: 1.129, Train Accuracy: 0.600
Train Loss: 1.725, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.600
Round 10
Train Loss: 1.339, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.032, Train Accuracy: 0.400
Train Loss: 1.406, Train Accuracy: 0.600
Train Loss: 1.210, Train Accuracy: 0.625
Train Loss: 1.283, Train Accuracy: 0.800
Train Loss: 1.475, Train Accuracy: 0.500
Train Loss: 1.165, Train Accuracy: 0.600
Train Loss: 1.672, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.400
Round 11
Train Loss: 1.347, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.500
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.378, Train Accuracy: 0.600
Train Loss: 1.255, Train Accuracy: 0.625
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.470, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.800
Train Loss: 1.789, Train Accuracy: 0.750
Train Loss: 1.220, Train Accuracy: 0.500
Round 12
Train Loss: 1.339, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.200
Train Loss: 1.359, Train Accuracy: 0.600
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.482, Train Accuracy: 0.500
Train Loss: 1.127, Train Accuracy: 0.400
Train Loss: 1.827, Train Accuracy: 0.750
Train Loss: 1.139, Train Accuracy: 0.600
Round 13
Train Loss: 1.242, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.027, Train Accuracy: 0.400
Train Loss: 1.416, Train Accuracy: 0.600
Train Loss: 1.222, Train Accuracy: 0.625
Train Loss: 1.307, Train Accuracy: 0.800
Train Loss: 1.451, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.800
Train Loss: 1.682, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.500
Round 14
Train Loss: 1.327, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.500
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.414, Train Accuracy: 0.600
Train Loss: 1.214, Train Accuracy: 0.625
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.434, Train Accuracy: 0.250
Train Loss: 1.150, Train Accuracy: 0.800
Train Loss: 1.716, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.400
Round 15
Train Loss: 1.395, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 1.388, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.509, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.400
Train Loss: 1.818, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.300
Round 16
Train Loss: 1.282, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.400
Train Loss: 1.021, Train Accuracy: 0.600
Train Loss: 1.369, Train Accuracy: 0.600
Train Loss: 1.233, Train Accuracy: 0.750
Train Loss: 1.313, Train Accuracy: 0.800
Train Loss: 1.503, Train Accuracy: 0.250
Train Loss: 1.186, Train Accuracy: 0.200
Train Loss: 1.883, Train Accuracy: 0.750
Train Loss: 1.262, Train Accuracy: 0.700
Round 17
Train Loss: 1.252, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.500
Train Loss: 1.018, Train Accuracy: 0.400
Train Loss: 1.418, Train Accuracy: 0.800
Train Loss: 1.233, Train Accuracy: 0.625
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.469, Train Accuracy: 0.500
Train Loss: 1.151, Train Accuracy: 0.600
Train Loss: 1.836, Train Accuracy: 0.750
Train Loss: 1.129, Train Accuracy: 0.500
Round 18
Train Loss: 1.349, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.500
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.433, Train Accuracy: 0.600
Train Loss: 1.215, Train Accuracy: 0.625
Train Loss: 1.366, Train Accuracy: 0.800
Train Loss: 1.421, Train Accuracy: 0.500
Train Loss: 1.152, Train Accuracy: 0.200
Train Loss: 1.873, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.600
Round 19
Train Loss: 1.347, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.500
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.435, Train Accuracy: 0.800
Train Loss: 1.196, Train Accuracy: 0.750
Train Loss: 1.347, Train Accuracy: 0.800
Train Loss: 1.507, Train Accuracy: 1.000
Train Loss: 1.140, Train Accuracy: 0.200
Train Loss: 1.746, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.500
Round 20
Train Loss: 1.494, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.700
Train Loss: 1.009, Train Accuracy: 0.400
Train Loss: 1.397, Train Accuracy: 0.600
Train Loss: 1.216, Train Accuracy: 0.625
Train Loss: 1.362, Train Accuracy: 0.800
Train Loss: 1.421, Train Accuracy: 0.500
Train Loss: 1.116, Train Accuracy: 0.200
Train Loss: 1.772, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.500
Round 21
Train Loss: 1.282, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.600
Train Loss: 1.005, Train Accuracy: 0.400
Train Loss: 1.368, Train Accuracy: 0.800
Train Loss: 1.196, Train Accuracy: 0.625
Train Loss: 1.403, Train Accuracy: 0.800
Train Loss: 1.556, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.400
Train Loss: 1.675, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.600
Round 22
Train Loss: 1.316, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.600
Train Loss: 1.003, Train Accuracy: 0.800
Train Loss: 1.370, Train Accuracy: 0.600
Train Loss: 1.208, Train Accuracy: 0.625
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.559, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.600
Train Loss: 1.664, Train Accuracy: 0.750
Train Loss: 1.205, Train Accuracy: 0.700
Round 23
Train Loss: 1.301, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.309, Train Accuracy: 0.600
Train Loss: 1.200, Train Accuracy: 0.750
Train Loss: 1.363, Train Accuracy: 0.800
Train Loss: 1.467, Train Accuracy: 1.000
Train Loss: 1.242, Train Accuracy: 0.800
Train Loss: 1.815, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.700
Round 24
Train Loss: 1.347, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.600
Train Loss: 1.005, Train Accuracy: 0.400
Train Loss: 1.410, Train Accuracy: 0.400
Train Loss: 1.184, Train Accuracy: 0.875
Train Loss: 1.390, Train Accuracy: 0.800
Train Loss: 1.492, Train Accuracy: 0.500
Train Loss: 1.168, Train Accuracy: 0.600
Train Loss: 2.010, Train Accuracy: 0.750
Train Loss: 1.116, Train Accuracy: 0.300
Round 25
Train Loss: 1.335, Train Accuracy: 0.750
Train Loss: 1.050, Train Accuracy: 0.800
Train Loss: 0.983, Train Accuracy: 0.400
Train Loss: 1.372, Train Accuracy: 0.600
Train Loss: 1.189, Train Accuracy: 0.750
Train Loss: 1.405, Train Accuracy: 0.800
Train Loss: 1.476, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.600
Train Loss: 1.901, Train Accuracy: 0.750
Train Loss: 1.139, Train Accuracy: 0.500
Round 26
Train Loss: 1.265, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.500
Train Loss: 0.984, Train Accuracy: 0.400
Train Loss: 1.427, Train Accuracy: 0.600
Train Loss: 1.159, Train Accuracy: 0.625
Train Loss: 1.363, Train Accuracy: 0.800
Train Loss: 1.611, Train Accuracy: 0.250
Train Loss: 1.065, Train Accuracy: 0.600
Train Loss: 1.776, Train Accuracy: 0.750
Train Loss: 1.115, Train Accuracy: 0.400
Round 27
Train Loss: 1.372, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.600
Train Loss: 0.982, Train Accuracy: 0.600
Train Loss: 1.307, Train Accuracy: 0.600
Train Loss: 1.188, Train Accuracy: 0.750
Train Loss: 1.286, Train Accuracy: 0.800
Train Loss: 1.465, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.400
Train Loss: 1.983, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.600
Round 28
Train Loss: 1.320, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.500
Train Loss: 0.977, Train Accuracy: 0.600
Train Loss: 1.424, Train Accuracy: 0.600
Train Loss: 1.223, Train Accuracy: 0.625
Train Loss: 1.367, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 0.750
Train Loss: 1.124, Train Accuracy: 0.600
Train Loss: 1.950, Train Accuracy: 0.750
Train Loss: 1.123, Train Accuracy: 0.600
Round 29
Train Loss: 1.226, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.700
Train Loss: 0.976, Train Accuracy: 0.800
Train Loss: 1.245, Train Accuracy: 0.600
Train Loss: 1.184, Train Accuracy: 0.750
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.534, Train Accuracy: 1.000
Train Loss: 1.148, Train Accuracy: 0.600
Train Loss: 2.109, Train Accuracy: 0.750
Train Loss: 1.120, Train Accuracy: 0.700
Round 30
Train Loss: 1.355, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 0.975, Train Accuracy: 0.600
Train Loss: 1.442, Train Accuracy: 1.000
Train Loss: 1.168, Train Accuracy: 0.625
Train Loss: 1.288, Train Accuracy: 0.800
Train Loss: 1.606, Train Accuracy: 0.500
Train Loss: 1.150, Train Accuracy: 0.800
Train Loss: 1.898, Train Accuracy: 0.750
Train Loss: 1.118, Train Accuracy: 0.400
Round 31
Train Loss: 1.310, Train Accuracy: 0.750
Train Loss: 1.014, Train Accuracy: 0.600
Train Loss: 0.998, Train Accuracy: 0.400
Train Loss: 1.324, Train Accuracy: 1.000
Train Loss: 1.238, Train Accuracy: 0.750
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.444, Train Accuracy: 0.750
Train Loss: 1.110, Train Accuracy: 0.600
Train Loss: 1.910, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.400
Round 32
Train Loss: 1.279, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.600
Train Loss: 0.956, Train Accuracy: 0.800
Train Loss: 1.322, Train Accuracy: 1.000
Train Loss: 1.156, Train Accuracy: 0.625
Train Loss: 1.359, Train Accuracy: 0.800
Train Loss: 1.425, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.800
Train Loss: 1.715, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.700
Round 33
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.600
Train Loss: 0.959, Train Accuracy: 0.600
Train Loss: 1.359, Train Accuracy: 0.800
Train Loss: 1.189, Train Accuracy: 0.750
Train Loss: 1.329, Train Accuracy: 0.800
Train Loss: 1.582, Train Accuracy: 0.500
Train Loss: 1.112, Train Accuracy: 0.800
Train Loss: 2.021, Train Accuracy: 1.000
Train Loss: 1.092, Train Accuracy: 0.700
Round 34
Train Loss: 1.403, Train Accuracy: 0.750
Train Loss: 1.007, Train Accuracy: 0.600
Train Loss: 0.939, Train Accuracy: 0.600
Train Loss: 1.393, Train Accuracy: 1.000
Train Loss: 1.096, Train Accuracy: 0.500
Train Loss: 1.313, Train Accuracy: 0.800
Train Loss: 1.593, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.600
Train Loss: 1.874, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.800
Round 35
Train Loss: 1.246, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.600
Train Loss: 0.957, Train Accuracy: 0.600
Train Loss: 1.338, Train Accuracy: 0.600
Train Loss: 1.157, Train Accuracy: 0.750
Train Loss: 1.422, Train Accuracy: 0.800
Train Loss: 1.692, Train Accuracy: 0.500
Train Loss: 1.163, Train Accuracy: 1.000
Train Loss: 1.920, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.800
Round 36
Train Loss: 1.159, Train Accuracy: 0.750
Train Loss: 0.987, Train Accuracy: 0.500
Train Loss: 0.951, Train Accuracy: 0.600
Train Loss: 1.287, Train Accuracy: 0.800
Train Loss: 1.116, Train Accuracy: 0.625
Train Loss: 1.242, Train Accuracy: 0.800
Train Loss: 1.501, Train Accuracy: 1.000
Train Loss: 1.058, Train Accuracy: 0.600
Train Loss: 1.918, Train Accuracy: 0.750
Train Loss: 1.025, Train Accuracy: 0.600
Round 37
Train Loss: 1.210, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.700
Train Loss: 0.931, Train Accuracy: 0.400
Train Loss: 1.239, Train Accuracy: 0.800
Train Loss: 1.143, Train Accuracy: 0.750
Train Loss: 1.270, Train Accuracy: 0.800
Train Loss: 1.583, Train Accuracy: 1.000
Train Loss: 1.117, Train Accuracy: 0.600
Train Loss: 1.967, Train Accuracy: 0.750
Train Loss: 1.104, Train Accuracy: 0.500
Round 38
Train Loss: 1.342, Train Accuracy: 0.750
Train Loss: 0.983, Train Accuracy: 0.800
Train Loss: 0.936, Train Accuracy: 0.600
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.102, Train Accuracy: 0.750
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.594, Train Accuracy: 1.000
Train Loss: 1.118, Train Accuracy: 0.600
Train Loss: 1.915, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.900
Round 39
Train Loss: 1.240, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.500
Train Loss: 0.934, Train Accuracy: 0.600
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.113, Train Accuracy: 0.750
Train Loss: 1.346, Train Accuracy: 0.800
Train Loss: 1.410, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.600
Train Loss: 2.000, Train Accuracy: 1.000
Train Loss: 1.034, Train Accuracy: 0.600
Round 40
Train Loss: 1.324, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.800
Train Loss: 0.958, Train Accuracy: 0.600
Train Loss: 1.480, Train Accuracy: 0.800
Train Loss: 1.137, Train Accuracy: 0.750
Train Loss: 1.232, Train Accuracy: 0.800
Train Loss: 1.548, Train Accuracy: 0.500
Train Loss: 0.997, Train Accuracy: 0.600
Train Loss: 2.160, Train Accuracy: 0.750
Train Loss: 1.259, Train Accuracy: 0.500
Round 41
Train Loss: 1.218, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.800
Train Loss: 0.938, Train Accuracy: 0.200
Train Loss: 1.162, Train Accuracy: 0.600
Train Loss: 1.123, Train Accuracy: 0.500
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.329, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 2.010, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.700
Round 42
Train Loss: 1.417, Train Accuracy: 0.750
Train Loss: 0.957, Train Accuracy: 0.500
Train Loss: 0.894, Train Accuracy: 0.600
Train Loss: 1.168, Train Accuracy: 1.000
Train Loss: 1.097, Train Accuracy: 0.500
Train Loss: 1.262, Train Accuracy: 0.800
Train Loss: 1.474, Train Accuracy: 0.500
Train Loss: 1.025, Train Accuracy: 0.600
Train Loss: 1.962, Train Accuracy: 0.750
Train Loss: 1.088, Train Accuracy: 0.500
Round 43
Train Loss: 1.325, Train Accuracy: 0.750
Train Loss: 0.973, Train Accuracy: 0.500
Train Loss: 0.918, Train Accuracy: 0.800
Train Loss: 1.292, Train Accuracy: 0.600
Train Loss: 1.109, Train Accuracy: 0.500
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.423, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.200
Train Loss: 1.836, Train Accuracy: 0.500
Train Loss: 1.073, Train Accuracy: 0.600
Round 44
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 0.960, Train Accuracy: 0.900
Train Loss: 0.941, Train Accuracy: 0.600
Train Loss: 1.439, Train Accuracy: 1.000
Train Loss: 1.159, Train Accuracy: 0.625
Train Loss: 1.255, Train Accuracy: 0.800
Train Loss: 1.492, Train Accuracy: 1.000
Train Loss: 1.008, Train Accuracy: 0.400
Train Loss: 1.851, Train Accuracy: 1.000
Train Loss: 1.171, Train Accuracy: 0.500
Round 45
Train Loss: 1.255, Train Accuracy: 0.750
Train Loss: 0.943, Train Accuracy: 0.600
Train Loss: 0.880, Train Accuracy: 0.400
Train Loss: 1.268, Train Accuracy: 0.600
Train Loss: 1.085, Train Accuracy: 0.750
Train Loss: 1.337, Train Accuracy: 1.000
Train Loss: 1.610, Train Accuracy: 0.500
Train Loss: 1.026, Train Accuracy: 0.200
Train Loss: 2.126, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.700
Round 46
Train Loss: 1.193, Train Accuracy: 0.750
Train Loss: 0.982, Train Accuracy: 0.600
Train Loss: 0.948, Train Accuracy: 0.600
Train Loss: 1.176, Train Accuracy: 0.600
Train Loss: 1.071, Train Accuracy: 0.375
Train Loss: 1.126, Train Accuracy: 0.800
Train Loss: 1.420, Train Accuracy: 0.500
Train Loss: 0.957, Train Accuracy: 0.400
Train Loss: 2.174, Train Accuracy: 1.000
Train Loss: 0.977, Train Accuracy: 0.700
Round 47
Train Loss: 1.439, Train Accuracy: 0.750
Train Loss: 0.931, Train Accuracy: 0.600
Train Loss: 0.968, Train Accuracy: 0.400
Train Loss: 1.361, Train Accuracy: 1.000
Train Loss: 1.150, Train Accuracy: 0.625
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.422, Train Accuracy: 1.000
Train Loss: 1.015, Train Accuracy: 0.800
Train Loss: 2.076, Train Accuracy: 1.000
Train Loss: 1.195, Train Accuracy: 0.700
Round 48
Train Loss: 1.270, Train Accuracy: 0.750
Train Loss: 0.953, Train Accuracy: 0.700
Train Loss: 0.869, Train Accuracy: 0.400
Train Loss: 1.160, Train Accuracy: 0.800
Train Loss: 1.140, Train Accuracy: 0.625
Train Loss: 1.210, Train Accuracy: 0.800
Train Loss: 1.426, Train Accuracy: 0.500

(FLClient pid=2860806) 2025-04-11 09:07:08,507 - INFO - Epoch   2| Train Loss: 0.574| Train Accuracy: 0.600 [repeated 357x across cluster]
(FLClient pid=2860856) 2025-04-11 09:07:08,511 - INFO - Epoch   2| Validation Loss: 1.715, Validation Accuracy: 0.233 [repeated 119x across cluster]

Results saved to Central_results4/Pubmed_full_GCN/results_Pubmed_full_GCN.txt

Running experiment with data_loading_option: adjacency, model_type: GCN
DEVICE: cuda
Data loading option is adjacency
Model type is GCN

2025-04-11 09:07:12,139	INFO worker.py:1816 -- Started a local Ray instance.

data_loading_option: adjacency
Data loaded
Device is cuda
Pubmed()
10

(FLClient pid=2861918) 2025-04-11 09:07:18,750 - INFO - Epoch   0| Train Loss: 1.111| Train Accuracy: 0.250
(FLClient pid=2861918) 2025-04-11 09:07:18,753 - INFO - Epoch   1| Train Loss: 0.960| Train Accuracy: 0.750
(FLClient pid=2861918) 2025-04-11 09:07:18,756 - INFO - Epoch   2| Train Loss: 0.866| Train Accuracy: 0.750
(FLClient pid=2861918) 2025-04-11 09:07:18,765 - INFO - Epoch   2| Validation Loss: 1.128, Validation Accuracy: 0.295
(FLClient pid=2861922) 2025-04-11 09:07:23,895 - INFO - Epoch   2| Train Loss: 0.980| Train Accuracy: 0.500 [repeated 360x across cluster]
(FLClient pid=2861922) 2025-04-11 09:07:23,903 - INFO - Epoch   2| Validation Loss: 1.074, Validation Accuracy: 0.467 [repeated 120x across cluster]
(FLClient pid=2861918) 2025-04-11 09:07:28,984 - INFO - Epoch   0| Train Loss: 1.146| Train Accuracy: 0.250 [repeated 448x across cluster]
(FLClient pid=2861915) 2025-04-11 09:07:28,672 - INFO - Epoch   2| Validation Loss: 1.204, Validation Accuracy: 0.219 [repeated 149x across cluster]
(FLClient pid=2861922) 2025-04-11 09:07:34,112 - INFO - Epoch   2| Train Loss: 0.796| Train Accuracy: 0.800 [repeated 452x across cluster]
(FLClient pid=2861922) 2025-04-11 09:07:34,119 - INFO - Epoch   2| Validation Loss: 0.966, Validation Accuracy: 0.467 [repeated 151x across cluster]
(FLClient pid=2861922) 2025-04-11 09:07:39,242 - INFO - Epoch   2| Train Loss: 0.691| Train Accuracy: 0.800 [repeated 450x across cluster]
(FLClient pid=2861922) 2025-04-11 09:07:39,248 - INFO - Epoch   2| Validation Loss: 0.915, Validation Accuracy: 0.467 [repeated 150x across cluster]
(FLClient pid=2861922) 2025-04-11 09:07:44,348 - INFO - Epoch   2| Train Loss: 0.850| Train Accuracy: 0.600 [repeated 450x across cluster]
(FLClient pid=2861922) 2025-04-11 09:07:44,355 - INFO - Epoch   2| Validation Loss: 0.892, Validation Accuracy: 0.556 [repeated 150x across cluster]
(FLClient pid=2861922) 2025-04-11 09:07:49,476 - INFO - Epoch   2| Train Loss: 0.655| Train Accuracy: 0.700 [repeated 450x across cluster]
(FLClient pid=2861922) 2025-04-11 09:07:49,484 - INFO - Epoch   2| Validation Loss: 0.962, Validation Accuracy: 0.467 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.128, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.051, Train Accuracy: 0.400
Train Loss: 1.198, Train Accuracy: 0.400
Train Loss: 1.194, Train Accuracy: 0.625
Train Loss: 1.187, Train Accuracy: 0.800
Train Loss: 1.363, Train Accuracy: 0.500
Train Loss: 1.138, Train Accuracy: 0.400
Train Loss: 1.354, Train Accuracy: 0.750
Train Loss: 1.142, Train Accuracy: 0.500
Round 2
Train Loss: 1.174, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.042, Train Accuracy: 0.400
Train Loss: 1.252, Train Accuracy: 0.200
Train Loss: 1.217, Train Accuracy: 0.625
Train Loss: 1.189, Train Accuracy: 0.800
Train Loss: 1.395, Train Accuracy: 0.500
Train Loss: 1.135, Train Accuracy: 0.400
Train Loss: 1.406, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.400
Round 3
Train Loss: 1.155, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.500
Train Loss: 1.043, Train Accuracy: 0.400
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.210, Train Accuracy: 0.625
Train Loss: 1.192, Train Accuracy: 0.800
Train Loss: 1.448, Train Accuracy: 0.500
Train Loss: 1.135, Train Accuracy: 0.600
Train Loss: 1.459, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.400
Round 4
Train Loss: 1.165, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.302, Train Accuracy: 0.600
Train Loss: 1.198, Train Accuracy: 0.625
Train Loss: 1.190, Train Accuracy: 0.800
Train Loss: 1.443, Train Accuracy: 0.500
Train Loss: 1.148, Train Accuracy: 0.400
Train Loss: 1.500, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.500
Round 5
Train Loss: 1.228, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.038, Train Accuracy: 0.400
Train Loss: 1.318, Train Accuracy: 0.600
Train Loss: 1.229, Train Accuracy: 0.625
Train Loss: 1.210, Train Accuracy: 0.800
Train Loss: 1.471, Train Accuracy: 0.500
Train Loss: 1.149, Train Accuracy: 0.600
Train Loss: 1.520, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.400
Round 6
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.038, Train Accuracy: 0.400
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.233, Train Accuracy: 0.625
Train Loss: 1.245, Train Accuracy: 0.800
Train Loss: 1.479, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.600
Train Loss: 1.568, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.500
Round 7
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 1.084, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.200
Train Loss: 1.343, Train Accuracy: 0.400
Train Loss: 1.232, Train Accuracy: 0.625
Train Loss: 1.242, Train Accuracy: 0.800
Train Loss: 1.480, Train Accuracy: 0.500
Train Loss: 1.154, Train Accuracy: 0.400
Train Loss: 1.581, Train Accuracy: 0.750
Train Loss: 1.214, Train Accuracy: 0.500
Round 8
Train Loss: 1.303, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 1.338, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.254, Train Accuracy: 0.800
Train Loss: 1.520, Train Accuracy: 0.500
Train Loss: 1.146, Train Accuracy: 0.600
Train Loss: 1.619, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.400
Round 9
Train Loss: 1.336, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.500
Train Loss: 1.020, Train Accuracy: 0.600
Train Loss: 1.357, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.625
Train Loss: 1.232, Train Accuracy: 0.800
Train Loss: 1.560, Train Accuracy: 0.500
Train Loss: 1.123, Train Accuracy: 0.400
Train Loss: 1.657, Train Accuracy: 0.750
Train Loss: 1.193, Train Accuracy: 0.600
Round 10
Train Loss: 1.250, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.500
Train Loss: 1.021, Train Accuracy: 0.400
Train Loss: 1.408, Train Accuracy: 0.800
Train Loss: 1.233, Train Accuracy: 0.625
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.525, Train Accuracy: 0.500
Train Loss: 1.138, Train Accuracy: 0.400
Train Loss: 1.663, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.500
Round 11
Train Loss: 1.345, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.019, Train Accuracy: 0.200
Train Loss: 1.399, Train Accuracy: 0.600
Train Loss: 1.227, Train Accuracy: 0.625
Train Loss: 1.234, Train Accuracy: 0.800
Train Loss: 1.504, Train Accuracy: 0.750
Train Loss: 1.207, Train Accuracy: 0.200
Train Loss: 1.705, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.500
Round 12
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.026, Train Accuracy: 0.400
Train Loss: 1.449, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.625
Train Loss: 1.268, Train Accuracy: 0.800
Train Loss: 1.541, Train Accuracy: 0.500
Train Loss: 1.163, Train Accuracy: 0.600
Train Loss: 1.668, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.500
Round 13
Train Loss: 1.323, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.013, Train Accuracy: 0.600
Train Loss: 1.448, Train Accuracy: 0.600
Train Loss: 1.178, Train Accuracy: 0.625
Train Loss: 1.292, Train Accuracy: 0.800
Train Loss: 1.560, Train Accuracy: 0.500
Train Loss: 1.161, Train Accuracy: 0.400
Train Loss: 1.704, Train Accuracy: 0.750
Train Loss: 1.213, Train Accuracy: 0.400
Round 14
Train Loss: 1.237, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.500
Train Loss: 1.019, Train Accuracy: 0.400
Train Loss: 1.387, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.526, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.400
Train Loss: 1.736, Train Accuracy: 0.750
Train Loss: 1.211, Train Accuracy: 0.400
Round 15
Train Loss: 1.253, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.400
Train Loss: 1.008, Train Accuracy: 0.400
Train Loss: 1.425, Train Accuracy: 0.600
Train Loss: 1.260, Train Accuracy: 0.625
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.567, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.400
Train Loss: 1.761, Train Accuracy: 0.750
Train Loss: 1.217, Train Accuracy: 0.400
Round 16
Train Loss: 1.218, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 1.411, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.556, Train Accuracy: 0.750
Train Loss: 1.129, Train Accuracy: 0.600
Train Loss: 1.790, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.600
Round 17
Train Loss: 1.274, Train Accuracy: 0.750
Train Loss: 1.046, Train Accuracy: 0.600
Train Loss: 1.008, Train Accuracy: 0.400
Train Loss: 1.392, Train Accuracy: 0.600
Train Loss: 1.230, Train Accuracy: 0.625
Train Loss: 1.292, Train Accuracy: 0.800
Train Loss: 1.570, Train Accuracy: 0.750
Train Loss: 1.146, Train Accuracy: 0.600
Train Loss: 1.836, Train Accuracy: 0.750
Train Loss: 1.217, Train Accuracy: 0.200
Round 18
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.600
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.442, Train Accuracy: 1.000
Train Loss: 1.218, Train Accuracy: 0.625
Train Loss: 1.287, Train Accuracy: 0.800
Train Loss: 1.581, Train Accuracy: 0.500
Train Loss: 1.154, Train Accuracy: 0.400
Train Loss: 1.812, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.600
Round 19
Train Loss: 1.202, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.500
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 1.422, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.508, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.600
Train Loss: 1.722, Train Accuracy: 0.750
Train Loss: 1.218, Train Accuracy: 0.500
Round 20
Train Loss: 1.263, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.000, Train Accuracy: 0.800
Train Loss: 1.473, Train Accuracy: 0.600
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.305, Train Accuracy: 0.800
Train Loss: 1.629, Train Accuracy: 0.750
Train Loss: 1.175, Train Accuracy: 0.600
Train Loss: 1.811, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.600
Round 21
Train Loss: 1.272, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.500
Train Loss: 0.994, Train Accuracy: 0.400
Train Loss: 1.461, Train Accuracy: 0.600
Train Loss: 1.166, Train Accuracy: 0.625
Train Loss: 1.345, Train Accuracy: 0.800
Train Loss: 1.573, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.400
Train Loss: 1.856, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.400
Round 22
Train Loss: 1.382, Train Accuracy: 0.750
Train Loss: 1.050, Train Accuracy: 0.500
Train Loss: 0.990, Train Accuracy: 0.800
Train Loss: 1.444, Train Accuracy: 0.600
Train Loss: 1.252, Train Accuracy: 0.750
Train Loss: 1.356, Train Accuracy: 0.800
Train Loss: 1.537, Train Accuracy: 0.750
Train Loss: 1.209, Train Accuracy: 0.000
Train Loss: 1.735, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.500
Round 23
Train Loss: 1.396, Train Accuracy: 0.750
Train Loss: 1.040, Train Accuracy: 0.500
Train Loss: 0.988, Train Accuracy: 0.400
Train Loss: 1.408, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.516, Train Accuracy: 0.500
Train Loss: 1.167, Train Accuracy: 0.600
Train Loss: 1.807, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.500
Round 24
Train Loss: 1.145, Train Accuracy: 0.750
Train Loss: 1.030, Train Accuracy: 0.500
Train Loss: 0.987, Train Accuracy: 0.400
Train Loss: 1.438, Train Accuracy: 0.600
Train Loss: 1.181, Train Accuracy: 0.750
Train Loss: 1.251, Train Accuracy: 0.800
Train Loss: 1.608, Train Accuracy: 0.500
Train Loss: 1.191, Train Accuracy: 0.800
Train Loss: 1.837, Train Accuracy: 1.000
Train Loss: 1.140, Train Accuracy: 0.500
Round 25
Train Loss: 1.140, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.500
Train Loss: 0.980, Train Accuracy: 0.200
Train Loss: 1.454, Train Accuracy: 0.800
Train Loss: 1.210, Train Accuracy: 0.750
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.606, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.600
Train Loss: 1.849, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.700
Round 26
Train Loss: 1.288, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.600
Train Loss: 0.984, Train Accuracy: 0.400
Train Loss: 1.440, Train Accuracy: 0.800
Train Loss: 1.117, Train Accuracy: 0.750
Train Loss: 1.373, Train Accuracy: 0.800
Train Loss: 1.566, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.800
Train Loss: 1.869, Train Accuracy: 0.750
Train Loss: 1.139, Train Accuracy: 0.400
Round 27
Train Loss: 1.262, Train Accuracy: 0.750
Train Loss: 1.009, Train Accuracy: 0.700
Train Loss: 0.973, Train Accuracy: 0.400
Train Loss: 1.475, Train Accuracy: 0.800
Train Loss: 1.186, Train Accuracy: 0.625
Train Loss: 1.293, Train Accuracy: 0.800
Train Loss: 1.712, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.600
Train Loss: 1.865, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.400
Round 28
Train Loss: 1.295, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.500
Train Loss: 0.978, Train Accuracy: 0.600
Train Loss: 1.457, Train Accuracy: 0.800
Train Loss: 1.213, Train Accuracy: 0.750
Train Loss: 1.390, Train Accuracy: 0.800
Train Loss: 1.605, Train Accuracy: 1.000
Train Loss: 1.189, Train Accuracy: 0.600
Train Loss: 1.901, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.400
Round 29
Train Loss: 1.400, Train Accuracy: 0.750
Train Loss: 1.025, Train Accuracy: 0.500
Train Loss: 0.967, Train Accuracy: 0.400
Train Loss: 1.486, Train Accuracy: 1.000
Train Loss: 1.171, Train Accuracy: 0.750
Train Loss: 1.391, Train Accuracy: 0.800
Train Loss: 1.628, Train Accuracy: 0.500
Train Loss: 1.315, Train Accuracy: 0.400
Train Loss: 1.907, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.700
Round 30
Train Loss: 1.382, Train Accuracy: 0.750
Train Loss: 1.020, Train Accuracy: 0.600
Train Loss: 0.961, Train Accuracy: 0.600
Train Loss: 1.472, Train Accuracy: 1.000
Train Loss: 1.154, Train Accuracy: 0.625
Train Loss: 1.243, Train Accuracy: 0.800
Train Loss: 1.542, Train Accuracy: 0.500
Train Loss: 1.229, Train Accuracy: 0.400
Train Loss: 1.995, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.600
Round 31
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.600
Train Loss: 0.973, Train Accuracy: 0.400
Train Loss: 1.477, Train Accuracy: 1.000
Train Loss: 1.274, Train Accuracy: 0.500
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.662, Train Accuracy: 0.500
Train Loss: 1.132, Train Accuracy: 0.400
Train Loss: 2.069, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.700
Round 32
Train Loss: 1.401, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 0.969, Train Accuracy: 0.400
Train Loss: 1.525, Train Accuracy: 1.000
Train Loss: 1.197, Train Accuracy: 0.750
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.561, Train Accuracy: 1.000
Train Loss: 1.073, Train Accuracy: 0.600
Train Loss: 2.018, Train Accuracy: 0.750
Train Loss: 1.118, Train Accuracy: 0.600
Round 33
Train Loss: 1.199, Train Accuracy: 0.750
Train Loss: 1.011, Train Accuracy: 0.500
Train Loss: 0.960, Train Accuracy: 0.400
Train Loss: 1.434, Train Accuracy: 1.000
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.678, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.400
Train Loss: 1.865, Train Accuracy: 0.750
Train Loss: 1.219, Train Accuracy: 0.600
Round 34
Train Loss: 1.226, Train Accuracy: 0.750
Train Loss: 0.998, Train Accuracy: 0.500
Train Loss: 0.946, Train Accuracy: 0.600
Train Loss: 1.438, Train Accuracy: 0.600
Train Loss: 1.111, Train Accuracy: 0.750
Train Loss: 1.246, Train Accuracy: 0.800
Train Loss: 1.609, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.800
Train Loss: 1.913, Train Accuracy: 0.750
Train Loss: 1.088, Train Accuracy: 0.600
Round 35
Train Loss: 1.352, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.500
Train Loss: 0.973, Train Accuracy: 0.600
Train Loss: 1.440, Train Accuracy: 0.600
Train Loss: 1.203, Train Accuracy: 0.750
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.688, Train Accuracy: 0.500
Train Loss: 1.227, Train Accuracy: 0.800
Train Loss: 1.940, Train Accuracy: 0.750
Train Loss: 1.243, Train Accuracy: 0.700
Round 36
Train Loss: 1.241, Train Accuracy: 0.750
Train Loss: 0.979, Train Accuracy: 0.700
Train Loss: 0.952, Train Accuracy: 0.400
Train Loss: 1.485, Train Accuracy: 0.800
Train Loss: 1.236, Train Accuracy: 0.625
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.622, Train Accuracy: 1.000
Train Loss: 1.115, Train Accuracy: 0.600
Train Loss: 1.771, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.700
Round 37
Train Loss: 1.146, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.600
Train Loss: 0.973, Train Accuracy: 0.400
Train Loss: 1.547, Train Accuracy: 0.600
Train Loss: 1.098, Train Accuracy: 0.625
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.613, Train Accuracy: 0.750
Train Loss: 1.005, Train Accuracy: 0.800
Train Loss: 1.970, Train Accuracy: 0.750
Train Loss: 1.209, Train Accuracy: 0.500
Round 38
Train Loss: 1.078, Train Accuracy: 0.750
Train Loss: 0.983, Train Accuracy: 0.700
Train Loss: 0.954, Train Accuracy: 0.800
Train Loss: 1.385, Train Accuracy: 1.000
Train Loss: 1.226, Train Accuracy: 0.750
Train Loss: 1.291, Train Accuracy: 0.800
Train Loss: 1.817, Train Accuracy: 0.750
Train Loss: 1.125, Train Accuracy: 0.600
Train Loss: 1.940, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.600
Round 39
Train Loss: 1.231, Train Accuracy: 0.750
Train Loss: 0.979, Train Accuracy: 0.700
Train Loss: 0.954, Train Accuracy: 0.400
Train Loss: 1.454, Train Accuracy: 0.800
Train Loss: 1.269, Train Accuracy: 0.250
Train Loss: 1.219, Train Accuracy: 0.800
Train Loss: 1.688, Train Accuracy: 1.000
Train Loss: 0.989, Train Accuracy: 0.600
Train Loss: 1.943, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.600
Round 40
Train Loss: 1.190, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.700
Train Loss: 0.927, Train Accuracy: 1.000
Train Loss: 1.362, Train Accuracy: 0.600
Train Loss: 1.263, Train Accuracy: 0.500
Train Loss: 1.217, Train Accuracy: 0.800
Train Loss: 1.585, Train Accuracy: 0.500
Train Loss: 1.068, Train Accuracy: 0.600
Train Loss: 2.030, Train Accuracy: 0.750
Train Loss: 1.113, Train Accuracy: 0.800
Round 41
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.700
Train Loss: 0.917, Train Accuracy: 1.000
Train Loss: 1.400, Train Accuracy: 1.000
Train Loss: 1.124, Train Accuracy: 0.375
Train Loss: 1.285, Train Accuracy: 0.800
Train Loss: 1.639, Train Accuracy: 1.000
Train Loss: 1.066, Train Accuracy: 0.600
Train Loss: 1.983, Train Accuracy: 0.750
Train Loss: 1.099, Train Accuracy: 0.700
Round 42
Train Loss: 1.039, Train Accuracy: 0.750
Train Loss: 0.972, Train Accuracy: 0.600
Train Loss: 0.938, Train Accuracy: 0.800
Train Loss: 1.508, Train Accuracy: 0.800
Train Loss: 1.083, Train Accuracy: 0.750
Train Loss: 1.250, Train Accuracy: 0.800
Train Loss: 1.547, Train Accuracy: 1.000
Train Loss: 1.117, Train Accuracy: 0.600
Train Loss: 2.054, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.600
Round 43
Train Loss: 1.169, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.800
Train Loss: 0.926, Train Accuracy: 0.400
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 1.210, Train Accuracy: 0.800
Train Loss: 1.685, Train Accuracy: 0.750
Train Loss: 1.012, Train Accuracy: 0.600
Train Loss: 1.962, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.600
Round 44
Train Loss: 1.211, Train Accuracy: 0.750
Train Loss: 0.953, Train Accuracy: 0.800
Train Loss: 0.940, Train Accuracy: 0.800
Train Loss: 1.388, Train Accuracy: 1.000
Train Loss: 1.195, Train Accuracy: 0.625
Train Loss: 1.214, Train Accuracy: 0.800
Train Loss: 1.478, Train Accuracy: 0.750
Train Loss: 1.018, Train Accuracy: 0.600
Train Loss: 2.097, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.700
Round 45
Train Loss: 1.206, Train Accuracy: 0.750
Train Loss: 0.962, Train Accuracy: 0.700
Train Loss: 0.904, Train Accuracy: 0.800
Train Loss: 1.595, Train Accuracy: 0.800
Train Loss: 1.197, Train Accuracy: 0.750
Train Loss: 1.228, Train Accuracy: 0.800
Train Loss: 1.632, Train Accuracy: 0.500
Train Loss: 1.125, Train Accuracy: 0.600
Train Loss: 2.004, Train Accuracy: 0.750
Train Loss: 1.257, Train Accuracy: 0.500
Round 46
Train Loss: 1.119, Train Accuracy: 0.750
Train Loss: 0.964, Train Accuracy: 0.500
Train Loss: 0.904, Train Accuracy: 0.600
Train Loss: 1.709, Train Accuracy: 0.800
Train Loss: 1.123, Train Accuracy: 0.500
Train Loss: 1.342, Train Accuracy: 0.800
Train Loss: 1.661, Train Accuracy: 0.750
Train Loss: 1.046, Train Accuracy: 0.800
Train Loss: 1.993, Train Accuracy: 0.750
Train Loss: 1.033, Train Accuracy: 0.600
Round 47
Train Loss: 1.158, Train Accuracy: 0.750
Train Loss: 0.951, Train Accuracy: 0.700
Train Loss: 0.917, Train Accuracy: 0.600
Train Loss: 1.360, Train Accuracy: 1.000
Train Loss: 1.139, Train Accuracy: 0.625
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.595, Train Accuracy: 1.000
Train Loss: 1.008, Train Accuracy: 0.800
Train Loss: 2.016, Train Accuracy: 1.000
Train Loss: 1.130, Train Accuracy: 0.700
Round 48
Train Loss: 1.209, Train Accuracy: 0.750
Train Loss: 0.943, Train Accuracy: 0.800
Train Loss: 1.001, Train Accuracy: 0.800
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.087, Train Accuracy: 0.250
Train Loss: 1.226, Train Accuracy: 0.800
Train Loss: 1.579, Train Accuracy: 1.000

(FLClient pid=2861925) 2025-04-11 09:08:01,042 - INFO - Epoch   2| Train Loss: 0.728| Train Accuracy: 0.750 [repeated 390x across cluster]
(FLClient pid=2861915) 2025-04-11 09:07:53,554 - INFO - Epoch   2| Validation Loss: 0.826, Validation Accuracy: 0.531 [repeated 129x across cluster]
(FLClient pid=2861925) 2025-04-11 09:08:06,261 - INFO - Epoch   2| Train Loss: 0.510| Train Accuracy: 0.750 [repeated 390x across cluster]
(FLClient pid=2861925) 2025-04-11 09:08:06,266 - INFO - Epoch   2| Validation Loss: 1.393, Validation Accuracy: 0.295 [repeated 131x across cluster]
(FLClient pid=2861925) 2025-04-11 09:08:11,357 - INFO - Epoch   2| Train Loss: 0.564| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2861925) 2025-04-11 09:08:11,364 - INFO - Epoch   2| Validation Loss: 1.504, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2861925) 2025-04-11 09:08:16,453 - INFO - Epoch   0| Train Loss: 1.203| Train Accuracy: 0.500 [repeated 448x across cluster]
(FLClient pid=2861926) 2025-04-11 09:08:16,133 - INFO - Epoch   2| Validation Loss: 1.108, Validation Accuracy: 0.484 [repeated 149x across cluster]
(FLClient pid=2861925) 2025-04-11 09:08:21,570 - INFO - Epoch   2| Train Loss: 0.495| Train Accuracy: 0.750 [repeated 452x across cluster]
(FLClient pid=2861925) 2025-04-11 09:08:21,578 - INFO - Epoch   2| Validation Loss: 1.068, Validation Accuracy: 0.318 [repeated 151x across cluster]
(FLClient pid=2861925) 2025-04-11 09:08:26,686 - INFO - Epoch   2| Train Loss: 0.573| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2861925) 2025-04-11 09:08:26,690 - INFO - Epoch   2| Validation Loss: 1.548, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2861925) 2025-04-11 09:08:31,764 - INFO - Epoch   2| Train Loss: 0.446| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2861925) 2025-04-11 09:08:31,772 - INFO - Epoch   2| Validation Loss: 0.877, Validation Accuracy: 0.500 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.500
Train Loss: 1.069, Train Accuracy: 0.400
Train Loss: 1.187, Train Accuracy: 0.600
Train Loss: 1.185, Train Accuracy: 0.625
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.302, Train Accuracy: 0.500
Train Loss: 1.133, Train Accuracy: 0.400
Train Loss: 1.372, Train Accuracy: 0.750
Train Loss: 1.142, Train Accuracy: 0.400
Round 2
Train Loss: 1.317, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.056, Train Accuracy: 0.400
Train Loss: 1.212, Train Accuracy: 0.600
Train Loss: 1.202, Train Accuracy: 0.625
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.359, Train Accuracy: 0.500
Train Loss: 1.134, Train Accuracy: 0.200
Train Loss: 1.388, Train Accuracy: 0.750
Train Loss: 1.139, Train Accuracy: 0.700
Round 3
Train Loss: 1.365, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.058, Train Accuracy: 0.400
Train Loss: 1.250, Train Accuracy: 0.600
Train Loss: 1.227, Train Accuracy: 0.625
Train Loss: 1.291, Train Accuracy: 0.800
Train Loss: 1.371, Train Accuracy: 0.500
Train Loss: 1.160, Train Accuracy: 0.600
Train Loss: 1.478, Train Accuracy: 0.750
Train Loss: 1.155, Train Accuracy: 0.400
Round 4
Train Loss: 1.286, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.060, Train Accuracy: 0.400
Train Loss: 1.275, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.625
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.417, Train Accuracy: 0.500
Train Loss: 1.183, Train Accuracy: 0.600
Train Loss: 1.524, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.400
Round 5
Train Loss: 1.354, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.060, Train Accuracy: 0.400
Train Loss: 1.294, Train Accuracy: 0.600
Train Loss: 1.258, Train Accuracy: 0.625
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.423, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.600
Train Loss: 1.536, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.400
Round 6
Train Loss: 1.382, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.400
Train Loss: 1.045, Train Accuracy: 0.400
Train Loss: 1.302, Train Accuracy: 0.600
Train Loss: 1.273, Train Accuracy: 0.625
Train Loss: 1.333, Train Accuracy: 0.800
Train Loss: 1.459, Train Accuracy: 0.500
Train Loss: 1.155, Train Accuracy: 0.400
Train Loss: 1.590, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.600
Round 7
Train Loss: 1.413, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.046, Train Accuracy: 0.400
Train Loss: 1.339, Train Accuracy: 0.600
Train Loss: 1.279, Train Accuracy: 0.625
Train Loss: 1.369, Train Accuracy: 0.800
Train Loss: 1.456, Train Accuracy: 0.500
Train Loss: 1.192, Train Accuracy: 0.400
Train Loss: 1.621, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.300
Round 8
Train Loss: 1.362, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.049, Train Accuracy: 0.400
Train Loss: 1.353, Train Accuracy: 0.600
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.256, Train Accuracy: 0.800
Train Loss: 1.477, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.800
Train Loss: 1.716, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.500
Round 9
Train Loss: 1.302, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.055, Train Accuracy: 0.400
Train Loss: 1.346, Train Accuracy: 0.600
Train Loss: 1.239, Train Accuracy: 0.625
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.514, Train Accuracy: 0.500
Train Loss: 1.222, Train Accuracy: 0.400
Train Loss: 1.632, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.400
Round 10
Train Loss: 1.337, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.040, Train Accuracy: 0.400
Train Loss: 1.380, Train Accuracy: 0.600
Train Loss: 1.253, Train Accuracy: 0.625
Train Loss: 1.360, Train Accuracy: 0.800
Train Loss: 1.533, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.200
Train Loss: 1.697, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.400
Round 11
Train Loss: 1.466, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.600
Train Loss: 1.040, Train Accuracy: 0.400
Train Loss: 1.385, Train Accuracy: 0.600
Train Loss: 1.279, Train Accuracy: 0.625
Train Loss: 1.392, Train Accuracy: 0.800
Train Loss: 1.502, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.000
Train Loss: 1.733, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.300
Round 12
Train Loss: 1.366, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.200
Train Loss: 1.391, Train Accuracy: 0.600
Train Loss: 1.230, Train Accuracy: 0.625
Train Loss: 1.357, Train Accuracy: 0.800
Train Loss: 1.510, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.600
Train Loss: 1.712, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.500
Round 13
Train Loss: 1.359, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.400
Train Loss: 1.035, Train Accuracy: 0.200
Train Loss: 1.398, Train Accuracy: 0.600
Train Loss: 1.265, Train Accuracy: 0.625
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.517, Train Accuracy: 0.500
Train Loss: 1.183, Train Accuracy: 0.800
Train Loss: 1.783, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.600
Round 14
Train Loss: 1.393, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.400
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.417, Train Accuracy: 0.600
Train Loss: 1.264, Train Accuracy: 0.625
Train Loss: 1.348, Train Accuracy: 0.800
Train Loss: 1.508, Train Accuracy: 0.500
Train Loss: 1.224, Train Accuracy: 0.600
Train Loss: 1.738, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.500
Round 15
Train Loss: 1.319, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.600
Train Loss: 1.032, Train Accuracy: 0.400
Train Loss: 1.418, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.416, Train Accuracy: 0.800
Train Loss: 1.533, Train Accuracy: 0.500
Train Loss: 1.151, Train Accuracy: 0.200
Train Loss: 1.835, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.400
Round 16
Train Loss: 1.413, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.600
Train Loss: 1.053, Train Accuracy: 0.800
Train Loss: 1.425, Train Accuracy: 0.600
Train Loss: 1.288, Train Accuracy: 0.625
Train Loss: 1.465, Train Accuracy: 0.800
Train Loss: 1.530, Train Accuracy: 0.500
Train Loss: 1.296, Train Accuracy: 0.600
Train Loss: 1.781, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.400
Round 17
Train Loss: 1.263, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.600
Train Loss: 1.024, Train Accuracy: 0.400
Train Loss: 1.408, Train Accuracy: 0.600
Train Loss: 1.258, Train Accuracy: 0.625
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.552, Train Accuracy: 0.500
Train Loss: 1.227, Train Accuracy: 0.200
Train Loss: 1.895, Train Accuracy: 0.750
Train Loss: 1.209, Train Accuracy: 0.600
Round 18
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 1.062, Train Accuracy: 0.500
Train Loss: 1.017, Train Accuracy: 0.400
Train Loss: 1.440, Train Accuracy: 0.600
Train Loss: 1.261, Train Accuracy: 0.625
Train Loss: 1.428, Train Accuracy: 0.800
Train Loss: 1.531, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.800
Train Loss: 1.893, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.400
Round 19
Train Loss: 1.257, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.500
Train Loss: 1.013, Train Accuracy: 0.200
Train Loss: 1.472, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.625
Train Loss: 1.400, Train Accuracy: 0.800
Train Loss: 1.539, Train Accuracy: 0.500
Train Loss: 1.187, Train Accuracy: 0.400
Train Loss: 1.880, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.700
Round 20
Train Loss: 1.363, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.400
Train Loss: 1.015, Train Accuracy: 0.400
Train Loss: 1.436, Train Accuracy: 0.800
Train Loss: 1.251, Train Accuracy: 0.625
Train Loss: 1.372, Train Accuracy: 0.800
Train Loss: 1.535, Train Accuracy: 0.500
Train Loss: 1.152, Train Accuracy: 0.800
Train Loss: 1.917, Train Accuracy: 0.750
Train Loss: 1.124, Train Accuracy: 0.500
Round 21
Train Loss: 1.388, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.700
Train Loss: 1.016, Train Accuracy: 0.000
Train Loss: 1.452, Train Accuracy: 0.600
Train Loss: 1.266, Train Accuracy: 0.625
Train Loss: 1.469, Train Accuracy: 0.800
Train Loss: 1.538, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.600
Train Loss: 1.840, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.500
Round 22
Train Loss: 1.322, Train Accuracy: 0.500
Train Loss: 1.050, Train Accuracy: 0.600
Train Loss: 1.007, Train Accuracy: 0.400
Train Loss: 1.454, Train Accuracy: 0.600
Train Loss: 1.247, Train Accuracy: 0.625
Train Loss: 1.488, Train Accuracy: 0.800
Train Loss: 1.561, Train Accuracy: 0.500
Train Loss: 1.149, Train Accuracy: 0.200
Train Loss: 1.856, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.400
Round 23
Train Loss: 1.380, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.500
Train Loss: 1.009, Train Accuracy: 0.400
Train Loss: 1.469, Train Accuracy: 0.600
Train Loss: 1.257, Train Accuracy: 0.625
Train Loss: 1.402, Train Accuracy: 0.800
Train Loss: 1.523, Train Accuracy: 0.500
Train Loss: 1.167, Train Accuracy: 0.600
Train Loss: 1.987, Train Accuracy: 0.750
Train Loss: 1.131, Train Accuracy: 0.400
Round 24
Train Loss: 1.422, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.500
Train Loss: 1.002, Train Accuracy: 0.200
Train Loss: 1.391, Train Accuracy: 0.600
Train Loss: 1.250, Train Accuracy: 0.625
Train Loss: 1.415, Train Accuracy: 0.800
Train Loss: 1.573, Train Accuracy: 0.500
Train Loss: 1.196, Train Accuracy: 0.400
Train Loss: 1.883, Train Accuracy: 0.750
Train Loss: 1.189, Train Accuracy: 0.400
Round 25
Train Loss: 1.464, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.600
Train Loss: 1.009, Train Accuracy: 0.200
Train Loss: 1.457, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 0.625
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.588, Train Accuracy: 1.000
Train Loss: 1.151, Train Accuracy: 0.600
Train Loss: 1.901, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.700
Round 26
Train Loss: 1.329, Train Accuracy: 0.750
Train Loss: 1.050, Train Accuracy: 0.700
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 1.478, Train Accuracy: 0.600
Train Loss: 1.201, Train Accuracy: 0.625
Train Loss: 1.424, Train Accuracy: 0.800
Train Loss: 1.539, Train Accuracy: 0.500
Train Loss: 1.132, Train Accuracy: 0.400
Train Loss: 2.006, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.500
Round 27
Train Loss: 1.295, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 0.998, Train Accuracy: 0.200
Train Loss: 1.497, Train Accuracy: 0.800
Train Loss: 1.252, Train Accuracy: 0.625
Train Loss: 1.315, Train Accuracy: 0.800
Train Loss: 1.568, Train Accuracy: 0.750
Train Loss: 1.115, Train Accuracy: 0.200
Train Loss: 1.890, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.200
Round 28
Train Loss: 1.481, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.500
Train Loss: 0.998, Train Accuracy: 0.400
Train Loss: 1.439, Train Accuracy: 0.600
Train Loss: 1.248, Train Accuracy: 0.625
Train Loss: 1.315, Train Accuracy: 0.800
Train Loss: 1.624, Train Accuracy: 0.500
Train Loss: 1.151, Train Accuracy: 0.400
Train Loss: 1.848, Train Accuracy: 0.750
Train Loss: 1.155, Train Accuracy: 0.500
Round 29
Train Loss: 1.504, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.500
Train Loss: 0.995, Train Accuracy: 0.200
Train Loss: 1.450, Train Accuracy: 0.800
Train Loss: 1.260, Train Accuracy: 0.625
Train Loss: 1.378, Train Accuracy: 0.800
Train Loss: 1.566, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.600
Train Loss: 2.023, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.600
Round 30
Train Loss: 1.209, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.300
Train Loss: 0.985, Train Accuracy: 0.600
Train Loss: 1.465, Train Accuracy: 0.600
Train Loss: 1.194, Train Accuracy: 0.625
Train Loss: 1.481, Train Accuracy: 0.800
Train Loss: 1.570, Train Accuracy: 0.500
Train Loss: 1.151, Train Accuracy: 0.200
Train Loss: 1.907, Train Accuracy: 0.750
Train Loss: 1.192, Train Accuracy: 0.500
Round 31
Train Loss: 1.363, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 1.009, Train Accuracy: 0.400
Train Loss: 1.471, Train Accuracy: 0.600
Train Loss: 1.200, Train Accuracy: 0.625
Train Loss: 1.412, Train Accuracy: 0.800
Train Loss: 1.611, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.400
Train Loss: 1.861, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.700
Round 32
Train Loss: 1.443, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.600
Train Loss: 0.983, Train Accuracy: 0.400
Train Loss: 1.387, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 0.625
Train Loss: 1.270, Train Accuracy: 0.800
Train Loss: 1.580, Train Accuracy: 0.500
Train Loss: 1.119, Train Accuracy: 0.200
Train Loss: 1.769, Train Accuracy: 0.750
Train Loss: 1.126, Train Accuracy: 0.400
Round 33
Train Loss: 1.127, Train Accuracy: 0.750
Train Loss: 1.022, Train Accuracy: 0.500
Train Loss: 0.982, Train Accuracy: 0.200
Train Loss: 1.494, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.625
Train Loss: 1.339, Train Accuracy: 0.800
Train Loss: 1.578, Train Accuracy: 1.000
Train Loss: 1.182, Train Accuracy: 0.800
Train Loss: 1.879, Train Accuracy: 0.750
Train Loss: 1.251, Train Accuracy: 0.600
Round 34
Train Loss: 1.394, Train Accuracy: 0.500
Train Loss: 1.031, Train Accuracy: 0.700
Train Loss: 0.969, Train Accuracy: 0.600
Train Loss: 1.453, Train Accuracy: 0.800
Train Loss: 1.215, Train Accuracy: 0.625
Train Loss: 1.367, Train Accuracy: 0.800
Train Loss: 1.543, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.600
Train Loss: 2.027, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.400
Round 35
Train Loss: 1.344, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 1.011, Train Accuracy: 0.600
Train Loss: 1.502, Train Accuracy: 0.800
Train Loss: 1.212, Train Accuracy: 0.625
Train Loss: 1.393, Train Accuracy: 0.800
Train Loss: 1.560, Train Accuracy: 0.750
Train Loss: 1.062, Train Accuracy: 0.800
Train Loss: 1.893, Train Accuracy: 0.750
Train Loss: 1.113, Train Accuracy: 0.400
Round 36
Train Loss: 1.341, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.500
Train Loss: 0.990, Train Accuracy: 0.600
Train Loss: 1.385, Train Accuracy: 0.600
Train Loss: 1.174, Train Accuracy: 0.750
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.530, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.400
Train Loss: 1.902, Train Accuracy: 0.750
Train Loss: 1.111, Train Accuracy: 0.600
Round 37
Train Loss: 1.313, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.700
Train Loss: 0.959, Train Accuracy: 0.800
Train Loss: 1.415, Train Accuracy: 0.800
Train Loss: 1.173, Train Accuracy: 0.625
Train Loss: 1.374, Train Accuracy: 0.800
Train Loss: 1.655, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.600
Train Loss: 1.872, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.800
Round 38
Train Loss: 1.335, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.500
Train Loss: 0.957, Train Accuracy: 0.600
Train Loss: 1.374, Train Accuracy: 0.800
Train Loss: 1.189, Train Accuracy: 0.625
Train Loss: 1.428, Train Accuracy: 0.800
Train Loss: 1.660, Train Accuracy: 0.500
Train Loss: 1.138, Train Accuracy: 0.800
Train Loss: 2.169, Train Accuracy: 0.750
Train Loss: 1.092, Train Accuracy: 0.700
Round 39
Train Loss: 1.307, Train Accuracy: 0.750
Train Loss: 1.007, Train Accuracy: 0.500
Train Loss: 0.950, Train Accuracy: 0.400
Train Loss: 1.417, Train Accuracy: 0.800
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.244, Train Accuracy: 0.800
Train Loss: 1.598, Train Accuracy: 1.000
Train Loss: 1.083, Train Accuracy: 0.400
Train Loss: 2.188, Train Accuracy: 1.000
Train Loss: 1.172, Train Accuracy: 0.600
Round 40
Train Loss: 1.148, Train Accuracy: 0.750
Train Loss: 0.993, Train Accuracy: 0.600
Train Loss: 0.962, Train Accuracy: 0.600
Train Loss: 1.392, Train Accuracy: 0.800
Train Loss: 1.139, Train Accuracy: 0.750
Train Loss: 1.480, Train Accuracy: 1.000
Train Loss: 1.559, Train Accuracy: 1.000
Train Loss: 1.100, Train Accuracy: 0.800
Train Loss: 2.188, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.400
Round 41
Train Loss: 1.277, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.400
Train Loss: 0.951, Train Accuracy: 0.400
Train Loss: 1.515, Train Accuracy: 0.800
Train Loss: 1.234, Train Accuracy: 0.625
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.569, Train Accuracy: 0.750
Train Loss: 1.205, Train Accuracy: 0.400
Train Loss: 1.997, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.600
Round 42
Train Loss: 1.206, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.300
Train Loss: 1.009, Train Accuracy: 0.400
Train Loss: 1.435, Train Accuracy: 1.000
Train Loss: 1.116, Train Accuracy: 0.750
Train Loss: 1.458, Train Accuracy: 0.800
Train Loss: 1.444, Train Accuracy: 0.750
Train Loss: 1.403, Train Accuracy: 0.800
Train Loss: 2.146, Train Accuracy: 0.750
Train Loss: 1.115, Train Accuracy: 0.600
Round 43
Train Loss: 1.288, Train Accuracy: 0.750
Train Loss: 1.007, Train Accuracy: 0.700
Train Loss: 0.950, Train Accuracy: 0.600
Train Loss: 1.382, Train Accuracy: 0.800
Train Loss: 1.244, Train Accuracy: 0.875
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.550, Train Accuracy: 0.750
Train Loss: 1.130, Train Accuracy: 1.000
Train Loss: 2.038, Train Accuracy: 1.000
Train Loss: 1.108, Train Accuracy: 0.600
Round 44
Train Loss: 1.402, Train Accuracy: 1.000
Train Loss: 1.015, Train Accuracy: 0.600
Train Loss: 0.954, Train Accuracy: 0.400
Train Loss: 1.242, Train Accuracy: 0.800
Train Loss: 1.090, Train Accuracy: 0.500
Train Loss: 1.434, Train Accuracy: 0.800
Train Loss: 1.556, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.800
Train Loss: 2.117, Train Accuracy: 0.750
Train Loss: 1.328, Train Accuracy: 0.400
Round 45
Train Loss: 1.198, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.400
Train Loss: 0.924, Train Accuracy: 0.400
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.169, Train Accuracy: 0.625
Train Loss: 1.397, Train Accuracy: 0.800
Train Loss: 1.663, Train Accuracy: 0.750
Train Loss: 1.158, Train Accuracy: 0.400
Train Loss: 1.860, Train Accuracy: 0.750
Train Loss: 1.158, Train Accuracy: 0.700
Round 46
Train Loss: 1.358, Train Accuracy: 0.750
Train Loss: 0.970, Train Accuracy: 0.700
Train Loss: 0.935, Train Accuracy: 0.400
Train Loss: 1.388, Train Accuracy: 1.000
Train Loss: 1.119, Train Accuracy: 0.625
Train Loss: 1.407, Train Accuracy: 0.800
Train Loss: 1.518, Train Accuracy: 1.000
Train Loss: 1.132, Train Accuracy: 0.800
Train Loss: 1.946, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.700
Round 47
Train Loss: 1.273, Train Accuracy: 0.750
Train Loss: 1.017, Train Accuracy: 0.400
Train Loss: 0.938, Train Accuracy: 0.600
Train Loss: 1.468, Train Accuracy: 1.000
Train Loss: 1.100, Train Accuracy: 0.750
Train Loss: 1.375, Train Accuracy: 0.800
Train Loss: 1.699, Train Accuracy: 0.500
Train Loss: 1.044, Train Accuracy: 0.800
Train Loss: 2.020, Train Accuracy: 0.750
Train Loss: 1.216, Train Accuracy: 0.600
Round 48
Train Loss: 1.295, Train Accuracy: 0.500
Train Loss: 1.017, Train Accuracy: 0.300
Train Loss: 0.909, Train Accuracy: 0.400
Train Loss: 1.398, Train Accuracy: 1.000
Train Loss: 1.031, Train Accuracy: 0.750
Train Loss: 1.242, Train Accuracy: 0.800
Train Loss: 1.573, Train Accuracy: 0.750

(FLClient pid=2861933) 2025-04-11 09:08:43,079 - INFO - Epoch   2| Train Loss: 1.040| Train Accuracy: 0.400 [repeated 360x across cluster]
(FLClient pid=2861926) 2025-04-11 09:08:35,522 - INFO - Epoch   2| Validation Loss: 1.010, Validation Accuracy: 0.438 [repeated 119x across cluster]
(FLClient pid=2861927) 2025-04-11 09:08:48,117 - INFO - Epoch   0| Train Loss: 1.290| Train Accuracy: 0.250 [repeated 388x across cluster]
(FLClient pid=2864333) 2025-04-11 09:08:47,809 - INFO - Epoch   2| Validation Loss: 1.186, Validation Accuracy: 0.250 [repeated 130x across cluster]
(FLClient pid=2861927) 2025-04-11 09:08:53,275 - INFO - Epoch   2| Train Loss: 0.575| Train Accuracy: 0.750 [repeated 452x across cluster]
(FLClient pid=2861927) 2025-04-11 09:08:53,281 - INFO - Epoch   2| Validation Loss: 1.270, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2861927) 2025-04-11 09:08:58,373 - INFO - Epoch   1| Train Loss: 0.621| Train Accuracy: 0.500 [repeated 449x across cluster]
(FLClient pid=2864333) 2025-04-11 09:08:58,048 - INFO - Epoch   2| Validation Loss: 1.200, Validation Accuracy: 0.234 [repeated 149x across cluster]
(FLClient pid=2861927) 2025-04-11 09:09:03,487 - INFO - Epoch   2| Train Loss: 0.479| Train Accuracy: 0.750 [repeated 451x across cluster]
(FLClient pid=2861927) 2025-04-11 09:09:03,494 - INFO - Epoch   2| Validation Loss: 1.522, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2861927) 2025-04-11 09:09:08,586 - INFO - Epoch   2| Train Loss: 0.437| Train Accuracy: 1.000 [repeated 450x across cluster]
(FLClient pid=2861927) 2025-04-11 09:09:08,594 - INFO - Epoch   2| Validation Loss: 1.484, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2861927) 2025-04-11 09:09:13,686 - INFO - Epoch   2| Train Loss: 0.480| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2861927) 2025-04-11 09:09:13,694 - INFO - Epoch   2| Validation Loss: 1.275, Validation Accuracy: 0.295 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.162, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.048, Train Accuracy: 0.400
Train Loss: 1.193, Train Accuracy: 0.600
Train Loss: 1.198, Train Accuracy: 0.625
Train Loss: 1.188, Train Accuracy: 0.800
Train Loss: 1.371, Train Accuracy: 0.500
Train Loss: 1.148, Train Accuracy: 0.600
Train Loss: 1.349, Train Accuracy: 0.750
Train Loss: 1.142, Train Accuracy: 0.400
Round 2
Train Loss: 1.186, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.400
Train Loss: 1.228, Train Accuracy: 0.600
Train Loss: 1.227, Train Accuracy: 0.625
Train Loss: 1.196, Train Accuracy: 0.800
Train Loss: 1.428, Train Accuracy: 0.500
Train Loss: 1.143, Train Accuracy: 0.400
Train Loss: 1.397, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.500
Round 3
Train Loss: 1.219, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.600
Train Loss: 1.244, Train Accuracy: 0.400
Train Loss: 1.222, Train Accuracy: 0.625
Train Loss: 1.225, Train Accuracy: 0.800
Train Loss: 1.432, Train Accuracy: 0.500
Train Loss: 1.143, Train Accuracy: 0.200
Train Loss: 1.445, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.600
Round 4
Train Loss: 1.210, Train Accuracy: 0.750
Train Loss: 1.088, Train Accuracy: 0.500
Train Loss: 1.036, Train Accuracy: 0.400
Train Loss: 1.258, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.240, Train Accuracy: 0.800
Train Loss: 1.426, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.600
Train Loss: 1.469, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.500
Round 5
Train Loss: 1.225, Train Accuracy: 0.750
Train Loss: 1.086, Train Accuracy: 0.500
Train Loss: 1.034, Train Accuracy: 0.400
Train Loss: 1.276, Train Accuracy: 0.600
Train Loss: 1.230, Train Accuracy: 0.625
Train Loss: 1.244, Train Accuracy: 0.800
Train Loss: 1.427, Train Accuracy: 0.500
Train Loss: 1.154, Train Accuracy: 0.600
Train Loss: 1.499, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.600
Round 6
Train Loss: 1.240, Train Accuracy: 0.750
Train Loss: 1.089, Train Accuracy: 0.500
Train Loss: 1.031, Train Accuracy: 0.600
Train Loss: 1.307, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.230, Train Accuracy: 0.800
Train Loss: 1.460, Train Accuracy: 0.500
Train Loss: 1.158, Train Accuracy: 0.400
Train Loss: 1.543, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.400
Round 7
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 1.084, Train Accuracy: 0.500
Train Loss: 1.033, Train Accuracy: 0.400
Train Loss: 1.317, Train Accuracy: 0.600
Train Loss: 1.250, Train Accuracy: 0.625
Train Loss: 1.233, Train Accuracy: 0.800
Train Loss: 1.470, Train Accuracy: 0.500
Train Loss: 1.146, Train Accuracy: 0.600
Train Loss: 1.560, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.400
Round 8
Train Loss: 1.254, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.334, Train Accuracy: 0.400
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.247, Train Accuracy: 0.800
Train Loss: 1.472, Train Accuracy: 0.500
Train Loss: 1.141, Train Accuracy: 0.200
Train Loss: 1.546, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.500
Round 9
Train Loss: 1.277, Train Accuracy: 0.750
Train Loss: 1.086, Train Accuracy: 0.500
Train Loss: 1.026, Train Accuracy: 0.400
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.482, Train Accuracy: 0.500
Train Loss: 1.156, Train Accuracy: 0.200
Train Loss: 1.611, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.600
Round 10
Train Loss: 1.312, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.600
Train Loss: 1.034, Train Accuracy: 0.400
Train Loss: 1.372, Train Accuracy: 0.600
Train Loss: 1.204, Train Accuracy: 0.625
Train Loss: 1.286, Train Accuracy: 0.800
Train Loss: 1.505, Train Accuracy: 0.500
Train Loss: 1.197, Train Accuracy: 0.600
Train Loss: 1.591, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.400
Round 11
Train Loss: 1.288, Train Accuracy: 0.750
Train Loss: 1.092, Train Accuracy: 0.500
Train Loss: 1.027, Train Accuracy: 0.600
Train Loss: 1.389, Train Accuracy: 0.600
Train Loss: 1.250, Train Accuracy: 0.625
Train Loss: 1.249, Train Accuracy: 0.800
Train Loss: 1.516, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.600
Train Loss: 1.631, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.500
Round 12
Train Loss: 1.265, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.373, Train Accuracy: 0.600
Train Loss: 1.223, Train Accuracy: 0.625
Train Loss: 1.255, Train Accuracy: 0.800
Train Loss: 1.538, Train Accuracy: 0.500
Train Loss: 1.161, Train Accuracy: 0.400
Train Loss: 1.674, Train Accuracy: 0.750
Train Loss: 1.190, Train Accuracy: 0.400
Round 13
Train Loss: 1.291, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.400
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 1.382, Train Accuracy: 0.600
Train Loss: 1.202, Train Accuracy: 0.625
Train Loss: 1.288, Train Accuracy: 0.800
Train Loss: 1.531, Train Accuracy: 0.500
Train Loss: 1.160, Train Accuracy: 0.600
Train Loss: 1.706, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.300
Round 14
Train Loss: 1.280, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.020, Train Accuracy: 0.600
Train Loss: 1.386, Train Accuracy: 0.800
Train Loss: 1.233, Train Accuracy: 0.625
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.521, Train Accuracy: 0.500
Train Loss: 1.127, Train Accuracy: 0.200
Train Loss: 1.677, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.500
Round 15
Train Loss: 1.355, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 1.387, Train Accuracy: 0.600
Train Loss: 1.222, Train Accuracy: 0.625
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.564, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.800
Train Loss: 1.656, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.300
Round 16
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 1.062, Train Accuracy: 0.500
Train Loss: 1.018, Train Accuracy: 0.600
Train Loss: 1.367, Train Accuracy: 0.600
Train Loss: 1.252, Train Accuracy: 0.625
Train Loss: 1.260, Train Accuracy: 0.800
Train Loss: 1.535, Train Accuracy: 0.250
Train Loss: 1.173, Train Accuracy: 0.200
Train Loss: 1.724, Train Accuracy: 0.750
Train Loss: 1.193, Train Accuracy: 0.500
Round 17
Train Loss: 1.272, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.011, Train Accuracy: 0.600
Train Loss: 1.429, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.625
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.523, Train Accuracy: 0.500
Train Loss: 1.192, Train Accuracy: 0.400
Train Loss: 1.770, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.500
Round 18
Train Loss: 1.262, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.020, Train Accuracy: 0.800
Train Loss: 1.412, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.625
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.561, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.400
Train Loss: 1.733, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.500
Round 19
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.500
Train Loss: 1.009, Train Accuracy: 0.400
Train Loss: 1.488, Train Accuracy: 0.600
Train Loss: 1.213, Train Accuracy: 0.500
Train Loss: 1.296, Train Accuracy: 0.800
Train Loss: 1.526, Train Accuracy: 0.500
Train Loss: 1.235, Train Accuracy: 0.800
Train Loss: 1.730, Train Accuracy: 0.750
Train Loss: 1.216, Train Accuracy: 0.500
Round 20
Train Loss: 1.315, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.600
Train Loss: 1.008, Train Accuracy: 0.400
Train Loss: 1.454, Train Accuracy: 0.800
Train Loss: 1.228, Train Accuracy: 0.750
Train Loss: 1.251, Train Accuracy: 0.800
Train Loss: 1.565, Train Accuracy: 0.500
Train Loss: 1.133, Train Accuracy: 0.400
Train Loss: 1.743, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.600
Round 21
Train Loss: 1.238, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.400
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 1.429, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.302, Train Accuracy: 0.800
Train Loss: 1.562, Train Accuracy: 0.500
Train Loss: 1.128, Train Accuracy: 0.400
Train Loss: 1.911, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.500
Round 22
Train Loss: 1.289, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.500
Train Loss: 1.000, Train Accuracy: 0.400
Train Loss: 1.418, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.584, Train Accuracy: 0.750
Train Loss: 1.098, Train Accuracy: 0.400
Train Loss: 1.695, Train Accuracy: 0.750
Train Loss: 1.205, Train Accuracy: 0.600
Round 23
Train Loss: 1.439, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.500
Train Loss: 1.001, Train Accuracy: 0.600
Train Loss: 1.548, Train Accuracy: 0.800
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.291, Train Accuracy: 0.800
Train Loss: 1.597, Train Accuracy: 0.250
Train Loss: 1.119, Train Accuracy: 0.400
Train Loss: 1.828, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.400
Round 24
Train Loss: 1.365, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.500
Train Loss: 0.993, Train Accuracy: 0.600
Train Loss: 1.476, Train Accuracy: 0.800
Train Loss: 1.212, Train Accuracy: 0.750
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.594, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.600
Train Loss: 1.906, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 0.600
Round 25
Train Loss: 1.329, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.600
Train Loss: 1.003, Train Accuracy: 0.400
Train Loss: 1.429, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.602, Train Accuracy: 0.500
Train Loss: 1.157, Train Accuracy: 0.400
Train Loss: 1.673, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.500
Round 26
Train Loss: 1.203, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.500
Train Loss: 0.991, Train Accuracy: 0.200
Train Loss: 1.495, Train Accuracy: 0.800
Train Loss: 1.207, Train Accuracy: 0.625
Train Loss: 1.235, Train Accuracy: 0.800
Train Loss: 1.546, Train Accuracy: 0.500
Train Loss: 1.223, Train Accuracy: 0.600
Train Loss: 1.891, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.600
Round 27
Train Loss: 1.313, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.600
Train Loss: 0.998, Train Accuracy: 0.400
Train Loss: 1.468, Train Accuracy: 1.000
Train Loss: 1.161, Train Accuracy: 0.500
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.627, Train Accuracy: 1.000
Train Loss: 1.250, Train Accuracy: 0.600
Train Loss: 1.948, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.700
Round 28
Train Loss: 1.320, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.700
Train Loss: 0.981, Train Accuracy: 0.400
Train Loss: 1.531, Train Accuracy: 0.800
Train Loss: 1.164, Train Accuracy: 0.625
Train Loss: 1.282, Train Accuracy: 0.800
Train Loss: 1.543, Train Accuracy: 0.000
Train Loss: 1.119, Train Accuracy: 0.200
Train Loss: 1.777, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.700
Round 29
Train Loss: 1.270, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.500
Train Loss: 0.978, Train Accuracy: 0.400
Train Loss: 1.457, Train Accuracy: 0.800
Train Loss: 1.147, Train Accuracy: 0.625
Train Loss: 1.261, Train Accuracy: 0.800
Train Loss: 1.622, Train Accuracy: 0.500
Train Loss: 1.122, Train Accuracy: 0.600
Train Loss: 1.931, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.500
Round 30
Train Loss: 1.324, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.500
Train Loss: 0.970, Train Accuracy: 0.800
Train Loss: 1.404, Train Accuracy: 0.800
Train Loss: 1.191, Train Accuracy: 0.625
Train Loss: 1.409, Train Accuracy: 0.800
Train Loss: 1.641, Train Accuracy: 0.500
Train Loss: 1.138, Train Accuracy: 0.600
Train Loss: 1.967, Train Accuracy: 1.000
Train Loss: 1.236, Train Accuracy: 0.700
Round 31
Train Loss: 1.228, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.700
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 1.448, Train Accuracy: 0.600
Train Loss: 1.176, Train Accuracy: 0.625
Train Loss: 1.267, Train Accuracy: 0.800
Train Loss: 1.662, Train Accuracy: 0.500
Train Loss: 1.199, Train Accuracy: 0.400
Train Loss: 1.780, Train Accuracy: 0.750
Train Loss: 1.229, Train Accuracy: 0.600
Round 32
Train Loss: 1.317, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.600
Train Loss: 0.973, Train Accuracy: 0.600
Train Loss: 1.374, Train Accuracy: 0.600
Train Loss: 1.169, Train Accuracy: 0.625
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.567, Train Accuracy: 1.000
Train Loss: 1.213, Train Accuracy: 0.800
Train Loss: 1.822, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.700
Round 33
Train Loss: 1.410, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.600
Train Loss: 0.985, Train Accuracy: 0.600
Train Loss: 1.482, Train Accuracy: 0.800
Train Loss: 1.269, Train Accuracy: 0.875
Train Loss: 1.264, Train Accuracy: 0.800
Train Loss: 1.561, Train Accuracy: 0.500
Train Loss: 1.215, Train Accuracy: 0.600
Train Loss: 1.884, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.600
Round 34
Train Loss: 1.329, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.500
Train Loss: 0.968, Train Accuracy: 0.600
Train Loss: 1.472, Train Accuracy: 0.800
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.399, Train Accuracy: 0.800
Train Loss: 1.609, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.800
Train Loss: 1.776, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.500
Round 35
Train Loss: 1.294, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.500
Train Loss: 0.966, Train Accuracy: 0.400
Train Loss: 1.435, Train Accuracy: 0.400
Train Loss: 1.267, Train Accuracy: 0.750
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.574, Train Accuracy: 0.750
Train Loss: 1.110, Train Accuracy: 0.600
Train Loss: 1.975, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.600
Round 36
Train Loss: 1.194, Train Accuracy: 0.750
Train Loss: 0.993, Train Accuracy: 0.500
Train Loss: 0.986, Train Accuracy: 0.400
Train Loss: 1.419, Train Accuracy: 0.800
Train Loss: 1.175, Train Accuracy: 0.750
Train Loss: 1.293, Train Accuracy: 0.800
Train Loss: 1.621, Train Accuracy: 1.000
Train Loss: 1.203, Train Accuracy: 0.600
Train Loss: 1.840, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.600
Round 37
Train Loss: 1.150, Train Accuracy: 0.750
Train Loss: 0.987, Train Accuracy: 0.600
Train Loss: 0.964, Train Accuracy: 0.600
Train Loss: 1.459, Train Accuracy: 0.600
Train Loss: 1.135, Train Accuracy: 0.750
Train Loss: 1.361, Train Accuracy: 0.800
Train Loss: 1.640, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.200
Train Loss: 1.930, Train Accuracy: 0.750
Train Loss: 1.128, Train Accuracy: 0.600
Round 38
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.700
Train Loss: 0.952, Train Accuracy: 0.600
Train Loss: 1.369, Train Accuracy: 0.600
Train Loss: 1.243, Train Accuracy: 0.625
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.563, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.200
Train Loss: 1.607, Train Accuracy: 0.750
Train Loss: 1.095, Train Accuracy: 0.700
Round 39
Train Loss: 1.431, Train Accuracy: 0.750
Train Loss: 0.993, Train Accuracy: 0.500
Train Loss: 0.972, Train Accuracy: 0.400
Train Loss: 1.365, Train Accuracy: 0.600
Train Loss: 1.137, Train Accuracy: 0.625
Train Loss: 1.245, Train Accuracy: 0.800
Train Loss: 1.628, Train Accuracy: 1.000
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.901, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.600
Round 40
Train Loss: 1.178, Train Accuracy: 0.750
Train Loss: 1.009, Train Accuracy: 0.500
Train Loss: 0.928, Train Accuracy: 0.600
Train Loss: 1.505, Train Accuracy: 0.800
Train Loss: 1.240, Train Accuracy: 0.875
Train Loss: 1.191, Train Accuracy: 0.800
Train Loss: 1.609, Train Accuracy: 0.500
Train Loss: 1.142, Train Accuracy: 0.600
Train Loss: 1.944, Train Accuracy: 0.750
Train Loss: 1.120, Train Accuracy: 0.600
Round 41
Train Loss: 1.244, Train Accuracy: 1.000
Train Loss: 0.972, Train Accuracy: 0.800
Train Loss: 0.935, Train Accuracy: 0.400
Train Loss: 1.518, Train Accuracy: 1.000
Train Loss: 1.292, Train Accuracy: 0.500
Train Loss: 1.272, Train Accuracy: 0.800
Train Loss: 1.637, Train Accuracy: 1.000
Train Loss: 1.076, Train Accuracy: 0.800
Train Loss: 1.905, Train Accuracy: 1.000
Train Loss: 1.120, Train Accuracy: 0.700
Round 42
Train Loss: 1.239, Train Accuracy: 0.750
Train Loss: 0.962, Train Accuracy: 0.600
Train Loss: 0.929, Train Accuracy: 0.800
Train Loss: 1.435, Train Accuracy: 0.600
Train Loss: 1.199, Train Accuracy: 0.750
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.618, Train Accuracy: 1.000
Train Loss: 1.014, Train Accuracy: 0.600
Train Loss: 1.952, Train Accuracy: 0.750
Train Loss: 1.131, Train Accuracy: 0.600
Round 43
Train Loss: 1.108, Train Accuracy: 0.750
Train Loss: 1.004, Train Accuracy: 0.500
Train Loss: 0.934, Train Accuracy: 0.600
Train Loss: 1.404, Train Accuracy: 1.000
Train Loss: 1.062, Train Accuracy: 0.250
Train Loss: 1.304, Train Accuracy: 0.800
Train Loss: 1.570, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.800
Train Loss: 1.862, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.800
Round 44
Train Loss: 1.220, Train Accuracy: 1.000
Train Loss: 0.973, Train Accuracy: 0.700
Train Loss: 0.947, Train Accuracy: 0.400
Train Loss: 1.532, Train Accuracy: 0.800
Train Loss: 1.198, Train Accuracy: 0.625
Train Loss: 1.185, Train Accuracy: 0.800
Train Loss: 1.593, Train Accuracy: 0.500
Train Loss: 1.072, Train Accuracy: 0.800
Train Loss: 2.096, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.600
Round 45
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 0.972, Train Accuracy: 0.400
Train Loss: 0.911, Train Accuracy: 0.600
Train Loss: 1.531, Train Accuracy: 1.000
Train Loss: 1.121, Train Accuracy: 0.750
Train Loss: 1.331, Train Accuracy: 1.000
Train Loss: 1.658, Train Accuracy: 0.750
Train Loss: 1.090, Train Accuracy: 1.000
Train Loss: 2.084, Train Accuracy: 1.000
Train Loss: 1.086, Train Accuracy: 0.700
Round 46
Train Loss: 1.107, Train Accuracy: 0.750
Train Loss: 0.960, Train Accuracy: 0.600
Train Loss: 0.930, Train Accuracy: 0.400
Train Loss: 1.512, Train Accuracy: 1.000
Train Loss: 1.178, Train Accuracy: 0.625
Train Loss: 1.181, Train Accuracy: 0.800
Train Loss: 1.589, Train Accuracy: 1.000
Train Loss: 1.037, Train Accuracy: 1.000
Train Loss: 1.995, Train Accuracy: 0.750
Train Loss: 1.126, Train Accuracy: 0.600
Round 47
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 0.963, Train Accuracy: 0.500
Train Loss: 0.930, Train Accuracy: 0.600
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.220, Train Accuracy: 0.800
Train Loss: 1.710, Train Accuracy: 1.000
Train Loss: 1.148, Train Accuracy: 1.000
Train Loss: 1.844, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.400
Round 48
Train Loss: 1.076, Train Accuracy: 0.750
Train Loss: 0.957, Train Accuracy: 0.800
Train Loss: 0.968, Train Accuracy: 0.800
Train Loss: 1.393, Train Accuracy: 0.800
Train Loss: 1.291, Train Accuracy: 0.250
Train Loss: 1.241, Train Accuracy: 0.800
Train Loss: 1.683, Train Accuracy: 0.750

(FLClient pid=2865119) 2025-04-11 09:09:25,311 - INFO - Epoch   2| Train Loss: 0.754| Train Accuracy: 0.750 [repeated 360x across cluster]
(FLClient pid=2865119) 2025-04-11 09:09:25,321 - INFO - Epoch   2| Validation Loss: 1.271, Validation Accuracy: 0.295 [repeated 120x across cluster]
(FLClient pid=2865120) 2025-04-11 09:09:30,506 - INFO - Epoch   2| Train Loss: 0.991| Train Accuracy: 0.500 [repeated 420x across cluster]
(FLClient pid=2865120) 2025-04-11 09:09:30,512 - INFO - Epoch   2| Validation Loss: 1.063, Validation Accuracy: 0.467 [repeated 140x across cluster]
(FLClient pid=2865120) 2025-04-11 09:09:35,607 - INFO - Epoch   2| Train Loss: 0.967| Train Accuracy: 0.500 [repeated 450x across cluster]
(FLClient pid=2865120) 2025-04-11 09:09:35,615 - INFO - Epoch   2| Validation Loss: 1.005, Validation Accuracy: 0.467 [repeated 150x across cluster]
(FLClient pid=2865120) 2025-04-11 09:09:40,734 - INFO - Epoch   2| Train Loss: 0.710| Train Accuracy: 0.800 [repeated 450x across cluster]
(FLClient pid=2865228) 2025-04-11 09:09:40,400 - INFO - Epoch   2| Validation Loss: 1.098, Validation Accuracy: 0.312 [repeated 149x across cluster]
(FLClient pid=2865119) 2025-04-11 09:09:45,810 - INFO - Epoch   0| Train Loss: 0.936| Train Accuracy: 0.500 [repeated 448x across cluster]
(FLClient pid=2865228) 2025-04-11 09:09:45,498 - INFO - Epoch   2| Validation Loss: 1.245, Validation Accuracy: 0.172 [repeated 150x across cluster]
(FLClient pid=2865120) 2025-04-11 09:09:50,920 - INFO - Epoch   2| Train Loss: 0.815| Train Accuracy: 0.600 [repeated 452x across cluster]
(FLClient pid=2865120) 2025-04-11 09:09:50,928 - INFO - Epoch   2| Validation Loss: 0.872, Validation Accuracy: 0.489 [repeated 151x across cluster]
(FLClient pid=2865120) 2025-04-11 09:09:56,025 - INFO - Epoch   2| Train Loss: 0.591| Train Accuracy: 0.800 [repeated 450x across cluster]
(FLClient pid=2865120) 2025-04-11 09:09:56,033 - INFO - Epoch   2| Validation Loss: 0.856, Validation Accuracy: 0.556 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.271, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.500
Train Loss: 1.042, Train Accuracy: 0.400
Train Loss: 1.187, Train Accuracy: 0.600
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.372, Train Accuracy: 0.500
Train Loss: 1.139, Train Accuracy: 0.400
Train Loss: 1.428, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.500
Round 2
Train Loss: 1.310, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.300, Train Accuracy: 0.600
Train Loss: 1.232, Train Accuracy: 0.625
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.416, Train Accuracy: 0.500
Train Loss: 1.133, Train Accuracy: 0.800
Train Loss: 1.484, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.300
Round 3
Train Loss: 1.353, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.042, Train Accuracy: 0.400
Train Loss: 1.296, Train Accuracy: 0.600
Train Loss: 1.247, Train Accuracy: 0.625
Train Loss: 1.312, Train Accuracy: 0.800
Train Loss: 1.420, Train Accuracy: 0.500
Train Loss: 1.135, Train Accuracy: 0.400
Train Loss: 1.549, Train Accuracy: 0.750
Train Loss: 1.193, Train Accuracy: 0.400
Round 4
Train Loss: 1.357, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.315, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.488, Train Accuracy: 0.500
Train Loss: 1.150, Train Accuracy: 0.600
Train Loss: 1.587, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.700
Round 5
Train Loss: 1.414, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.500
Train Loss: 1.031, Train Accuracy: 0.400
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.243, Train Accuracy: 0.625
Train Loss: 1.282, Train Accuracy: 0.800
Train Loss: 1.479, Train Accuracy: 0.250
Train Loss: 1.162, Train Accuracy: 0.400
Train Loss: 1.606, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.700
Round 6
Train Loss: 1.359, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.347, Train Accuracy: 0.600
Train Loss: 1.262, Train Accuracy: 0.625
Train Loss: 1.292, Train Accuracy: 0.800
Train Loss: 1.466, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.400
Train Loss: 1.636, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.400
Round 7
Train Loss: 1.295, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.360, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 0.625
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.521, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.400
Train Loss: 1.685, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.700
Round 8
Train Loss: 1.336, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.027, Train Accuracy: 0.400
Train Loss: 1.382, Train Accuracy: 0.600
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.305, Train Accuracy: 0.800
Train Loss: 1.513, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.400
Train Loss: 1.687, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.400
Round 9
Train Loss: 1.368, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.500
Train Loss: 1.026, Train Accuracy: 0.400
Train Loss: 1.401, Train Accuracy: 0.600
Train Loss: 1.251, Train Accuracy: 0.625
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.492, Train Accuracy: 0.500
Train Loss: 1.166, Train Accuracy: 0.600
Train Loss: 1.663, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.400
Round 10
Train Loss: 1.381, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.400
Train Loss: 1.027, Train Accuracy: 0.000
Train Loss: 1.449, Train Accuracy: 0.800
Train Loss: 1.201, Train Accuracy: 0.625
Train Loss: 1.234, Train Accuracy: 0.800
Train Loss: 1.565, Train Accuracy: 0.500
Train Loss: 1.146, Train Accuracy: 0.200
Train Loss: 1.729, Train Accuracy: 0.750
Train Loss: 1.189, Train Accuracy: 0.600
Round 11
Train Loss: 1.258, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.400
Train Loss: 1.018, Train Accuracy: 0.200
Train Loss: 1.315, Train Accuracy: 0.600
Train Loss: 1.262, Train Accuracy: 0.625
Train Loss: 1.335, Train Accuracy: 0.800
Train Loss: 1.495, Train Accuracy: 0.250
Train Loss: 1.203, Train Accuracy: 0.400
Train Loss: 1.814, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.400
Round 12
Train Loss: 1.254, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.600
Train Loss: 1.015, Train Accuracy: 0.200
Train Loss: 1.428, Train Accuracy: 0.800
Train Loss: 1.271, Train Accuracy: 0.500
Train Loss: 1.342, Train Accuracy: 0.800
Train Loss: 1.510, Train Accuracy: 0.500
Train Loss: 1.170, Train Accuracy: 0.400
Train Loss: 1.674, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.500
Round 13
Train Loss: 1.409, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.600
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 1.394, Train Accuracy: 0.600
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.380, Train Accuracy: 0.800
Train Loss: 1.542, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 0.600
Train Loss: 1.675, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.500
Round 14
Train Loss: 1.314, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.600
Train Loss: 1.015, Train Accuracy: 0.400
Train Loss: 1.385, Train Accuracy: 0.600
Train Loss: 1.194, Train Accuracy: 0.625
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.569, Train Accuracy: 1.000
Train Loss: 1.135, Train Accuracy: 0.600
Train Loss: 1.676, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.500
Round 15
Train Loss: 1.350, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.005, Train Accuracy: 0.400
Train Loss: 1.482, Train Accuracy: 0.800
Train Loss: 1.286, Train Accuracy: 0.625
Train Loss: 1.343, Train Accuracy: 0.800
Train Loss: 1.625, Train Accuracy: 0.500
Train Loss: 1.149, Train Accuracy: 0.400
Train Loss: 1.798, Train Accuracy: 0.750
Train Loss: 1.155, Train Accuracy: 0.500
Round 16
Train Loss: 1.425, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.400
Train Loss: 1.019, Train Accuracy: 0.400
Train Loss: 1.440, Train Accuracy: 0.600
Train Loss: 1.233, Train Accuracy: 0.625
Train Loss: 1.259, Train Accuracy: 0.800
Train Loss: 1.568, Train Accuracy: 0.250
Train Loss: 1.110, Train Accuracy: 0.400
Train Loss: 1.783, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.600
Round 17
Train Loss: 1.346, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.600
Train Loss: 1.017, Train Accuracy: 0.400
Train Loss: 1.404, Train Accuracy: 0.800
Train Loss: 1.215, Train Accuracy: 0.625
Train Loss: 1.353, Train Accuracy: 0.800
Train Loss: 1.526, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.800
Train Loss: 1.823, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.400
Round 18
Train Loss: 1.215, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.500
Train Loss: 0.997, Train Accuracy: 0.600
Train Loss: 1.427, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.500
Train Loss: 1.298, Train Accuracy: 0.800
Train Loss: 1.630, Train Accuracy: 0.750
Train Loss: 1.110, Train Accuracy: 0.200
Train Loss: 1.887, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.500
Round 19
Train Loss: 1.240, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.400
Train Loss: 1.002, Train Accuracy: 0.200
Train Loss: 1.423, Train Accuracy: 0.800
Train Loss: 1.183, Train Accuracy: 0.625
Train Loss: 1.348, Train Accuracy: 0.800
Train Loss: 1.501, Train Accuracy: 1.000
Train Loss: 1.131, Train Accuracy: 0.800
Train Loss: 1.833, Train Accuracy: 1.000
Train Loss: 1.139, Train Accuracy: 0.600
Round 20
Train Loss: 1.269, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.600
Train Loss: 1.003, Train Accuracy: 0.400
Train Loss: 1.468, Train Accuracy: 0.600
Train Loss: 1.220, Train Accuracy: 0.625
Train Loss: 1.347, Train Accuracy: 0.800
Train Loss: 1.541, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.600
Train Loss: 1.913, Train Accuracy: 0.750
Train Loss: 1.213, Train Accuracy: 0.400
Round 21
Train Loss: 1.229, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.500
Train Loss: 0.993, Train Accuracy: 0.400
Train Loss: 1.374, Train Accuracy: 0.600
Train Loss: 1.167, Train Accuracy: 0.750
Train Loss: 1.421, Train Accuracy: 0.800
Train Loss: 1.654, Train Accuracy: 0.500
Train Loss: 1.104, Train Accuracy: 0.400
Train Loss: 1.751, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.400
Round 22
Train Loss: 1.196, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.600
Train Loss: 0.986, Train Accuracy: 0.400
Train Loss: 1.372, Train Accuracy: 0.600
Train Loss: 1.191, Train Accuracy: 0.750
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.543, Train Accuracy: 0.750
Train Loss: 1.155, Train Accuracy: 0.600
Train Loss: 1.782, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.600
Round 23
Train Loss: 1.317, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.700
Train Loss: 1.001, Train Accuracy: 0.400
Train Loss: 1.402, Train Accuracy: 1.000
Train Loss: 1.210, Train Accuracy: 0.750
Train Loss: 1.406, Train Accuracy: 0.800
Train Loss: 1.563, Train Accuracy: 0.500
Train Loss: 1.128, Train Accuracy: 0.800
Train Loss: 1.791, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.300
Round 24
Train Loss: 1.369, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.700
Train Loss: 0.990, Train Accuracy: 0.600
Train Loss: 1.438, Train Accuracy: 0.800
Train Loss: 1.196, Train Accuracy: 0.625
Train Loss: 1.374, Train Accuracy: 0.800
Train Loss: 1.536, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.600
Train Loss: 1.843, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.500
Round 25
Train Loss: 1.280, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.600
Train Loss: 0.984, Train Accuracy: 0.600
Train Loss: 1.319, Train Accuracy: 0.600
Train Loss: 1.196, Train Accuracy: 0.625
Train Loss: 1.402, Train Accuracy: 0.800
Train Loss: 1.512, Train Accuracy: 0.500
Train Loss: 1.071, Train Accuracy: 0.600
Train Loss: 1.916, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.400
Round 26
Train Loss: 1.210, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.600
Train Loss: 0.973, Train Accuracy: 0.600
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.232, Train Accuracy: 0.750
Train Loss: 1.321, Train Accuracy: 0.800
Train Loss: 1.658, Train Accuracy: 0.500
Train Loss: 1.135, Train Accuracy: 0.800
Train Loss: 1.808, Train Accuracy: 0.750
Train Loss: 1.193, Train Accuracy: 0.600
Round 27
Train Loss: 1.309, Train Accuracy: 0.750
Train Loss: 1.018, Train Accuracy: 0.600
Train Loss: 0.970, Train Accuracy: 0.600
Train Loss: 1.429, Train Accuracy: 0.800
Train Loss: 1.212, Train Accuracy: 0.875
Train Loss: 1.391, Train Accuracy: 0.800
Train Loss: 1.465, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.600
Train Loss: 1.968, Train Accuracy: 0.750
Train Loss: 1.097, Train Accuracy: 0.500
Round 28
Train Loss: 1.317, Train Accuracy: 0.750
Train Loss: 1.013, Train Accuracy: 0.600
Train Loss: 0.987, Train Accuracy: 0.400
Train Loss: 1.362, Train Accuracy: 0.600
Train Loss: 1.170, Train Accuracy: 0.750
Train Loss: 1.413, Train Accuracy: 0.800
Train Loss: 1.550, Train Accuracy: 1.000
Train Loss: 1.047, Train Accuracy: 0.600
Train Loss: 1.950, Train Accuracy: 0.750
Train Loss: 1.222, Train Accuracy: 0.600
Round 29
Train Loss: 1.225, Train Accuracy: 0.750
Train Loss: 1.005, Train Accuracy: 0.700
Train Loss: 0.951, Train Accuracy: 0.600
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.171, Train Accuracy: 0.625
Train Loss: 1.333, Train Accuracy: 0.800
Train Loss: 1.610, Train Accuracy: 0.750
Train Loss: 1.211, Train Accuracy: 0.600
Train Loss: 1.893, Train Accuracy: 0.750
Train Loss: 1.103, Train Accuracy: 0.500
Round 30
Train Loss: 1.350, Train Accuracy: 0.750
Train Loss: 1.005, Train Accuracy: 0.500
Train Loss: 0.959, Train Accuracy: 0.200
Train Loss: 1.473, Train Accuracy: 0.800
Train Loss: 1.154, Train Accuracy: 0.875
Train Loss: 1.312, Train Accuracy: 0.800
Train Loss: 1.518, Train Accuracy: 0.500
Train Loss: 1.081, Train Accuracy: 0.800
Train Loss: 1.958, Train Accuracy: 0.750
Train Loss: 1.158, Train Accuracy: 0.700
Round 31
Train Loss: 1.373, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.800
Train Loss: 0.972, Train Accuracy: 0.600
Train Loss: 1.393, Train Accuracy: 0.800
Train Loss: 1.206, Train Accuracy: 0.875
Train Loss: 1.380, Train Accuracy: 0.800
Train Loss: 1.556, Train Accuracy: 1.000
Train Loss: 1.097, Train Accuracy: 0.800
Train Loss: 1.747, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.600
Round 32
Train Loss: 1.386, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.700
Train Loss: 0.959, Train Accuracy: 0.600
Train Loss: 1.342, Train Accuracy: 0.800
Train Loss: 1.226, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.800
Train Loss: 1.631, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.600
Train Loss: 1.834, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.700
Round 33
Train Loss: 1.209, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.700
Train Loss: 0.951, Train Accuracy: 0.400
Train Loss: 1.489, Train Accuracy: 1.000
Train Loss: 1.170, Train Accuracy: 0.625
Train Loss: 1.333, Train Accuracy: 0.800
Train Loss: 1.498, Train Accuracy: 0.500
Train Loss: 1.032, Train Accuracy: 0.400
Train Loss: 2.041, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.600
Round 34
Train Loss: 1.141, Train Accuracy: 0.750
Train Loss: 1.007, Train Accuracy: 0.700
Train Loss: 0.956, Train Accuracy: 0.400
Train Loss: 1.281, Train Accuracy: 1.000
Train Loss: 1.198, Train Accuracy: 0.750
Train Loss: 1.315, Train Accuracy: 0.800
Train Loss: 1.512, Train Accuracy: 1.000
Train Loss: 1.097, Train Accuracy: 0.400
Train Loss: 1.648, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.600
Round 35
Train Loss: 1.159, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.600
Train Loss: 0.942, Train Accuracy: 0.600
Train Loss: 1.344, Train Accuracy: 1.000
Train Loss: 1.130, Train Accuracy: 0.750
Train Loss: 1.318, Train Accuracy: 0.800
Train Loss: 1.606, Train Accuracy: 0.500
Train Loss: 1.061, Train Accuracy: 0.800
Train Loss: 2.058, Train Accuracy: 1.000
Train Loss: 1.280, Train Accuracy: 0.600
Round 36
Train Loss: 1.311, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.700
Train Loss: 0.925, Train Accuracy: 0.400
Train Loss: 1.298, Train Accuracy: 0.800
Train Loss: 1.149, Train Accuracy: 0.750
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.468, Train Accuracy: 1.000
Train Loss: 1.125, Train Accuracy: 0.800
Train Loss: 1.761, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Round 37
Train Loss: 1.200, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.600
Train Loss: 0.988, Train Accuracy: 0.600
Train Loss: 1.439, Train Accuracy: 0.600
Train Loss: 1.239, Train Accuracy: 0.875
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.482, Train Accuracy: 1.000
Train Loss: 1.120, Train Accuracy: 0.600
Train Loss: 1.889, Train Accuracy: 0.750
Train Loss: 0.996, Train Accuracy: 0.600
Round 38
Train Loss: 1.279, Train Accuracy: 0.750
Train Loss: 0.982, Train Accuracy: 0.500
Train Loss: 0.918, Train Accuracy: 0.600
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.069, Train Accuracy: 0.750
Train Loss: 1.234, Train Accuracy: 0.800
Train Loss: 1.487, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.800
Train Loss: 1.950, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.500
Round 39
Train Loss: 1.339, Train Accuracy: 0.750
Train Loss: 0.976, Train Accuracy: 0.700
Train Loss: 0.974, Train Accuracy: 0.800
Train Loss: 1.460, Train Accuracy: 0.800
Train Loss: 1.231, Train Accuracy: 0.750
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.485, Train Accuracy: 1.000
Train Loss: 1.043, Train Accuracy: 0.800
Train Loss: 2.022, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.700
Round 40
Train Loss: 1.123, Train Accuracy: 0.750
Train Loss: 1.033, Train Accuracy: 0.500
Train Loss: 0.958, Train Accuracy: 0.600
Train Loss: 1.295, Train Accuracy: 0.600
Train Loss: 1.185, Train Accuracy: 0.625
Train Loss: 1.346, Train Accuracy: 0.800
Train Loss: 1.665, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.400
Train Loss: 2.043, Train Accuracy: 1.000
Train Loss: 1.057, Train Accuracy: 0.900
Round 41
Train Loss: 1.401, Train Accuracy: 0.750
Train Loss: 0.953, Train Accuracy: 0.800
Train Loss: 0.916, Train Accuracy: 0.400
Train Loss: 1.318, Train Accuracy: 0.800
Train Loss: 1.159, Train Accuracy: 0.500
Train Loss: 1.500, Train Accuracy: 1.000
Train Loss: 1.644, Train Accuracy: 1.000
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 1.776, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.700
Round 42
Train Loss: 1.302, Train Accuracy: 0.750
Train Loss: 0.930, Train Accuracy: 0.600
Train Loss: 0.942, Train Accuracy: 0.800
Train Loss: 1.350, Train Accuracy: 1.000
Train Loss: 1.218, Train Accuracy: 0.750
Train Loss: 1.352, Train Accuracy: 0.800
Train Loss: 1.749, Train Accuracy: 0.500
Train Loss: 1.004, Train Accuracy: 0.800
Train Loss: 1.911, Train Accuracy: 0.750
Train Loss: 1.294, Train Accuracy: 0.600
Round 43
Train Loss: 1.242, Train Accuracy: 0.750
Train Loss: 0.982, Train Accuracy: 0.600
Train Loss: 0.899, Train Accuracy: 0.800
Train Loss: 1.353, Train Accuracy: 1.000
Train Loss: 1.053, Train Accuracy: 0.250
Train Loss: 1.339, Train Accuracy: 0.800
Train Loss: 1.555, Train Accuracy: 1.000
Train Loss: 1.187, Train Accuracy: 0.600
Train Loss: 2.120, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 0.700
Round 44
Train Loss: 1.121, Train Accuracy: 0.750
Train Loss: 1.004, Train Accuracy: 0.800
Train Loss: 0.908, Train Accuracy: 0.600
Train Loss: 1.530, Train Accuracy: 1.000
Train Loss: 1.097, Train Accuracy: 0.500
Train Loss: 1.240, Train Accuracy: 0.800
Train Loss: 1.512, Train Accuracy: 1.000
Train Loss: 0.991, Train Accuracy: 0.800
Train Loss: 1.766, Train Accuracy: 0.750
Train Loss: 1.098, Train Accuracy: 0.700
Round 45
Train Loss: 1.154, Train Accuracy: 0.750
Train Loss: 0.956, Train Accuracy: 0.800
Train Loss: 0.926, Train Accuracy: 1.000
Train Loss: 1.297, Train Accuracy: 0.600
Train Loss: 1.046, Train Accuracy: 0.750
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.627, Train Accuracy: 1.000
Train Loss: 1.051, Train Accuracy: 0.600
Train Loss: 1.927, Train Accuracy: 0.750
Train Loss: 1.336, Train Accuracy: 0.500
Round 46
Train Loss: 1.075, Train Accuracy: 0.750
Train Loss: 0.924, Train Accuracy: 0.500
Train Loss: 0.924, Train Accuracy: 0.600
Train Loss: 1.285, Train Accuracy: 0.800
Train Loss: 1.049, Train Accuracy: 0.250
Train Loss: 1.382, Train Accuracy: 1.000
Train Loss: 1.668, Train Accuracy: 1.000
Train Loss: 1.301, Train Accuracy: 0.600
Train Loss: 2.360, Train Accuracy: 1.000
Train Loss: 1.317, Train Accuracy: 0.800
Round 47
Train Loss: 1.319, Train Accuracy: 0.750
Train Loss: 0.962, Train Accuracy: 0.800
Train Loss: 0.919, Train Accuracy: 0.600
Train Loss: 1.397, Train Accuracy: 1.000
Train Loss: 1.114, Train Accuracy: 0.875
Train Loss: 1.219, Train Accuracy: 0.800
Train Loss: 1.580, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.600
Train Loss: 2.104, Train Accuracy: 1.000
Train Loss: 0.956, Train Accuracy: 0.800
Round 48
Train Loss: 1.221, Train Accuracy: 0.750
Train Loss: 0.911, Train Accuracy: 0.600
Train Loss: 0.885, Train Accuracy: 1.000
Train Loss: 1.275, Train Accuracy: 1.000
Train Loss: 1.166, Train Accuracy: 0.875
Train Loss: 1.339, Train Accuracy: 0.800
Train Loss: 1.481, Train Accuracy: 0.750

(FLClient pid=2866164) 2025-04-11 09:10:07,335 - INFO - Epoch   2| Train Loss: 0.710| Train Accuracy: 0.750 [repeated 330x across cluster]
(FLClient pid=2865228) 2025-04-11 09:09:59,501 - INFO - Epoch   2| Validation Loss: 0.842, Validation Accuracy: 0.578 [repeated 109x across cluster]
(FLClient pid=2866164) 2025-04-11 09:10:12,574 - INFO - Epoch   2| Train Loss: 0.611| Train Accuracy: 0.750 [repeated 390x across cluster]
(FLClient pid=2866164) 2025-04-11 09:10:12,582 - INFO - Epoch   2| Validation Loss: 1.278, Validation Accuracy: 0.295 [repeated 131x across cluster]
(FLClient pid=2866164) 2025-04-11 09:10:17,660 - INFO - Epoch   0| Train Loss: 1.223| Train Accuracy: 0.250 [repeated 448x across cluster]
(FLClient pid=2866425) 2025-04-11 09:10:17,346 - INFO - Epoch   2| Validation Loss: 1.080, Validation Accuracy: 0.500 [repeated 149x across cluster]
(FLClient pid=2866168) 2025-04-11 09:10:22,770 - INFO - Epoch   0| Train Loss: 0.908| Train Accuracy: 0.625 [repeated 450x across cluster]
(FLClient pid=2866425) 2025-04-11 09:10:22,461 - INFO - Epoch   2| Validation Loss: 1.272, Validation Accuracy: 0.156 [repeated 150x across cluster]
(FLClient pid=2866164) 2025-04-11 09:10:27,947 - INFO - Epoch   1| Train Loss: 0.587| Train Accuracy: 0.750 [repeated 451x across cluster]
(FLClient pid=2866425) 2025-04-11 09:10:27,627 - INFO - Epoch   2| Validation Loss: 1.523, Validation Accuracy: 0.156 [repeated 150x across cluster]
(FLClient pid=2866164) 2025-04-11 09:10:33,052 - INFO - Epoch   1| Train Loss: 0.467| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2866425) 2025-04-11 09:10:32,727 - INFO - Epoch   2| Validation Loss: 0.892, Validation Accuracy: 0.469 [repeated 150x across cluster]
(FLClient pid=2866164) 2025-04-11 09:10:38,176 - INFO - Epoch   2| Train Loss: 0.387| Train Accuracy: 1.000 [repeated 451x across cluster]
(FLClient pid=2866425) 2025-04-11 09:10:37,836 - INFO - Epoch   2| Validation Loss: 1.221, Validation Accuracy: 0.234 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.358, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.073, Train Accuracy: 0.600
Train Loss: 1.177, Train Accuracy: 0.600
Train Loss: 1.161, Train Accuracy: 0.625
Train Loss: 1.314, Train Accuracy: 0.800
Train Loss: 1.263, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.400
Train Loss: 1.444, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.100
Round 2
Train Loss: 1.352, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.500
Train Loss: 1.069, Train Accuracy: 0.200
Train Loss: 1.237, Train Accuracy: 0.600
Train Loss: 1.189, Train Accuracy: 0.625
Train Loss: 1.256, Train Accuracy: 0.800
Train Loss: 1.347, Train Accuracy: 0.500
Train Loss: 1.140, Train Accuracy: 0.400
Train Loss: 1.477, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.300
Round 3
Train Loss: 1.297, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.063, Train Accuracy: 0.400
Train Loss: 1.252, Train Accuracy: 0.600
Train Loss: 1.229, Train Accuracy: 0.625
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.352, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.400
Train Loss: 1.555, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.300
Round 4
Train Loss: 1.345, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.058, Train Accuracy: 0.200
Train Loss: 1.285, Train Accuracy: 0.600
Train Loss: 1.234, Train Accuracy: 0.625
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.381, Train Accuracy: 0.250
Train Loss: 1.180, Train Accuracy: 0.600
Train Loss: 1.527, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.400
Round 5
Train Loss: 1.278, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.051, Train Accuracy: 0.600
Train Loss: 1.331, Train Accuracy: 0.600
Train Loss: 1.242, Train Accuracy: 0.625
Train Loss: 1.322, Train Accuracy: 0.800
Train Loss: 1.428, Train Accuracy: 0.500
Train Loss: 1.165, Train Accuracy: 0.400
Train Loss: 1.620, Train Accuracy: 0.750
Train Loss: 1.158, Train Accuracy: 0.400
Round 6
Train Loss: 1.423, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.043, Train Accuracy: 0.400
Train Loss: 1.298, Train Accuracy: 0.600
Train Loss: 1.257, Train Accuracy: 0.625
Train Loss: 1.339, Train Accuracy: 0.800
Train Loss: 1.426, Train Accuracy: 0.000
Train Loss: 1.181, Train Accuracy: 0.400
Train Loss: 1.612, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.600
Round 7
Train Loss: 1.278, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.400
Train Loss: 1.045, Train Accuracy: 0.400
Train Loss: 1.348, Train Accuracy: 0.600
Train Loss: 1.260, Train Accuracy: 0.625
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.420, Train Accuracy: 0.500
Train Loss: 1.143, Train Accuracy: 0.200
Train Loss: 1.639, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.400
Round 8
Train Loss: 1.348, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.700
Train Loss: 1.045, Train Accuracy: 0.400
Train Loss: 1.349, Train Accuracy: 0.600
Train Loss: 1.256, Train Accuracy: 0.625
Train Loss: 1.307, Train Accuracy: 0.800
Train Loss: 1.438, Train Accuracy: 0.500
Train Loss: 1.153, Train Accuracy: 0.800
Train Loss: 1.685, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.300
Round 9
Train Loss: 1.392, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.038, Train Accuracy: 0.400
Train Loss: 1.348, Train Accuracy: 0.600
Train Loss: 1.268, Train Accuracy: 0.625
Train Loss: 1.248, Train Accuracy: 0.800
Train Loss: 1.473, Train Accuracy: 0.500
Train Loss: 1.199, Train Accuracy: 0.400
Train Loss: 1.712, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.500
Round 10
Train Loss: 1.418, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Train Loss: 1.045, Train Accuracy: 0.400
Train Loss: 1.392, Train Accuracy: 0.600
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.486, Train Accuracy: 0.500
Train Loss: 1.161, Train Accuracy: 0.600
Train Loss: 1.739, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.600
Round 11
Train Loss: 1.414, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.040, Train Accuracy: 0.400
Train Loss: 1.356, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.377, Train Accuracy: 0.800
Train Loss: 1.506, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.200
Train Loss: 1.803, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.300
Round 12
Train Loss: 1.354, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.400
Train Loss: 1.027, Train Accuracy: 0.400
Train Loss: 1.395, Train Accuracy: 0.600
Train Loss: 1.288, Train Accuracy: 0.625
Train Loss: 1.342, Train Accuracy: 0.800
Train Loss: 1.483, Train Accuracy: 0.500
Train Loss: 1.205, Train Accuracy: 0.400
Train Loss: 1.791, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.500
Round 13
Train Loss: 1.371, Train Accuracy: 0.750
Train Loss: 1.062, Train Accuracy: 0.500
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 1.395, Train Accuracy: 0.600
Train Loss: 1.251, Train Accuracy: 0.625
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.472, Train Accuracy: 0.250
Train Loss: 1.139, Train Accuracy: 0.600
Train Loss: 1.786, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.500
Round 14
Train Loss: 1.278, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 1.404, Train Accuracy: 0.600
Train Loss: 1.261, Train Accuracy: 0.625
Train Loss: 1.383, Train Accuracy: 0.800
Train Loss: 1.483, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.600
Train Loss: 1.720, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.700
Round 15
Train Loss: 1.501, Train Accuracy: 0.750
Train Loss: 1.062, Train Accuracy: 0.500
Train Loss: 1.022, Train Accuracy: 0.200
Train Loss: 1.396, Train Accuracy: 0.600
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 1.449, Train Accuracy: 0.800
Train Loss: 1.473, Train Accuracy: 0.500
Train Loss: 1.163, Train Accuracy: 0.600
Train Loss: 1.703, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.500
Round 16
Train Loss: 1.411, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.415, Train Accuracy: 0.800
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.366, Train Accuracy: 0.800
Train Loss: 1.490, Train Accuracy: 0.500
Train Loss: 1.208, Train Accuracy: 0.600
Train Loss: 1.806, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.300
Round 17
Train Loss: 1.244, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.500
Train Loss: 1.018, Train Accuracy: 0.400
Train Loss: 1.422, Train Accuracy: 0.600
Train Loss: 1.268, Train Accuracy: 0.625
Train Loss: 1.352, Train Accuracy: 0.800
Train Loss: 1.546, Train Accuracy: 0.500
Train Loss: 1.231, Train Accuracy: 0.600
Train Loss: 1.913, Train Accuracy: 0.750
Train Loss: 1.124, Train Accuracy: 0.400
Round 18
Train Loss: 1.381, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.500
Train Loss: 1.015, Train Accuracy: 0.400
Train Loss: 1.450, Train Accuracy: 0.600
Train Loss: 1.184, Train Accuracy: 0.625
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.502, Train Accuracy: 0.500
Train Loss: 1.159, Train Accuracy: 0.600
Train Loss: 1.781, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.400
Round 19
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.700
Train Loss: 1.009, Train Accuracy: 0.600
Train Loss: 1.400, Train Accuracy: 0.800
Train Loss: 1.218, Train Accuracy: 0.625
Train Loss: 1.430, Train Accuracy: 0.800
Train Loss: 1.597, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.600
Train Loss: 1.850, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.600
Round 20
Train Loss: 1.445, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.600
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.441, Train Accuracy: 0.600
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.379, Train Accuracy: 0.800
Train Loss: 1.537, Train Accuracy: 0.500
Train Loss: 1.133, Train Accuracy: 0.400
Train Loss: 1.879, Train Accuracy: 0.750
Train Loss: 1.113, Train Accuracy: 0.400
Round 21
Train Loss: 1.345, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.200
Train Loss: 1.456, Train Accuracy: 0.600
Train Loss: 1.227, Train Accuracy: 0.625
Train Loss: 1.315, Train Accuracy: 0.800
Train Loss: 1.566, Train Accuracy: 0.500
Train Loss: 1.126, Train Accuracy: 0.400
Train Loss: 1.929, Train Accuracy: 0.750
Train Loss: 1.097, Train Accuracy: 0.400
Round 22
Train Loss: 1.321, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.500
Train Loss: 1.014, Train Accuracy: 0.200
Train Loss: 1.401, Train Accuracy: 0.600
Train Loss: 1.220, Train Accuracy: 0.750
Train Loss: 1.370, Train Accuracy: 0.800
Train Loss: 1.511, Train Accuracy: 0.250
Train Loss: 1.129, Train Accuracy: 0.200
Train Loss: 2.044, Train Accuracy: 0.750
Train Loss: 1.203, Train Accuracy: 0.400
Round 23
Train Loss: 1.482, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.300
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.497, Train Accuracy: 0.800
Train Loss: 1.208, Train Accuracy: 0.625
Train Loss: 1.298, Train Accuracy: 0.800
Train Loss: 1.506, Train Accuracy: 0.500
Train Loss: 1.113, Train Accuracy: 0.600
Train Loss: 1.810, Train Accuracy: 0.750
Train Loss: 1.132, Train Accuracy: 0.400
Round 24
Train Loss: 1.297, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 1.009, Train Accuracy: 0.400
Train Loss: 1.414, Train Accuracy: 0.600
Train Loss: 1.184, Train Accuracy: 0.625
Train Loss: 1.466, Train Accuracy: 0.800
Train Loss: 1.555, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.600
Train Loss: 1.843, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.500
Round 25
Train Loss: 1.258, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.500
Train Loss: 0.991, Train Accuracy: 0.200
Train Loss: 1.477, Train Accuracy: 0.800
Train Loss: 1.206, Train Accuracy: 0.750
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.509, Train Accuracy: 0.500
Train Loss: 1.255, Train Accuracy: 0.600
Train Loss: 1.883, Train Accuracy: 0.750
Train Loss: 1.118, Train Accuracy: 0.700
Round 26
Train Loss: 1.245, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.400
Train Loss: 1.002, Train Accuracy: 0.400
Train Loss: 1.429, Train Accuracy: 0.600
Train Loss: 1.227, Train Accuracy: 0.625
Train Loss: 1.458, Train Accuracy: 0.800
Train Loss: 1.518, Train Accuracy: 0.500
Train Loss: 1.147, Train Accuracy: 0.800
Train Loss: 1.917, Train Accuracy: 0.750
Train Loss: 1.148, Train Accuracy: 0.500
Round 27
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.700
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.419, Train Accuracy: 0.600
Train Loss: 1.196, Train Accuracy: 0.750
Train Loss: 1.431, Train Accuracy: 0.800
Train Loss: 1.548, Train Accuracy: 1.000
Train Loss: 1.143, Train Accuracy: 0.200
Train Loss: 1.973, Train Accuracy: 1.000
Train Loss: 1.150, Train Accuracy: 0.400
Round 28
Train Loss: 1.335, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.500
Train Loss: 0.987, Train Accuracy: 0.200
Train Loss: 1.484, Train Accuracy: 0.600
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 1.365, Train Accuracy: 0.800
Train Loss: 1.565, Train Accuracy: 1.000
Train Loss: 1.209, Train Accuracy: 1.000
Train Loss: 1.887, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.300
Round 29
Train Loss: 1.364, Train Accuracy: 0.750
Train Loss: 1.033, Train Accuracy: 0.600
Train Loss: 1.000, Train Accuracy: 0.400
Train Loss: 1.365, Train Accuracy: 0.800
Train Loss: 1.180, Train Accuracy: 0.625
Train Loss: 1.419, Train Accuracy: 0.800
Train Loss: 1.468, Train Accuracy: 0.500
Train Loss: 1.206, Train Accuracy: 0.400
Train Loss: 2.028, Train Accuracy: 0.750
Train Loss: 1.142, Train Accuracy: 0.700
Round 30
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.600
Train Loss: 0.983, Train Accuracy: 0.000
Train Loss: 1.410, Train Accuracy: 0.600
Train Loss: 1.215, Train Accuracy: 0.750
Train Loss: 1.535, Train Accuracy: 0.800
Train Loss: 1.432, Train Accuracy: 0.500
Train Loss: 1.227, Train Accuracy: 0.600
Train Loss: 1.925, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.400
Round 31
Train Loss: 1.479, Train Accuracy: 0.750
Train Loss: 1.008, Train Accuracy: 0.700
Train Loss: 0.972, Train Accuracy: 0.600
Train Loss: 1.283, Train Accuracy: 0.600
Train Loss: 1.242, Train Accuracy: 0.625
Train Loss: 1.381, Train Accuracy: 0.800
Train Loss: 1.548, Train Accuracy: 0.250
Train Loss: 1.146, Train Accuracy: 0.600
Train Loss: 1.999, Train Accuracy: 0.750
Train Loss: 1.138, Train Accuracy: 0.600
Round 32
Train Loss: 1.211, Train Accuracy: 0.750
Train Loss: 1.012, Train Accuracy: 0.500
Train Loss: 0.985, Train Accuracy: 0.400
Train Loss: 1.374, Train Accuracy: 0.800
Train Loss: 1.194, Train Accuracy: 0.625
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 0.500
Train Loss: 1.082, Train Accuracy: 0.600
Train Loss: 2.101, Train Accuracy: 0.750
Train Loss: 1.244, Train Accuracy: 0.500
Round 33
Train Loss: 1.357, Train Accuracy: 0.750
Train Loss: 1.012, Train Accuracy: 0.600
Train Loss: 1.005, Train Accuracy: 0.400
Train Loss: 1.394, Train Accuracy: 0.600
Train Loss: 1.171, Train Accuracy: 0.750
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.569, Train Accuracy: 0.500
Train Loss: 1.207, Train Accuracy: 0.600
Train Loss: 1.933, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.700
Round 34
Train Loss: 1.272, Train Accuracy: 0.750
Train Loss: 0.998, Train Accuracy: 0.600
Train Loss: 0.969, Train Accuracy: 0.800
Train Loss: 1.428, Train Accuracy: 0.600
Train Loss: 1.197, Train Accuracy: 0.750
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.643, Train Accuracy: 0.500
Train Loss: 1.132, Train Accuracy: 0.600
Train Loss: 2.055, Train Accuracy: 0.750
Train Loss: 1.092, Train Accuracy: 0.500
Round 35
Train Loss: 1.440, Train Accuracy: 0.750
Train Loss: 1.012, Train Accuracy: 0.600
Train Loss: 0.955, Train Accuracy: 0.600
Train Loss: 1.454, Train Accuracy: 0.800
Train Loss: 1.198, Train Accuracy: 0.625
Train Loss: 1.465, Train Accuracy: 0.800
Train Loss: 1.597, Train Accuracy: 0.500
Train Loss: 1.235, Train Accuracy: 0.200
Train Loss: 1.799, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.500
Round 36
Train Loss: 1.586, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.800
Train Loss: 0.971, Train Accuracy: 0.800
Train Loss: 1.368, Train Accuracy: 0.800
Train Loss: 1.130, Train Accuracy: 0.875
Train Loss: 1.449, Train Accuracy: 0.800
Train Loss: 1.594, Train Accuracy: 0.750
Train Loss: 1.111, Train Accuracy: 1.000
Train Loss: 1.762, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.600
Round 37
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 1.004, Train Accuracy: 0.700
Train Loss: 0.970, Train Accuracy: 0.400
Train Loss: 1.527, Train Accuracy: 1.000
Train Loss: 1.161, Train Accuracy: 0.750
Train Loss: 1.380, Train Accuracy: 0.800
Train Loss: 1.568, Train Accuracy: 0.500
Train Loss: 1.100, Train Accuracy: 0.800
Train Loss: 1.972, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.600
Round 38
Train Loss: 1.143, Train Accuracy: 0.750
Train Loss: 1.005, Train Accuracy: 0.400
Train Loss: 0.997, Train Accuracy: 0.400
Train Loss: 1.387, Train Accuracy: 1.000
Train Loss: 1.123, Train Accuracy: 0.625
Train Loss: 1.386, Train Accuracy: 0.800
Train Loss: 1.503, Train Accuracy: 0.500
Train Loss: 1.071, Train Accuracy: 0.800
Train Loss: 2.030, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 0.700
Round 39
Train Loss: 1.289, Train Accuracy: 0.750
Train Loss: 0.992, Train Accuracy: 0.800
Train Loss: 0.953, Train Accuracy: 0.400
Train Loss: 1.380, Train Accuracy: 1.000
Train Loss: 1.189, Train Accuracy: 0.625
Train Loss: 1.237, Train Accuracy: 0.800
Train Loss: 1.561, Train Accuracy: 1.000
Train Loss: 1.055, Train Accuracy: 0.800
Train Loss: 1.843, Train Accuracy: 0.750
Train Loss: 1.092, Train Accuracy: 0.300
Round 40
Train Loss: 1.181, Train Accuracy: 0.750
Train Loss: 0.980, Train Accuracy: 0.600
Train Loss: 0.945, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.600
Train Loss: 1.198, Train Accuracy: 0.625
Train Loss: 1.523, Train Accuracy: 0.800
Train Loss: 1.445, Train Accuracy: 0.500
Train Loss: 1.096, Train Accuracy: 0.800
Train Loss: 2.083, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.800
Round 41
Train Loss: 1.377, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 0.933, Train Accuracy: 0.400
Train Loss: 1.305, Train Accuracy: 0.600
Train Loss: 1.214, Train Accuracy: 0.625
Train Loss: 1.457, Train Accuracy: 0.800
Train Loss: 1.686, Train Accuracy: 1.000
Train Loss: 1.148, Train Accuracy: 0.400
Train Loss: 1.970, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.600
Round 42
Train Loss: 1.501, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 0.926, Train Accuracy: 0.800
Train Loss: 1.250, Train Accuracy: 0.600
Train Loss: 1.157, Train Accuracy: 0.750
Train Loss: 1.518, Train Accuracy: 0.800
Train Loss: 1.449, Train Accuracy: 0.250
Train Loss: 1.104, Train Accuracy: 0.800
Train Loss: 1.916, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.500
Round 43
Train Loss: 1.333, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.600
Train Loss: 0.928, Train Accuracy: 0.600
Train Loss: 1.469, Train Accuracy: 0.600
Train Loss: 1.119, Train Accuracy: 0.875
Train Loss: 1.428, Train Accuracy: 0.800
Train Loss: 1.634, Train Accuracy: 0.500
Train Loss: 1.073, Train Accuracy: 0.800
Train Loss: 1.671, Train Accuracy: 0.750
Train Loss: 1.272, Train Accuracy: 0.600
Round 44
Train Loss: 1.380, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 0.951, Train Accuracy: 0.600
Train Loss: 1.573, Train Accuracy: 0.600
Train Loss: 1.160, Train Accuracy: 0.750
Train Loss: 1.369, Train Accuracy: 0.800
Train Loss: 1.502, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.800
Train Loss: 1.893, Train Accuracy: 0.750
Train Loss: 1.113, Train Accuracy: 0.600
Round 45
Train Loss: 1.068, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.800
Train Loss: 0.926, Train Accuracy: 0.600
Train Loss: 1.294, Train Accuracy: 0.600
Train Loss: 1.082, Train Accuracy: 0.750
Train Loss: 1.571, Train Accuracy: 0.800
Train Loss: 1.661, Train Accuracy: 1.000
Train Loss: 1.165, Train Accuracy: 0.600
Train Loss: 1.820, Train Accuracy: 0.750
Train Loss: 1.237, Train Accuracy: 0.800
Round 46
Train Loss: 1.373, Train Accuracy: 0.500
Train Loss: 1.055, Train Accuracy: 0.400
Train Loss: 0.945, Train Accuracy: 0.400
Train Loss: 1.387, Train Accuracy: 0.800
Train Loss: 1.107, Train Accuracy: 0.750
Train Loss: 1.324, Train Accuracy: 0.800
Train Loss: 1.735, Train Accuracy: 1.000
Train Loss: 1.173, Train Accuracy: 0.800
Train Loss: 1.940, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.500
Round 47
Train Loss: 1.251, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.500
Train Loss: 0.968, Train Accuracy: 0.600
Train Loss: 1.592, Train Accuracy: 0.800
Train Loss: 1.062, Train Accuracy: 0.500
Train Loss: 1.453, Train Accuracy: 0.800
Train Loss: 1.717, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.800
Train Loss: 1.924, Train Accuracy: 0.750
Train Loss: 1.360, Train Accuracy: 0.600
Round 48
Train Loss: 1.248, Train Accuracy: 0.750
Train Loss: 0.931, Train Accuracy: 0.600
Train Loss: 0.980, Train Accuracy: 0.600
Train Loss: 1.405, Train Accuracy: 1.000
Train Loss: 1.221, Train Accuracy: 0.750
Train Loss: 1.465, Train Accuracy: 0.800
Train Loss: 1.429, Train Accuracy: 0.750

(FLClient pid=2867238) 2025-04-11 09:10:49,870 - INFO - Epoch   2| Train Loss: 0.744| Train Accuracy: 0.750 [repeated 360x across cluster]
(FLClient pid=2867238) 2025-04-11 09:10:49,879 - INFO - Epoch   2| Validation Loss: 1.189, Validation Accuracy: 0.295 [repeated 121x across cluster]
(FLClient pid=2867238) 2025-04-11 09:10:54,975 - INFO - Epoch   2| Train Loss: 0.606| Train Accuracy: 0.750 [repeated 390x across cluster]
(FLClient pid=2867238) 2025-04-11 09:10:54,982 - INFO - Epoch   2| Validation Loss: 1.329, Validation Accuracy: 0.295 [repeated 130x across cluster]
(FLClient pid=2867238) 2025-04-11 09:11:00,067 - INFO - Epoch   2| Train Loss: 0.581| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2867238) 2025-04-11 09:11:00,072 - INFO - Epoch   2| Validation Loss: 1.300, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2867238) 2025-04-11 09:11:05,181 - INFO - Epoch   2| Train Loss: 0.754| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2867238) 2025-04-11 09:11:05,188 - INFO - Epoch   2| Validation Loss: 1.243, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2867238) 2025-04-11 09:11:10,273 - INFO - Epoch   1| Train Loss: 0.767| Train Accuracy: 0.500 [repeated 449x across cluster]
(FLClient pid=2867499) 2025-04-11 09:11:09,954 - INFO - Epoch   2| Validation Loss: 1.241, Validation Accuracy: 0.172 [repeated 149x across cluster]
(FLClient pid=2867238) 2025-04-11 09:11:15,396 - INFO - Epoch   2| Train Loss: 0.576| Train Accuracy: 0.750 [repeated 451x across cluster]
(FLClient pid=2867499) 2025-04-11 09:11:15,061 - INFO - Epoch   2| Validation Loss: 0.871, Validation Accuracy: 0.500 [repeated 150x across cluster]
(FLClient pid=2867238) 2025-04-11 09:11:20,475 - INFO - Epoch   2| Train Loss: 0.418| Train Accuracy: 1.000 [repeated 450x across cluster]
(FLClient pid=2867238) 2025-04-11 09:11:20,484 - INFO - Epoch   2| Validation Loss: 0.997, Validation Accuracy: 0.318 [repeated 151x across cluster]

Training done
Round 1
Train Loss: 1.189, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.600
Train Loss: 1.070, Train Accuracy: 0.600
Train Loss: 1.228, Train Accuracy: 0.600
Train Loss: 1.173, Train Accuracy: 0.625
Train Loss: 1.203, Train Accuracy: 0.800
Train Loss: 1.287, Train Accuracy: 0.500
Train Loss: 1.173, Train Accuracy: 0.400
Train Loss: 1.532, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.600
Round 2
Train Loss: 1.228, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.500
Train Loss: 1.050, Train Accuracy: 0.400
Train Loss: 1.279, Train Accuracy: 0.600
Train Loss: 1.173, Train Accuracy: 0.625
Train Loss: 1.244, Train Accuracy: 0.800
Train Loss: 1.359, Train Accuracy: 1.000
Train Loss: 1.155, Train Accuracy: 0.400
Train Loss: 1.519, Train Accuracy: 0.750
Train Loss: 1.216, Train Accuracy: 0.400
Round 3
Train Loss: 1.192, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.500
Train Loss: 1.051, Train Accuracy: 0.400
Train Loss: 1.324, Train Accuracy: 0.600
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.282, Train Accuracy: 0.800
Train Loss: 1.384, Train Accuracy: 0.500
Train Loss: 1.131, Train Accuracy: 0.200
Train Loss: 1.625, Train Accuracy: 0.750
Train Loss: 1.207, Train Accuracy: 0.500
Round 4
Train Loss: 1.237, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 1.290, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.246, Train Accuracy: 0.800
Train Loss: 1.397, Train Accuracy: 0.250
Train Loss: 1.215, Train Accuracy: 0.400
Train Loss: 1.636, Train Accuracy: 0.750
Train Loss: 1.192, Train Accuracy: 0.400
Round 5
Train Loss: 1.245, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.700
Train Loss: 1.036, Train Accuracy: 0.600
Train Loss: 1.331, Train Accuracy: 0.600
Train Loss: 1.207, Train Accuracy: 0.625
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.353, Train Accuracy: 0.500
Train Loss: 1.170, Train Accuracy: 0.400
Train Loss: 1.637, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.400
Round 6
Train Loss: 1.261, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.366, Train Accuracy: 0.600
Train Loss: 1.215, Train Accuracy: 0.750
Train Loss: 1.265, Train Accuracy: 0.800
Train Loss: 1.386, Train Accuracy: 0.500
Train Loss: 1.164, Train Accuracy: 0.400
Train Loss: 1.689, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.500
Round 7
Train Loss: 1.303, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.500
Train Loss: 1.031, Train Accuracy: 0.600
Train Loss: 1.355, Train Accuracy: 0.600
Train Loss: 1.227, Train Accuracy: 0.625
Train Loss: 1.265, Train Accuracy: 0.800
Train Loss: 1.411, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.600
Train Loss: 1.772, Train Accuracy: 0.750
Train Loss: 1.247, Train Accuracy: 0.600
Round 8
Train Loss: 1.316, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.347, Train Accuracy: 0.800
Train Loss: 1.185, Train Accuracy: 0.625
Train Loss: 1.260, Train Accuracy: 0.800
Train Loss: 1.395, Train Accuracy: 0.500
Train Loss: 1.235, Train Accuracy: 0.600
Train Loss: 1.842, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.500
Round 9
Train Loss: 1.348, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.391, Train Accuracy: 0.600
Train Loss: 1.184, Train Accuracy: 0.625
Train Loss: 1.292, Train Accuracy: 0.800
Train Loss: 1.448, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.800
Train Loss: 1.786, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.400
Round 10
Train Loss: 1.314, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.500
Train Loss: 1.020, Train Accuracy: 0.400
Train Loss: 1.269, Train Accuracy: 0.600
Train Loss: 1.218, Train Accuracy: 0.625
Train Loss: 1.247, Train Accuracy: 0.800
Train Loss: 1.446, Train Accuracy: 0.750
Train Loss: 1.101, Train Accuracy: 0.400
Train Loss: 1.848, Train Accuracy: 0.750
Train Loss: 1.208, Train Accuracy: 0.400
Round 11
Train Loss: 1.323, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 1.338, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.267, Train Accuracy: 0.800
Train Loss: 1.423, Train Accuracy: 0.500
Train Loss: 1.220, Train Accuracy: 0.600
Train Loss: 1.863, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 0.600
Round 12
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.600
Train Loss: 1.012, Train Accuracy: 0.400
Train Loss: 1.293, Train Accuracy: 0.600
Train Loss: 1.240, Train Accuracy: 0.625
Train Loss: 1.321, Train Accuracy: 0.800
Train Loss: 1.415, Train Accuracy: 0.500
Train Loss: 1.140, Train Accuracy: 0.400
Train Loss: 1.810, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.500
Round 13
Train Loss: 1.335, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.305, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 0.625
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.426, Train Accuracy: 0.500
Train Loss: 1.235, Train Accuracy: 0.400
Train Loss: 1.798, Train Accuracy: 0.750
Train Loss: 1.238, Train Accuracy: 0.600
Round 14
Train Loss: 1.329, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.600
Train Loss: 1.003, Train Accuracy: 0.400
Train Loss: 1.339, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.750
Train Loss: 1.403, Train Accuracy: 0.800
Train Loss: 1.486, Train Accuracy: 1.000
Train Loss: 1.164, Train Accuracy: 0.400
Train Loss: 1.886, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.400
Round 15
Train Loss: 1.332, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.500
Train Loss: 1.012, Train Accuracy: 0.400
Train Loss: 1.395, Train Accuracy: 0.800
Train Loss: 1.229, Train Accuracy: 0.625
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.464, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.200
Train Loss: 1.797, Train Accuracy: 0.750
Train Loss: 1.131, Train Accuracy: 0.600
Round 16
Train Loss: 1.249, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 0.993, Train Accuracy: 0.600
Train Loss: 1.351, Train Accuracy: 0.600
Train Loss: 1.275, Train Accuracy: 0.625
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.400
Train Loss: 1.724, Train Accuracy: 0.750
Train Loss: 1.130, Train Accuracy: 0.300
Round 17
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.500
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.338, Train Accuracy: 0.600
Train Loss: 1.204, Train Accuracy: 0.750
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.483, Train Accuracy: 0.500
Train Loss: 1.069, Train Accuracy: 0.400
Train Loss: 2.027, Train Accuracy: 1.000
Train Loss: 1.213, Train Accuracy: 0.600
Round 18
Train Loss: 1.356, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.600
Train Loss: 0.987, Train Accuracy: 0.400
Train Loss: 1.363, Train Accuracy: 0.600
Train Loss: 1.203, Train Accuracy: 0.750
Train Loss: 1.421, Train Accuracy: 0.800
Train Loss: 1.429, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.400
Train Loss: 1.895, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.400
Round 19
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.600
Train Loss: 0.994, Train Accuracy: 0.400
Train Loss: 1.233, Train Accuracy: 0.600
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.292, Train Accuracy: 0.800
Train Loss: 1.557, Train Accuracy: 0.500
Train Loss: 1.206, Train Accuracy: 0.400
Train Loss: 1.885, Train Accuracy: 0.750
Train Loss: 1.098, Train Accuracy: 0.500
Round 20
Train Loss: 1.264, Train Accuracy: 0.750
Train Loss: 1.022, Train Accuracy: 0.500
Train Loss: 0.984, Train Accuracy: 0.400
Train Loss: 1.489, Train Accuracy: 1.000
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.529, Train Accuracy: 0.500
Train Loss: 1.109, Train Accuracy: 0.600
Train Loss: 1.887, Train Accuracy: 0.750
Train Loss: 1.155, Train Accuracy: 0.600
Round 21
Train Loss: 1.345, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.700
Train Loss: 0.985, Train Accuracy: 0.400
Train Loss: 1.354, Train Accuracy: 0.400
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.434, Train Accuracy: 1.000
Train Loss: 1.092, Train Accuracy: 0.600
Train Loss: 2.009, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.400
Round 22
Train Loss: 1.222, Train Accuracy: 0.750
Train Loss: 1.022, Train Accuracy: 0.600
Train Loss: 1.014, Train Accuracy: 0.600
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.211, Train Accuracy: 0.625
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.480, Train Accuracy: 0.750
Train Loss: 1.226, Train Accuracy: 0.600
Train Loss: 1.842, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.500
Round 23
Train Loss: 1.348, Train Accuracy: 0.750
Train Loss: 1.008, Train Accuracy: 0.600
Train Loss: 1.002, Train Accuracy: 0.400
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.240, Train Accuracy: 0.750
Train Loss: 1.386, Train Accuracy: 0.800
Train Loss: 1.595, Train Accuracy: 0.500
Train Loss: 1.130, Train Accuracy: 0.800
Train Loss: 2.037, Train Accuracy: 1.000
Train Loss: 1.108, Train Accuracy: 0.400
Round 24
Train Loss: 1.257, Train Accuracy: 0.750
Train Loss: 1.012, Train Accuracy: 0.700
Train Loss: 0.976, Train Accuracy: 0.600
Train Loss: 1.318, Train Accuracy: 0.600
Train Loss: 1.207, Train Accuracy: 0.750
Train Loss: 1.404, Train Accuracy: 0.800
Train Loss: 1.573, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.600
Train Loss: 1.880, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.600
Round 25
Train Loss: 1.199, Train Accuracy: 0.750
Train Loss: 1.017, Train Accuracy: 0.500
Train Loss: 0.958, Train Accuracy: 0.400
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.264, Train Accuracy: 0.625
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.469, Train Accuracy: 0.500
Train Loss: 1.091, Train Accuracy: 0.600
Train Loss: 1.694, Train Accuracy: 0.750
Train Loss: 1.205, Train Accuracy: 0.500
Round 26
Train Loss: 1.498, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.500
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.141, Train Accuracy: 0.375
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.527, Train Accuracy: 1.000
Train Loss: 1.073, Train Accuracy: 0.400
Train Loss: 2.011, Train Accuracy: 0.750
Train Loss: 1.099, Train Accuracy: 0.700
Round 27
Train Loss: 1.288, Train Accuracy: 0.750
Train Loss: 1.003, Train Accuracy: 0.600
Train Loss: 0.947, Train Accuracy: 0.400
Train Loss: 1.259, Train Accuracy: 0.800
Train Loss: 1.266, Train Accuracy: 0.625
Train Loss: 1.422, Train Accuracy: 0.800
Train Loss: 1.536, Train Accuracy: 0.750
Train Loss: 1.111, Train Accuracy: 0.400
Train Loss: 2.138, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.500
Round 28
Train Loss: 1.365, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.600
Train Loss: 0.964, Train Accuracy: 0.800
Train Loss: 1.381, Train Accuracy: 0.800
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.745, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.800
Train Loss: 2.169, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.700
Round 29
Train Loss: 1.300, Train Accuracy: 0.750
Train Loss: 1.004, Train Accuracy: 0.700
Train Loss: 0.970, Train Accuracy: 0.400
Train Loss: 1.225, Train Accuracy: 0.800
Train Loss: 1.148, Train Accuracy: 0.500
Train Loss: 1.333, Train Accuracy: 0.800
Train Loss: 1.655, Train Accuracy: 0.500
Train Loss: 1.054, Train Accuracy: 0.600
Train Loss: 2.117, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.800
Round 30
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.700
Train Loss: 0.970, Train Accuracy: 0.600
Train Loss: 1.299, Train Accuracy: 1.000
Train Loss: 1.168, Train Accuracy: 0.625
Train Loss: 1.342, Train Accuracy: 0.800
Train Loss: 1.679, Train Accuracy: 0.750
Train Loss: 1.062, Train Accuracy: 0.400
Train Loss: 1.819, Train Accuracy: 0.750
Train Loss: 1.155, Train Accuracy: 0.700
Round 31
Train Loss: 1.201, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 0.961, Train Accuracy: 0.600
Train Loss: 1.182, Train Accuracy: 0.600
Train Loss: 1.185, Train Accuracy: 0.625
Train Loss: 1.249, Train Accuracy: 0.800
Train Loss: 1.629, Train Accuracy: 0.500
Train Loss: 1.111, Train Accuracy: 0.600
Train Loss: 2.096, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.400
Round 32
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 0.983, Train Accuracy: 0.700
Train Loss: 0.945, Train Accuracy: 0.400
Train Loss: 1.307, Train Accuracy: 0.800
Train Loss: 1.100, Train Accuracy: 0.750
Train Loss: 1.239, Train Accuracy: 0.800
Train Loss: 1.391, Train Accuracy: 0.500
Train Loss: 1.058, Train Accuracy: 0.800
Train Loss: 1.955, Train Accuracy: 0.750
Train Loss: 1.110, Train Accuracy: 0.600
Round 33
Train Loss: 1.183, Train Accuracy: 0.750
Train Loss: 0.962, Train Accuracy: 0.700
Train Loss: 1.019, Train Accuracy: 0.600
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.221, Train Accuracy: 0.625
Train Loss: 1.318, Train Accuracy: 0.800
Train Loss: 1.730, Train Accuracy: 1.000
Train Loss: 1.035, Train Accuracy: 0.800
Train Loss: 2.208, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.400
Round 34
Train Loss: 1.192, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.500
Train Loss: 0.937, Train Accuracy: 0.600
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.161, Train Accuracy: 0.500
Train Loss: 1.335, Train Accuracy: 0.800
Train Loss: 1.465, Train Accuracy: 0.750
Train Loss: 1.040, Train Accuracy: 0.400
Train Loss: 1.976, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.600
Round 35
Train Loss: 1.280, Train Accuracy: 0.750
Train Loss: 0.980, Train Accuracy: 0.500
Train Loss: 0.960, Train Accuracy: 0.600
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.203, Train Accuracy: 0.625
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.549, Train Accuracy: 0.500
Train Loss: 1.082, Train Accuracy: 0.800
Train Loss: 1.894, Train Accuracy: 0.750
Train Loss: 1.247, Train Accuracy: 0.300
Round 36
Train Loss: 1.225, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.500
Train Loss: 0.920, Train Accuracy: 0.400
Train Loss: 1.247, Train Accuracy: 1.000
Train Loss: 1.188, Train Accuracy: 0.625
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 0.500
Train Loss: 1.067, Train Accuracy: 0.600
Train Loss: 1.863, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.500
Round 37
Train Loss: 1.335, Train Accuracy: 0.750
Train Loss: 0.964, Train Accuracy: 0.700
Train Loss: 0.919, Train Accuracy: 0.600
Train Loss: 1.194, Train Accuracy: 1.000
Train Loss: 1.160, Train Accuracy: 0.625
Train Loss: 1.287, Train Accuracy: 0.800
Train Loss: 1.459, Train Accuracy: 1.000
Train Loss: 1.140, Train Accuracy: 0.400
Train Loss: 1.924, Train Accuracy: 0.750
Train Loss: 1.261, Train Accuracy: 0.500
Round 38
Train Loss: 1.360, Train Accuracy: 0.750
Train Loss: 0.987, Train Accuracy: 0.600
Train Loss: 0.917, Train Accuracy: 0.600
Train Loss: 1.410, Train Accuracy: 1.000
Train Loss: 1.135, Train Accuracy: 0.625
Train Loss: 1.219, Train Accuracy: 0.800
Train Loss: 1.415, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.600
Train Loss: 2.050, Train Accuracy: 1.000
Train Loss: 1.409, Train Accuracy: 0.700
Round 39
Train Loss: 1.053, Train Accuracy: 0.750
Train Loss: 0.976, Train Accuracy: 0.700
Train Loss: 0.933, Train Accuracy: 1.000
Train Loss: 1.304, Train Accuracy: 1.000
Train Loss: 1.127, Train Accuracy: 0.750
Train Loss: 1.250, Train Accuracy: 0.800
Train Loss: 1.612, Train Accuracy: 0.500
Train Loss: 1.061, Train Accuracy: 0.400
Train Loss: 1.712, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.600
Round 40
Train Loss: 1.178, Train Accuracy: 0.750
Train Loss: 0.944, Train Accuracy: 0.600
Train Loss: 0.918, Train Accuracy: 0.600
Train Loss: 1.456, Train Accuracy: 0.800
Train Loss: 1.126, Train Accuracy: 0.250
Train Loss: 1.407, Train Accuracy: 0.800
Train Loss: 1.451, Train Accuracy: 0.750
Train Loss: 1.101, Train Accuracy: 0.800
Train Loss: 1.969, Train Accuracy: 0.750
Train Loss: 1.260, Train Accuracy: 0.700
Round 41
Train Loss: 1.108, Train Accuracy: 0.750
Train Loss: 0.952, Train Accuracy: 0.800
Train Loss: 0.961, Train Accuracy: 0.800
Train Loss: 1.212, Train Accuracy: 1.000
Train Loss: 1.141, Train Accuracy: 0.875
Train Loss: 1.404, Train Accuracy: 0.800
Train Loss: 1.533, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.400
Train Loss: 2.189, Train Accuracy: 1.000
Train Loss: 1.088, Train Accuracy: 0.600
Round 42
Train Loss: 1.244, Train Accuracy: 0.750
Train Loss: 1.018, Train Accuracy: 0.400
Train Loss: 0.897, Train Accuracy: 0.600
Train Loss: 1.391, Train Accuracy: 1.000
Train Loss: 1.138, Train Accuracy: 0.750
Train Loss: 1.273, Train Accuracy: 0.800
Train Loss: 1.746, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.800
Train Loss: 2.083, Train Accuracy: 1.000
Train Loss: 1.143, Train Accuracy: 0.700
Round 43
Train Loss: 1.210, Train Accuracy: 0.750
Train Loss: 0.927, Train Accuracy: 0.500
Train Loss: 0.913, Train Accuracy: 0.600
Train Loss: 1.338, Train Accuracy: 1.000
Train Loss: 1.112, Train Accuracy: 0.625
Train Loss: 1.252, Train Accuracy: 0.800
Train Loss: 1.652, Train Accuracy: 0.500
Train Loss: 0.958, Train Accuracy: 0.600
Train Loss: 2.210, Train Accuracy: 1.000
Train Loss: 1.380, Train Accuracy: 0.400
Round 44
Train Loss: 1.243, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 0.865, Train Accuracy: 0.600
Train Loss: 1.167, Train Accuracy: 1.000
Train Loss: 1.130, Train Accuracy: 0.250
Train Loss: 1.347, Train Accuracy: 0.800
Train Loss: 1.452, Train Accuracy: 1.000
Train Loss: 1.020, Train Accuracy: 0.800
Train Loss: 2.167, Train Accuracy: 1.000
Train Loss: 1.038, Train Accuracy: 0.800
Round 45
Train Loss: 1.270, Train Accuracy: 0.750
Train Loss: 0.933, Train Accuracy: 0.800
Train Loss: 0.875, Train Accuracy: 0.600
Train Loss: 1.331, Train Accuracy: 0.600
Train Loss: 1.159, Train Accuracy: 0.750
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.593, Train Accuracy: 0.500
Train Loss: 1.065, Train Accuracy: 0.400
Train Loss: 1.828, Train Accuracy: 0.750
Train Loss: 1.370, Train Accuracy: 0.500
Round 46
Train Loss: 1.162, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.400
Train Loss: 0.864, Train Accuracy: 0.600
Train Loss: 1.128, Train Accuracy: 1.000
Train Loss: 1.181, Train Accuracy: 0.750
Train Loss: 1.272, Train Accuracy: 0.800
Train Loss: 1.430, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.600
Train Loss: 1.645, Train Accuracy: 0.750
Train Loss: 1.097, Train Accuracy: 0.700
Round 47
Train Loss: 1.266, Train Accuracy: 0.750
Train Loss: 0.921, Train Accuracy: 0.700
Train Loss: 0.903, Train Accuracy: 0.400
Train Loss: 1.509, Train Accuracy: 1.000
Train Loss: 1.193, Train Accuracy: 0.875
Train Loss: 1.318, Train Accuracy: 0.800
Train Loss: 1.812, Train Accuracy: 0.500
Train Loss: 0.962, Train Accuracy: 0.600
Train Loss: 2.022, Train Accuracy: 0.750
Train Loss: 1.298, Train Accuracy: 0.500
Round 48
Train Loss: 1.080, Train Accuracy: 0.750
Train Loss: 0.980, Train Accuracy: 0.700
Train Loss: 0.912, Train Accuracy: 0.600
Train Loss: 1.203, Train Accuracy: 1.000
Train Loss: 1.109, Train Accuracy: 0.750
Train Loss: 1.367, Train Accuracy: 0.800
Train Loss: 1.288, Train Accuracy: 0.500

(FLClient pid=2868254) 2025-04-11 09:11:32,396 - INFO - Epoch   0| Train Loss: 1.108| Train Accuracy: 0.000 [repeated 358x across cluster]
(FLClient pid=2867499) 2025-04-11 09:11:24,219 - INFO - Epoch   2| Validation Loss: 1.233, Validation Accuracy: 0.297 [repeated 119x across cluster]
(FLClient pid=2868254) 2025-04-11 09:11:37,623 - INFO - Epoch   2| Train Loss: 0.696| Train Accuracy: 0.750 [repeated 422x across cluster]
(FLClient pid=2868254) 2025-04-11 09:11:37,630 - INFO - Epoch   2| Validation Loss: 1.215, Validation Accuracy: 0.295 [repeated 141x across cluster]
(FLClient pid=2868254) 2025-04-11 09:11:42,716 - INFO - Epoch   2| Train Loss: 0.693| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2868254) 2025-04-11 09:11:42,724 - INFO - Epoch   2| Validation Loss: 1.189, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2868254) 2025-04-11 09:11:47,803 - INFO - Epoch   2| Train Loss: 0.484| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2868254) 2025-04-11 09:11:47,811 - INFO - Epoch   2| Validation Loss: 1.322, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2868254) 2025-04-11 09:11:52,870 - INFO - Epoch   1| Train Loss: 0.515| Train Accuracy: 0.750 [repeated 449x across cluster]
(FLClient pid=2868389) 2025-04-11 09:11:52,541 - INFO - Epoch   2| Validation Loss: 2.116, Validation Accuracy: 0.233 [repeated 149x across cluster]
(FLClient pid=2868254) 2025-04-11 09:11:57,951 - INFO - Epoch   0| Train Loss: 0.831| Train Accuracy: 0.750 [repeated 449x across cluster]
(FLClient pid=2868389) 2025-04-11 09:11:57,640 - INFO - Epoch   2| Validation Loss: 1.980, Validation Accuracy: 0.233 [repeated 150x across cluster]
(FLClient pid=2868254) 2025-04-11 09:12:03,124 - INFO - Epoch   0| Train Loss: 0.812| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2868255) 2025-04-11 09:12:02,813 - INFO - Epoch   2| Validation Loss: 0.831, Validation Accuracy: 0.578 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.170, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.066, Train Accuracy: 0.400
Train Loss: 1.225, Train Accuracy: 0.600
Train Loss: 1.179, Train Accuracy: 0.625
Train Loss: 1.190, Train Accuracy: 0.800
Train Loss: 1.302, Train Accuracy: 0.500
Train Loss: 1.136, Train Accuracy: 0.400
Train Loss: 1.497, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.400
Round 2
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 1.083, Train Accuracy: 0.500
Train Loss: 1.067, Train Accuracy: 0.400
Train Loss: 1.237, Train Accuracy: 0.600
Train Loss: 1.189, Train Accuracy: 0.625
Train Loss: 1.189, Train Accuracy: 0.800
Train Loss: 1.326, Train Accuracy: 0.500
Train Loss: 1.161, Train Accuracy: 0.400
Train Loss: 1.564, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.400
Round 3
Train Loss: 1.200, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.055, Train Accuracy: 0.400
Train Loss: 1.283, Train Accuracy: 0.600
Train Loss: 1.200, Train Accuracy: 0.625
Train Loss: 1.207, Train Accuracy: 0.800
Train Loss: 1.338, Train Accuracy: 0.500
Train Loss: 1.165, Train Accuracy: 0.400
Train Loss: 1.606, Train Accuracy: 0.750
Train Loss: 1.192, Train Accuracy: 0.400
Round 4
Train Loss: 1.215, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.600
Train Loss: 1.049, Train Accuracy: 0.400
Train Loss: 1.294, Train Accuracy: 0.600
Train Loss: 1.211, Train Accuracy: 0.625
Train Loss: 1.219, Train Accuracy: 0.800
Train Loss: 1.338, Train Accuracy: 0.500
Train Loss: 1.156, Train Accuracy: 0.800
Train Loss: 1.652, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.400
Round 5
Train Loss: 1.237, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.600
Train Loss: 1.043, Train Accuracy: 0.400
Train Loss: 1.369, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.236, Train Accuracy: 0.800
Train Loss: 1.378, Train Accuracy: 0.500
Train Loss: 1.175, Train Accuracy: 0.400
Train Loss: 1.712, Train Accuracy: 0.750
Train Loss: 1.211, Train Accuracy: 0.500
Round 6
Train Loss: 1.224, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 1.304, Train Accuracy: 0.600
Train Loss: 1.215, Train Accuracy: 0.625
Train Loss: 1.242, Train Accuracy: 0.800
Train Loss: 1.373, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.400
Train Loss: 1.672, Train Accuracy: 0.750
Train Loss: 1.209, Train Accuracy: 0.500
Round 7
Train Loss: 1.238, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.500
Train Loss: 1.045, Train Accuracy: 0.600
Train Loss: 1.374, Train Accuracy: 0.600
Train Loss: 1.212, Train Accuracy: 0.625
Train Loss: 1.236, Train Accuracy: 0.800
Train Loss: 1.386, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.600
Train Loss: 1.757, Train Accuracy: 0.750
Train Loss: 1.193, Train Accuracy: 0.400
Round 8
Train Loss: 1.235, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.400
Train Loss: 1.038, Train Accuracy: 0.000
Train Loss: 1.350, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.238, Train Accuracy: 0.800
Train Loss: 1.429, Train Accuracy: 0.750
Train Loss: 1.138, Train Accuracy: 0.200
Train Loss: 1.848, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.500
Round 9
Train Loss: 1.294, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 1.354, Train Accuracy: 0.600
Train Loss: 1.240, Train Accuracy: 0.625
Train Loss: 1.273, Train Accuracy: 0.800
Train Loss: 1.442, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.600
Train Loss: 1.807, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.400
Round 10
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.600
Train Loss: 1.026, Train Accuracy: 0.400
Train Loss: 1.363, Train Accuracy: 0.600
Train Loss: 1.210, Train Accuracy: 0.625
Train Loss: 1.242, Train Accuracy: 0.800
Train Loss: 1.420, Train Accuracy: 0.500
Train Loss: 1.154, Train Accuracy: 0.400
Train Loss: 1.857, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.500
Round 11
Train Loss: 1.270, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.600
Train Loss: 1.030, Train Accuracy: 0.600
Train Loss: 1.421, Train Accuracy: 0.600
Train Loss: 1.257, Train Accuracy: 0.625
Train Loss: 1.270, Train Accuracy: 0.800
Train Loss: 1.434, Train Accuracy: 0.500
Train Loss: 1.103, Train Accuracy: 0.200
Train Loss: 1.957, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.400
Round 12
Train Loss: 1.253, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.406, Train Accuracy: 0.600
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.251, Train Accuracy: 0.800
Train Loss: 1.417, Train Accuracy: 0.500
Train Loss: 1.192, Train Accuracy: 0.600
Train Loss: 1.922, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.600
Round 13
Train Loss: 1.383, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.500
Train Loss: 1.022, Train Accuracy: 0.200
Train Loss: 1.397, Train Accuracy: 0.600
Train Loss: 1.223, Train Accuracy: 0.625
Train Loss: 1.249, Train Accuracy: 0.800
Train Loss: 1.405, Train Accuracy: 0.500
Train Loss: 1.141, Train Accuracy: 0.400
Train Loss: 1.843, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.400
Round 14
Train Loss: 1.385, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.600
Train Loss: 1.021, Train Accuracy: 0.400
Train Loss: 1.358, Train Accuracy: 0.800
Train Loss: 1.212, Train Accuracy: 0.625
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.462, Train Accuracy: 0.750
Train Loss: 1.175, Train Accuracy: 0.800
Train Loss: 1.868, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.400
Round 15
Train Loss: 1.215, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.600
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.310, Train Accuracy: 0.600
Train Loss: 1.242, Train Accuracy: 0.625
Train Loss: 1.364, Train Accuracy: 0.800
Train Loss: 1.419, Train Accuracy: 0.250
Train Loss: 1.156, Train Accuracy: 0.400
Train Loss: 1.941, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.600
Round 16
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 1.019, Train Accuracy: 0.400
Train Loss: 1.323, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.302, Train Accuracy: 0.800
Train Loss: 1.402, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.400
Train Loss: 1.771, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.600
Round 17
Train Loss: 1.245, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.700
Train Loss: 1.020, Train Accuracy: 0.400
Train Loss: 1.407, Train Accuracy: 0.800
Train Loss: 1.212, Train Accuracy: 0.750
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.422, Train Accuracy: 0.500
Train Loss: 1.174, Train Accuracy: 0.800
Train Loss: 1.793, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.500
Round 18
Train Loss: 1.323, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.600
Train Loss: 1.005, Train Accuracy: 0.800
Train Loss: 1.392, Train Accuracy: 0.600
Train Loss: 1.212, Train Accuracy: 0.750
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.420, Train Accuracy: 0.500
Train Loss: 1.141, Train Accuracy: 0.400
Train Loss: 1.880, Train Accuracy: 0.750
Train Loss: 1.199, Train Accuracy: 0.600
Round 19
Train Loss: 1.245, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.600
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.426, Train Accuracy: 0.600
Train Loss: 1.183, Train Accuracy: 0.625
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.450, Train Accuracy: 0.500
Train Loss: 1.159, Train Accuracy: 0.600
Train Loss: 1.852, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.600
Round 20
Train Loss: 1.310, Train Accuracy: 0.750
Train Loss: 1.033, Train Accuracy: 0.300
Train Loss: 0.998, Train Accuracy: 0.400
Train Loss: 1.371, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.750
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.472, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.600
Train Loss: 1.919, Train Accuracy: 0.750
Train Loss: 1.203, Train Accuracy: 0.700
Round 21
Train Loss: 1.399, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.600
Train Loss: 1.004, Train Accuracy: 0.600
Train Loss: 1.466, Train Accuracy: 1.000
Train Loss: 1.249, Train Accuracy: 0.750
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 0.600
Train Loss: 1.926, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.600
Round 22
Train Loss: 1.302, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.600
Train Loss: 1.001, Train Accuracy: 0.400
Train Loss: 1.522, Train Accuracy: 0.800
Train Loss: 1.188, Train Accuracy: 0.750
Train Loss: 1.417, Train Accuracy: 0.800
Train Loss: 1.503, Train Accuracy: 1.000
Train Loss: 1.132, Train Accuracy: 0.400
Train Loss: 1.867, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.500
Round 23
Train Loss: 1.268, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.600
Train Loss: 0.994, Train Accuracy: 0.400
Train Loss: 1.351, Train Accuracy: 0.600
Train Loss: 1.242, Train Accuracy: 0.750
Train Loss: 1.305, Train Accuracy: 0.800
Train Loss: 1.456, Train Accuracy: 0.750
Train Loss: 1.139, Train Accuracy: 0.600
Train Loss: 1.933, Train Accuracy: 0.750
Train Loss: 1.148, Train Accuracy: 0.500
Round 24
Train Loss: 1.410, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.500
Train Loss: 0.989, Train Accuracy: 0.400
Train Loss: 1.431, Train Accuracy: 0.800
Train Loss: 1.212, Train Accuracy: 0.750
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.502, Train Accuracy: 1.000
Train Loss: 1.177, Train Accuracy: 0.600
Train Loss: 2.103, Train Accuracy: 0.750
Train Loss: 1.190, Train Accuracy: 0.700
Round 25
Train Loss: 1.263, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.500
Train Loss: 1.013, Train Accuracy: 0.600
Train Loss: 1.358, Train Accuracy: 0.600
Train Loss: 1.206, Train Accuracy: 0.875
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.391, Train Accuracy: 0.750
Train Loss: 1.112, Train Accuracy: 0.600
Train Loss: 1.944, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.600
Round 26
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.700
Train Loss: 0.986, Train Accuracy: 0.400
Train Loss: 1.492, Train Accuracy: 0.600
Train Loss: 1.202, Train Accuracy: 0.625
Train Loss: 1.388, Train Accuracy: 0.800
Train Loss: 1.460, Train Accuracy: 1.000
Train Loss: 1.176, Train Accuracy: 0.600
Train Loss: 2.056, Train Accuracy: 0.750
Train Loss: 1.114, Train Accuracy: 0.700
Round 27
Train Loss: 1.240, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.600
Train Loss: 0.992, Train Accuracy: 0.400
Train Loss: 1.508, Train Accuracy: 1.000
Train Loss: 1.188, Train Accuracy: 0.750
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.523, Train Accuracy: 0.500
Train Loss: 1.238, Train Accuracy: 0.600
Train Loss: 1.988, Train Accuracy: 0.750
Train Loss: 1.120, Train Accuracy: 0.500
Round 28
Train Loss: 1.283, Train Accuracy: 0.750
Train Loss: 1.004, Train Accuracy: 0.600
Train Loss: 0.970, Train Accuracy: 0.400
Train Loss: 1.372, Train Accuracy: 1.000
Train Loss: 1.203, Train Accuracy: 0.750
Train Loss: 1.312, Train Accuracy: 0.800
Train Loss: 1.466, Train Accuracy: 0.500
Train Loss: 1.210, Train Accuracy: 0.600
Train Loss: 2.028, Train Accuracy: 1.000
Train Loss: 1.174, Train Accuracy: 0.800
Round 29
Train Loss: 1.292, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 0.998, Train Accuracy: 0.600
Train Loss: 1.484, Train Accuracy: 1.000
Train Loss: 1.178, Train Accuracy: 0.750
Train Loss: 1.295, Train Accuracy: 0.800
Train Loss: 1.614, Train Accuracy: 1.000
Train Loss: 1.138, Train Accuracy: 0.600
Train Loss: 2.163, Train Accuracy: 1.000
Train Loss: 1.141, Train Accuracy: 0.500
Round 30
Train Loss: 1.189, Train Accuracy: 0.750
Train Loss: 1.012, Train Accuracy: 0.700
Train Loss: 0.968, Train Accuracy: 0.400
Train Loss: 1.346, Train Accuracy: 0.800
Train Loss: 1.170, Train Accuracy: 0.750
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.564, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.600
Train Loss: 1.962, Train Accuracy: 0.750
Train Loss: 1.110, Train Accuracy: 0.500
Round 31
Train Loss: 1.318, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.700
Train Loss: 0.957, Train Accuracy: 0.600
Train Loss: 1.424, Train Accuracy: 0.800
Train Loss: 1.127, Train Accuracy: 0.875
Train Loss: 1.267, Train Accuracy: 0.800
Train Loss: 1.435, Train Accuracy: 0.750
Train Loss: 1.235, Train Accuracy: 0.600
Train Loss: 1.875, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.600
Round 32
Train Loss: 1.252, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.700
Train Loss: 0.962, Train Accuracy: 0.400
Train Loss: 1.406, Train Accuracy: 0.800
Train Loss: 1.185, Train Accuracy: 0.750
Train Loss: 1.306, Train Accuracy: 0.800
Train Loss: 1.449, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.800
Train Loss: 2.130, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.800
Round 33
Train Loss: 1.187, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.700
Train Loss: 0.954, Train Accuracy: 0.600
Train Loss: 1.429, Train Accuracy: 1.000
Train Loss: 1.215, Train Accuracy: 0.750
Train Loss: 1.437, Train Accuracy: 0.800
Train Loss: 1.525, Train Accuracy: 1.000
Train Loss: 1.094, Train Accuracy: 0.800
Train Loss: 2.161, Train Accuracy: 0.750
Train Loss: 1.118, Train Accuracy: 0.600
Round 34
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 0.993, Train Accuracy: 0.600
Train Loss: 0.967, Train Accuracy: 0.400
Train Loss: 1.318, Train Accuracy: 0.800
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.464, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.800
Train Loss: 2.010, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.500
Round 35
Train Loss: 1.290, Train Accuracy: 0.750
Train Loss: 0.984, Train Accuracy: 0.500
Train Loss: 0.973, Train Accuracy: 0.600
Train Loss: 1.496, Train Accuracy: 1.000
Train Loss: 1.113, Train Accuracy: 0.875
Train Loss: 1.282, Train Accuracy: 0.800
Train Loss: 1.642, Train Accuracy: 0.500
Train Loss: 1.096, Train Accuracy: 0.800
Train Loss: 1.886, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.800
Round 36
Train Loss: 1.169, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.500
Train Loss: 0.953, Train Accuracy: 0.600
Train Loss: 1.376, Train Accuracy: 0.800
Train Loss: 1.160, Train Accuracy: 0.875
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.387, Train Accuracy: 1.000
Train Loss: 1.176, Train Accuracy: 0.400
Train Loss: 2.014, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.800
Round 37
Train Loss: 1.345, Train Accuracy: 0.500
Train Loss: 0.982, Train Accuracy: 0.700
Train Loss: 0.928, Train Accuracy: 0.600
Train Loss: 1.442, Train Accuracy: 1.000
Train Loss: 1.180, Train Accuracy: 0.875
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.523, Train Accuracy: 0.750
Train Loss: 1.215, Train Accuracy: 0.800
Train Loss: 1.767, Train Accuracy: 0.750
Train Loss: 1.240, Train Accuracy: 0.600
Round 38
Train Loss: 1.394, Train Accuracy: 0.750
Train Loss: 0.964, Train Accuracy: 0.600
Train Loss: 0.945, Train Accuracy: 0.600
Train Loss: 1.262, Train Accuracy: 1.000
Train Loss: 1.093, Train Accuracy: 0.875
Train Loss: 1.377, Train Accuracy: 0.800
Train Loss: 1.622, Train Accuracy: 0.750
Train Loss: 1.105, Train Accuracy: 0.600
Train Loss: 1.837, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.800
Round 39
Train Loss: 1.196, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.800
Train Loss: 0.954, Train Accuracy: 0.600
Train Loss: 1.360, Train Accuracy: 0.800
Train Loss: 1.170, Train Accuracy: 0.875
Train Loss: 1.397, Train Accuracy: 1.000
Train Loss: 1.446, Train Accuracy: 0.750
Train Loss: 1.107, Train Accuracy: 0.600
Train Loss: 1.798, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.700
Round 40
Train Loss: 1.414, Train Accuracy: 0.750
Train Loss: 0.976, Train Accuracy: 0.600
Train Loss: 0.928, Train Accuracy: 0.600
Train Loss: 1.562, Train Accuracy: 0.800
Train Loss: 1.184, Train Accuracy: 0.750
Train Loss: 1.324, Train Accuracy: 0.800
Train Loss: 1.503, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.800
Train Loss: 1.797, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.500
Round 41
Train Loss: 1.137, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.500
Train Loss: 0.948, Train Accuracy: 0.600
Train Loss: 1.270, Train Accuracy: 0.800
Train Loss: 1.175, Train Accuracy: 0.750
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.459, Train Accuracy: 1.000
Train Loss: 0.955, Train Accuracy: 0.800
Train Loss: 1.988, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.500
Round 42
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 0.957, Train Accuracy: 0.800
Train Loss: 0.911, Train Accuracy: 0.600
Train Loss: 1.200, Train Accuracy: 0.800
Train Loss: 1.187, Train Accuracy: 0.625
Train Loss: 1.249, Train Accuracy: 0.800
Train Loss: 1.717, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.400
Train Loss: 2.372, Train Accuracy: 1.000
Train Loss: 1.092, Train Accuracy: 0.500
Round 43
Train Loss: 1.271, Train Accuracy: 0.750
Train Loss: 0.989, Train Accuracy: 0.500
Train Loss: 0.942, Train Accuracy: 0.600
Train Loss: 1.469, Train Accuracy: 0.800
Train Loss: 1.198, Train Accuracy: 0.500
Train Loss: 1.364, Train Accuracy: 0.800
Train Loss: 1.428, Train Accuracy: 1.000
Train Loss: 1.268, Train Accuracy: 0.600
Train Loss: 2.138, Train Accuracy: 1.000
Train Loss: 0.987, Train Accuracy: 0.400
Round 44
Train Loss: 1.210, Train Accuracy: 0.750
Train Loss: 0.948, Train Accuracy: 0.600
Train Loss: 0.920, Train Accuracy: 0.600
Train Loss: 1.273, Train Accuracy: 1.000
Train Loss: 1.083, Train Accuracy: 0.625
Train Loss: 1.402, Train Accuracy: 1.000
Train Loss: 1.431, Train Accuracy: 1.000
Train Loss: 1.141, Train Accuracy: 0.600
Train Loss: 1.834, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.900
Round 45
Train Loss: 1.322, Train Accuracy: 0.750
Train Loss: 0.935, Train Accuracy: 0.600
Train Loss: 0.887, Train Accuracy: 0.600
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.123, Train Accuracy: 0.500
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.450, Train Accuracy: 0.750
Train Loss: 1.013, Train Accuracy: 1.000
Train Loss: 2.192, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Round 46
Train Loss: 1.327, Train Accuracy: 0.750
Train Loss: 0.952, Train Accuracy: 0.700
Train Loss: 0.890, Train Accuracy: 0.600
Train Loss: 1.597, Train Accuracy: 0.800
Train Loss: 1.144, Train Accuracy: 0.875
Train Loss: 1.358, Train Accuracy: 0.800
Train Loss: 1.450, Train Accuracy: 0.750
Train Loss: 1.040, Train Accuracy: 0.400
Train Loss: 1.940, Train Accuracy: 0.750
Train Loss: 1.226, Train Accuracy: 0.700
Round 47
Train Loss: 1.214, Train Accuracy: 0.750
Train Loss: 0.967, Train Accuracy: 0.700
Train Loss: 0.964, Train Accuracy: 0.400
Train Loss: 1.315, Train Accuracy: 1.000
Train Loss: 1.103, Train Accuracy: 0.625
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.597, Train Accuracy: 0.500
Train Loss: 1.091, Train Accuracy: 0.600
Train Loss: 2.096, Train Accuracy: 0.750
Train Loss: 1.111, Train Accuracy: 0.800
Round 48
Train Loss: 1.298, Train Accuracy: 0.750
Train Loss: 0.943, Train Accuracy: 0.600
Train Loss: 0.916, Train Accuracy: 0.600
Train Loss: 1.475, Train Accuracy: 0.800
Train Loss: 1.126, Train Accuracy: 0.500
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.580, Train Accuracy: 0.750

(FLClient pid=2869258) 2025-04-11 09:12:14,887 - INFO - Epoch   2| Train Loss: 1.037| Train Accuracy: 0.500 [repeated 332x across cluster]
(FLClient pid=2869258) 2025-04-11 09:12:14,897 - INFO - Epoch   2| Validation Loss: 1.083, Validation Accuracy: 0.467 [repeated 111x across cluster]
(FLClient pid=2869257) 2025-04-11 09:12:19,974 - INFO - Epoch   2| Train Loss: 0.661| Train Accuracy: 0.750 [repeated 420x across cluster]
(FLClient pid=2869257) 2025-04-11 09:12:19,982 - INFO - Epoch   2| Validation Loss: 1.353, Validation Accuracy: 0.295 [repeated 140x across cluster]
(FLClient pid=2869257) 2025-04-11 09:12:25,094 - INFO - Epoch   2| Train Loss: 0.537| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2869472) 2025-04-11 09:12:24,755 - INFO - Epoch   2| Validation Loss: 1.083, Validation Accuracy: 0.484 [repeated 149x across cluster]
(FLClient pid=2869257) 2025-04-11 09:12:30,168 - INFO - Epoch   0| Train Loss: 1.005| Train Accuracy: 0.500 [repeated 448x across cluster]
(FLClient pid=2869472) 2025-04-11 09:12:29,859 - INFO - Epoch   2| Validation Loss: 1.197, Validation Accuracy: 0.172 [repeated 150x across cluster]
(FLClient pid=2869257) 2025-04-11 09:12:35,301 - INFO - Epoch   2| Train Loss: 0.504| Train Accuracy: 0.750 [repeated 452x across cluster]
(FLClient pid=2869257) 2025-04-11 09:12:35,308 - INFO - Epoch   2| Validation Loss: 1.257, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2869257) 2025-04-11 09:12:40,412 - INFO - Epoch   2| Train Loss: 0.470| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2869257) 2025-04-11 09:12:40,419 - INFO - Epoch   2| Validation Loss: 0.997, Validation Accuracy: 0.364 [repeated 150x across cluster]
(FLClient pid=2869257) 2025-04-11 09:12:45,519 - INFO - Epoch   2| Train Loss: 0.434| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2869257) 2025-04-11 09:12:45,527 - INFO - Epoch   2| Validation Loss: 1.486, Validation Accuracy: 0.295 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.207, Train Accuracy: 0.750
Train Loss: 1.083, Train Accuracy: 0.500
Train Loss: 1.059, Train Accuracy: 0.400
Train Loss: 1.305, Train Accuracy: 0.600
Train Loss: 1.197, Train Accuracy: 0.625
Train Loss: 1.273, Train Accuracy: 0.800
Train Loss: 1.374, Train Accuracy: 0.500
Train Loss: 1.149, Train Accuracy: 0.200
Train Loss: 1.565, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.400
Round 2
Train Loss: 1.324, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.053, Train Accuracy: 0.200
Train Loss: 1.319, Train Accuracy: 0.600
Train Loss: 1.211, Train Accuracy: 0.625
Train Loss: 1.238, Train Accuracy: 0.800
Train Loss: 1.459, Train Accuracy: 0.250
Train Loss: 1.156, Train Accuracy: 0.400
Train Loss: 1.587, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.400
Round 3
Train Loss: 1.249, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.500
Train Loss: 1.048, Train Accuracy: 0.400
Train Loss: 1.391, Train Accuracy: 0.600
Train Loss: 1.222, Train Accuracy: 0.625
Train Loss: 1.301, Train Accuracy: 0.800
Train Loss: 1.468, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.200
Train Loss: 1.800, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.300
Round 4
Train Loss: 1.295, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.040, Train Accuracy: 0.400
Train Loss: 1.394, Train Accuracy: 0.600
Train Loss: 1.204, Train Accuracy: 0.625
Train Loss: 1.282, Train Accuracy: 0.800
Train Loss: 1.448, Train Accuracy: 0.250
Train Loss: 1.150, Train Accuracy: 0.400
Train Loss: 1.673, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.300
Round 5
Train Loss: 1.385, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.500
Train Loss: 1.042, Train Accuracy: 0.400
Train Loss: 1.366, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.301, Train Accuracy: 0.800
Train Loss: 1.501, Train Accuracy: 0.500
Train Loss: 1.148, Train Accuracy: 0.800
Train Loss: 1.772, Train Accuracy: 0.750
Train Loss: 1.210, Train Accuracy: 0.700
Round 6
Train Loss: 1.289, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.500
Train Loss: 1.042, Train Accuracy: 0.200
Train Loss: 1.402, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.322, Train Accuracy: 0.800
Train Loss: 1.501, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.400
Train Loss: 1.758, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.400
Round 7
Train Loss: 1.436, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 1.396, Train Accuracy: 0.600
Train Loss: 1.270, Train Accuracy: 0.625
Train Loss: 1.366, Train Accuracy: 0.800
Train Loss: 1.563, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.600
Train Loss: 1.729, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.300
Round 8
Train Loss: 1.255, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.027, Train Accuracy: 0.200
Train Loss: 1.450, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.377, Train Accuracy: 0.800
Train Loss: 1.544, Train Accuracy: 0.750
Train Loss: 1.239, Train Accuracy: 0.400
Train Loss: 1.811, Train Accuracy: 0.750
Train Loss: 1.215, Train Accuracy: 0.700
Round 9
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.023, Train Accuracy: 0.600
Train Loss: 1.432, Train Accuracy: 0.600
Train Loss: 1.204, Train Accuracy: 0.625
Train Loss: 1.261, Train Accuracy: 0.800
Train Loss: 1.571, Train Accuracy: 0.500
Train Loss: 1.173, Train Accuracy: 0.600
Train Loss: 1.912, Train Accuracy: 0.750
Train Loss: 1.148, Train Accuracy: 0.300
Round 10
Train Loss: 1.376, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 1.483, Train Accuracy: 0.600
Train Loss: 1.257, Train Accuracy: 0.625
Train Loss: 1.381, Train Accuracy: 0.800
Train Loss: 1.542, Train Accuracy: 0.500
Train Loss: 1.178, Train Accuracy: 0.400
Train Loss: 1.965, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.600
Round 11
Train Loss: 1.339, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.500
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 1.466, Train Accuracy: 0.600
Train Loss: 1.218, Train Accuracy: 0.625
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.520, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.800
Train Loss: 1.937, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.500
Round 12
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.500
Train Loss: 1.018, Train Accuracy: 0.400
Train Loss: 1.518, Train Accuracy: 0.800
Train Loss: 1.248, Train Accuracy: 0.625
Train Loss: 1.347, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 0.500
Train Loss: 1.170, Train Accuracy: 0.400
Train Loss: 1.966, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.500
Round 13
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.476, Train Accuracy: 0.600
Train Loss: 1.211, Train Accuracy: 0.625
Train Loss: 1.409, Train Accuracy: 0.800
Train Loss: 1.563, Train Accuracy: 0.250
Train Loss: 1.162, Train Accuracy: 0.400
Train Loss: 1.882, Train Accuracy: 0.750
Train Loss: 1.138, Train Accuracy: 0.400
Round 14
Train Loss: 1.396, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.600
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 1.489, Train Accuracy: 0.600
Train Loss: 1.258, Train Accuracy: 0.625
Train Loss: 1.384, Train Accuracy: 0.800
Train Loss: 1.604, Train Accuracy: 0.500
Train Loss: 1.136, Train Accuracy: 0.400
Train Loss: 1.930, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.800
Round 15
Train Loss: 1.353, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.700
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.495, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.625
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.574, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.600
Train Loss: 2.031, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.300
Round 16
Train Loss: 1.356, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.500
Train Loss: 1.024, Train Accuracy: 0.400
Train Loss: 1.513, Train Accuracy: 0.600
Train Loss: 1.196, Train Accuracy: 0.750
Train Loss: 1.380, Train Accuracy: 0.800
Train Loss: 1.513, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.600
Train Loss: 2.018, Train Accuracy: 1.000
Train Loss: 1.118, Train Accuracy: 0.300
Round 17
Train Loss: 1.228, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.500
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 1.550, Train Accuracy: 0.400
Train Loss: 1.221, Train Accuracy: 0.625
Train Loss: 1.356, Train Accuracy: 0.800
Train Loss: 1.560, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.600
Train Loss: 2.076, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.500
Round 18
Train Loss: 1.407, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.500
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.542, Train Accuracy: 0.600
Train Loss: 1.233, Train Accuracy: 0.625
Train Loss: 1.293, Train Accuracy: 0.800
Train Loss: 1.556, Train Accuracy: 0.500
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.777, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.500
Round 19
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 1.033, Train Accuracy: 0.500
Train Loss: 1.017, Train Accuracy: 0.400
Train Loss: 1.451, Train Accuracy: 0.600
Train Loss: 1.263, Train Accuracy: 0.625
Train Loss: 1.384, Train Accuracy: 0.800
Train Loss: 1.572, Train Accuracy: 0.750
Train Loss: 1.130, Train Accuracy: 0.800
Train Loss: 1.920, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.500
Round 20
Train Loss: 1.313, Train Accuracy: 0.750
Train Loss: 1.046, Train Accuracy: 0.500
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.379, Train Accuracy: 0.600
Train Loss: 1.174, Train Accuracy: 0.625
Train Loss: 1.374, Train Accuracy: 0.800
Train Loss: 1.615, Train Accuracy: 0.500
Train Loss: 1.167, Train Accuracy: 0.600
Train Loss: 2.017, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.600
Round 21
Train Loss: 1.268, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.600
Train Loss: 0.993, Train Accuracy: 0.600
Train Loss: 1.507, Train Accuracy: 0.600
Train Loss: 1.215, Train Accuracy: 0.625
Train Loss: 1.430, Train Accuracy: 0.800
Train Loss: 1.533, Train Accuracy: 0.250
Train Loss: 1.243, Train Accuracy: 0.400
Train Loss: 1.975, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.700
Round 22
Train Loss: 1.260, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.500
Train Loss: 1.001, Train Accuracy: 0.400
Train Loss: 1.368, Train Accuracy: 0.600
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.394, Train Accuracy: 0.800
Train Loss: 1.595, Train Accuracy: 0.500
Train Loss: 1.137, Train Accuracy: 0.600
Train Loss: 2.005, Train Accuracy: 0.750
Train Loss: 1.121, Train Accuracy: 0.400
Round 23
Train Loss: 1.212, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.500
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.467, Train Accuracy: 0.800
Train Loss: 1.153, Train Accuracy: 0.750
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.540, Train Accuracy: 0.500
Train Loss: 1.133, Train Accuracy: 0.400
Train Loss: 2.065, Train Accuracy: 0.750
Train Loss: 1.130, Train Accuracy: 0.400
Round 24
Train Loss: 1.139, Train Accuracy: 0.750
Train Loss: 1.017, Train Accuracy: 0.600
Train Loss: 1.004, Train Accuracy: 0.400
Train Loss: 1.529, Train Accuracy: 0.800
Train Loss: 1.175, Train Accuracy: 0.625
Train Loss: 1.401, Train Accuracy: 0.800
Train Loss: 1.572, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.400
Train Loss: 1.912, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.700
Round 25
Train Loss: 1.227, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.600
Train Loss: 0.990, Train Accuracy: 0.400
Train Loss: 1.488, Train Accuracy: 0.800
Train Loss: 1.180, Train Accuracy: 0.750
Train Loss: 1.453, Train Accuracy: 0.800
Train Loss: 1.614, Train Accuracy: 1.000
Train Loss: 1.288, Train Accuracy: 0.800
Train Loss: 2.106, Train Accuracy: 0.750
Train Loss: 1.116, Train Accuracy: 0.300
Round 26
Train Loss: 1.282, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.600
Train Loss: 0.989, Train Accuracy: 0.200
Train Loss: 1.425, Train Accuracy: 0.600
Train Loss: 1.185, Train Accuracy: 0.750
Train Loss: 1.427, Train Accuracy: 0.800
Train Loss: 1.465, Train Accuracy: 0.500
Train Loss: 1.147, Train Accuracy: 0.400
Train Loss: 2.005, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.700
Round 27
Train Loss: 1.175, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.400
Train Loss: 0.982, Train Accuracy: 0.800
Train Loss: 1.421, Train Accuracy: 0.600
Train Loss: 1.155, Train Accuracy: 0.750
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.579, Train Accuracy: 0.750
Train Loss: 1.224, Train Accuracy: 0.400
Train Loss: 2.108, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.600
Round 28
Train Loss: 1.156, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.800
Train Loss: 0.970, Train Accuracy: 0.400
Train Loss: 1.486, Train Accuracy: 0.600
Train Loss: 1.113, Train Accuracy: 0.625
Train Loss: 1.359, Train Accuracy: 0.800
Train Loss: 1.495, Train Accuracy: 1.000
Train Loss: 1.155, Train Accuracy: 0.600
Train Loss: 2.144, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.600
Round 29
Train Loss: 1.349, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.700
Train Loss: 0.970, Train Accuracy: 0.400
Train Loss: 1.333, Train Accuracy: 0.600
Train Loss: 1.176, Train Accuracy: 0.750
Train Loss: 1.453, Train Accuracy: 0.800
Train Loss: 1.637, Train Accuracy: 0.500
Train Loss: 1.246, Train Accuracy: 0.800
Train Loss: 1.820, Train Accuracy: 0.750
Train Loss: 1.083, Train Accuracy: 0.500
Round 30
Train Loss: 1.195, Train Accuracy: 0.750
Train Loss: 0.998, Train Accuracy: 0.700
Train Loss: 0.965, Train Accuracy: 0.600
Train Loss: 1.609, Train Accuracy: 0.800
Train Loss: 1.196, Train Accuracy: 0.625
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.713, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.800
Train Loss: 1.987, Train Accuracy: 0.750
Train Loss: 1.128, Train Accuracy: 0.500
Round 31
Train Loss: 1.297, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.500
Train Loss: 0.970, Train Accuracy: 0.400
Train Loss: 1.500, Train Accuracy: 0.800
Train Loss: 1.205, Train Accuracy: 0.750
Train Loss: 1.412, Train Accuracy: 0.800
Train Loss: 1.507, Train Accuracy: 0.750
Train Loss: 1.264, Train Accuracy: 0.600
Train Loss: 2.047, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.800
Round 32
Train Loss: 1.302, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.700
Train Loss: 0.963, Train Accuracy: 0.400
Train Loss: 1.518, Train Accuracy: 0.800
Train Loss: 1.123, Train Accuracy: 0.750
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.727, Train Accuracy: 0.500
Train Loss: 1.087, Train Accuracy: 0.800
Train Loss: 2.024, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.500
Round 33
Train Loss: 1.218, Train Accuracy: 0.750
Train Loss: 1.007, Train Accuracy: 0.800
Train Loss: 0.979, Train Accuracy: 0.200
Train Loss: 1.480, Train Accuracy: 1.000
Train Loss: 1.109, Train Accuracy: 0.875
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.742, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.600
Train Loss: 1.737, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.700
Round 34
Train Loss: 1.115, Train Accuracy: 0.750
Train Loss: 1.008, Train Accuracy: 0.600
Train Loss: 0.984, Train Accuracy: 0.600
Train Loss: 1.348, Train Accuracy: 0.600
Train Loss: 1.090, Train Accuracy: 0.750
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.643, Train Accuracy: 1.000
Train Loss: 1.131, Train Accuracy: 0.200
Train Loss: 2.148, Train Accuracy: 0.750
Train Loss: 1.046, Train Accuracy: 0.300
Round 35
Train Loss: 1.100, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 0.953, Train Accuracy: 0.400
Train Loss: 1.309, Train Accuracy: 0.600
Train Loss: 1.110, Train Accuracy: 0.750
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.501, Train Accuracy: 0.750
Train Loss: 1.018, Train Accuracy: 0.800
Train Loss: 2.022, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.600
Round 36
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.700
Train Loss: 1.013, Train Accuracy: 0.400
Train Loss: 1.437, Train Accuracy: 0.800
Train Loss: 1.093, Train Accuracy: 0.875
Train Loss: 1.255, Train Accuracy: 0.800
Train Loss: 1.701, Train Accuracy: 0.500
Train Loss: 1.052, Train Accuracy: 0.800
Train Loss: 2.266, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.300
Round 37
Train Loss: 1.244, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.700
Train Loss: 0.926, Train Accuracy: 0.400
Train Loss: 1.365, Train Accuracy: 1.000
Train Loss: 1.179, Train Accuracy: 0.750
Train Loss: 1.407, Train Accuracy: 0.800
Train Loss: 1.781, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.800
Train Loss: 1.838, Train Accuracy: 0.750
Train Loss: 1.259, Train Accuracy: 0.700
Round 38
Train Loss: 1.386, Train Accuracy: 0.750
Train Loss: 1.017, Train Accuracy: 0.400
Train Loss: 0.938, Train Accuracy: 0.400
Train Loss: 1.431, Train Accuracy: 0.600
Train Loss: 1.076, Train Accuracy: 0.750
Train Loss: 1.346, Train Accuracy: 0.800
Train Loss: 1.654, Train Accuracy: 0.750
Train Loss: 1.094, Train Accuracy: 0.600
Train Loss: 1.913, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.500
Round 39
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 1.017, Train Accuracy: 0.400
Train Loss: 0.938, Train Accuracy: 0.600
Train Loss: 1.291, Train Accuracy: 0.600
Train Loss: 1.149, Train Accuracy: 0.750
Train Loss: 1.379, Train Accuracy: 0.800
Train Loss: 1.413, Train Accuracy: 0.750
Train Loss: 1.122, Train Accuracy: 0.800
Train Loss: 1.774, Train Accuracy: 0.750
Train Loss: 1.330, Train Accuracy: 0.500
Round 40
Train Loss: 1.353, Train Accuracy: 0.750
Train Loss: 0.967, Train Accuracy: 0.700
Train Loss: 0.926, Train Accuracy: 0.800
Train Loss: 1.364, Train Accuracy: 1.000
Train Loss: 1.112, Train Accuracy: 0.500
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.548, Train Accuracy: 0.750
Train Loss: 1.128, Train Accuracy: 0.600
Train Loss: 2.069, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.300
Round 41
Train Loss: 1.235, Train Accuracy: 0.750
Train Loss: 0.957, Train Accuracy: 0.800
Train Loss: 0.915, Train Accuracy: 0.600
Train Loss: 1.409, Train Accuracy: 1.000
Train Loss: 1.115, Train Accuracy: 0.625
Train Loss: 1.318, Train Accuracy: 0.800
Train Loss: 1.624, Train Accuracy: 0.500
Train Loss: 0.979, Train Accuracy: 0.800
Train Loss: 2.078, Train Accuracy: 1.000
Train Loss: 1.207, Train Accuracy: 0.700
Round 42
Train Loss: 1.179, Train Accuracy: 0.500
Train Loss: 1.017, Train Accuracy: 0.500
Train Loss: 0.925, Train Accuracy: 0.600
Train Loss: 1.352, Train Accuracy: 0.800
Train Loss: 1.112, Train Accuracy: 0.875
Train Loss: 1.273, Train Accuracy: 0.800
Train Loss: 1.482, Train Accuracy: 0.500
Train Loss: 1.111, Train Accuracy: 0.400
Train Loss: 1.867, Train Accuracy: 0.750
Train Loss: 1.088, Train Accuracy: 0.700
Round 43
Train Loss: 1.223, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.400
Train Loss: 0.945, Train Accuracy: 0.600
Train Loss: 1.327, Train Accuracy: 1.000
Train Loss: 1.055, Train Accuracy: 0.750
Train Loss: 1.313, Train Accuracy: 0.800
Train Loss: 1.437, Train Accuracy: 1.000
Train Loss: 1.313, Train Accuracy: 0.800
Train Loss: 2.046, Train Accuracy: 1.000
Train Loss: 1.084, Train Accuracy: 0.800
Round 44
Train Loss: 1.098, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 0.897, Train Accuracy: 0.400
Train Loss: 1.254, Train Accuracy: 0.600
Train Loss: 1.090, Train Accuracy: 0.375
Train Loss: 1.287, Train Accuracy: 0.800
Train Loss: 1.434, Train Accuracy: 1.000
Train Loss: 1.145, Train Accuracy: 0.400
Train Loss: 1.675, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.700
Round 45
Train Loss: 1.155, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.500
Train Loss: 0.897, Train Accuracy: 0.600
Train Loss: 1.431, Train Accuracy: 0.800
Train Loss: 1.088, Train Accuracy: 0.750
Train Loss: 1.446, Train Accuracy: 0.800
Train Loss: 1.568, Train Accuracy: 1.000
Train Loss: 1.116, Train Accuracy: 1.000
Train Loss: 2.154, Train Accuracy: 1.000
Train Loss: 1.230, Train Accuracy: 0.500
Round 46
Train Loss: 1.060, Train Accuracy: 0.750
Train Loss: 0.940, Train Accuracy: 0.800
Train Loss: 0.935, Train Accuracy: 0.800
Train Loss: 1.393, Train Accuracy: 1.000
Train Loss: 1.001, Train Accuracy: 0.625
Train Loss: 1.251, Train Accuracy: 0.800
Train Loss: 1.597, Train Accuracy: 1.000
Train Loss: 0.980, Train Accuracy: 0.600
Train Loss: 2.032, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.700
Round 47
Train Loss: 1.206, Train Accuracy: 0.500
Train Loss: 0.997, Train Accuracy: 0.400
Train Loss: 0.886, Train Accuracy: 0.400
Train Loss: 1.309, Train Accuracy: 1.000
Train Loss: 1.012, Train Accuracy: 0.750
Train Loss: 1.268, Train Accuracy: 0.800
Train Loss: 1.530, Train Accuracy: 0.500
Train Loss: 1.068, Train Accuracy: 0.600
Train Loss: 2.429, Train Accuracy: 1.000
Train Loss: 1.145, Train Accuracy: 0.700
Round 48
Train Loss: 1.082, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.700
Train Loss: 0.927, Train Accuracy: 0.800
Train Loss: 1.177, Train Accuracy: 0.800
Train Loss: 1.085, Train Accuracy: 0.875
Train Loss: 1.396, Train Accuracy: 0.800
Train Loss: 1.536, Train Accuracy: 1.000

(FLClient pid=2870275) 2025-04-11 09:12:57,263 - INFO - Epoch   2| Train Loss: 0.635| Train Accuracy: 0.750 [repeated 330x across cluster]
(FLClient pid=2870275) 2025-04-11 09:12:57,272 - INFO - Epoch   2| Validation Loss: 1.394, Validation Accuracy: 0.295 [repeated 110x across cluster]
(FLClient pid=2870275) 2025-04-11 09:13:02,558 - INFO - Epoch   0| Train Loss: 1.108| Train Accuracy: 0.500 [repeated 448x across cluster]
(FLClient pid=2870277) 2025-04-11 09:13:02,250 - INFO - Epoch   2| Validation Loss: 1.011, Validation Accuracy: 0.510 [repeated 149x across cluster]
(FLClient pid=2870275) 2025-04-11 09:13:07,681 - INFO - Epoch   2| Train Loss: 0.680| Train Accuracy: 0.750 [repeated 452x across cluster]
(FLClient pid=2870275) 2025-04-11 09:13:07,687 - INFO - Epoch   2| Validation Loss: 1.494, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2870275) 2025-04-11 09:13:12,771 - INFO - Epoch   2| Train Loss: 0.626| Train Accuracy: 1.000 [repeated 450x across cluster]
(FLClient pid=2870275) 2025-04-11 09:13:12,779 - INFO - Epoch   2| Validation Loss: 1.522, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2870275) 2025-04-11 09:13:17,883 - INFO - Epoch   2| Train Loss: 0.455| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2870275) 2025-04-11 09:13:17,891 - INFO - Epoch   2| Validation Loss: 0.898, Validation Accuracy: 0.477 [repeated 150x across cluster]
(FLClient pid=2870275) 2025-04-11 09:13:22,968 - INFO - Epoch   2| Train Loss: 0.295| Train Accuracy: 1.000 [repeated 450x across cluster]
(FLClient pid=2870275) 2025-04-11 09:13:22,975 - INFO - Epoch   2| Validation Loss: 1.159, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2870275) 2025-04-11 09:13:28,051 - INFO - Epoch   0| Train Loss: 0.700| Train Accuracy: 0.750 [repeated 448x across cluster]
(FLClient pid=2870486) 2025-04-11 09:13:27,742 - INFO - Epoch   2| Validation Loss: 1.381, Validation Accuracy: 0.234 [repeated 149x across cluster]

Training done
Round 1
Train Loss: 1.394, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.075, Train Accuracy: 0.400
Train Loss: 1.283, Train Accuracy: 0.600
Train Loss: 1.207, Train Accuracy: 0.625
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.438, Train Accuracy: 0.500
Train Loss: 1.147, Train Accuracy: 0.200
Train Loss: 1.536, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.400
Round 2
Train Loss: 1.388, Train Accuracy: 0.750
Train Loss: 1.083, Train Accuracy: 0.500
Train Loss: 1.073, Train Accuracy: 0.400
Train Loss: 1.376, Train Accuracy: 0.600
Train Loss: 1.257, Train Accuracy: 0.625
Train Loss: 1.335, Train Accuracy: 0.800
Train Loss: 1.494, Train Accuracy: 0.500
Train Loss: 1.170, Train Accuracy: 0.400
Train Loss: 1.658, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.500
Round 3
Train Loss: 1.455, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.062, Train Accuracy: 0.400
Train Loss: 1.403, Train Accuracy: 0.600
Train Loss: 1.270, Train Accuracy: 0.625
Train Loss: 1.283, Train Accuracy: 0.800
Train Loss: 1.566, Train Accuracy: 0.500
Train Loss: 1.179, Train Accuracy: 0.400
Train Loss: 1.624, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.300
Round 4
Train Loss: 1.510, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.200
Train Loss: 1.486, Train Accuracy: 0.600
Train Loss: 1.247, Train Accuracy: 0.625
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.566, Train Accuracy: 0.500
Train Loss: 1.220, Train Accuracy: 0.400
Train Loss: 1.760, Train Accuracy: 0.750
Train Loss: 1.199, Train Accuracy: 0.400
Round 5
Train Loss: 1.348, Train Accuracy: 0.750
Train Loss: 1.084, Train Accuracy: 0.500
Train Loss: 1.045, Train Accuracy: 0.400
Train Loss: 1.440, Train Accuracy: 0.600
Train Loss: 1.283, Train Accuracy: 0.625
Train Loss: 1.368, Train Accuracy: 0.800
Train Loss: 1.588, Train Accuracy: 0.500
Train Loss: 1.183, Train Accuracy: 0.200
Train Loss: 1.738, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.400
Round 6
Train Loss: 1.412, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 1.518, Train Accuracy: 0.600
Train Loss: 1.227, Train Accuracy: 0.625
Train Loss: 1.440, Train Accuracy: 0.800
Train Loss: 1.638, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.400
Train Loss: 1.863, Train Accuracy: 0.750
Train Loss: 1.199, Train Accuracy: 0.500
Round 7
Train Loss: 1.306, Train Accuracy: 0.750
Train Loss: 1.083, Train Accuracy: 0.500
Train Loss: 1.031, Train Accuracy: 0.400
Train Loss: 1.529, Train Accuracy: 0.600
Train Loss: 1.273, Train Accuracy: 0.625
Train Loss: 1.395, Train Accuracy: 0.800
Train Loss: 1.593, Train Accuracy: 0.250
Train Loss: 1.161, Train Accuracy: 0.600
Train Loss: 1.899, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.300
Round 8
Train Loss: 1.385, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.033, Train Accuracy: 0.400
Train Loss: 1.515, Train Accuracy: 0.600
Train Loss: 1.285, Train Accuracy: 0.625
Train Loss: 1.339, Train Accuracy: 0.800
Train Loss: 1.628, Train Accuracy: 0.500
Train Loss: 1.183, Train Accuracy: 0.400
Train Loss: 1.927, Train Accuracy: 0.750
Train Loss: 1.208, Train Accuracy: 0.600
Round 9
Train Loss: 1.530, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.600
Train Loss: 1.032, Train Accuracy: 0.600
Train Loss: 1.511, Train Accuracy: 0.600
Train Loss: 1.242, Train Accuracy: 0.625
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.635, Train Accuracy: 0.500
Train Loss: 1.192, Train Accuracy: 0.400
Train Loss: 1.856, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.400
Round 10
Train Loss: 1.361, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.600
Train Loss: 1.027, Train Accuracy: 0.400
Train Loss: 1.531, Train Accuracy: 0.600
Train Loss: 1.266, Train Accuracy: 0.625
Train Loss: 1.412, Train Accuracy: 0.800
Train Loss: 1.608, Train Accuracy: 0.500
Train Loss: 1.238, Train Accuracy: 0.800
Train Loss: 1.864, Train Accuracy: 0.750
Train Loss: 1.209, Train Accuracy: 0.600
Round 11
Train Loss: 1.530, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.400
Train Loss: 1.027, Train Accuracy: 0.400
Train Loss: 1.517, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.403, Train Accuracy: 0.800
Train Loss: 1.662, Train Accuracy: 0.500
Train Loss: 1.181, Train Accuracy: 0.600
Train Loss: 1.931, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.300
Round 12
Train Loss: 1.261, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.500
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.485, Train Accuracy: 0.600
Train Loss: 1.292, Train Accuracy: 0.625
Train Loss: 1.503, Train Accuracy: 0.800
Train Loss: 1.665, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.800
Train Loss: 1.910, Train Accuracy: 0.750
Train Loss: 1.208, Train Accuracy: 0.400
Round 13
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.600
Train Loss: 1.020, Train Accuracy: 0.400
Train Loss: 1.586, Train Accuracy: 0.600
Train Loss: 1.256, Train Accuracy: 0.625
Train Loss: 1.365, Train Accuracy: 0.800
Train Loss: 1.625, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.800
Train Loss: 1.936, Train Accuracy: 0.750
Train Loss: 1.222, Train Accuracy: 0.500
Round 14
Train Loss: 1.532, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.700
Train Loss: 1.014, Train Accuracy: 0.200
Train Loss: 1.536, Train Accuracy: 0.600
Train Loss: 1.264, Train Accuracy: 0.625
Train Loss: 1.396, Train Accuracy: 0.800
Train Loss: 1.659, Train Accuracy: 0.500
Train Loss: 1.170, Train Accuracy: 0.600
Train Loss: 2.038, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.500
Round 15
Train Loss: 1.372, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.520, Train Accuracy: 0.600
Train Loss: 1.180, Train Accuracy: 0.625
Train Loss: 1.314, Train Accuracy: 0.800
Train Loss: 1.578, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.400
Train Loss: 1.990, Train Accuracy: 0.750
Train Loss: 1.209, Train Accuracy: 0.400
Round 16
Train Loss: 1.540, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.500
Train Loss: 1.040, Train Accuracy: 0.400
Train Loss: 1.543, Train Accuracy: 0.600
Train Loss: 1.178, Train Accuracy: 0.625
Train Loss: 1.390, Train Accuracy: 0.800
Train Loss: 1.649, Train Accuracy: 0.250
Train Loss: 1.128, Train Accuracy: 0.600
Train Loss: 1.984, Train Accuracy: 0.750
Train Loss: 1.218, Train Accuracy: 0.600
Round 17
Train Loss: 1.428, Train Accuracy: 0.750
Train Loss: 1.050, Train Accuracy: 0.600
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 1.516, Train Accuracy: 0.600
Train Loss: 1.215, Train Accuracy: 0.625
Train Loss: 1.327, Train Accuracy: 0.800
Train Loss: 1.656, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.400
Train Loss: 1.989, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.700
Round 18
Train Loss: 1.332, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.600
Train Loss: 1.005, Train Accuracy: 0.600
Train Loss: 1.589, Train Accuracy: 0.800
Train Loss: 1.189, Train Accuracy: 0.625
Train Loss: 1.381, Train Accuracy: 0.800
Train Loss: 1.638, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.400
Train Loss: 2.080, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.600
Round 19
Train Loss: 1.504, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.600
Train Loss: 1.007, Train Accuracy: 0.400
Train Loss: 1.485, Train Accuracy: 0.800
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.407, Train Accuracy: 0.800
Train Loss: 1.662, Train Accuracy: 0.750
Train Loss: 1.114, Train Accuracy: 0.400
Train Loss: 2.131, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.500
Round 20
Train Loss: 1.418, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.800
Train Loss: 1.011, Train Accuracy: 0.600
Train Loss: 1.534, Train Accuracy: 0.800
Train Loss: 1.187, Train Accuracy: 0.625
Train Loss: 1.232, Train Accuracy: 0.800
Train Loss: 1.701, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.600
Train Loss: 2.084, Train Accuracy: 0.750
Train Loss: 1.132, Train Accuracy: 0.400
Round 21
Train Loss: 1.427, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.500
Train Loss: 1.013, Train Accuracy: 0.400
Train Loss: 1.533, Train Accuracy: 0.600
Train Loss: 1.164, Train Accuracy: 0.625
Train Loss: 1.273, Train Accuracy: 0.800
Train Loss: 1.682, Train Accuracy: 0.750
Train Loss: 1.230, Train Accuracy: 0.800
Train Loss: 2.188, Train Accuracy: 0.750
Train Loss: 1.129, Train Accuracy: 0.600
Round 22
Train Loss: 1.321, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.600
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 1.485, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.750
Train Loss: 1.379, Train Accuracy: 0.800
Train Loss: 1.644, Train Accuracy: 0.500
Train Loss: 1.175, Train Accuracy: 0.600
Train Loss: 1.822, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.500
Round 23
Train Loss: 1.363, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.700
Train Loss: 0.981, Train Accuracy: 0.600
Train Loss: 1.477, Train Accuracy: 0.600
Train Loss: 1.176, Train Accuracy: 0.625
Train Loss: 1.378, Train Accuracy: 0.800
Train Loss: 1.548, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.600
Train Loss: 2.105, Train Accuracy: 0.750
Train Loss: 1.129, Train Accuracy: 0.600
Round 24
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.800
Train Loss: 0.996, Train Accuracy: 0.400
Train Loss: 1.515, Train Accuracy: 0.600
Train Loss: 1.191, Train Accuracy: 0.625
Train Loss: 1.358, Train Accuracy: 0.800
Train Loss: 1.545, Train Accuracy: 0.500
Train Loss: 1.158, Train Accuracy: 0.800
Train Loss: 2.178, Train Accuracy: 1.000
Train Loss: 1.161, Train Accuracy: 0.900
Round 25
Train Loss: 1.161, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.600
Train Loss: 0.993, Train Accuracy: 0.600
Train Loss: 1.491, Train Accuracy: 0.800
Train Loss: 1.153, Train Accuracy: 0.625
Train Loss: 1.271, Train Accuracy: 0.800
Train Loss: 1.632, Train Accuracy: 1.000
Train Loss: 1.135, Train Accuracy: 0.600
Train Loss: 1.987, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.600
Round 26
Train Loss: 1.319, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.700
Train Loss: 0.983, Train Accuracy: 0.400
Train Loss: 1.457, Train Accuracy: 0.800
Train Loss: 1.193, Train Accuracy: 0.625
Train Loss: 1.372, Train Accuracy: 0.800
Train Loss: 1.533, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.400
Train Loss: 2.173, Train Accuracy: 1.000
Train Loss: 1.229, Train Accuracy: 0.800
Round 27
Train Loss: 1.567, Train Accuracy: 0.750
Train Loss: 1.003, Train Accuracy: 0.600
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 1.462, Train Accuracy: 0.800
Train Loss: 1.211, Train Accuracy: 0.625
Train Loss: 1.414, Train Accuracy: 0.800
Train Loss: 1.552, Train Accuracy: 0.500
Train Loss: 1.146, Train Accuracy: 0.800
Train Loss: 2.048, Train Accuracy: 1.000
Train Loss: 1.190, Train Accuracy: 0.800
Round 28
Train Loss: 1.342, Train Accuracy: 0.750
Train Loss: 1.014, Train Accuracy: 0.500
Train Loss: 0.973, Train Accuracy: 0.400
Train Loss: 1.619, Train Accuracy: 0.600
Train Loss: 1.211, Train Accuracy: 0.625
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.580, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.600
Train Loss: 1.809, Train Accuracy: 0.750
Train Loss: 1.226, Train Accuracy: 0.700
Round 29
Train Loss: 1.384, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.400
Train Loss: 0.968, Train Accuracy: 0.600
Train Loss: 1.446, Train Accuracy: 0.800
Train Loss: 1.147, Train Accuracy: 0.375
Train Loss: 1.360, Train Accuracy: 0.800
Train Loss: 1.622, Train Accuracy: 1.000
Train Loss: 1.065, Train Accuracy: 0.800
Train Loss: 1.983, Train Accuracy: 0.750
Train Loss: 1.290, Train Accuracy: 0.300
Round 30
Train Loss: 1.127, Train Accuracy: 0.750
Train Loss: 0.996, Train Accuracy: 0.500
Train Loss: 0.961, Train Accuracy: 0.400
Train Loss: 1.477, Train Accuracy: 1.000
Train Loss: 1.112, Train Accuracy: 0.625
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.553, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.400
Train Loss: 1.970, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.500
Round 31
Train Loss: 1.494, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.800
Train Loss: 0.962, Train Accuracy: 0.600
Train Loss: 1.537, Train Accuracy: 0.800
Train Loss: 1.212, Train Accuracy: 0.625
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.667, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.800
Train Loss: 1.965, Train Accuracy: 0.750
Train Loss: 1.229, Train Accuracy: 0.800
Round 32
Train Loss: 1.187, Train Accuracy: 0.750
Train Loss: 0.994, Train Accuracy: 0.600
Train Loss: 0.995, Train Accuracy: 0.600
Train Loss: 1.504, Train Accuracy: 1.000
Train Loss: 1.113, Train Accuracy: 0.625
Train Loss: 1.407, Train Accuracy: 0.800
Train Loss: 1.669, Train Accuracy: 1.000
Train Loss: 1.219, Train Accuracy: 0.600
Train Loss: 2.076, Train Accuracy: 0.750
Train Loss: 1.121, Train Accuracy: 0.600
Round 33
Train Loss: 1.110, Train Accuracy: 0.750
Train Loss: 0.996, Train Accuracy: 0.700
Train Loss: 0.978, Train Accuracy: 0.400
Train Loss: 1.627, Train Accuracy: 0.800
Train Loss: 1.153, Train Accuracy: 0.750
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.582, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 1.000
Train Loss: 1.880, Train Accuracy: 0.750
Train Loss: 1.125, Train Accuracy: 0.700
Round 34
Train Loss: 1.276, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.300
Train Loss: 0.963, Train Accuracy: 0.800
Train Loss: 1.413, Train Accuracy: 0.600
Train Loss: 1.098, Train Accuracy: 0.750
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.602, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 1.000
Train Loss: 1.819, Train Accuracy: 0.750
Train Loss: 1.129, Train Accuracy: 0.800
Round 35
Train Loss: 1.424, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.600
Train Loss: 0.944, Train Accuracy: 0.400
Train Loss: 1.426, Train Accuracy: 0.800
Train Loss: 1.128, Train Accuracy: 0.875
Train Loss: 1.252, Train Accuracy: 0.800
Train Loss: 1.549, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 1.000
Train Loss: 2.038, Train Accuracy: 0.750
Train Loss: 1.213, Train Accuracy: 0.600
Round 36
Train Loss: 1.332, Train Accuracy: 0.750
Train Loss: 1.020, Train Accuracy: 0.700
Train Loss: 0.949, Train Accuracy: 0.400
Train Loss: 1.361, Train Accuracy: 1.000
Train Loss: 1.198, Train Accuracy: 0.625
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.681, Train Accuracy: 1.000
Train Loss: 1.191, Train Accuracy: 0.600
Train Loss: 2.014, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.800
Round 37
Train Loss: 1.137, Train Accuracy: 0.750
Train Loss: 1.014, Train Accuracy: 0.600
Train Loss: 0.947, Train Accuracy: 0.400
Train Loss: 1.379, Train Accuracy: 0.800
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.672, Train Accuracy: 0.500
Train Loss: 1.252, Train Accuracy: 0.600
Train Loss: 1.838, Train Accuracy: 0.750
Train Loss: 1.233, Train Accuracy: 0.700
Round 38
Train Loss: 1.222, Train Accuracy: 0.750
Train Loss: 1.022, Train Accuracy: 0.500
Train Loss: 0.932, Train Accuracy: 1.000
Train Loss: 1.498, Train Accuracy: 1.000
Train Loss: 1.146, Train Accuracy: 0.750
Train Loss: 1.265, Train Accuracy: 0.800
Train Loss: 1.522, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.400
Train Loss: 1.790, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.500
Round 39
Train Loss: 1.013, Train Accuracy: 0.750
Train Loss: 0.983, Train Accuracy: 0.600
Train Loss: 0.923, Train Accuracy: 0.400
Train Loss: 1.342, Train Accuracy: 0.800
Train Loss: 1.133, Train Accuracy: 0.750
Train Loss: 1.363, Train Accuracy: 0.800
Train Loss: 1.686, Train Accuracy: 0.500
Train Loss: 1.115, Train Accuracy: 0.800
Train Loss: 1.968, Train Accuracy: 1.000
Train Loss: 1.344, Train Accuracy: 0.800
Round 40
Train Loss: 1.553, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.500
Train Loss: 0.986, Train Accuracy: 0.600
Train Loss: 1.434, Train Accuracy: 1.000
Train Loss: 1.098, Train Accuracy: 0.750
Train Loss: 1.298, Train Accuracy: 0.800
Train Loss: 1.694, Train Accuracy: 1.000
Train Loss: 1.213, Train Accuracy: 0.800
Train Loss: 2.100, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.300
Round 41
Train Loss: 1.278, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.700
Train Loss: 0.926, Train Accuracy: 0.800
Train Loss: 1.458, Train Accuracy: 0.800
Train Loss: 1.070, Train Accuracy: 0.500
Train Loss: 1.287, Train Accuracy: 0.800
Train Loss: 1.606, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.200
Train Loss: 1.694, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.900
Round 42
Train Loss: 1.141, Train Accuracy: 0.750
Train Loss: 0.945, Train Accuracy: 0.500
Train Loss: 0.904, Train Accuracy: 0.400
Train Loss: 1.505, Train Accuracy: 0.800
Train Loss: 1.175, Train Accuracy: 0.875
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.774, Train Accuracy: 1.000
Train Loss: 1.033, Train Accuracy: 1.000
Train Loss: 2.103, Train Accuracy: 0.750
Train Loss: 1.083, Train Accuracy: 0.900
Round 43
Train Loss: 1.107, Train Accuracy: 0.750
Train Loss: 0.984, Train Accuracy: 0.700
Train Loss: 0.937, Train Accuracy: 0.800
Train Loss: 1.435, Train Accuracy: 1.000
Train Loss: 1.180, Train Accuracy: 0.625
Train Loss: 1.204, Train Accuracy: 0.800
Train Loss: 1.936, Train Accuracy: 0.750
Train Loss: 1.094, Train Accuracy: 0.600
Train Loss: 1.832, Train Accuracy: 0.750
Train Loss: 0.978, Train Accuracy: 0.600
Round 44
Train Loss: 1.233, Train Accuracy: 0.750
Train Loss: 0.922, Train Accuracy: 0.700
Train Loss: 0.900, Train Accuracy: 0.800
Train Loss: 1.559, Train Accuracy: 1.000
Train Loss: 1.104, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.800
Train Loss: 1.761, Train Accuracy: 0.750
Train Loss: 0.971, Train Accuracy: 0.800
Train Loss: 1.775, Train Accuracy: 0.750
Train Loss: 1.230, Train Accuracy: 0.700
Round 45
Train Loss: 1.379, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.400
Train Loss: 0.916, Train Accuracy: 0.800
Train Loss: 1.729, Train Accuracy: 0.800
Train Loss: 1.131, Train Accuracy: 0.625
Train Loss: 1.228, Train Accuracy: 0.800
Train Loss: 1.809, Train Accuracy: 0.750
Train Loss: 1.138, Train Accuracy: 0.800
Train Loss: 2.268, Train Accuracy: 1.000
Train Loss: 1.167, Train Accuracy: 0.700
Round 46
Train Loss: 1.522, Train Accuracy: 1.000
Train Loss: 0.944, Train Accuracy: 0.700
Train Loss: 0.909, Train Accuracy: 0.800
Train Loss: 1.285, Train Accuracy: 0.800
Train Loss: 1.088, Train Accuracy: 0.625
Train Loss: 1.239, Train Accuracy: 0.800
Train Loss: 1.764, Train Accuracy: 1.000
Train Loss: 0.977, Train Accuracy: 0.600
Train Loss: 1.930, Train Accuracy: 0.750
Train Loss: 1.252, Train Accuracy: 0.500
Round 47
Train Loss: 1.256, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.900
Train Loss: 0.920, Train Accuracy: 0.400
Train Loss: 1.348, Train Accuracy: 0.800
Train Loss: 1.086, Train Accuracy: 0.750
Train Loss: 1.231, Train Accuracy: 0.800
Train Loss: 1.647, Train Accuracy: 1.000
Train Loss: 1.005, Train Accuracy: 0.800
Train Loss: 2.077, Train Accuracy: 0.750
Train Loss: 1.283, Train Accuracy: 0.500
Round 48
Train Loss: 1.250, Train Accuracy: 0.750
Train Loss: 0.993, Train Accuracy: 0.600
Train Loss: 0.889, Train Accuracy: 0.800
Train Loss: 1.434, Train Accuracy: 1.000
Train Loss: 1.114, Train Accuracy: 0.875
Train Loss: 1.415, Train Accuracy: 0.800
Train Loss: 1.729, Train Accuracy: 0.500

(FLClient pid=2871276) 2025-04-11 09:13:38,734 - INFO - Epoch   2| Train Loss: 0.811| Train Accuracy: 0.750 [repeated 302x across cluster]
(FLClient pid=2871276) 2025-04-11 09:13:38,747 - INFO - Epoch   2| Validation Loss: 1.165, Validation Accuracy: 0.295 [repeated 101x across cluster]
(FLClient pid=2871277) 2025-04-11 09:13:43,957 - INFO - Epoch   0| Train Loss: 1.073| Train Accuracy: 0.400 [repeated 388x across cluster]
(FLClient pid=2871540) 2025-04-11 09:13:43,649 - INFO - Epoch   2| Validation Loss: 1.738, Validation Accuracy: 0.233 [repeated 129x across cluster]
(FLClient pid=2871591) 2025-04-11 09:13:49,087 - INFO - Epoch   1| Train Loss: 0.854| Train Accuracy: 0.700 [repeated 451x across cluster]
(FLClient pid=2871540) 2025-04-11 09:13:48,766 - INFO - Epoch   2| Validation Loss: 1.867, Validation Accuracy: 0.233 [repeated 150x across cluster]
(FLClient pid=2871591) 2025-04-11 09:13:54,163 - INFO - Epoch   2| Train Loss: 0.794| Train Accuracy: 0.800 [repeated 451x across cluster]
(FLClient pid=2871591) 2025-04-11 09:13:54,170 - INFO - Epoch   2| Validation Loss: 1.023, Validation Accuracy: 0.547 [repeated 151x across cluster]
(FLClient pid=2871591) 2025-04-11 09:13:59,236 - INFO - Epoch   0| Train Loss: 0.860| Train Accuracy: 0.600 [repeated 448x across cluster]
(FLClient pid=2871540) 2025-04-11 09:13:58,927 - INFO - Epoch   2| Validation Loss: 2.276, Validation Accuracy: 0.233 [repeated 149x across cluster]
(FLClient pid=2871591) 2025-04-11 09:14:04,365 - INFO - Epoch   2| Train Loss: 0.556| Train Accuracy: 0.800 [repeated 452x across cluster]
(FLClient pid=2871591) 2025-04-11 09:14:04,370 - INFO - Epoch   2| Validation Loss: 0.997, Validation Accuracy: 0.547 [repeated 151x across cluster]
(FLClient pid=2871591) 2025-04-11 09:14:09,479 - INFO - Epoch   2| Train Loss: 0.637| Train Accuracy: 0.700 [repeated 450x across cluster]
(FLClient pid=2871591) 2025-04-11 09:14:09,485 - INFO - Epoch   2| Validation Loss: 0.859, Validation Accuracy: 0.516 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.165, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.049, Train Accuracy: 0.400
Train Loss: 1.168, Train Accuracy: 0.600
Train Loss: 1.200, Train Accuracy: 0.625
Train Loss: 1.218, Train Accuracy: 0.800
Train Loss: 1.310, Train Accuracy: 0.500
Train Loss: 1.128, Train Accuracy: 0.400
Train Loss: 1.368, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.400
Round 2
Train Loss: 1.205, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.400
Train Loss: 1.193, Train Accuracy: 0.800
Train Loss: 1.207, Train Accuracy: 0.625
Train Loss: 1.218, Train Accuracy: 0.800
Train Loss: 1.354, Train Accuracy: 0.500
Train Loss: 1.139, Train Accuracy: 0.600
Train Loss: 1.407, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.400
Round 3
Train Loss: 1.250, Train Accuracy: 0.750
Train Loss: 1.086, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.224, Train Accuracy: 0.600
Train Loss: 1.216, Train Accuracy: 0.625
Train Loss: 1.250, Train Accuracy: 0.800
Train Loss: 1.372, Train Accuracy: 0.500
Train Loss: 1.153, Train Accuracy: 0.600
Train Loss: 1.443, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.400
Round 4
Train Loss: 1.266, Train Accuracy: 0.750
Train Loss: 1.089, Train Accuracy: 0.500
Train Loss: 1.038, Train Accuracy: 0.400
Train Loss: 1.229, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.625
Train Loss: 1.260, Train Accuracy: 0.800
Train Loss: 1.409, Train Accuracy: 0.500
Train Loss: 1.147, Train Accuracy: 0.800
Train Loss: 1.447, Train Accuracy: 0.750
Train Loss: 1.214, Train Accuracy: 0.400
Round 5
Train Loss: 1.218, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.600
Train Loss: 1.031, Train Accuracy: 0.400
Train Loss: 1.259, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.284, Train Accuracy: 0.800
Train Loss: 1.399, Train Accuracy: 0.500
Train Loss: 1.139, Train Accuracy: 0.200
Train Loss: 1.514, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 0.400
Round 6
Train Loss: 1.246, Train Accuracy: 0.750
Train Loss: 1.089, Train Accuracy: 0.500
Train Loss: 1.024, Train Accuracy: 0.400
Train Loss: 1.271, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.252, Train Accuracy: 0.800
Train Loss: 1.465, Train Accuracy: 1.000
Train Loss: 1.152, Train Accuracy: 0.400
Train Loss: 1.538, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.500
Round 7
Train Loss: 1.276, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.288, Train Accuracy: 0.600
Train Loss: 1.233, Train Accuracy: 0.625
Train Loss: 1.244, Train Accuracy: 0.800
Train Loss: 1.447, Train Accuracy: 0.500
Train Loss: 1.140, Train Accuracy: 0.200
Train Loss: 1.588, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.400
Round 8
Train Loss: 1.388, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.023, Train Accuracy: 0.400
Train Loss: 1.286, Train Accuracy: 0.600
Train Loss: 1.251, Train Accuracy: 0.625
Train Loss: 1.260, Train Accuracy: 0.800
Train Loss: 1.450, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.400
Train Loss: 1.642, Train Accuracy: 0.750
Train Loss: 1.205, Train Accuracy: 0.300
Round 9
Train Loss: 1.411, Train Accuracy: 0.750
Train Loss: 1.084, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.277, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.625
Train Loss: 1.285, Train Accuracy: 0.800
Train Loss: 1.470, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.600
Train Loss: 1.602, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.400
Round 10
Train Loss: 1.241, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.019, Train Accuracy: 0.600
Train Loss: 1.316, Train Accuracy: 0.600
Train Loss: 1.212, Train Accuracy: 0.625
Train Loss: 1.276, Train Accuracy: 0.800
Train Loss: 1.466, Train Accuracy: 0.500
Train Loss: 1.137, Train Accuracy: 0.400
Train Loss: 1.744, Train Accuracy: 0.750
Train Loss: 1.213, Train Accuracy: 0.500
Round 11
Train Loss: 1.254, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.015, Train Accuracy: 0.400
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.209, Train Accuracy: 0.500
Train Loss: 1.273, Train Accuracy: 0.800
Train Loss: 1.513, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.600
Train Loss: 1.617, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.400
Round 12
Train Loss: 1.332, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.500
Train Loss: 1.014, Train Accuracy: 0.600
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.262, Train Accuracy: 0.625
Train Loss: 1.288, Train Accuracy: 0.800
Train Loss: 1.501, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.600
Train Loss: 1.797, Train Accuracy: 0.750
Train Loss: 1.209, Train Accuracy: 0.600
Round 13
Train Loss: 1.229, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.600
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.381, Train Accuracy: 0.800
Train Loss: 1.248, Train Accuracy: 0.500
Train Loss: 1.254, Train Accuracy: 0.800
Train Loss: 1.544, Train Accuracy: 1.000
Train Loss: 1.188, Train Accuracy: 0.800
Train Loss: 1.738, Train Accuracy: 0.750
Train Loss: 1.234, Train Accuracy: 0.500
Round 14
Train Loss: 1.305, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 1.381, Train Accuracy: 0.400
Train Loss: 1.239, Train Accuracy: 0.625
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.544, Train Accuracy: 1.000
Train Loss: 1.148, Train Accuracy: 0.400
Train Loss: 1.666, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.200
Round 15
Train Loss: 1.450, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.500
Train Loss: 1.003, Train Accuracy: 0.200
Train Loss: 1.319, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.603, Train Accuracy: 0.500
Train Loss: 1.154, Train Accuracy: 0.600
Train Loss: 1.812, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.400
Round 16
Train Loss: 1.286, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.500
Train Loss: 1.002, Train Accuracy: 0.400
Train Loss: 1.326, Train Accuracy: 0.600
Train Loss: 1.227, Train Accuracy: 0.750
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.498, Train Accuracy: 0.750
Train Loss: 1.148, Train Accuracy: 0.400
Train Loss: 1.698, Train Accuracy: 0.750
Train Loss: 1.260, Train Accuracy: 0.400
Round 17
Train Loss: 1.333, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.600
Train Loss: 1.001, Train Accuracy: 0.400
Train Loss: 1.332, Train Accuracy: 0.400
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.540, Train Accuracy: 0.750
Train Loss: 1.146, Train Accuracy: 0.600
Train Loss: 1.940, Train Accuracy: 1.000
Train Loss: 1.202, Train Accuracy: 0.400
Round 18
Train Loss: 1.312, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.500
Train Loss: 0.995, Train Accuracy: 0.400
Train Loss: 1.315, Train Accuracy: 0.800
Train Loss: 1.220, Train Accuracy: 0.750
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.541, Train Accuracy: 1.000
Train Loss: 1.176, Train Accuracy: 0.600
Train Loss: 1.801, Train Accuracy: 0.750
Train Loss: 1.211, Train Accuracy: 0.500
Round 19
Train Loss: 1.302, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.600
Train Loss: 1.001, Train Accuracy: 0.400
Train Loss: 1.347, Train Accuracy: 0.600
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.360, Train Accuracy: 0.800
Train Loss: 1.529, Train Accuracy: 0.500
Train Loss: 1.141, Train Accuracy: 0.400
Train Loss: 1.756, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.500
Round 20
Train Loss: 1.338, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.500
Train Loss: 0.992, Train Accuracy: 0.400
Train Loss: 1.428, Train Accuracy: 0.400
Train Loss: 1.204, Train Accuracy: 0.750
Train Loss: 1.228, Train Accuracy: 0.800
Train Loss: 1.441, Train Accuracy: 0.500
Train Loss: 1.135, Train Accuracy: 0.600
Train Loss: 1.838, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.600
Round 21
Train Loss: 1.262, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.500
Train Loss: 0.983, Train Accuracy: 0.400
Train Loss: 1.394, Train Accuracy: 0.800
Train Loss: 1.231, Train Accuracy: 0.750
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.555, Train Accuracy: 1.000
Train Loss: 1.107, Train Accuracy: 0.600
Train Loss: 1.656, Train Accuracy: 0.750
Train Loss: 1.230, Train Accuracy: 0.400
Round 22
Train Loss: 1.223, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.700
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 1.424, Train Accuracy: 0.800
Train Loss: 1.271, Train Accuracy: 0.750
Train Loss: 1.307, Train Accuracy: 0.800
Train Loss: 1.573, Train Accuracy: 0.750
Train Loss: 1.102, Train Accuracy: 0.600
Train Loss: 1.804, Train Accuracy: 0.750
Train Loss: 1.190, Train Accuracy: 0.700
Round 23
Train Loss: 1.282, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 0.998, Train Accuracy: 0.600
Train Loss: 1.401, Train Accuracy: 0.600
Train Loss: 1.183, Train Accuracy: 0.750
Train Loss: 1.281, Train Accuracy: 0.800
Train Loss: 1.603, Train Accuracy: 0.500
Train Loss: 1.098, Train Accuracy: 0.600
Train Loss: 1.747, Train Accuracy: 0.750
Train Loss: 1.229, Train Accuracy: 0.600
Round 24
Train Loss: 1.148, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.500
Train Loss: 0.988, Train Accuracy: 0.600
Train Loss: 1.290, Train Accuracy: 0.600
Train Loss: 1.214, Train Accuracy: 0.750
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.574, Train Accuracy: 1.000
Train Loss: 1.124, Train Accuracy: 0.400
Train Loss: 1.819, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.500
Round 25
Train Loss: 1.549, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.600
Train Loss: 0.972, Train Accuracy: 0.600
Train Loss: 1.375, Train Accuracy: 0.800
Train Loss: 1.205, Train Accuracy: 0.875
Train Loss: 1.292, Train Accuracy: 0.800
Train Loss: 1.589, Train Accuracy: 1.000
Train Loss: 1.128, Train Accuracy: 0.600
Train Loss: 1.826, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.600
Round 26
Train Loss: 1.227, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.500
Train Loss: 0.973, Train Accuracy: 0.400
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.148, Train Accuracy: 0.750
Train Loss: 1.372, Train Accuracy: 0.800
Train Loss: 1.581, Train Accuracy: 0.500
Train Loss: 1.067, Train Accuracy: 0.200
Train Loss: 1.901, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.400
Round 27
Train Loss: 1.325, Train Accuracy: 0.750
Train Loss: 1.008, Train Accuracy: 0.600
Train Loss: 0.966, Train Accuracy: 0.400
Train Loss: 1.343, Train Accuracy: 0.800
Train Loss: 1.219, Train Accuracy: 0.750
Train Loss: 1.398, Train Accuracy: 0.800
Train Loss: 1.448, Train Accuracy: 0.750
Train Loss: 1.084, Train Accuracy: 0.600
Train Loss: 1.869, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.600
Round 28
Train Loss: 1.234, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 1.005, Train Accuracy: 0.400
Train Loss: 1.301, Train Accuracy: 0.800
Train Loss: 1.204, Train Accuracy: 0.750
Train Loss: 1.244, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 1.000
Train Loss: 1.096, Train Accuracy: 0.600
Train Loss: 1.867, Train Accuracy: 0.750
Train Loss: 1.148, Train Accuracy: 0.600
Round 29
Train Loss: 1.292, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.600
Train Loss: 0.974, Train Accuracy: 0.600
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.210, Train Accuracy: 0.625
Train Loss: 1.371, Train Accuracy: 0.800
Train Loss: 1.689, Train Accuracy: 1.000
Train Loss: 1.050, Train Accuracy: 0.400
Train Loss: 1.895, Train Accuracy: 1.000
Train Loss: 1.153, Train Accuracy: 0.500
Round 30
Train Loss: 1.215, Train Accuracy: 0.750
Train Loss: 0.998, Train Accuracy: 0.700
Train Loss: 0.953, Train Accuracy: 0.600
Train Loss: 1.474, Train Accuracy: 0.400
Train Loss: 1.162, Train Accuracy: 0.625
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.569, Train Accuracy: 1.000
Train Loss: 1.123, Train Accuracy: 0.600
Train Loss: 2.034, Train Accuracy: 1.000
Train Loss: 1.129, Train Accuracy: 0.500
Round 31
Train Loss: 1.198, Train Accuracy: 0.750
Train Loss: 1.009, Train Accuracy: 0.500
Train Loss: 0.965, Train Accuracy: 0.600
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.233, Train Accuracy: 0.500
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.490, Train Accuracy: 1.000
Train Loss: 1.151, Train Accuracy: 0.600
Train Loss: 1.915, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.700
Round 32
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.700
Train Loss: 0.969, Train Accuracy: 0.400
Train Loss: 1.325, Train Accuracy: 0.600
Train Loss: 1.187, Train Accuracy: 0.750
Train Loss: 1.247, Train Accuracy: 0.800
Train Loss: 1.556, Train Accuracy: 1.000
Train Loss: 1.167, Train Accuracy: 0.600
Train Loss: 1.890, Train Accuracy: 0.750
Train Loss: 1.125, Train Accuracy: 0.800
Round 33
Train Loss: 1.354, Train Accuracy: 1.000
Train Loss: 0.998, Train Accuracy: 0.500
Train Loss: 0.939, Train Accuracy: 0.600
Train Loss: 1.339, Train Accuracy: 0.600
Train Loss: 1.144, Train Accuracy: 0.750
Train Loss: 1.249, Train Accuracy: 0.800
Train Loss: 1.406, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.600
Train Loss: 1.938, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.500
Round 34
Train Loss: 1.165, Train Accuracy: 0.750
Train Loss: 0.989, Train Accuracy: 0.500
Train Loss: 0.930, Train Accuracy: 0.600
Train Loss: 1.461, Train Accuracy: 1.000
Train Loss: 1.213, Train Accuracy: 0.500
Train Loss: 1.359, Train Accuracy: 0.800
Train Loss: 1.535, Train Accuracy: 1.000
Train Loss: 1.039, Train Accuracy: 0.600
Train Loss: 1.894, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.600
Round 35
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.400
Train Loss: 0.929, Train Accuracy: 0.200
Train Loss: 1.305, Train Accuracy: 1.000
Train Loss: 1.164, Train Accuracy: 0.625
Train Loss: 1.285, Train Accuracy: 0.800
Train Loss: 1.665, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.400
Train Loss: 1.762, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.700
Round 36
Train Loss: 1.147, Train Accuracy: 0.750
Train Loss: 0.972, Train Accuracy: 0.700
Train Loss: 0.929, Train Accuracy: 0.800
Train Loss: 1.346, Train Accuracy: 1.000
Train Loss: 1.160, Train Accuracy: 0.875
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.598, Train Accuracy: 0.500
Train Loss: 1.078, Train Accuracy: 0.800
Train Loss: 1.776, Train Accuracy: 0.750
Train Loss: 1.115, Train Accuracy: 0.600
Round 37
Train Loss: 1.211, Train Accuracy: 0.750
Train Loss: 0.979, Train Accuracy: 0.800
Train Loss: 0.902, Train Accuracy: 0.600
Train Loss: 1.315, Train Accuracy: 1.000
Train Loss: 1.245, Train Accuracy: 0.375
Train Loss: 1.337, Train Accuracy: 1.000
Train Loss: 1.488, Train Accuracy: 0.750
Train Loss: 1.046, Train Accuracy: 0.600
Train Loss: 1.918, Train Accuracy: 0.750
Train Loss: 1.100, Train Accuracy: 0.500
Round 38
Train Loss: 1.283, Train Accuracy: 0.750
Train Loss: 0.996, Train Accuracy: 0.300
Train Loss: 0.928, Train Accuracy: 0.600
Train Loss: 1.450, Train Accuracy: 1.000
Train Loss: 1.222, Train Accuracy: 0.750
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.643, Train Accuracy: 0.500
Train Loss: 1.083, Train Accuracy: 0.400
Train Loss: 1.831, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.700
Round 39
Train Loss: 1.293, Train Accuracy: 0.750
Train Loss: 0.969, Train Accuracy: 0.600
Train Loss: 0.910, Train Accuracy: 0.400
Train Loss: 1.459, Train Accuracy: 0.800
Train Loss: 1.182, Train Accuracy: 0.625
Train Loss: 1.292, Train Accuracy: 0.800
Train Loss: 1.505, Train Accuracy: 1.000
Train Loss: 0.984, Train Accuracy: 0.800
Train Loss: 1.796, Train Accuracy: 0.750
Train Loss: 1.189, Train Accuracy: 0.600
Round 40
Train Loss: 1.111, Train Accuracy: 0.750
Train Loss: 0.976, Train Accuracy: 0.600
Train Loss: 0.944, Train Accuracy: 0.600
Train Loss: 1.333, Train Accuracy: 1.000
Train Loss: 1.240, Train Accuracy: 0.750
Train Loss: 1.469, Train Accuracy: 1.000
Train Loss: 1.720, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.600
Train Loss: 1.958, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.700
Round 41
Train Loss: 1.258, Train Accuracy: 0.750
Train Loss: 0.981, Train Accuracy: 0.500
Train Loss: 0.902, Train Accuracy: 0.400
Train Loss: 1.429, Train Accuracy: 1.000
Train Loss: 1.332, Train Accuracy: 0.750
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.522, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.600
Train Loss: 1.978, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.700
Round 42
Train Loss: 1.281, Train Accuracy: 1.000
Train Loss: 0.948, Train Accuracy: 0.700
Train Loss: 0.907, Train Accuracy: 0.800
Train Loss: 1.299, Train Accuracy: 1.000
Train Loss: 1.206, Train Accuracy: 0.500
Train Loss: 1.231, Train Accuracy: 0.800
Train Loss: 1.504, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 1.000
Train Loss: 1.909, Train Accuracy: 0.750
Train Loss: 1.132, Train Accuracy: 0.800
Round 43
Train Loss: 1.130, Train Accuracy: 0.750
Train Loss: 0.965, Train Accuracy: 0.600
Train Loss: 0.905, Train Accuracy: 0.400
Train Loss: 1.393, Train Accuracy: 1.000
Train Loss: 1.104, Train Accuracy: 0.750
Train Loss: 1.283, Train Accuracy: 0.800
Train Loss: 1.624, Train Accuracy: 1.000
Train Loss: 1.156, Train Accuracy: 0.600
Train Loss: 2.031, Train Accuracy: 1.000
Train Loss: 1.133, Train Accuracy: 0.900
Round 44
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 0.965, Train Accuracy: 0.800
Train Loss: 0.884, Train Accuracy: 0.400
Train Loss: 1.459, Train Accuracy: 0.800
Train Loss: 1.176, Train Accuracy: 0.625
Train Loss: 1.185, Train Accuracy: 0.800
Train Loss: 1.808, Train Accuracy: 0.500
Train Loss: 1.091, Train Accuracy: 0.800
Train Loss: 1.949, Train Accuracy: 1.000
Train Loss: 1.023, Train Accuracy: 0.800
Round 45
Train Loss: 1.169, Train Accuracy: 0.750
Train Loss: 0.936, Train Accuracy: 0.500
Train Loss: 0.976, Train Accuracy: 0.600
Train Loss: 1.271, Train Accuracy: 1.000
Train Loss: 1.124, Train Accuracy: 0.500
Train Loss: 1.309, Train Accuracy: 1.000
Train Loss: 1.507, Train Accuracy: 1.000
Train Loss: 1.071, Train Accuracy: 1.000
Train Loss: 1.808, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.700
Round 46
Train Loss: 1.141, Train Accuracy: 0.750
Train Loss: 0.937, Train Accuracy: 0.800
Train Loss: 0.883, Train Accuracy: 0.600
Train Loss: 1.613, Train Accuracy: 0.800
Train Loss: 1.235, Train Accuracy: 0.625
Train Loss: 1.254, Train Accuracy: 0.800
Train Loss: 1.565, Train Accuracy: 1.000
Train Loss: 1.154, Train Accuracy: 0.600
Train Loss: 1.974, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.900
Round 47
Train Loss: 1.244, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.500
Train Loss: 0.858, Train Accuracy: 0.600
Train Loss: 1.401, Train Accuracy: 0.800
Train Loss: 1.170, Train Accuracy: 0.250
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.492, Train Accuracy: 1.000
Train Loss: 1.031, Train Accuracy: 0.800
Train Loss: 2.002, Train Accuracy: 0.750
Train Loss: 1.102, Train Accuracy: 0.400
Round 48
Train Loss: 1.146, Train Accuracy: 0.500
Train Loss: 0.966, Train Accuracy: 0.700
Train Loss: 0.947, Train Accuracy: 0.800
Train Loss: 1.268, Train Accuracy: 1.000
Train Loss: 1.026, Train Accuracy: 0.250
Train Loss: 1.317, Train Accuracy: 1.000
Train Loss: 1.726, Train Accuracy: 0.750

(FLClient pid=2871540) 2025-04-11 09:14:13,236 - INFO - Epoch   2| Train Loss: 0.481| Train Accuracy: 0.750 [repeated 357x across cluster]
(FLClient pid=2871540) 2025-04-11 09:14:13,244 - INFO - Epoch   2| Validation Loss: 1.680, Validation Accuracy: 0.442 [repeated 119x across cluster]

Results saved to Central_results4/Pubmed_adjacency_GCN/results_Pubmed_adjacency_GCN.txt

Running experiment with data_loading_option: diffusion, model_type: GCN
DEVICE: cuda
Data loading option is diffusion
Model type is GCN

2025-04-11 09:14:16,712	INFO worker.py:1816 -- Started a local Ray instance.

data_loading_option: diffusion
Data loaded
Device is cuda
Pubmed()
10

(FLClient pid=2872539) 2025-04-11 09:14:42,410 - INFO - Epoch   0| Train Loss: 1.103| Train Accuracy: 0.250
(FLClient pid=2872539) 2025-04-11 09:14:42,414 - INFO - Epoch   1| Train Loss: 0.891| Train Accuracy: 0.750
(FLClient pid=2872539) 2025-04-11 09:14:42,417 - INFO - Epoch   2| Train Loss: 0.696| Train Accuracy: 0.750
(FLClient pid=2872539) 2025-04-11 09:14:42,425 - INFO - Epoch   2| Validation Loss: 1.342, Validation Accuracy: 0.295
(FLClient pid=2872539) 2025-04-11 09:14:47,529 - INFO - Epoch   2| Train Loss: 0.732| Train Accuracy: 0.750 [repeated 360x across cluster]
(FLClient pid=2872539) 2025-04-11 09:14:47,537 - INFO - Epoch   2| Validation Loss: 1.232, Validation Accuracy: 0.295 [repeated 120x across cluster]
(FLClient pid=2872539) 2025-04-11 09:14:52,606 - INFO - Epoch   0| Train Loss: 1.212| Train Accuracy: 0.500 [repeated 448x across cluster]
(FLClient pid=2872545) 2025-04-11 09:14:52,296 - INFO - Epoch   2| Validation Loss: 1.150, Validation Accuracy: 0.375 [repeated 149x across cluster]
(FLClient pid=2872539) 2025-04-11 09:14:57,769 - INFO - Epoch   2| Train Loss: 0.602| Train Accuracy: 0.750 [repeated 452x across cluster]
(FLClient pid=2872539) 2025-04-11 09:14:57,776 - INFO - Epoch   2| Validation Loss: 1.331, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2872539) 2025-04-11 09:15:02,874 - INFO - Epoch   1| Train Loss: 0.570| Train Accuracy: 0.750 [repeated 449x across cluster]
(FLClient pid=2872545) 2025-04-11 09:15:02,553 - INFO - Epoch   2| Validation Loss: 1.416, Validation Accuracy: 0.156 [repeated 149x across cluster]
(FLClient pid=2872539) 2025-04-11 09:15:08,092 - INFO - Epoch   2| Train Loss: 0.412| Train Accuracy: 1.000 [repeated 451x across cluster]
(FLClient pid=2872539) 2025-04-11 09:15:08,100 - INFO - Epoch   2| Validation Loss: 1.154, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2872539) 2025-04-11 09:15:13,243 - INFO - Epoch   2| Train Loss: 0.507| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2872539) 2025-04-11 09:15:13,250 - INFO - Epoch   2| Validation Loss: 1.132, Validation Accuracy: 0.295 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.342, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.055, Train Accuracy: 0.400
Train Loss: 1.204, Train Accuracy: 0.600
Train Loss: 1.199, Train Accuracy: 0.625
Train Loss: 1.236, Train Accuracy: 0.800
Train Loss: 1.334, Train Accuracy: 0.500
Train Loss: 1.128, Train Accuracy: 0.200
Train Loss: 1.461, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.400
Round 2
Train Loss: 1.297, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.049, Train Accuracy: 0.400
Train Loss: 1.250, Train Accuracy: 0.600
Train Loss: 1.211, Train Accuracy: 0.625
Train Loss: 1.222, Train Accuracy: 0.800
Train Loss: 1.354, Train Accuracy: 0.500
Train Loss: 1.133, Train Accuracy: 0.400
Train Loss: 1.581, Train Accuracy: 0.750
Train Loss: 1.221, Train Accuracy: 0.600
Round 3
Train Loss: 1.363, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.311, Train Accuracy: 0.600
Train Loss: 1.220, Train Accuracy: 0.625
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.383, Train Accuracy: 0.250
Train Loss: 1.167, Train Accuracy: 0.400
Train Loss: 1.594, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.600
Round 4
Train Loss: 1.289, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.600
Train Loss: 1.038, Train Accuracy: 0.400
Train Loss: 1.249, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.625
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.367, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.400
Train Loss: 1.781, Train Accuracy: 0.750
Train Loss: 1.199, Train Accuracy: 0.500
Round 5
Train Loss: 1.318, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.047, Train Accuracy: 0.400
Train Loss: 1.274, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.413, Train Accuracy: 0.250
Train Loss: 1.175, Train Accuracy: 0.400
Train Loss: 1.652, Train Accuracy: 0.750
Train Loss: 1.193, Train Accuracy: 0.500
Round 6
Train Loss: 1.374, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.500
Train Loss: 1.033, Train Accuracy: 0.400
Train Loss: 1.310, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 0.625
Train Loss: 1.229, Train Accuracy: 0.800
Train Loss: 1.412, Train Accuracy: 0.500
Train Loss: 1.212, Train Accuracy: 0.400
Train Loss: 1.770, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.400
Round 7
Train Loss: 1.282, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.034, Train Accuracy: 0.400
Train Loss: 1.368, Train Accuracy: 0.600
Train Loss: 1.255, Train Accuracy: 0.625
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.410, Train Accuracy: 0.000
Train Loss: 1.203, Train Accuracy: 0.600
Train Loss: 1.751, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.300
Round 8
Train Loss: 1.342, Train Accuracy: 0.750
Train Loss: 1.084, Train Accuracy: 0.700
Train Loss: 1.026, Train Accuracy: 0.400
Train Loss: 1.349, Train Accuracy: 0.600
Train Loss: 1.269, Train Accuracy: 0.625
Train Loss: 1.229, Train Accuracy: 0.800
Train Loss: 1.445, Train Accuracy: 0.500
Train Loss: 1.162, Train Accuracy: 0.600
Train Loss: 1.816, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.600
Round 9
Train Loss: 1.382, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 1.351, Train Accuracy: 0.400
Train Loss: 1.249, Train Accuracy: 0.750
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.456, Train Accuracy: 0.500
Train Loss: 1.169, Train Accuracy: 0.200
Train Loss: 1.787, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.500
Round 10
Train Loss: 1.362, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.600
Train Loss: 1.024, Train Accuracy: 0.400
Train Loss: 1.350, Train Accuracy: 0.600
Train Loss: 1.217, Train Accuracy: 0.625
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.461, Train Accuracy: 0.250
Train Loss: 1.243, Train Accuracy: 0.600
Train Loss: 1.765, Train Accuracy: 0.750
Train Loss: 1.223, Train Accuracy: 0.600
Round 11
Train Loss: 1.482, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.400
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 1.366, Train Accuracy: 0.800
Train Loss: 1.234, Train Accuracy: 0.625
Train Loss: 1.287, Train Accuracy: 0.800
Train Loss: 1.481, Train Accuracy: 0.500
Train Loss: 1.156, Train Accuracy: 0.200
Train Loss: 1.794, Train Accuracy: 0.750
Train Loss: 1.210, Train Accuracy: 0.400
Round 12
Train Loss: 1.297, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.027, Train Accuracy: 0.400
Train Loss: 1.410, Train Accuracy: 0.600
Train Loss: 1.243, Train Accuracy: 0.625
Train Loss: 1.380, Train Accuracy: 0.800
Train Loss: 1.501, Train Accuracy: 0.500
Train Loss: 1.200, Train Accuracy: 0.800
Train Loss: 1.774, Train Accuracy: 0.750
Train Loss: 1.208, Train Accuracy: 0.600
Round 13
Train Loss: 1.232, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.600
Train Loss: 1.019, Train Accuracy: 0.200
Train Loss: 1.439, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 0.500
Train Loss: 1.158, Train Accuracy: 0.400
Train Loss: 1.942, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.400
Round 14
Train Loss: 1.412, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.600
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.371, Train Accuracy: 0.600
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.343, Train Accuracy: 0.800
Train Loss: 1.487, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 1.000
Train Loss: 1.961, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.600
Round 15
Train Loss: 1.333, Train Accuracy: 0.750
Train Loss: 1.062, Train Accuracy: 0.500
Train Loss: 1.009, Train Accuracy: 0.400
Train Loss: 1.410, Train Accuracy: 0.600
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.282, Train Accuracy: 0.800
Train Loss: 1.504, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.400
Train Loss: 1.807, Train Accuracy: 0.750
Train Loss: 1.192, Train Accuracy: 0.600
Round 16
Train Loss: 1.232, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.500
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.439, Train Accuracy: 0.800
Train Loss: 1.239, Train Accuracy: 0.750
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.585, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.400
Train Loss: 1.852, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.500
Round 17
Train Loss: 1.248, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.500
Train Loss: 1.007, Train Accuracy: 0.400
Train Loss: 1.362, Train Accuracy: 0.600
Train Loss: 1.240, Train Accuracy: 0.625
Train Loss: 1.229, Train Accuracy: 0.800
Train Loss: 1.480, Train Accuracy: 0.000
Train Loss: 1.103, Train Accuracy: 0.400
Train Loss: 1.954, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.600
Round 18
Train Loss: 1.188, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.600
Train Loss: 1.005, Train Accuracy: 0.400
Train Loss: 1.407, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.750
Train Loss: 1.255, Train Accuracy: 0.800
Train Loss: 1.497, Train Accuracy: 0.500
Train Loss: 1.137, Train Accuracy: 0.600
Train Loss: 1.918, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.500
Round 19
Train Loss: 1.219, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.800
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.431, Train Accuracy: 0.800
Train Loss: 1.247, Train Accuracy: 0.625
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.471, Train Accuracy: 0.750
Train Loss: 1.126, Train Accuracy: 0.400
Train Loss: 1.692, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.400
Round 20
Train Loss: 1.397, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.400
Train Loss: 1.004, Train Accuracy: 0.600
Train Loss: 1.382, Train Accuracy: 0.800
Train Loss: 1.235, Train Accuracy: 0.625
Train Loss: 1.292, Train Accuracy: 0.800
Train Loss: 1.518, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.800
Train Loss: 1.813, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.500
Round 21
Train Loss: 1.364, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.600
Train Loss: 0.995, Train Accuracy: 0.400
Train Loss: 1.433, Train Accuracy: 0.800
Train Loss: 1.190, Train Accuracy: 0.750
Train Loss: 1.347, Train Accuracy: 0.800
Train Loss: 1.492, Train Accuracy: 0.750
Train Loss: 1.214, Train Accuracy: 0.400
Train Loss: 1.757, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.400
Round 22
Train Loss: 1.223, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.600
Train Loss: 1.010, Train Accuracy: 0.200
Train Loss: 1.435, Train Accuracy: 1.000
Train Loss: 1.258, Train Accuracy: 0.625
Train Loss: 1.382, Train Accuracy: 0.800
Train Loss: 1.589, Train Accuracy: 0.500
Train Loss: 1.119, Train Accuracy: 0.400
Train Loss: 2.002, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.300
Round 23
Train Loss: 1.293, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.500
Train Loss: 1.003, Train Accuracy: 0.400
Train Loss: 1.456, Train Accuracy: 0.800
Train Loss: 1.256, Train Accuracy: 0.750
Train Loss: 1.266, Train Accuracy: 0.800
Train Loss: 1.616, Train Accuracy: 0.750
Train Loss: 1.219, Train Accuracy: 0.600
Train Loss: 1.826, Train Accuracy: 0.750
Train Loss: 1.205, Train Accuracy: 0.400
Round 24
Train Loss: 1.310, Train Accuracy: 0.750
Train Loss: 1.020, Train Accuracy: 0.400
Train Loss: 0.990, Train Accuracy: 0.400
Train Loss: 1.580, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.750
Train Loss: 1.307, Train Accuracy: 0.800
Train Loss: 1.455, Train Accuracy: 0.750
Train Loss: 1.139, Train Accuracy: 0.400
Train Loss: 2.142, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.600
Round 25
Train Loss: 1.358, Train Accuracy: 0.750
Train Loss: 1.040, Train Accuracy: 0.600
Train Loss: 1.019, Train Accuracy: 0.400
Train Loss: 1.417, Train Accuracy: 0.600
Train Loss: 1.203, Train Accuracy: 0.625
Train Loss: 1.388, Train Accuracy: 0.800
Train Loss: 1.583, Train Accuracy: 1.000
Train Loss: 1.308, Train Accuracy: 0.600
Train Loss: 1.818, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.500
Round 26
Train Loss: 1.278, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.500
Train Loss: 0.971, Train Accuracy: 0.400
Train Loss: 1.433, Train Accuracy: 0.800
Train Loss: 1.251, Train Accuracy: 0.625
Train Loss: 1.358, Train Accuracy: 0.800
Train Loss: 1.527, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.400
Train Loss: 1.919, Train Accuracy: 0.750
Train Loss: 1.132, Train Accuracy: 0.600
Round 27
Train Loss: 1.208, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.700
Train Loss: 0.971, Train Accuracy: 0.400
Train Loss: 1.326, Train Accuracy: 0.600
Train Loss: 1.258, Train Accuracy: 0.625
Train Loss: 1.273, Train Accuracy: 0.800
Train Loss: 1.511, Train Accuracy: 1.000
Train Loss: 1.205, Train Accuracy: 0.600
Train Loss: 2.103, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.700
Round 28
Train Loss: 1.448, Train Accuracy: 0.750
Train Loss: 1.005, Train Accuracy: 0.700
Train Loss: 0.980, Train Accuracy: 0.600
Train Loss: 1.357, Train Accuracy: 0.800
Train Loss: 1.182, Train Accuracy: 0.625
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.565, Train Accuracy: 0.500
Train Loss: 1.158, Train Accuracy: 0.600
Train Loss: 1.812, Train Accuracy: 0.500
Train Loss: 1.219, Train Accuracy: 0.600
Round 29
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.500
Train Loss: 0.969, Train Accuracy: 0.400
Train Loss: 1.427, Train Accuracy: 1.000
Train Loss: 1.231, Train Accuracy: 0.750
Train Loss: 1.427, Train Accuracy: 0.800
Train Loss: 1.554, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.400
Train Loss: 2.002, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.700
Round 30
Train Loss: 1.270, Train Accuracy: 0.750
Train Loss: 0.992, Train Accuracy: 0.700
Train Loss: 0.969, Train Accuracy: 0.400
Train Loss: 1.403, Train Accuracy: 0.800
Train Loss: 1.229, Train Accuracy: 0.625
Train Loss: 1.226, Train Accuracy: 0.800
Train Loss: 1.465, Train Accuracy: 0.500
Train Loss: 1.169, Train Accuracy: 0.600
Train Loss: 1.964, Train Accuracy: 0.750
Train Loss: 1.098, Train Accuracy: 0.600
Round 31
Train Loss: 1.236, Train Accuracy: 0.750
Train Loss: 0.992, Train Accuracy: 0.700
Train Loss: 0.969, Train Accuracy: 0.400
Train Loss: 1.407, Train Accuracy: 0.600
Train Loss: 1.149, Train Accuracy: 0.875
Train Loss: 1.427, Train Accuracy: 0.800
Train Loss: 1.642, Train Accuracy: 0.750
Train Loss: 1.227, Train Accuracy: 0.800
Train Loss: 2.020, Train Accuracy: 0.750
Train Loss: 1.110, Train Accuracy: 0.600
Round 32
Train Loss: 1.367, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.700
Train Loss: 0.961, Train Accuracy: 1.000
Train Loss: 1.419, Train Accuracy: 1.000
Train Loss: 1.158, Train Accuracy: 0.625
Train Loss: 1.403, Train Accuracy: 0.800
Train Loss: 1.583, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.400
Train Loss: 1.933, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.400
Round 33
Train Loss: 1.246, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.200
Train Loss: 0.948, Train Accuracy: 0.400
Train Loss: 1.389, Train Accuracy: 0.800
Train Loss: 1.162, Train Accuracy: 0.750
Train Loss: 1.385, Train Accuracy: 0.800
Train Loss: 1.517, Train Accuracy: 0.500
Train Loss: 1.190, Train Accuracy: 0.600
Train Loss: 2.035, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.500
Round 34
Train Loss: 1.171, Train Accuracy: 0.750
Train Loss: 0.978, Train Accuracy: 0.500
Train Loss: 0.940, Train Accuracy: 0.800
Train Loss: 1.271, Train Accuracy: 0.800
Train Loss: 1.189, Train Accuracy: 0.750
Train Loss: 1.414, Train Accuracy: 0.800
Train Loss: 1.455, Train Accuracy: 0.500
Train Loss: 1.107, Train Accuracy: 0.800
Train Loss: 1.847, Train Accuracy: 0.750
Train Loss: 1.083, Train Accuracy: 0.500
Round 35
Train Loss: 1.370, Train Accuracy: 0.750
Train Loss: 1.012, Train Accuracy: 0.600
Train Loss: 0.965, Train Accuracy: 0.400
Train Loss: 1.501, Train Accuracy: 0.600
Train Loss: 1.148, Train Accuracy: 0.750
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.515, Train Accuracy: 0.750
Train Loss: 1.175, Train Accuracy: 0.800
Train Loss: 1.826, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.600
Round 36
Train Loss: 1.389, Train Accuracy: 0.500
Train Loss: 0.972, Train Accuracy: 0.700
Train Loss: 0.959, Train Accuracy: 0.600
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.123, Train Accuracy: 0.750
Train Loss: 1.437, Train Accuracy: 0.800
Train Loss: 1.566, Train Accuracy: 1.000
Train Loss: 1.115, Train Accuracy: 0.400
Train Loss: 1.782, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.800
Round 37
Train Loss: 1.530, Train Accuracy: 0.750
Train Loss: 0.971, Train Accuracy: 0.700
Train Loss: 0.931, Train Accuracy: 0.800
Train Loss: 1.589, Train Accuracy: 0.400
Train Loss: 1.139, Train Accuracy: 0.750
Train Loss: 1.418, Train Accuracy: 0.800
Train Loss: 1.480, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.600
Train Loss: 2.145, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.400
Round 38
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 0.961, Train Accuracy: 0.700
Train Loss: 0.961, Train Accuracy: 0.600
Train Loss: 1.334, Train Accuracy: 1.000
Train Loss: 1.116, Train Accuracy: 0.500
Train Loss: 1.291, Train Accuracy: 0.800
Train Loss: 1.679, Train Accuracy: 0.500
Train Loss: 1.061, Train Accuracy: 0.800
Train Loss: 2.235, Train Accuracy: 1.000
Train Loss: 1.065, Train Accuracy: 0.600
Round 39
Train Loss: 1.168, Train Accuracy: 0.750
Train Loss: 0.992, Train Accuracy: 0.700
Train Loss: 0.922, Train Accuracy: 0.600
Train Loss: 1.463, Train Accuracy: 1.000
Train Loss: 1.214, Train Accuracy: 0.500
Train Loss: 1.364, Train Accuracy: 0.800
Train Loss: 1.555, Train Accuracy: 0.500
Train Loss: 1.080, Train Accuracy: 0.800
Train Loss: 1.926, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.400
Round 40
Train Loss: 1.262, Train Accuracy: 0.750
Train Loss: 0.980, Train Accuracy: 0.600
Train Loss: 0.941, Train Accuracy: 0.600
Train Loss: 1.467, Train Accuracy: 0.800
Train Loss: 1.210, Train Accuracy: 0.750
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.488, Train Accuracy: 0.750
Train Loss: 1.128, Train Accuracy: 0.600
Train Loss: 1.820, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.700
Round 41
Train Loss: 1.431, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 0.935, Train Accuracy: 0.800
Train Loss: 1.348, Train Accuracy: 1.000
Train Loss: 1.144, Train Accuracy: 0.500
Train Loss: 1.494, Train Accuracy: 1.000
Train Loss: 1.462, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.800
Train Loss: 2.282, Train Accuracy: 0.750
Train Loss: 1.295, Train Accuracy: 0.700
Round 42
Train Loss: 1.302, Train Accuracy: 0.750
Train Loss: 0.958, Train Accuracy: 0.400
Train Loss: 0.935, Train Accuracy: 1.000
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.204, Train Accuracy: 0.750
Train Loss: 1.419, Train Accuracy: 0.800
Train Loss: 1.520, Train Accuracy: 0.500
Train Loss: 1.146, Train Accuracy: 0.600
Train Loss: 2.119, Train Accuracy: 1.000
Train Loss: 1.213, Train Accuracy: 0.600
Round 43
Train Loss: 1.331, Train Accuracy: 0.750
Train Loss: 0.940, Train Accuracy: 0.600
Train Loss: 0.956, Train Accuracy: 0.800
Train Loss: 1.377, Train Accuracy: 1.000
Train Loss: 1.116, Train Accuracy: 0.875
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.681, Train Accuracy: 1.000
Train Loss: 1.052, Train Accuracy: 0.800
Train Loss: 2.270, Train Accuracy: 0.750
Train Loss: 1.296, Train Accuracy: 0.600
Round 44
Train Loss: 1.525, Train Accuracy: 0.750
Train Loss: 0.956, Train Accuracy: 0.700
Train Loss: 0.924, Train Accuracy: 0.600
Train Loss: 1.287, Train Accuracy: 1.000
Train Loss: 1.159, Train Accuracy: 0.375
Train Loss: 1.370, Train Accuracy: 0.800
Train Loss: 1.526, Train Accuracy: 1.000
Train Loss: 1.172, Train Accuracy: 0.800
Train Loss: 2.135, Train Accuracy: 0.750
Train Loss: 1.373, Train Accuracy: 0.700
Round 45
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 0.973, Train Accuracy: 0.300
Train Loss: 0.915, Train Accuracy: 0.600
Train Loss: 1.395, Train Accuracy: 1.000
Train Loss: 1.105, Train Accuracy: 0.875
Train Loss: 1.178, Train Accuracy: 0.800
Train Loss: 1.645, Train Accuracy: 0.750
Train Loss: 1.091, Train Accuracy: 0.800
Train Loss: 1.901, Train Accuracy: 1.000
Train Loss: 0.984, Train Accuracy: 0.500
Round 46
Train Loss: 1.173, Train Accuracy: 0.750
Train Loss: 0.960, Train Accuracy: 0.300
Train Loss: 0.994, Train Accuracy: 0.800
Train Loss: 1.497, Train Accuracy: 0.600
Train Loss: 1.184, Train Accuracy: 0.375
Train Loss: 1.291, Train Accuracy: 0.800
Train Loss: 1.449, Train Accuracy: 0.750
Train Loss: 1.146, Train Accuracy: 0.600
Train Loss: 2.253, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.600
Round 47
Train Loss: 1.159, Train Accuracy: 0.750
Train Loss: 0.996, Train Accuracy: 0.400
Train Loss: 0.926, Train Accuracy: 0.800
Train Loss: 1.490, Train Accuracy: 0.800
Train Loss: 1.153, Train Accuracy: 0.875
Train Loss: 1.207, Train Accuracy: 0.800
Train Loss: 1.839, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.600
Train Loss: 2.222, Train Accuracy: 1.000
Train Loss: 1.252, Train Accuracy: 0.900
Round 48
Train Loss: 1.232, Train Accuracy: 0.750
Train Loss: 0.940, Train Accuracy: 0.800
Train Loss: 0.934, Train Accuracy: 0.800
Train Loss: 1.208, Train Accuracy: 0.800
Train Loss: 1.117, Train Accuracy: 0.375
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.488, Train Accuracy: 1.000

(FLClient pid=2872546) 2025-04-11 09:15:44,173 - INFO - Epoch   2| Train Loss: 0.781| Train Accuracy: 0.750 [repeated 390x across cluster]
(FLClient pid=2872546) 2025-04-11 09:15:44,183 - INFO - Epoch   2| Validation Loss: 1.204, Validation Accuracy: 0.295 [repeated 130x across cluster]
(FLClient pid=2872541) 2025-04-11 09:15:49,301 - INFO - Epoch   2| Train Loss: 1.051| Train Accuracy: 0.500 [repeated 420x across cluster]
(FLClient pid=2872541) 2025-04-11 09:15:49,308 - INFO - Epoch   2| Validation Loss: 1.073, Validation Accuracy: 0.467 [repeated 140x across cluster]
(FLClient pid=2872541) 2025-04-11 09:15:54,368 - INFO - Epoch   1| Train Loss: 1.035| Train Accuracy: 0.500 [repeated 449x across cluster]
(FLClient pid=2872551) 2025-04-11 09:15:54,049 - INFO - Epoch   2| Validation Loss: 1.116, Validation Accuracy: 0.453 [repeated 149x across cluster]
(FLClient pid=2872541) 2025-04-11 09:15:59,451 - INFO - Epoch   2| Train Loss: 0.977| Train Accuracy: 0.400 [repeated 451x across cluster]
(FLClient pid=2872541) 2025-04-11 09:15:59,460 - INFO - Epoch   2| Validation Loss: 1.021, Validation Accuracy: 0.467 [repeated 151x across cluster]
(FLClient pid=2872541) 2025-04-11 09:16:04,544 - INFO - Epoch   2| Train Loss: 0.896| Train Accuracy: 0.400 [repeated 450x across cluster]
(FLClient pid=2872541) 2025-04-11 09:16:04,551 - INFO - Epoch   2| Validation Loss: 1.050, Validation Accuracy: 0.467 [repeated 150x across cluster]
(FLClient pid=2872541) 2025-04-11 09:16:09,642 - INFO - Epoch   2| Train Loss: 0.869| Train Accuracy: 0.400 [repeated 450x across cluster]
(FLClient pid=2872541) 2025-04-11 09:16:09,649 - INFO - Epoch   2| Validation Loss: 0.904, Validation Accuracy: 0.467 [repeated 150x across cluster]
(FLClient pid=2872541) 2025-04-11 09:16:14,747 - INFO - Epoch   2| Train Loss: 0.886| Train Accuracy: 0.400 [repeated 450x across cluster]
(FLClient pid=2872541) 2025-04-11 09:16:14,751 - INFO - Epoch   2| Validation Loss: 0.886, Validation Accuracy: 0.533 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.204, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.068, Train Accuracy: 0.400
Train Loss: 1.210, Train Accuracy: 0.600
Train Loss: 1.196, Train Accuracy: 0.625
Train Loss: 1.238, Train Accuracy: 0.800
Train Loss: 1.348, Train Accuracy: 0.500
Train Loss: 1.134, Train Accuracy: 0.200
Train Loss: 1.450, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.500
Round 2
Train Loss: 1.193, Train Accuracy: 0.750
Train Loss: 1.091, Train Accuracy: 0.500
Train Loss: 1.059, Train Accuracy: 0.400
Train Loss: 1.266, Train Accuracy: 0.600
Train Loss: 1.202, Train Accuracy: 0.625
Train Loss: 1.232, Train Accuracy: 0.800
Train Loss: 1.399, Train Accuracy: 0.500
Train Loss: 1.146, Train Accuracy: 0.200
Train Loss: 1.510, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.300
Round 3
Train Loss: 1.252, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 1.304, Train Accuracy: 0.600
Train Loss: 1.218, Train Accuracy: 0.625
Train Loss: 1.262, Train Accuracy: 0.800
Train Loss: 1.404, Train Accuracy: 0.500
Train Loss: 1.161, Train Accuracy: 0.800
Train Loss: 1.548, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.500
Round 4
Train Loss: 1.322, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.043, Train Accuracy: 0.400
Train Loss: 1.344, Train Accuracy: 0.600
Train Loss: 1.222, Train Accuracy: 0.625
Train Loss: 1.275, Train Accuracy: 0.800
Train Loss: 1.394, Train Accuracy: 0.500
Train Loss: 1.135, Train Accuracy: 0.400
Train Loss: 1.600, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 0.400
Round 5
Train Loss: 1.408, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.046, Train Accuracy: 0.400
Train Loss: 1.384, Train Accuracy: 0.600
Train Loss: 1.223, Train Accuracy: 0.625
Train Loss: 1.272, Train Accuracy: 0.800
Train Loss: 1.399, Train Accuracy: 0.250
Train Loss: 1.186, Train Accuracy: 0.600
Train Loss: 1.677, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.200
Round 6
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.200
Train Loss: 1.301, Train Accuracy: 0.600
Train Loss: 1.242, Train Accuracy: 0.625
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.422, Train Accuracy: 0.500
Train Loss: 1.215, Train Accuracy: 0.400
Train Loss: 1.826, Train Accuracy: 0.750
Train Loss: 1.217, Train Accuracy: 0.300
Round 7
Train Loss: 1.324, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.300
Train Loss: 1.030, Train Accuracy: 0.600
Train Loss: 1.309, Train Accuracy: 0.600
Train Loss: 1.230, Train Accuracy: 0.625
Train Loss: 1.240, Train Accuracy: 0.800
Train Loss: 1.490, Train Accuracy: 0.500
Train Loss: 1.183, Train Accuracy: 0.200
Train Loss: 1.709, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 0.400
Round 8
Train Loss: 1.278, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.431, Train Accuracy: 0.800
Train Loss: 1.210, Train Accuracy: 0.625
Train Loss: 1.292, Train Accuracy: 0.800
Train Loss: 1.422, Train Accuracy: 0.250
Train Loss: 1.169, Train Accuracy: 0.400
Train Loss: 1.864, Train Accuracy: 0.750
Train Loss: 1.207, Train Accuracy: 0.600
Round 9
Train Loss: 1.348, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.600
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.392, Train Accuracy: 0.600
Train Loss: 1.264, Train Accuracy: 0.625
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.429, Train Accuracy: 0.500
Train Loss: 1.170, Train Accuracy: 0.600
Train Loss: 1.772, Train Accuracy: 0.750
Train Loss: 1.192, Train Accuracy: 0.600
Round 10
Train Loss: 1.330, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.026, Train Accuracy: 0.200
Train Loss: 1.358, Train Accuracy: 0.600
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.329, Train Accuracy: 0.800
Train Loss: 1.397, Train Accuracy: 0.250
Train Loss: 1.166, Train Accuracy: 0.400
Train Loss: 1.879, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.500
Round 11
Train Loss: 1.323, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.600
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 1.402, Train Accuracy: 0.600
Train Loss: 1.262, Train Accuracy: 0.625
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.447, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.800
Train Loss: 1.826, Train Accuracy: 0.750
Train Loss: 1.190, Train Accuracy: 0.200
Round 12
Train Loss: 1.400, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Train Loss: 1.021, Train Accuracy: 0.400
Train Loss: 1.400, Train Accuracy: 0.600
Train Loss: 1.218, Train Accuracy: 0.625
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.539, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.200
Train Loss: 1.817, Train Accuracy: 0.750
Train Loss: 1.217, Train Accuracy: 0.500
Round 13
Train Loss: 1.321, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.400
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 1.365, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.268, Train Accuracy: 0.800
Train Loss: 1.504, Train Accuracy: 0.500
Train Loss: 1.199, Train Accuracy: 0.600
Train Loss: 1.763, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.400
Round 14
Train Loss: 1.421, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.021, Train Accuracy: 0.400
Train Loss: 1.400, Train Accuracy: 0.600
Train Loss: 1.257, Train Accuracy: 0.625
Train Loss: 1.329, Train Accuracy: 0.800
Train Loss: 1.463, Train Accuracy: 0.500
Train Loss: 1.147, Train Accuracy: 0.600
Train Loss: 1.896, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.300
Round 15
Train Loss: 1.251, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.019, Train Accuracy: 0.400
Train Loss: 1.354, Train Accuracy: 0.600
Train Loss: 1.221, Train Accuracy: 0.625
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.485, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.600
Train Loss: 1.903, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.500
Round 16
Train Loss: 1.212, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.500
Train Loss: 1.019, Train Accuracy: 0.600
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.204, Train Accuracy: 0.625
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.509, Train Accuracy: 0.750
Train Loss: 1.132, Train Accuracy: 0.600
Train Loss: 1.879, Train Accuracy: 0.750
Train Loss: 1.226, Train Accuracy: 0.800
Round 17
Train Loss: 1.384, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.600
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 1.427, Train Accuracy: 0.600
Train Loss: 1.206, Train Accuracy: 0.625
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.546, Train Accuracy: 0.250
Train Loss: 1.239, Train Accuracy: 0.400
Train Loss: 1.826, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 0.400
Round 18
Train Loss: 1.193, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.500
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.397, Train Accuracy: 0.800
Train Loss: 1.243, Train Accuracy: 0.625
Train Loss: 1.371, Train Accuracy: 0.800
Train Loss: 1.522, Train Accuracy: 0.500
Train Loss: 1.194, Train Accuracy: 0.400
Train Loss: 1.769, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.400
Round 19
Train Loss: 1.282, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.600
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.426, Train Accuracy: 0.600
Train Loss: 1.234, Train Accuracy: 0.750
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.482, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.400
Train Loss: 1.926, Train Accuracy: 0.750
Train Loss: 1.193, Train Accuracy: 0.800
Round 20
Train Loss: 1.416, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.600
Train Loss: 0.998, Train Accuracy: 0.400
Train Loss: 1.345, Train Accuracy: 0.800
Train Loss: 1.227, Train Accuracy: 0.625
Train Loss: 1.358, Train Accuracy: 0.800
Train Loss: 1.433, Train Accuracy: 0.500
Train Loss: 1.151, Train Accuracy: 0.600
Train Loss: 1.789, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.400
Round 21
Train Loss: 1.356, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.500
Train Loss: 1.001, Train Accuracy: 0.400
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.401, Train Accuracy: 0.800
Train Loss: 1.491, Train Accuracy: 0.750
Train Loss: 1.109, Train Accuracy: 0.400
Train Loss: 1.855, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.400
Round 22
Train Loss: 1.207, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 1.328, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.485, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.600
Train Loss: 2.080, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.700
Round 23
Train Loss: 1.340, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.700
Train Loss: 1.002, Train Accuracy: 0.400
Train Loss: 1.362, Train Accuracy: 0.800
Train Loss: 1.209, Train Accuracy: 0.500
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.550, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.400
Train Loss: 1.932, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.700
Round 24
Train Loss: 1.345, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.600
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 1.434, Train Accuracy: 0.800
Train Loss: 1.187, Train Accuracy: 0.625
Train Loss: 1.415, Train Accuracy: 0.800
Train Loss: 1.474, Train Accuracy: 1.000
Train Loss: 1.157, Train Accuracy: 0.600
Train Loss: 2.051, Train Accuracy: 0.750
Train Loss: 1.112, Train Accuracy: 0.500
Round 25
Train Loss: 1.320, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.500
Train Loss: 0.992, Train Accuracy: 0.400
Train Loss: 1.424, Train Accuracy: 0.600
Train Loss: 1.157, Train Accuracy: 0.750
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.532, Train Accuracy: 0.500
Train Loss: 1.148, Train Accuracy: 0.800
Train Loss: 2.042, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.600
Round 26
Train Loss: 1.196, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.600
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 1.471, Train Accuracy: 0.800
Train Loss: 1.178, Train Accuracy: 0.750
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.462, Train Accuracy: 0.500
Train Loss: 1.096, Train Accuracy: 0.600
Train Loss: 1.903, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.700
Round 27
Train Loss: 1.193, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.600
Train Loss: 0.980, Train Accuracy: 0.600
Train Loss: 1.408, Train Accuracy: 1.000
Train Loss: 1.170, Train Accuracy: 0.750
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.606, Train Accuracy: 1.000
Train Loss: 1.076, Train Accuracy: 0.800
Train Loss: 1.960, Train Accuracy: 0.750
Train Loss: 1.104, Train Accuracy: 0.400
Round 28
Train Loss: 1.252, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.500
Train Loss: 0.979, Train Accuracy: 0.400
Train Loss: 1.464, Train Accuracy: 0.800
Train Loss: 1.146, Train Accuracy: 0.750
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.800
Train Loss: 1.875, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.500
Round 29
Train Loss: 1.251, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.500
Train Loss: 0.996, Train Accuracy: 0.400
Train Loss: 1.348, Train Accuracy: 0.800
Train Loss: 1.209, Train Accuracy: 0.750
Train Loss: 1.377, Train Accuracy: 0.800
Train Loss: 1.423, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.600
Train Loss: 1.796, Train Accuracy: 0.750
Train Loss: 1.116, Train Accuracy: 0.700
Round 30
Train Loss: 1.272, Train Accuracy: 0.750
Train Loss: 1.005, Train Accuracy: 0.600
Train Loss: 0.970, Train Accuracy: 0.400
Train Loss: 1.281, Train Accuracy: 0.800
Train Loss: 1.198, Train Accuracy: 0.625
Train Loss: 1.385, Train Accuracy: 0.800
Train Loss: 1.543, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.600
Train Loss: 1.966, Train Accuracy: 0.750
Train Loss: 1.192, Train Accuracy: 0.800
Round 31
Train Loss: 1.343, Train Accuracy: 0.750
Train Loss: 1.013, Train Accuracy: 0.700
Train Loss: 0.984, Train Accuracy: 0.400
Train Loss: 1.459, Train Accuracy: 0.800
Train Loss: 1.183, Train Accuracy: 0.750
Train Loss: 1.357, Train Accuracy: 0.800
Train Loss: 1.445, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.600
Train Loss: 2.174, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.600
Round 32
Train Loss: 1.283, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 0.994, Train Accuracy: 0.600
Train Loss: 1.385, Train Accuracy: 0.800
Train Loss: 1.111, Train Accuracy: 0.750
Train Loss: 1.375, Train Accuracy: 0.800
Train Loss: 1.629, Train Accuracy: 0.500
Train Loss: 1.077, Train Accuracy: 0.600
Train Loss: 1.894, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.600
Round 33
Train Loss: 1.491, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.400
Train Loss: 0.989, Train Accuracy: 0.800
Train Loss: 1.410, Train Accuracy: 0.800
Train Loss: 1.178, Train Accuracy: 0.625
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.526, Train Accuracy: 1.000
Train Loss: 1.131, Train Accuracy: 0.600
Train Loss: 2.034, Train Accuracy: 1.000
Train Loss: 1.149, Train Accuracy: 0.300
Round 34
Train Loss: 1.282, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.800
Train Loss: 0.960, Train Accuracy: 0.400
Train Loss: 1.324, Train Accuracy: 1.000
Train Loss: 1.167, Train Accuracy: 0.750
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.584, Train Accuracy: 1.000
Train Loss: 1.090, Train Accuracy: 0.800
Train Loss: 2.002, Train Accuracy: 0.750
Train Loss: 1.146, Train Accuracy: 0.800
Round 35
Train Loss: 1.317, Train Accuracy: 0.500
Train Loss: 1.015, Train Accuracy: 0.600
Train Loss: 0.965, Train Accuracy: 0.400
Train Loss: 1.494, Train Accuracy: 1.000
Train Loss: 1.192, Train Accuracy: 0.500
Train Loss: 1.435, Train Accuracy: 0.800
Train Loss: 1.508, Train Accuracy: 0.500
Train Loss: 1.170, Train Accuracy: 0.600
Train Loss: 2.079, Train Accuracy: 0.750
Train Loss: 1.106, Train Accuracy: 0.500
Round 36
Train Loss: 1.220, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.600
Train Loss: 0.998, Train Accuracy: 0.400
Train Loss: 1.268, Train Accuracy: 0.800
Train Loss: 1.163, Train Accuracy: 0.625
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.494, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 1.985, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.600
Round 37
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.700
Train Loss: 0.940, Train Accuracy: 0.800
Train Loss: 1.420, Train Accuracy: 0.800
Train Loss: 1.223, Train Accuracy: 0.375
Train Loss: 1.391, Train Accuracy: 0.800
Train Loss: 1.434, Train Accuracy: 1.000
Train Loss: 1.090, Train Accuracy: 0.800
Train Loss: 1.780, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.500
Round 38
Train Loss: 1.256, Train Accuracy: 0.750
Train Loss: 0.996, Train Accuracy: 0.800
Train Loss: 0.983, Train Accuracy: 0.800
Train Loss: 1.400, Train Accuracy: 1.000
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.761, Train Accuracy: 0.750
Train Loss: 1.062, Train Accuracy: 0.600
Train Loss: 1.984, Train Accuracy: 0.750
Train Loss: 1.218, Train Accuracy: 0.500
Round 39
Train Loss: 1.476, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.500
Train Loss: 0.933, Train Accuracy: 0.200
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.148, Train Accuracy: 0.750
Train Loss: 1.432, Train Accuracy: 0.800
Train Loss: 1.484, Train Accuracy: 1.000
Train Loss: 1.081, Train Accuracy: 0.600
Train Loss: 2.134, Train Accuracy: 0.750
Train Loss: 1.292, Train Accuracy: 0.500
Round 40
Train Loss: 1.238, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.500
Train Loss: 0.929, Train Accuracy: 0.600
Train Loss: 1.396, Train Accuracy: 1.000
Train Loss: 1.205, Train Accuracy: 0.875
Train Loss: 1.345, Train Accuracy: 0.800
Train Loss: 1.420, Train Accuracy: 0.750
Train Loss: 1.189, Train Accuracy: 0.600
Train Loss: 1.888, Train Accuracy: 0.750
Train Loss: 1.050, Train Accuracy: 0.600
Round 41
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.700
Train Loss: 0.935, Train Accuracy: 0.600
Train Loss: 1.256, Train Accuracy: 0.800
Train Loss: 1.152, Train Accuracy: 0.750
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.413, Train Accuracy: 1.000
Train Loss: 0.982, Train Accuracy: 0.200
Train Loss: 1.678, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.700
Round 42
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 0.960, Train Accuracy: 0.600
Train Loss: 0.922, Train Accuracy: 0.600
Train Loss: 1.283, Train Accuracy: 1.000
Train Loss: 1.266, Train Accuracy: 0.625
Train Loss: 1.386, Train Accuracy: 0.800
Train Loss: 1.659, Train Accuracy: 0.500
Train Loss: 1.014, Train Accuracy: 0.800
Train Loss: 1.870, Train Accuracy: 0.750
Train Loss: 1.293, Train Accuracy: 0.600
Round 43
Train Loss: 1.386, Train Accuracy: 0.750
Train Loss: 0.968, Train Accuracy: 0.200
Train Loss: 0.907, Train Accuracy: 0.600
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.133, Train Accuracy: 0.500
Train Loss: 1.306, Train Accuracy: 0.800
Train Loss: 1.414, Train Accuracy: 0.500
Train Loss: 1.213, Train Accuracy: 0.800
Train Loss: 2.021, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.600
Round 44
Train Loss: 1.101, Train Accuracy: 0.750
Train Loss: 0.985, Train Accuracy: 0.500
Train Loss: 1.005, Train Accuracy: 0.600
Train Loss: 1.397, Train Accuracy: 0.800
Train Loss: 1.167, Train Accuracy: 0.375
Train Loss: 1.474, Train Accuracy: 1.000
Train Loss: 1.688, Train Accuracy: 0.500
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 1.839, Train Accuracy: 0.750
Train Loss: 1.215, Train Accuracy: 0.600
Round 45
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.400
Train Loss: 0.944, Train Accuracy: 0.400
Train Loss: 1.227, Train Accuracy: 0.800
Train Loss: 1.116, Train Accuracy: 0.875
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.543, Train Accuracy: 0.500
Train Loss: 1.358, Train Accuracy: 0.600
Train Loss: 1.938, Train Accuracy: 0.750
Train Loss: 1.241, Train Accuracy: 0.700
Round 46
Train Loss: 1.246, Train Accuracy: 0.750
Train Loss: 0.987, Train Accuracy: 0.600
Train Loss: 0.941, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 1.000
Train Loss: 1.117, Train Accuracy: 0.625
Train Loss: 1.288, Train Accuracy: 0.800
Train Loss: 1.398, Train Accuracy: 1.000
Train Loss: 1.055, Train Accuracy: 0.600
Train Loss: 1.659, Train Accuracy: 0.750
Train Loss: 1.247, Train Accuracy: 0.800
Round 47
Train Loss: 1.226, Train Accuracy: 0.750
Train Loss: 0.979, Train Accuracy: 0.600
Train Loss: 0.930, Train Accuracy: 0.600
Train Loss: 1.473, Train Accuracy: 0.800
Train Loss: 1.171, Train Accuracy: 0.625
Train Loss: 1.260, Train Accuracy: 0.800
Train Loss: 1.717, Train Accuracy: 0.500
Train Loss: 0.972, Train Accuracy: 0.600
Train Loss: 2.180, Train Accuracy: 0.750
Train Loss: 1.276, Train Accuracy: 0.600
Round 48
Train Loss: 1.176, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.700
Train Loss: 1.008, Train Accuracy: 0.600
Train Loss: 1.420, Train Accuracy: 1.000
Train Loss: 1.090, Train Accuracy: 0.750
Train Loss: 1.408, Train Accuracy: 0.800
Train Loss: 1.430, Train Accuracy: 0.500

(FLClient pid=2872558) 2025-04-11 09:16:44,381 - INFO - Epoch   2| Train Loss: 0.781| Train Accuracy: 0.750 [repeated 330x across cluster]
(FLClient pid=2872558) 2025-04-11 09:16:44,391 - INFO - Epoch   2| Validation Loss: 1.220, Validation Accuracy: 0.295 [repeated 110x across cluster]
(FLClient pid=2872558) 2025-04-11 09:16:49,596 - INFO - Epoch   2| Train Loss: 0.647| Train Accuracy: 0.750 [repeated 390x across cluster]
(FLClient pid=2872558) 2025-04-11 09:16:49,604 - INFO - Epoch   2| Validation Loss: 1.371, Validation Accuracy: 0.295 [repeated 130x across cluster]
(FLClient pid=2872558) 2025-04-11 09:16:54,693 - INFO - Epoch   2| Train Loss: 0.661| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2872558) 2025-04-11 09:16:54,701 - INFO - Epoch   2| Validation Loss: 1.327, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2872558) 2025-04-11 09:16:59,870 - INFO - Epoch   2| Train Loss: 0.613| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2872558) 2025-04-11 09:16:59,878 - INFO - Epoch   2| Validation Loss: 1.228, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2872558) 2025-04-11 09:17:04,976 - INFO - Epoch   2| Train Loss: 0.575| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2872558) 2025-04-11 09:17:04,984 - INFO - Epoch   2| Validation Loss: 1.259, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2872559) 2025-04-11 09:17:10,051 - INFO - Epoch   0| Train Loss: 0.899| Train Accuracy: 0.600 [repeated 448x across cluster]
(FLClient pid=2875340) 2025-04-11 09:17:09,741 - INFO - Epoch   2| Validation Loss: 1.253, Validation Accuracy: 0.203 [repeated 149x across cluster]
(FLClient pid=2872558) 2025-04-11 09:17:15,182 - INFO - Epoch   2| Train Loss: 0.329| Train Accuracy: 1.000 [repeated 452x across cluster]
(FLClient pid=2872558) 2025-04-11 09:17:15,189 - INFO - Epoch   2| Validation Loss: 1.386, Validation Accuracy: 0.295 [repeated 151x across cluster]

Training done
Round 1
Train Loss: 1.220, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.058, Train Accuracy: 0.600
Train Loss: 1.269, Train Accuracy: 0.600
Train Loss: 1.229, Train Accuracy: 0.625
Train Loss: 1.237, Train Accuracy: 0.800
Train Loss: 1.391, Train Accuracy: 0.500
Train Loss: 1.138, Train Accuracy: 0.600
Train Loss: 1.481, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.400
Round 2
Train Loss: 1.271, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.057, Train Accuracy: 0.600
Train Loss: 1.313, Train Accuracy: 0.600
Train Loss: 1.199, Train Accuracy: 0.625
Train Loss: 1.271, Train Accuracy: 0.800
Train Loss: 1.410, Train Accuracy: 1.000
Train Loss: 1.150, Train Accuracy: 0.400
Train Loss: 1.578, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.600
Round 3
Train Loss: 1.285, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.042, Train Accuracy: 0.400
Train Loss: 1.343, Train Accuracy: 0.600
Train Loss: 1.206, Train Accuracy: 0.625
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.437, Train Accuracy: 0.500
Train Loss: 1.158, Train Accuracy: 0.400
Train Loss: 1.648, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.500
Round 4
Train Loss: 1.334, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.043, Train Accuracy: 0.400
Train Loss: 1.388, Train Accuracy: 0.600
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.463, Train Accuracy: 0.500
Train Loss: 1.218, Train Accuracy: 0.600
Train Loss: 1.661, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.300
Round 5
Train Loss: 1.335, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.383, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.482, Train Accuracy: 0.750
Train Loss: 1.155, Train Accuracy: 0.400
Train Loss: 1.717, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.300
Round 6
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.046, Train Accuracy: 0.600
Train Loss: 1.419, Train Accuracy: 0.600
Train Loss: 1.283, Train Accuracy: 0.625
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.506, Train Accuracy: 0.500
Train Loss: 1.170, Train Accuracy: 0.000
Train Loss: 1.677, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.400
Round 7
Train Loss: 1.293, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.600
Train Loss: 1.423, Train Accuracy: 0.600
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.479, Train Accuracy: 0.500
Train Loss: 1.142, Train Accuracy: 0.400
Train Loss: 1.762, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.600
Round 8
Train Loss: 1.349, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.400
Train Loss: 1.024, Train Accuracy: 0.600
Train Loss: 1.418, Train Accuracy: 0.600
Train Loss: 1.293, Train Accuracy: 0.625
Train Loss: 1.335, Train Accuracy: 0.800
Train Loss: 1.478, Train Accuracy: 0.500
Train Loss: 1.157, Train Accuracy: 0.200
Train Loss: 1.807, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.300
Round 9
Train Loss: 1.337, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.400
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.441, Train Accuracy: 0.600
Train Loss: 1.239, Train Accuracy: 0.625
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.487, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.400
Train Loss: 1.846, Train Accuracy: 0.750
Train Loss: 1.175, Train Accuracy: 0.600
Round 10
Train Loss: 1.324, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.042, Train Accuracy: 0.800
Train Loss: 1.454, Train Accuracy: 0.600
Train Loss: 1.214, Train Accuracy: 0.625
Train Loss: 1.319, Train Accuracy: 0.800
Train Loss: 1.471, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.400
Train Loss: 1.798, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.500
Round 11
Train Loss: 1.276, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 1.449, Train Accuracy: 0.600
Train Loss: 1.194, Train Accuracy: 0.625
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.550, Train Accuracy: 0.500
Train Loss: 1.183, Train Accuracy: 0.400
Train Loss: 1.825, Train Accuracy: 0.750
Train Loss: 1.221, Train Accuracy: 0.500
Round 12
Train Loss: 1.250, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.481, Train Accuracy: 0.600
Train Loss: 1.221, Train Accuracy: 0.625
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.400
Train Loss: 1.834, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.500
Round 13
Train Loss: 1.369, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.500
Train Loss: 1.018, Train Accuracy: 0.400
Train Loss: 1.497, Train Accuracy: 0.800
Train Loss: 1.272, Train Accuracy: 0.750
Train Loss: 1.287, Train Accuracy: 0.800
Train Loss: 1.497, Train Accuracy: 0.500
Train Loss: 1.189, Train Accuracy: 0.400
Train Loss: 1.891, Train Accuracy: 0.750
Train Loss: 1.148, Train Accuracy: 0.500
Round 14
Train Loss: 1.371, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.013, Train Accuracy: 0.600
Train Loss: 1.499, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.625
Train Loss: 1.371, Train Accuracy: 0.800
Train Loss: 1.466, Train Accuracy: 0.500
Train Loss: 1.176, Train Accuracy: 0.400
Train Loss: 1.854, Train Accuracy: 0.750
Train Loss: 1.231, Train Accuracy: 0.800
Round 15
Train Loss: 1.385, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.023, Train Accuracy: 0.400
Train Loss: 1.497, Train Accuracy: 0.600
Train Loss: 1.227, Train Accuracy: 0.625
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.577, Train Accuracy: 0.250
Train Loss: 1.139, Train Accuracy: 0.800
Train Loss: 1.849, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.500
Round 16
Train Loss: 1.372, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 1.435, Train Accuracy: 0.600
Train Loss: 1.242, Train Accuracy: 0.500
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.603, Train Accuracy: 0.500
Train Loss: 1.307, Train Accuracy: 0.400
Train Loss: 1.891, Train Accuracy: 0.750
Train Loss: 1.219, Train Accuracy: 0.700
Round 17
Train Loss: 1.337, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.700
Train Loss: 1.007, Train Accuracy: 0.400
Train Loss: 1.425, Train Accuracy: 0.600
Train Loss: 1.256, Train Accuracy: 0.625
Train Loss: 1.401, Train Accuracy: 0.800
Train Loss: 1.511, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.400
Train Loss: 1.867, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.600
Round 18
Train Loss: 1.265, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.600
Train Loss: 1.012, Train Accuracy: 0.400
Train Loss: 1.430, Train Accuracy: 0.600
Train Loss: 1.268, Train Accuracy: 0.625
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.501, Train Accuracy: 0.500
Train Loss: 1.166, Train Accuracy: 0.800
Train Loss: 1.977, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.500
Round 19
Train Loss: 1.336, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.500
Train Loss: 0.993, Train Accuracy: 0.400
Train Loss: 1.411, Train Accuracy: 0.800
Train Loss: 1.295, Train Accuracy: 0.750
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.535, Train Accuracy: 0.500
Train Loss: 1.173, Train Accuracy: 0.200
Train Loss: 1.954, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.700
Round 20
Train Loss: 1.293, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.500
Train Loss: 1.003, Train Accuracy: 0.400
Train Loss: 1.627, Train Accuracy: 0.800
Train Loss: 1.192, Train Accuracy: 0.625
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.639, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.200
Train Loss: 2.044, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.400
Round 21
Train Loss: 1.337, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.500
Train Loss: 0.993, Train Accuracy: 0.200
Train Loss: 1.453, Train Accuracy: 0.600
Train Loss: 1.216, Train Accuracy: 0.750
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.562, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.800
Train Loss: 1.988, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.700
Round 22
Train Loss: 1.331, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.500
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 1.514, Train Accuracy: 0.600
Train Loss: 1.145, Train Accuracy: 0.625
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.540, Train Accuracy: 1.000
Train Loss: 1.152, Train Accuracy: 1.000
Train Loss: 1.911, Train Accuracy: 0.750
Train Loss: 1.128, Train Accuracy: 0.400
Round 23
Train Loss: 1.393, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 0.985, Train Accuracy: 0.800
Train Loss: 1.572, Train Accuracy: 0.600
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.513, Train Accuracy: 0.500
Train Loss: 1.090, Train Accuracy: 0.800
Train Loss: 1.900, Train Accuracy: 0.750
Train Loss: 1.101, Train Accuracy: 0.500
Round 24
Train Loss: 1.249, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.500
Train Loss: 0.984, Train Accuracy: 0.600
Train Loss: 1.481, Train Accuracy: 0.800
Train Loss: 1.160, Train Accuracy: 0.875
Train Loss: 1.440, Train Accuracy: 0.800
Train Loss: 1.529, Train Accuracy: 0.250
Train Loss: 1.159, Train Accuracy: 0.600
Train Loss: 1.950, Train Accuracy: 0.750
Train Loss: 1.112, Train Accuracy: 0.500
Round 25
Train Loss: 1.248, Train Accuracy: 0.750
Train Loss: 1.020, Train Accuracy: 0.600
Train Loss: 1.001, Train Accuracy: 0.600
Train Loss: 1.343, Train Accuracy: 0.800
Train Loss: 1.175, Train Accuracy: 0.750
Train Loss: 1.296, Train Accuracy: 0.800
Train Loss: 1.470, Train Accuracy: 0.500
Train Loss: 1.163, Train Accuracy: 0.600
Train Loss: 1.982, Train Accuracy: 0.750
Train Loss: 1.104, Train Accuracy: 0.500
Round 26
Train Loss: 1.290, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.600
Train Loss: 0.976, Train Accuracy: 0.400
Train Loss: 1.494, Train Accuracy: 1.000
Train Loss: 1.304, Train Accuracy: 0.625
Train Loss: 1.402, Train Accuracy: 0.800
Train Loss: 1.606, Train Accuracy: 0.750
Train Loss: 1.108, Train Accuracy: 0.800
Train Loss: 1.843, Train Accuracy: 0.750
Train Loss: 1.146, Train Accuracy: 0.500
Round 27
Train Loss: 1.455, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.500
Train Loss: 0.965, Train Accuracy: 0.400
Train Loss: 1.439, Train Accuracy: 0.800
Train Loss: 1.211, Train Accuracy: 0.750
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.487, Train Accuracy: 0.500
Train Loss: 1.275, Train Accuracy: 0.400
Train Loss: 2.018, Train Accuracy: 0.750
Train Loss: 1.101, Train Accuracy: 0.400
Round 28
Train Loss: 1.310, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.700
Train Loss: 0.989, Train Accuracy: 0.400
Train Loss: 1.487, Train Accuracy: 1.000
Train Loss: 1.177, Train Accuracy: 0.750
Train Loss: 1.301, Train Accuracy: 0.800
Train Loss: 1.535, Train Accuracy: 0.750
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 2.116, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.300
Round 29
Train Loss: 1.327, Train Accuracy: 0.750
Train Loss: 1.014, Train Accuracy: 0.800
Train Loss: 0.960, Train Accuracy: 0.600
Train Loss: 1.425, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.750
Train Loss: 1.356, Train Accuracy: 0.800
Train Loss: 1.597, Train Accuracy: 0.500
Train Loss: 1.199, Train Accuracy: 0.800
Train Loss: 1.944, Train Accuracy: 0.750
Train Loss: 1.213, Train Accuracy: 0.800
Round 30
Train Loss: 1.330, Train Accuracy: 0.750
Train Loss: 1.014, Train Accuracy: 0.500
Train Loss: 0.969, Train Accuracy: 0.600
Train Loss: 1.563, Train Accuracy: 1.000
Train Loss: 1.135, Train Accuracy: 0.750
Train Loss: 1.404, Train Accuracy: 0.800
Train Loss: 1.511, Train Accuracy: 0.750
Train Loss: 1.120, Train Accuracy: 0.200
Train Loss: 2.151, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.700
Round 31
Train Loss: 1.242, Train Accuracy: 0.750
Train Loss: 1.018, Train Accuracy: 0.800
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 1.496, Train Accuracy: 0.800
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.348, Train Accuracy: 0.800
Train Loss: 1.769, Train Accuracy: 0.500
Train Loss: 1.090, Train Accuracy: 0.800
Train Loss: 2.129, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.700
Round 32
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 0.987, Train Accuracy: 0.700
Train Loss: 0.959, Train Accuracy: 0.600
Train Loss: 1.464, Train Accuracy: 0.600
Train Loss: 1.190, Train Accuracy: 0.875
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.505, Train Accuracy: 0.500
Train Loss: 1.106, Train Accuracy: 0.600
Train Loss: 2.091, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.400
Round 33
Train Loss: 1.329, Train Accuracy: 0.750
Train Loss: 1.013, Train Accuracy: 0.500
Train Loss: 0.986, Train Accuracy: 0.400
Train Loss: 1.406, Train Accuracy: 0.800
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.459, Train Accuracy: 1.000
Train Loss: 1.112, Train Accuracy: 0.600
Train Loss: 1.880, Train Accuracy: 0.750
Train Loss: 1.129, Train Accuracy: 0.800
Round 34
Train Loss: 1.217, Train Accuracy: 0.750
Train Loss: 0.992, Train Accuracy: 0.800
Train Loss: 0.950, Train Accuracy: 0.200
Train Loss: 1.376, Train Accuracy: 0.800
Train Loss: 1.201, Train Accuracy: 0.625
Train Loss: 1.402, Train Accuracy: 0.800
Train Loss: 1.484, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.400
Train Loss: 2.051, Train Accuracy: 0.750
Train Loss: 1.235, Train Accuracy: 0.400
Round 35
Train Loss: 1.375, Train Accuracy: 1.000
Train Loss: 1.016, Train Accuracy: 0.600
Train Loss: 0.972, Train Accuracy: 0.800
Train Loss: 1.510, Train Accuracy: 0.600
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 1.305, Train Accuracy: 0.800
Train Loss: 1.770, Train Accuracy: 0.500
Train Loss: 1.024, Train Accuracy: 0.600
Train Loss: 2.014, Train Accuracy: 0.750
Train Loss: 1.254, Train Accuracy: 0.600
Round 36
Train Loss: 1.160, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.600
Train Loss: 0.951, Train Accuracy: 0.600
Train Loss: 1.565, Train Accuracy: 0.800
Train Loss: 1.138, Train Accuracy: 0.750
Train Loss: 1.244, Train Accuracy: 0.800
Train Loss: 1.758, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.600
Train Loss: 2.123, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.500
Round 37
Train Loss: 1.260, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.600
Train Loss: 0.948, Train Accuracy: 0.600
Train Loss: 1.561, Train Accuracy: 1.000
Train Loss: 1.076, Train Accuracy: 0.625
Train Loss: 1.367, Train Accuracy: 0.800
Train Loss: 1.618, Train Accuracy: 1.000
Train Loss: 1.286, Train Accuracy: 0.600
Train Loss: 2.216, Train Accuracy: 0.750
Train Loss: 1.331, Train Accuracy: 0.500
Round 38
Train Loss: 1.185, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.500
Train Loss: 0.953, Train Accuracy: 0.600
Train Loss: 1.419, Train Accuracy: 1.000
Train Loss: 1.209, Train Accuracy: 0.500
Train Loss: 1.391, Train Accuracy: 0.800
Train Loss: 1.730, Train Accuracy: 0.500
Train Loss: 1.197, Train Accuracy: 0.600
Train Loss: 1.937, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.800
Round 39
Train Loss: 1.272, Train Accuracy: 0.750
Train Loss: 0.974, Train Accuracy: 0.700
Train Loss: 0.919, Train Accuracy: 0.400
Train Loss: 1.347, Train Accuracy: 1.000
Train Loss: 1.142, Train Accuracy: 0.875
Train Loss: 1.346, Train Accuracy: 0.800
Train Loss: 1.678, Train Accuracy: 0.500
Train Loss: 1.369, Train Accuracy: 0.800
Train Loss: 1.943, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.600
Round 40
Train Loss: 1.132, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.700
Train Loss: 0.952, Train Accuracy: 0.600
Train Loss: 1.368, Train Accuracy: 1.000
Train Loss: 1.149, Train Accuracy: 0.375
Train Loss: 1.426, Train Accuracy: 0.800
Train Loss: 1.620, Train Accuracy: 1.000
Train Loss: 1.080, Train Accuracy: 0.800
Train Loss: 1.912, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.800
Round 41
Train Loss: 1.251, Train Accuracy: 0.750
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 0.979, Train Accuracy: 0.600
Train Loss: 1.463, Train Accuracy: 1.000
Train Loss: 1.065, Train Accuracy: 0.875
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.796, Train Accuracy: 0.500
Train Loss: 1.186, Train Accuracy: 0.800
Train Loss: 2.211, Train Accuracy: 0.750
Train Loss: 1.465, Train Accuracy: 0.500
Round 42
Train Loss: 1.276, Train Accuracy: 0.750
Train Loss: 0.996, Train Accuracy: 0.700
Train Loss: 0.900, Train Accuracy: 0.400
Train Loss: 1.453, Train Accuracy: 0.800
Train Loss: 1.096, Train Accuracy: 0.750
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.779, Train Accuracy: 0.500
Train Loss: 1.196, Train Accuracy: 0.800
Train Loss: 2.026, Train Accuracy: 0.750
Train Loss: 1.090, Train Accuracy: 0.700
Round 43
Train Loss: 1.401, Train Accuracy: 0.750
Train Loss: 0.975, Train Accuracy: 0.700
Train Loss: 0.958, Train Accuracy: 0.600
Train Loss: 1.323, Train Accuracy: 1.000
Train Loss: 1.268, Train Accuracy: 0.625
Train Loss: 1.305, Train Accuracy: 0.800
Train Loss: 1.586, Train Accuracy: 0.500
Train Loss: 1.005, Train Accuracy: 0.200
Train Loss: 1.974, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.500
Round 44
Train Loss: 1.228, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.600
Train Loss: 0.919, Train Accuracy: 0.400
Train Loss: 1.265, Train Accuracy: 0.800
Train Loss: 1.079, Train Accuracy: 0.625
Train Loss: 1.357, Train Accuracy: 0.800
Train Loss: 1.826, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.600
Train Loss: 1.953, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.700
Round 45
Train Loss: 1.335, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.600
Train Loss: 0.874, Train Accuracy: 0.800
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.079, Train Accuracy: 0.750
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.527, Train Accuracy: 0.500
Train Loss: 1.000, Train Accuracy: 0.800
Train Loss: 2.085, Train Accuracy: 0.750
Train Loss: 1.224, Train Accuracy: 0.700
Round 46
Train Loss: 1.236, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.700
Train Loss: 0.907, Train Accuracy: 0.400
Train Loss: 1.557, Train Accuracy: 0.800
Train Loss: 1.115, Train Accuracy: 0.750
Train Loss: 1.324, Train Accuracy: 0.800
Train Loss: 1.627, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.600
Train Loss: 2.128, Train Accuracy: 0.750
Train Loss: 1.269, Train Accuracy: 0.700
Round 47
Train Loss: 1.316, Train Accuracy: 0.750
Train Loss: 0.973, Train Accuracy: 0.600
Train Loss: 0.921, Train Accuracy: 0.800
Train Loss: 1.365, Train Accuracy: 1.000
Train Loss: 1.075, Train Accuracy: 0.250
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.778, Train Accuracy: 0.750
Train Loss: 0.952, Train Accuracy: 1.000
Train Loss: 2.141, Train Accuracy: 1.000
Train Loss: 1.464, Train Accuracy: 0.600
Round 48
Train Loss: 1.391, Train Accuracy: 0.750
Train Loss: 0.974, Train Accuracy: 0.600
Train Loss: 0.966, Train Accuracy: 0.600
Train Loss: 1.598, Train Accuracy: 0.800
Train Loss: 1.038, Train Accuracy: 0.750
Train Loss: 1.399, Train Accuracy: 0.800
Train Loss: 1.372, Train Accuracy: 1.000

(FLClient pid=2876287) 2025-04-11 09:17:45,782 - INFO - Epoch   2| Train Loss: 0.835| Train Accuracy: 0.750 [repeated 360x across cluster]
(FLClient pid=2876287) 2025-04-11 09:17:45,792 - INFO - Epoch   2| Validation Loss: 1.133, Validation Accuracy: 0.295 [repeated 120x across cluster]
(FLClient pid=2876287) 2025-04-11 09:17:50,956 - INFO - Epoch   2| Train Loss: 0.704| Train Accuracy: 0.750 [repeated 390x across cluster]
(FLClient pid=2876287) 2025-04-11 09:17:50,964 - INFO - Epoch   2| Validation Loss: 1.305, Validation Accuracy: 0.295 [repeated 130x across cluster]
(FLClient pid=2876287) 2025-04-11 09:17:56,053 - INFO - Epoch   2| Train Loss: 0.586| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2876287) 2025-04-11 09:17:56,060 - INFO - Epoch   2| Validation Loss: 1.262, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2876287) 2025-04-11 09:18:01,120 - INFO - Epoch   2| Train Loss: 0.648| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2876287) 2025-04-11 09:18:01,128 - INFO - Epoch   2| Validation Loss: 1.249, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2876287) 2025-04-11 09:18:06,209 - INFO - Epoch   2| Train Loss: 0.679| Train Accuracy: 0.500 [repeated 450x across cluster]
(FLClient pid=2876287) 2025-04-11 09:18:06,217 - INFO - Epoch   2| Validation Loss: 1.231, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2876287) 2025-04-11 09:18:11,296 - INFO - Epoch   2| Train Loss: 0.383| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2876287) 2025-04-11 09:18:11,304 - INFO - Epoch   2| Validation Loss: 0.871, Validation Accuracy: 0.636 [repeated 150x across cluster]
(FLClient pid=2876287) 2025-04-11 09:18:16,387 - INFO - Epoch   2| Train Loss: 0.433| Train Accuracy: 1.000 [repeated 450x across cluster]
(FLClient pid=2876287) 2025-04-11 09:18:16,395 - INFO - Epoch   2| Validation Loss: 1.070, Validation Accuracy: 0.295 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.133, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.176, Train Accuracy: 0.600
Train Loss: 1.180, Train Accuracy: 0.625
Train Loss: 1.184, Train Accuracy: 0.800
Train Loss: 1.316, Train Accuracy: 0.500
Train Loss: 1.135, Train Accuracy: 0.400
Train Loss: 1.381, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.400
Round 2
Train Loss: 1.171, Train Accuracy: 0.750
Train Loss: 1.083, Train Accuracy: 0.500
Train Loss: 1.033, Train Accuracy: 0.400
Train Loss: 1.203, Train Accuracy: 0.600
Train Loss: 1.195, Train Accuracy: 0.625
Train Loss: 1.197, Train Accuracy: 0.800
Train Loss: 1.321, Train Accuracy: 0.750
Train Loss: 1.125, Train Accuracy: 0.000
Train Loss: 1.383, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.400
Round 3
Train Loss: 1.203, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.032, Train Accuracy: 0.400
Train Loss: 1.206, Train Accuracy: 0.600
Train Loss: 1.206, Train Accuracy: 0.625
Train Loss: 1.208, Train Accuracy: 0.800
Train Loss: 1.300, Train Accuracy: 0.250
Train Loss: 1.143, Train Accuracy: 0.600
Train Loss: 1.437, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.400
Round 4
Train Loss: 1.241, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.500
Train Loss: 1.031, Train Accuracy: 0.400
Train Loss: 1.241, Train Accuracy: 0.600
Train Loss: 1.207, Train Accuracy: 0.625
Train Loss: 1.231, Train Accuracy: 0.800
Train Loss: 1.350, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.400
Train Loss: 1.458, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.400
Round 5
Train Loss: 1.221, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.231, Train Accuracy: 0.600
Train Loss: 1.185, Train Accuracy: 0.625
Train Loss: 1.255, Train Accuracy: 0.800
Train Loss: 1.375, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.600
Train Loss: 1.505, Train Accuracy: 0.750
Train Loss: 1.207, Train Accuracy: 0.400
Round 6
Train Loss: 1.240, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.400
Train Loss: 1.024, Train Accuracy: 0.400
Train Loss: 1.209, Train Accuracy: 0.600
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.240, Train Accuracy: 0.800
Train Loss: 1.331, Train Accuracy: 0.500
Train Loss: 1.174, Train Accuracy: 0.800
Train Loss: 1.572, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.400
Round 7
Train Loss: 1.235, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.500
Train Loss: 1.031, Train Accuracy: 0.400
Train Loss: 1.300, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.249, Train Accuracy: 0.800
Train Loss: 1.358, Train Accuracy: 0.250
Train Loss: 1.143, Train Accuracy: 0.200
Train Loss: 1.615, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.500
Round 8
Train Loss: 1.197, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.301, Train Accuracy: 0.800
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.248, Train Accuracy: 0.800
Train Loss: 1.340, Train Accuracy: 1.000
Train Loss: 1.146, Train Accuracy: 0.600
Train Loss: 1.595, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.400
Round 9
Train Loss: 1.243, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.023, Train Accuracy: 0.400
Train Loss: 1.242, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.415, Train Accuracy: 1.000
Train Loss: 1.149, Train Accuracy: 0.800
Train Loss: 1.538, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.300
Round 10
Train Loss: 1.307, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.600
Train Loss: 1.017, Train Accuracy: 0.400
Train Loss: 1.295, Train Accuracy: 0.600
Train Loss: 1.199, Train Accuracy: 0.625
Train Loss: 1.222, Train Accuracy: 0.800
Train Loss: 1.367, Train Accuracy: 0.250
Train Loss: 1.150, Train Accuracy: 0.400
Train Loss: 1.693, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.500
Round 11
Train Loss: 1.228, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.600
Train Loss: 1.015, Train Accuracy: 0.400
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.229, Train Accuracy: 0.625
Train Loss: 1.249, Train Accuracy: 0.800
Train Loss: 1.390, Train Accuracy: 0.500
Train Loss: 1.146, Train Accuracy: 0.600
Train Loss: 1.587, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.500
Round 12
Train Loss: 1.329, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.500
Train Loss: 1.015, Train Accuracy: 0.400
Train Loss: 1.295, Train Accuracy: 0.800
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.455, Train Accuracy: 0.500
Train Loss: 1.141, Train Accuracy: 0.400
Train Loss: 1.670, Train Accuracy: 0.750
Train Loss: 1.208, Train Accuracy: 0.500
Round 13
Train Loss: 1.274, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.400
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 1.208, Train Accuracy: 0.600
Train Loss: 1.188, Train Accuracy: 0.625
Train Loss: 1.251, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 0.500
Train Loss: 1.197, Train Accuracy: 0.200
Train Loss: 1.642, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.400
Round 14
Train Loss: 1.305, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.500
Train Loss: 1.007, Train Accuracy: 0.400
Train Loss: 1.303, Train Accuracy: 0.400
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.485, Train Accuracy: 0.500
Train Loss: 1.195, Train Accuracy: 0.600
Train Loss: 1.755, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.500
Round 15
Train Loss: 1.307, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.600
Train Loss: 1.018, Train Accuracy: 0.600
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.230, Train Accuracy: 0.625
Train Loss: 1.286, Train Accuracy: 0.800
Train Loss: 1.481, Train Accuracy: 1.000
Train Loss: 1.161, Train Accuracy: 0.400
Train Loss: 1.728, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.500
Round 16
Train Loss: 1.225, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.500
Train Loss: 1.003, Train Accuracy: 0.400
Train Loss: 1.359, Train Accuracy: 0.600
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.436, Train Accuracy: 0.750
Train Loss: 1.216, Train Accuracy: 0.600
Train Loss: 1.792, Train Accuracy: 0.750
Train Loss: 1.189, Train Accuracy: 0.400
Round 17
Train Loss: 1.288, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.600
Train Loss: 1.004, Train Accuracy: 0.400
Train Loss: 1.300, Train Accuracy: 0.600
Train Loss: 1.272, Train Accuracy: 0.875
Train Loss: 1.283, Train Accuracy: 0.800
Train Loss: 1.416, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.800
Train Loss: 1.676, Train Accuracy: 0.750
Train Loss: 1.203, Train Accuracy: 0.400
Round 18
Train Loss: 1.298, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 1.288, Train Accuracy: 0.600
Train Loss: 1.221, Train Accuracy: 0.625
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.527, Train Accuracy: 0.750
Train Loss: 1.115, Train Accuracy: 0.600
Train Loss: 1.741, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 0.500
Round 19
Train Loss: 1.258, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.600
Train Loss: 0.992, Train Accuracy: 0.400
Train Loss: 1.349, Train Accuracy: 1.000
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.454, Train Accuracy: 0.500
Train Loss: 1.137, Train Accuracy: 0.800
Train Loss: 1.793, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.400
Round 20
Train Loss: 1.197, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.500
Train Loss: 0.995, Train Accuracy: 0.400
Train Loss: 1.353, Train Accuracy: 0.800
Train Loss: 1.279, Train Accuracy: 0.625
Train Loss: 1.225, Train Accuracy: 0.800
Train Loss: 1.473, Train Accuracy: 0.750
Train Loss: 1.127, Train Accuracy: 0.600
Train Loss: 1.806, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.500
Round 21
Train Loss: 1.324, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.500
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 1.362, Train Accuracy: 0.600
Train Loss: 1.214, Train Accuracy: 0.500
Train Loss: 1.288, Train Accuracy: 0.800
Train Loss: 1.375, Train Accuracy: 0.250
Train Loss: 1.190, Train Accuracy: 0.600
Train Loss: 1.725, Train Accuracy: 0.750
Train Loss: 1.114, Train Accuracy: 0.500
Round 22
Train Loss: 1.432, Train Accuracy: 0.750
Train Loss: 1.030, Train Accuracy: 0.500
Train Loss: 0.995, Train Accuracy: 0.400
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.207, Train Accuracy: 0.875
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.542, Train Accuracy: 0.500
Train Loss: 1.135, Train Accuracy: 0.800
Train Loss: 1.836, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.700
Round 23
Train Loss: 1.266, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.500
Train Loss: 0.980, Train Accuracy: 0.600
Train Loss: 1.354, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.750
Train Loss: 1.267, Train Accuracy: 0.800
Train Loss: 1.518, Train Accuracy: 1.000
Train Loss: 1.178, Train Accuracy: 0.600
Train Loss: 1.769, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.600
Round 24
Train Loss: 1.348, Train Accuracy: 0.750
Train Loss: 1.025, Train Accuracy: 0.500
Train Loss: 0.977, Train Accuracy: 0.200
Train Loss: 1.302, Train Accuracy: 0.600
Train Loss: 1.190, Train Accuracy: 0.750
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.509, Train Accuracy: 1.000
Train Loss: 1.165, Train Accuracy: 0.600
Train Loss: 1.833, Train Accuracy: 0.750
Train Loss: 1.214, Train Accuracy: 0.600
Round 25
Train Loss: 1.287, Train Accuracy: 0.750
Train Loss: 1.033, Train Accuracy: 0.600
Train Loss: 1.002, Train Accuracy: 0.600
Train Loss: 1.464, Train Accuracy: 0.800
Train Loss: 1.203, Train Accuracy: 0.750
Train Loss: 1.362, Train Accuracy: 0.800
Train Loss: 1.489, Train Accuracy: 1.000
Train Loss: 1.145, Train Accuracy: 0.800
Train Loss: 1.958, Train Accuracy: 0.750
Train Loss: 1.107, Train Accuracy: 0.700
Round 26
Train Loss: 1.306, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.600
Train Loss: 0.989, Train Accuracy: 0.400
Train Loss: 1.322, Train Accuracy: 0.800
Train Loss: 1.206, Train Accuracy: 0.625
Train Loss: 1.228, Train Accuracy: 0.800
Train Loss: 1.629, Train Accuracy: 0.750
Train Loss: 1.090, Train Accuracy: 0.600
Train Loss: 1.917, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.700
Round 27
Train Loss: 1.260, Train Accuracy: 0.750
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 0.962, Train Accuracy: 0.400
Train Loss: 1.352, Train Accuracy: 0.800
Train Loss: 1.199, Train Accuracy: 0.875
Train Loss: 1.369, Train Accuracy: 0.800
Train Loss: 1.409, Train Accuracy: 0.500
Train Loss: 1.160, Train Accuracy: 0.800
Train Loss: 1.749, Train Accuracy: 0.750
Train Loss: 1.126, Train Accuracy: 0.500
Round 28
Train Loss: 1.234, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.600
Train Loss: 0.970, Train Accuracy: 0.600
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.223, Train Accuracy: 0.625
Train Loss: 1.305, Train Accuracy: 0.800
Train Loss: 1.488, Train Accuracy: 1.000
Train Loss: 1.164, Train Accuracy: 0.800
Train Loss: 1.804, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.400
Round 29
Train Loss: 1.262, Train Accuracy: 0.750
Train Loss: 1.003, Train Accuracy: 0.600
Train Loss: 0.964, Train Accuracy: 0.400
Train Loss: 1.442, Train Accuracy: 0.800
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.342, Train Accuracy: 0.800
Train Loss: 1.472, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.600
Train Loss: 1.867, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.500
Round 30
Train Loss: 1.302, Train Accuracy: 0.750
Train Loss: 1.007, Train Accuracy: 0.500
Train Loss: 0.968, Train Accuracy: 0.600
Train Loss: 1.389, Train Accuracy: 0.800
Train Loss: 1.211, Train Accuracy: 0.875
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.375, Train Accuracy: 0.750
Train Loss: 1.109, Train Accuracy: 0.400
Train Loss: 1.947, Train Accuracy: 0.750
Train Loss: 1.086, Train Accuracy: 0.500
Round 31
Train Loss: 1.226, Train Accuracy: 0.750
Train Loss: 1.012, Train Accuracy: 0.500
Train Loss: 0.951, Train Accuracy: 0.800
Train Loss: 1.480, Train Accuracy: 0.800
Train Loss: 1.161, Train Accuracy: 0.625
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.456, Train Accuracy: 0.750
Train Loss: 1.086, Train Accuracy: 0.200
Train Loss: 1.991, Train Accuracy: 1.000
Train Loss: 1.104, Train Accuracy: 0.500
Round 32
Train Loss: 1.109, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.700
Train Loss: 0.950, Train Accuracy: 0.600
Train Loss: 1.371, Train Accuracy: 1.000
Train Loss: 1.259, Train Accuracy: 0.375
Train Loss: 1.302, Train Accuracy: 0.800
Train Loss: 1.649, Train Accuracy: 0.500
Train Loss: 1.059, Train Accuracy: 0.600
Train Loss: 1.812, Train Accuracy: 0.750
Train Loss: 1.118, Train Accuracy: 0.600
Round 33
Train Loss: 1.380, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.600
Train Loss: 0.931, Train Accuracy: 0.400
Train Loss: 1.317, Train Accuracy: 1.000
Train Loss: 1.308, Train Accuracy: 0.375
Train Loss: 1.262, Train Accuracy: 0.800
Train Loss: 1.522, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.600
Train Loss: 1.867, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Round 34
Train Loss: 1.161, Train Accuracy: 0.750
Train Loss: 0.980, Train Accuracy: 0.500
Train Loss: 0.956, Train Accuracy: 0.600
Train Loss: 1.293, Train Accuracy: 0.600
Train Loss: 1.110, Train Accuracy: 0.625
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.512, Train Accuracy: 1.000
Train Loss: 1.181, Train Accuracy: 0.600
Train Loss: 1.627, Train Accuracy: 0.750
Train Loss: 1.298, Train Accuracy: 0.800
Round 35
Train Loss: 1.315, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.700
Train Loss: 0.932, Train Accuracy: 0.400
Train Loss: 1.289, Train Accuracy: 1.000
Train Loss: 1.212, Train Accuracy: 0.750
Train Loss: 1.208, Train Accuracy: 0.800
Train Loss: 1.546, Train Accuracy: 1.000
Train Loss: 1.122, Train Accuracy: 0.600
Train Loss: 1.885, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 0.600
Round 36
Train Loss: 1.199, Train Accuracy: 0.750
Train Loss: 0.975, Train Accuracy: 0.800
Train Loss: 0.928, Train Accuracy: 0.800
Train Loss: 1.350, Train Accuracy: 1.000
Train Loss: 1.143, Train Accuracy: 0.625
Train Loss: 1.225, Train Accuracy: 0.800
Train Loss: 1.513, Train Accuracy: 1.000
Train Loss: 1.067, Train Accuracy: 0.600
Train Loss: 1.833, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.500
Round 37
Train Loss: 1.436, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.700
Train Loss: 0.916, Train Accuracy: 0.400
Train Loss: 1.323, Train Accuracy: 1.000
Train Loss: 1.120, Train Accuracy: 0.875
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.578, Train Accuracy: 1.000
Train Loss: 1.047, Train Accuracy: 0.400
Train Loss: 2.038, Train Accuracy: 0.500
Train Loss: 1.089, Train Accuracy: 0.700
Round 38
Train Loss: 1.314, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.700
Train Loss: 0.936, Train Accuracy: 0.600
Train Loss: 1.329, Train Accuracy: 1.000
Train Loss: 1.184, Train Accuracy: 0.500
Train Loss: 1.232, Train Accuracy: 0.800
Train Loss: 1.445, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.400
Train Loss: 2.083, Train Accuracy: 1.000
Train Loss: 1.227, Train Accuracy: 0.700
Round 39
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 0.981, Train Accuracy: 0.500
Train Loss: 0.935, Train Accuracy: 0.600
Train Loss: 1.269, Train Accuracy: 1.000
Train Loss: 1.215, Train Accuracy: 0.875
Train Loss: 1.271, Train Accuracy: 0.800
Train Loss: 1.491, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.600
Train Loss: 1.871, Train Accuracy: 0.750
Train Loss: 1.105, Train Accuracy: 0.600
Round 40
Train Loss: 1.253, Train Accuracy: 0.750
Train Loss: 0.994, Train Accuracy: 0.600
Train Loss: 0.920, Train Accuracy: 0.800
Train Loss: 1.245, Train Accuracy: 0.600
Train Loss: 1.190, Train Accuracy: 0.375
Train Loss: 1.268, Train Accuracy: 0.800
Train Loss: 1.331, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.800
Train Loss: 2.036, Train Accuracy: 1.000
Train Loss: 1.155, Train Accuracy: 0.600
Round 41
Train Loss: 1.207, Train Accuracy: 0.750
Train Loss: 1.008, Train Accuracy: 0.600
Train Loss: 0.897, Train Accuracy: 0.800
Train Loss: 1.488, Train Accuracy: 0.800
Train Loss: 1.263, Train Accuracy: 0.625
Train Loss: 1.283, Train Accuracy: 0.800
Train Loss: 1.545, Train Accuracy: 0.500
Train Loss: 1.099, Train Accuracy: 0.600
Train Loss: 1.801, Train Accuracy: 0.750
Train Loss: 0.948, Train Accuracy: 0.500
Round 42
Train Loss: 1.253, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.600
Train Loss: 0.945, Train Accuracy: 0.400
Train Loss: 1.261, Train Accuracy: 0.800
Train Loss: 1.162, Train Accuracy: 0.625
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 1.000
Train Loss: 1.185, Train Accuracy: 0.800
Train Loss: 2.011, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.600
Round 43
Train Loss: 1.201, Train Accuracy: 0.750
Train Loss: 0.976, Train Accuracy: 0.600
Train Loss: 0.893, Train Accuracy: 0.800
Train Loss: 1.508, Train Accuracy: 1.000
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 1.336, Train Accuracy: 0.800
Train Loss: 1.414, Train Accuracy: 1.000
Train Loss: 1.015, Train Accuracy: 0.800
Train Loss: 1.947, Train Accuracy: 1.000
Train Loss: 1.250, Train Accuracy: 0.400
Round 44
Train Loss: 1.249, Train Accuracy: 0.750
Train Loss: 0.938, Train Accuracy: 0.800
Train Loss: 0.912, Train Accuracy: 1.000
Train Loss: 1.286, Train Accuracy: 1.000
Train Loss: 1.169, Train Accuracy: 0.750
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.450, Train Accuracy: 1.000
Train Loss: 1.011, Train Accuracy: 0.600
Train Loss: 1.627, Train Accuracy: 0.750
Train Loss: 1.090, Train Accuracy: 0.600
Round 45
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 0.943, Train Accuracy: 0.700
Train Loss: 0.963, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 1.000
Train Loss: 1.137, Train Accuracy: 0.500
Train Loss: 1.250, Train Accuracy: 0.800
Train Loss: 1.593, Train Accuracy: 0.500
Train Loss: 0.974, Train Accuracy: 0.600
Train Loss: 1.813, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.900
Round 46
Train Loss: 1.205, Train Accuracy: 0.750
Train Loss: 0.932, Train Accuracy: 0.800
Train Loss: 0.906, Train Accuracy: 0.600
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.104, Train Accuracy: 0.875
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.567, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.400
Train Loss: 1.975, Train Accuracy: 1.000
Train Loss: 1.292, Train Accuracy: 0.600
Round 47
Train Loss: 1.241, Train Accuracy: 1.000
Train Loss: 0.931, Train Accuracy: 0.500
Train Loss: 0.900, Train Accuracy: 0.800
Train Loss: 1.562, Train Accuracy: 0.800
Train Loss: 1.127, Train Accuracy: 0.375
Train Loss: 1.363, Train Accuracy: 0.800
Train Loss: 1.473, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 2.029, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.700
Round 48
Train Loss: 1.258, Train Accuracy: 0.750
Train Loss: 0.956, Train Accuracy: 0.500
Train Loss: 0.963, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 1.000
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 1.299, Train Accuracy: 1.000
Train Loss: 1.580, Train Accuracy: 0.500

(FLClient pid=2877390) 2025-04-11 09:18:46,931 - INFO - Epoch   2| Train Loss: 0.819| Train Accuracy: 0.750 [repeated 360x across cluster]
(FLClient pid=2877390) 2025-04-11 09:18:46,942 - INFO - Epoch   2| Validation Loss: 1.160, Validation Accuracy: 0.295 [repeated 120x across cluster]
(FLClient pid=2877391) 2025-04-11 09:18:52,103 - INFO - Epoch   2| Train Loss: 1.106| Train Accuracy: 0.400 [repeated 390x across cluster]
(FLClient pid=2877391) 2025-04-11 09:18:52,110 - INFO - Epoch   2| Validation Loss: 1.061, Validation Accuracy: 0.467 [repeated 130x across cluster]
(FLClient pid=2877391) 2025-04-11 09:18:57,210 - INFO - Epoch   2| Train Loss: 0.902| Train Accuracy: 0.600 [repeated 450x across cluster]
(FLClient pid=2877391) 2025-04-11 09:18:57,216 - INFO - Epoch   2| Validation Loss: 1.010, Validation Accuracy: 0.467 [repeated 150x across cluster]
(FLClient pid=2877391) 2025-04-11 09:19:02,273 - INFO - Epoch   0| Train Loss: 0.955| Train Accuracy: 0.600 [repeated 448x across cluster]
(FLClient pid=2877651) 2025-04-11 09:19:01,966 - INFO - Epoch   2| Validation Loss: 1.156, Validation Accuracy: 0.250 [repeated 149x across cluster]
(FLClient pid=2877391) 2025-04-11 09:19:07,400 - INFO - Epoch   2| Train Loss: 0.785| Train Accuracy: 0.700 [repeated 452x across cluster]
(FLClient pid=2877391) 2025-04-11 09:19:07,407 - INFO - Epoch   2| Validation Loss: 0.869, Validation Accuracy: 0.511 [repeated 151x across cluster]
(FLClient pid=2877391) 2025-04-11 09:19:12,471 - INFO - Epoch   0| Train Loss: 0.763| Train Accuracy: 0.800 [repeated 448x across cluster]
(FLClient pid=2877651) 2025-04-11 09:19:12,161 - INFO - Epoch   2| Validation Loss: 1.288, Validation Accuracy: 0.203 [repeated 149x across cluster]
(FLClient pid=2877395) 2025-04-11 09:19:17,571 - INFO - Epoch   0| Train Loss: 0.397| Train Accuracy: 1.000 [repeated 450x across cluster]
(FLClient pid=2877651) 2025-04-11 09:19:17,263 - INFO - Epoch   2| Validation Loss: 1.053, Validation Accuracy: 0.453 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.160, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.046, Train Accuracy: 0.600
Train Loss: 1.220, Train Accuracy: 0.600
Train Loss: 1.178, Train Accuracy: 0.625
Train Loss: 1.214, Train Accuracy: 0.800
Train Loss: 1.335, Train Accuracy: 0.500
Train Loss: 1.132, Train Accuracy: 0.400
Train Loss: 1.380, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.500
Round 2
Train Loss: 1.181, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.047, Train Accuracy: 0.400
Train Loss: 1.220, Train Accuracy: 0.600
Train Loss: 1.197, Train Accuracy: 0.625
Train Loss: 1.199, Train Accuracy: 0.800
Train Loss: 1.346, Train Accuracy: 0.500
Train Loss: 1.174, Train Accuracy: 0.600
Train Loss: 1.489, Train Accuracy: 0.750
Train Loss: 1.175, Train Accuracy: 0.400
Round 3
Train Loss: 1.198, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 1.255, Train Accuracy: 0.600
Train Loss: 1.216, Train Accuracy: 0.625
Train Loss: 1.215, Train Accuracy: 0.800
Train Loss: 1.357, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.400
Train Loss: 1.559, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.400
Round 4
Train Loss: 1.258, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.034, Train Accuracy: 0.400
Train Loss: 1.260, Train Accuracy: 0.600
Train Loss: 1.221, Train Accuracy: 0.625
Train Loss: 1.222, Train Accuracy: 0.800
Train Loss: 1.397, Train Accuracy: 0.500
Train Loss: 1.143, Train Accuracy: 0.600
Train Loss: 1.582, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.400
Round 5
Train Loss: 1.220, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.283, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 0.625
Train Loss: 1.283, Train Accuracy: 0.800
Train Loss: 1.375, Train Accuracy: 0.250
Train Loss: 1.157, Train Accuracy: 0.400
Train Loss: 1.637, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.400
Round 6
Train Loss: 1.280, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.038, Train Accuracy: 0.400
Train Loss: 1.320, Train Accuracy: 0.600
Train Loss: 1.242, Train Accuracy: 0.625
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.397, Train Accuracy: 0.500
Train Loss: 1.205, Train Accuracy: 0.400
Train Loss: 1.580, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.400
Round 7
Train Loss: 1.228, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.700
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.380, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.258, Train Accuracy: 0.800
Train Loss: 1.412, Train Accuracy: 0.500
Train Loss: 1.174, Train Accuracy: 1.000
Train Loss: 1.682, Train Accuracy: 0.750
Train Loss: 1.227, Train Accuracy: 0.500
Round 8
Train Loss: 1.250, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.700
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 1.320, Train Accuracy: 0.600
Train Loss: 1.229, Train Accuracy: 0.625
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.466, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.400
Train Loss: 1.699, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.500
Round 9
Train Loss: 1.294, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.040, Train Accuracy: 0.400
Train Loss: 1.333, Train Accuracy: 0.600
Train Loss: 1.232, Train Accuracy: 0.625
Train Loss: 1.307, Train Accuracy: 0.800
Train Loss: 1.415, Train Accuracy: 0.500
Train Loss: 1.152, Train Accuracy: 0.800
Train Loss: 1.663, Train Accuracy: 0.750
Train Loss: 1.208, Train Accuracy: 0.700
Round 10
Train Loss: 1.370, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.700
Train Loss: 1.024, Train Accuracy: 0.400
Train Loss: 1.369, Train Accuracy: 0.600
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.248, Train Accuracy: 0.800
Train Loss: 1.431, Train Accuracy: 0.250
Train Loss: 1.172, Train Accuracy: 0.400
Train Loss: 1.700, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.500
Round 11
Train Loss: 1.434, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.600
Train Loss: 1.018, Train Accuracy: 0.200
Train Loss: 1.324, Train Accuracy: 0.600
Train Loss: 1.210, Train Accuracy: 0.625
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.457, Train Accuracy: 0.500
Train Loss: 1.135, Train Accuracy: 0.600
Train Loss: 1.747, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.200
Round 12
Train Loss: 1.286, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.600
Train Loss: 1.021, Train Accuracy: 0.400
Train Loss: 1.405, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.254, Train Accuracy: 0.800
Train Loss: 1.488, Train Accuracy: 0.250
Train Loss: 1.138, Train Accuracy: 0.600
Train Loss: 1.786, Train Accuracy: 0.750
Train Loss: 1.175, Train Accuracy: 0.300
Round 13
Train Loss: 1.205, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.700
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.343, Train Accuracy: 0.600
Train Loss: 1.249, Train Accuracy: 0.625
Train Loss: 1.329, Train Accuracy: 0.800
Train Loss: 1.515, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.600
Train Loss: 1.877, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.300
Round 14
Train Loss: 1.252, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.400
Train Loss: 1.007, Train Accuracy: 0.000
Train Loss: 1.384, Train Accuracy: 0.600
Train Loss: 1.222, Train Accuracy: 0.625
Train Loss: 1.255, Train Accuracy: 0.800
Train Loss: 1.502, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.600
Train Loss: 1.823, Train Accuracy: 0.750
Train Loss: 1.225, Train Accuracy: 0.500
Round 15
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.400
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.392, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.625
Train Loss: 1.329, Train Accuracy: 0.800
Train Loss: 1.478, Train Accuracy: 1.000
Train Loss: 1.125, Train Accuracy: 0.400
Train Loss: 1.735, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 0.500
Round 16
Train Loss: 1.279, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Train Loss: 1.008, Train Accuracy: 0.600
Train Loss: 1.416, Train Accuracy: 0.600
Train Loss: 1.218, Train Accuracy: 0.750
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.480, Train Accuracy: 0.750
Train Loss: 1.213, Train Accuracy: 0.200
Train Loss: 1.823, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.400
Round 17
Train Loss: 1.232, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.500
Train Loss: 1.005, Train Accuracy: 0.400
Train Loss: 1.364, Train Accuracy: 0.600
Train Loss: 1.266, Train Accuracy: 0.750
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.465, Train Accuracy: 1.000
Train Loss: 1.163, Train Accuracy: 0.400
Train Loss: 1.928, Train Accuracy: 0.750
Train Loss: 1.215, Train Accuracy: 0.600
Round 18
Train Loss: 1.315, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.500
Train Loss: 1.004, Train Accuracy: 0.400
Train Loss: 1.329, Train Accuracy: 0.600
Train Loss: 1.234, Train Accuracy: 0.625
Train Loss: 1.234, Train Accuracy: 0.800
Train Loss: 1.512, Train Accuracy: 0.750
Train Loss: 1.148, Train Accuracy: 0.600
Train Loss: 1.948, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.500
Round 19
Train Loss: 1.342, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.500
Train Loss: 1.002, Train Accuracy: 0.600
Train Loss: 1.445, Train Accuracy: 0.600
Train Loss: 1.221, Train Accuracy: 0.750
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.514, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.400
Train Loss: 1.727, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.400
Round 20
Train Loss: 1.417, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.600
Train Loss: 0.990, Train Accuracy: 0.600
Train Loss: 1.426, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.276, Train Accuracy: 0.800
Train Loss: 1.443, Train Accuracy: 0.500
Train Loss: 1.141, Train Accuracy: 0.400
Train Loss: 1.893, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.700
Round 21
Train Loss: 1.324, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 0.995, Train Accuracy: 0.600
Train Loss: 1.399, Train Accuracy: 0.600
Train Loss: 1.181, Train Accuracy: 0.625
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.401, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.600
Train Loss: 1.941, Train Accuracy: 0.750
Train Loss: 1.219, Train Accuracy: 0.600
Round 22
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.500
Train Loss: 1.012, Train Accuracy: 0.600
Train Loss: 1.366, Train Accuracy: 0.600
Train Loss: 1.175, Train Accuracy: 0.625
Train Loss: 1.262, Train Accuracy: 0.800
Train Loss: 1.443, Train Accuracy: 0.250
Train Loss: 1.085, Train Accuracy: 0.600
Train Loss: 1.971, Train Accuracy: 0.750
Train Loss: 1.138, Train Accuracy: 0.400
Round 23
Train Loss: 1.151, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.500
Train Loss: 0.985, Train Accuracy: 0.600
Train Loss: 1.336, Train Accuracy: 0.600
Train Loss: 1.212, Train Accuracy: 0.625
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.491, Train Accuracy: 0.750
Train Loss: 1.104, Train Accuracy: 0.600
Train Loss: 2.007, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.400
Round 24
Train Loss: 1.208, Train Accuracy: 0.750
Train Loss: 1.033, Train Accuracy: 0.500
Train Loss: 0.995, Train Accuracy: 0.200
Train Loss: 1.401, Train Accuracy: 0.600
Train Loss: 1.191, Train Accuracy: 0.750
Train Loss: 1.410, Train Accuracy: 0.800
Train Loss: 1.645, Train Accuracy: 0.500
Train Loss: 1.175, Train Accuracy: 0.400
Train Loss: 1.969, Train Accuracy: 0.750
Train Loss: 1.220, Train Accuracy: 0.400
Round 25
Train Loss: 1.335, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.500
Train Loss: 0.987, Train Accuracy: 0.600
Train Loss: 1.338, Train Accuracy: 0.600
Train Loss: 1.195, Train Accuracy: 0.625
Train Loss: 1.321, Train Accuracy: 0.800
Train Loss: 1.481, Train Accuracy: 0.500
Train Loss: 1.126, Train Accuracy: 0.600
Train Loss: 1.934, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.600
Round 26
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 1.012, Train Accuracy: 0.700
Train Loss: 0.967, Train Accuracy: 0.600
Train Loss: 1.382, Train Accuracy: 1.000
Train Loss: 1.229, Train Accuracy: 0.625
Train Loss: 1.264, Train Accuracy: 0.800
Train Loss: 1.506, Train Accuracy: 0.500
Train Loss: 1.154, Train Accuracy: 0.400
Train Loss: 1.961, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.700
Round 27
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 1.012, Train Accuracy: 0.800
Train Loss: 0.997, Train Accuracy: 0.600
Train Loss: 1.516, Train Accuracy: 1.000
Train Loss: 1.190, Train Accuracy: 0.625
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.525, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.600
Train Loss: 2.011, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.600
Round 28
Train Loss: 1.104, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.500
Train Loss: 0.964, Train Accuracy: 0.600
Train Loss: 1.419, Train Accuracy: 1.000
Train Loss: 1.234, Train Accuracy: 0.625
Train Loss: 1.368, Train Accuracy: 0.800
Train Loss: 1.428, Train Accuracy: 0.500
Train Loss: 1.150, Train Accuracy: 0.600
Train Loss: 2.078, Train Accuracy: 0.750
Train Loss: 1.193, Train Accuracy: 0.600
Round 29
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 0.997, Train Accuracy: 0.600
Train Loss: 1.364, Train Accuracy: 1.000
Train Loss: 1.151, Train Accuracy: 0.750
Train Loss: 1.226, Train Accuracy: 0.800
Train Loss: 1.420, Train Accuracy: 1.000
Train Loss: 1.194, Train Accuracy: 0.400
Train Loss: 1.984, Train Accuracy: 0.750
Train Loss: 1.107, Train Accuracy: 0.500
Round 30
Train Loss: 1.370, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.500
Train Loss: 0.977, Train Accuracy: 0.400
Train Loss: 1.445, Train Accuracy: 0.800
Train Loss: 1.179, Train Accuracy: 0.750
Train Loss: 1.424, Train Accuracy: 0.800
Train Loss: 1.668, Train Accuracy: 0.250
Train Loss: 1.136, Train Accuracy: 0.600
Train Loss: 1.960, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.600
Round 31
Train Loss: 1.347, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.600
Train Loss: 0.988, Train Accuracy: 0.800
Train Loss: 1.376, Train Accuracy: 0.800
Train Loss: 1.191, Train Accuracy: 0.750
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.463, Train Accuracy: 0.750
Train Loss: 1.251, Train Accuracy: 0.600
Train Loss: 1.872, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.500
Round 32
Train Loss: 1.354, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.500
Train Loss: 0.982, Train Accuracy: 0.800
Train Loss: 1.457, Train Accuracy: 0.800
Train Loss: 1.169, Train Accuracy: 0.750
Train Loss: 1.371, Train Accuracy: 0.800
Train Loss: 1.562, Train Accuracy: 1.000
Train Loss: 1.078, Train Accuracy: 0.400
Train Loss: 1.780, Train Accuracy: 0.750
Train Loss: 1.103, Train Accuracy: 0.500
Round 33
Train Loss: 1.252, Train Accuracy: 0.750
Train Loss: 0.989, Train Accuracy: 0.700
Train Loss: 0.970, Train Accuracy: 0.600
Train Loss: 1.308, Train Accuracy: 1.000
Train Loss: 1.135, Train Accuracy: 0.750
Train Loss: 1.246, Train Accuracy: 0.800
Train Loss: 1.475, Train Accuracy: 0.500
Train Loss: 1.088, Train Accuracy: 0.200
Train Loss: 1.914, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.400
Round 34
Train Loss: 1.269, Train Accuracy: 0.750
Train Loss: 0.979, Train Accuracy: 0.700
Train Loss: 0.955, Train Accuracy: 0.600
Train Loss: 1.456, Train Accuracy: 1.000
Train Loss: 1.203, Train Accuracy: 0.625
Train Loss: 1.239, Train Accuracy: 0.800
Train Loss: 1.393, Train Accuracy: 1.000
Train Loss: 1.117, Train Accuracy: 0.800
Train Loss: 2.081, Train Accuracy: 0.750
Train Loss: 1.084, Train Accuracy: 0.400
Round 35
Train Loss: 1.167, Train Accuracy: 0.750
Train Loss: 0.985, Train Accuracy: 0.500
Train Loss: 0.937, Train Accuracy: 0.600
Train Loss: 1.396, Train Accuracy: 1.000
Train Loss: 1.201, Train Accuracy: 0.750
Train Loss: 1.319, Train Accuracy: 0.800
Train Loss: 1.482, Train Accuracy: 1.000
Train Loss: 1.068, Train Accuracy: 0.600
Train Loss: 2.057, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.700
Round 36
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 0.973, Train Accuracy: 0.300
Train Loss: 0.946, Train Accuracy: 0.200
Train Loss: 1.317, Train Accuracy: 1.000
Train Loss: 1.219, Train Accuracy: 0.500
Train Loss: 1.197, Train Accuracy: 0.800
Train Loss: 1.361, Train Accuracy: 1.000
Train Loss: 1.158, Train Accuracy: 0.600
Train Loss: 1.992, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.700
Round 37
Train Loss: 1.283, Train Accuracy: 0.750
Train Loss: 0.978, Train Accuracy: 0.300
Train Loss: 0.925, Train Accuracy: 0.600
Train Loss: 1.421, Train Accuracy: 1.000
Train Loss: 1.146, Train Accuracy: 0.625
Train Loss: 1.213, Train Accuracy: 0.800
Train Loss: 1.546, Train Accuracy: 0.500
Train Loss: 1.143, Train Accuracy: 0.800
Train Loss: 1.957, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.500
Round 38
Train Loss: 1.161, Train Accuracy: 0.750
Train Loss: 0.963, Train Accuracy: 0.600
Train Loss: 0.978, Train Accuracy: 0.800
Train Loss: 1.422, Train Accuracy: 0.800
Train Loss: 1.122, Train Accuracy: 0.500
Train Loss: 1.405, Train Accuracy: 0.800
Train Loss: 1.460, Train Accuracy: 0.750
Train Loss: 1.094, Train Accuracy: 0.800
Train Loss: 2.178, Train Accuracy: 0.750
Train Loss: 1.259, Train Accuracy: 0.600
Round 39
Train Loss: 1.301, Train Accuracy: 0.750
Train Loss: 0.983, Train Accuracy: 0.600
Train Loss: 0.921, Train Accuracy: 0.600
Train Loss: 1.255, Train Accuracy: 1.000
Train Loss: 1.158, Train Accuracy: 0.750
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.651, Train Accuracy: 1.000
Train Loss: 1.027, Train Accuracy: 0.800
Train Loss: 1.980, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.600
Round 40
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 0.956, Train Accuracy: 0.500
Train Loss: 0.981, Train Accuracy: 0.600
Train Loss: 1.393, Train Accuracy: 0.800
Train Loss: 1.159, Train Accuracy: 0.375
Train Loss: 1.235, Train Accuracy: 0.800
Train Loss: 1.421, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.600
Train Loss: 2.036, Train Accuracy: 1.000
Train Loss: 1.066, Train Accuracy: 0.600
Round 41
Train Loss: 1.316, Train Accuracy: 0.750
Train Loss: 0.951, Train Accuracy: 0.700
Train Loss: 0.936, Train Accuracy: 0.600
Train Loss: 1.299, Train Accuracy: 1.000
Train Loss: 1.128, Train Accuracy: 0.750
Train Loss: 1.234, Train Accuracy: 0.800
Train Loss: 1.521, Train Accuracy: 1.000
Train Loss: 1.234, Train Accuracy: 0.800
Train Loss: 1.733, Train Accuracy: 0.750
Train Loss: 1.283, Train Accuracy: 0.600
Round 42
Train Loss: 1.294, Train Accuracy: 0.750
Train Loss: 0.948, Train Accuracy: 0.500
Train Loss: 0.955, Train Accuracy: 0.600
Train Loss: 1.697, Train Accuracy: 0.800
Train Loss: 1.155, Train Accuracy: 0.750
Train Loss: 1.225, Train Accuracy: 0.800
Train Loss: 1.496, Train Accuracy: 0.750
Train Loss: 1.259, Train Accuracy: 0.800
Train Loss: 1.746, Train Accuracy: 0.750
Train Loss: 1.103, Train Accuracy: 0.800
Round 43
Train Loss: 1.427, Train Accuracy: 0.750
Train Loss: 0.946, Train Accuracy: 0.600
Train Loss: 0.953, Train Accuracy: 1.000
Train Loss: 1.476, Train Accuracy: 1.000
Train Loss: 1.111, Train Accuracy: 0.875
Train Loss: 1.207, Train Accuracy: 0.800
Train Loss: 1.779, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.600
Train Loss: 2.156, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.700
Round 44
Train Loss: 1.113, Train Accuracy: 0.750
Train Loss: 0.946, Train Accuracy: 0.500
Train Loss: 0.958, Train Accuracy: 0.400
Train Loss: 1.580, Train Accuracy: 0.600
Train Loss: 1.091, Train Accuracy: 0.500
Train Loss: 1.194, Train Accuracy: 0.800
Train Loss: 1.475, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.600
Train Loss: 2.155, Train Accuracy: 0.750
Train Loss: 1.017, Train Accuracy: 0.500
Round 45
Train Loss: 1.345, Train Accuracy: 0.750
Train Loss: 0.947, Train Accuracy: 0.600
Train Loss: 0.892, Train Accuracy: 0.800
Train Loss: 1.469, Train Accuracy: 1.000
Train Loss: 1.083, Train Accuracy: 0.875
Train Loss: 1.348, Train Accuracy: 0.800
Train Loss: 1.620, Train Accuracy: 0.500
Train Loss: 0.960, Train Accuracy: 0.600
Train Loss: 2.131, Train Accuracy: 1.000
Train Loss: 1.057, Train Accuracy: 0.700
Round 46
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 0.945, Train Accuracy: 0.600
Train Loss: 0.946, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.600
Train Loss: 1.126, Train Accuracy: 0.875
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.745, Train Accuracy: 0.500
Train Loss: 1.166, Train Accuracy: 0.600
Train Loss: 2.230, Train Accuracy: 1.000
Train Loss: 1.368, Train Accuracy: 0.500
Round 47
Train Loss: 1.103, Train Accuracy: 0.750
Train Loss: 0.930, Train Accuracy: 0.700
Train Loss: 0.945, Train Accuracy: 0.400
Train Loss: 1.593, Train Accuracy: 0.800
Train Loss: 1.130, Train Accuracy: 0.625
Train Loss: 1.266, Train Accuracy: 0.800
Train Loss: 1.515, Train Accuracy: 0.500
Train Loss: 1.020, Train Accuracy: 0.800
Train Loss: 1.731, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.700
Round 48
Train Loss: 1.111, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.300
Train Loss: 0.892, Train Accuracy: 0.800
Train Loss: 1.432, Train Accuracy: 1.000
Train Loss: 1.158, Train Accuracy: 0.625
Train Loss: 1.257, Train Accuracy: 0.800
Train Loss: 1.525, Train Accuracy: 0.750

(FLClient pid=2878542) 2025-04-11 09:19:48,348 - INFO - Epoch   2| Train Loss: 0.712| Train Accuracy: 0.750 [repeated 362x across cluster]
(FLClient pid=2878542) 2025-04-11 09:19:48,360 - INFO - Epoch   2| Validation Loss: 1.275, Validation Accuracy: 0.295 [repeated 121x across cluster]
(FLClient pid=2878542) 2025-04-11 09:19:53,579 - INFO - Epoch   0| Train Loss: 1.015| Train Accuracy: 0.500 [repeated 388x across cluster]
(FLClient pid=2878801) 2025-04-11 09:19:53,266 - INFO - Epoch   2| Validation Loss: 1.215, Validation Accuracy: 0.156 [repeated 129x across cluster]
(FLClient pid=2878542) 2025-04-11 09:19:58,717 - INFO - Epoch   2| Train Loss: 0.597| Train Accuracy: 0.750 [repeated 452x across cluster]
(FLClient pid=2878801) 2025-04-11 09:19:58,386 - INFO - Epoch   2| Validation Loss: 1.158, Validation Accuracy: 0.250 [repeated 150x across cluster]
(FLClient pid=2878542) 2025-04-11 09:20:03,819 - INFO - Epoch   2| Train Loss: 0.818| Train Accuracy: 0.500 [repeated 450x across cluster]
(FLClient pid=2878801) 2025-04-11 09:20:03,486 - INFO - Epoch   2| Validation Loss: 1.197, Validation Accuracy: 0.172 [repeated 150x across cluster]
(FLClient pid=2878542) 2025-04-11 09:20:08,945 - INFO - Epoch   2| Train Loss: 0.554| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2878542) 2025-04-11 09:20:08,953 - INFO - Epoch   2| Validation Loss: 1.124, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2878542) 2025-04-11 09:20:14,040 - INFO - Epoch   2| Train Loss: 0.361| Train Accuracy: 1.000 [repeated 450x across cluster]
(FLClient pid=2878542) 2025-04-11 09:20:14,048 - INFO - Epoch   2| Validation Loss: 1.309, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2878542) 2025-04-11 09:20:19,100 - INFO - Epoch   0| Train Loss: 0.816| Train Accuracy: 0.750 [repeated 448x across cluster]
(FLClient pid=2878801) 2025-04-11 09:20:18,794 - INFO - Epoch   2| Validation Loss: 1.228, Validation Accuracy: 0.250 [repeated 149x across cluster]

Training done
Round 1
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.066, Train Accuracy: 0.400
Train Loss: 1.246, Train Accuracy: 0.600
Train Loss: 1.196, Train Accuracy: 0.625
Train Loss: 1.234, Train Accuracy: 0.800
Train Loss: 1.321, Train Accuracy: 1.000
Train Loss: 1.144, Train Accuracy: 0.600
Train Loss: 1.405, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.500
Round 2
Train Loss: 1.261, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.048, Train Accuracy: 0.400
Train Loss: 1.254, Train Accuracy: 0.600
Train Loss: 1.193, Train Accuracy: 0.625
Train Loss: 1.251, Train Accuracy: 0.800
Train Loss: 1.360, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 0.400
Train Loss: 1.497, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.300
Round 3
Train Loss: 1.280, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.600
Train Loss: 1.043, Train Accuracy: 0.400
Train Loss: 1.279, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.625
Train Loss: 1.242, Train Accuracy: 0.800
Train Loss: 1.400, Train Accuracy: 0.500
Train Loss: 1.147, Train Accuracy: 0.600
Train Loss: 1.523, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.700
Round 4
Train Loss: 1.348, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.032, Train Accuracy: 0.400
Train Loss: 1.283, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.223, Train Accuracy: 0.800
Train Loss: 1.404, Train Accuracy: 0.500
Train Loss: 1.175, Train Accuracy: 0.600
Train Loss: 1.553, Train Accuracy: 0.750
Train Loss: 1.208, Train Accuracy: 0.400
Round 5
Train Loss: 1.267, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.027, Train Accuracy: 0.600
Train Loss: 1.385, Train Accuracy: 0.600
Train Loss: 1.233, Train Accuracy: 0.625
Train Loss: 1.321, Train Accuracy: 0.800
Train Loss: 1.408, Train Accuracy: 0.500
Train Loss: 1.204, Train Accuracy: 0.800
Train Loss: 1.590, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.300
Round 6
Train Loss: 1.283, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.400
Train Loss: 1.348, Train Accuracy: 0.600
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.420, Train Accuracy: 0.500
Train Loss: 1.149, Train Accuracy: 0.400
Train Loss: 1.712, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.500
Round 7
Train Loss: 1.366, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.600
Train Loss: 1.032, Train Accuracy: 0.600
Train Loss: 1.332, Train Accuracy: 0.600
Train Loss: 1.287, Train Accuracy: 0.625
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.473, Train Accuracy: 1.000
Train Loss: 1.170, Train Accuracy: 0.600
Train Loss: 1.670, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.400
Round 8
Train Loss: 1.330, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.500
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 1.400, Train Accuracy: 0.800
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.424, Train Accuracy: 0.250
Train Loss: 1.172, Train Accuracy: 0.200
Train Loss: 1.792, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.500
Round 9
Train Loss: 1.266, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.700
Train Loss: 1.021, Train Accuracy: 0.400
Train Loss: 1.366, Train Accuracy: 0.600
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.295, Train Accuracy: 0.800
Train Loss: 1.471, Train Accuracy: 0.500
Train Loss: 1.182, Train Accuracy: 0.600
Train Loss: 1.763, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.500
Round 10
Train Loss: 1.272, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.500
Train Loss: 1.034, Train Accuracy: 0.400
Train Loss: 1.413, Train Accuracy: 0.800
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.265, Train Accuracy: 0.800
Train Loss: 1.489, Train Accuracy: 0.500
Train Loss: 1.172, Train Accuracy: 0.800
Train Loss: 1.790, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.400
Round 11
Train Loss: 1.339, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.500
Train Loss: 1.024, Train Accuracy: 0.600
Train Loss: 1.375, Train Accuracy: 0.600
Train Loss: 1.229, Train Accuracy: 0.625
Train Loss: 1.307, Train Accuracy: 0.800
Train Loss: 1.470, Train Accuracy: 0.500
Train Loss: 1.202, Train Accuracy: 0.600
Train Loss: 1.789, Train Accuracy: 0.750
Train Loss: 1.209, Train Accuracy: 0.600
Round 12
Train Loss: 1.389, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.700
Train Loss: 1.031, Train Accuracy: 0.400
Train Loss: 1.360, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.342, Train Accuracy: 0.800
Train Loss: 1.512, Train Accuracy: 0.500
Train Loss: 1.220, Train Accuracy: 0.600
Train Loss: 1.725, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.600
Round 13
Train Loss: 1.279, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.600
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.411, Train Accuracy: 0.800
Train Loss: 1.239, Train Accuracy: 0.625
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.493, Train Accuracy: 0.500
Train Loss: 1.183, Train Accuracy: 0.800
Train Loss: 1.799, Train Accuracy: 0.750
Train Loss: 1.215, Train Accuracy: 0.600
Round 14
Train Loss: 1.325, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.500
Train Loss: 1.013, Train Accuracy: 0.400
Train Loss: 1.345, Train Accuracy: 0.600
Train Loss: 1.215, Train Accuracy: 0.625
Train Loss: 1.393, Train Accuracy: 0.800
Train Loss: 1.467, Train Accuracy: 0.750
Train Loss: 1.235, Train Accuracy: 0.800
Train Loss: 1.809, Train Accuracy: 0.750
Train Loss: 1.216, Train Accuracy: 0.400
Round 15
Train Loss: 1.298, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.600
Train Loss: 1.035, Train Accuracy: 0.600
Train Loss: 1.397, Train Accuracy: 0.600
Train Loss: 1.276, Train Accuracy: 0.750
Train Loss: 1.302, Train Accuracy: 0.800
Train Loss: 1.468, Train Accuracy: 0.500
Train Loss: 1.193, Train Accuracy: 0.400
Train Loss: 2.039, Train Accuracy: 0.750
Train Loss: 1.252, Train Accuracy: 0.800
Round 16
Train Loss: 1.340, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.600
Train Loss: 1.009, Train Accuracy: 0.600
Train Loss: 1.323, Train Accuracy: 0.600
Train Loss: 1.195, Train Accuracy: 0.625
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.471, Train Accuracy: 0.500
Train Loss: 1.266, Train Accuracy: 0.800
Train Loss: 1.936, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.600
Round 17
Train Loss: 1.211, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 1.404, Train Accuracy: 0.600
Train Loss: 1.234, Train Accuracy: 0.625
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.526, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.200
Train Loss: 1.903, Train Accuracy: 0.750
Train Loss: 1.139, Train Accuracy: 0.300
Round 18
Train Loss: 1.361, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.500
Train Loss: 1.013, Train Accuracy: 0.400
Train Loss: 1.372, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.750
Train Loss: 1.298, Train Accuracy: 0.800
Train Loss: 1.482, Train Accuracy: 0.500
Train Loss: 1.153, Train Accuracy: 0.600
Train Loss: 1.928, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.500
Round 19
Train Loss: 1.362, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.500
Train Loss: 1.018, Train Accuracy: 0.400
Train Loss: 1.340, Train Accuracy: 0.600
Train Loss: 1.222, Train Accuracy: 0.875
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.449, Train Accuracy: 0.500
Train Loss: 1.154, Train Accuracy: 0.600
Train Loss: 1.848, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.600
Round 20
Train Loss: 1.424, Train Accuracy: 0.750
Train Loss: 1.040, Train Accuracy: 0.600
Train Loss: 0.997, Train Accuracy: 0.400
Train Loss: 1.358, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.625
Train Loss: 1.418, Train Accuracy: 0.800
Train Loss: 1.483, Train Accuracy: 0.500
Train Loss: 1.119, Train Accuracy: 0.200
Train Loss: 1.909, Train Accuracy: 0.750
Train Loss: 1.260, Train Accuracy: 0.700
Round 21
Train Loss: 1.413, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.600
Train Loss: 1.000, Train Accuracy: 0.400
Train Loss: 1.402, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.276, Train Accuracy: 0.800
Train Loss: 1.439, Train Accuracy: 0.500
Train Loss: 1.178, Train Accuracy: 0.400
Train Loss: 1.786, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.500
Round 22
Train Loss: 1.503, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.400
Train Loss: 0.986, Train Accuracy: 0.400
Train Loss: 1.384, Train Accuracy: 0.600
Train Loss: 1.184, Train Accuracy: 0.625
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.506, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.600
Train Loss: 1.757, Train Accuracy: 0.750
Train Loss: 1.121, Train Accuracy: 0.400
Round 23
Train Loss: 1.293, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.500
Train Loss: 0.983, Train Accuracy: 0.400
Train Loss: 1.375, Train Accuracy: 0.600
Train Loss: 1.200, Train Accuracy: 0.625
Train Loss: 1.418, Train Accuracy: 0.800
Train Loss: 1.494, Train Accuracy: 0.500
Train Loss: 1.177, Train Accuracy: 0.600
Train Loss: 1.999, Train Accuracy: 0.750
Train Loss: 1.108, Train Accuracy: 0.500
Round 24
Train Loss: 1.345, Train Accuracy: 0.750
Train Loss: 1.025, Train Accuracy: 0.600
Train Loss: 0.997, Train Accuracy: 0.400
Train Loss: 1.479, Train Accuracy: 0.800
Train Loss: 1.232, Train Accuracy: 0.625
Train Loss: 1.258, Train Accuracy: 0.800
Train Loss: 1.551, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.400
Train Loss: 1.876, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.700
Round 25
Train Loss: 1.432, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.500
Train Loss: 0.983, Train Accuracy: 0.400
Train Loss: 1.412, Train Accuracy: 0.600
Train Loss: 1.210, Train Accuracy: 0.750
Train Loss: 1.388, Train Accuracy: 0.800
Train Loss: 1.510, Train Accuracy: 0.750
Train Loss: 1.132, Train Accuracy: 0.600
Train Loss: 1.849, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.600
Round 26
Train Loss: 1.354, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.500
Train Loss: 0.978, Train Accuracy: 0.600
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.256, Train Accuracy: 0.625
Train Loss: 1.286, Train Accuracy: 0.800
Train Loss: 1.486, Train Accuracy: 0.500
Train Loss: 1.215, Train Accuracy: 0.800
Train Loss: 1.793, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.700
Round 27
Train Loss: 1.283, Train Accuracy: 0.750
Train Loss: 1.013, Train Accuracy: 0.500
Train Loss: 0.985, Train Accuracy: 0.600
Train Loss: 1.315, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.750
Train Loss: 1.241, Train Accuracy: 0.800
Train Loss: 1.635, Train Accuracy: 0.750
Train Loss: 1.105, Train Accuracy: 0.600
Train Loss: 2.094, Train Accuracy: 0.750
Train Loss: 1.129, Train Accuracy: 0.700
Round 28
Train Loss: 1.263, Train Accuracy: 0.750
Train Loss: 1.008, Train Accuracy: 0.500
Train Loss: 0.988, Train Accuracy: 0.800
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.186, Train Accuracy: 0.750
Train Loss: 1.281, Train Accuracy: 0.800
Train Loss: 1.473, Train Accuracy: 1.000
Train Loss: 1.125, Train Accuracy: 0.800
Train Loss: 2.072, Train Accuracy: 0.750
Train Loss: 1.158, Train Accuracy: 0.500
Round 29
Train Loss: 1.280, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.500
Train Loss: 0.985, Train Accuracy: 0.600
Train Loss: 1.421, Train Accuracy: 1.000
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.214, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.400
Train Loss: 1.826, Train Accuracy: 0.750
Train Loss: 1.099, Train Accuracy: 0.400
Round 30
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.600
Train Loss: 1.003, Train Accuracy: 0.400
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.184, Train Accuracy: 0.750
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.474, Train Accuracy: 1.000
Train Loss: 1.176, Train Accuracy: 0.400
Train Loss: 1.826, Train Accuracy: 0.750
Train Loss: 1.086, Train Accuracy: 0.600
Round 31
Train Loss: 1.321, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.600
Train Loss: 0.966, Train Accuracy: 0.600
Train Loss: 1.348, Train Accuracy: 0.800
Train Loss: 1.161, Train Accuracy: 0.750
Train Loss: 1.433, Train Accuracy: 0.800
Train Loss: 1.508, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.600
Train Loss: 2.034, Train Accuracy: 0.750
Train Loss: 1.271, Train Accuracy: 0.600
Round 32
Train Loss: 1.431, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.800
Train Loss: 1.011, Train Accuracy: 0.600
Train Loss: 1.394, Train Accuracy: 1.000
Train Loss: 1.178, Train Accuracy: 0.625
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.572, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.600
Train Loss: 2.015, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.700
Round 33
Train Loss: 1.235, Train Accuracy: 0.750
Train Loss: 0.988, Train Accuracy: 0.600
Train Loss: 0.985, Train Accuracy: 0.600
Train Loss: 1.375, Train Accuracy: 0.800
Train Loss: 1.169, Train Accuracy: 0.625
Train Loss: 1.321, Train Accuracy: 0.800
Train Loss: 1.586, Train Accuracy: 1.000
Train Loss: 1.073, Train Accuracy: 0.800
Train Loss: 2.092, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Round 34
Train Loss: 1.430, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.700
Train Loss: 0.963, Train Accuracy: 0.800
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.236, Train Accuracy: 0.625
Train Loss: 1.414, Train Accuracy: 0.800
Train Loss: 1.489, Train Accuracy: 0.750
Train Loss: 1.227, Train Accuracy: 0.400
Train Loss: 1.901, Train Accuracy: 0.750
Train Loss: 1.224, Train Accuracy: 0.700
Round 35
Train Loss: 1.031, Train Accuracy: 0.750
Train Loss: 0.980, Train Accuracy: 0.700
Train Loss: 0.938, Train Accuracy: 1.000
Train Loss: 1.422, Train Accuracy: 1.000
Train Loss: 1.126, Train Accuracy: 0.750
Train Loss: 1.363, Train Accuracy: 0.800
Train Loss: 1.429, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.400
Train Loss: 1.837, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.500
Round 36
Train Loss: 1.268, Train Accuracy: 0.750
Train Loss: 0.972, Train Accuracy: 0.600
Train Loss: 0.939, Train Accuracy: 0.600
Train Loss: 1.352, Train Accuracy: 0.800
Train Loss: 1.196, Train Accuracy: 0.750
Train Loss: 1.425, Train Accuracy: 1.000
Train Loss: 1.432, Train Accuracy: 1.000
Train Loss: 1.110, Train Accuracy: 0.600
Train Loss: 2.131, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.600
Round 37
Train Loss: 1.130, Train Accuracy: 0.750
Train Loss: 0.963, Train Accuracy: 0.600
Train Loss: 0.942, Train Accuracy: 0.200
Train Loss: 1.412, Train Accuracy: 0.800
Train Loss: 1.149, Train Accuracy: 0.625
Train Loss: 1.304, Train Accuracy: 0.800
Train Loss: 1.488, Train Accuracy: 0.750
Train Loss: 1.124, Train Accuracy: 0.600
Train Loss: 2.059, Train Accuracy: 0.750
Train Loss: 1.092, Train Accuracy: 0.600
Round 38
Train Loss: 1.435, Train Accuracy: 0.750
Train Loss: 0.976, Train Accuracy: 0.600
Train Loss: 0.915, Train Accuracy: 1.000
Train Loss: 1.301, Train Accuracy: 0.800
Train Loss: 1.197, Train Accuracy: 0.625
Train Loss: 1.346, Train Accuracy: 0.800
Train Loss: 1.427, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 2.368, Train Accuracy: 1.000
Train Loss: 1.240, Train Accuracy: 0.500
Round 39
Train Loss: 1.276, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.600
Train Loss: 0.961, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.600
Train Loss: 1.136, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.800
Train Loss: 1.495, Train Accuracy: 1.000
Train Loss: 1.088, Train Accuracy: 0.600
Train Loss: 2.104, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 0.900
Round 40
Train Loss: 1.200, Train Accuracy: 0.750
Train Loss: 0.971, Train Accuracy: 0.800
Train Loss: 0.981, Train Accuracy: 0.600
Train Loss: 1.457, Train Accuracy: 0.800
Train Loss: 1.228, Train Accuracy: 0.250
Train Loss: 1.326, Train Accuracy: 1.000
Train Loss: 1.488, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.200
Train Loss: 1.805, Train Accuracy: 0.750
Train Loss: 1.352, Train Accuracy: 0.500
Round 41
Train Loss: 1.285, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 0.915, Train Accuracy: 0.800
Train Loss: 1.417, Train Accuracy: 0.800
Train Loss: 1.214, Train Accuracy: 0.625
Train Loss: 1.249, Train Accuracy: 0.800
Train Loss: 1.520, Train Accuracy: 1.000
Train Loss: 1.185, Train Accuracy: 0.800
Train Loss: 2.233, Train Accuracy: 1.000
Train Loss: 1.075, Train Accuracy: 0.900
Round 42
Train Loss: 1.321, Train Accuracy: 1.000
Train Loss: 0.991, Train Accuracy: 0.600
Train Loss: 0.926, Train Accuracy: 0.800
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.104, Train Accuracy: 0.875
Train Loss: 1.321, Train Accuracy: 0.800
Train Loss: 1.575, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.400
Train Loss: 2.098, Train Accuracy: 1.000
Train Loss: 1.077, Train Accuracy: 0.800
Round 43
Train Loss: 1.267, Train Accuracy: 0.750
Train Loss: 0.946, Train Accuracy: 0.800
Train Loss: 0.914, Train Accuracy: 0.400
Train Loss: 1.391, Train Accuracy: 1.000
Train Loss: 1.222, Train Accuracy: 0.625
Train Loss: 1.193, Train Accuracy: 0.800
Train Loss: 1.705, Train Accuracy: 0.500
Train Loss: 1.077, Train Accuracy: 1.000
Train Loss: 1.628, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.800
Round 44
Train Loss: 1.262, Train Accuracy: 0.500
Train Loss: 1.040, Train Accuracy: 0.600
Train Loss: 0.951, Train Accuracy: 0.600
Train Loss: 1.248, Train Accuracy: 0.800
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.256, Train Accuracy: 0.800
Train Loss: 1.517, Train Accuracy: 0.750
Train Loss: 1.389, Train Accuracy: 0.600
Train Loss: 2.049, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.800
Round 45
Train Loss: 1.146, Train Accuracy: 0.750
Train Loss: 1.022, Train Accuracy: 0.500
Train Loss: 0.932, Train Accuracy: 0.600
Train Loss: 1.544, Train Accuracy: 0.800
Train Loss: 1.190, Train Accuracy: 0.875
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.623, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.600
Train Loss: 1.499, Train Accuracy: 0.750
Train Loss: 1.211, Train Accuracy: 0.800
Round 46
Train Loss: 1.176, Train Accuracy: 0.750
Train Loss: 1.033, Train Accuracy: 0.600
Train Loss: 0.922, Train Accuracy: 0.600
Train Loss: 1.201, Train Accuracy: 0.600
Train Loss: 1.176, Train Accuracy: 0.625
Train Loss: 1.198, Train Accuracy: 0.800
Train Loss: 1.557, Train Accuracy: 0.750
Train Loss: 1.011, Train Accuracy: 1.000
Train Loss: 2.194, Train Accuracy: 1.000
Train Loss: 1.056, Train Accuracy: 0.700
Round 47
Train Loss: 1.141, Train Accuracy: 0.750
Train Loss: 0.950, Train Accuracy: 0.700
Train Loss: 0.875, Train Accuracy: 0.600
Train Loss: 1.325, Train Accuracy: 1.000
Train Loss: 1.118, Train Accuracy: 0.625
Train Loss: 1.163, Train Accuracy: 0.800
Train Loss: 1.711, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.600
Train Loss: 2.163, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.700
Round 48
Train Loss: 1.255, Train Accuracy: 0.750
Train Loss: 0.927, Train Accuracy: 0.600
Train Loss: 0.926, Train Accuracy: 0.600
Train Loss: 1.420, Train Accuracy: 0.400
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.456, Train Accuracy: 1.000

(FLClient pid=2879754) 2025-04-11 09:20:49,947 - INFO - Epoch   2| Train Loss: 0.764| Train Accuracy: 0.750 [repeated 362x across cluster]
(FLClient pid=2879754) 2025-04-11 09:20:49,956 - INFO - Epoch   2| Validation Loss: 1.288, Validation Accuracy: 0.295 [repeated 121x across cluster]
(FLClient pid=2879755) 2025-04-11 09:20:55,016 - INFO - Epoch   1| Train Loss: 0.953| Train Accuracy: 0.500 [repeated 389x across cluster]
(FLClient pid=2879967) 2025-04-11 09:20:54,697 - INFO - Epoch   2| Validation Loss: 1.163, Validation Accuracy: 0.156 [repeated 129x across cluster]
(FLClient pid=2879755) 2025-04-11 09:21:00,134 - INFO - Epoch   2| Train Loss: 1.018| Train Accuracy: 0.400 [repeated 451x across cluster]
(FLClient pid=2879755) 2025-04-11 09:21:00,141 - INFO - Epoch   2| Validation Loss: 1.029, Validation Accuracy: 0.467 [repeated 151x across cluster]
(FLClient pid=2879755) 2025-04-11 09:21:05,250 - INFO - Epoch   2| Train Loss: 0.857| Train Accuracy: 0.600 [repeated 450x across cluster]
(FLClient pid=2879755) 2025-04-11 09:21:05,256 - INFO - Epoch   2| Validation Loss: 0.987, Validation Accuracy: 0.467 [repeated 150x across cluster]
(FLClient pid=2879755) 2025-04-11 09:21:10,372 - INFO - Epoch   2| Train Loss: 0.848| Train Accuracy: 0.400 [repeated 450x across cluster]
(FLClient pid=2879755) 2025-04-11 09:21:10,376 - INFO - Epoch   2| Validation Loss: 0.988, Validation Accuracy: 0.467 [repeated 150x across cluster]
(FLClient pid=2879755) 2025-04-11 09:21:15,464 - INFO - Epoch   2| Train Loss: 0.922| Train Accuracy: 0.500 [repeated 450x across cluster]
(FLClient pid=2879755) 2025-04-11 09:21:15,472 - INFO - Epoch   2| Validation Loss: 0.939, Validation Accuracy: 0.467 [repeated 150x across cluster]
(FLClient pid=2879755) 2025-04-11 09:21:20,573 - INFO - Epoch   2| Train Loss: 0.755| Train Accuracy: 0.600 [repeated 450x across cluster]
(FLClient pid=2879755) 2025-04-11 09:21:20,581 - INFO - Epoch   2| Validation Loss: 0.887, Validation Accuracy: 0.556 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.288, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.064, Train Accuracy: 0.400
Train Loss: 1.255, Train Accuracy: 0.600
Train Loss: 1.190, Train Accuracy: 0.625
Train Loss: 1.265, Train Accuracy: 0.800
Train Loss: 1.350, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 0.400
Train Loss: 1.467, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.400
Round 2
Train Loss: 1.351, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.055, Train Accuracy: 0.400
Train Loss: 1.331, Train Accuracy: 0.600
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.285, Train Accuracy: 0.800
Train Loss: 1.380, Train Accuracy: 0.500
Train Loss: 1.161, Train Accuracy: 0.400
Train Loss: 1.623, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.400
Round 3
Train Loss: 1.256, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.047, Train Accuracy: 0.200
Train Loss: 1.370, Train Accuracy: 0.600
Train Loss: 1.257, Train Accuracy: 0.625
Train Loss: 1.295, Train Accuracy: 0.800
Train Loss: 1.439, Train Accuracy: 1.000
Train Loss: 1.182, Train Accuracy: 0.800
Train Loss: 1.708, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.400
Round 4
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.038, Train Accuracy: 0.200
Train Loss: 1.382, Train Accuracy: 0.600
Train Loss: 1.244, Train Accuracy: 0.625
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.441, Train Accuracy: 0.500
Train Loss: 1.152, Train Accuracy: 0.800
Train Loss: 1.805, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.500
Round 5
Train Loss: 1.355, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.400
Train Loss: 1.376, Train Accuracy: 0.600
Train Loss: 1.258, Train Accuracy: 0.625
Train Loss: 1.298, Train Accuracy: 0.800
Train Loss: 1.484, Train Accuracy: 0.250
Train Loss: 1.209, Train Accuracy: 0.200
Train Loss: 1.741, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.300
Round 6
Train Loss: 1.326, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Train Loss: 1.042, Train Accuracy: 0.400
Train Loss: 1.436, Train Accuracy: 0.600
Train Loss: 1.263, Train Accuracy: 0.625
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.508, Train Accuracy: 1.000
Train Loss: 1.205, Train Accuracy: 0.800
Train Loss: 1.825, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.400
Round 7
Train Loss: 1.421, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.033, Train Accuracy: 0.800
Train Loss: 1.389, Train Accuracy: 0.600
Train Loss: 1.263, Train Accuracy: 0.625
Train Loss: 1.388, Train Accuracy: 0.800
Train Loss: 1.465, Train Accuracy: 0.250
Train Loss: 1.200, Train Accuracy: 0.400
Train Loss: 1.798, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.300
Round 8
Train Loss: 1.387, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.390, Train Accuracy: 0.600
Train Loss: 1.252, Train Accuracy: 0.625
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.538, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.600
Train Loss: 1.958, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 0.600
Round 9
Train Loss: 1.365, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.500
Train Loss: 1.026, Train Accuracy: 0.600
Train Loss: 1.453, Train Accuracy: 0.600
Train Loss: 1.259, Train Accuracy: 0.625
Train Loss: 1.364, Train Accuracy: 0.800
Train Loss: 1.530, Train Accuracy: 0.500
Train Loss: 1.149, Train Accuracy: 0.400
Train Loss: 1.964, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 0.400
Round 10
Train Loss: 1.363, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.416, Train Accuracy: 0.600
Train Loss: 1.273, Train Accuracy: 0.625
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.478, Train Accuracy: 0.500
Train Loss: 1.211, Train Accuracy: 0.600
Train Loss: 1.968, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.500
Round 11
Train Loss: 1.367, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 1.428, Train Accuracy: 0.600
Train Loss: 1.250, Train Accuracy: 0.625
Train Loss: 1.371, Train Accuracy: 0.800
Train Loss: 1.575, Train Accuracy: 0.500
Train Loss: 1.172, Train Accuracy: 0.400
Train Loss: 1.964, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.700
Round 12
Train Loss: 1.502, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.023, Train Accuracy: 0.400
Train Loss: 1.435, Train Accuracy: 0.600
Train Loss: 1.283, Train Accuracy: 0.625
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.510, Train Accuracy: 1.000
Train Loss: 1.186, Train Accuracy: 0.400
Train Loss: 1.883, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.400
Round 13
Train Loss: 1.274, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.600
Train Loss: 1.014, Train Accuracy: 0.600
Train Loss: 1.406, Train Accuracy: 0.600
Train Loss: 1.285, Train Accuracy: 0.625
Train Loss: 1.383, Train Accuracy: 0.800
Train Loss: 1.542, Train Accuracy: 0.500
Train Loss: 1.140, Train Accuracy: 0.200
Train Loss: 1.944, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.600
Round 14
Train Loss: 1.395, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.479, Train Accuracy: 0.800
Train Loss: 1.273, Train Accuracy: 0.625
Train Loss: 1.368, Train Accuracy: 0.800
Train Loss: 1.577, Train Accuracy: 0.500
Train Loss: 1.206, Train Accuracy: 0.400
Train Loss: 1.894, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.400
Round 15
Train Loss: 1.546, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.700
Train Loss: 1.011, Train Accuracy: 0.600
Train Loss: 1.529, Train Accuracy: 0.600
Train Loss: 1.250, Train Accuracy: 0.625
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.535, Train Accuracy: 1.000
Train Loss: 1.227, Train Accuracy: 0.800
Train Loss: 1.853, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.400
Round 16
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.400
Train Loss: 1.440, Train Accuracy: 0.600
Train Loss: 1.214, Train Accuracy: 0.625
Train Loss: 1.281, Train Accuracy: 0.800
Train Loss: 1.592, Train Accuracy: 0.500
Train Loss: 1.204, Train Accuracy: 0.400
Train Loss: 1.980, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.400
Round 17
Train Loss: 1.403, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.400
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.454, Train Accuracy: 0.800
Train Loss: 1.257, Train Accuracy: 0.625
Train Loss: 1.372, Train Accuracy: 0.800
Train Loss: 1.508, Train Accuracy: 0.250
Train Loss: 1.164, Train Accuracy: 0.600
Train Loss: 1.939, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 0.500
Round 18
Train Loss: 1.256, Train Accuracy: 0.750
Train Loss: 1.040, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 1.450, Train Accuracy: 0.400
Train Loss: 1.263, Train Accuracy: 0.625
Train Loss: 1.387, Train Accuracy: 0.800
Train Loss: 1.538, Train Accuracy: 0.750
Train Loss: 1.216, Train Accuracy: 0.400
Train Loss: 2.091, Train Accuracy: 1.000
Train Loss: 1.164, Train Accuracy: 0.600
Round 19
Train Loss: 1.314, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.700
Train Loss: 1.004, Train Accuracy: 0.400
Train Loss: 1.470, Train Accuracy: 0.600
Train Loss: 1.252, Train Accuracy: 0.625
Train Loss: 1.419, Train Accuracy: 0.800
Train Loss: 1.520, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.800
Train Loss: 2.184, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.500
Round 20
Train Loss: 1.323, Train Accuracy: 0.750
Train Loss: 1.046, Train Accuracy: 0.600
Train Loss: 0.998, Train Accuracy: 0.600
Train Loss: 1.429, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.451, Train Accuracy: 0.800
Train Loss: 1.651, Train Accuracy: 0.500
Train Loss: 1.174, Train Accuracy: 0.200
Train Loss: 1.986, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.500
Round 21
Train Loss: 1.389, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.500
Train Loss: 1.013, Train Accuracy: 0.600
Train Loss: 1.480, Train Accuracy: 0.800
Train Loss: 1.218, Train Accuracy: 0.750
Train Loss: 1.441, Train Accuracy: 0.800
Train Loss: 1.579, Train Accuracy: 0.750
Train Loss: 1.227, Train Accuracy: 0.600
Train Loss: 2.163, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.600
Round 22
Train Loss: 1.289, Train Accuracy: 0.750
Train Loss: 1.040, Train Accuracy: 0.600
Train Loss: 0.994, Train Accuracy: 0.400
Train Loss: 1.360, Train Accuracy: 0.600
Train Loss: 1.251, Train Accuracy: 0.625
Train Loss: 1.412, Train Accuracy: 0.800
Train Loss: 1.614, Train Accuracy: 0.250
Train Loss: 1.122, Train Accuracy: 0.600
Train Loss: 1.944, Train Accuracy: 0.750
Train Loss: 1.084, Train Accuracy: 0.400
Round 23
Train Loss: 1.400, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.600
Train Loss: 0.986, Train Accuracy: 0.200
Train Loss: 1.507, Train Accuracy: 0.600
Train Loss: 1.207, Train Accuracy: 0.625
Train Loss: 1.385, Train Accuracy: 0.800
Train Loss: 1.641, Train Accuracy: 0.500
Train Loss: 1.218, Train Accuracy: 1.000
Train Loss: 2.115, Train Accuracy: 0.750
Train Loss: 1.090, Train Accuracy: 0.300
Round 24
Train Loss: 1.360, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.600
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 1.434, Train Accuracy: 0.600
Train Loss: 1.262, Train Accuracy: 0.625
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.578, Train Accuracy: 1.000
Train Loss: 1.113, Train Accuracy: 0.600
Train Loss: 2.112, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.400
Round 25
Train Loss: 1.288, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.500
Train Loss: 0.979, Train Accuracy: 0.400
Train Loss: 1.423, Train Accuracy: 0.800
Train Loss: 1.199, Train Accuracy: 0.625
Train Loss: 1.490, Train Accuracy: 0.800
Train Loss: 1.708, Train Accuracy: 0.500
Train Loss: 1.156, Train Accuracy: 0.600
Train Loss: 1.982, Train Accuracy: 0.750
Train Loss: 1.158, Train Accuracy: 0.500
Round 26
Train Loss: 1.440, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.500
Train Loss: 0.972, Train Accuracy: 0.400
Train Loss: 1.463, Train Accuracy: 0.800
Train Loss: 1.193, Train Accuracy: 0.625
Train Loss: 1.398, Train Accuracy: 0.800
Train Loss: 1.561, Train Accuracy: 0.250
Train Loss: 1.111, Train Accuracy: 0.400
Train Loss: 1.918, Train Accuracy: 0.750
Train Loss: 1.109, Train Accuracy: 0.500
Round 27
Train Loss: 1.233, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.600
Train Loss: 0.996, Train Accuracy: 0.400
Train Loss: 1.322, Train Accuracy: 0.600
Train Loss: 1.174, Train Accuracy: 0.750
Train Loss: 1.377, Train Accuracy: 0.800
Train Loss: 1.549, Train Accuracy: 1.000
Train Loss: 1.171, Train Accuracy: 0.600
Train Loss: 1.896, Train Accuracy: 0.750
Train Loss: 1.131, Train Accuracy: 0.500
Round 28
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 1.018, Train Accuracy: 0.600
Train Loss: 0.968, Train Accuracy: 0.400
Train Loss: 1.545, Train Accuracy: 0.800
Train Loss: 1.227, Train Accuracy: 0.750
Train Loss: 1.360, Train Accuracy: 0.800
Train Loss: 1.614, Train Accuracy: 0.500
Train Loss: 1.277, Train Accuracy: 0.600
Train Loss: 1.914, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.500
Round 29
Train Loss: 1.294, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 0.992, Train Accuracy: 0.400
Train Loss: 1.394, Train Accuracy: 0.800
Train Loss: 1.177, Train Accuracy: 0.750
Train Loss: 1.366, Train Accuracy: 0.800
Train Loss: 1.574, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.600
Train Loss: 2.190, Train Accuracy: 0.750
Train Loss: 1.240, Train Accuracy: 0.300
Round 30
Train Loss: 1.383, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.500
Train Loss: 0.958, Train Accuracy: 0.800
Train Loss: 1.395, Train Accuracy: 0.600
Train Loss: 1.154, Train Accuracy: 0.750
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.507, Train Accuracy: 0.500
Train Loss: 1.089, Train Accuracy: 0.400
Train Loss: 2.010, Train Accuracy: 0.750
Train Loss: 1.138, Train Accuracy: 0.500
Round 31
Train Loss: 1.235, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.500
Train Loss: 0.976, Train Accuracy: 0.600
Train Loss: 1.369, Train Accuracy: 0.800
Train Loss: 1.223, Train Accuracy: 0.625
Train Loss: 1.445, Train Accuracy: 0.800
Train Loss: 1.569, Train Accuracy: 0.250
Train Loss: 1.148, Train Accuracy: 0.600
Train Loss: 1.881, Train Accuracy: 0.750
Train Loss: 1.096, Train Accuracy: 0.400
Round 32
Train Loss: 1.344, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.700
Train Loss: 0.994, Train Accuracy: 0.600
Train Loss: 1.334, Train Accuracy: 0.600
Train Loss: 1.184, Train Accuracy: 0.750
Train Loss: 1.480, Train Accuracy: 0.800
Train Loss: 1.462, Train Accuracy: 0.750
Train Loss: 1.126, Train Accuracy: 0.600
Train Loss: 2.057, Train Accuracy: 0.750
Train Loss: 1.104, Train Accuracy: 0.600
Round 33
Train Loss: 1.256, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.700
Train Loss: 0.967, Train Accuracy: 0.600
Train Loss: 1.440, Train Accuracy: 0.800
Train Loss: 1.230, Train Accuracy: 0.625
Train Loss: 1.347, Train Accuracy: 0.800
Train Loss: 1.576, Train Accuracy: 0.500
Train Loss: 1.088, Train Accuracy: 0.400
Train Loss: 2.162, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.600
Round 34
Train Loss: 1.166, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.600
Train Loss: 0.948, Train Accuracy: 0.400
Train Loss: 1.388, Train Accuracy: 1.000
Train Loss: 1.175, Train Accuracy: 0.625
Train Loss: 1.342, Train Accuracy: 0.800
Train Loss: 1.618, Train Accuracy: 0.500
Train Loss: 1.071, Train Accuracy: 0.600
Train Loss: 2.188, Train Accuracy: 1.000
Train Loss: 1.053, Train Accuracy: 0.500
Round 35
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 0.934, Train Accuracy: 0.800
Train Loss: 1.429, Train Accuracy: 1.000
Train Loss: 1.275, Train Accuracy: 0.625
Train Loss: 1.339, Train Accuracy: 0.800
Train Loss: 1.739, Train Accuracy: 0.500
Train Loss: 1.132, Train Accuracy: 0.400
Train Loss: 2.238, Train Accuracy: 1.000
Train Loss: 1.309, Train Accuracy: 0.500
Round 36
Train Loss: 1.327, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.500
Train Loss: 0.935, Train Accuracy: 0.200
Train Loss: 1.349, Train Accuracy: 1.000
Train Loss: 1.133, Train Accuracy: 0.750
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.743, Train Accuracy: 0.500
Train Loss: 1.156, Train Accuracy: 0.600
Train Loss: 2.139, Train Accuracy: 0.750
Train Loss: 1.215, Train Accuracy: 0.800
Round 37
Train Loss: 1.226, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.800
Train Loss: 1.020, Train Accuracy: 0.600
Train Loss: 1.427, Train Accuracy: 0.800
Train Loss: 1.107, Train Accuracy: 0.875
Train Loss: 1.387, Train Accuracy: 0.800
Train Loss: 1.519, Train Accuracy: 0.750
Train Loss: 1.099, Train Accuracy: 0.600
Train Loss: 2.259, Train Accuracy: 1.000
Train Loss: 1.046, Train Accuracy: 0.600
Round 38
Train Loss: 1.422, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.500
Train Loss: 0.962, Train Accuracy: 0.600
Train Loss: 1.464, Train Accuracy: 0.800
Train Loss: 1.188, Train Accuracy: 0.750
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.601, Train Accuracy: 0.750
Train Loss: 1.118, Train Accuracy: 0.600
Train Loss: 1.926, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.800
Round 39
Train Loss: 1.226, Train Accuracy: 0.750
Train Loss: 0.972, Train Accuracy: 0.700
Train Loss: 0.942, Train Accuracy: 0.800
Train Loss: 1.373, Train Accuracy: 0.800
Train Loss: 1.194, Train Accuracy: 0.875
Train Loss: 1.373, Train Accuracy: 0.800
Train Loss: 1.741, Train Accuracy: 0.750
Train Loss: 1.234, Train Accuracy: 0.400
Train Loss: 2.121, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.700
Round 40
Train Loss: 1.319, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.500
Train Loss: 0.967, Train Accuracy: 0.600
Train Loss: 1.635, Train Accuracy: 0.800
Train Loss: 1.145, Train Accuracy: 0.750
Train Loss: 1.439, Train Accuracy: 0.800
Train Loss: 1.457, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.600
Train Loss: 1.936, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.600
Round 41
Train Loss: 1.413, Train Accuracy: 0.750
Train Loss: 0.984, Train Accuracy: 0.600
Train Loss: 0.940, Train Accuracy: 0.800
Train Loss: 1.438, Train Accuracy: 1.000
Train Loss: 1.363, Train Accuracy: 0.625
Train Loss: 1.362, Train Accuracy: 0.800
Train Loss: 1.453, Train Accuracy: 1.000
Train Loss: 1.037, Train Accuracy: 0.600
Train Loss: 2.057, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.700
Round 42
Train Loss: 1.287, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.700
Train Loss: 0.932, Train Accuracy: 0.600
Train Loss: 1.540, Train Accuracy: 0.800
Train Loss: 1.063, Train Accuracy: 0.875
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.534, Train Accuracy: 0.750
Train Loss: 1.094, Train Accuracy: 0.600
Train Loss: 2.312, Train Accuracy: 1.000
Train Loss: 1.059, Train Accuracy: 0.400
Round 43
Train Loss: 1.385, Train Accuracy: 0.750
Train Loss: 0.941, Train Accuracy: 0.700
Train Loss: 0.963, Train Accuracy: 0.800
Train Loss: 1.368, Train Accuracy: 0.600
Train Loss: 1.145, Train Accuracy: 0.750
Train Loss: 1.503, Train Accuracy: 0.800
Train Loss: 1.550, Train Accuracy: 0.500
Train Loss: 1.068, Train Accuracy: 0.600
Train Loss: 1.982, Train Accuracy: 0.750
Train Loss: 1.248, Train Accuracy: 0.900
Round 44
Train Loss: 1.377, Train Accuracy: 0.500
Train Loss: 0.987, Train Accuracy: 0.600
Train Loss: 0.984, Train Accuracy: 0.400
Train Loss: 1.524, Train Accuracy: 0.800
Train Loss: 1.133, Train Accuracy: 0.750
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.735, Train Accuracy: 0.750
Train Loss: 1.126, Train Accuracy: 0.800
Train Loss: 2.059, Train Accuracy: 1.000
Train Loss: 1.239, Train Accuracy: 0.500
Round 45
Train Loss: 1.151, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.400
Train Loss: 0.942, Train Accuracy: 0.600
Train Loss: 1.347, Train Accuracy: 0.800
Train Loss: 1.120, Train Accuracy: 0.750
Train Loss: 1.432, Train Accuracy: 1.000
Train Loss: 1.521, Train Accuracy: 1.000
Train Loss: 1.008, Train Accuracy: 0.400
Train Loss: 2.069, Train Accuracy: 0.750
Train Loss: 1.088, Train Accuracy: 0.700
Round 46
Train Loss: 1.347, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.600
Train Loss: 0.922, Train Accuracy: 0.600
Train Loss: 1.556, Train Accuracy: 0.800
Train Loss: 1.090, Train Accuracy: 0.625
Train Loss: 1.425, Train Accuracy: 0.800
Train Loss: 1.536, Train Accuracy: 1.000
Train Loss: 1.072, Train Accuracy: 0.800
Train Loss: 2.153, Train Accuracy: 1.000
Train Loss: 1.265, Train Accuracy: 0.500
Round 47
Train Loss: 1.116, Train Accuracy: 0.750
Train Loss: 0.987, Train Accuracy: 0.600
Train Loss: 0.892, Train Accuracy: 0.600
Train Loss: 1.210, Train Accuracy: 1.000
Train Loss: 1.083, Train Accuracy: 0.750
Train Loss: 1.464, Train Accuracy: 0.800
Train Loss: 1.603, Train Accuracy: 0.750
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.929, Train Accuracy: 0.750
Train Loss: 1.325, Train Accuracy: 0.700
Round 48
Train Loss: 1.212, Train Accuracy: 0.750
Train Loss: 0.998, Train Accuracy: 0.600
Train Loss: 0.959, Train Accuracy: 0.600
Train Loss: 1.274, Train Accuracy: 1.000
Train Loss: 1.138, Train Accuracy: 0.625
Train Loss: 1.296, Train Accuracy: 0.800
Train Loss: 1.749, Train Accuracy: 0.500

(FLClient pid=2880912) 2025-04-11 09:21:51,377 - INFO - Epoch   1| Train Loss: 0.875| Train Accuracy: 0.750 [repeated 359x across cluster]
(FLClient pid=2879967) 2025-04-11 09:21:24,321 - INFO - Epoch   2| Validation Loss: 1.126, Validation Accuracy: 0.438 [repeated 119x across cluster]
(FLClient pid=2881018) 2025-04-11 09:21:56,308 - INFO - Epoch   2| Train Loss: 0.788| Train Accuracy: 0.750 [repeated 376x across cluster]
(FLClient pid=2881018) 2025-04-11 09:21:56,315 - INFO - Epoch   2| Validation Loss: 1.437, Validation Accuracy: 0.333 [repeated 126x across cluster]
(FLClient pid=2880912) 2025-04-11 09:22:01,410 - INFO - Epoch   2| Train Loss: 0.847| Train Accuracy: 0.250 [repeated 435x across cluster]
(FLClient pid=2880912) 2025-04-11 09:22:01,418 - INFO - Epoch   2| Validation Loss: 1.399, Validation Accuracy: 0.295 [repeated 145x across cluster]
(FLClient pid=2880912) 2025-04-11 09:22:06,508 - INFO - Epoch   2| Train Loss: 0.582| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2881171) 2025-04-11 09:22:06,178 - INFO - Epoch   2| Validation Loss: 1.190, Validation Accuracy: 0.172 [repeated 149x across cluster]
(FLClient pid=2880912) 2025-04-11 09:22:11,611 - INFO - Epoch   2| Train Loss: 0.432| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2880912) 2025-04-11 09:22:11,619 - INFO - Epoch   2| Validation Loss: 1.217, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2880912) 2025-04-11 09:22:16,691 - INFO - Epoch   0| Train Loss: 0.842| Train Accuracy: 0.500 [repeated 448x across cluster]
(FLClient pid=2880916) 2025-04-11 09:22:16,378 - INFO - Epoch   2| Validation Loss: 1.158, Validation Accuracy: 0.350 [repeated 149x across cluster]
(FLClient pid=2880912) 2025-04-11 09:22:21,781 - INFO - Epoch   0| Train Loss: 0.815| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2881097) 2025-04-11 09:22:21,473 - INFO - Epoch   2| Validation Loss: 1.881, Validation Accuracy: 0.233 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.229, Train Accuracy: 0.750
Train Loss: 1.086, Train Accuracy: 0.500
Train Loss: 1.069, Train Accuracy: 0.400
Train Loss: 1.161, Train Accuracy: 0.600
Train Loss: 1.158, Train Accuracy: 0.625
Train Loss: 1.315, Train Accuracy: 0.800
Train Loss: 1.248, Train Accuracy: 0.500
Train Loss: 1.123, Train Accuracy: 0.400
Train Loss: 1.400, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.300
Round 2
Train Loss: 1.313, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.054, Train Accuracy: 0.400
Train Loss: 1.183, Train Accuracy: 0.600
Train Loss: 1.173, Train Accuracy: 0.625
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.278, Train Accuracy: 0.500
Train Loss: 1.122, Train Accuracy: 0.400
Train Loss: 1.390, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.500
Round 3
Train Loss: 1.335, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.052, Train Accuracy: 0.400
Train Loss: 1.213, Train Accuracy: 0.600
Train Loss: 1.192, Train Accuracy: 0.625
Train Loss: 1.314, Train Accuracy: 0.800
Train Loss: 1.266, Train Accuracy: 0.500
Train Loss: 1.131, Train Accuracy: 0.200
Train Loss: 1.432, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.300
Round 4
Train Loss: 1.373, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.500
Train Loss: 1.046, Train Accuracy: 0.400
Train Loss: 1.211, Train Accuracy: 0.600
Train Loss: 1.208, Train Accuracy: 0.625
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.322, Train Accuracy: 0.500
Train Loss: 1.154, Train Accuracy: 0.400
Train Loss: 1.484, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.300
Round 5
Train Loss: 1.314, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.042, Train Accuracy: 0.400
Train Loss: 1.204, Train Accuracy: 0.600
Train Loss: 1.216, Train Accuracy: 0.625
Train Loss: 1.271, Train Accuracy: 0.800
Train Loss: 1.318, Train Accuracy: 0.500
Train Loss: 1.157, Train Accuracy: 0.600
Train Loss: 1.493, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.600
Round 6
Train Loss: 1.218, Train Accuracy: 0.750
Train Loss: 1.088, Train Accuracy: 0.500
Train Loss: 1.043, Train Accuracy: 0.400
Train Loss: 1.206, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.273, Train Accuracy: 0.800
Train Loss: 1.317, Train Accuracy: 0.500
Train Loss: 1.157, Train Accuracy: 0.800
Train Loss: 1.507, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.400
Round 7
Train Loss: 1.332, Train Accuracy: 0.750
Train Loss: 1.091, Train Accuracy: 0.400
Train Loss: 1.033, Train Accuracy: 0.400
Train Loss: 1.239, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.281, Train Accuracy: 0.800
Train Loss: 1.366, Train Accuracy: 1.000
Train Loss: 1.160, Train Accuracy: 0.600
Train Loss: 1.533, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.400
Round 8
Train Loss: 1.326, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.600
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.223, Train Accuracy: 0.600
Train Loss: 1.261, Train Accuracy: 0.625
Train Loss: 1.301, Train Accuracy: 0.800
Train Loss: 1.383, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.400
Train Loss: 1.634, Train Accuracy: 0.750
Train Loss: 1.217, Train Accuracy: 0.500
Round 9
Train Loss: 1.447, Train Accuracy: 0.750
Train Loss: 1.095, Train Accuracy: 0.600
Train Loss: 1.036, Train Accuracy: 0.400
Train Loss: 1.257, Train Accuracy: 0.600
Train Loss: 1.257, Train Accuracy: 0.625
Train Loss: 1.281, Train Accuracy: 0.800
Train Loss: 1.404, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.600
Train Loss: 1.549, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.400
Round 10
Train Loss: 1.305, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.700
Train Loss: 1.054, Train Accuracy: 0.800
Train Loss: 1.291, Train Accuracy: 0.800
Train Loss: 1.249, Train Accuracy: 0.625
Train Loss: 1.305, Train Accuracy: 0.800
Train Loss: 1.454, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.600
Train Loss: 1.628, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.400
Round 11
Train Loss: 1.285, Train Accuracy: 0.750
Train Loss: 1.086, Train Accuracy: 0.500
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.250, Train Accuracy: 0.600
Train Loss: 1.274, Train Accuracy: 0.625
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.373, Train Accuracy: 0.500
Train Loss: 1.226, Train Accuracy: 0.400
Train Loss: 1.554, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.500
Round 12
Train Loss: 1.348, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.600
Train Loss: 1.038, Train Accuracy: 0.400
Train Loss: 1.238, Train Accuracy: 0.600
Train Loss: 1.281, Train Accuracy: 0.625
Train Loss: 1.402, Train Accuracy: 0.800
Train Loss: 1.391, Train Accuracy: 0.500
Train Loss: 1.196, Train Accuracy: 0.400
Train Loss: 1.743, Train Accuracy: 0.750
Train Loss: 1.225, Train Accuracy: 0.400
Round 13
Train Loss: 1.499, Train Accuracy: 0.750
Train Loss: 1.089, Train Accuracy: 0.600
Train Loss: 1.017, Train Accuracy: 0.600
Train Loss: 1.265, Train Accuracy: 0.600
Train Loss: 1.288, Train Accuracy: 0.625
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.437, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.600
Train Loss: 1.667, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.500
Round 14
Train Loss: 1.208, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.600
Train Loss: 1.018, Train Accuracy: 0.400
Train Loss: 1.234, Train Accuracy: 0.600
Train Loss: 1.290, Train Accuracy: 0.625
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.421, Train Accuracy: 0.500
Train Loss: 1.139, Train Accuracy: 0.600
Train Loss: 1.698, Train Accuracy: 0.750
Train Loss: 1.138, Train Accuracy: 0.400
Round 15
Train Loss: 1.198, Train Accuracy: 0.250
Train Loss: 1.053, Train Accuracy: 0.600
Train Loss: 1.010, Train Accuracy: 0.600
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.261, Train Accuracy: 0.625
Train Loss: 1.283, Train Accuracy: 0.800
Train Loss: 1.444, Train Accuracy: 0.500
Train Loss: 1.195, Train Accuracy: 0.600
Train Loss: 1.694, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.400
Round 16
Train Loss: 1.357, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.700
Train Loss: 1.007, Train Accuracy: 0.400
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.263, Train Accuracy: 0.625
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.439, Train Accuracy: 0.500
Train Loss: 1.147, Train Accuracy: 0.400
Train Loss: 1.666, Train Accuracy: 0.750
Train Loss: 1.290, Train Accuracy: 0.400
Round 17
Train Loss: 1.231, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.500
Train Loss: 1.017, Train Accuracy: 0.400
Train Loss: 1.271, Train Accuracy: 0.800
Train Loss: 1.265, Train Accuracy: 0.750
Train Loss: 1.391, Train Accuracy: 0.800
Train Loss: 1.456, Train Accuracy: 0.500
Train Loss: 1.131, Train Accuracy: 0.400
Train Loss: 1.714, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.300
Round 18
Train Loss: 1.504, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.600
Train Loss: 1.000, Train Accuracy: 0.400
Train Loss: 1.273, Train Accuracy: 1.000
Train Loss: 1.244, Train Accuracy: 0.625
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.445, Train Accuracy: 0.500
Train Loss: 1.126, Train Accuracy: 0.400
Train Loss: 1.714, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.300
Round 19
Train Loss: 1.441, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.700
Train Loss: 0.998, Train Accuracy: 0.600
Train Loss: 1.319, Train Accuracy: 0.600
Train Loss: 1.265, Train Accuracy: 0.750
Train Loss: 1.396, Train Accuracy: 0.800
Train Loss: 1.503, Train Accuracy: 1.000
Train Loss: 1.144, Train Accuracy: 0.400
Train Loss: 1.651, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.400
Round 20
Train Loss: 1.348, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.800
Train Loss: 0.992, Train Accuracy: 0.400
Train Loss: 1.261, Train Accuracy: 0.800
Train Loss: 1.269, Train Accuracy: 0.750
Train Loss: 1.313, Train Accuracy: 0.800
Train Loss: 1.406, Train Accuracy: 0.500
Train Loss: 1.192, Train Accuracy: 0.600
Train Loss: 1.767, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.500
Round 21
Train Loss: 1.292, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.700
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.282, Train Accuracy: 0.800
Train Loss: 1.239, Train Accuracy: 0.750
Train Loss: 1.380, Train Accuracy: 0.800
Train Loss: 1.397, Train Accuracy: 0.500
Train Loss: 1.181, Train Accuracy: 0.600
Train Loss: 1.932, Train Accuracy: 1.000
Train Loss: 1.071, Train Accuracy: 0.500
Round 22
Train Loss: 1.500, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.600
Train Loss: 0.990, Train Accuracy: 0.400
Train Loss: 1.274, Train Accuracy: 1.000
Train Loss: 1.279, Train Accuracy: 0.625
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.478, Train Accuracy: 0.500
Train Loss: 1.248, Train Accuracy: 0.600
Train Loss: 1.761, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.400
Round 23
Train Loss: 1.473, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.600
Train Loss: 0.990, Train Accuracy: 0.600
Train Loss: 1.258, Train Accuracy: 0.600
Train Loss: 1.255, Train Accuracy: 0.875
Train Loss: 1.417, Train Accuracy: 0.800
Train Loss: 1.558, Train Accuracy: 0.500
Train Loss: 1.192, Train Accuracy: 0.600
Train Loss: 1.727, Train Accuracy: 0.750
Train Loss: 1.103, Train Accuracy: 0.500
Round 24
Train Loss: 1.220, Train Accuracy: 0.750
Train Loss: 1.033, Train Accuracy: 0.600
Train Loss: 0.985, Train Accuracy: 0.400
Train Loss: 1.210, Train Accuracy: 0.800
Train Loss: 1.232, Train Accuracy: 0.625
Train Loss: 1.336, Train Accuracy: 0.800
Train Loss: 1.439, Train Accuracy: 0.500
Train Loss: 1.122, Train Accuracy: 0.600
Train Loss: 1.943, Train Accuracy: 1.000
Train Loss: 1.126, Train Accuracy: 0.400
Round 25
Train Loss: 1.483, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.500
Train Loss: 0.990, Train Accuracy: 0.600
Train Loss: 1.214, Train Accuracy: 0.800
Train Loss: 1.232, Train Accuracy: 0.625
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.447, Train Accuracy: 0.500
Train Loss: 1.124, Train Accuracy: 0.600
Train Loss: 1.828, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.800
Round 26
Train Loss: 1.318, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.500
Train Loss: 0.988, Train Accuracy: 0.600
Train Loss: 1.189, Train Accuracy: 0.600
Train Loss: 1.220, Train Accuracy: 0.750
Train Loss: 1.359, Train Accuracy: 0.800
Train Loss: 1.495, Train Accuracy: 0.750
Train Loss: 1.126, Train Accuracy: 0.200
Train Loss: 1.876, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.600
Round 27
Train Loss: 1.314, Train Accuracy: 0.750
Train Loss: 1.017, Train Accuracy: 0.500
Train Loss: 0.963, Train Accuracy: 0.600
Train Loss: 1.170, Train Accuracy: 0.800
Train Loss: 1.218, Train Accuracy: 0.750
Train Loss: 1.301, Train Accuracy: 0.800
Train Loss: 1.403, Train Accuracy: 1.000
Train Loss: 1.138, Train Accuracy: 0.800
Train Loss: 1.715, Train Accuracy: 0.750
Train Loss: 1.142, Train Accuracy: 0.800
Round 28
Train Loss: 1.399, Train Accuracy: 0.250
Train Loss: 1.016, Train Accuracy: 0.700
Train Loss: 0.980, Train Accuracy: 0.600
Train Loss: 1.240, Train Accuracy: 0.800
Train Loss: 1.249, Train Accuracy: 0.625
Train Loss: 1.248, Train Accuracy: 0.800
Train Loss: 1.500, Train Accuracy: 0.750
Train Loss: 1.222, Train Accuracy: 0.800
Train Loss: 1.976, Train Accuracy: 0.750
Train Loss: 1.099, Train Accuracy: 0.500
Round 29
Train Loss: 1.380, Train Accuracy: 0.500
Train Loss: 1.018, Train Accuracy: 0.700
Train Loss: 0.981, Train Accuracy: 0.600
Train Loss: 1.141, Train Accuracy: 0.600
Train Loss: 1.217, Train Accuracy: 0.625
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.387, Train Accuracy: 1.000
Train Loss: 1.105, Train Accuracy: 0.600
Train Loss: 1.856, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.400
Round 30
Train Loss: 1.345, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.700
Train Loss: 0.963, Train Accuracy: 0.600
Train Loss: 1.145, Train Accuracy: 0.800
Train Loss: 1.263, Train Accuracy: 0.875
Train Loss: 1.375, Train Accuracy: 0.800
Train Loss: 1.400, Train Accuracy: 0.500
Train Loss: 1.107, Train Accuracy: 0.400
Train Loss: 1.883, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.500
Round 31
Train Loss: 1.117, Train Accuracy: 0.750
Train Loss: 0.998, Train Accuracy: 0.600
Train Loss: 0.969, Train Accuracy: 0.600
Train Loss: 1.243, Train Accuracy: 1.000
Train Loss: 1.233, Train Accuracy: 0.750
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.461, Train Accuracy: 0.500
Train Loss: 1.116, Train Accuracy: 0.800
Train Loss: 2.190, Train Accuracy: 1.000
Train Loss: 1.293, Train Accuracy: 0.500
Round 32
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.600
Train Loss: 0.944, Train Accuracy: 0.600
Train Loss: 1.285, Train Accuracy: 0.800
Train Loss: 1.192, Train Accuracy: 0.625
Train Loss: 1.400, Train Accuracy: 1.000
Train Loss: 1.419, Train Accuracy: 0.500
Train Loss: 1.205, Train Accuracy: 1.000
Train Loss: 1.732, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.500
Round 33
Train Loss: 1.222, Train Accuracy: 0.750
Train Loss: 0.981, Train Accuracy: 0.600
Train Loss: 0.989, Train Accuracy: 0.600
Train Loss: 1.336, Train Accuracy: 1.000
Train Loss: 1.229, Train Accuracy: 0.750
Train Loss: 1.385, Train Accuracy: 0.800
Train Loss: 1.421, Train Accuracy: 0.750
Train Loss: 1.155, Train Accuracy: 0.600
Train Loss: 1.708, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.500
Round 34
Train Loss: 1.306, Train Accuracy: 0.500
Train Loss: 0.984, Train Accuracy: 0.600
Train Loss: 0.974, Train Accuracy: 0.600
Train Loss: 1.215, Train Accuracy: 0.800
Train Loss: 1.265, Train Accuracy: 0.750
Train Loss: 1.241, Train Accuracy: 0.800
Train Loss: 1.497, Train Accuracy: 0.500
Train Loss: 1.113, Train Accuracy: 0.600
Train Loss: 2.024, Train Accuracy: 1.000
Train Loss: 1.165, Train Accuracy: 0.500
Round 35
Train Loss: 1.278, Train Accuracy: 0.750
Train Loss: 0.989, Train Accuracy: 0.600
Train Loss: 0.947, Train Accuracy: 0.600
Train Loss: 1.376, Train Accuracy: 0.800
Train Loss: 1.238, Train Accuracy: 0.750
Train Loss: 1.218, Train Accuracy: 0.800
Train Loss: 1.426, Train Accuracy: 0.750
Train Loss: 1.095, Train Accuracy: 0.800
Train Loss: 1.802, Train Accuracy: 0.750
Train Loss: 1.214, Train Accuracy: 0.500
Round 36
Train Loss: 1.350, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.600
Train Loss: 0.930, Train Accuracy: 0.400
Train Loss: 1.166, Train Accuracy: 1.000
Train Loss: 1.199, Train Accuracy: 0.875
Train Loss: 1.440, Train Accuracy: 0.800
Train Loss: 1.490, Train Accuracy: 1.000
Train Loss: 1.047, Train Accuracy: 0.800
Train Loss: 1.953, Train Accuracy: 0.750
Train Loss: 1.092, Train Accuracy: 0.600
Round 37
Train Loss: 1.253, Train Accuracy: 0.500
Train Loss: 0.964, Train Accuracy: 0.400
Train Loss: 0.936, Train Accuracy: 0.600
Train Loss: 1.240, Train Accuracy: 1.000
Train Loss: 1.191, Train Accuracy: 0.625
Train Loss: 1.371, Train Accuracy: 0.800
Train Loss: 1.621, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.600
Train Loss: 2.001, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.500
Round 38
Train Loss: 1.081, Train Accuracy: 0.750
Train Loss: 0.967, Train Accuracy: 0.500
Train Loss: 0.921, Train Accuracy: 0.400
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.203, Train Accuracy: 0.750
Train Loss: 1.232, Train Accuracy: 0.800
Train Loss: 1.370, Train Accuracy: 1.000
Train Loss: 1.056, Train Accuracy: 0.600
Train Loss: 1.817, Train Accuracy: 0.750
Train Loss: 1.232, Train Accuracy: 0.400
Round 39
Train Loss: 1.270, Train Accuracy: 0.500
Train Loss: 0.980, Train Accuracy: 0.600
Train Loss: 0.931, Train Accuracy: 0.600
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.206, Train Accuracy: 0.625
Train Loss: 1.246, Train Accuracy: 0.800
Train Loss: 1.436, Train Accuracy: 0.750
Train Loss: 1.007, Train Accuracy: 0.800
Train Loss: 1.919, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.700
Round 40
Train Loss: 1.258, Train Accuracy: 0.750
Train Loss: 0.958, Train Accuracy: 0.500
Train Loss: 0.906, Train Accuracy: 0.400
Train Loss: 1.342, Train Accuracy: 1.000
Train Loss: 1.343, Train Accuracy: 0.625
Train Loss: 1.384, Train Accuracy: 0.800
Train Loss: 1.486, Train Accuracy: 0.500
Train Loss: 1.066, Train Accuracy: 0.600
Train Loss: 1.952, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.500
Round 41
Train Loss: 1.362, Train Accuracy: 0.750
Train Loss: 0.974, Train Accuracy: 0.700
Train Loss: 0.929, Train Accuracy: 0.600
Train Loss: 1.300, Train Accuracy: 1.000
Train Loss: 1.206, Train Accuracy: 0.750
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.433, Train Accuracy: 1.000
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 2.091, Train Accuracy: 0.750
Train Loss: 1.274, Train Accuracy: 0.500
Round 42
Train Loss: 1.306, Train Accuracy: 0.500
Train Loss: 0.971, Train Accuracy: 0.700
Train Loss: 0.928, Train Accuracy: 0.400
Train Loss: 1.488, Train Accuracy: 0.600
Train Loss: 1.217, Train Accuracy: 0.500
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.401, Train Accuracy: 0.500
Train Loss: 1.182, Train Accuracy: 0.600
Train Loss: 2.057, Train Accuracy: 1.000
Train Loss: 1.190, Train Accuracy: 0.700
Round 43
Train Loss: 1.232, Train Accuracy: 0.750
Train Loss: 0.961, Train Accuracy: 0.500
Train Loss: 0.909, Train Accuracy: 0.600
Train Loss: 1.202, Train Accuracy: 1.000
Train Loss: 1.100, Train Accuracy: 0.625
Train Loss: 1.373, Train Accuracy: 1.000
Train Loss: 1.397, Train Accuracy: 0.500
Train Loss: 1.223, Train Accuracy: 0.600
Train Loss: 2.100, Train Accuracy: 1.000
Train Loss: 1.040, Train Accuracy: 0.800
Round 44
Train Loss: 1.157, Train Accuracy: 0.750
Train Loss: 0.974, Train Accuracy: 0.600
Train Loss: 0.928, Train Accuracy: 0.800
Train Loss: 1.394, Train Accuracy: 1.000
Train Loss: 1.144, Train Accuracy: 0.750
Train Loss: 1.250, Train Accuracy: 0.800
Train Loss: 1.340, Train Accuracy: 1.000
Train Loss: 0.967, Train Accuracy: 0.600
Train Loss: 1.561, Train Accuracy: 0.750
Train Loss: 1.394, Train Accuracy: 0.600
Round 45
Train Loss: 1.228, Train Accuracy: 0.750
Train Loss: 0.956, Train Accuracy: 0.500
Train Loss: 0.936, Train Accuracy: 0.600
Train Loss: 1.432, Train Accuracy: 1.000
Train Loss: 1.240, Train Accuracy: 0.375
Train Loss: 1.185, Train Accuracy: 0.800
Train Loss: 1.447, Train Accuracy: 1.000
Train Loss: 1.338, Train Accuracy: 1.000
Train Loss: 1.852, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.400
Round 46
Train Loss: 1.435, Train Accuracy: 0.750
Train Loss: 0.933, Train Accuracy: 0.500
Train Loss: 0.888, Train Accuracy: 0.600
Train Loss: 1.160, Train Accuracy: 1.000
Train Loss: 1.139, Train Accuracy: 0.750
Train Loss: 1.264, Train Accuracy: 0.800
Train Loss: 1.497, Train Accuracy: 0.500
Train Loss: 1.222, Train Accuracy: 0.600
Train Loss: 1.804, Train Accuracy: 0.750
Train Loss: 1.335, Train Accuracy: 0.900
Round 47
Train Loss: 1.414, Train Accuracy: 1.000
Train Loss: 0.940, Train Accuracy: 0.700
Train Loss: 0.859, Train Accuracy: 0.200
Train Loss: 1.190, Train Accuracy: 0.800
Train Loss: 1.173, Train Accuracy: 0.625
Train Loss: 1.440, Train Accuracy: 0.800
Train Loss: 1.775, Train Accuracy: 1.000
Train Loss: 1.208, Train Accuracy: 0.600
Train Loss: 1.996, Train Accuracy: 0.750
Train Loss: 1.375, Train Accuracy: 0.800
Round 48
Train Loss: 1.245, Train Accuracy: 0.500
Train Loss: 0.936, Train Accuracy: 0.800
Train Loss: 0.893, Train Accuracy: 0.600
Train Loss: 1.496, Train Accuracy: 0.800
Train Loss: 1.206, Train Accuracy: 0.625
Train Loss: 1.312, Train Accuracy: 0.800
Train Loss: 1.918, Train Accuracy: 0.750

(FLClient pid=2882058) 2025-04-11 09:22:53,009 - INFO - Epoch   2| Train Loss: 0.689| Train Accuracy: 0.750 [repeated 392x across cluster]
(FLClient pid=2882058) 2025-04-11 09:22:53,020 - INFO - Epoch   2| Validation Loss: 1.415, Validation Accuracy: 0.295 [repeated 131x across cluster]
(FLClient pid=2882058) 2025-04-11 09:22:58,147 - INFO - Epoch   2| Train Loss: 0.652| Train Accuracy: 0.750 [repeated 390x across cluster]
(FLClient pid=2882058) 2025-04-11 09:22:58,154 - INFO - Epoch   2| Validation Loss: 1.376, Validation Accuracy: 0.295 [repeated 130x across cluster]
(FLClient pid=2882058) 2025-04-11 09:23:03,260 - INFO - Epoch   2| Train Loss: 0.415| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2882058) 2025-04-11 09:23:03,268 - INFO - Epoch   2| Validation Loss: 1.385, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2882058) 2025-04-11 09:23:08,378 - INFO - Epoch   2| Train Loss: 0.455| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2882058) 2025-04-11 09:23:08,385 - INFO - Epoch   2| Validation Loss: 1.225, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2882058) 2025-04-11 09:23:13,473 - INFO - Epoch   2| Train Loss: 0.568| Train Accuracy: 0.500 [repeated 450x across cluster]
(FLClient pid=2882058) 2025-04-11 09:23:13,481 - INFO - Epoch   2| Validation Loss: 1.357, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2882059) 2025-04-11 09:23:18,576 - INFO - Epoch   0| Train Loss: 0.777| Train Accuracy: 0.500 [repeated 448x across cluster]
(FLClient pid=2882292) 2025-04-11 09:23:18,261 - INFO - Epoch   2| Validation Loss: 1.438, Validation Accuracy: 0.156 [repeated 149x across cluster]
(FLClient pid=2882058) 2025-04-11 09:23:23,716 - INFO - Epoch   1| Train Loss: 0.358| Train Accuracy: 0.750 [repeated 451x across cluster]
(FLClient pid=2882292) 2025-04-11 09:23:23,399 - INFO - Epoch   2| Validation Loss: 1.191, Validation Accuracy: 0.281 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.415, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.074, Train Accuracy: 0.400
Train Loss: 1.209, Train Accuracy: 0.600
Train Loss: 1.170, Train Accuracy: 0.625
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.302, Train Accuracy: 0.750
Train Loss: 1.138, Train Accuracy: 0.400
Train Loss: 1.389, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.300
Round 2
Train Loss: 1.379, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.058, Train Accuracy: 0.400
Train Loss: 1.248, Train Accuracy: 0.600
Train Loss: 1.202, Train Accuracy: 0.625
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.326, Train Accuracy: 0.500
Train Loss: 1.156, Train Accuracy: 0.200
Train Loss: 1.436, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.300
Round 3
Train Loss: 1.368, Train Accuracy: 0.750
Train Loss: 1.084, Train Accuracy: 0.500
Train Loss: 1.056, Train Accuracy: 0.400
Train Loss: 1.235, Train Accuracy: 0.600
Train Loss: 1.214, Train Accuracy: 0.625
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.363, Train Accuracy: 0.500
Train Loss: 1.148, Train Accuracy: 0.400
Train Loss: 1.496, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.500
Round 4
Train Loss: 1.324, Train Accuracy: 0.750
Train Loss: 1.083, Train Accuracy: 0.500
Train Loss: 1.047, Train Accuracy: 0.400
Train Loss: 1.255, Train Accuracy: 0.600
Train Loss: 1.233, Train Accuracy: 0.625
Train Loss: 1.252, Train Accuracy: 0.800
Train Loss: 1.386, Train Accuracy: 0.000
Train Loss: 1.159, Train Accuracy: 0.400
Train Loss: 1.529, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.400
Round 5
Train Loss: 1.340, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.042, Train Accuracy: 0.400
Train Loss: 1.306, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.401, Train Accuracy: 0.500
Train Loss: 1.193, Train Accuracy: 0.400
Train Loss: 1.537, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.500
Round 6
Train Loss: 1.325, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.500
Train Loss: 1.049, Train Accuracy: 0.400
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.248, Train Accuracy: 0.625
Train Loss: 1.383, Train Accuracy: 0.800
Train Loss: 1.430, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.400
Train Loss: 1.599, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.400
Round 7
Train Loss: 1.419, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.500
Train Loss: 1.034, Train Accuracy: 0.400
Train Loss: 1.316, Train Accuracy: 0.600
Train Loss: 1.253, Train Accuracy: 0.625
Train Loss: 1.397, Train Accuracy: 0.800
Train Loss: 1.424, Train Accuracy: 0.250
Train Loss: 1.201, Train Accuracy: 0.600
Train Loss: 1.647, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.600
Round 8
Train Loss: 1.340, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.500
Train Loss: 1.038, Train Accuracy: 0.400
Train Loss: 1.358, Train Accuracy: 0.600
Train Loss: 1.270, Train Accuracy: 0.625
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.427, Train Accuracy: 0.750
Train Loss: 1.242, Train Accuracy: 0.600
Train Loss: 1.666, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.200
Round 9
Train Loss: 1.329, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.034, Train Accuracy: 0.600
Train Loss: 1.367, Train Accuracy: 0.600
Train Loss: 1.266, Train Accuracy: 0.625
Train Loss: 1.368, Train Accuracy: 0.800
Train Loss: 1.473, Train Accuracy: 0.250
Train Loss: 1.194, Train Accuracy: 0.600
Train Loss: 1.731, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.500
Round 10
Train Loss: 1.509, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.500
Train Loss: 1.032, Train Accuracy: 0.400
Train Loss: 1.374, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.750
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.491, Train Accuracy: 0.500
Train Loss: 1.189, Train Accuracy: 0.800
Train Loss: 1.750, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.600
Round 11
Train Loss: 1.487, Train Accuracy: 0.500
Train Loss: 1.061, Train Accuracy: 0.400
Train Loss: 1.036, Train Accuracy: 0.400
Train Loss: 1.411, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.625
Train Loss: 1.324, Train Accuracy: 0.800
Train Loss: 1.487, Train Accuracy: 0.500
Train Loss: 1.195, Train Accuracy: 0.800
Train Loss: 1.714, Train Accuracy: 0.750
Train Loss: 1.132, Train Accuracy: 0.300
Round 12
Train Loss: 1.305, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.500
Train Loss: 1.018, Train Accuracy: 0.400
Train Loss: 1.364, Train Accuracy: 0.800
Train Loss: 1.267, Train Accuracy: 0.625
Train Loss: 1.264, Train Accuracy: 0.800
Train Loss: 1.505, Train Accuracy: 0.250
Train Loss: 1.189, Train Accuracy: 0.400
Train Loss: 1.758, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 0.400
Round 13
Train Loss: 1.428, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.300
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.396, Train Accuracy: 0.800
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.286, Train Accuracy: 0.800
Train Loss: 1.521, Train Accuracy: 0.500
Train Loss: 1.195, Train Accuracy: 0.400
Train Loss: 1.799, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.500
Round 14
Train Loss: 1.376, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.500
Train Loss: 1.020, Train Accuracy: 0.400
Train Loss: 1.356, Train Accuracy: 0.600
Train Loss: 1.175, Train Accuracy: 0.625
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.510, Train Accuracy: 0.750
Train Loss: 1.220, Train Accuracy: 0.600
Train Loss: 1.709, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.600
Round 15
Train Loss: 1.487, Train Accuracy: 0.500
Train Loss: 1.057, Train Accuracy: 0.500
Train Loss: 1.013, Train Accuracy: 0.400
Train Loss: 1.349, Train Accuracy: 0.400
Train Loss: 1.244, Train Accuracy: 0.625
Train Loss: 1.433, Train Accuracy: 0.800
Train Loss: 1.566, Train Accuracy: 1.000
Train Loss: 1.226, Train Accuracy: 0.400
Train Loss: 1.869, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.500
Round 16
Train Loss: 1.366, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.458, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.750
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.585, Train Accuracy: 0.500
Train Loss: 1.148, Train Accuracy: 0.200
Train Loss: 1.818, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.200
Round 17
Train Loss: 1.326, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.000
Train Loss: 1.381, Train Accuracy: 0.800
Train Loss: 1.281, Train Accuracy: 0.625
Train Loss: 1.463, Train Accuracy: 0.800
Train Loss: 1.519, Train Accuracy: 0.250
Train Loss: 1.157, Train Accuracy: 0.800
Train Loss: 1.812, Train Accuracy: 0.750
Train Loss: 1.148, Train Accuracy: 0.500
Round 18
Train Loss: 1.288, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.600
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 1.433, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.356, Train Accuracy: 0.800
Train Loss: 1.571, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.600
Train Loss: 1.874, Train Accuracy: 0.750
Train Loss: 1.127, Train Accuracy: 0.400
Round 19
Train Loss: 1.139, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.500
Train Loss: 1.002, Train Accuracy: 0.400
Train Loss: 1.340, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.319, Train Accuracy: 0.800
Train Loss: 1.544, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.600
Train Loss: 1.793, Train Accuracy: 0.750
Train Loss: 1.132, Train Accuracy: 0.500
Round 20
Train Loss: 1.422, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.800
Train Loss: 0.995, Train Accuracy: 0.200
Train Loss: 1.458, Train Accuracy: 0.600
Train Loss: 1.239, Train Accuracy: 0.750
Train Loss: 1.412, Train Accuracy: 0.800
Train Loss: 1.475, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.600
Train Loss: 1.872, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.400
Round 21
Train Loss: 1.407, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.500
Train Loss: 1.002, Train Accuracy: 0.400
Train Loss: 1.432, Train Accuracy: 0.800
Train Loss: 1.275, Train Accuracy: 0.625
Train Loss: 1.447, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 0.500
Train Loss: 1.285, Train Accuracy: 0.200
Train Loss: 1.999, Train Accuracy: 1.000
Train Loss: 1.150, Train Accuracy: 0.400
Round 22
Train Loss: 1.301, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.500
Train Loss: 0.990, Train Accuracy: 0.400
Train Loss: 1.418, Train Accuracy: 0.600
Train Loss: 1.251, Train Accuracy: 0.625
Train Loss: 1.368, Train Accuracy: 0.800
Train Loss: 1.549, Train Accuracy: 0.500
Train Loss: 1.135, Train Accuracy: 0.800
Train Loss: 1.782, Train Accuracy: 0.750
Train Loss: 1.130, Train Accuracy: 0.400
Round 23
Train Loss: 1.378, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.500
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 1.450, Train Accuracy: 0.800
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 1.401, Train Accuracy: 0.800
Train Loss: 1.530, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.400
Train Loss: 1.896, Train Accuracy: 0.750
Train Loss: 1.146, Train Accuracy: 0.700
Round 24
Train Loss: 1.437, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.700
Train Loss: 0.989, Train Accuracy: 0.400
Train Loss: 1.431, Train Accuracy: 0.600
Train Loss: 1.239, Train Accuracy: 0.625
Train Loss: 1.387, Train Accuracy: 0.800
Train Loss: 1.562, Train Accuracy: 0.500
Train Loss: 1.177, Train Accuracy: 0.800
Train Loss: 1.858, Train Accuracy: 0.750
Train Loss: 1.138, Train Accuracy: 0.300
Round 25
Train Loss: 1.345, Train Accuracy: 0.750
Train Loss: 1.050, Train Accuracy: 0.700
Train Loss: 0.991, Train Accuracy: 0.600
Train Loss: 1.467, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.750
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.546, Train Accuracy: 0.750
Train Loss: 1.229, Train Accuracy: 0.600
Train Loss: 1.875, Train Accuracy: 0.750
Train Loss: 1.138, Train Accuracy: 0.400
Round 26
Train Loss: 1.138, Train Accuracy: 0.750
Train Loss: 1.020, Train Accuracy: 0.800
Train Loss: 0.979, Train Accuracy: 0.400
Train Loss: 1.422, Train Accuracy: 0.800
Train Loss: 1.212, Train Accuracy: 0.625
Train Loss: 1.424, Train Accuracy: 0.800
Train Loss: 1.553, Train Accuracy: 0.500
Train Loss: 1.125, Train Accuracy: 0.400
Train Loss: 1.796, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.600
Round 27
Train Loss: 1.295, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.600
Train Loss: 0.981, Train Accuracy: 0.400
Train Loss: 1.389, Train Accuracy: 0.600
Train Loss: 1.215, Train Accuracy: 0.875
Train Loss: 1.383, Train Accuracy: 0.800
Train Loss: 1.510, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.600
Train Loss: 1.974, Train Accuracy: 0.750
Train Loss: 1.089, Train Accuracy: 0.500
Round 28
Train Loss: 1.406, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.700
Train Loss: 0.983, Train Accuracy: 0.400
Train Loss: 1.422, Train Accuracy: 1.000
Train Loss: 1.192, Train Accuracy: 0.625
Train Loss: 1.417, Train Accuracy: 0.800
Train Loss: 1.565, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.800
Train Loss: 1.939, Train Accuracy: 0.750
Train Loss: 1.175, Train Accuracy: 0.500
Round 29
Train Loss: 1.385, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.700
Train Loss: 0.978, Train Accuracy: 0.800
Train Loss: 1.339, Train Accuracy: 0.600
Train Loss: 1.282, Train Accuracy: 0.625
Train Loss: 1.291, Train Accuracy: 0.800
Train Loss: 1.520, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.600
Train Loss: 1.811, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.400
Round 30
Train Loss: 1.520, Train Accuracy: 0.750
Train Loss: 1.013, Train Accuracy: 0.600
Train Loss: 0.971, Train Accuracy: 0.600
Train Loss: 1.517, Train Accuracy: 1.000
Train Loss: 1.248, Train Accuracy: 0.625
Train Loss: 1.400, Train Accuracy: 0.800
Train Loss: 1.552, Train Accuracy: 0.500
Train Loss: 1.241, Train Accuracy: 0.800
Train Loss: 1.797, Train Accuracy: 0.500
Train Loss: 1.132, Train Accuracy: 0.400
Round 31
Train Loss: 1.357, Train Accuracy: 0.750
Train Loss: 1.011, Train Accuracy: 0.500
Train Loss: 0.995, Train Accuracy: 0.600
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.192, Train Accuracy: 0.750
Train Loss: 1.434, Train Accuracy: 0.800
Train Loss: 1.590, Train Accuracy: 0.500
Train Loss: 1.083, Train Accuracy: 0.600
Train Loss: 2.001, Train Accuracy: 0.750
Train Loss: 1.096, Train Accuracy: 0.600
Round 32
Train Loss: 1.334, Train Accuracy: 0.750
Train Loss: 1.014, Train Accuracy: 0.600
Train Loss: 0.964, Train Accuracy: 0.600
Train Loss: 1.374, Train Accuracy: 0.800
Train Loss: 1.187, Train Accuracy: 0.750
Train Loss: 1.347, Train Accuracy: 0.800
Train Loss: 1.536, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.400
Train Loss: 1.865, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.600
Round 33
Train Loss: 1.462, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.700
Train Loss: 0.969, Train Accuracy: 0.800
Train Loss: 1.322, Train Accuracy: 0.600
Train Loss: 1.135, Train Accuracy: 0.625
Train Loss: 1.381, Train Accuracy: 0.800
Train Loss: 1.445, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 1.000
Train Loss: 1.819, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.700
Round 34
Train Loss: 1.277, Train Accuracy: 0.750
Train Loss: 1.030, Train Accuracy: 0.700
Train Loss: 0.960, Train Accuracy: 0.600
Train Loss: 1.330, Train Accuracy: 0.600
Train Loss: 1.175, Train Accuracy: 0.625
Train Loss: 1.372, Train Accuracy: 0.800
Train Loss: 1.392, Train Accuracy: 0.750
Train Loss: 1.209, Train Accuracy: 0.800
Train Loss: 1.992, Train Accuracy: 0.750
Train Loss: 1.234, Train Accuracy: 0.700
Round 35
Train Loss: 1.431, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.600
Train Loss: 0.945, Train Accuracy: 0.600
Train Loss: 1.333, Train Accuracy: 0.800
Train Loss: 1.239, Train Accuracy: 0.750
Train Loss: 1.443, Train Accuracy: 1.000
Train Loss: 1.623, Train Accuracy: 0.500
Train Loss: 1.244, Train Accuracy: 0.800
Train Loss: 1.786, Train Accuracy: 0.750
Train Loss: 1.104, Train Accuracy: 0.500
Round 36
Train Loss: 1.242, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.400
Train Loss: 0.986, Train Accuracy: 0.200
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.183, Train Accuracy: 0.375
Train Loss: 1.397, Train Accuracy: 0.800
Train Loss: 1.453, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 1.000
Train Loss: 1.802, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.500
Round 37
Train Loss: 1.227, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.700
Train Loss: 0.979, Train Accuracy: 0.600
Train Loss: 1.495, Train Accuracy: 0.600
Train Loss: 1.177, Train Accuracy: 0.750
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.658, Train Accuracy: 1.000
Train Loss: 1.163, Train Accuracy: 0.600
Train Loss: 1.804, Train Accuracy: 0.750
Train Loss: 1.220, Train Accuracy: 0.600
Round 38
Train Loss: 1.374, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.700
Train Loss: 0.924, Train Accuracy: 0.400
Train Loss: 1.263, Train Accuracy: 0.600
Train Loss: 1.210, Train Accuracy: 0.750
Train Loss: 1.422, Train Accuracy: 0.800
Train Loss: 1.538, Train Accuracy: 1.000
Train Loss: 1.073, Train Accuracy: 0.600
Train Loss: 2.043, Train Accuracy: 0.750
Train Loss: 1.104, Train Accuracy: 0.600
Round 39
Train Loss: 1.296, Train Accuracy: 0.500
Train Loss: 0.985, Train Accuracy: 0.900
Train Loss: 0.945, Train Accuracy: 0.400
Train Loss: 1.407, Train Accuracy: 1.000
Train Loss: 1.177, Train Accuracy: 0.750
Train Loss: 1.364, Train Accuracy: 0.800
Train Loss: 1.520, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 1.000
Train Loss: 1.710, Train Accuracy: 0.750
Train Loss: 1.124, Train Accuracy: 0.700
Round 40
Train Loss: 1.290, Train Accuracy: 0.750
Train Loss: 0.987, Train Accuracy: 0.800
Train Loss: 0.919, Train Accuracy: 0.400
Train Loss: 1.424, Train Accuracy: 0.800
Train Loss: 1.164, Train Accuracy: 0.250
Train Loss: 1.369, Train Accuracy: 0.800
Train Loss: 1.651, Train Accuracy: 0.500
Train Loss: 1.093, Train Accuracy: 0.600
Train Loss: 1.831, Train Accuracy: 0.750
Train Loss: 1.319, Train Accuracy: 0.700
Round 41
Train Loss: 1.125, Train Accuracy: 0.750
Train Loss: 0.989, Train Accuracy: 0.500
Train Loss: 0.969, Train Accuracy: 0.600
Train Loss: 1.481, Train Accuracy: 0.800
Train Loss: 1.200, Train Accuracy: 0.875
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.528, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.800
Train Loss: 2.015, Train Accuracy: 0.750
Train Loss: 1.100, Train Accuracy: 0.700
Round 42
Train Loss: 1.346, Train Accuracy: 0.750
Train Loss: 0.969, Train Accuracy: 0.600
Train Loss: 0.926, Train Accuracy: 0.400
Train Loss: 1.208, Train Accuracy: 0.800
Train Loss: 1.124, Train Accuracy: 0.750
Train Loss: 1.272, Train Accuracy: 0.800
Train Loss: 1.540, Train Accuracy: 0.750
Train Loss: 1.033, Train Accuracy: 0.400
Train Loss: 2.122, Train Accuracy: 0.750
Train Loss: 1.094, Train Accuracy: 0.700
Round 43
Train Loss: 1.236, Train Accuracy: 0.750
Train Loss: 0.978, Train Accuracy: 0.500
Train Loss: 0.946, Train Accuracy: 0.600
Train Loss: 1.230, Train Accuracy: 0.600
Train Loss: 1.099, Train Accuracy: 0.750
Train Loss: 1.475, Train Accuracy: 0.800
Train Loss: 1.738, Train Accuracy: 0.750
Train Loss: 1.105, Train Accuracy: 1.000
Train Loss: 1.870, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.600
Round 44
Train Loss: 1.225, Train Accuracy: 0.750
Train Loss: 0.969, Train Accuracy: 0.800
Train Loss: 0.946, Train Accuracy: 0.400
Train Loss: 1.166, Train Accuracy: 0.600
Train Loss: 1.157, Train Accuracy: 0.625
Train Loss: 1.371, Train Accuracy: 0.800
Train Loss: 1.615, Train Accuracy: 0.500
Train Loss: 1.017, Train Accuracy: 0.200
Train Loss: 1.902, Train Accuracy: 0.750
Train Loss: 1.146, Train Accuracy: 0.600
Round 45
Train Loss: 1.318, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.700
Train Loss: 0.974, Train Accuracy: 0.400
Train Loss: 1.446, Train Accuracy: 0.600
Train Loss: 1.143, Train Accuracy: 0.750
Train Loss: 1.409, Train Accuracy: 0.800
Train Loss: 1.421, Train Accuracy: 0.750
Train Loss: 1.096, Train Accuracy: 0.600
Train Loss: 1.822, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.700
Round 46
Train Loss: 1.352, Train Accuracy: 0.750
Train Loss: 0.940, Train Accuracy: 0.500
Train Loss: 0.890, Train Accuracy: 0.600
Train Loss: 1.282, Train Accuracy: 0.800
Train Loss: 1.069, Train Accuracy: 0.875
Train Loss: 1.190, Train Accuracy: 0.800
Train Loss: 1.576, Train Accuracy: 1.000
Train Loss: 1.035, Train Accuracy: 0.600
Train Loss: 1.704, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.800
Round 47
Train Loss: 1.276, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.600
Train Loss: 0.898, Train Accuracy: 0.800
Train Loss: 1.430, Train Accuracy: 1.000
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 1.442, Train Accuracy: 0.800
Train Loss: 1.485, Train Accuracy: 0.500
Train Loss: 1.041, Train Accuracy: 0.800
Train Loss: 2.210, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.700
Round 48
Train Loss: 1.687, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.500
Train Loss: 0.915, Train Accuracy: 0.400
Train Loss: 1.358, Train Accuracy: 1.000
Train Loss: 1.122, Train Accuracy: 0.625
Train Loss: 1.264, Train Accuracy: 0.800
Train Loss: 1.580, Train Accuracy: 0.750

(FLClient pid=2883220) 2025-04-11 09:23:54,445 - INFO - Epoch   2| Train Loss: 0.766| Train Accuracy: 0.750 [repeated 361x across cluster]
(FLClient pid=2883220) 2025-04-11 09:23:54,454 - INFO - Epoch   2| Validation Loss: 1.256, Validation Accuracy: 0.295 [repeated 121x across cluster]
(FLClient pid=2883220) 2025-04-11 09:23:59,435 - INFO - Epoch   2| Train Loss: 0.574| Train Accuracy: 0.750 [repeated 377x across cluster]
(FLClient pid=2883220) 2025-04-11 09:23:59,443 - INFO - Epoch   2| Validation Loss: 1.356, Validation Accuracy: 0.295 [repeated 120x across cluster]
(FLClient pid=2883220) 2025-04-11 09:24:04,608 - INFO - Epoch   2| Train Loss: 0.659| Train Accuracy: 0.750 [repeated 433x across cluster]
(FLClient pid=2883220) 2025-04-11 09:24:04,617 - INFO - Epoch   2| Validation Loss: 1.312, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2883220) 2025-04-11 09:24:09,834 - INFO - Epoch   1| Train Loss: 0.563| Train Accuracy: 0.750 [repeated 449x across cluster]
(FLClient pid=2883483) 2025-04-11 09:24:09,509 - INFO - Epoch   2| Validation Loss: 0.982, Validation Accuracy: 0.438 [repeated 149x across cluster]
(FLClient pid=2883220) 2025-04-11 09:24:14,978 - INFO - Epoch   0| Train Loss: 1.013| Train Accuracy: 0.500 [repeated 449x across cluster]
(FLClient pid=2883483) 2025-04-11 09:24:14,666 - INFO - Epoch   2| Validation Loss: 1.068, Validation Accuracy: 0.391 [repeated 150x across cluster]
(FLClient pid=2883220) 2025-04-11 09:24:20,158 - INFO - Epoch   2| Train Loss: 0.573| Train Accuracy: 0.500 [repeated 452x across cluster]
(FLClient pid=2883220) 2025-04-11 09:24:20,166 - INFO - Epoch   2| Validation Loss: 1.280, Validation Accuracy: 0.295 [repeated 151x across cluster]
(FLClient pid=2883220) 2025-04-11 09:24:25,411 - INFO - Epoch   2| Train Loss: 0.532| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2883220) 2025-04-11 09:24:25,418 - INFO - Epoch   2| Validation Loss: 0.936, Validation Accuracy: 0.455 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.256, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.077, Train Accuracy: 0.400
Train Loss: 1.296, Train Accuracy: 0.600
Train Loss: 1.179, Train Accuracy: 0.625
Train Loss: 1.231, Train Accuracy: 0.800
Train Loss: 1.379, Train Accuracy: 0.500
Train Loss: 1.137, Train Accuracy: 0.400
Train Loss: 1.582, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.400
Round 2
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.072, Train Accuracy: 0.600
Train Loss: 1.377, Train Accuracy: 0.600
Train Loss: 1.206, Train Accuracy: 0.625
Train Loss: 1.262, Train Accuracy: 0.800
Train Loss: 1.412, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.600
Train Loss: 1.736, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.500
Round 3
Train Loss: 1.286, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.061, Train Accuracy: 0.400
Train Loss: 1.336, Train Accuracy: 0.600
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.381, Train Accuracy: 0.750
Train Loss: 1.218, Train Accuracy: 0.400
Train Loss: 1.785, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.400
Round 4
Train Loss: 1.279, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Train Loss: 1.056, Train Accuracy: 0.400
Train Loss: 1.391, Train Accuracy: 0.600
Train Loss: 1.234, Train Accuracy: 0.625
Train Loss: 1.257, Train Accuracy: 0.800
Train Loss: 1.416, Train Accuracy: 0.250
Train Loss: 1.155, Train Accuracy: 0.400
Train Loss: 1.731, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.500
Round 5
Train Loss: 1.287, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.500
Train Loss: 1.051, Train Accuracy: 0.400
Train Loss: 1.418, Train Accuracy: 0.600
Train Loss: 1.217, Train Accuracy: 0.750
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.454, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.200
Train Loss: 1.784, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.400
Round 6
Train Loss: 1.305, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Train Loss: 1.049, Train Accuracy: 0.400
Train Loss: 1.433, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.425, Train Accuracy: 0.250
Train Loss: 1.196, Train Accuracy: 0.600
Train Loss: 1.880, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.500
Round 7
Train Loss: 1.337, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.500
Train Loss: 1.065, Train Accuracy: 0.400
Train Loss: 1.423, Train Accuracy: 0.600
Train Loss: 1.249, Train Accuracy: 0.625
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.471, Train Accuracy: 0.500
Train Loss: 1.171, Train Accuracy: 0.400
Train Loss: 1.801, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.500
Round 8
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.500
Train Loss: 1.058, Train Accuracy: 0.600
Train Loss: 1.393, Train Accuracy: 0.600
Train Loss: 1.203, Train Accuracy: 0.625
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.417, Train Accuracy: 0.250
Train Loss: 1.145, Train Accuracy: 0.400
Train Loss: 1.801, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.400
Round 9
Train Loss: 1.312, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.500
Train Loss: 1.046, Train Accuracy: 0.200
Train Loss: 1.484, Train Accuracy: 0.600
Train Loss: 1.255, Train Accuracy: 0.625
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.464, Train Accuracy: 0.500
Train Loss: 1.263, Train Accuracy: 0.600
Train Loss: 1.973, Train Accuracy: 0.750
Train Loss: 1.193, Train Accuracy: 0.300
Round 10
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.050, Train Accuracy: 0.400
Train Loss: 1.557, Train Accuracy: 0.600
Train Loss: 1.259, Train Accuracy: 0.625
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.454, Train Accuracy: 0.250
Train Loss: 1.136, Train Accuracy: 0.400
Train Loss: 1.980, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.500
Round 11
Train Loss: 1.360, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.600
Train Loss: 1.054, Train Accuracy: 0.400
Train Loss: 1.462, Train Accuracy: 0.600
Train Loss: 1.244, Train Accuracy: 0.625
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.490, Train Accuracy: 0.500
Train Loss: 1.266, Train Accuracy: 0.400
Train Loss: 1.948, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.500
Round 12
Train Loss: 1.313, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.600
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.474, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.625
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.543, Train Accuracy: 0.750
Train Loss: 1.277, Train Accuracy: 0.400
Train Loss: 1.840, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.400
Round 13
Train Loss: 1.356, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.500
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.458, Train Accuracy: 0.600
Train Loss: 1.264, Train Accuracy: 0.625
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.498, Train Accuracy: 0.500
Train Loss: 1.243, Train Accuracy: 0.400
Train Loss: 1.904, Train Accuracy: 0.750
Train Loss: 1.207, Train Accuracy: 0.600
Round 14
Train Loss: 1.316, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.500
Train Loss: 1.033, Train Accuracy: 0.400
Train Loss: 1.445, Train Accuracy: 0.600
Train Loss: 1.264, Train Accuracy: 0.750
Train Loss: 1.415, Train Accuracy: 0.800
Train Loss: 1.512, Train Accuracy: 0.500
Train Loss: 1.187, Train Accuracy: 0.400
Train Loss: 2.062, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.700
Round 15
Train Loss: 1.372, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.600
Train Loss: 1.036, Train Accuracy: 0.200
Train Loss: 1.478, Train Accuracy: 0.600
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.498, Train Accuracy: 0.500
Train Loss: 1.232, Train Accuracy: 0.400
Train Loss: 1.899, Train Accuracy: 0.750
Train Loss: 1.213, Train Accuracy: 0.600
Round 16
Train Loss: 1.290, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.478, Train Accuracy: 0.600
Train Loss: 1.194, Train Accuracy: 0.750
Train Loss: 1.319, Train Accuracy: 0.800
Train Loss: 1.466, Train Accuracy: 0.750
Train Loss: 1.221, Train Accuracy: 0.200
Train Loss: 1.913, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.400
Round 17
Train Loss: 1.362, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.600
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.531, Train Accuracy: 0.800
Train Loss: 1.282, Train Accuracy: 0.625
Train Loss: 1.379, Train Accuracy: 0.800
Train Loss: 1.515, Train Accuracy: 0.750
Train Loss: 1.243, Train Accuracy: 0.400
Train Loss: 2.088, Train Accuracy: 0.750
Train Loss: 1.146, Train Accuracy: 0.500
Round 18
Train Loss: 1.379, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.500
Train Loss: 1.012, Train Accuracy: 0.400
Train Loss: 1.487, Train Accuracy: 0.600
Train Loss: 1.296, Train Accuracy: 0.625
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.564, Train Accuracy: 0.500
Train Loss: 1.195, Train Accuracy: 0.400
Train Loss: 1.935, Train Accuracy: 0.750
Train Loss: 1.203, Train Accuracy: 0.500
Round 19
Train Loss: 1.342, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.374, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.568, Train Accuracy: 0.500
Train Loss: 1.242, Train Accuracy: 0.400
Train Loss: 1.904, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.500
Round 20
Train Loss: 1.246, Train Accuracy: 0.750
Train Loss: 1.036, Train Accuracy: 0.600
Train Loss: 1.017, Train Accuracy: 0.200
Train Loss: 1.498, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.521, Train Accuracy: 0.500
Train Loss: 1.198, Train Accuracy: 0.200
Train Loss: 1.966, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.700
Round 21
Train Loss: 1.293, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.500
Train Loss: 1.011, Train Accuracy: 0.200
Train Loss: 1.531, Train Accuracy: 0.600
Train Loss: 1.274, Train Accuracy: 0.750
Train Loss: 1.329, Train Accuracy: 0.800
Train Loss: 1.521, Train Accuracy: 0.500
Train Loss: 1.126, Train Accuracy: 0.400
Train Loss: 2.039, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.700
Round 22
Train Loss: 1.329, Train Accuracy: 0.500
Train Loss: 1.021, Train Accuracy: 0.500
Train Loss: 1.004, Train Accuracy: 0.400
Train Loss: 1.475, Train Accuracy: 0.800
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.546, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.600
Train Loss: 2.142, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.600
Round 23
Train Loss: 1.288, Train Accuracy: 0.750
Train Loss: 1.018, Train Accuracy: 0.600
Train Loss: 1.004, Train Accuracy: 0.200
Train Loss: 1.463, Train Accuracy: 0.600
Train Loss: 1.221, Train Accuracy: 0.750
Train Loss: 1.388, Train Accuracy: 0.800
Train Loss: 1.516, Train Accuracy: 0.500
Train Loss: 1.235, Train Accuracy: 0.800
Train Loss: 2.201, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.500
Round 24
Train Loss: 1.340, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.600
Train Loss: 0.996, Train Accuracy: 0.600
Train Loss: 1.503, Train Accuracy: 0.800
Train Loss: 1.220, Train Accuracy: 0.750
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.538, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.600
Train Loss: 1.996, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.600
Round 25
Train Loss: 1.346, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.400
Train Loss: 0.995, Train Accuracy: 0.400
Train Loss: 1.490, Train Accuracy: 0.800
Train Loss: 1.266, Train Accuracy: 0.625
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.557, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.600
Train Loss: 2.036, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.500
Round 26
Train Loss: 1.333, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.500
Train Loss: 1.001, Train Accuracy: 0.400
Train Loss: 1.436, Train Accuracy: 0.800
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.314, Train Accuracy: 0.800
Train Loss: 1.463, Train Accuracy: 0.500
Train Loss: 1.177, Train Accuracy: 0.400
Train Loss: 2.092, Train Accuracy: 0.750
Train Loss: 1.114, Train Accuracy: 0.500
Round 27
Train Loss: 1.139, Train Accuracy: 0.750
Train Loss: 1.020, Train Accuracy: 0.500
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.331, Train Accuracy: 0.600
Train Loss: 1.232, Train Accuracy: 0.750
Train Loss: 1.410, Train Accuracy: 0.800
Train Loss: 1.604, Train Accuracy: 0.500
Train Loss: 1.173, Train Accuracy: 0.600
Train Loss: 1.998, Train Accuracy: 0.750
Train Loss: 1.104, Train Accuracy: 0.500
Round 28
Train Loss: 1.312, Train Accuracy: 0.750
Train Loss: 1.030, Train Accuracy: 0.500
Train Loss: 0.992, Train Accuracy: 0.600
Train Loss: 1.413, Train Accuracy: 0.600
Train Loss: 1.143, Train Accuracy: 0.750
Train Loss: 1.295, Train Accuracy: 0.800
Train Loss: 1.485, Train Accuracy: 1.000
Train Loss: 1.116, Train Accuracy: 0.600
Train Loss: 2.221, Train Accuracy: 0.750
Train Loss: 1.107, Train Accuracy: 0.500
Round 29
Train Loss: 1.246, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.600
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 1.478, Train Accuracy: 0.600
Train Loss: 1.209, Train Accuracy: 0.750
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.579, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.600
Train Loss: 1.813, Train Accuracy: 0.750
Train Loss: 1.110, Train Accuracy: 0.500
Round 30
Train Loss: 1.203, Train Accuracy: 0.750
Train Loss: 1.009, Train Accuracy: 0.200
Train Loss: 0.989, Train Accuracy: 0.400
Train Loss: 1.390, Train Accuracy: 0.600
Train Loss: 1.178, Train Accuracy: 0.750
Train Loss: 1.364, Train Accuracy: 0.800
Train Loss: 1.462, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.600
Train Loss: 2.212, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.600
Round 31
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 0.989, Train Accuracy: 0.600
Train Loss: 0.981, Train Accuracy: 0.400
Train Loss: 1.400, Train Accuracy: 0.600
Train Loss: 1.203, Train Accuracy: 0.625
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.574, Train Accuracy: 0.500
Train Loss: 1.096, Train Accuracy: 0.400
Train Loss: 2.220, Train Accuracy: 1.000
Train Loss: 1.089, Train Accuracy: 0.600
Round 32
Train Loss: 1.449, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.500
Train Loss: 0.990, Train Accuracy: 0.400
Train Loss: 1.413, Train Accuracy: 0.800
Train Loss: 1.210, Train Accuracy: 0.625
Train Loss: 1.402, Train Accuracy: 0.800
Train Loss: 1.374, Train Accuracy: 0.500
Train Loss: 1.227, Train Accuracy: 0.400
Train Loss: 1.999, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.400
Round 33
Train Loss: 1.266, Train Accuracy: 0.750
Train Loss: 1.005, Train Accuracy: 0.600
Train Loss: 0.995, Train Accuracy: 0.400
Train Loss: 1.507, Train Accuracy: 1.000
Train Loss: 1.173, Train Accuracy: 0.750
Train Loss: 1.408, Train Accuracy: 0.800
Train Loss: 1.669, Train Accuracy: 0.500
Train Loss: 1.193, Train Accuracy: 0.600
Train Loss: 1.926, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.600
Round 34
Train Loss: 1.404, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.700
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.416, Train Accuracy: 0.800
Train Loss: 1.214, Train Accuracy: 0.750
Train Loss: 1.275, Train Accuracy: 0.800
Train Loss: 1.525, Train Accuracy: 1.000
Train Loss: 1.168, Train Accuracy: 0.200
Train Loss: 2.135, Train Accuracy: 1.000
Train Loss: 1.258, Train Accuracy: 0.300
Round 35
Train Loss: 1.202, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.600
Train Loss: 0.960, Train Accuracy: 0.400
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.193, Train Accuracy: 0.750
Train Loss: 1.268, Train Accuracy: 0.800
Train Loss: 1.664, Train Accuracy: 0.500
Train Loss: 1.141, Train Accuracy: 0.600
Train Loss: 2.048, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.400
Round 36
Train Loss: 1.312, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.600
Train Loss: 1.000, Train Accuracy: 0.600
Train Loss: 1.332, Train Accuracy: 0.600
Train Loss: 1.147, Train Accuracy: 0.750
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.666, Train Accuracy: 0.500
Train Loss: 1.096, Train Accuracy: 0.600
Train Loss: 2.008, Train Accuracy: 0.750
Train Loss: 1.155, Train Accuracy: 0.500
Round 37
Train Loss: 1.293, Train Accuracy: 0.750
Train Loss: 0.984, Train Accuracy: 0.800
Train Loss: 0.992, Train Accuracy: 0.600
Train Loss: 1.339, Train Accuracy: 0.600
Train Loss: 1.293, Train Accuracy: 0.625
Train Loss: 1.369, Train Accuracy: 0.800
Train Loss: 1.637, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 2.203, Train Accuracy: 0.750
Train Loss: 1.123, Train Accuracy: 0.500
Round 38
Train Loss: 1.466, Train Accuracy: 0.750
Train Loss: 0.967, Train Accuracy: 0.500
Train Loss: 0.954, Train Accuracy: 0.400
Train Loss: 1.496, Train Accuracy: 0.800
Train Loss: 1.255, Train Accuracy: 0.625
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.522, Train Accuracy: 0.750
Train Loss: 1.131, Train Accuracy: 0.600
Train Loss: 1.836, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.800
Round 39
Train Loss: 1.385, Train Accuracy: 0.750
Train Loss: 0.988, Train Accuracy: 0.800
Train Loss: 0.949, Train Accuracy: 0.600
Train Loss: 1.412, Train Accuracy: 1.000
Train Loss: 1.158, Train Accuracy: 0.625
Train Loss: 1.508, Train Accuracy: 0.800
Train Loss: 1.574, Train Accuracy: 1.000
Train Loss: 1.112, Train Accuracy: 0.600
Train Loss: 2.151, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.500
Round 40
Train Loss: 1.406, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.300
Train Loss: 0.950, Train Accuracy: 0.600
Train Loss: 1.191, Train Accuracy: 0.800
Train Loss: 1.142, Train Accuracy: 0.750
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.590, Train Accuracy: 0.500
Train Loss: 1.110, Train Accuracy: 0.800
Train Loss: 2.086, Train Accuracy: 0.750
Train Loss: 1.306, Train Accuracy: 0.600
Round 41
Train Loss: 1.199, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.800
Train Loss: 0.936, Train Accuracy: 0.400
Train Loss: 1.356, Train Accuracy: 0.800
Train Loss: 1.143, Train Accuracy: 0.750
Train Loss: 1.233, Train Accuracy: 0.800
Train Loss: 1.749, Train Accuracy: 0.500
Train Loss: 1.227, Train Accuracy: 0.200
Train Loss: 2.214, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.200
Round 42
Train Loss: 1.302, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.700
Train Loss: 0.960, Train Accuracy: 0.600
Train Loss: 1.395, Train Accuracy: 0.800
Train Loss: 1.137, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.800
Train Loss: 1.676, Train Accuracy: 0.500
Train Loss: 1.069, Train Accuracy: 0.400
Train Loss: 2.059, Train Accuracy: 0.750
Train Loss: 0.982, Train Accuracy: 0.400
Round 43
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 1.017, Train Accuracy: 0.600
Train Loss: 0.955, Train Accuracy: 0.600
Train Loss: 1.400, Train Accuracy: 0.800
Train Loss: 1.129, Train Accuracy: 0.875
Train Loss: 1.257, Train Accuracy: 0.800
Train Loss: 1.538, Train Accuracy: 1.000
Train Loss: 1.126, Train Accuracy: 0.600
Train Loss: 1.936, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.500
Round 44
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.500
Train Loss: 0.919, Train Accuracy: 0.400
Train Loss: 1.367, Train Accuracy: 0.800
Train Loss: 1.091, Train Accuracy: 0.750
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.667, Train Accuracy: 0.500
Train Loss: 1.222, Train Accuracy: 0.800
Train Loss: 2.159, Train Accuracy: 0.750
Train Loss: 1.108, Train Accuracy: 0.600
Round 45
Train Loss: 1.319, Train Accuracy: 0.750
Train Loss: 0.951, Train Accuracy: 0.700
Train Loss: 0.946, Train Accuracy: 0.400
Train Loss: 1.187, Train Accuracy: 0.800
Train Loss: 1.192, Train Accuracy: 0.625
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.556, Train Accuracy: 0.750
Train Loss: 1.122, Train Accuracy: 0.400
Train Loss: 2.049, Train Accuracy: 0.750
Train Loss: 1.014, Train Accuracy: 0.600
Round 46
Train Loss: 1.222, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.600
Train Loss: 0.953, Train Accuracy: 0.600
Train Loss: 1.512, Train Accuracy: 0.800
Train Loss: 1.119, Train Accuracy: 0.750
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.437, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.600
Train Loss: 2.093, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.700
Round 47
Train Loss: 1.177, Train Accuracy: 0.500
Train Loss: 0.937, Train Accuracy: 0.600
Train Loss: 0.916, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.600
Train Loss: 1.085, Train Accuracy: 0.500
Train Loss: 1.374, Train Accuracy: 0.800
Train Loss: 1.736, Train Accuracy: 0.500
Train Loss: 1.084, Train Accuracy: 0.600
Train Loss: 1.696, Train Accuracy: 0.750
Train Loss: 1.508, Train Accuracy: 0.600
Round 48
Train Loss: 1.159, Train Accuracy: 0.750
Train Loss: 1.009, Train Accuracy: 0.600
Train Loss: 0.983, Train Accuracy: 0.600
Train Loss: 1.661, Train Accuracy: 0.800
Train Loss: 1.100, Train Accuracy: 0.625
Train Loss: 1.288, Train Accuracy: 0.800
Train Loss: 1.774, Train Accuracy: 0.750

(FLClient pid=2883483) 2025-04-11 09:24:29,530 - INFO - Epoch   2| Train Loss: 0.452| Train Accuracy: 0.900 [repeated 387x across cluster]
(FLClient pid=2883483) 2025-04-11 09:24:29,537 - INFO - Epoch   2| Validation Loss: 0.993, Validation Accuracy: 0.500 [repeated 129x across cluster]

Results saved to Central_results4/Pubmed_diffusion_GCN/results_Pubmed_diffusion_GCN.txt

In [2]:
import os
import ast # To safely evaluate string literal as dictionary
import pandas as pd
import logging # Using logging for better error reporting

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def process_results_folder(main_folder_path):
    """
    Processes experiment results stored in subfolders of a main directory.

    Reads .txt files containing dictionary-like strings, parses them,
    and organizes the configuration and summary data into a Pandas DataFrame.

    Args:
        main_folder_path (str): The path to the main results folder
                                (e.g., 'Central_results2').

    Returns:
        pandas.DataFrame: A DataFrame containing the structured results,
                          with each row representing an experiment.
                          Returns an empty DataFrame if the folder is not found
                          or no valid results are processed.
    """
    all_results_data = [] # List to hold data for each valid experiment

    # --- Input Validation ---
    if not os.path.isdir(main_folder_path):
        logging.error(f"Folder not found at '{main_folder_path}'")
        return pd.DataFrame() # Return empty DataFrame

    logging.info(f"Starting processing for folder: '{main_folder_path}'")

    # --- Iterate Through Subfolders ---
    try:
        subfolder_names = os.listdir(main_folder_path)
    except OSError as e:
        logging.error(f"Could not list directory contents for '{main_folder_path}': {e}")
        return pd.DataFrame()

    for item_name in subfolder_names:
        subfolder_path = os.path.join(main_folder_path, item_name)

        # Check if it's actually a directory
        if not os.path.isdir(subfolder_path):
            logging.debug(f"Skipping non-directory item: '{item_name}'")
            continue

        logging.info(f"Processing subfolder: '{item_name}'")

        # --- Find the .txt File ---
        txt_file_path = None
        try:
            files_in_subfolder = os.listdir(subfolder_path)
            for filename in files_in_subfolder:
                if filename.endswith(".txt"):
                    # Assume only one relevant .txt file per subfolder
                    txt_file_path = os.path.join(subfolder_path, filename)
                    logging.debug(f"Found results file: '{filename}'")
                    break # Stop searching in this subfolder once found
            if not txt_file_path:
                 logging.warning(f"No .txt file found in subfolder '{item_name}'. Skipping.")
                 continue
        except OSError as e:
            logging.warning(f"Could not list files in subfolder '{item_name}': {e}. Skipping.")
            continue

        # --- Read and Parse File Content ---
        try:
            with open(txt_file_path, 'r', encoding='utf-8') as f:
                content = f.read()

            # Safely parse the string content into a Python dictionary
            # ast.literal_eval is safer than eval() for untrusted input
            data = ast.literal_eval(content)

            if not isinstance(data, dict):
                 logging.warning(f"Parsed content from '{txt_file_path}' is not a dictionary. Skipping.")
                 continue

        except FileNotFoundError:
            # This might happen in rare race conditions if the file is deleted
            # between listing and opening
            logging.warning(f"File '{txt_file_path}' found initially but could not be opened. Skipping.")
            continue
        except (SyntaxError, ValueError) as e:
            logging.warning(f"Error parsing content in file '{txt_file_path}': {e}. Skipping.")
            continue
        except Exception as e:
            logging.error(f"An unexpected error occurred reading/parsing '{txt_file_path}': {e}. Skipping.")
            continue

        # --- Extract Data ---
        # Use .get() for safer access in case keys are missing
        config = data.get('experiment_config', {})
        summary = data.get('summary', {})

        if not config or not summary:
             logging.warning(f"Missing 'experiment_config' or 'summary' key in '{txt_file_path}'. Skipping file.")
             continue

        # Create a flat dictionary for the DataFrame row
        # Start with configuration parameters
        row_data = config.copy()

        # Add summary results, prefixing keys if needed to avoid clashes (optional)
        # Example: prefix summary keys with 'summary_'
        # summary_prefixed = {f'summary_{k}': v for k, v in summary.items()}
        # row_data.update(summary_prefixed)

        # Or just update directly if keys are distinct
        row_data.update(summary)

        # Add an identifier for the experiment (using subfolder name)
        row_data['experiment_id'] = item_name
        # You could also add the filename if needed:
        # row_data['source_file'] = os.path.basename(txt_file_path)

        # Remove potentially large list/dict columns if not needed directly in the summary table
        # Adjust these based on what you want in the final table
        row_data.pop('global_results', None) # Remove list of all global results per round
        row_data.pop('client_results', None) # Remove list of all client results per round
        row_data.pop('rounds', None)         # Remove the detailed rounds data

        all_results_data.append(row_data)
        logging.debug(f"Successfully processed data for experiment '{item_name}'")

    # --- Create DataFrame ---
    if not all_results_data:
        logging.warning("No valid experiment data found to create a DataFrame.")
        return pd.DataFrame()

    try:
        results_df = pd.DataFrame(all_results_data)
        logging.info(f"Successfully created DataFrame with {len(results_df)} rows.")

        # Optional: Reorder columns for better readability
        id_col = ['experiment_id']
        config_cols = list(data.get('experiment_config', {}).keys())
        summary_cols = list(k for k in data.get('summary', {}).keys() if k not in ['global_results', 'client_results']) # Get summary keys added
        # Filter out columns that might not exist in all rows if parsing failed partially
        existing_cols = [col for col in id_col + config_cols + summary_cols if col in results_df.columns]
        results_df = results_df[existing_cols]

        # Optional: Set experiment_id as the DataFrame index
        # results_df.set_index('experiment_id', inplace=True)

    except Exception as e:
        logging.error(f"Failed to create DataFrame from processed data: {e}")
        return pd.DataFrame()


    return results_df

# --- Example Usage ---
# Note: Replace 'Central_results2' with the actual path to your folder.
# If running this script, make sure the folder exists relative to the script
# or provide an absolute path.

# Create dummy structure for demonstration if needed
def create_dummy_structure(base_dir="Central_results2_demo"):
    if not os.path.exists(base_dir):
        os.makedirs(base_dir)
    # Sample data similar to the user's example
    experiments_data = {
        "Pubmed_adjacency_GCN": {'experiment_config': {'device': 'cuda', 'data_loading_option': 'adjacency', 'model_type': 'GCN', 'dataset': 'Pubmed', 'num_clients': 10, 'beta': 1, 'hop': 1, 'fulltraining_flag': False}, 'rounds': [{'round': 1, 'global_result': 0.715, 'client_result': 0.724}, {'round': 2, 'global_result': 0.67, 'client_result': 0.698}], 'summary': {'global_results': [0.715, 0.67], 'client_results': [0.724, 0.698], 'average_global_result': 0.6925, 'average_client_result': 0.711, 'std_global': 0.0225, 'std_client': 0.013}},
        "Pubmed_diffusion_GCN": {'experiment_config': {'device': 'cuda', 'data_loading_option': 'diffusion', 'model_type': 'GCN', 'dataset': 'Pubmed', 'num_clients': 10, 'beta': 1, 'hop': 2, 'fulltraining_flag': False}, 'rounds': [], 'summary': {'average_global_result': 0.701, 'average_client_result': 0.715, 'std_global': 0.021, 'std_client': 0.012}},
        "Cora_full_SAGE": {'experiment_config': {'device': 'cpu', 'data_loading_option': 'full', 'model_type': 'SAGE', 'dataset': 'Cora', 'num_clients': 1, 'beta': 0, 'hop': 0, 'fulltraining_flag': True}, 'rounds': [], 'summary': {'average_global_result': 0.81, 'average_client_result': 0.81, 'std_global': 0.0, 'std_client': 0.0}},
        "Folder_With_Invalid_Txt": "This is not a dictionary string", # Test invalid content
        "Folder_With_No_Txt": {}, # Test missing txt file
        "Folder_With_Missing_Keys": {'experiment_config': {'device': 'cpu'}, 'summary': {}} # Test missing keys
    }
    logging.info(f"Creating dummy structure in '{base_dir}'...")
    for folder_name, data in experiments_data.items():
        subfolder_path = os.path.join(base_dir, folder_name)
        if not os.path.exists(subfolder_path):
            os.makedirs(subfolder_path)

        if folder_name == "Folder_With_No_Txt":
            # Create an empty file or a file with a different extension
            with open(os.path.join(subfolder_path, "other_file.log"), 'w') as f:
                f.write("Log data")
            continue # Don't create the specific .txt file

        # Create the results text file
        txt_filename = f"results_{folder_name}.txt"
        txt_filepath = os.path.join(subfolder_path, txt_filename)
        try:
            with open(txt_filepath, 'w', encoding='utf-8') as f:
                if isinstance(data, dict):
                    # Convert dict to string representation for the file
                    f.write(str(data))
                else:
                    # Write invalid data directly
                    f.write(data)
        except IOError as e:
            logging.error(f"Failed to write dummy file {txt_filepath}: {e}")
    logging.info("Dummy structure created.")


# --- Main execution block ---
if __name__ == "__main__":
    # Create dummy data for testing
    dummy_folder_path = "Central_results2_demo"
    create_dummy_structure(dummy_folder_path)

    # Process the results folder
    results_dataframe = process_results_folder(dummy_folder_path)

    # Display the results
    if not results_dataframe.empty:
        print("\n--- Processed Results DataFrame ---")
        # Configure pandas display options for better readability
        pd.set_option('display.max_columns', None) # Show all columns
        pd.set_option('display.width', 1000)       # Adjust width
        print(results_dataframe)
    else:
        print("\nNo DataFrame was generated. Check log messages for details.")

    # Clean up dummy structure (optional)
    # import shutil
    # try:
    #     shutil.rmtree(dummy_folder_path)
    #     logging.info(f"Cleaned up dummy directory: '{dummy_folder_path}'")
    # except OSError as e:
    #     logging.error(f"Error removing dummy directory '{dummy_folder_path}': {e}")

2025-04-11 09:38:42,584 - INFO - Creating dummy structure in 'Central_results2_demo'...
2025-04-11 09:38:42,586 - INFO - Dummy structure created.
2025-04-11 09:38:42,587 - INFO - Starting processing for folder: 'Central_results2_demo'
2025-04-11 09:38:42,587 - INFO - Processing subfolder: 'Folder_With_Missing_Keys'
2025-04-11 09:38:42,588 - WARNING - Missing 'experiment_config' or 'summary' key in 'Central_results2_demo/Folder_With_Missing_Keys/results_Folder_With_Missing_Keys.txt'. Skipping file.
2025-04-11 09:38:42,588 - INFO - Processing subfolder: 'Folder_With_No_Txt'
2025-04-11 09:38:42,589 - WARNING - No .txt file found in subfolder 'Folder_With_No_Txt'. Skipping.
2025-04-11 09:38:42,589 - INFO - Processing subfolder: 'Folder_With_Invalid_Txt'
2025-04-11 09:38:42,590 - WARNING - Error parsing content in file 'Central_results2_demo/Folder_With_Invalid_Txt/results_Folder_With_Invalid_Txt.txt': invalid syntax (<unknown>, line 1). Skipping.
2025-04-11 09:38:42,590 - INFO - Processing subfolder: 'Cora_full_SAGE'
2025-04-11 09:38:42,591 - INFO - Processing subfolder: 'Pubmed_adjacency_GCN'
2025-04-11 09:38:42,591 - INFO - Processing subfolder: 'Pubmed_diffusion_GCN'
2025-04-11 09:38:42,593 - INFO - Successfully created DataFrame with 3 rows.

--- Processed Results DataFrame ---
          experiment_id device data_loading_option model_type dataset  num_clients  beta  hop  fulltraining_flag  average_global_result  average_client_result  std_global  std_client
0        Cora_full_SAGE    cpu                full       SAGE    Cora            1     0    0               True                 0.8100                  0.810      0.0000       0.000
1  Pubmed_adjacency_GCN   cuda           adjacency        GCN  Pubmed           10     1    1              False                 0.6925                  0.711      0.0225       0.013
2  Pubmed_diffusion_GCN   cuda           diffusion        GCN  Pubmed           10     1    2              False                 0.7010                  0.715      0.0210       0.012

In [3]:
results_folder = "Central_results2"
df = process_results_folder(results_folder)

2025-04-11 09:38:44,753 - INFO - Starting processing for folder: 'Central_results2'
2025-04-11 09:38:44,754 - INFO - Processing subfolder: 'Pubmed_zero_GCN'
2025-04-11 09:38:44,754 - INFO - Processing subfolder: 'Pubmed_full_GCN'
2025-04-11 09:38:44,755 - INFO - Processing subfolder: 'Pubmed_adjacency_GCN'
2025-04-11 09:38:44,756 - INFO - Processing subfolder: 'Pubmed_diffusion_GCN'
2025-04-11 09:38:44,757 - INFO - Successfully created DataFrame with 4 rows.

In [4]:
df

          experiment_id device data_loading_option model_type dataset  num_clients  beta  hop  fulltraining_flag  average_global_result  average_client_result  std_global  std_client
0       Pubmed_zero_GCN   cuda                zero        GCN  Pubmed           10     1    1              False                 0.5725               0.450772      0.0715    0.084506
1       Pubmed_full_GCN   cuda                full        GCN  Pubmed           10     1    1              False                 0.7195               0.724965      0.0035    0.009670
2  Pubmed_adjacency_GCN   cuda           adjacency        GCN  Pubmed           10     1    1              False                 0.6925               0.711236      0.0225    0.013122
3  Pubmed_diffusion_GCN   cuda           diffusion        GCN  Pubmed           10     1    1              False                 0.7140               0.714027      0.0030    0.000312

In [5]:
results_folder2 = "Central_results3"
df2 = process_results_folder(results_folder2)
df2

2025-04-11 09:38:45,683 - INFO - Starting processing for folder: 'Central_results3'
2025-04-11 09:38:45,683 - INFO - Processing subfolder: 'Pubmed_zero_GCN'
2025-04-11 09:38:45,684 - INFO - Processing subfolder: 'Pubmed_full_GCN'
2025-04-11 09:38:45,685 - INFO - Processing subfolder: 'Pubmed_adjacency_GCN'
2025-04-11 09:38:45,686 - INFO - Processing subfolder: 'Pubmed_diffusion_GCN'
2025-04-11 09:38:45,687 - INFO - Successfully created DataFrame with 4 rows.

          experiment_id device data_loading_option model_type dataset  num_clients   beta  hop  fulltraining_flag  average_global_result  average_client_result  std_global  std_client
0       Pubmed_zero_GCN   cuda                zero        GCN  Pubmed           10  10000    1              False                  0.515               0.468085       0.003    0.015345
1       Pubmed_full_GCN   cuda                full        GCN  Pubmed           10  10000    1              False                  0.725               0.706215       0.002    0.004191
2  Pubmed_adjacency_GCN   cuda           adjacency        GCN  Pubmed           10  10000    1              False                  0.698               0.672976       0.040    0.071713
3  Pubmed_diffusion_GCN   cuda           diffusion        GCN  Pubmed           10  10000    1              False                  0.719               0.736479       0.032    0.043827

In [6]:
results_folder3 = "Central_results4"
df3 = process_results_folder(results_folder3)
df3

2025-04-11 09:38:46,297 - INFO - Starting processing for folder: 'Central_results4'
2025-04-11 09:38:46,298 - INFO - Processing subfolder: 'Pubmed_full_GCN'
2025-04-11 09:38:46,298 - INFO - Processing subfolder: 'Pubmed_adjacency_GCN'
2025-04-11 09:38:46,299 - INFO - Processing subfolder: 'Pubmed_diffusion_GCN'
2025-04-11 09:38:46,301 - INFO - Successfully created DataFrame with 3 rows.

          experiment_id device data_loading_option model_type dataset  num_clients   beta  hop  fulltraining_flag  average_global_result  average_client_result  std_global  std_client
0       Pubmed_full_GCN   cuda                full        GCN  Pubmed           10  10000    1              False                 0.6913               0.684061    0.048413    0.044691
1  Pubmed_adjacency_GCN   cuda           adjacency        GCN  Pubmed           10  10000    1              False                 0.7201               0.716847    0.055193    0.062479
2  Pubmed_diffusion_GCN   cuda           diffusion        GCN  Pubmed           10  10000    1              False                 0.6702               0.659849    0.068670    0.076445