In [1]:
import sys
import os
import torch

In [2]:
# from federated_learning_cuda import load_configuration, main_experiment
from run import load_configuration, main_experiment

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")   
from run import load_and_split_with_khop, load_and_split_with_feature_prop
dataset_name = "Cora"
num_clients = 10
beta = 1
hop = 1
data_loading_option = "full"
fulltraining_flag = False

In [4]:
cora_data = load_and_split_with_khop(dataset_name, device, num_clients, beta, hop=hop, imputation_method=data_loading_option, fulltraining_flag=fulltraining_flag)

In [5]:
len(cora_data)

4

In [6]:
# # check client 0 data
# print(clients_data[0])
# # check number of nodes in client 0 with zerof feature vectors
# # also check train/test/val nodes the number
# #total nodes in client 0
# total_nodes = clients_data[0].x.shape[0]
# #nodes with zero feature vectors
# zfv_nodes = torch.sum(clients_data[0].x == 0)
# print(f"Number of nodes in client 0 with zero feature vectors: {torch.sum(clients_data[0].x == 0)}")
# print(f"Number of train nodes in client 0: {torch.sum(clients_data[0].train_mask)}")
# print(f"Number of test nodes in client 0: {torch.sum(clients_data[0].test_mask)}")
# print(f"Number of val nodes in client 0: {torch.sum(clients_data[0].val_mask)}")

In [7]:
# load with fp and check the same things
data, dataset, clients_data, test_data,  = load_and_split_with_feature_prop("Citeseer", device, num_clients=10, beta=0.5, hop=1)

# check client 0 data
print(clients_data[0])
# check number of nodes in client 0 with zerof feature vectors
print(f"Number of nodes in client 0 with zero feature vectors: {torch.sum(clients_data[0].x == 0)}")
print(f"Number of train nodes in client 0: {torch.sum(clients_data[0].train_mask)}")
print(f"Number of test nodes in client 0: {torch.sum(clients_data[0].test_mask)}")
print(f"Number of val nodes in client 0: {torch.sum(clients_data[0].val_mask)}")

Data(x=[936, 3703], edge_index=[2, 2454], y=[936], train_mask=[936], val_mask=[936], test_mask=[936], mapping=[339])
Number of nodes in client 0 with zero feature vectors: 3281071
Number of train nodes in client 0: 7
Number of test nodes in client 0: 104
Number of val nodes in client 0: 55

In [8]:
import torch

print(f"Number of GPUs available: {torch.cuda.device_count()}")

if torch.cuda.is_available():
    for i in range(torch.cuda.device_count()):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
else:
    print("No GPU available")

Number of GPUs available: 1
GPU 0: NVIDIA L40-48Q

In [9]:
# from federated_learning_cuda import load_configuration, main_experiment
from run import load_configuration, main_experiment
import os
import ray
ray.shutdown()

if __name__ == "__main__":
    # Define all options in a list
    data_loading_options = ["full", ]
    model_types = ["GCN"]
        
    # Load configuration once since it's common for all runs
    clients_num, beta, cfg = load_configuration()

    beta = 10000

    clients_num = 10

    # Main results directory
    main_dir = 'Central_results44'
    dataset_name = "Pubmed"  # You can change this if you have different datasets

    # Loop over all combinations of data_loading_option and model_type
    for data_loading_option in data_loading_options:
        for model_type in model_types:
            # Create a structured directory for each experiment
            result_name = f"{dataset_name}_{data_loading_option}_{model_type}"
            results_dir = os.path.join(main_dir, result_name)

            # Create the directory if it doesn't exist
            os.makedirs(results_dir, exist_ok=True)

            print(f"Running experiment with data_loading_option: {data_loading_option}, model_type: {model_type}")
            result, output = main_experiment(clients_num, beta, data_loading_option, model_type, cfg, dataset_name=dataset_name, hop=1)
            
            # Replace literal '\n' with actual newline characters if necessary
            # Convert result dictionary to string representation first
            result_str = str(result)
            result_with_newlines = result_str.replace('\\n', '\n')
            
            # Create a unique filename for each combination
            filename = f'results_{dataset_name}_{data_loading_option}_{model_type}.txt'
            filepath = os.path.join(results_dir, filename)
            
            # Write the result to the text file
            with open(filepath, 'w') as f:
                f.write(result_with_newlines)
            
            print(f"Results saved to {filepath}\n")

Running experiment with data_loading_option: full, model_type: GCN
DEVICE: cuda
Data loading option is full
Model type is GCN

2025-04-29 17:41:19,450	INFO worker.py:1816 -- Started a local Ray instance.

data_loading_option: full
Data loaded
Device is cuda
Pubmed()
10

(FLClient pid=4055747) 2025-04-29 17:41:29,983 - INFO - Epoch   0| Train Loss: 1.106| Train Accuracy: 0.000
(FLClient pid=4055747) 2025-04-29 17:41:29,995 - INFO - Epoch   1| Train Loss: 1.068| Train Accuracy: 0.500
(FLClient pid=4055747) 2025-04-29 17:41:30,007 - INFO - Epoch   2| Train Loss: 1.032| Train Accuracy: 0.500
(FLClient pid=4055747) 2025-04-29 17:41:30,023 - INFO - Epoch   2| Validation Loss: 1.071, Validation Accuracy: 0.467
(FLClient pid=4055748) 2025-04-29 17:41:35,464 - INFO - Epoch   0| Train Loss: 1.090| Train Accuracy: 0.000 [repeated 148x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(FLClient pid=4055753) 2025-04-29 17:41:34,768 - INFO - Epoch   2| Validation Loss: 1.623, Validation Accuracy: 0.233 [repeated 49x across cluster]
(FLClient pid=4055745) 2025-04-29 17:41:40,488 - INFO - Epoch   2| Train Loss: 0.590| Train Accuracy: 0.750 [repeated 212x across cluster]
(FLClient pid=4055754) 2025-04-29 17:41:39,717 - INFO - Epoch   2| Validation Loss: 1.189, Validation Accuracy: 0.156 [repeated 70x across cluster]
(FLClient pid=4055745) 2025-04-29 17:41:45,756 - INFO - Epoch   1| Train Loss: 0.780| Train Accuracy: 0.750 [repeated 209x across cluster]
(FLClient pid=4055753) 2025-04-29 17:41:45,042 - INFO - Epoch   2| Validation Loss: 1.971, Validation Accuracy: 0.233 [repeated 70x across cluster]
(FLClient pid=4055748) 2025-04-29 17:41:51,028 - INFO - Epoch   0| Train Loss: 0.869| Train Accuracy: 0.800 [repeated 209x across cluster]
(FLClient pid=4055756) 2025-04-29 17:41:50,317 - INFO - Epoch   2| Validation Loss: 1.308, Validation Accuracy: 0.414 [repeated 70x across cluster]
(FLClient pid=4055745) 2025-04-29 17:41:56,073 - INFO - Epoch   2| Train Loss: 0.629| Train Accuracy: 0.750 [repeated 212x across cluster]
(FLClient pid=4055745) 2025-04-29 17:41:56,080 - INFO - Epoch   2| Validation Loss: 1.294, Validation Accuracy: 0.295 [repeated 71x across cluster]
(FLClient pid=4055754) 2025-04-29 17:42:01,365 - INFO - Epoch   0| Train Loss: 0.966| Train Accuracy: 0.500 [repeated 208x across cluster]
(FLClient pid=4055754) 2025-04-29 17:42:00,603 - INFO - Epoch   2| Validation Loss: 1.096, Validation Accuracy: 0.469 [repeated 69x across cluster]
(FLClient pid=4055745) 2025-04-29 17:42:06,384 - INFO - Epoch   2| Train Loss: 0.524| Train Accuracy: 0.750 [repeated 212x across cluster]
(FLClient pid=4055754) 2025-04-29 17:42:05,645 - INFO - Epoch   2| Validation Loss: 1.363, Validation Accuracy: 0.156 [repeated 70x across cluster]
(FLClient pid=4055745) 2025-04-29 17:42:11,618 - INFO - Epoch   1| Train Loss: 0.621| Train Accuracy: 0.750 [repeated 209x across cluster]
(FLClient pid=4055754) 2025-04-29 17:42:10,929 - INFO - Epoch   2| Validation Loss: 0.901, Validation Accuracy: 0.391 [repeated 70x across cluster]
(FLClient pid=4055745) 2025-04-29 17:42:16,764 - INFO - Epoch   2| Train Loss: 0.417| Train Accuracy: 0.750 [repeated 211x across cluster]
(FLClient pid=4055745) 2025-04-29 17:42:16,769 - INFO - Epoch   2| Validation Loss: 1.004, Validation Accuracy: 0.386 [repeated 71x across cluster]
(FLClient pid=4055745) 2025-04-29 17:42:22,040 - INFO - Epoch   2| Train Loss: 0.371| Train Accuracy: 0.750 [repeated 300x across cluster]
(FLClient pid=4055745) 2025-04-29 17:42:22,047 - INFO - Epoch   2| Validation Loss: 1.008, Validation Accuracy: 0.364 [repeated 100x across cluster]
(FLClient pid=4055745) 2025-04-29 17:42:27,057 - INFO - Epoch   2| Train Loss: 0.374| Train Accuracy: 0.750 [repeated 210x across cluster]
(FLClient pid=4055745) 2025-04-29 17:42:27,061 - INFO - Epoch   2| Validation Loss: 1.102, Validation Accuracy: 0.295 [repeated 70x across cluster]
(FLClient pid=4055745) 2025-04-29 17:42:32,043 - INFO - Epoch   2| Train Loss: 0.694| Train Accuracy: 0.750 [repeated 210x across cluster]
(FLClient pid=4055745) 2025-04-29 17:42:32,050 - INFO - Epoch   2| Validation Loss: 1.016, Validation Accuracy: 0.318 [repeated 70x across cluster]
(FLClient pid=4055745) 2025-04-29 17:42:37,541 - INFO - Epoch   2| Train Loss: 0.571| Train Accuracy: 0.750 [repeated 240x across cluster]
(FLClient pid=4055745) 2025-04-29 17:42:37,547 - INFO - Epoch   2| Validation Loss: 0.926, Validation Accuracy: 0.432 [repeated 80x across cluster]

Training done
Round 1
Train Loss: 1.222, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.071, Train Accuracy: 0.600
Train Loss: 1.198, Train Accuracy: 0.600
Train Loss: 1.172, Train Accuracy: 0.625
Train Loss: 1.236, Train Accuracy: 0.800
Train Loss: 1.297, Train Accuracy: 0.500
Train Loss: 1.128, Train Accuracy: 0.600
Train Loss: 1.425, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.400
Round 2
Train Loss: 1.241, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.060, Train Accuracy: 0.400
Train Loss: 1.229, Train Accuracy: 0.600
Train Loss: 1.190, Train Accuracy: 0.625
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.370, Train Accuracy: 0.500
Train Loss: 1.141, Train Accuracy: 0.600
Train Loss: 1.360, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.400
Round 3
Train Loss: 1.270, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.500
Train Loss: 1.055, Train Accuracy: 0.600
Train Loss: 1.255, Train Accuracy: 0.600
Train Loss: 1.208, Train Accuracy: 0.625
Train Loss: 1.261, Train Accuracy: 0.800
Train Loss: 1.352, Train Accuracy: 0.500
Train Loss: 1.128, Train Accuracy: 0.600
Train Loss: 1.437, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.400
Round 4
Train Loss: 1.234, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.051, Train Accuracy: 0.400
Train Loss: 1.271, Train Accuracy: 0.600
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.243, Train Accuracy: 0.800
Train Loss: 1.371, Train Accuracy: 0.250
Train Loss: 1.134, Train Accuracy: 0.400
Train Loss: 1.527, Train Accuracy: 0.750
Train Loss: 1.213, Train Accuracy: 0.400
Round 5
Train Loss: 1.272, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.049, Train Accuracy: 0.400
Train Loss: 1.302, Train Accuracy: 0.600
Train Loss: 1.249, Train Accuracy: 0.625
Train Loss: 1.282, Train Accuracy: 0.800
Train Loss: 1.447, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.400
Train Loss: 1.623, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.400
Round 6
Train Loss: 1.303, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.048, Train Accuracy: 0.400
Train Loss: 1.288, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.447, Train Accuracy: 0.500
Train Loss: 1.137, Train Accuracy: 0.600
Train Loss: 1.681, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.400
Round 7
Train Loss: 1.355, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 1.323, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.312, Train Accuracy: 0.800
Train Loss: 1.403, Train Accuracy: 0.500
Train Loss: 1.197, Train Accuracy: 0.400
Train Loss: 1.726, Train Accuracy: 0.750
Train Loss: 1.192, Train Accuracy: 0.400
Round 8
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.323, Train Accuracy: 0.600
Train Loss: 1.255, Train Accuracy: 0.625
Train Loss: 1.257, Train Accuracy: 0.800
Train Loss: 1.468, Train Accuracy: 0.500
Train Loss: 1.203, Train Accuracy: 0.400
Train Loss: 1.832, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.500
Round 9
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.700
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.364, Train Accuracy: 0.600
Train Loss: 1.264, Train Accuracy: 0.625
Train Loss: 1.335, Train Accuracy: 0.800
Train Loss: 1.424, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.200
Train Loss: 1.654, Train Accuracy: 0.750
Train Loss: 1.212, Train Accuracy: 0.300
Round 10
Train Loss: 1.333, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.600
Train Loss: 1.027, Train Accuracy: 0.400
Train Loss: 1.317, Train Accuracy: 0.600
Train Loss: 1.251, Train Accuracy: 0.625
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.501, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.600
Train Loss: 1.743, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.400
Round 11
Train Loss: 1.258, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.408, Train Accuracy: 0.600
Train Loss: 1.255, Train Accuracy: 0.625
Train Loss: 1.347, Train Accuracy: 0.800
Train Loss: 1.417, Train Accuracy: 0.500
Train Loss: 1.119, Train Accuracy: 0.600
Train Loss: 1.787, Train Accuracy: 0.750
Train Loss: 1.221, Train Accuracy: 0.500
Round 12
Train Loss: 1.389, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.400
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.284, Train Accuracy: 0.600
Train Loss: 1.254, Train Accuracy: 0.625
Train Loss: 1.333, Train Accuracy: 0.800
Train Loss: 1.444, Train Accuracy: 0.250
Train Loss: 1.157, Train Accuracy: 0.200
Train Loss: 1.876, Train Accuracy: 0.750
Train Loss: 1.189, Train Accuracy: 0.700
Round 13
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 1.062, Train Accuracy: 0.600
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.449, Train Accuracy: 0.800
Train Loss: 1.261, Train Accuracy: 0.625
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.439, Train Accuracy: 0.500
Train Loss: 1.200, Train Accuracy: 0.400
Train Loss: 1.879, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.600
Round 14
Train Loss: 1.269, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.600
Train Loss: 1.009, Train Accuracy: 0.600
Train Loss: 1.296, Train Accuracy: 0.600
Train Loss: 1.244, Train Accuracy: 0.625
Train Loss: 1.324, Train Accuracy: 0.800
Train Loss: 1.520, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.400
Train Loss: 1.742, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.500
Round 15
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.600
Train Loss: 1.016, Train Accuracy: 0.200
Train Loss: 1.260, Train Accuracy: 0.600
Train Loss: 1.268, Train Accuracy: 0.750
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.467, Train Accuracy: 0.500
Train Loss: 1.166, Train Accuracy: 0.400
Train Loss: 1.747, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.400
Round 16
Train Loss: 1.314, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.600
Train Loss: 1.015, Train Accuracy: 0.400
Train Loss: 1.374, Train Accuracy: 0.600
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.411, Train Accuracy: 0.800
Train Loss: 1.575, Train Accuracy: 0.750
Train Loss: 1.105, Train Accuracy: 0.400
Train Loss: 1.741, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.300
Round 17
Train Loss: 1.313, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.700
Train Loss: 1.014, Train Accuracy: 0.200
Train Loss: 1.372, Train Accuracy: 0.600
Train Loss: 1.229, Train Accuracy: 0.750
Train Loss: 1.356, Train Accuracy: 0.800
Train Loss: 1.497, Train Accuracy: 0.250
Train Loss: 1.175, Train Accuracy: 0.600
Train Loss: 1.908, Train Accuracy: 0.750
Train Loss: 1.128, Train Accuracy: 0.400
Round 18
Train Loss: 1.417, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.600
Train Loss: 1.002, Train Accuracy: 0.400
Train Loss: 1.394, Train Accuracy: 0.600
Train Loss: 1.193, Train Accuracy: 0.750
Train Loss: 1.378, Train Accuracy: 0.800
Train Loss: 1.539, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.400
Train Loss: 1.693, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.300
Round 19
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 0.991, Train Accuracy: 0.400
Train Loss: 1.417, Train Accuracy: 0.800
Train Loss: 1.198, Train Accuracy: 0.750
Train Loss: 1.390, Train Accuracy: 0.800
Train Loss: 1.493, Train Accuracy: 1.000
Train Loss: 1.108, Train Accuracy: 0.400
Train Loss: 1.971, Train Accuracy: 1.000
Train Loss: 1.166, Train Accuracy: 0.500
Round 20
Train Loss: 1.370, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.600
Train Loss: 0.989, Train Accuracy: 0.400
Train Loss: 1.324, Train Accuracy: 0.600
Train Loss: 1.184, Train Accuracy: 0.625
Train Loss: 1.314, Train Accuracy: 0.800
Train Loss: 1.522, Train Accuracy: 1.000
Train Loss: 1.195, Train Accuracy: 0.400
Train Loss: 1.858, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.600
Round 21
Train Loss: 1.354, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.600
Train Loss: 0.981, Train Accuracy: 0.600
Train Loss: 1.382, Train Accuracy: 0.800
Train Loss: 1.203, Train Accuracy: 0.625
Train Loss: 1.319, Train Accuracy: 0.800
Train Loss: 1.538, Train Accuracy: 0.750
Train Loss: 1.060, Train Accuracy: 0.400
Train Loss: 1.755, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.600
Round 22
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.408, Train Accuracy: 0.800
Train Loss: 1.200, Train Accuracy: 0.750
Train Loss: 1.365, Train Accuracy: 0.800
Train Loss: 1.504, Train Accuracy: 1.000
Train Loss: 1.345, Train Accuracy: 0.800
Train Loss: 1.873, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.400
Round 23
Train Loss: 1.298, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.500
Train Loss: 0.976, Train Accuracy: 0.800
Train Loss: 1.346, Train Accuracy: 0.600
Train Loss: 1.184, Train Accuracy: 0.875
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.535, Train Accuracy: 0.750
Train Loss: 1.208, Train Accuracy: 0.600
Train Loss: 1.986, Train Accuracy: 0.750
Train Loss: 1.125, Train Accuracy: 0.400
Round 24
Train Loss: 1.395, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.700
Train Loss: 1.000, Train Accuracy: 0.600
Train Loss: 1.382, Train Accuracy: 0.600
Train Loss: 1.139, Train Accuracy: 0.625
Train Loss: 1.362, Train Accuracy: 0.800
Train Loss: 1.539, Train Accuracy: 0.500
Train Loss: 1.097, Train Accuracy: 0.600
Train Loss: 2.077, Train Accuracy: 0.750
Train Loss: 1.101, Train Accuracy: 0.500
Round 25
Train Loss: 1.279, Train Accuracy: 0.750
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 0.967, Train Accuracy: 0.600
Train Loss: 1.364, Train Accuracy: 1.000
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.261, Train Accuracy: 0.800
Train Loss: 1.593, Train Accuracy: 0.750
Train Loss: 1.139, Train Accuracy: 0.800
Train Loss: 1.802, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.700
Round 26
Train Loss: 1.359, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.700
Train Loss: 0.972, Train Accuracy: 0.400
Train Loss: 1.308, Train Accuracy: 0.600
Train Loss: 1.165, Train Accuracy: 0.750
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.481, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.600
Train Loss: 2.006, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.700
Round 27
Train Loss: 1.464, Train Accuracy: 0.750
Train Loss: 1.033, Train Accuracy: 0.500
Train Loss: 0.974, Train Accuracy: 0.600
Train Loss: 1.353, Train Accuracy: 0.800
Train Loss: 1.144, Train Accuracy: 0.625
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.400, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.600
Train Loss: 1.875, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Round 28
Train Loss: 1.296, Train Accuracy: 0.750
Train Loss: 1.014, Train Accuracy: 0.700
Train Loss: 0.953, Train Accuracy: 0.600
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.165, Train Accuracy: 0.750
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.607, Train Accuracy: 0.750
Train Loss: 1.094, Train Accuracy: 0.800
Train Loss: 1.687, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.500
Round 29
Train Loss: 1.353, Train Accuracy: 0.750
Train Loss: 1.009, Train Accuracy: 0.600
Train Loss: 0.942, Train Accuracy: 0.200
Train Loss: 1.244, Train Accuracy: 0.600
Train Loss: 1.207, Train Accuracy: 0.750
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.488, Train Accuracy: 0.500
Train Loss: 1.073, Train Accuracy: 0.600
Train Loss: 1.672, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.500
Round 30
Train Loss: 1.280, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.600
Train Loss: 0.940, Train Accuracy: 0.400
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.188, Train Accuracy: 0.625
Train Loss: 1.314, Train Accuracy: 0.800
Train Loss: 1.478, Train Accuracy: 1.000
Train Loss: 1.077, Train Accuracy: 0.600
Train Loss: 1.836, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.600
Round 31
Train Loss: 1.241, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.600
Train Loss: 0.933, Train Accuracy: 0.600
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.171, Train Accuracy: 0.750
Train Loss: 1.264, Train Accuracy: 0.800
Train Loss: 1.528, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.600
Train Loss: 2.092, Train Accuracy: 1.000
Train Loss: 1.139, Train Accuracy: 0.300
Round 32
Train Loss: 1.267, Train Accuracy: 0.750
Train Loss: 0.987, Train Accuracy: 0.600
Train Loss: 0.934, Train Accuracy: 0.600
Train Loss: 1.348, Train Accuracy: 1.000
Train Loss: 1.177, Train Accuracy: 0.750
Train Loss: 1.318, Train Accuracy: 0.800
Train Loss: 1.467, Train Accuracy: 1.000
Train Loss: 1.111, Train Accuracy: 0.600
Train Loss: 1.954, Train Accuracy: 0.750
Train Loss: 1.211, Train Accuracy: 0.500
Round 33
Train Loss: 1.179, Train Accuracy: 0.750
Train Loss: 0.996, Train Accuracy: 0.600
Train Loss: 0.953, Train Accuracy: 0.600
Train Loss: 1.250, Train Accuracy: 0.800
Train Loss: 1.177, Train Accuracy: 0.875
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.511, Train Accuracy: 1.000
Train Loss: 1.068, Train Accuracy: 0.600
Train Loss: 2.041, Train Accuracy: 1.000
Train Loss: 1.026, Train Accuracy: 0.400
Round 34
Train Loss: 1.294, Train Accuracy: 0.750
Train Loss: 0.988, Train Accuracy: 0.400
Train Loss: 0.930, Train Accuracy: 0.400
Train Loss: 1.440, Train Accuracy: 0.800
Train Loss: 1.130, Train Accuracy: 0.625
Train Loss: 1.353, Train Accuracy: 0.800
Train Loss: 1.478, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.400
Train Loss: 1.879, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.500
Round 35
Train Loss: 1.322, Train Accuracy: 0.750
Train Loss: 0.985, Train Accuracy: 0.800
Train Loss: 0.934, Train Accuracy: 0.400
Train Loss: 1.539, Train Accuracy: 1.000
Train Loss: 1.158, Train Accuracy: 0.875
Train Loss: 1.240, Train Accuracy: 0.800
Train Loss: 1.495, Train Accuracy: 1.000
Train Loss: 1.106, Train Accuracy: 0.400
Train Loss: 2.027, Train Accuracy: 1.000
Train Loss: 1.035, Train Accuracy: 0.500
Round 36
Train Loss: 1.228, Train Accuracy: 0.750
Train Loss: 0.970, Train Accuracy: 0.600
Train Loss: 0.912, Train Accuracy: 0.800
Train Loss: 1.288, Train Accuracy: 1.000
Train Loss: 1.107, Train Accuracy: 0.750
Train Loss: 1.310, Train Accuracy: 1.000
Train Loss: 1.448, Train Accuracy: 1.000
Train Loss: 1.163, Train Accuracy: 0.800
Train Loss: 2.090, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.600
Round 37
Train Loss: 1.357, Train Accuracy: 0.750
Train Loss: 0.979, Train Accuracy: 0.700
Train Loss: 0.901, Train Accuracy: 0.800
Train Loss: 1.477, Train Accuracy: 0.800
Train Loss: 1.135, Train Accuracy: 0.500
Train Loss: 1.421, Train Accuracy: 0.800
Train Loss: 1.341, Train Accuracy: 0.750
Train Loss: 0.993, Train Accuracy: 0.800
Train Loss: 1.996, Train Accuracy: 0.750
Train Loss: 1.115, Train Accuracy: 0.500
Round 38
Train Loss: 1.309, Train Accuracy: 0.750
Train Loss: 0.960, Train Accuracy: 0.600
Train Loss: 0.892, Train Accuracy: 0.400
Train Loss: 1.343, Train Accuracy: 1.000
Train Loss: 1.106, Train Accuracy: 0.875
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.523, Train Accuracy: 0.500
Train Loss: 1.084, Train Accuracy: 0.600
Train Loss: 2.201, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.800
Round 39
Train Loss: 1.338, Train Accuracy: 0.750
Train Loss: 0.968, Train Accuracy: 0.600
Train Loss: 0.887, Train Accuracy: 0.200
Train Loss: 1.538, Train Accuracy: 0.600
Train Loss: 1.106, Train Accuracy: 0.750
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.543, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.800
Train Loss: 1.686, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.700
Round 40
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 0.962, Train Accuracy: 0.600
Train Loss: 0.887, Train Accuracy: 0.600
Train Loss: 1.391, Train Accuracy: 1.000
Train Loss: 1.187, Train Accuracy: 0.625
Train Loss: 1.209, Train Accuracy: 0.800
Train Loss: 1.530, Train Accuracy: 1.000
Train Loss: 1.057, Train Accuracy: 0.800
Train Loss: 2.347, Train Accuracy: 1.000
Train Loss: 1.096, Train Accuracy: 0.700
Round 41
Train Loss: 1.384, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.600
Train Loss: 0.879, Train Accuracy: 0.800
Train Loss: 1.325, Train Accuracy: 0.600
Train Loss: 1.129, Train Accuracy: 0.250
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.542, Train Accuracy: 1.000
Train Loss: 0.986, Train Accuracy: 0.600
Train Loss: 2.211, Train Accuracy: 0.750
Train Loss: 0.976, Train Accuracy: 0.800
Round 42
Train Loss: 1.262, Train Accuracy: 0.750
Train Loss: 0.940, Train Accuracy: 0.600
Train Loss: 0.917, Train Accuracy: 0.400
Train Loss: 1.333, Train Accuracy: 1.000
Train Loss: 1.172, Train Accuracy: 0.500
Train Loss: 1.322, Train Accuracy: 0.800
Train Loss: 1.481, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.600
Train Loss: 1.875, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.700
Round 43
Train Loss: 1.193, Train Accuracy: 0.750
Train Loss: 0.969, Train Accuracy: 0.400
Train Loss: 0.927, Train Accuracy: 0.800
Train Loss: 1.522, Train Accuracy: 0.800
Train Loss: 1.155, Train Accuracy: 0.625
Train Loss: 1.314, Train Accuracy: 0.800
Train Loss: 1.614, Train Accuracy: 1.000
Train Loss: 1.089, Train Accuracy: 0.600
Train Loss: 1.685, Train Accuracy: 0.750
Train Loss: 1.108, Train Accuracy: 0.600
Round 44
Train Loss: 1.355, Train Accuracy: 0.750
Train Loss: 0.926, Train Accuracy: 0.700
Train Loss: 0.903, Train Accuracy: 0.800
Train Loss: 1.430, Train Accuracy: 0.800
Train Loss: 1.153, Train Accuracy: 0.750
Train Loss: 1.229, Train Accuracy: 0.800
Train Loss: 1.409, Train Accuracy: 0.500
Train Loss: 1.172, Train Accuracy: 0.600
Train Loss: 2.271, Train Accuracy: 1.000
Train Loss: 1.268, Train Accuracy: 0.600
Round 45
Train Loss: 1.205, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.700
Train Loss: 0.885, Train Accuracy: 1.000
Train Loss: 1.128, Train Accuracy: 0.800
Train Loss: 1.098, Train Accuracy: 0.500
Train Loss: 1.249, Train Accuracy: 0.800
Train Loss: 1.616, Train Accuracy: 0.750
Train Loss: 0.960, Train Accuracy: 0.800
Train Loss: 2.085, Train Accuracy: 1.000
Train Loss: 0.991, Train Accuracy: 0.500
Round 46
Train Loss: 1.545, Train Accuracy: 0.750
Train Loss: 1.012, Train Accuracy: 0.700
Train Loss: 0.932, Train Accuracy: 0.600
Train Loss: 1.191, Train Accuracy: 1.000
Train Loss: 1.124, Train Accuracy: 0.500
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.416, Train Accuracy: 1.000
Train Loss: 1.111, Train Accuracy: 1.000
Train Loss: 2.030, Train Accuracy: 0.750
Train Loss: 0.937, Train Accuracy: 0.600
Round 47
Train Loss: 1.544, Train Accuracy: 0.750
Train Loss: 0.945, Train Accuracy: 0.600
Train Loss: 0.999, Train Accuracy: 0.800
Train Loss: 1.316, Train Accuracy: 1.000
Train Loss: 1.071, Train Accuracy: 0.375
Train Loss: 1.244, Train Accuracy: 0.800
Train Loss: 1.537, Train Accuracy: 1.000
Train Loss: 1.053, Train Accuracy: 0.600
Train Loss: 1.740, Train Accuracy: 0.500
Train Loss: 1.363, Train Accuracy: 0.600
Round 48
Train Loss: 1.156, Train Accuracy: 0.750
Train Loss: 0.978, Train Accuracy: 0.400
Train Loss: 0.842, Train Accuracy: 0.800
Train Loss: 1.154, Train Accuracy: 0.800
Train Loss: 1.209, Train Accuracy: 0.250
Train Loss: 1.174, Train Accuracy: 0.800
Train Loss: 1.558, Train Accuracy: 1.000

(FLClient pid=4055765) 2025-04-29 17:42:53,823 - INFO - Epoch   0| Train Loss: 1.088| Train Accuracy: 0.750 [repeated 208x across cluster]
(FLClient pid=4055754) 2025-04-29 17:42:41,921 - INFO - Epoch   2| Validation Loss: 0.736, Validation Accuracy: 0.656 [repeated 69x across cluster]
(FLClient pid=4055765) 2025-04-29 17:42:59,205 - INFO - Epoch   2| Train Loss: 0.775| Train Accuracy: 0.750 [repeated 152x across cluster]
(FLClient pid=4055765) 2025-04-29 17:42:59,214 - INFO - Epoch   2| Validation Loss: 1.298, Validation Accuracy: 0.295 [repeated 51x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:04,677 - INFO - Epoch   2| Train Loss: 0.645| Train Accuracy: 0.750 [repeated 240x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:04,684 - INFO - Epoch   2| Validation Loss: 1.282, Validation Accuracy: 0.295 [repeated 80x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:09,717 - INFO - Epoch   2| Train Loss: 0.434| Train Accuracy: 0.750 [repeated 210x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:09,724 - INFO - Epoch   2| Validation Loss: 1.366, Validation Accuracy: 0.295 [repeated 70x across cluster]
(FLClient pid=4055752) 2025-04-29 17:43:14,803 - INFO - Epoch   0| Train Loss: 1.024| Train Accuracy: 0.600 [repeated 208x across cluster]
(FLClient pid=4055763) 2025-04-29 17:43:14,172 - INFO - Epoch   2| Validation Loss: 1.119, Validation Accuracy: 0.500 [repeated 69x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:20,094 - INFO - Epoch   2| Train Loss: 0.481| Train Accuracy: 0.750 [repeated 212x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:20,103 - INFO - Epoch   2| Validation Loss: 1.344, Validation Accuracy: 0.295 [repeated 71x across cluster]
(FLClient pid=4055762) 2025-04-29 17:43:25,664 - INFO - Epoch   2| Train Loss: 0.469| Train Accuracy: 0.750 [repeated 240x across cluster]
(FLClient pid=4055762) 2025-04-29 17:43:25,669 - INFO - Epoch   2| Validation Loss: 1.993, Validation Accuracy: 0.233 [repeated 80x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:30,779 - INFO - Epoch   2| Train Loss: 0.418| Train Accuracy: 0.750 [repeated 210x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:30,788 - INFO - Epoch   2| Validation Loss: 1.141, Validation Accuracy: 0.295 [repeated 70x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:36,241 - INFO - Epoch   2| Train Loss: 0.472| Train Accuracy: 0.750 [repeated 240x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:36,249 - INFO - Epoch   2| Validation Loss: 1.162, Validation Accuracy: 0.295 [repeated 80x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:41,271 - INFO - Epoch   0| Train Loss: 1.028| Train Accuracy: 0.250 [repeated 208x across cluster]
(FLClient pid=4055763) 2025-04-29 17:43:40,527 - INFO - Epoch   2| Validation Loss: 0.841, Validation Accuracy: 0.500 [repeated 69x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:46,302 - INFO - Epoch   2| Train Loss: 0.481| Train Accuracy: 0.750 [repeated 212x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:46,309 - INFO - Epoch   2| Validation Loss: 1.056, Validation Accuracy: 0.295 [repeated 71x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:51,865 - INFO - Epoch   2| Train Loss: 0.317| Train Accuracy: 0.750 [repeated 240x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:51,873 - INFO - Epoch   2| Validation Loss: 0.968, Validation Accuracy: 0.364 [repeated 80x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:57,072 - INFO - Epoch   2| Train Loss: 0.274| Train Accuracy: 1.000 [repeated 210x across cluster]
(FLClient pid=4055765) 2025-04-29 17:43:57,079 - INFO - Epoch   2| Validation Loss: 1.367, Validation Accuracy: 0.295 [repeated 70x across cluster]
(FLClient pid=4055765) 2025-04-29 17:44:02,131 - INFO - Epoch   2| Train Loss: 0.342| Train Accuracy: 0.750 [repeated 218x across cluster]
(FLClient pid=4055765) 2025-04-29 17:44:02,139 - INFO - Epoch   2| Validation Loss: 0.882, Validation Accuracy: 0.636 [repeated 70x across cluster]

Training done
Round 1
Train Loss: 1.249, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.048, Train Accuracy: 0.400
Train Loss: 1.196, Train Accuracy: 0.600
Train Loss: 1.190, Train Accuracy: 0.625
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.289, Train Accuracy: 0.500
Train Loss: 1.128, Train Accuracy: 0.600
Train Loss: 1.324, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.400
Round 2
Train Loss: 1.295, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.047, Train Accuracy: 0.400
Train Loss: 1.232, Train Accuracy: 0.600
Train Loss: 1.217, Train Accuracy: 0.625
Train Loss: 1.268, Train Accuracy: 0.800
Train Loss: 1.329, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.600
Train Loss: 1.449, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.500
Round 3
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.045, Train Accuracy: 0.400
Train Loss: 1.277, Train Accuracy: 0.600
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.365, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 0.800
Train Loss: 1.514, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.400
Round 4
Train Loss: 1.263, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.600
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.270, Train Accuracy: 0.600
Train Loss: 1.221, Train Accuracy: 0.625
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.429, Train Accuracy: 0.500
Train Loss: 1.151, Train Accuracy: 0.600
Train Loss: 1.610, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.400
Round 5
Train Loss: 1.271, Train Accuracy: 0.750
Train Loss: 1.088, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 1.351, Train Accuracy: 0.600
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.276, Train Accuracy: 0.800
Train Loss: 1.475, Train Accuracy: 0.750
Train Loss: 1.174, Train Accuracy: 0.600
Train Loss: 1.606, Train Accuracy: 0.750
Train Loss: 1.152, Train Accuracy: 0.300
Round 6
Train Loss: 1.298, Train Accuracy: 0.750
Train Loss: 1.096, Train Accuracy: 0.500
Train Loss: 1.032, Train Accuracy: 0.400
Train Loss: 1.333, Train Accuracy: 0.600
Train Loss: 1.239, Train Accuracy: 0.625
Train Loss: 1.282, Train Accuracy: 0.800
Train Loss: 1.408, Train Accuracy: 0.500
Train Loss: 1.132, Train Accuracy: 0.200
Train Loss: 1.691, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.400
Round 7
Train Loss: 1.330, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.345, Train Accuracy: 0.600
Train Loss: 1.244, Train Accuracy: 0.625
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.473, Train Accuracy: 0.500
Train Loss: 1.139, Train Accuracy: 0.400
Train Loss: 1.694, Train Accuracy: 0.750
Train Loss: 1.229, Train Accuracy: 0.400
Round 8
Train Loss: 1.290, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.027, Train Accuracy: 0.400
Train Loss: 1.397, Train Accuracy: 0.600
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.432, Train Accuracy: 0.500
Train Loss: 1.136, Train Accuracy: 0.600
Train Loss: 1.640, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.500
Round 9
Train Loss: 1.317, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.700
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.330, Train Accuracy: 0.600
Train Loss: 1.247, Train Accuracy: 0.625
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.431, Train Accuracy: 1.000
Train Loss: 1.157, Train Accuracy: 0.400
Train Loss: 1.653, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.500
Round 10
Train Loss: 1.433, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.023, Train Accuracy: 0.400
Train Loss: 1.375, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.468, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.200
Train Loss: 1.780, Train Accuracy: 0.750
Train Loss: 1.217, Train Accuracy: 0.600
Round 11
Train Loss: 1.264, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.600
Train Loss: 1.018, Train Accuracy: 0.600
Train Loss: 1.372, Train Accuracy: 0.600
Train Loss: 1.258, Train Accuracy: 0.625
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.470, Train Accuracy: 1.000
Train Loss: 1.123, Train Accuracy: 0.400
Train Loss: 1.744, Train Accuracy: 0.750
Train Loss: 1.189, Train Accuracy: 0.500
Round 12
Train Loss: 1.288, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.399, Train Accuracy: 0.600
Train Loss: 1.218, Train Accuracy: 0.625
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.509, Train Accuracy: 0.750
Train Loss: 1.225, Train Accuracy: 0.400
Train Loss: 1.769, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.500
Round 13
Train Loss: 1.244, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.400
Train Loss: 1.020, Train Accuracy: 0.400
Train Loss: 1.324, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.352, Train Accuracy: 0.800
Train Loss: 1.474, Train Accuracy: 0.750
Train Loss: 1.155, Train Accuracy: 0.400
Train Loss: 1.821, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.600
Round 14
Train Loss: 1.282, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.500
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 1.399, Train Accuracy: 1.000
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.403, Train Accuracy: 0.800
Train Loss: 1.526, Train Accuracy: 0.500
Train Loss: 1.165, Train Accuracy: 0.600
Train Loss: 1.752, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.500
Round 15
Train Loss: 1.360, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.500
Train Loss: 1.017, Train Accuracy: 0.400
Train Loss: 1.418, Train Accuracy: 0.600
Train Loss: 1.253, Train Accuracy: 0.625
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.493, Train Accuracy: 0.750
Train Loss: 1.116, Train Accuracy: 0.200
Train Loss: 1.848, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.500
Round 16
Train Loss: 1.406, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.600
Train Loss: 1.008, Train Accuracy: 0.400
Train Loss: 1.328, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.315, Train Accuracy: 0.800
Train Loss: 1.507, Train Accuracy: 0.500
Train Loss: 1.109, Train Accuracy: 0.400
Train Loss: 1.740, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.700
Round 17
Train Loss: 1.369, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.400
Train Loss: 1.003, Train Accuracy: 0.400
Train Loss: 1.367, Train Accuracy: 0.600
Train Loss: 1.182, Train Accuracy: 0.750
Train Loss: 1.365, Train Accuracy: 0.800
Train Loss: 1.427, Train Accuracy: 0.500
Train Loss: 1.121, Train Accuracy: 0.200
Train Loss: 1.863, Train Accuracy: 0.750
Train Loss: 1.158, Train Accuracy: 0.400
Round 18
Train Loss: 1.233, Train Accuracy: 0.750
Train Loss: 1.046, Train Accuracy: 0.500
Train Loss: 1.007, Train Accuracy: 0.800
Train Loss: 1.352, Train Accuracy: 0.800
Train Loss: 1.206, Train Accuracy: 0.625
Train Loss: 1.312, Train Accuracy: 0.800
Train Loss: 1.469, Train Accuracy: 0.500
Train Loss: 1.209, Train Accuracy: 0.600
Train Loss: 1.847, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.500
Round 19
Train Loss: 1.369, Train Accuracy: 0.500
Train Loss: 1.051, Train Accuracy: 0.500
Train Loss: 1.000, Train Accuracy: 0.600
Train Loss: 1.304, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.288, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.600
Train Loss: 1.772, Train Accuracy: 0.750
Train Loss: 1.111, Train Accuracy: 0.600
Round 20
Train Loss: 1.325, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.600
Train Loss: 0.993, Train Accuracy: 0.600
Train Loss: 1.432, Train Accuracy: 0.600
Train Loss: 1.233, Train Accuracy: 0.750
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.462, Train Accuracy: 0.500
Train Loss: 1.135, Train Accuracy: 0.600
Train Loss: 1.824, Train Accuracy: 0.750
Train Loss: 1.156, Train Accuracy: 0.800
Round 21
Train Loss: 1.366, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 1.305, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.875
Train Loss: 1.390, Train Accuracy: 0.800
Train Loss: 1.593, Train Accuracy: 1.000
Train Loss: 1.115, Train Accuracy: 0.400
Train Loss: 1.846, Train Accuracy: 0.750
Train Loss: 1.131, Train Accuracy: 0.700
Round 22
Train Loss: 1.339, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.500
Train Loss: 0.988, Train Accuracy: 0.600
Train Loss: 1.356, Train Accuracy: 0.600
Train Loss: 1.199, Train Accuracy: 0.750
Train Loss: 1.451, Train Accuracy: 0.800
Train Loss: 1.577, Train Accuracy: 1.000
Train Loss: 1.181, Train Accuracy: 0.400
Train Loss: 2.009, Train Accuracy: 0.750
Train Loss: 1.107, Train Accuracy: 0.500
Round 23
Train Loss: 1.249, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.600
Train Loss: 0.974, Train Accuracy: 0.400
Train Loss: 1.344, Train Accuracy: 0.600
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.655, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.400
Train Loss: 1.794, Train Accuracy: 0.750
Train Loss: 1.220, Train Accuracy: 0.800
Round 24
Train Loss: 1.415, Train Accuracy: 0.750
Train Loss: 1.019, Train Accuracy: 0.600
Train Loss: 0.986, Train Accuracy: 0.800
Train Loss: 1.356, Train Accuracy: 0.600
Train Loss: 1.265, Train Accuracy: 0.750
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.563, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.400
Train Loss: 1.834, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.500
Round 25
Train Loss: 1.452, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 0.972, Train Accuracy: 0.600
Train Loss: 1.273, Train Accuracy: 0.600
Train Loss: 1.197, Train Accuracy: 0.875
Train Loss: 1.381, Train Accuracy: 0.800
Train Loss: 1.539, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.600
Train Loss: 1.739, Train Accuracy: 0.750
Train Loss: 1.116, Train Accuracy: 0.700
Round 26
Train Loss: 1.198, Train Accuracy: 0.750
Train Loss: 1.013, Train Accuracy: 0.600
Train Loss: 0.956, Train Accuracy: 0.600
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.178, Train Accuracy: 0.750
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.497, Train Accuracy: 0.750
Train Loss: 1.115, Train Accuracy: 0.200
Train Loss: 1.675, Train Accuracy: 0.750
Train Loss: 1.105, Train Accuracy: 0.400
Round 27
Train Loss: 1.463, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.600
Train Loss: 0.964, Train Accuracy: 0.400
Train Loss: 1.488, Train Accuracy: 0.600
Train Loss: 1.154, Train Accuracy: 0.625
Train Loss: 1.357, Train Accuracy: 0.800
Train Loss: 1.554, Train Accuracy: 0.500
Train Loss: 1.059, Train Accuracy: 0.600
Train Loss: 1.970, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.300
Round 28
Train Loss: 1.235, Train Accuracy: 0.750
Train Loss: 0.994, Train Accuracy: 0.700
Train Loss: 0.958, Train Accuracy: 0.800
Train Loss: 1.441, Train Accuracy: 1.000
Train Loss: 1.187, Train Accuracy: 0.750
Train Loss: 1.304, Train Accuracy: 0.800
Train Loss: 1.486, Train Accuracy: 1.000
Train Loss: 1.111, Train Accuracy: 0.400
Train Loss: 1.894, Train Accuracy: 0.750
Train Loss: 1.107, Train Accuracy: 0.600
Round 29
Train Loss: 1.246, Train Accuracy: 0.750
Train Loss: 1.004, Train Accuracy: 0.600
Train Loss: 0.951, Train Accuracy: 0.400
Train Loss: 1.489, Train Accuracy: 1.000
Train Loss: 1.173, Train Accuracy: 0.625
Train Loss: 1.359, Train Accuracy: 0.800
Train Loss: 1.519, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.600
Train Loss: 1.910, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.300
Round 30
Train Loss: 1.159, Train Accuracy: 0.750
Train Loss: 1.011, Train Accuracy: 0.600
Train Loss: 0.955, Train Accuracy: 0.400
Train Loss: 1.323, Train Accuracy: 0.600
Train Loss: 1.157, Train Accuracy: 0.750
Train Loss: 1.256, Train Accuracy: 0.800
Train Loss: 1.590, Train Accuracy: 0.750
Train Loss: 1.127, Train Accuracy: 0.600
Train Loss: 2.096, Train Accuracy: 0.750
Train Loss: 1.107, Train Accuracy: 0.500
Round 31
Train Loss: 1.300, Train Accuracy: 0.750
Train Loss: 1.020, Train Accuracy: 0.700
Train Loss: 0.953, Train Accuracy: 0.600
Train Loss: 1.345, Train Accuracy: 1.000
Train Loss: 1.167, Train Accuracy: 0.875
Train Loss: 1.252, Train Accuracy: 0.800
Train Loss: 1.515, Train Accuracy: 0.500
Train Loss: 1.025, Train Accuracy: 0.600
Train Loss: 2.130, Train Accuracy: 0.750
Train Loss: 1.102, Train Accuracy: 0.500
Round 32
Train Loss: 1.239, Train Accuracy: 0.750
Train Loss: 1.004, Train Accuracy: 0.600
Train Loss: 0.969, Train Accuracy: 0.800
Train Loss: 1.410, Train Accuracy: 1.000
Train Loss: 1.163, Train Accuracy: 0.750
Train Loss: 1.217, Train Accuracy: 0.800
Train Loss: 1.613, Train Accuracy: 0.500
Train Loss: 1.031, Train Accuracy: 0.800
Train Loss: 1.854, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.700
Round 33
Train Loss: 1.290, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.600
Train Loss: 0.936, Train Accuracy: 0.400
Train Loss: 1.560, Train Accuracy: 0.800
Train Loss: 1.216, Train Accuracy: 0.625
Train Loss: 1.253, Train Accuracy: 0.800
Train Loss: 1.709, Train Accuracy: 0.500
Train Loss: 1.033, Train Accuracy: 0.600
Train Loss: 1.869, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.500
Round 34
Train Loss: 1.206, Train Accuracy: 0.750
Train Loss: 0.976, Train Accuracy: 0.800
Train Loss: 0.934, Train Accuracy: 0.400
Train Loss: 1.438, Train Accuracy: 1.000
Train Loss: 1.118, Train Accuracy: 0.875
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.594, Train Accuracy: 1.000
Train Loss: 1.105, Train Accuracy: 0.200
Train Loss: 1.906, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.600
Round 35
Train Loss: 1.344, Train Accuracy: 0.750
Train Loss: 0.970, Train Accuracy: 0.700
Train Loss: 0.934, Train Accuracy: 0.600
Train Loss: 1.405, Train Accuracy: 1.000
Train Loss: 1.112, Train Accuracy: 0.750
Train Loss: 1.380, Train Accuracy: 1.000
Train Loss: 1.658, Train Accuracy: 1.000
Train Loss: 1.042, Train Accuracy: 0.800
Train Loss: 1.924, Train Accuracy: 1.000
Train Loss: 1.049, Train Accuracy: 0.800
Round 36
Train Loss: 1.109, Train Accuracy: 0.750
Train Loss: 0.979, Train Accuracy: 0.600
Train Loss: 0.911, Train Accuracy: 0.600
Train Loss: 1.320, Train Accuracy: 1.000
Train Loss: 1.211, Train Accuracy: 0.625
Train Loss: 1.237, Train Accuracy: 0.800
Train Loss: 1.593, Train Accuracy: 0.750
Train Loss: 1.126, Train Accuracy: 0.600
Train Loss: 1.864, Train Accuracy: 0.750
Train Loss: 1.203, Train Accuracy: 0.600
Round 37
Train Loss: 1.197, Train Accuracy: 0.750
Train Loss: 0.969, Train Accuracy: 0.600
Train Loss: 0.899, Train Accuracy: 0.600
Train Loss: 1.385, Train Accuracy: 1.000
Train Loss: 1.142, Train Accuracy: 0.500
Train Loss: 1.283, Train Accuracy: 0.800
Train Loss: 1.722, Train Accuracy: 1.000
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 1.986, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.500
Round 38
Train Loss: 1.231, Train Accuracy: 0.750
Train Loss: 0.948, Train Accuracy: 0.700
Train Loss: 0.949, Train Accuracy: 0.600
Train Loss: 1.328, Train Accuracy: 1.000
Train Loss: 1.071, Train Accuracy: 0.250
Train Loss: 1.374, Train Accuracy: 0.800
Train Loss: 1.640, Train Accuracy: 0.250
Train Loss: 1.060, Train Accuracy: 0.600
Train Loss: 1.750, Train Accuracy: 0.750
Train Loss: 1.118, Train Accuracy: 0.700
Round 39
Train Loss: 1.240, Train Accuracy: 0.750
Train Loss: 0.950, Train Accuracy: 0.700
Train Loss: 0.932, Train Accuracy: 0.600
Train Loss: 1.244, Train Accuracy: 0.800
Train Loss: 1.109, Train Accuracy: 0.500
Train Loss: 1.404, Train Accuracy: 1.000
Train Loss: 1.732, Train Accuracy: 1.000
Train Loss: 1.032, Train Accuracy: 0.800
Train Loss: 1.756, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.700
Round 40
Train Loss: 1.080, Train Accuracy: 0.750
Train Loss: 0.947, Train Accuracy: 0.700
Train Loss: 0.908, Train Accuracy: 0.800
Train Loss: 1.582, Train Accuracy: 0.800
Train Loss: 1.107, Train Accuracy: 0.500
Train Loss: 1.249, Train Accuracy: 0.800
Train Loss: 1.568, Train Accuracy: 0.500
Train Loss: 1.085, Train Accuracy: 0.600
Train Loss: 1.961, Train Accuracy: 0.750
Train Loss: 1.319, Train Accuracy: 0.500
Round 41
Train Loss: 1.205, Train Accuracy: 0.750
Train Loss: 0.954, Train Accuracy: 0.400
Train Loss: 0.914, Train Accuracy: 0.600
Train Loss: 1.210, Train Accuracy: 1.000
Train Loss: 1.258, Train Accuracy: 0.875
Train Loss: 1.361, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 1.000
Train Loss: 1.004, Train Accuracy: 0.800
Train Loss: 1.729, Train Accuracy: 1.000
Train Loss: 1.115, Train Accuracy: 0.600
Round 42
Train Loss: 1.227, Train Accuracy: 0.500
Train Loss: 0.928, Train Accuracy: 0.600
Train Loss: 0.947, Train Accuracy: 0.600
Train Loss: 1.478, Train Accuracy: 0.800
Train Loss: 1.278, Train Accuracy: 0.625
Train Loss: 1.152, Train Accuracy: 0.800
Train Loss: 1.398, Train Accuracy: 0.500
Train Loss: 1.005, Train Accuracy: 0.800
Train Loss: 2.233, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.700
Round 43
Train Loss: 1.339, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.600
Train Loss: 0.879, Train Accuracy: 1.000
Train Loss: 1.351, Train Accuracy: 1.000
Train Loss: 1.127, Train Accuracy: 0.875
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.537, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.600
Train Loss: 1.993, Train Accuracy: 0.750
Train Loss: 1.153, Train Accuracy: 0.700
Round 44
Train Loss: 1.364, Train Accuracy: 1.000
Train Loss: 0.918, Train Accuracy: 0.600
Train Loss: 0.912, Train Accuracy: 0.800
Train Loss: 1.302, Train Accuracy: 0.800
Train Loss: 1.145, Train Accuracy: 0.625
Train Loss: 1.193, Train Accuracy: 0.800
Train Loss: 1.912, Train Accuracy: 0.750
Train Loss: 0.979, Train Accuracy: 0.600
Train Loss: 1.816, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.600
Round 45
Train Loss: 1.088, Train Accuracy: 0.750
Train Loss: 0.946, Train Accuracy: 0.500
Train Loss: 0.892, Train Accuracy: 0.600
Train Loss: 1.623, Train Accuracy: 0.800
Train Loss: 1.087, Train Accuracy: 0.625
Train Loss: 1.277, Train Accuracy: 0.800
Train Loss: 1.517, Train Accuracy: 0.750
Train Loss: 0.942, Train Accuracy: 0.600
Train Loss: 2.036, Train Accuracy: 1.000
Train Loss: 1.046, Train Accuracy: 0.600
Round 46
Train Loss: 1.125, Train Accuracy: 0.750
Train Loss: 0.923, Train Accuracy: 0.700
Train Loss: 0.910, Train Accuracy: 0.800
Train Loss: 1.366, Train Accuracy: 1.000
Train Loss: 1.108, Train Accuracy: 0.750
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.473, Train Accuracy: 1.000
Train Loss: 0.945, Train Accuracy: 0.800
Train Loss: 1.869, Train Accuracy: 0.750
Train Loss: 0.937, Train Accuracy: 0.700
Round 47
Train Loss: 1.140, Train Accuracy: 0.750
Train Loss: 0.961, Train Accuracy: 0.700
Train Loss: 0.870, Train Accuracy: 0.800
Train Loss: 1.449, Train Accuracy: 1.000
Train Loss: 1.033, Train Accuracy: 0.875
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.614, Train Accuracy: 0.500
Train Loss: 1.155, Train Accuracy: 0.600
Train Loss: 1.849, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.600
Round 48
Train Loss: 1.376, Train Accuracy: 0.750
Train Loss: 0.981, Train Accuracy: 0.700
Train Loss: 0.839, Train Accuracy: 0.800
Train Loss: 1.459, Train Accuracy: 0.800
Train Loss: 1.204, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.800
Train Loss: 1.615, Train Accuracy: 1.000

(FLClient pid=4055763) 2025-04-29 17:44:06,397 - INFO - Epoch   2| Train Loss: 0.495| Train Accuracy: 0.700 [repeated 199x across cluster]
(FLClient pid=4055763) 2025-04-29 17:44:06,404 - INFO - Epoch   2| Validation Loss: 0.883, Validation Accuracy: 0.578 [repeated 69x across cluster]

Results saved to Central_results44/Pubmed_full_GCN/results_Pubmed_full_GCN.txt

In [15]:
import os
import ast # To safely evaluate string literal as dictionary
import pandas as pd
import logging # Using logging for better error reporting

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def process_results_folder(main_folder_path):
    """
    Processes experiment results stored in subfolders of a main directory.

    Reads .txt files containing dictionary-like strings, parses them,
    and organizes the configuration and summary data into a Pandas DataFrame.

    Args:
        main_folder_path (str): The path to the main results folder
                                (e.g., 'Central_results2').

    Returns:
        pandas.DataFrame: A DataFrame containing the structured results,
                          with each row representing an experiment.
                          Returns an empty DataFrame if the folder is not found
                          or no valid results are processed.
    """
    all_results_data = [] # List to hold data for each valid experiment

    # --- Input Validation ---
    if not os.path.isdir(main_folder_path):
        logging.error(f"Folder not found at '{main_folder_path}'")
        return pd.DataFrame() # Return empty DataFrame

    logging.info(f"Starting processing for folder: '{main_folder_path}'")

    # --- Iterate Through Subfolders ---
    try:
        subfolder_names = os.listdir(main_folder_path)
    except OSError as e:
        logging.error(f"Could not list directory contents for '{main_folder_path}': {e}")
        return pd.DataFrame()

    for item_name in subfolder_names:
        subfolder_path = os.path.join(main_folder_path, item_name)

        # Check if it's actually a directory
        if not os.path.isdir(subfolder_path):
            logging.debug(f"Skipping non-directory item: '{item_name}'")
            continue

        logging.info(f"Processing subfolder: '{item_name}'")

        # --- Find the .txt File ---
        txt_file_path = None
        try:
            files_in_subfolder = os.listdir(subfolder_path)
            for filename in files_in_subfolder:
                if filename.endswith(".txt"):
                    # Assume only one relevant .txt file per subfolder
                    txt_file_path = os.path.join(subfolder_path, filename)
                    logging.debug(f"Found results file: '{filename}'")
                    break # Stop searching in this subfolder once found
            if not txt_file_path:
                 logging.warning(f"No .txt file found in subfolder '{item_name}'. Skipping.")
                 continue
        except OSError as e:
            logging.warning(f"Could not list files in subfolder '{item_name}': {e}. Skipping.")
            continue

        # --- Read and Parse File Content ---
        try:
            with open(txt_file_path, 'r', encoding='utf-8') as f:
                content = f.read()

            # Safely parse the string content into a Python dictionary
            # ast.literal_eval is safer than eval() for untrusted input
            data = ast.literal_eval(content)

            if not isinstance(data, dict):
                 logging.warning(f"Parsed content from '{txt_file_path}' is not a dictionary. Skipping.")
                 continue

        except FileNotFoundError:
            # This might happen in rare race conditions if the file is deleted
            # between listing and opening
            logging.warning(f"File '{txt_file_path}' found initially but could not be opened. Skipping.")
            continue
        except (SyntaxError, ValueError) as e:
            logging.warning(f"Error parsing content in file '{txt_file_path}': {e}. Skipping.")
            continue
        except Exception as e:
            logging.error(f"An unexpected error occurred reading/parsing '{txt_file_path}': {e}. Skipping.")
            continue

        # --- Extract Data ---
        # Use .get() for safer access in case keys are missing
        config = data.get('experiment_config', {})
        summary = data.get('summary', {})

        if not config or not summary:
             logging.warning(f"Missing 'experiment_config' or 'summary' key in '{txt_file_path}'. Skipping file.")
             continue

        # Create a flat dictionary for the DataFrame row
        # Start with configuration parameters
        row_data = config.copy()

        # Add summary results, prefixing keys if needed to avoid clashes (optional)
        # Example: prefix summary keys with 'summary_'
        # summary_prefixed = {f'summary_{k}': v for k, v in summary.items()}
        # row_data.update(summary_prefixed)

        # Or just update directly if keys are distinct
        row_data.update(summary)

        # Add an identifier for the experiment (using subfolder name)
        row_data['experiment_id'] = item_name
        # You could also add the filename if needed:
        # row_data['source_file'] = os.path.basename(txt_file_path)

        # Remove potentially large list/dict columns if not needed directly in the summary table
        # Adjust these based on what you want in the final table
        row_data.pop('global_results', None) # Remove list of all global results per round
        row_data.pop('client_results', None) # Remove list of all client results per round
        row_data.pop('rounds', None)         # Remove the detailed rounds data

        all_results_data.append(row_data)
        logging.debug(f"Successfully processed data for experiment '{item_name}'")

    # --- Create DataFrame ---
    if not all_results_data:
        logging.warning("No valid experiment data found to create a DataFrame.")
        return pd.DataFrame()

    try:
        results_df = pd.DataFrame(all_results_data)
        logging.info(f"Successfully created DataFrame with {len(results_df)} rows.")

        # Optional: Reorder columns for better readability
        id_col = ['experiment_id']
        config_cols = list(data.get('experiment_config', {}).keys())
        summary_cols = list(k for k in data.get('summary', {}).keys() if k not in ['global_results', 'client_results']) # Get summary keys added
        # Filter out columns that might not exist in all rows if parsing failed partially
        existing_cols = [col for col in id_col + config_cols + summary_cols if col in results_df.columns]
        results_df = results_df[existing_cols]

        # Optional: Set experiment_id as the DataFrame index
        # results_df.set_index('experiment_id', inplace=True)

    except Exception as e:
        logging.error(f"Failed to create DataFrame from processed data: {e}")
        return pd.DataFrame()


    return results_df

# --- Example Usage ---
# Note: Replace 'Central_results2' with the actual path to your folder.
# If running this script, make sure the folder exists relative to the script
# or provide an absolute path.

# Create dummy structure for demonstration if needed
def create_dummy_structure(base_dir="Central_results2_demo"):
    if not os.path.exists(base_dir):
        os.makedirs(base_dir)
    # Sample data similar to the user's example
    experiments_data = {
        "Pubmed_adjacency_GCN": {'experiment_config': {'device': 'cuda', 'data_loading_option': 'adjacency', 'model_type': 'GCN', 'dataset': 'Pubmed', 'num_clients': 10, 'beta': 1, 'hop': 1, 'fulltraining_flag': False}, 'rounds': [{'round': 1, 'global_result': 0.715, 'client_result': 0.724}, {'round': 2, 'global_result': 0.67, 'client_result': 0.698}], 'summary': {'global_results': [0.715, 0.67], 'client_results': [0.724, 0.698], 'average_global_result': 0.6925, 'average_client_result': 0.711, 'std_global': 0.0225, 'std_client': 0.013}},
        "Pubmed_diffusion_GCN": {'experiment_config': {'device': 'cuda', 'data_loading_option': 'diffusion', 'model_type': 'GCN', 'dataset': 'Pubmed', 'num_clients': 10, 'beta': 1, 'hop': 2, 'fulltraining_flag': False}, 'rounds': [], 'summary': {'average_global_result': 0.701, 'average_client_result': 0.715, 'std_global': 0.021, 'std_client': 0.012}},
        "Cora_full_SAGE": {'experiment_config': {'device': 'cpu', 'data_loading_option': 'full', 'model_type': 'SAGE', 'dataset': 'Cora', 'num_clients': 1, 'beta': 0, 'hop': 0, 'fulltraining_flag': True}, 'rounds': [], 'summary': {'average_global_result': 0.81, 'average_client_result': 0.81, 'std_global': 0.0, 'std_client': 0.0}},
        "Folder_With_Invalid_Txt": "This is not a dictionary string", # Test invalid content
        "Folder_With_No_Txt": {}, # Test missing txt file
        "Folder_With_Missing_Keys": {'experiment_config': {'device': 'cpu'}, 'summary': {}} # Test missing keys
    }
    logging.info(f"Creating dummy structure in '{base_dir}'...")
    for folder_name, data in experiments_data.items():
        subfolder_path = os.path.join(base_dir, folder_name)
        if not os.path.exists(subfolder_path):
            os.makedirs(subfolder_path)

        if folder_name == "Folder_With_No_Txt":
            # Create an empty file or a file with a different extension
            with open(os.path.join(subfolder_path, "other_file.log"), 'w') as f:
                f.write("Log data")
            continue # Don't create the specific .txt file

        # Create the results text file
        txt_filename = f"results_{folder_name}.txt"
        txt_filepath = os.path.join(subfolder_path, txt_filename)
        try:
            with open(txt_filepath, 'w', encoding='utf-8') as f:
                if isinstance(data, dict):
                    # Convert dict to string representation for the file
                    f.write(str(data))
                else:
                    # Write invalid data directly
                    f.write(data)
        except IOError as e:
            logging.error(f"Failed to write dummy file {txt_filepath}: {e}")
    logging.info("Dummy structure created.")


# --- Main execution block ---
if __name__ == "__main__":
    # Create dummy data for testing
    dummy_folder_path = "Central_results2_demo"
    create_dummy_structure(dummy_folder_path)

    # Process the results folder
    results_dataframe = process_results_folder(dummy_folder_path)

    # Display the results
    if not results_dataframe.empty:
        print("\n--- Processed Results DataFrame ---")
        # Configure pandas display options for better readability
        pd.set_option('display.max_columns', None) # Show all columns
        pd.set_option('display.width', 1000)       # Adjust width
        print(results_dataframe)
    else:
        print("\nNo DataFrame was generated. Check log messages for details.")

    # Clean up dummy structure (optional)
    # import shutil
    # try:
    #     shutil.rmtree(dummy_folder_path)
    #     logging.info(f"Cleaned up dummy directory: '{dummy_folder_path}'")
    # except OSError as e:
    #     logging.error(f"Error removing dummy directory '{dummy_folder_path}': {e}")

2025-04-29 17:44:37,413 - INFO - Creating dummy structure in 'Central_results2_demo'...
2025-04-29 17:44:37,417 - INFO - Dummy structure created.
2025-04-29 17:44:37,420 - INFO - Starting processing for folder: 'Central_results2_demo'
2025-04-29 17:44:37,423 - INFO - Processing subfolder: 'Folder_With_Missing_Keys'
2025-04-29 17:44:37,426 - WARNING - Missing 'experiment_config' or 'summary' key in 'Central_results2_demo/Folder_With_Missing_Keys/results_Folder_With_Missing_Keys.txt'. Skipping file.
2025-04-29 17:44:37,426 - INFO - Processing subfolder: 'Folder_With_No_Txt'
2025-04-29 17:44:37,427 - WARNING - No .txt file found in subfolder 'Folder_With_No_Txt'. Skipping.
2025-04-29 17:44:37,427 - INFO - Processing subfolder: 'Folder_With_Invalid_Txt'
2025-04-29 17:44:37,428 - WARNING - Error parsing content in file 'Central_results2_demo/Folder_With_Invalid_Txt/results_Folder_With_Invalid_Txt.txt': invalid syntax (<unknown>, line 1). Skipping.
2025-04-29 17:44:37,429 - INFO - Processing subfolder: 'Cora_full_SAGE'
2025-04-29 17:44:37,431 - INFO - Processing subfolder: 'Pubmed_adjacency_GCN'
2025-04-29 17:44:37,432 - INFO - Processing subfolder: 'Pubmed_diffusion_GCN'
2025-04-29 17:44:37,435 - INFO - Successfully created DataFrame with 3 rows.

--- Processed Results DataFrame ---
          experiment_id device data_loading_option model_type dataset  num_clients  beta  hop  fulltraining_flag  average_global_result  average_client_result  std_global  std_client
0        Cora_full_SAGE    cpu                full       SAGE    Cora            1     0    0               True                 0.8100                  0.810      0.0000       0.000
1  Pubmed_adjacency_GCN   cuda           adjacency        GCN  Pubmed           10     1    1              False                 0.6925                  0.711      0.0225       0.013
2  Pubmed_diffusion_GCN   cuda           diffusion        GCN  Pubmed           10     1    2              False                 0.7010                  0.715      0.0210       0.012

In [17]:
results_folder = "Central_results44"
df = process_results_folder(results_folder)

2025-04-29 17:44:47,320 - INFO - Starting processing for folder: 'Central_results44'
2025-04-29 17:44:47,321 - INFO - Processing subfolder: 'Pubmed_full_GCN'
2025-04-29 17:44:47,325 - INFO - Successfully created DataFrame with 1 rows.

In [18]:
df

     experiment_id device data_loading_option model_type dataset  num_clients   beta  hop  fulltraining_flag  average_global_result  average_client_result  std_global  std_client
0  Pubmed_full_GCN   cuda                full        GCN  Pubmed           10  10000    1              False                  0.747               0.740617       0.017    0.022248

In [13]:
results_folder2 = "Central_results3"
df2 = process_results_folder(results_folder2)
df2

2025-04-29 17:44:10,741 - ERROR - Folder not found at 'Central_results3'

Empty DataFrame
Columns: []
Index: []

In [14]:
results_folder3 = "Central_results44"
df3 = process_results_folder(results_folder3)
df3

2025-04-29 17:44:10,753 - INFO - Starting processing for folder: 'Central_results44'
2025-04-29 17:44:10,754 - INFO - Processing subfolder: 'Pubmed_full_GCN'
2025-04-29 17:44:10,756 - INFO - Successfully created DataFrame with 1 rows.

     experiment_id device data_loading_option model_type dataset  num_clients   beta  hop  fulltraining_flag  average_global_result  average_client_result  std_global  std_client
0  Pubmed_full_GCN   cuda                full        GCN  Pubmed           10  10000    1              False                  0.747               0.740617       0.017    0.022248