In [1]:
path = "/home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline"

In [2]:
import sys
import os
# Add the project root to Python path
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

In [3]:
import pandas as pd
from src.analysis.process_results import process_results_folder_json_v2
from src.analysis.training_logs_analysis import parse_client_csv, process_fp_logs

In [4]:
results_df = process_results_folder_json_v2(path)

print(results_df.head())

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_183835.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191356.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191625.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_162754.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_181402.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_162517.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_161231.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_155441.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_190745.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_122404.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_133353.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_134201.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_143015.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_142510.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_160958.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_155948.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_181315.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_143754.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_151903.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_163544.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_183954.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_140455.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_181233.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_155208.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_190823.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_151358.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_153419.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_123433.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_134432.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_135718.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_132344.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_190904.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191018.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_142742.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_173301.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_134938.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191510.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_162010.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_144533.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_160725.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_160452.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_152642.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_155714.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_181439.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_134707.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_184031.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_141001.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_144028.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_135212.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_142239.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_152133.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_163029.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_131605.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_133927.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_132617.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_145605.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_120449.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_153651.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_173537.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_160219.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_145838.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_153146.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_142005.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_163306.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191433.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_190940.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_144806.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_162242.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_141506.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_143520.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_150112.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_152408.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_132848.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_181111.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_125547.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_135949.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_183917.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_145038.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_185434.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_185548.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_150345.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_151123.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_145332.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_133653.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_124510.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_161737.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_132111.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_185511.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_144301.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191547.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_152913.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_181150.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_154157.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_140224.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_154430.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_133120.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_154703.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_141736.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_161504.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_130628.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191319.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_184109.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_163818.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_153924.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_131837.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_143248.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_141235.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_183758.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_154936.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_150852.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_140729.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_150619.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_151629.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_135445.json
INFO: Successfully created DataFrame with 126 rows.

  datasets data_loading models num_clients  num_rounds  epochs optimizer  \
0   [Cora]         full  [GCN]         [5]          10       3       SGD
1   [Cora]         full  [GCN]         [5]          10       3       SGD
2   [Cora]         full  [GCN]         [5]          10       3       SGD
3   [Cora]         full  [GCN]        [10]         200       3       SGD
4   [Cora]         full  [GCN]         [5]          10       3       SGD

    decay   beta   lr  ... dataset  model  clients  avg_global avg_client  \
0  0.0005      2  0.5  ...    Cora    GCN        5      0.7205   0.637037
1  0.0005      2  0.5  ...    Cora    GCN        5      0.6695   0.589532
2  0.0005      2  0.5  ...    Cora    GCN        5      0.6910   0.582748
3  0.0005  10000  0.5  ...    Cora    GCN       10      0.5890   0.576767
4  0.0005      2  0.5  ...    Cora    GCN        5      0.7250   0.615251

   client_std_dev  global_std_dev  \
0        0.009378          0.0185
1        0.007439          0.0125
2        0.004423          0.0190
3        0.000000          0.0000
4        0.022996          0.0190

                                            duration  \
0  {'seconds': 31.198800086975098, 'formatted': '...
1  {'seconds': 30.553484201431274, 'formatted': '...
2  {'seconds': 30.64890718460083, 'formatted': '0...
3  {'seconds': 145.6281223297119, 'formatted': '0...
4  {'seconds': 35.39778208732605, 'formatted': '0...

                     experiment_id        timestamp
0  summary_results_20250724_183835  20250724_183835
1  summary_results_20250724_191356  20250724_191356
2  summary_results_20250724_191625  20250724_191625
3  summary_results_20250728_162754  20250728_162754
4  summary_results_20250724_181402  20250724_181402

[5 rows x 28 columns]

In [5]:
results_df

,datasets,data_loading,models,num_clients,num_rounds,epochs,optimizer,decay,beta,lr,...,dataset,model,clients,avg_global,avg_client,client_std_dev,global_std_dev,duration,experiment_id,timestamp
0,[Cora],full,[GCN],[5],10,3,SGD,0.0005,2,0.5,...,Cora,GCN,5,0.7205,0.637037,0.009378,0.0185,"{'seconds': 31.198800086975098, 'formatted': '...",summary_results_20250724_183835,20250724_183835
1,[Cora],full,[GCN],[5],10,3,SGD,0.0005,2,0.5,...,Cora,GCN,5,0.6695,0.589532,0.007439,0.0125,"{'seconds': 30.553484201431274, 'formatted': '...",summary_results_20250724_191356,20250724_191356
2,[Cora],full,[GCN],[5],10,3,SGD,0.0005,2,0.5,...,Cora,GCN,5,0.6910,0.582748,0.004423,0.0190,"{'seconds': 30.64890718460083, 'formatted': '0...",summary_results_20250724_191625,20250724_191625
3,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.5890,0.576767,0.000000,0.0000,"{'seconds': 145.6281223297119, 'formatted': '0...",summary_results_20250728_162754,20250728_162754
4,[Cora],full,[GCN],[5],10,3,SGD,0.0005,2,0.5,...,Cora,GCN,5,0.7250,0.615251,0.022996,0.0190,"{'seconds': 35.39778208732605, 'formatted': '0...",summary_results_20250724_181402,20250724_181402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.8070,0.798116,0.000000,0.0000,"{'seconds': 144.76601815223694, 'formatted': '...",summary_results_20250728_150852,20250728_150852
122,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.7940,0.783298,0.000000,0.0000,"{'seconds': 142.51317310333252, 'formatted': '...",summary_results_20250728_140729,20250728_140729
123,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.3930,0.377304,0.000000,0.0000,"{'seconds': 144.6793773174286, 'formatted': '0...",summary_results_20250728_150619,20250728_150619
124,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.1760,0.178277,0.000000,0.0000,"{'seconds': 143.12395668029785, 'formatted': '...",summary_results_20250728_151629,20250728_151629
125,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.1600,0.159314,0.000000,0.0000,"{'seconds': 144.31446504592896, 'formatted': '...",summary_results_20250728_135445,20250728_135445

In [6]:
# sort by avg_client
results_df = results_df.sort_values(by='avg_client', ascending=False)

In [7]:
results_df

,datasets,data_loading,models,num_clients,num_rounds,epochs,optimizer,decay,beta,lr,...,dataset,model,clients,avg_global,avg_client,client_std_dev,global_std_dev,duration,experiment_id,timestamp
74,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.8180,0.808741,0.000000,0.0000,"{'seconds': 141.59555459022522, 'formatted': '...",summary_results_20250728_141506,20250728_141506
63,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.8140,0.807842,0.000000,0.0000,"{'seconds': 143.61564779281616, 'formatted': '...",summary_results_20250728_153651,20250728_153651
29,[Cora],full,[GCN],[10],300,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.8110,0.804736,0.000000,0.0000,"{'seconds': 208.4695909023285, 'formatted': '0...",summary_results_20250728_123433,20250728_123433
85,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.8140,0.803680,0.000000,0.0000,"{'seconds': 142.58982300758362, 'formatted': '...",summary_results_20250728_145038,20250728_145038
59,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.8120,0.802066,0.000000,0.0000,"{'seconds': 143.18678092956543, 'formatted': '...",summary_results_20250728_145605,20250728_145605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.1450,0.140349,0.000000,0.0000,"{'seconds': 146.45219230651855, 'formatted': '...",summary_results_20250728_163306,20250728_163306
75,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.1250,0.112719,0.000000,0.0000,"{'seconds': 142.4726321697235, 'formatted': '0...",summary_results_20250728_143520,20250728_143520
46,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.1040,0.111821,0.000000,0.0000,"{'seconds': 144.33225393295288, 'formatted': '...",summary_results_20250728_155714,20250728_155714
112,[Cora],full,[GCN],[5],10,3,SGD,0.0005,2,0.5,...,Cora,GCN,5,0.1075,0.102632,0.006824,0.0055,"{'seconds': 30.26354146003723, 'formatted': '0...",summary_results_20250724_191319,20250724_191319
38,[Pubmed],None,[GCN],[5],10,3,SGD,0.0005,2,0.5,...,Pubmed,GCN,5,NaN,NaN,NaN,NaN,"{'seconds': 6.137397527694702, 'formatted': '0...",summary_results_20250724_173301,20250724_173301

In [8]:
results_df.columns

Index(['datasets', 'data_loading', 'models', 'num_clients', 'num_rounds',
       'epochs', 'optimizer', 'decay', 'beta', 'lr', 'results_dir',
       'save_results', 'hop', 'fulltraining_flag', 'use_pe', 'pe_r', 'pe_P',
       'normalize', 'dataset', 'model', 'clients', 'avg_global', 'avg_client',
       'client_std_dev', 'global_std_dev', 'duration', 'experiment_id',
       'timestamp'],
      dtype='object')

In [9]:
# lets keep only: decay, optimizer, beta, lr, avg client, 
results = results_df[['decay', 'optimizer', 'beta', 'lr', 'avg_client']]

In [11]:
# lets reset results index
results = results.reset_index(drop=True)
results

      decay optimizer   beta   lr  avg_client
0    0.0005       SGD  10000  0.5    0.808741
1    0.0005       SGD  10000  0.5    0.807842
2    0.0005       SGD  10000  0.5    0.804736
3    0.0005       SGD  10000  0.5    0.803680
4    0.0005       SGD  10000  0.5    0.802066
..      ...       ...    ...  ...         ...
121  0.0005       SGD  10000  0.5    0.140349
122  0.0005       SGD  10000  0.5    0.112719
123  0.0005       SGD  10000  0.5    0.111821
124  0.0005       SGD      2  0.5    0.102632
125  0.0005       SGD      2  0.5         NaN

[126 rows x 5 columns]

In [14]:
results.head(50)

     decay optimizer   beta   lr  avg_client
0   0.0005       SGD  10000  0.5    0.808741
1   0.0005       SGD  10000  0.5    0.807842
2   0.0005       SGD  10000  0.5    0.804736
3   0.0005       SGD  10000  0.5    0.803680
4   0.0005       SGD  10000  0.5    0.802066
5   0.0005       SGD  10000  0.5    0.801395
6   0.0005       SGD  10000  0.5    0.801110
7   0.0005       SGD  10000  0.5    0.800961
8   0.0005       SGD  10000  0.5    0.800582
9   0.0005       SGD  10000  0.5    0.800326
10  0.0005       SGD  10000  0.5    0.799644
11  0.0005       SGD  10000  0.5    0.799507
12  0.0005       SGD  10000  0.5    0.798627
13  0.0005       SGD  10000  0.5    0.798116
14  0.0005       SGD  10000  0.5    0.798094
15  0.0005       SGD  10000  0.5    0.796218
16  0.0005       SGD  10000  0.5    0.795664
17  0.0005       SGD  10000  0.5    0.795302
18  0.0005       SGD  10000  0.5    0.793517
19  0.0005       SGD  10000  0.5    0.792695
20  0.0005       SGD  10000  0.5    0.792528
21  0.0005       SGD  10000  0.5    0.792497
22  0.0005       SGD  10000  0.5    0.792332
23  0.0005       SGD  10000  0.5    0.791830
24  0.0005       SGD     10  0.5    0.786972
25  0.0005       SGD  10000  0.5    0.786180
26  0.0005       SGD  10000  0.5    0.783298
27  0.0005       SGD  10000  0.5    0.781992
28  0.0005       SGD  10000  0.5    0.779720
29  0.0005       SGD  10000  0.5    0.779611
30  0.0005       SGD  10000  0.5    0.778264
31  0.0005       SGD  10000  0.5    0.777297
32  0.0005       SGD     10  0.5    0.773501
33  0.0005       SGD  10000  0.5    0.771680
34  0.0005       SGD  10000  0.5    0.769198
35  0.0005       SGD  10000  0.5    0.768518
36  0.0005       SGD  10000  0.5    0.768269
37  0.0005       SGD      1  0.5    0.768047
38  0.0005       SGD  10000  0.5    0.767089
39  0.0005       SGD  10000  0.5    0.765940
40  0.0005       SGD  10000  0.5    0.765590
41  0.0005       SGD  10000  0.5    0.763141
42  0.0005       SGD  10000  0.5    0.761710
43  0.0005       SGD  10000  0.5    0.761371
44  0.0005       SGD  10000  0.5    0.760208
45  0.0005       SGD      1  0.5    0.755385
46  0.0005       SGD  10000  0.5    0.747552
47  0.0005       SGD  10000  0.5    0.745621
48  0.0005       SGD  10000  0.5    0.743739
49  0.0005       SGD  10000  0.5    0.741447