In [1]:
# pubmed, cora, citeseer
# Pubmed
# - iid
# - non-iid

In [2]:
path = "/home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline"

In [3]:
import sys
import os
# Add the project root to Python path
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

In [4]:
import pandas as pd
from src.analysis.process_results import process_results_folder_json_v2, process_results_folder_json
from src.analysis.training_logs_analysis import parse_client_csv, process_fp_logs

### Cora Initial

In [5]:
cora_path = "/home/brian_bosho/FP/FP/federated-gnn/results/cora"

In [6]:
df_cora = process_results_folder_json(cora_path)

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/cora
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/Cora_full_GCN_beta10000_clients10 copy/results_Cora_full_GCN_beta10000_clients10_20250801_133452.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/Cora_adjacency_GCN_beta10000_clients10 copy/results_Cora_adjacency_GCN_beta10000_clients10_20250801_113724.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/Cora_diffusion_GCN_beta1_clients10 copy/results_Cora_diffusion_GCN_beta1_clients10_20250730_190533.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/Cora_adjacency_GCN_beta1_clients10/results_Cora_adjacency_GCN_beta1_clients10_20250730_172626.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_zero_hop_GCN_beta10000_clients10/results_Cora_zero_hop_GCN_beta10000_clients10_20250730_100330.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_adjacency_GCN_beta1_clients10/results_Cora_adjacency_GCN_beta1_clients10_20250730_172626.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_adjacency_GCN_beta10000_clients10/results_Cora_adjacency_GCN_beta10000_clients10_20250801_113724.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_zero_hop_GCN_beta1_clients10/results_Cora_zero_hop_GCN_beta1_clients10_20250730_090916.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_diffusion_GCN_beta10000_clients10/results_Cora_diffusion_GCN_beta10000_clients10_20250801_123956.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_full_GCN_beta10000_clients10/results_Cora_full_GCN_beta10000_clients10_20250801_133452.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_diffusion_GCN_beta1_clients10/results_Cora_diffusion_GCN_beta1_clients10_20250730_190533.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_full_GCN_beta1_clients10/results_Cora_full_GCN_beta1_clients10_20250730_202007.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-190440_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-190440_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-183524_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-183524_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-185649_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-185649_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-180428_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-180428_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-173255_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-173255_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-183021_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-183021_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-182006_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-182006_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-174655_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-174655_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-183952_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-183952_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-172635_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-172635_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-175216_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-175216_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-180959_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-180959_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-175821_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-175821_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-184420_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-184420_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-181441_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-181441_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-184912_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-184912_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-190049_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-190049_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-173916_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-173916_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-185310_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-185310_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-182514_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/propagation_stats/prop_exp_20250730-182514_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/Cora_full_GCN_beta1_clients10 copy/results_Cora_full_GCN_beta1_clients10_20250730_202007.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/Cora_adjacency_GCN_beta10000_clients10/results_Cora_adjacency_GCN_beta10000_clients10_20250801_113724.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/Cora_diffusion_GCN_beta10000_clients10 copy/results_Cora_diffusion_GCN_beta10000_clients10_20250801_123956.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final_pe/Cora_zero_hop_GCN_beta10000_clients10/results_Cora_zero_hop_GCN_beta10000_clients10_20250730_100330.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-105433_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-105433_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-104200_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-104200_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-104754_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-104754_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-110834_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-110834_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-110145_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-110145_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final_pe/Cora_zero_hop_GCN_beta1_clients10/results_Cora_zero_hop_GCN_beta1_clients10_20250730_090916.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final/Cora_zero_hop_GCN_beta10000_clients10/results_Cora_zero_hop_GCN_beta10000_clients10_20250730_101930.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final/propagation_stats/prop_exp_20250730-110147_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final/propagation_stats/prop_exp_20250730-110147_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/cora_gcn_final/Cora_zero_hop_GCN_beta1_clients10/results_Cora_zero_hop_GCN_beta1_clients10_20250730_092518.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/Cora_adjacency_GCN_beta1_clients10 copy/results_Cora_adjacency_GCN_beta1_clients10_20250730_172626.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/Cora_diffusion_GCN_beta10000_clients10/results_Cora_diffusion_GCN_beta10000_clients10_20250801_120654.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_zero_hop_GCN_beta10000_clients10/results_Cora_zero_hop_GCN_beta10000_clients10_20250730_101930.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_adjacency_GCN_beta1_clients10/results_Cora_adjacency_GCN_beta1_clients10_20250730_172626.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_adjacency_GCN_beta10000_clients10/results_Cora_adjacency_GCN_beta10000_clients10_20250801_113724.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_zero_hop_GCN_beta1_clients10/results_Cora_zero_hop_GCN_beta1_clients10_20250730_092518.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_diffusion_GCN_beta10000_clients10/results_Cora_diffusion_GCN_beta10000_clients10_20250801_120654.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_full_GCN_beta10000_clients10/results_Cora_full_GCN_beta10000_clients10_20250801_123620.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_diffusion_GCN_beta1_clients10/results_Cora_diffusion_GCN_beta1_clients10_20250730_182509.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_full_GCN_beta1_clients10/results_Cora_full_GCN_beta1_clients10_20250730_190820.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/Cora_full_GCN_beta10000_clients10/results_Cora_full_GCN_beta10000_clients10_20250801_123620.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/Cora_diffusion_GCN_beta1_clients10/results_Cora_diffusion_GCN_beta1_clients10_20250730_182509.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/Cora_full_GCN_beta1_clients10/results_Cora_full_GCN_beta1_clients10_20250730_190820.json
INFO: Successfully created DataFrame with 32 rows.

In [7]:
df_cora

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id
0,cuda,full,GCN,Cora,10,10000,1,False,"[0.813, 0.816, 0.807, 0.81, 0.82, 0.815, 0.817...","[0.8084585426219777, 0.8049957492678637, 0.795...",0.813444,0.802203,0.003919,0.005133,results_Cora_full_GCN_beta10000_clients10_2025...
1,cuda,adjacency,GCN,Cora,10,10000,1,False,"[0.79, 0.792, 0.794, 0.798, 0.799, 0.804, 0.79...","[0.74288381700342, 0.7354451525942126, 0.74279...",0.795900,0.748087,0.005612,0.008948,results_Cora_adjacency_GCN_beta10000_clients10...
2,cuda,diffusion,GCN,Cora,10,1,1,False,"[0.809, 0.809, 0.801, 0.823, 0.801, 0.814, 0.8...","[0.8134162745758482, 0.8008913461351594, 0.809...",0.812600,0.808264,0.008114,0.006617,results_Cora_diffusion_GCN_beta1_clients10_202...
3,cuda,adjacency,GCN,Cora,10,1,1,False,"[0.822, 0.794, 0.804, 0.808, 0.798, 0.813, 0.7...","[0.7965100921345902, 0.7840048781476988, 0.791...",0.803900,0.789962,0.008780,0.004619,results_Cora_adjacency_GCN_beta1_clients10_202...
4,cuda,zero_hop,GCN,Cora,10,10000,1,False,"[0.786, 0.784, 0.778, 0.789, 0.739, 0.778, 0.7...","[0.6217537691914499, 0.6112577894931188, 0.620...",0.770000,0.613490,0.015139,0.010878,results_Cora_zero_hop_GCN_beta10000_clients10_...
5,cuda,adjacency,GCN,Cora,10,1,1,False,"[0.812, 0.144, 0.797, 0.821, 0.812, 0.811, 0.8...","[0.8040941602066501, 0.1578069885807677, 0.805...",0.743500,0.737552,0.200051,0.193332,results_Cora_adjacency_GCN_beta1_clients10_202...
6,cuda,adjacency,GCN,Cora,10,10000,1,False,"[0.79, 0.792, 0.794, 0.798, 0.799, 0.804, 0.79...","[0.74288381700342, 0.7354451525942126, 0.74279...",0.795900,0.748087,0.005612,0.008948,results_Cora_adjacency_GCN_beta10000_clients10...
7,cuda,zero_hop,GCN,Cora,10,1,1,False,"[0.785, 0.758, 0.802, 0.778, 0.787, 0.8, 0.782...","[0.6950289199595718, 0.6649461202319075, 0.704...",0.784900,0.687031,0.013546,0.016691,results_Cora_zero_hop_GCN_beta1_clients10_2025...
8,cuda,diffusion,GCN,Cora,10,10000,1,False,"[0.805, 0.786, 0.798, 0.802, 0.779, 0.792, 0.7...","[0.7681693076135729, 0.7501767394637466, 0.758...",0.793600,0.756639,0.009604,0.007680,results_Cora_diffusion_GCN_beta10000_clients10...
9,cuda,full,GCN,Cora,10,10000,1,False,"[0.813, 0.816, 0.807, 0.81, 0.82, 0.815, 0.817...","[0.8084585426219777, 0.8049957492678637, 0.795...",0.813444,0.802203,0.003919,0.005133,results_Cora_full_GCN_beta10000_clients10_2025...
10,cuda,diffusion,GCN,Cora,10,1,1,False,"[0.809, 0.809, 0.801, 0.823, 0.801, 0.814, 0.8...","[0.8134162745758482, 0.8008913461351594, 0.809...",0.812600,0.808264,0.008114,0.006617,results_Cora_diffusion_GCN_beta1_clients10_202...
11,cuda,full,GCN,Cora,10,1,1,False,"[0.814, 0.809]","[0.8121815244729327, 0.8087107586129413]",0.811500,0.810446,0.002500,0.001735,results_Cora_full_GCN_beta1_clients10_20250730...
12,cuda,full,GCN,Cora,10,1,1,False,"[0.814, 0.809]","[0.8121815244729327, 0.8087107586129413]",0.811500,0.810446,0.002500,0.001735,results_Cora_full_GCN_beta1_clients10_20250730...
13,cuda,adjacency,GCN,Cora,10,10000,1,False,"[0.795, 0.791, 0.781, 0.78, 0.789, 0.789, 0.79...","[0.7355113242882227, 0.7227902595738103, 0.721...",0.785700,0.726120,0.005460,0.005278,results_Cora_adjacency_GCN_beta10000_clients10...
14,cuda,diffusion,GCN,Cora,10,10000,1,False,"[0.805, 0.786, 0.798, 0.802, 0.779, 0.792, 0.7...","[0.7681693076135729, 0.7501767394637466, 0.758...",0.793600,0.756639,0.009604,0.007680,results_Cora_diffusion_GCN_beta10000_clients10...
15,cuda,zero_hop,GCN,Cora,10,10000,1,False,"[0.786, 0.784, 0.778, 0.789, 0.739, 0.778, 0.7...","[0.6217537691914499, 0.6112577894931188, 0.620...",0.770000,0.613490,0.015139,0.010878,results_Cora_zero_hop_GCN_beta10000_clients10_...
16,cuda,zero_hop,GCN,Cora,10,1,1,False,"[0.785, 0.758, 0.802, 0.778, 0.787, 0.8, 0.782...","[0.6950289199595718, 0.6649461202319075, 0.704...",0.784900,0.687031,0.013546,0.016691,results_Cora_zero_hop_GCN_beta1_clients10_2025...
17,cuda,zero_hop,GCN,Cora,10,10000,1,False,"[0.758, 0.782, 0.8, 0.783, 0.772, 0.774, 0.745...","[0.6043236548515871, 0.6392549533733296, 0.634...",0.777111,0.625810,0.016258,0.016496,results_Cora_zero_hop_GCN_beta10000_clients10_...
18,cuda,zero_hop,GCN,Cora,10,1,1,False,"[0.785, 0.782, 0.76, 0.776, 0.769, 0.763, 0.76...","[0.7010149392297724, 0.6830376189276474, 0.678...",0.775500,0.686265,0.010032,0.008227,results_Cora_zero_hop_GCN_beta1_clients10_2025...
19,cuda,adjacency,GCN,Cora,10,1,1,False,"[0.812, 0.144, 0.797, 0.821, 0.812, 0.811, 0.8...","[0.8040941602066501, 0.1578069885807677, 0.805...",0.743500,0.737552,0.200051,0.193332,results_Cora_adjacency_GCN_beta1_clients10_202...
20,cuda,diffusion,GCN,Cora,10,10000,1,False,"[0.791, 0.792, 0.788, 0.783, 0.796, 0.793, 0.7...","[0.7409296424039813, 0.7497307879497169, 0.725...",0.791000,0.732819,0.005040,0.007815,results_Cora_diffusion_GCN_beta10000_clients10...
21,cuda,zero_hop,GCN,Cora,10,10000,1,False,"[0.758, 0.782, 0.8, 0.783, 0.772, 0.774, 0.745...","[0.6043236548515871, 0.6392549533733296, 0.634...",0.777111,0.625810,0.016258,0.016496,results_Cora_zero_hop_GCN_beta10000_clients10_...
22,cuda,adjacency,GCN,Cora,10,1,1,False,"[0.822, 0.794, 0.804, 0.808, 0.798, 0.813, 0.7...","[0.7965100921345902, 0.7840048781476988, 0.791...",0.803900,0.789962,0.008780,0.004619,results_Cora_adjacency_GCN_beta1_clients10_202...
23,cuda,adjacency,GCN,Cora,10,10000,1,False,"[0.795, 0.791, 0.781, 0.78, 0.789, 0.789, 0.79...","[0.7355113242882227, 0.7227902595738103, 0.721...",0.785700,0.726120,0.005460,0.005278,results_Cora_adjacency_GCN_beta10000_clients10...
24,cuda,zero_hop,GCN,Cora,10,1,1,False,"[0.785, 0.782, 0.76, 0.776, 0.769, 0.763, 0.76...","[0.7010149392297724, 0.6830376189276474, 0.678...",0.775500,0.686265,0.010032,0.008227,results_Cora_zero_hop_GCN_beta1_clients10_2025...
25,cuda,diffusion,GCN,Cora,10,10000,1,False,"[0.791, 0.792, 0.788, 0.783, 0.796, 0.793, 0.7...","[0.7409296424039813, 0.7497307879497169, 0.725...",0.791000,0.732819,0.005040,0.007815,results_Cora_diffusion_GCN_beta10000_clients10...
26,cuda,full,GCN,Cora,10,10000,1,False,"[0.817, 0.811, 0.809, 0.817, 0.818, 0.81, 0.81...","[0.8039834247444404, 0.8030939862942035, 0.800...",0.812100,0.803654,0.006172,0.004212,results_Cora_full_GCN_beta10000_clients10_2025...
27,cuda,diffusion,GCN,Cora,10,1,1,False,"[0.797, 0.811, 0.797, 0.793, 0.802, 0.793, 0.7...","[0.779315082787234, 0.7894729067152236, 0.8019...",0.799800,0.788618,0.005776,0.008740,results_Cora_diffusion_GCN_beta1_clients10_202...
28,cuda,full,GCN,Cora,10,1,1,False,"[0.804, 0.803, 0.808, 0.815, 0.814, 0.812, 0.8...","[0.8066407470248992, 0.8072586519224959, 0.803...",0.810222,0.810089,0.004211,0.003820,results_Cora_full_GCN_beta1_clients10_20250730...
29,cuda,full,GCN,Cora,10,10000,1,False,"[0.817, 0.811, 0.809, 0.817, 0.818, 0.81, 0.81...","[0.8039834247444404, 0.8030939862942035, 0.800...",0.812100,0.803654,0.006172,0.004212,results_Cora_full_GCN_beta10000_clients10_2025...
30,cuda,diffusion,GCN,Cora,10,1,1,False,"[0.797, 0.811, 0.797, 0.793, 0.802, 0.793, 0.7...","[0.779315082787234, 0.7894729067152236, 0.8019...",0.799800,0.788618,0.005776,0.008740,results_Cora_diffusion_GCN_beta1_clients10_202...
31,cuda,full,GCN,Cora,10,1,1,False,"[0.804, 0.803, 0.808, 0.815, 0.814, 0.812, 0.8...","[0.8066407470248992, 0.8072586519224959, 0.803...",0.810222,0.810089,0.004211,0.003820,results_Cora_full_GCN_beta1_clients10_20250730...

In [8]:
cora_pe_path = "/home/brian_bosho/FP/FP/federated-gnn/results/cora/PE"
cora_no_pe_path = "/home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE"

In [9]:
df_cora_pe = process_results_folder_json(cora_pe_path)
df_cora_no_pe = process_results_folder_json(cora_no_pe_path)

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_zero_hop_GCN_beta10000_clients10/results_Cora_zero_hop_GCN_beta10000_clients10_20250730_100330.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_adjacency_GCN_beta1_clients10/results_Cora_adjacency_GCN_beta1_clients10_20250730_172626.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_adjacency_GCN_beta10000_clients10/results_Cora_adjacency_GCN_beta10000_clients10_20250801_113724.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_zero_hop_GCN_beta1_clients10/results_Cora_zero_hop_GCN_beta1_clients10_20250730_090916.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_diffusion_GCN_beta10000_clients10/results_Cora_diffusion_GCN_beta10000_clients10_20250801_123956.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_full_GCN_beta10000_clients10/results_Cora_full_GCN_beta10000_clients10_20250801_133452.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_diffusion_GCN_beta1_clients10/results_Cora_diffusion_GCN_beta1_clients10_20250730_190533.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/PE/Cora_full_GCN_beta1_clients10/results_Cora_full_GCN_beta1_clients10_20250730_202007.json
INFO: Successfully created DataFrame with 8 rows.
INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_zero_hop_GCN_beta10000_clients10/results_Cora_zero_hop_GCN_beta10000_clients10_20250730_101930.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_adjacency_GCN_beta1_clients10/results_Cora_adjacency_GCN_beta1_clients10_20250730_172626.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_adjacency_GCN_beta10000_clients10/results_Cora_adjacency_GCN_beta10000_clients10_20250801_113724.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_zero_hop_GCN_beta1_clients10/results_Cora_zero_hop_GCN_beta1_clients10_20250730_092518.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_diffusion_GCN_beta10000_clients10/results_Cora_diffusion_GCN_beta10000_clients10_20250801_120654.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_full_GCN_beta10000_clients10/results_Cora_full_GCN_beta10000_clients10_20250801_123620.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_diffusion_GCN_beta1_clients10/results_Cora_diffusion_GCN_beta1_clients10_20250730_182509.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora/No_PE/Cora_full_GCN_beta1_clients10/results_Cora_full_GCN_beta1_clients10_20250730_190820.json
INFO: Successfully created DataFrame with 8 rows.

In [10]:
df_cora_pe["use_pe"] = True
df_cora_no_pe["use_pe"] = False

In [11]:
df_cora = pd.concat([df_cora_pe, df_cora_no_pe], ignore_index=True)
df_cora

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id,use_pe
0,cuda,zero_hop,GCN,Cora,10,10000,1,False,"[0.786, 0.784, 0.778, 0.789, 0.739, 0.778, 0.7...","[0.6217537691914499, 0.6112577894931188, 0.620...",0.770000,0.613490,0.015139,0.010878,results_Cora_zero_hop_GCN_beta10000_clients10_...,True
1,cuda,adjacency,GCN,Cora,10,1,1,False,"[0.812, 0.144, 0.797, 0.821, 0.812, 0.811, 0.8...","[0.8040941602066501, 0.1578069885807677, 0.805...",0.743500,0.737552,0.200051,0.193332,results_Cora_adjacency_GCN_beta1_clients10_202...,True
2,cuda,adjacency,GCN,Cora,10,10000,1,False,"[0.79, 0.792, 0.794, 0.798, 0.799, 0.804, 0.79...","[0.74288381700342, 0.7354451525942126, 0.74279...",0.795900,0.748087,0.005612,0.008948,results_Cora_adjacency_GCN_beta10000_clients10...,True
3,cuda,zero_hop,GCN,Cora,10,1,1,False,"[0.785, 0.758, 0.802, 0.778, 0.787, 0.8, 0.782...","[0.6950289199595718, 0.6649461202319075, 0.704...",0.784900,0.687031,0.013546,0.016691,results_Cora_zero_hop_GCN_beta1_clients10_2025...,True
4,cuda,diffusion,GCN,Cora,10,10000,1,False,"[0.805, 0.786, 0.798, 0.802, 0.779, 0.792, 0.7...","[0.7681693076135729, 0.7501767394637466, 0.758...",0.793600,0.756639,0.009604,0.007680,results_Cora_diffusion_GCN_beta10000_clients10...,True
5,cuda,full,GCN,Cora,10,10000,1,False,"[0.813, 0.816, 0.807, 0.81, 0.82, 0.815, 0.817...","[0.8084585426219777, 0.8049957492678637, 0.795...",0.813444,0.802203,0.003919,0.005133,results_Cora_full_GCN_beta10000_clients10_2025...,True
6,cuda,diffusion,GCN,Cora,10,1,1,False,"[0.809, 0.809, 0.801, 0.823, 0.801, 0.814, 0.8...","[0.8134162745758482, 0.8008913461351594, 0.809...",0.812600,0.808264,0.008114,0.006617,results_Cora_diffusion_GCN_beta1_clients10_202...,True
7,cuda,full,GCN,Cora,10,1,1,False,"[0.814, 0.809]","[0.8121815244729327, 0.8087107586129413]",0.811500,0.810446,0.002500,0.001735,results_Cora_full_GCN_beta1_clients10_20250730...,True
8,cuda,zero_hop,GCN,Cora,10,10000,1,False,"[0.758, 0.782, 0.8, 0.783, 0.772, 0.774, 0.745...","[0.6043236548515871, 0.6392549533733296, 0.634...",0.777111,0.625810,0.016258,0.016496,results_Cora_zero_hop_GCN_beta10000_clients10_...,False
9,cuda,adjacency,GCN,Cora,10,1,1,False,"[0.822, 0.794, 0.804, 0.808, 0.798, 0.813, 0.7...","[0.7965100921345902, 0.7840048781476988, 0.791...",0.803900,0.789962,0.008780,0.004619,results_Cora_adjacency_GCN_beta1_clients10_202...,False
10,cuda,adjacency,GCN,Cora,10,10000,1,False,"[0.795, 0.791, 0.781, 0.78, 0.789, 0.789, 0.79...","[0.7355113242882227, 0.7227902595738103, 0.721...",0.785700,0.726120,0.005460,0.005278,results_Cora_adjacency_GCN_beta10000_clients10...,False
11,cuda,zero_hop,GCN,Cora,10,1,1,False,"[0.785, 0.782, 0.76, 0.776, 0.769, 0.763, 0.76...","[0.7010149392297724, 0.6830376189276474, 0.678...",0.775500,0.686265,0.010032,0.008227,results_Cora_zero_hop_GCN_beta1_clients10_2025...,False
12,cuda,diffusion,GCN,Cora,10,10000,1,False,"[0.791, 0.792, 0.788, 0.783, 0.796, 0.793, 0.7...","[0.7409296424039813, 0.7497307879497169, 0.725...",0.791000,0.732819,0.005040,0.007815,results_Cora_diffusion_GCN_beta10000_clients10...,False
13,cuda,full,GCN,Cora,10,10000,1,False,"[0.817, 0.811, 0.809, 0.817, 0.818, 0.81, 0.81...","[0.8039834247444404, 0.8030939862942035, 0.800...",0.812100,0.803654,0.006172,0.004212,results_Cora_full_GCN_beta10000_clients10_2025...,False
14,cuda,diffusion,GCN,Cora,10,1,1,False,"[0.797, 0.811, 0.797, 0.793, 0.802, 0.793, 0.7...","[0.779315082787234, 0.7894729067152236, 0.8019...",0.799800,0.788618,0.005776,0.008740,results_Cora_diffusion_GCN_beta1_clients10_202...,False
15,cuda,full,GCN,Cora,10,1,1,False,"[0.804, 0.803, 0.808, 0.815, 0.814, 0.812, 0.8...","[0.8066407470248992, 0.8072586519224959, 0.803...",0.810222,0.810089,0.004211,0.003820,results_Cora_full_GCN_beta1_clients10_20250730...,False

In [12]:
keep_cols = ['data_loading_option', 'model_type', 'dataset','beta','average_client_result', 'use_pe','experiment_id', 'std_client']
df_cora = df_cora[keep_cols]

In [13]:
df_cora

,data_loading_option,model_type,dataset,beta,average_client_result,use_pe,experiment_id,std_client
0,zero_hop,GCN,Cora,10000,0.613490,True,results_Cora_zero_hop_GCN_beta10000_clients10_...,0.010878
1,adjacency,GCN,Cora,1,0.737552,True,results_Cora_adjacency_GCN_beta1_clients10_202...,0.193332
2,adjacency,GCN,Cora,10000,0.748087,True,results_Cora_adjacency_GCN_beta10000_clients10...,0.008948
3,zero_hop,GCN,Cora,1,0.687031,True,results_Cora_zero_hop_GCN_beta1_clients10_2025...,0.016691
4,diffusion,GCN,Cora,10000,0.756639,True,results_Cora_diffusion_GCN_beta10000_clients10...,0.007680
5,full,GCN,Cora,10000,0.802203,True,results_Cora_full_GCN_beta10000_clients10_2025...,0.005133
6,diffusion,GCN,Cora,1,0.808264,True,results_Cora_diffusion_GCN_beta1_clients10_202...,0.006617
7,full,GCN,Cora,1,0.810446,True,results_Cora_full_GCN_beta1_clients10_20250730...,0.001735
8,zero_hop,GCN,Cora,10000,0.625810,False,results_Cora_zero_hop_GCN_beta10000_clients10_...,0.016496
9,adjacency,GCN,Cora,1,0.789962,False,results_Cora_adjacency_GCN_beta1_clients10_202...,0.004619
10,adjacency,GCN,Cora,10000,0.726120,False,results_Cora_adjacency_GCN_beta10000_clients10...,0.005278
11,zero_hop,GCN,Cora,1,0.686265,False,results_Cora_zero_hop_GCN_beta1_clients10_2025...,0.008227
12,diffusion,GCN,Cora,10000,0.732819,False,results_Cora_diffusion_GCN_beta10000_clients10...,0.007815
13,full,GCN,Cora,10000,0.803654,False,results_Cora_full_GCN_beta10000_clients10_2025...,0.004212
14,diffusion,GCN,Cora,1,0.788618,False,results_Cora_diffusion_GCN_beta1_clients10_202...,0.008740
15,full,GCN,Cora,1,0.810089,False,results_Cora_full_GCN_beta1_clients10_20250730...,0.003820

In [14]:
# drop experiment_id column
df_cora = df_cora.drop(columns=['experiment_id'])
df_cora

,data_loading_option,model_type,dataset,beta,average_client_result,use_pe,std_client
0,zero_hop,GCN,Cora,10000,0.613490,True,0.010878
1,adjacency,GCN,Cora,1,0.737552,True,0.193332
2,adjacency,GCN,Cora,10000,0.748087,True,0.008948
3,zero_hop,GCN,Cora,1,0.687031,True,0.016691
4,diffusion,GCN,Cora,10000,0.756639,True,0.007680
5,full,GCN,Cora,10000,0.802203,True,0.005133
6,diffusion,GCN,Cora,1,0.808264,True,0.006617
7,full,GCN,Cora,1,0.810446,True,0.001735
8,zero_hop,GCN,Cora,10000,0.625810,False,0.016496
9,adjacency,GCN,Cora,1,0.789962,False,0.004619
10,adjacency,GCN,Cora,10000,0.726120,False,0.005278
11,zero_hop,GCN,Cora,1,0.686265,False,0.008227
12,diffusion,GCN,Cora,10000,0.732819,False,0.007815
13,full,GCN,Cora,10000,0.803654,False,0.004212
14,diffusion,GCN,Cora,1,0.788618,False,0.008740
15,full,GCN,Cora,1,0.810089,False,0.003820

### Pubmed

In [15]:
pubmed_no_pe_path = "/home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/No_pe"
pubmed_pe_path = "/home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/PE"

In [16]:
df_pubmed_no_pe = process_results_folder_json(pubmed_no_pe_path)
df_pubmed_pe = process_results_folder_json(pubmed_pe_path)

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/No_pe
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/No_pe/Pubmed_full_GCN_beta10000_clients10/results_Pubmed_full_GCN_beta10000_clients10_20250730_212512.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/No_pe/Pubmed_zero_hop_GCN_beta10000_clients10/results_Pubmed_zero_hop_GCN_beta10000_clients10_20250730_201644.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/No_pe/Pubmed_adjacency_GCN_beta10_clients10/results_Pubmed_adjacency_GCN_beta10_clients10_20250730_202650.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/No_pe/Pubmed_zero_hop_GCN_beta10_clients10/results_Pubmed_zero_hop_GCN_beta10_clients10_20250730_200702.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/No_pe/Pubmed_full_GCN_beta10_clients10/results_Pubmed_full_GCN_beta10_clients10_20250730_211043.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/No_pe/Pubmed_diffusion_GCN_beta10_clients10/results_Pubmed_diffusion_GCN_beta10_clients10_20250730_203938.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/No_pe/Pubmed_diffusion_GCN_beta10000_clients10/results_Pubmed_diffusion_GCN_beta10000_clients10_20250730_205538.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/No_pe/Pubmed_adjacency_GCN_beta10000_clients10/results_Pubmed_adjacency_GCN_beta10000_clients10_20250730_203148.json
INFO: Successfully created DataFrame with 8 rows.
INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/PE
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/PE/Pubmed_full_GCN_beta10000_clients10/results_Pubmed_full_GCN_beta10000_clients10_20250730_222946.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/PE/Pubmed_zero_hop_GCN_beta10000_clients10/results_Pubmed_zero_hop_GCN_beta10000_clients10_20250730_213256.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/PE/Pubmed_adjacency_GCN_beta10_clients10/results_Pubmed_adjacency_GCN_beta10_clients10_20250730_215547.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/PE/Pubmed_zero_hop_GCN_beta10_clients10/results_Pubmed_zero_hop_GCN_beta10_clients10_20250730_213052.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/PE/Pubmed_full_GCN_beta10_clients10/results_Pubmed_full_GCN_beta10_clients10_20250730_222705.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/PE/Pubmed_diffusion_GCN_beta10_clients10/results_Pubmed_diffusion_GCN_beta10_clients10_20250730_221012.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/PE/Pubmed_diffusion_GCN_beta10000_clients10/results_Pubmed_diffusion_GCN_beta10000_clients10_20250730_221352.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Pubmed/PE/Pubmed_adjacency_GCN_beta10000_clients10/results_Pubmed_adjacency_GCN_beta10000_clients10_20250730_220141.json
INFO: Successfully created DataFrame with 8 rows.

In [17]:
df_pubmed_no_pe["use_pe"] = False
df_pubmed_pe["use_pe"] = True

In [18]:
# concatenate the two
df_pubmed = pd.concat([df_pubmed_no_pe, df_pubmed_pe], ignore_index=True)

In [19]:
keep_cols = ['data_loading_option', 'model_type', 'dataset','beta','average_client_result', 'use_pe','experiment_id', 'std_client']

In [20]:
df_pubmed = df_pubmed[keep_cols]
df_pubmed

,data_loading_option,model_type,dataset,beta,average_client_result,use_pe,experiment_id,std_client
0,full,GCN,Pubmed,10000,0.784176,False,results_Pubmed_full_GCN_beta10000_clients10_20...,0.002904
1,zero_hop,GCN,Pubmed,10000,0.653125,False,results_Pubmed_zero_hop_GCN_beta10000_clients1...,0.008509
2,adjacency,GCN,Pubmed,10,0.779701,False,results_Pubmed_adjacency_GCN_beta10_clients10_...,0.000446
3,zero_hop,GCN,Pubmed,10,0.645805,False,results_Pubmed_zero_hop_GCN_beta10_clients10_2...,0.012908
4,full,GCN,Pubmed,10,0.795334,False,results_Pubmed_full_GCN_beta10_clients10_20250...,0.007189
5,diffusion,GCN,Pubmed,10,0.781134,False,results_Pubmed_diffusion_GCN_beta10_clients10_...,0.005931
6,diffusion,GCN,Pubmed,10000,0.792203,False,results_Pubmed_diffusion_GCN_beta10000_clients...,0.003282
7,adjacency,GCN,Pubmed,10000,0.793614,False,results_Pubmed_adjacency_GCN_beta10000_clients...,0.003996
8,full,GCN,Pubmed,10000,0.786222,True,results_Pubmed_full_GCN_beta10000_clients10_20...,0.005237
9,zero_hop,GCN,Pubmed,10000,0.647367,True,results_Pubmed_zero_hop_GCN_beta10000_clients1...,0.011396
10,adjacency,GCN,Pubmed,10,0.761056,True,results_Pubmed_adjacency_GCN_beta10_clients10_...,0.005078
11,zero_hop,GCN,Pubmed,10,0.655896,True,results_Pubmed_zero_hop_GCN_beta10_clients10_2...,0.009144
12,full,GCN,Pubmed,10,0.795168,True,results_Pubmed_full_GCN_beta10_clients10_20250...,0.003688
13,diffusion,GCN,Pubmed,10,0.764270,True,results_Pubmed_diffusion_GCN_beta10_clients10_...,0.005372
14,diffusion,GCN,Pubmed,10000,0.768603,True,results_Pubmed_diffusion_GCN_beta10000_clients...,0.005833
15,adjacency,GCN,Pubmed,10000,0.772679,True,results_Pubmed_adjacency_GCN_beta10000_clients...,0.009039

In [21]:
# drop experiment_id column
df_pubmed = df_pubmed.drop(columns=['experiment_id'])
df_pubmed

,data_loading_option,model_type,dataset,beta,average_client_result,use_pe,std_client
0,full,GCN,Pubmed,10000,0.784176,False,0.002904
1,zero_hop,GCN,Pubmed,10000,0.653125,False,0.008509
2,adjacency,GCN,Pubmed,10,0.779701,False,0.000446
3,zero_hop,GCN,Pubmed,10,0.645805,False,0.012908
4,full,GCN,Pubmed,10,0.795334,False,0.007189
5,diffusion,GCN,Pubmed,10,0.781134,False,0.005931
6,diffusion,GCN,Pubmed,10000,0.792203,False,0.003282
7,adjacency,GCN,Pubmed,10000,0.793614,False,0.003996
8,full,GCN,Pubmed,10000,0.786222,True,0.005237
9,zero_hop,GCN,Pubmed,10000,0.647367,True,0.011396
10,adjacency,GCN,Pubmed,10,0.761056,True,0.005078
11,zero_hop,GCN,Pubmed,10,0.655896,True,0.009144
12,full,GCN,Pubmed,10,0.795168,True,0.003688
13,diffusion,GCN,Pubmed,10,0.764270,True,0.005372
14,diffusion,GCN,Pubmed,10000,0.768603,True,0.005833
15,adjacency,GCN,Pubmed,10000,0.772679,True,0.009039

### Combine

### Citeseer All

In [22]:
citeseer_no_pe_path = "/home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/No_PE"
citeseer_pe_path = "/home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE"

In [23]:
df_citeseer_no_pe_path = process_results_folder_json(citeseer_no_pe_path)
df_citeseer_pe_path = process_results_folder_json(citeseer_pe_path)

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/No_PE
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/No_PE/Citeseer_full_GCN_beta10000_clients10/results_Citeseer_full_GCN_beta10000_clients10_20250730_174615.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/No_PE/Citeseer_diffusion_GCN_beta1_clients10/results_Citeseer_diffusion_GCN_beta1_clients10_20250730_102313.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/No_PE/Citeseer_full_GCN_beta1_clients10/results_Citeseer_full_GCN_beta1_clients10_20250730_172626.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/No_PE/Citeseer_zero_hop_GCN_beta10000_clients10/results_Citeseer_zero_hop_GCN_beta10000_clients10_20250730_092607.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/No_PE/Citeseer_adjacency_GCN_beta10000_clients10/results_Citeseer_adjacency_GCN_beta10000_clients10_20250730_100602.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/No_PE/Citeseer_adjacency_GCN_beta1_clients10/results_Citeseer_adjacency_GCN_beta1_clients10_20250730_094444.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/No_PE/Citeseer_diffusion_GCN_beta10000_clients10/results_Citeseer_diffusion_GCN_beta10000_clients10_20250730_104634.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/No_PE/Citeseer_zero_hop_GCN_beta1_clients10/results_Citeseer_zero_hop_GCN_beta1_clients10_20250730_090916.json
INFO: Successfully created DataFrame with 8 rows.
INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE/Citeseer_full_GCN_beta10000_clients10/results_Citeseer_full_GCN_beta10000_clients10_20250730_183022.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE/Citeseer_diffusion_GCN_beta1_clients10/results_Citeseer_diffusion_GCN_beta1_clients10_20250801_220200.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE/Citeseer_diffusion_GCN_beta1_clients10/results_Citeseer_diffusion_GCN_beta1_clients10_20250801_225029.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE/Citeseer_full_GCN_beta1_clients10/results_Citeseer_full_GCN_beta1_clients10_20250730_181557.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE/Citeseer_zero_hop_GCN_beta10000_clients10/results_Citeseer_zero_hop_GCN_beta10000_clients10_20250730_092955.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE/Citeseer_adjacency_GCN_beta10000_clients10/results_Citeseer_adjacency_GCN_beta10000_clients10_20250801_222111.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE/Citeseer_adjacency_GCN_beta10000_clients10/results_Citeseer_adjacency_GCN_beta10000_clients10_20250802_001525.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE/Citeseer_adjacency_GCN_beta1_clients10/results_Citeseer_adjacency_GCN_beta1_clients10_20250801_221353.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE/Citeseer_adjacency_GCN_beta1_clients10/results_Citeseer_adjacency_GCN_beta1_clients10_20250801_234250.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE/Citeseer_diffusion_GCN_beta10000_clients10/results_Citeseer_diffusion_GCN_beta10000_clients10_20250801_220908.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE/Citeseer_diffusion_GCN_beta10000_clients10/results_Citeseer_diffusion_GCN_beta10000_clients10_20250801_231823.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/Citeseer/PE/Citeseer_zero_hop_GCN_beta1_clients10/results_Citeseer_zero_hop_GCN_beta1_clients10_20250730_090916.json
INFO: Successfully created DataFrame with 12 rows.

In [24]:
df_citeseer_no_pe_path

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id
0,cuda,full,GCN,Citeseer,10,10000,1,False,"[0.713, 0.717, 0.708, 0.714, 0.712, 0.711, 0.7...","[0.711392605564596, 0.7130019847926208, 0.7052...",0.714000,0.709026,0.003768,0.003617,results_Citeseer_full_GCN_beta10000_clients10_...
1,cuda,diffusion,GCN,Citeseer,10,1,1,False,"[0.705, 0.7, 0.71, 0.71, 0.716, 0.711, 0.712, ...","[0.6918816278737333, 0.6817554877813852, 0.695...",0.709000,0.693874,0.004313,0.005693,results_Citeseer_diffusion_GCN_beta1_clients10...
2,cuda,full,GCN,Citeseer,10,1,1,False,"[0.702, 0.711, 0.715, 0.714, 0.708, 0.714, 0.7...","[0.6876990757266757, 0.6941391252478837, 0.696...",0.708900,0.694183,0.004504,0.006091,results_Citeseer_full_GCN_beta1_clients10_2025...
3,cuda,zero_hop,GCN,Citeseer,10,10000,1,False,"[0.698, 0.693, 0.694, 0.695, 0.693, 0.694, 0.6...","[0.6370812482157587, 0.6400242182277399, 0.628...",0.692700,0.630202,0.004880,0.006743,results_Citeseer_zero_hop_GCN_beta10000_client...
4,cuda,adjacency,GCN,Citeseer,10,10000,1,False,"[0.703, 0.702, 0.697, 0.699, 0.687, 0.698, 0.6...","[0.6751090277419792, 0.6658915169344064, 0.663...",0.696600,0.665228,0.005426,0.007105,results_Citeseer_adjacency_GCN_beta10000_clien...
5,cuda,adjacency,GCN,Citeseer,10,1,1,False,"[0.706, 0.713, 0.707, 0.703, 0.709, 0.704, 0.7...","[0.6827637016346125, 0.6954366404174741, 0.689...",0.705900,0.688982,0.003618,0.005460,results_Citeseer_adjacency_GCN_beta1_clients10...
6,cuda,diffusion,GCN,Citeseer,10,10000,1,False,"[0.689, 0.68, 0.694, 0.699, 0.701, 0.695, 0.69...","[0.6568782948341426, 0.6496332452113072, 0.652...",0.694444,0.660517,0.006202,0.006450,results_Citeseer_diffusion_GCN_beta10000_clien...
7,cuda,zero_hop,GCN,Citeseer,10,1,1,False,"[0.685, 0.682, 0.673, 0.687, 0.677, 0.696, 0.6...","[0.6283491135530416, 0.6328829148191576, 0.623...",0.688900,0.637077,0.009115,0.008811,results_Citeseer_zero_hop_GCN_beta1_clients10_...

In [25]:
df_citeseer_pe_path

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id
0,cuda,full,GCN,Citeseer,10,10000,1,False,"[0.711, 0.715, 0.714, 0.711, 0.713, 0.712, 0.7...","[0.7102733533576991, 0.7103590972731836, 0.705...",0.7127,0.707747,0.002492,0.002133,results_Citeseer_full_GCN_beta10000_clients10_...
1,cuda,diffusion,GCN,Citeseer,10,1,1,False,[0.697],[0.6728300264090981],0.6970,0.672830,0.000000,0.000000,results_Citeseer_diffusion_GCN_beta1_clients10...
2,cuda,diffusion,GCN,Citeseer,10,1,1,False,"[0.69, 0.696, 0.689, 0.689, 0.681, 0.708, 0.68...","[0.6687639084905717, 0.6793319790325384, 0.674...",0.6938,0.670252,0.010448,0.009377,results_Citeseer_diffusion_GCN_beta1_clients10...
3,cuda,full,GCN,Citeseer,10,1,1,False,"[0.709, 0.711, 0.716, 0.707, 0.708, 0.706, 0.7...","[0.7037613628501868, 0.6988745039908, 0.706218...",0.7117,0.697607,0.005951,0.006093,results_Citeseer_full_GCN_beta1_clients10_2025...
4,cuda,zero_hop,GCN,Citeseer,10,10000,1,False,"[0.68, 0.695, 0.694, 0.703, 0.672, 0.708, 0.69...","[0.6158200033756078, 0.632877454261015, 0.6207...",0.6929,0.629163,0.009904,0.012182,results_Citeseer_zero_hop_GCN_beta10000_client...
5,cuda,adjacency,GCN,Citeseer,10,10000,1,False,[0.701],[0.6633762329641597],0.7010,0.663376,0.000000,0.000000,results_Citeseer_adjacency_GCN_beta10000_clien...
6,cuda,adjacency,GCN,Citeseer,10,10000,1,False,"[0.685, 0.684, 0.695, 0.689, 0.687, 0.7, 0.705...","[0.6477295185911026, 0.6499846732046363, 0.663...",0.6924,0.655510,0.006576,0.008037,results_Citeseer_adjacency_GCN_beta10000_clien...
7,cuda,adjacency,GCN,Citeseer,10,1,1,False,[0.698],[0.6657038153997148],0.6980,0.665704,0.000000,0.000000,results_Citeseer_adjacency_GCN_beta1_clients10...
8,cuda,adjacency,GCN,Citeseer,10,1,1,False,"[0.699, 0.71, 0.692, 0.698, 0.679, 0.683, 0.70...","[0.6791122602423629, 0.6743524296099944, 0.666...",0.6957,0.667342,0.010565,0.008693,results_Citeseer_adjacency_GCN_beta1_clients10...
9,cuda,diffusion,GCN,Citeseer,10,10000,1,False,[0.697],[0.6598225789857581],0.6970,0.659823,0.000000,0.000000,results_Citeseer_diffusion_GCN_beta10000_clien...
10,cuda,diffusion,GCN,Citeseer,10,10000,1,False,"[0.694, 0.693, 0.681, 0.685, 0.696, 0.695, 0.6...","[0.6710298156707626, 0.660254991555785, 0.6518...",0.6895,0.658065,0.005679,0.011232,results_Citeseer_diffusion_GCN_beta10000_clien...
11,cuda,zero_hop,GCN,Citeseer,10,1,1,False,"[0.688, 0.695, 0.701, 0.686, 0.691, 0.679, 0.6...","[0.6451203811738717, 0.6399981390820348, 0.647...",0.6907,0.635401,0.005832,0.006945,results_Citeseer_zero_hop_GCN_beta1_clients10_...

In [26]:
# add a column use_pe = True df_citeseer_no_pe_path
df_citeseer_no_pe_path["use_pe"] = False
df_citeseer_pe_path["use_pe"] = True

# df_citeseer_pe_path

In [27]:
df_citeseer_combined = pd.concat([df_citeseer_no_pe_path, df_citeseer_pe_path], ignore_index=True)
df_citeseer_combined

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id,use_pe
0,cuda,full,GCN,Citeseer,10,10000,1,False,"[0.713, 0.717, 0.708, 0.714, 0.712, 0.711, 0.7...","[0.711392605564596, 0.7130019847926208, 0.7052...",0.714000,0.709026,0.003768,0.003617,results_Citeseer_full_GCN_beta10000_clients10_...,False
1,cuda,diffusion,GCN,Citeseer,10,1,1,False,"[0.705, 0.7, 0.71, 0.71, 0.716, 0.711, 0.712, ...","[0.6918816278737333, 0.6817554877813852, 0.695...",0.709000,0.693874,0.004313,0.005693,results_Citeseer_diffusion_GCN_beta1_clients10...,False
2,cuda,full,GCN,Citeseer,10,1,1,False,"[0.702, 0.711, 0.715, 0.714, 0.708, 0.714, 0.7...","[0.6876990757266757, 0.6941391252478837, 0.696...",0.708900,0.694183,0.004504,0.006091,results_Citeseer_full_GCN_beta1_clients10_2025...,False
3,cuda,zero_hop,GCN,Citeseer,10,10000,1,False,"[0.698, 0.693, 0.694, 0.695, 0.693, 0.694, 0.6...","[0.6370812482157587, 0.6400242182277399, 0.628...",0.692700,0.630202,0.004880,0.006743,results_Citeseer_zero_hop_GCN_beta10000_client...,False
4,cuda,adjacency,GCN,Citeseer,10,10000,1,False,"[0.703, 0.702, 0.697, 0.699, 0.687, 0.698, 0.6...","[0.6751090277419792, 0.6658915169344064, 0.663...",0.696600,0.665228,0.005426,0.007105,results_Citeseer_adjacency_GCN_beta10000_clien...,False
5,cuda,adjacency,GCN,Citeseer,10,1,1,False,"[0.706, 0.713, 0.707, 0.703, 0.709, 0.704, 0.7...","[0.6827637016346125, 0.6954366404174741, 0.689...",0.705900,0.688982,0.003618,0.005460,results_Citeseer_adjacency_GCN_beta1_clients10...,False
6,cuda,diffusion,GCN,Citeseer,10,10000,1,False,"[0.689, 0.68, 0.694, 0.699, 0.701, 0.695, 0.69...","[0.6568782948341426, 0.6496332452113072, 0.652...",0.694444,0.660517,0.006202,0.006450,results_Citeseer_diffusion_GCN_beta10000_clien...,False
7,cuda,zero_hop,GCN,Citeseer,10,1,1,False,"[0.685, 0.682, 0.673, 0.687, 0.677, 0.696, 0.6...","[0.6283491135530416, 0.6328829148191576, 0.623...",0.688900,0.637077,0.009115,0.008811,results_Citeseer_zero_hop_GCN_beta1_clients10_...,False
8,cuda,full,GCN,Citeseer,10,10000,1,False,"[0.711, 0.715, 0.714, 0.711, 0.713, 0.712, 0.7...","[0.7102733533576991, 0.7103590972731836, 0.705...",0.712700,0.707747,0.002492,0.002133,results_Citeseer_full_GCN_beta10000_clients10_...,True
9,cuda,diffusion,GCN,Citeseer,10,1,1,False,[0.697],[0.6728300264090981],0.697000,0.672830,0.000000,0.000000,results_Citeseer_diffusion_GCN_beta1_clients10...,True
10,cuda,diffusion,GCN,Citeseer,10,1,1,False,"[0.69, 0.696, 0.689, 0.689, 0.681, 0.708, 0.68...","[0.6687639084905717, 0.6793319790325384, 0.674...",0.693800,0.670252,0.010448,0.009377,results_Citeseer_diffusion_GCN_beta1_clients10...,True
11,cuda,full,GCN,Citeseer,10,1,1,False,"[0.709, 0.711, 0.716, 0.707, 0.708, 0.706, 0.7...","[0.7037613628501868, 0.6988745039908, 0.706218...",0.711700,0.697607,0.005951,0.006093,results_Citeseer_full_GCN_beta1_clients10_2025...,True
12,cuda,zero_hop,GCN,Citeseer,10,10000,1,False,"[0.68, 0.695, 0.694, 0.703, 0.672, 0.708, 0.69...","[0.6158200033756078, 0.632877454261015, 0.6207...",0.692900,0.629163,0.009904,0.012182,results_Citeseer_zero_hop_GCN_beta10000_client...,True
13,cuda,adjacency,GCN,Citeseer,10,10000,1,False,[0.701],[0.6633762329641597],0.701000,0.663376,0.000000,0.000000,results_Citeseer_adjacency_GCN_beta10000_clien...,True
14,cuda,adjacency,GCN,Citeseer,10,10000,1,False,"[0.685, 0.684, 0.695, 0.689, 0.687, 0.7, 0.705...","[0.6477295185911026, 0.6499846732046363, 0.663...",0.692400,0.655510,0.006576,0.008037,results_Citeseer_adjacency_GCN_beta10000_clien...,True
15,cuda,adjacency,GCN,Citeseer,10,1,1,False,[0.698],[0.6657038153997148],0.698000,0.665704,0.000000,0.000000,results_Citeseer_adjacency_GCN_beta1_clients10...,True
16,cuda,adjacency,GCN,Citeseer,10,1,1,False,"[0.699, 0.71, 0.692, 0.698, 0.679, 0.683, 0.70...","[0.6791122602423629, 0.6743524296099944, 0.666...",0.695700,0.667342,0.010565,0.008693,results_Citeseer_adjacency_GCN_beta1_clients10...,True
17,cuda,diffusion,GCN,Citeseer,10,10000,1,False,[0.697],[0.6598225789857581],0.697000,0.659823,0.000000,0.000000,results_Citeseer_diffusion_GCN_beta10000_clien...,True
18,cuda,diffusion,GCN,Citeseer,10,10000,1,False,"[0.694, 0.693, 0.681, 0.685, 0.696, 0.695, 0.6...","[0.6710298156707626, 0.660254991555785, 0.6518...",0.689500,0.658065,0.005679,0.011232,results_Citeseer_diffusion_GCN_beta10000_clien...,True
19,cuda,zero_hop,GCN,Citeseer,10,1,1,False,"[0.688, 0.695, 0.701, 0.686, 0.691, 0.679, 0.6...","[0.6451203811738717, 0.6399981390820348, 0.647...",0.690700,0.635401,0.005832,0.006945,results_Citeseer_zero_hop_GCN_beta1_clients10_...,True

In [28]:
df_citeseer_combined.columns

Index(['device', 'data_loading_option', 'model_type', 'dataset', 'num_clients',
       'beta', 'hop', 'fulltraining_flag', 'global_results', 'client_results',
       'average_global_result', 'average_client_result', 'std_global',
       'std_client', 'experiment_id', 'use_pe'],
      dtype='object')

In [29]:
keep_cols = ['data_loading_option', 'model_type', 'dataset','beta','average_client_result', 'use_pe','experiment_id', 'std_client']
keep_cols

['data_loading_option',
 'model_type',
 'dataset',
 'beta',
 'average_client_result',
 'use_pe',
 'experiment_id',
 'std_client']

In [30]:
df_citeseer = df_citeseer_combined[keep_cols]
df_citeseer

,data_loading_option,model_type,dataset,beta,average_client_result,use_pe,experiment_id,std_client
0,full,GCN,Citeseer,10000,0.709026,False,results_Citeseer_full_GCN_beta10000_clients10_...,0.003617
1,diffusion,GCN,Citeseer,1,0.693874,False,results_Citeseer_diffusion_GCN_beta1_clients10...,0.005693
2,full,GCN,Citeseer,1,0.694183,False,results_Citeseer_full_GCN_beta1_clients10_2025...,0.006091
3,zero_hop,GCN,Citeseer,10000,0.630202,False,results_Citeseer_zero_hop_GCN_beta10000_client...,0.006743
4,adjacency,GCN,Citeseer,10000,0.665228,False,results_Citeseer_adjacency_GCN_beta10000_clien...,0.007105
5,adjacency,GCN,Citeseer,1,0.688982,False,results_Citeseer_adjacency_GCN_beta1_clients10...,0.005460
6,diffusion,GCN,Citeseer,10000,0.660517,False,results_Citeseer_diffusion_GCN_beta10000_clien...,0.006450
7,zero_hop,GCN,Citeseer,1,0.637077,False,results_Citeseer_zero_hop_GCN_beta1_clients10_...,0.008811
8,full,GCN,Citeseer,10000,0.707747,True,results_Citeseer_full_GCN_beta10000_clients10_...,0.002133
9,diffusion,GCN,Citeseer,1,0.672830,True,results_Citeseer_diffusion_GCN_beta1_clients10...,0.000000
10,diffusion,GCN,Citeseer,1,0.670252,True,results_Citeseer_diffusion_GCN_beta1_clients10...,0.009377
11,full,GCN,Citeseer,1,0.697607,True,results_Citeseer_full_GCN_beta1_clients10_2025...,0.006093
12,zero_hop,GCN,Citeseer,10000,0.629163,True,results_Citeseer_zero_hop_GCN_beta10000_client...,0.012182
13,adjacency,GCN,Citeseer,10000,0.663376,True,results_Citeseer_adjacency_GCN_beta10000_clien...,0.000000
14,adjacency,GCN,Citeseer,10000,0.655510,True,results_Citeseer_adjacency_GCN_beta10000_clien...,0.008037
15,adjacency,GCN,Citeseer,1,0.665704,True,results_Citeseer_adjacency_GCN_beta1_clients10...,0.000000
16,adjacency,GCN,Citeseer,1,0.667342,True,results_Citeseer_adjacency_GCN_beta1_clients10...,0.008693
17,diffusion,GCN,Citeseer,10000,0.659823,True,results_Citeseer_diffusion_GCN_beta10000_clien...,0.000000
18,diffusion,GCN,Citeseer,10000,0.658065,True,results_Citeseer_diffusion_GCN_beta10000_clien...,0.011232
19,zero_hop,GCN,Citeseer,1,0.635401,True,results_Citeseer_zero_hop_GCN_beta1_clients10_...,0.006945

In [31]:
# drop experiment_id cols
df_citeseer = df_citeseer.drop(columns=['experiment_id'])
df_citeseer

,data_loading_option,model_type,dataset,beta,average_client_result,use_pe,std_client
0,full,GCN,Citeseer,10000,0.709026,False,0.003617
1,diffusion,GCN,Citeseer,1,0.693874,False,0.005693
2,full,GCN,Citeseer,1,0.694183,False,0.006091
3,zero_hop,GCN,Citeseer,10000,0.630202,False,0.006743
4,adjacency,GCN,Citeseer,10000,0.665228,False,0.007105
5,adjacency,GCN,Citeseer,1,0.688982,False,0.005460
6,diffusion,GCN,Citeseer,10000,0.660517,False,0.006450
7,zero_hop,GCN,Citeseer,1,0.637077,False,0.008811
8,full,GCN,Citeseer,10000,0.707747,True,0.002133
9,diffusion,GCN,Citeseer,1,0.672830,True,0.000000
10,diffusion,GCN,Citeseer,1,0.670252,True,0.009377
11,full,GCN,Citeseer,1,0.697607,True,0.006093
12,zero_hop,GCN,Citeseer,10000,0.629163,True,0.012182
13,adjacency,GCN,Citeseer,10000,0.663376,True,0.000000
14,adjacency,GCN,Citeseer,10000,0.655510,True,0.008037
15,adjacency,GCN,Citeseer,1,0.665704,True,0.000000
16,adjacency,GCN,Citeseer,1,0.667342,True,0.008693
17,diffusion,GCN,Citeseer,10000,0.659823,True,0.000000
18,diffusion,GCN,Citeseer,10000,0.658065,True,0.011232
19,zero_hop,GCN,Citeseer,1,0.635401,True,0.006945

In [32]:
# combine the dataframes: df_cora, df_citeseer and df_pubmed
df = pd.concat([df_cora, df_citeseer, df_pubmed], ignore_index=True)
df

,data_loading_option,model_type,dataset,beta,average_client_result,use_pe,std_client
0,zero_hop,GCN,Cora,10000,0.613490,True,0.010878
1,adjacency,GCN,Cora,1,0.737552,True,0.193332
2,adjacency,GCN,Cora,10000,0.748087,True,0.008948
3,zero_hop,GCN,Cora,1,0.687031,True,0.016691
4,diffusion,GCN,Cora,10000,0.756639,True,0.007680
5,full,GCN,Cora,10000,0.802203,True,0.005133
6,diffusion,GCN,Cora,1,0.808264,True,0.006617
7,full,GCN,Cora,1,0.810446,True,0.001735
8,zero_hop,GCN,Cora,10000,0.625810,False,0.016496
9,adjacency,GCN,Cora,1,0.789962,False,0.004619
10,adjacency,GCN,Cora,10000,0.726120,False,0.005278
11,zero_hop,GCN,Cora,1,0.686265,False,0.008227
12,diffusion,GCN,Cora,10000,0.732819,False,0.007815
13,full,GCN,Cora,10000,0.803654,False,0.004212
14,diffusion,GCN,Cora,1,0.788618,False,0.008740
15,full,GCN,Cora,1,0.810089,False,0.003820
16,full,GCN,Citeseer,10000,0.709026,False,0.003617
17,diffusion,GCN,Citeseer,1,0.693874,False,0.005693
18,full,GCN,Citeseer,1,0.694183,False,0.006091
19,zero_hop,GCN,Citeseer,10000,0.630202,False,0.006743
20,adjacency,GCN,Citeseer,10000,0.665228,False,0.007105
21,adjacency,GCN,Citeseer,1,0.688982,False,0.005460
22,diffusion,GCN,Citeseer,10000,0.660517,False,0.006450
23,zero_hop,GCN,Citeseer,1,0.637077,False,0.008811
24,full,GCN,Citeseer,10000,0.707747,True,0.002133
25,diffusion,GCN,Citeseer,1,0.672830,True,0.000000
26,diffusion,GCN,Citeseer,1,0.670252,True,0.009377
27,full,GCN,Citeseer,1,0.697607,True,0.006093
28,zero_hop,GCN,Citeseer,10000,0.629163,True,0.012182
29,adjacency,GCN,Citeseer,10000,0.663376,True,0.000000
30,adjacency,GCN,Citeseer,10000,0.655510,True,0.008037
31,adjacency,GCN,Citeseer,1,0.665704,True,0.000000
32,adjacency,GCN,Citeseer,1,0.667342,True,0.008693
33,diffusion,GCN,Citeseer,10000,0.659823,True,0.000000
34,diffusion,GCN,Citeseer,10000,0.658065,True,0.011232
35,zero_hop,GCN,Citeseer,1,0.635401,True,0.006945
36,full,GCN,Pubmed,10000,0.784176,False,0.002904
37,zero_hop,GCN,Pubmed,10000,0.653125,False,0.008509
38,adjacency,GCN,Pubmed,10,0.779701,False,0.000446
39,zero_hop,GCN,Pubmed,10,0.645805,False,0.012908
40,full,GCN,Pubmed,10,0.795334,False,0.007189
41,diffusion,GCN,Pubmed,10,0.781134,False,0.005931
42,diffusion,GCN,Pubmed,10000,0.792203,False,0.003282
43,adjacency,GCN,Pubmed,10000,0.793614,False,0.003996
44,full,GCN,Pubmed,10000,0.786222,True,0.005237
45,zero_hop,GCN,Pubmed,10000,0.647367,True,0.011396
46,adjacency,GCN,Pubmed,10,0.761056,True,0.005078
47,zero_hop,GCN,Pubmed,10,0.655896,True,0.009144
48,full,GCN,Pubmed,10,0.795168,True,0.003688
49,diffusion,GCN,Pubmed,10,0.764270,True,0.005372
50,diffusion,GCN,Pubmed,10000,0.768603,True,0.005833
51,adjacency,GCN,Pubmed,10000,0.772679,True,0.009039

In [34]:
# save df as a csv
output_path = "/home/brian_bosho/FP/FP/federated-gnn/results/combined_results_final.csv"
df.to_csv(output_path, index=False)

### Cora Training analysis

In [14]:
# cora_gcn_pe_path = "/home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh"
cora_gcn_beta10000_no_pe_nzh =  "/home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh"
cora_gcn_beta1_no_pe_nzh = "/home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh"
cora_gcn_pe_beta10000_nzh = "/home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh"
cora_gcn_pe_beta1_nzh = "/home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh"
cora_gcn_zh_no_pe = "/home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final"
cora_gcn_zh_pe = "/home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe"

In [15]:
cora_gcn_zh_no_pe = process_results_folder_json(cora_gcn_zh_no_pe)
cora_gcn_zh_pe = process_results_folder_json(cora_gcn_zh_pe)

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final/Cora_zero_hop_GCN_beta10000_clients10/results_Cora_zero_hop_GCN_beta10000_clients10_20250730_101930.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final/propagation_stats/prop_exp_20250730-110147_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final/propagation_stats/prop_exp_20250730-110147_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final/Cora_zero_hop_GCN_beta1_clients10/results_Cora_zero_hop_GCN_beta1_clients10_20250730_092518.json
INFO: Successfully created DataFrame with 2 rows.
INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe/Cora_zero_hop_GCN_beta10000_clients10/results_Cora_zero_hop_GCN_beta10000_clients10_20250730_100330.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-105433_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-105433_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-104200_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-104200_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-104754_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-104754_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-110834_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-110834_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-110145_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe/propagation_stats/prop_exp_20250730-110145_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/cora_gcn_final_pe/Cora_zero_hop_GCN_beta1_clients10/results_Cora_zero_hop_GCN_beta1_clients10_20250730_090916.json
INFO: Successfully created DataFrame with 2 rows.

In [10]:
df_cora_gcn_beta10000_no_pe_nzh

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id
0,cuda,adjacency,GCN,Cora,10,10000,1,False,"[0.795, 0.791, 0.781, 0.78, 0.789, 0.789, 0.79...","[0.7355113242882227, 0.7227902595738103, 0.721...",0.7857,0.726120,0.005460,0.005278,results_Cora_adjacency_GCN_beta10000_clients10...
1,cuda,diffusion,GCN,Cora,10,10000,1,False,"[0.791, 0.792, 0.788, 0.783, 0.796, 0.793, 0.7...","[0.7409296424039813, 0.7497307879497169, 0.725...",0.7910,0.732819,0.005040,0.007815,results_Cora_diffusion_GCN_beta10000_clients10...
2,cuda,full,GCN,Cora,10,10000,1,False,"[0.817, 0.811, 0.809, 0.817, 0.818, 0.81, 0.81...","[0.8039834247444404, 0.8030939862942035, 0.800...",0.8121,0.803654,0.006172,0.004212,results_Cora_full_GCN_beta10000_clients10_2025...

In [11]:
df_cora_gcn_beta1_no_pe_nzh

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id
0,cuda,adjacency,GCN,Cora,10,1,1,False,"[0.822, 0.794, 0.804, 0.808, 0.798, 0.813, 0.7...","[0.7965100921345902, 0.7840048781476988, 0.791...",0.803900,0.789962,0.008780,0.004619,results_Cora_adjacency_GCN_beta1_clients10_202...
1,cuda,diffusion,GCN,Cora,10,1,1,False,"[0.797, 0.811, 0.797, 0.793, 0.802, 0.793, 0.7...","[0.779315082787234, 0.7894729067152236, 0.8019...",0.799800,0.788618,0.005776,0.008740,results_Cora_diffusion_GCN_beta1_clients10_202...
2,cuda,full,GCN,Cora,10,1,1,False,"[0.804, 0.803, 0.808, 0.815, 0.814, 0.812, 0.8...","[0.8066407470248992, 0.8072586519224959, 0.803...",0.810222,0.810089,0.004211,0.003820,results_Cora_full_GCN_beta1_clients10_20250730...

In [12]:
df_cora_gcn_pe_beta10000_nzh

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id
0,cuda,adjacency,GCN,Cora,10,10000,1,False,"[0.79, 0.792, 0.794, 0.798, 0.799, 0.804, 0.79...","[0.74288381700342, 0.7354451525942126, 0.74279...",0.795900,0.748087,0.005612,0.008948,results_Cora_adjacency_GCN_beta10000_clients10...
1,cuda,diffusion,GCN,Cora,10,10000,1,False,"[0.805, 0.786, 0.798, 0.802, 0.779, 0.792, 0.7...","[0.7681693076135729, 0.7501767394637466, 0.758...",0.793600,0.756639,0.009604,0.007680,results_Cora_diffusion_GCN_beta10000_clients10...
2,cuda,full,GCN,Cora,10,10000,1,False,"[0.813, 0.816, 0.807, 0.81, 0.82, 0.815, 0.817...","[0.8084585426219777, 0.8049957492678637, 0.795...",0.813444,0.802203,0.003919,0.005133,results_Cora_full_GCN_beta10000_clients10_2025...

In [13]:
df_cora_gcn_pe_beta1_nzh

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id
0,cuda,adjacency,GCN,Cora,10,1,1,False,"[0.812, 0.144, 0.797, 0.821, 0.812, 0.811, 0.8...","[0.8040941602066501, 0.1578069885807677, 0.805...",0.7435,0.737552,0.200051,0.193332,results_Cora_adjacency_GCN_beta1_clients10_202...
1,cuda,diffusion,GCN,Cora,10,1,1,False,"[0.809, 0.809, 0.801, 0.823, 0.801, 0.814, 0.8...","[0.8134162745758482, 0.8008913461351594, 0.809...",0.8126,0.808264,0.008114,0.006617,results_Cora_diffusion_GCN_beta1_clients10_202...
2,cuda,full,GCN,Cora,10,1,1,False,"[0.814, 0.809]","[0.8121815244729327, 0.8087107586129413]",0.8115,0.810446,0.002500,0.001735,results_Cora_full_GCN_beta1_clients10_20250730...

In [9]:
df_cora_gcn_beta10000_no_pe_nzh = process_results_folder_json(cora_gcn_beta10000_no_pe_nzh)
df_cora_gcn_beta1_no_pe_nzh = process_results_folder_json(cora_gcn_beta1_no_pe_nzh)
df_cora_gcn_pe_beta10000_nzh = process_results_folder_json(cora_gcn_pe_beta10000_nzh)
df_cora_gcn_pe_beta1_nzh = process_results_folder_json(cora_gcn_pe_beta1_nzh)

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-122155_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-122155_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-114658_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-114658_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-121308_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-121308_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-115751_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-115751_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-115445_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-115445_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-122805_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-122805_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-122512_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-122512_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-101753_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-101753_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-120054_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-120054_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-100514_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-100514_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-120658_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-120658_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-095555_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-095555_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-095904_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-095904_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-121606_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-121606_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-123340_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-123340_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-113729_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-113729_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-114102_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-114102_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-120955_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-120955_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-100802_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-100802_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-100152_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-100152_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-121853_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-121853_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-115220_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-115220_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-120341_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-120341_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-101153_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-101153_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-123039_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-123039_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-114928_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-114928_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-114349_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-114349_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-101429_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/propagation_stats/prop_exp_20250801-101429_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/Cora_adjacency_GCN_beta10000_clients10/results_Cora_adjacency_GCN_beta10000_clients10_20250801_113724.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/Cora_diffusion_GCN_beta10000_clients10/results_Cora_diffusion_GCN_beta10000_clients10_20250801_120654.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta10000_no_pe_nzh/Cora_full_GCN_beta10000_clients10/results_Cora_full_GCN_beta10000_clients10_20250801_123620.json
INFO: Successfully created DataFrame with 3 rows.
INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/Cora_adjacency_GCN_beta1_clients10/results_Cora_adjacency_GCN_beta1_clients10_20250730_172626.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-190440_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-190440_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-183524_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-183524_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-185649_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-185649_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-180428_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-180428_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-173255_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-173255_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-183021_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-183021_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-182006_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-182006_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-174655_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-174655_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-183952_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-183952_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-172635_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-172635_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-175216_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-175216_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-180959_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-180959_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-175821_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-175821_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-184420_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-184420_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-181441_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-181441_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-184912_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-184912_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-190049_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-190049_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-173916_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-173916_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-185310_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-185310_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-182514_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-182514_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/Cora_diffusion_GCN_beta1_clients10/results_Cora_diffusion_GCN_beta1_clients10_20250730_182509.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/Cora_full_GCN_beta1_clients10/results_Cora_full_GCN_beta1_clients10_20250730_190820.json
INFO: Successfully created DataFrame with 3 rows.
INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-122702_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-122702_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-124000_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-124000_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-113732_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-113732_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-130102_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-130102_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-130700_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-130700_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-123311_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-123311_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-115651_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta10000_nzh/propagation_stats/prop_exp_20250801-115651_adjacency_beta_10000_hop_1.json

In [6]:
df_cora_gcn_pe = process_results_folder_json(cora_gcn_pe_path)
df_cora_gcn_pe

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/Cora_adjacency_GCN_beta1_clients10/results_Cora_adjacency_GCN_beta1_clients10_20250730_172626.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-175701_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-175701_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-195156_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-195156_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-174143_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-174143_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-182044_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-182044_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-194542_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-194542_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-174111_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-174111_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-191336_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-191336_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-192230_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-192230_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-193027_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-193027_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-201022_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-201022_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-193929_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-193929_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-195722_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-195722_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-183035_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-183035_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-172635_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-172635_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-185047_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-185047_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-184109_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-184109_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-181021_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-181021_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-185819_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-185819_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-200348_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-200348_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-190536_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/propagation_stats/prop_exp_20250730-190536_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/Cora_diffusion_GCN_beta1_clients10/results_Cora_diffusion_GCN_beta1_clients10_20250730_190533.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_pe_beta1_nzh/Cora_full_GCN_beta1_clients10/results_Cora_full_GCN_beta1_clients10_20250730_202007.json
INFO: Successfully created DataFrame with 3 rows.

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id
0,cuda,adjacency,GCN,Cora,10,1,1,False,"[0.812, 0.144, 0.797, 0.821, 0.812, 0.811, 0.8...","[0.8040941602066501, 0.1578069885807677, 0.805...",0.7435,0.737552,0.200051,0.193332,results_Cora_adjacency_GCN_beta1_clients10_202...
1,cuda,diffusion,GCN,Cora,10,1,1,False,"[0.809, 0.809, 0.801, 0.823, 0.801, 0.814, 0.8...","[0.8134162745758482, 0.8008913461351594, 0.809...",0.8126,0.808264,0.008114,0.006617,results_Cora_diffusion_GCN_beta1_clients10_202...
2,cuda,full,GCN,Cora,10,1,1,False,"[0.814, 0.809]","[0.8121815244729327, 0.8087107586129413]",0.8115,0.810446,0.002500,0.001735,results_Cora_full_GCN_beta1_clients10_20250730...

In [7]:
cora_gcn_no_pe_path = "/home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh"
df_cora_gcn_no_pe = process_results_folder_json(cora_gcn_no_pe_path)
df_cora_gcn_no_pe

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/Cora_adjacency_GCN_beta1_clients10/results_Cora_adjacency_GCN_beta1_clients10_20250730_172626.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-190440_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-190440_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-183524_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-183524_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-185649_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-185649_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-180428_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-180428_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-173255_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-173255_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-183021_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-183021_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-182006_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-182006_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-174655_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-174655_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-183952_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-183952_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-172635_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-172635_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-175216_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-175216_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-180959_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-180959_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-175821_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-175821_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-184420_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-184420_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-181441_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-181441_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-184912_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-184912_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-190049_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-190049_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-173916_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-173916_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-185310_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-185310_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-182514_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/propagation_stats/prop_exp_20250730-182514_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/Cora_diffusion_GCN_beta1_clients10/results_Cora_diffusion_GCN_beta1_clients10_20250730_182509.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/cora_gcn_beta1_no_pe_nzh/Cora_full_GCN_beta1_clients10/results_Cora_full_GCN_beta1_clients10_20250730_190820.json
INFO: Successfully created DataFrame with 3 rows.

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id
0,cuda,adjacency,GCN,Cora,10,1,1,False,"[0.822, 0.794, 0.804, 0.808, 0.798, 0.813, 0.7...","[0.7965100921345902, 0.7840048781476988, 0.791...",0.803900,0.789962,0.008780,0.004619,results_Cora_adjacency_GCN_beta1_clients10_202...
1,cuda,diffusion,GCN,Cora,10,1,1,False,"[0.797, 0.811, 0.797, 0.793, 0.802, 0.793, 0.7...","[0.779315082787234, 0.7894729067152236, 0.8019...",0.799800,0.788618,0.005776,0.008740,results_Cora_diffusion_GCN_beta1_clients10_202...
2,cuda,full,GCN,Cora,10,1,1,False,"[0.804, 0.803, 0.808, 0.815, 0.814, 0.812, 0.8...","[0.8066407470248992, 0.8072586519224959, 0.803...",0.810222,0.810089,0.004211,0.003820,results_Cora_full_GCN_beta1_clients10_20250730...

### Citeseer Hyperparams

In [13]:
citeseer_gcn_no_pe = "/home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe"
df_citeseer_gcn_no_pe = process_results_folder_json(citeseer_gcn_no_pe)
df_citeseer_gcn_no_pe

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/Citeseer_diffusion_GCN_beta1_clients10/results_Citeseer_diffusion_GCN_beta1_clients10_20250730_102313.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/Citeseer_zero_hop_GCN_beta10000_clients10/results_Citeseer_zero_hop_GCN_beta10000_clients10_20250730_092607.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/Citeseer_adjacency_GCN_beta10000_clients10/results_Citeseer_adjacency_GCN_beta10000_clients10_20250730_100602.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/Citeseer_adjacency_GCN_beta1_clients10/results_Citeseer_adjacency_GCN_beta1_clients10_20250730_094444.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-103045_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-103045_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-102319_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-102319_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-101633_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-101633_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-103449_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-103449_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-105526_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-105526_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-102853_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-102853_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-100918_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-100918_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-104933_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-104933_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-095923_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-095923_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-110123_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-110123_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-101822_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-101822_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-104754_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-104754_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-103708_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-103708_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-095513_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-095513_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-095319_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-095319_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-095714_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-095714_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-101111_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-101111_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-095123_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-095123_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-094736_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-094736_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-094940_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-094940_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-104143_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-104143_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-100608_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-100608_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-105134_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-105134_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-100155_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-100155_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-103230_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-103230_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-104639_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-104639_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-100748_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-100748_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-105724_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-105724_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-103910_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-103910_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-100407_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-100407_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-105318_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-105318_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-102140_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-102140_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-101518_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-101518_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-094450_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-094450_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-101324_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-101324_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-110335_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-110335_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-102613_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-102613_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-104403_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-104403_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-105921_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-105921_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-102001_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/propagation_stats/prop_exp_20250730-102001_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/Citeseer_diffusion_GCN_beta10000_clients10/results_Citeseer_diffusion_GCN_beta10000_clients10_20250730_104634.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_no_pe/Citeseer_zero_hop_GCN_beta1_clients10/results_Citeseer_zero_hop_GCN_beta1_clients10_20250730_090916.json
INFO: Successfully created DataFrame with 6 rows.

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id
0,cuda,diffusion,GCN,Citeseer,10,1,1,False,"[0.705, 0.7, 0.71, 0.71, 0.716, 0.711, 0.712, ...","[0.6918816278737333, 0.6817554877813852, 0.695...",0.709000,0.693874,0.004313,0.005693,results_Citeseer_diffusion_GCN_beta1_clients10...
1,cuda,zero_hop,GCN,Citeseer,10,10000,1,False,"[0.698, 0.693, 0.694, 0.695, 0.693, 0.694, 0.6...","[0.6370812482157587, 0.6400242182277399, 0.628...",0.692700,0.630202,0.004880,0.006743,results_Citeseer_zero_hop_GCN_beta10000_client...
2,cuda,adjacency,GCN,Citeseer,10,10000,1,False,"[0.703, 0.702, 0.697, 0.699, 0.687, 0.698, 0.6...","[0.6751090277419792, 0.6658915169344064, 0.663...",0.696600,0.665228,0.005426,0.007105,results_Citeseer_adjacency_GCN_beta10000_clien...
3,cuda,adjacency,GCN,Citeseer,10,1,1,False,"[0.706, 0.713, 0.707, 0.703, 0.709, 0.704, 0.7...","[0.6827637016346125, 0.6954366404174741, 0.689...",0.705900,0.688982,0.003618,0.005460,results_Citeseer_adjacency_GCN_beta1_clients10...
4,cuda,diffusion,GCN,Citeseer,10,10000,1,False,"[0.689, 0.68, 0.694, 0.699, 0.701, 0.695, 0.69...","[0.6568782948341426, 0.6496332452113072, 0.652...",0.694444,0.660517,0.006202,0.006450,results_Citeseer_diffusion_GCN_beta10000_clien...
5,cuda,zero_hop,GCN,Citeseer,10,1,1,False,"[0.685, 0.682, 0.673, 0.687, 0.677, 0.696, 0.6...","[0.6283491135530416, 0.6328829148191576, 0.623...",0.688900,0.637077,0.009115,0.008811,results_Citeseer_zero_hop_GCN_beta1_clients10_...

In [15]:
citeseer_gcn_pe_path = "/home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe"
df_citeseer_gcn_pe = process_results_folder_json(citeseer_gcn_pe_path)
df_citeseer_gcn_pe

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/Citeseer_diffusion_GCN_beta1_clients10/results_Citeseer_diffusion_GCN_beta1_clients10_20250730_103827.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/Citeseer_zero_hop_GCN_beta10000_clients10/results_Citeseer_zero_hop_GCN_beta10000_clients10_20250730_092955.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/Citeseer_adjacency_GCN_beta10000_clients10/results_Citeseer_adjacency_GCN_beta10000_clients10_20250730_100215.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/Citeseer_adjacency_GCN_beta1_clients10/results_Citeseer_adjacency_GCN_beta1_clients10_20250730_094658.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-094704_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-094704_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-105240_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-105240_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095332_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095332_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095638_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095638_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-094842_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-094842_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-102044_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-102044_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-101640_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-101640_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-104358_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-104358_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-102236_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-102236_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-103304_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-103304_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-100930_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-100930_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095824_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095824_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-103951_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-103951_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-103028_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-103028_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-110713_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-110713_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-103832_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-103832_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095944_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095944_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-111143_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-111143_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-100221_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-100221_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-105121_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-105121_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-101221_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-101221_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-104933_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-104933_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-104159_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-104159_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-105434_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-105434_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-110447_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-110447_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-104724_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-104724_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-105923_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-105923_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-102759_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-102759_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095211_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095211_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095446_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095446_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-104532_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-104532_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-100102_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-100102_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095029_adjacency_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-095029_adjacency_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-103502_adjacency_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-103502_adjacency_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-111550_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-111550_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-104756_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-104756_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results_exp1/citeseer_ablation_final_pe/Citeseer_zero_hop_GCN_beta1_clients10/results_Citeseer_zero_hop_GCN_beta1_clients10_20250730_090916.json
INFO: Successfully created DataFrame with 5 rows.

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id
0,cuda,diffusion,GCN,Citeseer,10,1,1,False,"[0.245, 0.254, 0.235, 0.251, 0.277, 0.232, 0.2...","[0.2467812478977744, 0.2584031199049428, 0.235...",0.248222,0.251867,0.015490,0.017194,results_Citeseer_diffusion_GCN_beta1_clients10...
1,cuda,zero_hop,GCN,Citeseer,10,10000,1,False,"[0.68, 0.695, 0.694, 0.703, 0.672, 0.708, 0.69...","[0.6158200033756078, 0.632877454261015, 0.6207...",0.692900,0.629163,0.009904,0.012182,results_Citeseer_zero_hop_GCN_beta10000_client...
2,cuda,adjacency,GCN,Citeseer,10,10000,1,False,"[0.352, 0.267, 0.345, 0.251, 0.366, 0.319, 0.3...","[0.4406023473385159, 0.3886781330591257, 0.434...",0.323500,0.424004,0.035853,0.037339,results_Citeseer_adjacency_GCN_beta10000_clien...
3,cuda,adjacency,GCN,Citeseer,10,1,1,False,"[0.251, 0.246, 0.257, 0.232, 0.232, 0.235, 0.2...","[0.2560829547941862, 0.2506218261516146, 0.260...",0.238300,0.237208,0.008922,0.012325,results_Citeseer_adjacency_GCN_beta1_clients10...
4,cuda,zero_hop,GCN,Citeseer,10,1,1,False,"[0.688, 0.695, 0.701, 0.686, 0.691, 0.679, 0.6...","[0.6451203811738717, 0.6399981390820348, 0.647...",0.690700,0.635401,0.005832,0.006945,results_Citeseer_zero_hop_GCN_beta1_clients10_...

In [9]:
cs_2_path = "/home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe"

In [10]:
cs_3_path = "/home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_no_pe"

In [11]:
cs2_df = process_results_folder_json(cs_2_path)
cs2_df

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/Citeseer_full_GCN_beta10000_clients10/results_Citeseer_full_GCN_beta10000_clients10_20250730_183022.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/Citeseer_diffusion_GCN_beta1_clients10/results_Citeseer_diffusion_GCN_beta1_clients10_20250730_172626.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/Citeseer_full_GCN_beta1_clients10/results_Citeseer_full_GCN_beta1_clients10_20250730_181557.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-174225_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-174225_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-180232_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-180232_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-174917_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-174917_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-174107_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-174107_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-173553_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-173553_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-180638_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-180638_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-175218_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-175218_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-173224_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-173224_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-173909_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-173909_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-174346_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-174346_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-175853_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-175853_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-175355_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-175355_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-173418_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-173418_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-181119_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-181119_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-174824_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-174824_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-180822_diffusion_beta_10000_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-180822_diffusion_beta_10000_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-173736_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-173736_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-173021_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-173021_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-172635_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-172635_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-172834_diffusion_beta_1_hop_1.json
WARNING: Missing keys in: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/propagation_stats/prop_exp_20250730-172834_diffusion_beta_1_hop_1.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_pe/Citeseer_diffusion_GCN_beta10000_clients10/results_Citeseer_diffusion_GCN_beta10000_clients10_20250730_174340.json
INFO: Successfully created DataFrame with 4 rows.

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id
0,cuda,full,GCN,Citeseer,10,10000,1,False,"[0.711, 0.715, 0.714, 0.711, 0.713, 0.712, 0.7...","[0.7102733533576991, 0.7103590972731836, 0.705...",0.7127,0.707747,0.002492,0.002133,results_Citeseer_full_GCN_beta10000_clients10_...
1,cuda,diffusion,GCN,Citeseer,10,1,1,False,"[0.269, 0.245, 0.232, 0.237, 0.243, 0.252, 0.2...","[0.27711965399189276, 0.2546792167090538, 0.22...",0.2445,0.249051,0.012769,0.015787,results_Citeseer_diffusion_GCN_beta1_clients10...
2,cuda,full,GCN,Citeseer,10,1,1,False,"[0.709, 0.711, 0.716, 0.707, 0.708, 0.706, 0.7...","[0.7037613628501868, 0.6988745039908, 0.706218...",0.7117,0.697607,0.005951,0.006093,results_Citeseer_full_GCN_beta1_clients10_2025...
3,cuda,diffusion,GCN,Citeseer,10,10000,1,False,"[0.395, 0.28, 0.401, 0.409, 0.421, 0.419, 0.37...","[0.45688140039093356, 0.3901622388665782, 0.47...",0.3802,0.454485,0.040602,0.027867,results_Citeseer_diffusion_GCN_beta10000_clien...

In [12]:
cs_3_df = process_results_folder_json(cs_3_path)
cs_3_df

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_no_pe
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_no_pe/Citeseer_full_GCN_beta10000_clients10/results_Citeseer_full_GCN_beta10000_clients10_20250730_174615.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/citeseer_ablation_final_no_pe/Citeseer_full_GCN_beta1_clients10/results_Citeseer_full_GCN_beta1_clients10_20250730_172626.json
INFO: Successfully created DataFrame with 2 rows.

,device,data_loading_option,model_type,dataset,num_clients,beta,hop,fulltraining_flag,global_results,client_results,average_global_result,average_client_result,std_global,std_client,experiment_id
0,cuda,full,GCN,Citeseer,10,10000,1,False,"[0.713, 0.717, 0.708, 0.714, 0.712, 0.711, 0.7...","[0.711392605564596, 0.7130019847926208, 0.7052...",0.7140,0.709026,0.003768,0.003617,results_Citeseer_full_GCN_beta10000_clients10_...
1,cuda,full,GCN,Citeseer,10,1,1,False,"[0.702, 0.711, 0.715, 0.714, 0.708, 0.714, 0.7...","[0.6876990757266757, 0.6941391252478837, 0.696...",0.7089,0.694183,0.004504,0.006091,results_Citeseer_full_GCN_beta1_clients10_2025...

### Cora Hyperparameter Analysis

In [4]:
results_df = process_results_folder_json_v2(path)

print(results_df.head())

INFO: Scanning folder: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_183835.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191356.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191625.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_162754.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_181402.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_162517.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_161231.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_155441.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_190745.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_122404.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_133353.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_134201.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_143015.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_142510.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_160958.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_155948.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_181315.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_143754.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_151903.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_163544.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_183954.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_140455.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_181233.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_155208.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_190823.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_151358.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_153419.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_123433.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_134432.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_135718.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_132344.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_190904.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191018.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_142742.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_173301.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_134938.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191510.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_162010.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_144533.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_160725.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_160452.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_152642.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_155714.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_181439.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_134707.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_184031.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_141001.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_144028.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_135212.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_142239.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_152133.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_163029.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_131605.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_133927.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_132617.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_145605.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_120449.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_153651.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_173537.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_160219.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_145838.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_153146.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_142005.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_163306.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191433.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_190940.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_144806.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_162242.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_141506.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_143520.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_150112.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_152408.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_132848.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_181111.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_125547.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_135949.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_183917.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_145038.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_185434.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_185548.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_150345.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_151123.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_145332.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_133653.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_124510.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_161737.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_132111.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_185511.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_144301.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191547.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_152913.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_181150.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_154157.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_140224.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_154430.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_133120.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_154703.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_141736.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_161504.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_130628.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_191319.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_184109.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_163818.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_153924.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_131837.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_143248.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_141235.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250724_183758.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_154936.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_150852.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_140729.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_150619.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_151629.json
INFO: Reading: /home/brian_bosho/FP/FP/federated-gnn/results/results_summary/cora_baseline/summary_results_20250728_135445.json
INFO: Successfully created DataFrame with 126 rows.

  datasets data_loading models num_clients  num_rounds  epochs optimizer  \
0   [Cora]         full  [GCN]         [5]          10       3       SGD
1   [Cora]         full  [GCN]         [5]          10       3       SGD
2   [Cora]         full  [GCN]         [5]          10       3       SGD
3   [Cora]         full  [GCN]        [10]         200       3       SGD
4   [Cora]         full  [GCN]         [5]          10       3       SGD

    decay   beta   lr  ... dataset  model  clients  avg_global avg_client  \
0  0.0005      2  0.5  ...    Cora    GCN        5      0.7205   0.637037
1  0.0005      2  0.5  ...    Cora    GCN        5      0.6695   0.589532
2  0.0005      2  0.5  ...    Cora    GCN        5      0.6910   0.582748
3  0.0005  10000  0.5  ...    Cora    GCN       10      0.5890   0.576767
4  0.0005      2  0.5  ...    Cora    GCN        5      0.7250   0.615251

   client_std_dev  global_std_dev  \
0        0.009378          0.0185
1        0.007439          0.0125
2        0.004423          0.0190
3        0.000000          0.0000
4        0.022996          0.0190

                                            duration  \
0  {'seconds': 31.198800086975098, 'formatted': '...
1  {'seconds': 30.553484201431274, 'formatted': '...
2  {'seconds': 30.64890718460083, 'formatted': '0...
3  {'seconds': 145.6281223297119, 'formatted': '0...
4  {'seconds': 35.39778208732605, 'formatted': '0...

                     experiment_id        timestamp
0  summary_results_20250724_183835  20250724_183835
1  summary_results_20250724_191356  20250724_191356
2  summary_results_20250724_191625  20250724_191625
3  summary_results_20250728_162754  20250728_162754
4  summary_results_20250724_181402  20250724_181402

[5 rows x 28 columns]

In [5]:
results_df

,datasets,data_loading,models,num_clients,num_rounds,epochs,optimizer,decay,beta,lr,...,dataset,model,clients,avg_global,avg_client,client_std_dev,global_std_dev,duration,experiment_id,timestamp
0,[Cora],full,[GCN],[5],10,3,SGD,0.0005,2,0.5,...,Cora,GCN,5,0.7205,0.637037,0.009378,0.0185,"{'seconds': 31.198800086975098, 'formatted': '...",summary_results_20250724_183835,20250724_183835
1,[Cora],full,[GCN],[5],10,3,SGD,0.0005,2,0.5,...,Cora,GCN,5,0.6695,0.589532,0.007439,0.0125,"{'seconds': 30.553484201431274, 'formatted': '...",summary_results_20250724_191356,20250724_191356
2,[Cora],full,[GCN],[5],10,3,SGD,0.0005,2,0.5,...,Cora,GCN,5,0.6910,0.582748,0.004423,0.0190,"{'seconds': 30.64890718460083, 'formatted': '0...",summary_results_20250724_191625,20250724_191625
3,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.5890,0.576767,0.000000,0.0000,"{'seconds': 145.6281223297119, 'formatted': '0...",summary_results_20250728_162754,20250728_162754
4,[Cora],full,[GCN],[5],10,3,SGD,0.0005,2,0.5,...,Cora,GCN,5,0.7250,0.615251,0.022996,0.0190,"{'seconds': 35.39778208732605, 'formatted': '0...",summary_results_20250724_181402,20250724_181402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.8070,0.798116,0.000000,0.0000,"{'seconds': 144.76601815223694, 'formatted': '...",summary_results_20250728_150852,20250728_150852
122,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.7940,0.783298,0.000000,0.0000,"{'seconds': 142.51317310333252, 'formatted': '...",summary_results_20250728_140729,20250728_140729
123,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.3930,0.377304,0.000000,0.0000,"{'seconds': 144.6793773174286, 'formatted': '0...",summary_results_20250728_150619,20250728_150619
124,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.1760,0.178277,0.000000,0.0000,"{'seconds': 143.12395668029785, 'formatted': '...",summary_results_20250728_151629,20250728_151629
125,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.1600,0.159314,0.000000,0.0000,"{'seconds': 144.31446504592896, 'formatted': '...",summary_results_20250728_135445,20250728_135445

In [6]:
# sort by avg_client
results_df = results_df.sort_values(by='avg_client', ascending=False)

In [7]:
results_df

,datasets,data_loading,models,num_clients,num_rounds,epochs,optimizer,decay,beta,lr,...,dataset,model,clients,avg_global,avg_client,client_std_dev,global_std_dev,duration,experiment_id,timestamp
74,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.8180,0.808741,0.000000,0.0000,"{'seconds': 141.59555459022522, 'formatted': '...",summary_results_20250728_141506,20250728_141506
63,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.8140,0.807842,0.000000,0.0000,"{'seconds': 143.61564779281616, 'formatted': '...",summary_results_20250728_153651,20250728_153651
29,[Cora],full,[GCN],[10],300,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.8110,0.804736,0.000000,0.0000,"{'seconds': 208.4695909023285, 'formatted': '0...",summary_results_20250728_123433,20250728_123433
85,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.8140,0.803680,0.000000,0.0000,"{'seconds': 142.58982300758362, 'formatted': '...",summary_results_20250728_145038,20250728_145038
59,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.8120,0.802066,0.000000,0.0000,"{'seconds': 143.18678092956543, 'formatted': '...",summary_results_20250728_145605,20250728_145605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.1450,0.140349,0.000000,0.0000,"{'seconds': 146.45219230651855, 'formatted': '...",summary_results_20250728_163306,20250728_163306
75,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.1250,0.112719,0.000000,0.0000,"{'seconds': 142.4726321697235, 'formatted': '0...",summary_results_20250728_143520,20250728_143520
46,[Cora],full,[GCN],[10],200,3,SGD,0.0005,10000,0.5,...,Cora,GCN,10,0.1040,0.111821,0.000000,0.0000,"{'seconds': 144.33225393295288, 'formatted': '...",summary_results_20250728_155714,20250728_155714
112,[Cora],full,[GCN],[5],10,3,SGD,0.0005,2,0.5,...,Cora,GCN,5,0.1075,0.102632,0.006824,0.0055,"{'seconds': 30.26354146003723, 'formatted': '0...",summary_results_20250724_191319,20250724_191319
38,[Pubmed],None,[GCN],[5],10,3,SGD,0.0005,2,0.5,...,Pubmed,GCN,5,NaN,NaN,NaN,NaN,"{'seconds': 6.137397527694702, 'formatted': '0...",summary_results_20250724_173301,20250724_173301

In [8]:
results_df.columns

Index(['datasets', 'data_loading', 'models', 'num_clients', 'num_rounds',
       'epochs', 'optimizer', 'decay', 'beta', 'lr', 'results_dir',
       'save_results', 'hop', 'fulltraining_flag', 'use_pe', 'pe_r', 'pe_P',
       'normalize', 'dataset', 'model', 'clients', 'avg_global', 'avg_client',
       'client_std_dev', 'global_std_dev', 'duration', 'experiment_id',
       'timestamp'],
      dtype='object')

In [9]:
# lets keep only: decay, optimizer, beta, lr, avg client, 
results = results_df[['decay', 'optimizer', 'beta', 'lr', 'avg_client']]

In [11]:
# lets reset results index
results = results.reset_index(drop=True)
results

      decay optimizer   beta   lr  avg_client
0    0.0005       SGD  10000  0.5    0.808741
1    0.0005       SGD  10000  0.5    0.807842
2    0.0005       SGD  10000  0.5    0.804736
3    0.0005       SGD  10000  0.5    0.803680
4    0.0005       SGD  10000  0.5    0.802066
..      ...       ...    ...  ...         ...
121  0.0005       SGD  10000  0.5    0.140349
122  0.0005       SGD  10000  0.5    0.112719
123  0.0005       SGD  10000  0.5    0.111821
124  0.0005       SGD      2  0.5    0.102632
125  0.0005       SGD      2  0.5         NaN

[126 rows x 5 columns]

In [14]:
results.head(50)

     decay optimizer   beta   lr  avg_client
0   0.0005       SGD  10000  0.5    0.808741
1   0.0005       SGD  10000  0.5    0.807842
2   0.0005       SGD  10000  0.5    0.804736
3   0.0005       SGD  10000  0.5    0.803680
4   0.0005       SGD  10000  0.5    0.802066
5   0.0005       SGD  10000  0.5    0.801395
6   0.0005       SGD  10000  0.5    0.801110
7   0.0005       SGD  10000  0.5    0.800961
8   0.0005       SGD  10000  0.5    0.800582
9   0.0005       SGD  10000  0.5    0.800326
10  0.0005       SGD  10000  0.5    0.799644
11  0.0005       SGD  10000  0.5    0.799507
12  0.0005       SGD  10000  0.5    0.798627
13  0.0005       SGD  10000  0.5    0.798116
14  0.0005       SGD  10000  0.5    0.798094
15  0.0005       SGD  10000  0.5    0.796218
16  0.0005       SGD  10000  0.5    0.795664
17  0.0005       SGD  10000  0.5    0.795302
18  0.0005       SGD  10000  0.5    0.793517
19  0.0005       SGD  10000  0.5    0.792695
20  0.0005       SGD  10000  0.5    0.792528
21  0.0005       SGD  10000  0.5    0.792497
22  0.0005       SGD  10000  0.5    0.792332
23  0.0005       SGD  10000  0.5    0.791830
24  0.0005       SGD     10  0.5    0.786972
25  0.0005       SGD  10000  0.5    0.786180
26  0.0005       SGD  10000  0.5    0.783298
27  0.0005       SGD  10000  0.5    0.781992
28  0.0005       SGD  10000  0.5    0.779720
29  0.0005       SGD  10000  0.5    0.779611
30  0.0005       SGD  10000  0.5    0.778264
31  0.0005       SGD  10000  0.5    0.777297
32  0.0005       SGD     10  0.5    0.773501
33  0.0005       SGD  10000  0.5    0.771680
34  0.0005       SGD  10000  0.5    0.769198
35  0.0005       SGD  10000  0.5    0.768518
36  0.0005       SGD  10000  0.5    0.768269
37  0.0005       SGD      1  0.5    0.768047
38  0.0005       SGD  10000  0.5    0.767089
39  0.0005       SGD  10000  0.5    0.765940
40  0.0005       SGD  10000  0.5    0.765590
41  0.0005       SGD  10000  0.5    0.763141
42  0.0005       SGD  10000  0.5    0.761710
43  0.0005       SGD  10000  0.5    0.761371
44  0.0005       SGD  10000  0.5    0.760208
45  0.0005       SGD      1  0.5    0.755385
46  0.0005       SGD  10000  0.5    0.747552
47  0.0005       SGD  10000  0.5    0.745621
48  0.0005       SGD  10000  0.5    0.743739
49  0.0005       SGD  10000  0.5    0.741447

In [ ]:
# Merge all DataFrames into one comprehensive DataFrame
import pandas as pd

# First, add identifier columns to each DataFrame to distinguish configurations
dataframes_to_merge = []

# Cora experiments
if 'df_cora_gcn_beta10000_no_pe_nzh' in locals():
    df_temp = df_cora_gcn_beta10000_no_pe_nzh.copy()
    df_temp['dataset'] = 'cora'
    df_temp['beta'] = 10000
    df_temp['positional_encoding'] = False
    df_temp['hop_type'] = 'non_zero_hop'
    dataframes_to_merge.append(df_temp)

if 'df_cora_gcn_beta1_no_pe_nzh' in locals():
    df_temp = df_cora_gcn_beta1_no_pe_nzh.copy()
    df_temp['dataset'] = 'cora'
    df_temp['beta'] = 1
    df_temp['positional_encoding'] = False
    df_temp['hop_type'] = 'non_zero_hop'
    dataframes_to_merge.append(df_temp)

if 'df_cora_gcn_pe_beta10000_nzh' in locals():
    df_temp = df_cora_gcn_pe_beta10000_nzh.copy()
    df_temp['dataset'] = 'cora'
    df_temp['beta'] = 10000
    df_temp['positional_encoding'] = True
    df_temp['hop_type'] = 'non_zero_hop'
    dataframes_to_merge.append(df_temp)

if 'df_cora_gcn_pe_beta1_nzh' in locals():
    df_temp = df_cora_gcn_pe_beta1_nzh.copy()
    df_temp['dataset'] = 'cora'
    df_temp['beta'] = 1
    df_temp['positional_encoding'] = True
    df_temp['hop_type'] = 'non_zero_hop'
    dataframes_to_merge.append(df_temp)

if 'cora_gcn_zh_no_pe' in locals():
    df_temp = cora_gcn_zh_no_pe.copy()
    df_temp['dataset'] = 'cora'
    df_temp['beta'] = None  # Will need to infer from other columns if needed
    df_temp['positional_encoding'] = False
    df_temp['hop_type'] = 'zero_hop'
    dataframes_to_merge.append(df_temp)

if 'cora_gcn_zh_pe' in locals():
    df_temp = cora_gcn_zh_pe.copy()
    df_temp['dataset'] = 'cora'
    df_temp['beta'] = None  # Will need to infer from other columns if needed
    df_temp['positional_encoding'] = True
    df_temp['hop_type'] = 'zero_hop'
    dataframes_to_merge.append(df_temp)

# Citeseer experiments
if 'df_citeseer_gcn_no_pe' in locals():
    df_temp = df_citeseer_gcn_no_pe.copy()
    df_temp['dataset'] = 'citeseer'
    df_temp['beta'] = None  # Will need to infer from other columns if needed
    df_temp['positional_encoding'] = False
    df_temp['hop_type'] = 'mixed'  # Based on the output, seems to have multiple hop types
    dataframes_to_merge.append(df_temp)

if 'df_citeseer_gcn_pe' in locals():
    df_temp = df_citeseer_gcn_pe.copy()
    df_temp['dataset'] = 'citeseer'
    df_temp['beta'] = None  # Will need to infer from other columns if needed
    df_temp['positional_encoding'] = True
    df_temp['hop_type'] = 'mixed'  # Based on the output, seems to have multiple hop types
    dataframes_to_merge.append(df_temp)

# Merge all DataFrames
if dataframes_to_merge:
    df_all_experiments = pd.concat(dataframes_to_merge, ignore_index=True)
    print(f"Successfully merged {len(dataframes_to_merge)} DataFrames into one with {len(df_all_experiments)} total rows")
    print(f"Columns: {list(df_all_experiments.columns)}")
    print(f"Dataset distribution: {df_all_experiments['dataset'].value_counts()}")
    print(f"Positional encoding distribution: {df_all_experiments['positional_encoding'].value_counts()}")
else:
    print("No DataFrames found to merge")

df_all_experiments