In [1]:
import pandas as pd

data = [
    ["Pubmed", "zero_hop", "GAT", 1, 10, 0.6328, 0.6435, 0.0091, 0.0071, "00:49:57"],
    ["Pubmed", "zero_hop", "GAT", 10, 10, 0.6336, 0.6471, 0.0025, 0.0046, "00:51:56"],
    ["Pubmed", "zero_hop", "GAT", 10000, 10, 0.665, 0.655, 0.002, 0.004, "00:37:26"],
    ["Pubmed", "adjacency", "GAT", 1, 10, 0.4436, 0.6829, 0.045, 0.1021, "00:25:23"],
    ["Pubmed", "adjacency", "GAT", 10, 10, 0.7274, 0.7257, 0.0299, 0.0262, "00:49:08"],
    ["Pubmed", "adjacency", "GAT", 10000, 10, 0.7236, 0.7035, 0.0756, 0.0428, "00:43:37"],
    ["Pubmed", "diffusion", "GAT", 1, 10, 0.5088, 0.7102, 0.0173, 0.047, "00:11:15"],
    ["Pubmed", "diffusion", "GAT", 10, 10, 0.7386, 0.7502, 0.0204, 0.0191, "00:10:41"],
    ["Pubmed", "diffusion", "GAT", 10000, 10, 0.7078, 0.6686, 0.0806, 0.064, "00:10:17"],
    ["Pubmed", "full", "GAT", 1, 10, 0.6914, 0.6964, 0.0225, 0.027, "00:07:54"],
    ["Pubmed", "full", "GAT", 10, 10, 0.7536, 0.7578, 0.028, 0.0286, "00:08:00"],
    ["Pubmed", "full", "GAT", 10000, 10, 0.7388, 0.7378, 0.0118, 0.016, "00:07:59"],
]

columns = [
    "Dataset", "Data Loading", "Model", "Beta", "Clients",
    "Avg Global Result", "Avg Client Result", "client_std_dev",
    "global_std_dev", "Duration"
]

pubmed_gat_pe = pd.DataFrame(data, columns=columns)

In [2]:
pubmed_gat_pe

,Dataset,Data Loading,Model,Beta,Clients,Avg Global Result,Avg Client Result,client_std_dev,global_std_dev,Duration
0,Pubmed,zero_hop,GAT,1,10,0.6328,0.6435,0.0091,0.0071,00:49:57
1,Pubmed,zero_hop,GAT,10,10,0.6336,0.6471,0.0025,0.0046,00:51:56
2,Pubmed,zero_hop,GAT,10000,10,0.6650,0.6550,0.0020,0.0040,00:37:26
3,Pubmed,adjacency,GAT,1,10,0.4436,0.6829,0.0450,0.1021,00:25:23
4,Pubmed,adjacency,GAT,10,10,0.7274,0.7257,0.0299,0.0262,00:49:08
5,Pubmed,adjacency,GAT,10000,10,0.7236,0.7035,0.0756,0.0428,00:43:37
6,Pubmed,diffusion,GAT,1,10,0.5088,0.7102,0.0173,0.0470,00:11:15
7,Pubmed,diffusion,GAT,10,10,0.7386,0.7502,0.0204,0.0191,00:10:41
8,Pubmed,diffusion,GAT,10000,10,0.7078,0.6686,0.0806,0.0640,00:10:17
9,Pubmed,full,GAT,1,10,0.6914,0.6964,0.0225,0.0270,00:07:54
10,Pubmed,full,GAT,10,10,0.7536,0.7578,0.0280,0.0286,00:08:00
11,Pubmed,full,GAT,10000,10,0.7388,0.7378,0.0118,0.0160,00:07:59

In [3]:
import pandas as pd

data = [
    ["Pubmed", "zero_hop", "GAT", 1, 10, 0.6292, 0.6428, 0.0031, 0.0046, "00:09:13"],
    ["Pubmed", "zero_hop", "GAT", 10, 10, 0.6316, 0.6444, 0.0037, 0.0069, "00:11:47"],
    ["Pubmed", "zero_hop", "GAT", 10000, 10, 0.6682, 0.6567, 0.002, 0.0031, "00:12:32"],
    ["Pubmed", "adjacency", "GAT", 1, 10, 0.646, 0.6887, 0.0205, 0.0411, "00:12:14"],
    ["Pubmed", "adjacency", "GAT", 10, 10, 0.7776, 0.7807, 0.0143, 0.0067, "00:12:54"],
    ["Pubmed", "adjacency", "GAT", 10000, 10, 0.7552, 0.7579, 0.0479, 0.038, "00:10:20"],
    ["Pubmed", "diffusion", "GAT", 1, 10, 0.6634, 0.7086, 0.0092, 0.0203, "00:14:39"],
    ["Pubmed", "diffusion", "GAT", 10, 10, 0.7618, 0.7836, 0.0119, 0.0231, "00:14:17"],
    ["Pubmed", "diffusion", "GAT", 10000, 10, 0.7424, 0.7426, 0.039, 0.0323, "00:14:19"],
    ["Pubmed", "full", "GAT", 1, 10, 0.699, 0.7005, 0.0251, 0.0253, "00:12:26"],
    ["Pubmed", "full", "GAT", 10, 10, 0.7578, 0.7575, 0.0057, 0.0112, "00:12:40"],
    ["Pubmed", "full", "GAT", 10000, 10, 0.7332, 0.7305, 0.0118, 0.0157, "00:12:25"],
]

columns = [
    "Dataset", "Data Loading", "Model", "Beta", "Clients",
    "Avg Global Result", "Avg Client Result", "client_std_dev",
    "global_std_dev", "Duration"
]

pubmed_dat_no_pe = pd.DataFrame(data, columns=columns)

In [4]:
pubmed_dat_no_pe

,Dataset,Data Loading,Model,Beta,Clients,Avg Global Result,Avg Client Result,client_std_dev,global_std_dev,Duration
0,Pubmed,zero_hop,GAT,1,10,0.6292,0.6428,0.0031,0.0046,00:09:13
1,Pubmed,zero_hop,GAT,10,10,0.6316,0.6444,0.0037,0.0069,00:11:47
2,Pubmed,zero_hop,GAT,10000,10,0.6682,0.6567,0.0020,0.0031,00:12:32
3,Pubmed,adjacency,GAT,1,10,0.6460,0.6887,0.0205,0.0411,00:12:14
4,Pubmed,adjacency,GAT,10,10,0.7776,0.7807,0.0143,0.0067,00:12:54
5,Pubmed,adjacency,GAT,10000,10,0.7552,0.7579,0.0479,0.0380,00:10:20
6,Pubmed,diffusion,GAT,1,10,0.6634,0.7086,0.0092,0.0203,00:14:39
7,Pubmed,diffusion,GAT,10,10,0.7618,0.7836,0.0119,0.0231,00:14:17
8,Pubmed,diffusion,GAT,10000,10,0.7424,0.7426,0.0390,0.0323,00:14:19
9,Pubmed,full,GAT,1,10,0.6990,0.7005,0.0251,0.0253,00:12:26
10,Pubmed,full,GAT,10,10,0.7578,0.7575,0.0057,0.0112,00:12:40
11,Pubmed,full,GAT,10000,10,0.7332,0.7305,0.0118,0.0157,00:12:25

In [6]:
# lets drop: Dataset, mode, avg global results, and global std_dev on both dataframes
pubmed_dat_no_pe.drop(columns=["Dataset", "Model", "Avg Global Result", "global_std_dev"], inplace=True)
pubmed_dat_no_pe

   Data Loading   Beta  Clients  Avg Client Result  client_std_dev  Duration
0      zero_hop      1       10             0.6428          0.0031  00:09:13
1      zero_hop     10       10             0.6444          0.0037  00:11:47
2      zero_hop  10000       10             0.6567          0.0020  00:12:32
3     adjacency      1       10             0.6887          0.0205  00:12:14
4     adjacency     10       10             0.7807          0.0143  00:12:54
5     adjacency  10000       10             0.7579          0.0479  00:10:20
6     diffusion      1       10             0.7086          0.0092  00:14:39
7     diffusion     10       10             0.7836          0.0119  00:14:17
8     diffusion  10000       10             0.7426          0.0390  00:14:19
9          full      1       10             0.7005          0.0251  00:12:26
10         full     10       10             0.7575          0.0057  00:12:40
11         full  10000       10             0.7305          0.0118  00:12:25

In [7]:
pubmed_gat_pe.drop(columns=["Dataset", "Model", "Avg Global Result", "global_std_dev"], inplace=True)
pubmed_gat_pe

   Data Loading   Beta  Clients  Avg Client Result  client_std_dev  Duration
0      zero_hop      1       10             0.6435          0.0091  00:49:57
1      zero_hop     10       10             0.6471          0.0025  00:51:56
2      zero_hop  10000       10             0.6550          0.0020  00:37:26
3     adjacency      1       10             0.6829          0.0450  00:25:23
4     adjacency     10       10             0.7257          0.0299  00:49:08
5     adjacency  10000       10             0.7035          0.0756  00:43:37
6     diffusion      1       10             0.7102          0.0173  00:11:15
7     diffusion     10       10             0.7502          0.0204  00:10:41
8     diffusion  10000       10             0.6686          0.0806  00:10:17
9          full      1       10             0.6964          0.0225  00:07:54
10         full     10       10             0.7578          0.0280  00:08:00
11         full  10000       10             0.7378          0.0118  00:07:59

In [8]:
pubmed_gat_pe["pe"] = True

In [9]:
pubmed_gat_pe

,Data Loading,Beta,Clients,Avg Client Result,client_std_dev,Duration,pe
0,zero_hop,1,10,0.6435,0.0091,00:49:57,True
1,zero_hop,10,10,0.6471,0.0025,00:51:56,True
2,zero_hop,10000,10,0.6550,0.0020,00:37:26,True
3,adjacency,1,10,0.6829,0.0450,00:25:23,True
4,adjacency,10,10,0.7257,0.0299,00:49:08,True
5,adjacency,10000,10,0.7035,0.0756,00:43:37,True
6,diffusion,1,10,0.7102,0.0173,00:11:15,True
7,diffusion,10,10,0.7502,0.0204,00:10:41,True
8,diffusion,10000,10,0.6686,0.0806,00:10:17,True
9,full,1,10,0.6964,0.0225,00:07:54,True
10,full,10,10,0.7578,0.0280,00:08:00,True
11,full,10000,10,0.7378,0.0118,00:07:59,True

In [10]:
pubmed_dat_no_pe["pe"] = False
pubmed_dat_no_pe

,Data Loading,Beta,Clients,Avg Client Result,client_std_dev,Duration,pe
0,zero_hop,1,10,0.6428,0.0031,00:09:13,False
1,zero_hop,10,10,0.6444,0.0037,00:11:47,False
2,zero_hop,10000,10,0.6567,0.0020,00:12:32,False
3,adjacency,1,10,0.6887,0.0205,00:12:14,False
4,adjacency,10,10,0.7807,0.0143,00:12:54,False
5,adjacency,10000,10,0.7579,0.0479,00:10:20,False
6,diffusion,1,10,0.7086,0.0092,00:14:39,False
7,diffusion,10,10,0.7836,0.0119,00:14:17,False
8,diffusion,10000,10,0.7426,0.0390,00:14:19,False
9,full,1,10,0.7005,0.0251,00:12:26,False
10,full,10,10,0.7575,0.0057,00:12:40,False
11,full,10000,10,0.7305,0.0118,00:12:25,False

In [11]:
# lets combine the two dataframes vertically
pubmed_gat = pd.concat([pubmed_gat_pe, pubmed_dat_no_pe], ignore_index=True)
pubmed_gat

,Data Loading,Beta,Clients,Avg Client Result,client_std_dev,Duration,pe
0,zero_hop,1,10,0.6435,0.0091,00:49:57,True
1,zero_hop,10,10,0.6471,0.0025,00:51:56,True
2,zero_hop,10000,10,0.6550,0.0020,00:37:26,True
3,adjacency,1,10,0.6829,0.0450,00:25:23,True
4,adjacency,10,10,0.7257,0.0299,00:49:08,True
5,adjacency,10000,10,0.7035,0.0756,00:43:37,True
6,diffusion,1,10,0.7102,0.0173,00:11:15,True
7,diffusion,10,10,0.7502,0.0204,00:10:41,True
8,diffusion,10000,10,0.6686,0.0806,00:10:17,True
9,full,1,10,0.6964,0.0225,00:07:54,True
10,full,10,10,0.7578,0.0280,00:08:00,True
11,full,10000,10,0.7378,0.0118,00:07:59,True
12,zero_hop,1,10,0.6428,0.0031,00:09:13,False
13,zero_hop,10,10,0.6444,0.0037,00:11:47,False
14,zero_hop,10000,10,0.6567,0.0020,00:12:32,False
15,adjacency,1,10,0.6887,0.0205,00:12:14,False
16,adjacency,10,10,0.7807,0.0143,00:12:54,False
17,adjacency,10000,10,0.7579,0.0479,00:10:20,False
18,diffusion,1,10,0.7086,0.0092,00:14:39,False
19,diffusion,10,10,0.7836,0.0119,00:14:17,False
20,diffusion,10000,10,0.7426,0.0390,00:14:19,False
21,full,1,10,0.7005,0.0251,00:12:26,False
22,full,10,10,0.7575,0.0057,00:12:40,False
23,full,10000,10,0.7305,0.0118,00:12:25,False

In [12]:
# lets drop the rows where the beta value is 1
pubmed_gat = pubmed_gat[pubmed_gat["Beta"] != 1]
pubmed_gat

,Data Loading,Beta,Clients,Avg Client Result,client_std_dev,Duration,pe
1,zero_hop,10,10,0.6471,0.0025,00:51:56,True
2,zero_hop,10000,10,0.6550,0.0020,00:37:26,True
4,adjacency,10,10,0.7257,0.0299,00:49:08,True
5,adjacency,10000,10,0.7035,0.0756,00:43:37,True
7,diffusion,10,10,0.7502,0.0204,00:10:41,True
8,diffusion,10000,10,0.6686,0.0806,00:10:17,True
10,full,10,10,0.7578,0.0280,00:08:00,True
11,full,10000,10,0.7378,0.0118,00:07:59,True
13,zero_hop,10,10,0.6444,0.0037,00:11:47,False
14,zero_hop,10000,10,0.6567,0.0020,00:12:32,False
16,adjacency,10,10,0.7807,0.0143,00:12:54,False
17,adjacency,10000,10,0.7579,0.0479,00:10:20,False
19,diffusion,10,10,0.7836,0.0119,00:14:17,False
20,diffusion,10000,10,0.7426,0.0390,00:14:19,False
22,full,10,10,0.7575,0.0057,00:12:40,False
23,full,10000,10,0.7305,0.0118,00:12:25,False