In [1]:
import sys
import os
import torch

In [2]:
# from federated_learning_cuda import load_configuration, main_experiment
from run import load_configuration, main_experiment

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")   
from run import load_and_split_with_khop, load_and_split_with_feature_prop
dataset_name = "Cora"
num_clients = 10
beta = 1
hop = 1
data_loading_option = "full"
fulltraining_flag = False

In [4]:
cora_data = load_and_split_with_khop(dataset_name, device, num_clients, beta, hop=hop, imputation_method=data_loading_option, fulltraining_flag=fulltraining_flag)

In [5]:
len(cora_data)

4

In [6]:
# # check client 0 data
# print(clients_data[0])
# # check number of nodes in client 0 with zerof feature vectors
# # also check train/test/val nodes the number
# #total nodes in client 0
# total_nodes = clients_data[0].x.shape[0]
# #nodes with zero feature vectors
# zfv_nodes = torch.sum(clients_data[0].x == 0)
# print(f"Number of nodes in client 0 with zero feature vectors: {torch.sum(clients_data[0].x == 0)}")
# print(f"Number of train nodes in client 0: {torch.sum(clients_data[0].train_mask)}")
# print(f"Number of test nodes in client 0: {torch.sum(clients_data[0].test_mask)}")
# print(f"Number of val nodes in client 0: {torch.sum(clients_data[0].val_mask)}")

In [7]:
# load with fp and check the same things
data, dataset, clients_data, test_data,  = load_and_split_with_feature_prop("Citeseer", device, num_clients=10, beta=0.5, hop=1)

# check client 0 data
print(clients_data[0])
# check number of nodes in client 0 with zerof feature vectors
print(f"Number of nodes in client 0 with zero feature vectors: {torch.sum(clients_data[0].x == 0)}")
print(f"Number of train nodes in client 0: {torch.sum(clients_data[0].train_mask)}")
print(f"Number of test nodes in client 0: {torch.sum(clients_data[0].test_mask)}")
print(f"Number of val nodes in client 0: {torch.sum(clients_data[0].val_mask)}")

Data(x=[936, 3703], edge_index=[2, 2454], y=[936], train_mask=[936], val_mask=[936], test_mask=[936], mapping=[339])
Number of nodes in client 0 with zero feature vectors: 3281071
Number of train nodes in client 0: 7
Number of test nodes in client 0: 104
Number of val nodes in client 0: 55

In [8]:
import torch

print(f"Number of GPUs available: {torch.cuda.device_count()}")

if torch.cuda.is_available():
    for i in range(torch.cuda.device_count()):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
else:
    print("No GPU available")

Number of GPUs available: 1
GPU 0: NVIDIA L40-48Q

In [24]:
# from federated_learning_cuda import load_configuration, main_experiment
from run import load_configuration, main_experiment
import os
import ray
ray.shutdown()

if __name__ == "__main__":
    # Define all options in a list
    data_loading_options = ["full", "adjacency", "diffusion", ]
    model_types = ["GCN"]
        
    # Load configuration once since it's common for all runs
    clients_num, beta, cfg = load_configuration()

    beta = 10000

    clients_num = 10

    # Main results directory
    main_dir = 'Pubmed_results474'
    dataset_name = "Pubmed"  # You can change this if you have different datasets

    # Loop over all combinations of data_loading_option and model_type
    for data_loading_option in data_loading_options:
        for model_type in model_types:
            # Create a structured directory for each experiment
            result_name = f"{dataset_name}_{data_loading_option}_{model_type}"
            results_dir = os.path.join(main_dir, result_name)

            # Create the directory if it doesn't exist
            os.makedirs(results_dir, exist_ok=True)

            print(f"Running experiment with data_loading_option: {data_loading_option}, model_type: {model_type}")
            result, output = main_experiment(clients_num, beta, data_loading_option, model_type, cfg, dataset_name=dataset_name, hop=1)
            
            # Replace literal '\n' with actual newline characters if necessary
            # Convert result dictionary to string representation first
            result_str = str(result)
            result_with_newlines = result_str.replace('\\n', '\n')
            
            # Create a unique filename for each combination
            filename = f'results_{dataset_name}_{data_loading_option}_{model_type}.txt'
            filepath = os.path.join(results_dir, filename)
            
            # Write the result to the text file
            with open(filepath, 'w') as f:
                f.write(result_with_newlines)
            
            print(f"Results saved to {filepath}\n")

Running experiment with data_loading_option: full, model_type: GCN
DEVICE: cuda
Data loading option is full
Model type is GCN

2025-05-02 19:05:06,641	INFO worker.py:1816 -- Started a local Ray instance.

data_loading_option: full

Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.x
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.tx
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.allx
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.y
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.ty
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.ally
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.graph
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.pubmed.test.index
Processing...
Done!

Data loaded
Device is cuda
Pubmed()
10

(FLClient pid=2775432) 2025-05-02 19:05:25,873 - INFO - Epoch   0| Train Loss: 1.100| Train Accuracy: 0.250
(FLClient pid=2775432) 2025-05-02 19:05:25,877 - INFO - Epoch   1| Train Loss: 0.900| Train Accuracy: 0.750
(FLClient pid=2775432) 2025-05-02 19:05:25,880 - INFO - Epoch   2| Train Loss: 0.727| Train Accuracy: 0.750
(FLClient pid=2775432) 2025-05-02 19:05:25,890 - INFO - Epoch   2| Validation Loss: 1.319, Validation Accuracy: 0.295
(FLClient pid=2775432) 2025-05-02 19:05:30,907 - INFO - Epoch   2| Train Loss: 0.517| Train Accuracy: 0.750 [repeated 390x across cluster]
(FLClient pid=2775432) 2025-05-02 19:05:31,255 - INFO - Epoch   2| Validation Loss: 1.355, Validation Accuracy: 0.295 [repeated 140x across cluster]
(FLClient pid=2775432) 2025-05-02 19:05:36,032 - INFO - Epoch   1| Train Loss: 0.692| Train Accuracy: 0.750 [repeated 449x across cluster]
(FLClient pid=2775432) 2025-05-02 19:05:36,391 - INFO - Epoch   2| Validation Loss: 1.231, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2775432) 2025-05-02 19:05:41,156 - INFO - Epoch   2| Train Loss: 0.613| Train Accuracy: 0.500 [repeated 451x across cluster]
(FLClient pid=2775432) 2025-05-02 19:05:41,508 - INFO - Epoch   2| Validation Loss: 1.365, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2775432) 2025-05-02 19:05:46,291 - INFO - Epoch   1| Train Loss: 0.531| Train Accuracy: 0.750 [repeated 449x across cluster]
(FLClient pid=2775432) 2025-05-02 19:05:46,650 - INFO - Epoch   2| Validation Loss: 1.355, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2775432) 2025-05-02 19:05:51,437 - INFO - Epoch   2| Train Loss: 0.348| Train Accuracy: 1.000 [repeated 451x across cluster]
(FLClient pid=2775432) 2025-05-02 19:05:51,786 - INFO - Epoch   2| Validation Loss: 1.671, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2775432) 2025-05-02 19:05:56,540 - INFO - Epoch   2| Train Loss: 0.316| Train Accuracy: 1.000 [repeated 450x across cluster]
(FLClient pid=2775438) 2025-05-02 19:05:56,548 - INFO - Epoch   2| Validation Loss: 0.862, Validation Accuracy: 0.562 [repeated 149x across cluster]

Training done
Round 1
Train Loss: 1.319, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.048, Train Accuracy: 0.400
Train Loss: 1.195, Train Accuracy: 0.600
Train Loss: 1.181, Train Accuracy: 0.625
Train Loss: 1.315, Train Accuracy: 0.800
Train Loss: 1.323, Train Accuracy: 0.500
Train Loss: 1.132, Train Accuracy: 0.200
Train Loss: 1.342, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.200
Round 2
Train Loss: 1.361, Train Accuracy: 0.750
Train Loss: 1.086, Train Accuracy: 0.500
Train Loss: 1.051, Train Accuracy: 0.200
Train Loss: 1.218, Train Accuracy: 0.600
Train Loss: 1.199, Train Accuracy: 0.625
Train Loss: 1.286, Train Accuracy: 0.800
Train Loss: 1.357, Train Accuracy: 1.000
Train Loss: 1.150, Train Accuracy: 0.400
Train Loss: 1.412, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.400
Round 3
Train Loss: 1.358, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.054, Train Accuracy: 0.400
Train Loss: 1.227, Train Accuracy: 0.600
Train Loss: 1.208, Train Accuracy: 0.625
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.376, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.600
Train Loss: 1.463, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.500
Round 4
Train Loss: 1.326, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 1.235, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.625
Train Loss: 1.292, Train Accuracy: 0.800
Train Loss: 1.402, Train Accuracy: 0.500
Train Loss: 1.160, Train Accuracy: 0.600
Train Loss: 1.532, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.400
Round 5
Train Loss: 1.276, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.043, Train Accuracy: 0.200
Train Loss: 1.263, Train Accuracy: 0.600
Train Loss: 1.258, Train Accuracy: 0.625
Train Loss: 1.295, Train Accuracy: 0.800
Train Loss: 1.423, Train Accuracy: 0.500
Train Loss: 1.186, Train Accuracy: 0.800
Train Loss: 1.549, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.700
Round 6
Train Loss: 1.406, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.283, Train Accuracy: 0.600
Train Loss: 1.255, Train Accuracy: 0.625
Train Loss: 1.292, Train Accuracy: 0.800
Train Loss: 1.440, Train Accuracy: 0.500
Train Loss: 1.194, Train Accuracy: 0.800
Train Loss: 1.563, Train Accuracy: 0.750
Train Loss: 1.155, Train Accuracy: 0.400
Round 7
Train Loss: 1.369, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 1.290, Train Accuracy: 0.600
Train Loss: 1.260, Train Accuracy: 0.625
Train Loss: 1.287, Train Accuracy: 0.800
Train Loss: 1.439, Train Accuracy: 0.500
Train Loss: 1.194, Train Accuracy: 0.400
Train Loss: 1.645, Train Accuracy: 0.750
Train Loss: 1.189, Train Accuracy: 0.600
Round 8
Train Loss: 1.331, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.400
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.334, Train Accuracy: 0.600
Train Loss: 1.240, Train Accuracy: 0.625
Train Loss: 1.312, Train Accuracy: 0.800
Train Loss: 1.446, Train Accuracy: 0.250
Train Loss: 1.184, Train Accuracy: 0.600
Train Loss: 1.667, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.400
Round 9
Train Loss: 1.454, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.325, Train Accuracy: 0.600
Train Loss: 1.265, Train Accuracy: 0.625
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.467, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.200
Train Loss: 1.639, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.400
Round 10
Train Loss: 1.334, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.500
Train Loss: 1.033, Train Accuracy: 0.000
Train Loss: 1.328, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.307, Train Accuracy: 0.800
Train Loss: 1.451, Train Accuracy: 0.500
Train Loss: 1.179, Train Accuracy: 0.000
Train Loss: 1.649, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.400
Round 11
Train Loss: 1.393, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.500
Train Loss: 1.017, Train Accuracy: 0.400
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.267, Train Accuracy: 0.625
Train Loss: 1.314, Train Accuracy: 0.800
Train Loss: 1.477, Train Accuracy: 0.500
Train Loss: 1.163, Train Accuracy: 0.200
Train Loss: 1.695, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.400
Round 12
Train Loss: 1.341, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 1.379, Train Accuracy: 0.600
Train Loss: 1.253, Train Accuracy: 0.625
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.487, Train Accuracy: 0.500
Train Loss: 1.150, Train Accuracy: 0.400
Train Loss: 1.674, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.300
Round 13
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.500
Train Loss: 1.015, Train Accuracy: 0.400
Train Loss: 1.301, Train Accuracy: 0.600
Train Loss: 1.243, Train Accuracy: 0.625
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.464, Train Accuracy: 0.500
Train Loss: 1.159, Train Accuracy: 0.600
Train Loss: 1.701, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.500
Round 14
Train Loss: 1.370, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.600
Train Loss: 1.026, Train Accuracy: 0.400
Train Loss: 1.303, Train Accuracy: 0.600
Train Loss: 1.248, Train Accuracy: 0.625
Train Loss: 1.286, Train Accuracy: 0.800
Train Loss: 1.529, Train Accuracy: 0.500
Train Loss: 1.240, Train Accuracy: 0.400
Train Loss: 1.741, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.600
Round 15
Train Loss: 1.355, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.500
Train Loss: 1.009, Train Accuracy: 0.400
Train Loss: 1.398, Train Accuracy: 0.800
Train Loss: 1.247, Train Accuracy: 0.625
Train Loss: 1.293, Train Accuracy: 0.800
Train Loss: 1.544, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.400
Train Loss: 1.685, Train Accuracy: 0.750
Train Loss: 1.213, Train Accuracy: 0.600
Round 16
Train Loss: 1.370, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.500
Train Loss: 1.020, Train Accuracy: 0.400
Train Loss: 1.420, Train Accuracy: 0.800
Train Loss: 1.261, Train Accuracy: 0.625
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.400
Train Loss: 1.807, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.500
Round 17
Train Loss: 1.283, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.600
Train Loss: 1.009, Train Accuracy: 0.400
Train Loss: 1.376, Train Accuracy: 0.600
Train Loss: 1.259, Train Accuracy: 0.625
Train Loss: 1.334, Train Accuracy: 0.800
Train Loss: 1.526, Train Accuracy: 0.750
Train Loss: 1.161, Train Accuracy: 0.600
Train Loss: 1.667, Train Accuracy: 0.750
Train Loss: 1.199, Train Accuracy: 0.700
Round 18
Train Loss: 1.517, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.500
Train Loss: 1.009, Train Accuracy: 0.400
Train Loss: 1.357, Train Accuracy: 0.600
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.372, Train Accuracy: 0.800
Train Loss: 1.512, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.600
Train Loss: 1.729, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.400
Round 19
Train Loss: 1.334, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.400
Train Loss: 0.998, Train Accuracy: 0.400
Train Loss: 1.330, Train Accuracy: 0.600
Train Loss: 1.282, Train Accuracy: 0.625
Train Loss: 1.390, Train Accuracy: 0.800
Train Loss: 1.584, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.600
Train Loss: 1.713, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.400
Round 20
Train Loss: 1.415, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.500
Train Loss: 0.997, Train Accuracy: 0.400
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.376, Train Accuracy: 0.800
Train Loss: 1.567, Train Accuracy: 1.000
Train Loss: 1.144, Train Accuracy: 0.400
Train Loss: 1.810, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.500
Round 21
Train Loss: 1.281, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.600
Train Loss: 0.994, Train Accuracy: 0.400
Train Loss: 1.352, Train Accuracy: 0.600
Train Loss: 1.302, Train Accuracy: 0.750
Train Loss: 1.272, Train Accuracy: 0.800
Train Loss: 1.508, Train Accuracy: 0.750
Train Loss: 1.197, Train Accuracy: 0.200
Train Loss: 1.803, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.600
Round 22
Train Loss: 1.314, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.600
Train Loss: 0.992, Train Accuracy: 0.400
Train Loss: 1.357, Train Accuracy: 0.800
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.544, Train Accuracy: 0.750
Train Loss: 1.142, Train Accuracy: 0.400
Train Loss: 1.654, Train Accuracy: 0.750
Train Loss: 1.209, Train Accuracy: 0.600
Round 23
Train Loss: 1.178, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.600
Train Loss: 0.985, Train Accuracy: 0.400
Train Loss: 1.382, Train Accuracy: 0.800
Train Loss: 1.206, Train Accuracy: 0.625
Train Loss: 1.329, Train Accuracy: 0.800
Train Loss: 1.475, Train Accuracy: 1.000
Train Loss: 1.172, Train Accuracy: 0.600
Train Loss: 1.872, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.500
Round 24
Train Loss: 1.422, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.600
Train Loss: 0.988, Train Accuracy: 0.200
Train Loss: 1.356, Train Accuracy: 1.000
Train Loss: 1.240, Train Accuracy: 0.750
Train Loss: 1.276, Train Accuracy: 0.800
Train Loss: 1.498, Train Accuracy: 0.500
Train Loss: 1.150, Train Accuracy: 0.600
Train Loss: 1.767, Train Accuracy: 0.750
Train Loss: 1.091, Train Accuracy: 0.700
Round 25
Train Loss: 1.279, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.700
Train Loss: 0.972, Train Accuracy: 0.400
Train Loss: 1.371, Train Accuracy: 0.800
Train Loss: 1.210, Train Accuracy: 0.625
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.530, Train Accuracy: 1.000
Train Loss: 1.140, Train Accuracy: 0.600
Train Loss: 1.880, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.600
Round 26
Train Loss: 1.473, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.700
Train Loss: 0.966, Train Accuracy: 0.600
Train Loss: 1.372, Train Accuracy: 0.800
Train Loss: 1.203, Train Accuracy: 0.875
Train Loss: 1.226, Train Accuracy: 0.800
Train Loss: 1.496, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.600
Train Loss: 1.772, Train Accuracy: 0.750
Train Loss: 1.148, Train Accuracy: 0.600
Round 27
Train Loss: 1.392, Train Accuracy: 0.750
Train Loss: 1.030, Train Accuracy: 0.500
Train Loss: 0.969, Train Accuracy: 0.400
Train Loss: 1.344, Train Accuracy: 1.000
Train Loss: 1.176, Train Accuracy: 0.875
Train Loss: 1.390, Train Accuracy: 0.800
Train Loss: 1.479, Train Accuracy: 0.750
Train Loss: 1.217, Train Accuracy: 0.800
Train Loss: 1.683, Train Accuracy: 0.750
Train Loss: 1.128, Train Accuracy: 0.500
Round 28
Train Loss: 1.322, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.500
Train Loss: 0.984, Train Accuracy: 0.400
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.197, Train Accuracy: 0.875
Train Loss: 1.393, Train Accuracy: 0.800
Train Loss: 1.607, Train Accuracy: 0.500
Train Loss: 1.152, Train Accuracy: 0.400
Train Loss: 1.795, Train Accuracy: 0.750
Train Loss: 1.235, Train Accuracy: 0.800
Round 29
Train Loss: 1.255, Train Accuracy: 0.750
Train Loss: 1.008, Train Accuracy: 0.500
Train Loss: 0.967, Train Accuracy: 0.600
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.241, Train Accuracy: 0.750
Train Loss: 1.294, Train Accuracy: 0.800
Train Loss: 1.725, Train Accuracy: 0.500
Train Loss: 1.044, Train Accuracy: 0.600
Train Loss: 1.853, Train Accuracy: 0.750
Train Loss: 1.116, Train Accuracy: 0.500
Round 30
Train Loss: 1.231, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 0.955, Train Accuracy: 0.400
Train Loss: 1.364, Train Accuracy: 0.800
Train Loss: 1.185, Train Accuracy: 0.375
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.423, Train Accuracy: 0.500
Train Loss: 1.140, Train Accuracy: 0.600
Train Loss: 1.652, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.500
Round 31
Train Loss: 1.380, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.800
Train Loss: 0.950, Train Accuracy: 0.400
Train Loss: 1.236, Train Accuracy: 0.800
Train Loss: 1.251, Train Accuracy: 0.875
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.587, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.800
Train Loss: 2.077, Train Accuracy: 1.000
Train Loss: 1.034, Train Accuracy: 0.500
Round 32
Train Loss: 1.335, Train Accuracy: 0.750
Train Loss: 0.984, Train Accuracy: 0.500
Train Loss: 0.963, Train Accuracy: 0.400
Train Loss: 1.232, Train Accuracy: 0.800
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.358, Train Accuracy: 1.000
Train Loss: 1.535, Train Accuracy: 0.750
Train Loss: 1.245, Train Accuracy: 0.600
Train Loss: 2.098, Train Accuracy: 0.750
Train Loss: 1.108, Train Accuracy: 0.600
Round 33
Train Loss: 1.497, Train Accuracy: 0.750
Train Loss: 0.985, Train Accuracy: 0.600
Train Loss: 0.946, Train Accuracy: 0.800
Train Loss: 1.319, Train Accuracy: 0.600
Train Loss: 1.227, Train Accuracy: 0.750
Train Loss: 1.286, Train Accuracy: 0.800
Train Loss: 1.482, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.600
Train Loss: 1.871, Train Accuracy: 1.000
Train Loss: 1.057, Train Accuracy: 0.700
Round 34
Train Loss: 1.431, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.600
Train Loss: 0.961, Train Accuracy: 0.600
Train Loss: 1.290, Train Accuracy: 1.000
Train Loss: 1.237, Train Accuracy: 0.750
Train Loss: 1.381, Train Accuracy: 0.800
Train Loss: 1.556, Train Accuracy: 1.000
Train Loss: 1.132, Train Accuracy: 0.400
Train Loss: 1.743, Train Accuracy: 0.750
Train Loss: 1.025, Train Accuracy: 0.300
Round 35
Train Loss: 1.232, Train Accuracy: 0.750
Train Loss: 0.968, Train Accuracy: 0.800
Train Loss: 0.932, Train Accuracy: 0.600
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.212, Train Accuracy: 0.625
Train Loss: 1.413, Train Accuracy: 0.800
Train Loss: 1.531, Train Accuracy: 1.000
Train Loss: 1.083, Train Accuracy: 0.800
Train Loss: 1.923, Train Accuracy: 0.750
Train Loss: 1.050, Train Accuracy: 0.700
Round 36
Train Loss: 1.360, Train Accuracy: 0.750
Train Loss: 1.007, Train Accuracy: 0.600
Train Loss: 0.913, Train Accuracy: 0.400
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.187, Train Accuracy: 0.500
Train Loss: 1.236, Train Accuracy: 0.800
Train Loss: 1.676, Train Accuracy: 0.500
Train Loss: 1.077, Train Accuracy: 0.800
Train Loss: 1.790, Train Accuracy: 0.750
Train Loss: 1.104, Train Accuracy: 0.700
Round 37
Train Loss: 1.279, Train Accuracy: 0.750
Train Loss: 0.972, Train Accuracy: 0.600
Train Loss: 0.959, Train Accuracy: 0.600
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.174, Train Accuracy: 0.250
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.663, Train Accuracy: 1.000
Train Loss: 1.179, Train Accuracy: 0.600
Train Loss: 1.770, Train Accuracy: 0.750
Train Loss: 1.094, Train Accuracy: 0.700
Round 38
Train Loss: 1.164, Train Accuracy: 0.750
Train Loss: 0.975, Train Accuracy: 0.600
Train Loss: 0.896, Train Accuracy: 0.800
Train Loss: 1.265, Train Accuracy: 1.000
Train Loss: 1.198, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.800
Train Loss: 1.715, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.600
Train Loss: 1.943, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.600
Round 39
Train Loss: 1.085, Train Accuracy: 0.750
Train Loss: 0.968, Train Accuracy: 0.700
Train Loss: 0.906, Train Accuracy: 0.200
Train Loss: 1.435, Train Accuracy: 0.800
Train Loss: 1.314, Train Accuracy: 0.875
Train Loss: 1.214, Train Accuracy: 0.800
Train Loss: 1.487, Train Accuracy: 0.500
Train Loss: 0.990, Train Accuracy: 0.800
Train Loss: 2.114, Train Accuracy: 1.000
Train Loss: 1.022, Train Accuracy: 0.600
Round 40
Train Loss: 1.037, Train Accuracy: 0.750
Train Loss: 0.974, Train Accuracy: 0.700
Train Loss: 0.939, Train Accuracy: 0.400
Train Loss: 1.226, Train Accuracy: 0.800
Train Loss: 1.232, Train Accuracy: 0.875
Train Loss: 1.319, Train Accuracy: 0.800
Train Loss: 1.571, Train Accuracy: 0.500
Train Loss: 1.127, Train Accuracy: 0.600
Train Loss: 1.770, Train Accuracy: 0.750
Train Loss: 1.132, Train Accuracy: 0.400
Round 41
Train Loss: 1.264, Train Accuracy: 0.750
Train Loss: 0.952, Train Accuracy: 0.700
Train Loss: 0.949, Train Accuracy: 0.600
Train Loss: 1.435, Train Accuracy: 0.800
Train Loss: 1.220, Train Accuracy: 0.625
Train Loss: 1.281, Train Accuracy: 0.800
Train Loss: 1.654, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.800
Train Loss: 1.615, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.700
Round 42
Train Loss: 1.272, Train Accuracy: 0.750
Train Loss: 0.953, Train Accuracy: 0.700
Train Loss: 0.941, Train Accuracy: 0.600
Train Loss: 1.360, Train Accuracy: 1.000
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 1.256, Train Accuracy: 0.800
Train Loss: 1.608, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.600
Train Loss: 2.302, Train Accuracy: 0.750
Train Loss: 1.113, Train Accuracy: 0.700
Round 43
Train Loss: 1.217, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.700
Train Loss: 0.862, Train Accuracy: 0.800
Train Loss: 1.264, Train Accuracy: 1.000
Train Loss: 1.240, Train Accuracy: 0.625
Train Loss: 1.302, Train Accuracy: 0.800
Train Loss: 1.580, Train Accuracy: 0.750
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.891, Train Accuracy: 0.750
Train Loss: 0.983, Train Accuracy: 0.700
Round 44
Train Loss: 1.279, Train Accuracy: 0.500
Train Loss: 0.932, Train Accuracy: 0.500
Train Loss: 0.971, Train Accuracy: 0.600
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.213, Train Accuracy: 0.875
Train Loss: 1.339, Train Accuracy: 0.800
Train Loss: 1.549, Train Accuracy: 0.500
Train Loss: 1.032, Train Accuracy: 0.600
Train Loss: 2.063, Train Accuracy: 1.000
Train Loss: 1.230, Train Accuracy: 0.700
Round 45
Train Loss: 1.365, Train Accuracy: 0.750
Train Loss: 0.941, Train Accuracy: 0.600
Train Loss: 0.917, Train Accuracy: 0.600
Train Loss: 1.454, Train Accuracy: 1.000
Train Loss: 1.128, Train Accuracy: 0.750
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.574, Train Accuracy: 0.500
Train Loss: 0.998, Train Accuracy: 0.600
Train Loss: 1.763, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.500
Round 46
Train Loss: 1.266, Train Accuracy: 0.750
Train Loss: 0.937, Train Accuracy: 0.400
Train Loss: 0.857, Train Accuracy: 0.800
Train Loss: 1.187, Train Accuracy: 1.000
Train Loss: 1.143, Train Accuracy: 0.875
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.711, Train Accuracy: 1.000
Train Loss: 1.165, Train Accuracy: 0.600
Train Loss: 2.277, Train Accuracy: 1.000
Train Loss: 0.953, Train Accuracy: 0.500
Round 47
Train Loss: 1.348, Train Accuracy: 0.500
Train Loss: 0.989, Train Accuracy: 0.500
Train Loss: 0.922, Train Accuracy: 0.400
Train Loss: 1.239, Train Accuracy: 1.000
Train Loss: 1.184, Train Accuracy: 0.625
Train Loss: 1.369, Train Accuracy: 1.000
Train Loss: 1.482, Train Accuracy: 1.000
Train Loss: 0.971, Train Accuracy: 0.400
Train Loss: 1.925, Train Accuracy: 0.750
Train Loss: 0.903, Train Accuracy: 0.400
Round 48
Train Loss: 1.394, Train Accuracy: 1.000
Train Loss: 0.924, Train Accuracy: 0.800
Train Loss: 0.869, Train Accuracy: 0.600
Train Loss: 1.390, Train Accuracy: 1.000
Train Loss: 1.143, Train Accuracy: 0.750
Train Loss: 1.319, Train Accuracy: 1.000
Train Loss: 1.474, Train Accuracy: 0.750

(FLClient pid=2775434) 2025-05-02 19:06:07,443 - INFO - Epoch   2| Train Loss: 0.680| Train Accuracy: 0.750 [repeated 360x across cluster]
(FLClient pid=2775434) 2025-05-02 19:06:07,452 - INFO - Epoch   2| Validation Loss: 1.364, Validation Accuracy: 0.295 [repeated 111x across cluster]
(FLClient pid=2775439) 2025-05-02 19:06:12,379 - INFO - Epoch   2| Train Loss: 1.026| Train Accuracy: 0.400 [repeated 387x across cluster]
(FLClient pid=2775434) 2025-05-02 19:06:12,386 - INFO - Epoch   2| Validation Loss: 1.193, Validation Accuracy: 0.295 [repeated 120x across cluster]
(FLClient pid=2775434) 2025-05-02 19:06:17,499 - INFO - Epoch   2| Train Loss: 0.530| Train Accuracy: 0.750 [repeated 423x across cluster]
(FLClient pid=2775434) 2025-05-02 19:06:17,506 - INFO - Epoch   2| Validation Loss: 1.340, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2775434) 2025-05-02 19:06:22,622 - INFO - Epoch   2| Train Loss: 0.630| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2775434) 2025-05-02 19:06:22,630 - INFO - Epoch   2| Validation Loss: 1.217, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2775434) 2025-05-02 19:06:27,759 - INFO - Epoch   2| Train Loss: 0.547| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2775434) 2025-05-02 19:06:27,767 - INFO - Epoch   2| Validation Loss: 0.991, Validation Accuracy: 0.341 [repeated 150x across cluster]
(FLClient pid=2775434) 2025-05-02 19:06:32,891 - INFO - Epoch   2| Train Loss: 0.509| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2775434) 2025-05-02 19:06:32,899 - INFO - Epoch   2| Validation Loss: 1.479, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2775434) 2025-05-02 19:06:38,011 - INFO - Epoch   2| Train Loss: 0.400| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2775434) 2025-05-02 19:06:38,019 - INFO - Epoch   2| Validation Loss: 0.819, Validation Accuracy: 0.591 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.364, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.055, Train Accuracy: 0.200
Train Loss: 1.205, Train Accuracy: 0.600
Train Loss: 1.200, Train Accuracy: 0.625
Train Loss: 1.333, Train Accuracy: 0.800
Train Loss: 1.344, Train Accuracy: 0.500
Train Loss: 1.128, Train Accuracy: 0.600
Train Loss: 1.388, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.400
Round 2
Train Loss: 1.359, Train Accuracy: 0.750
Train Loss: 1.086, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 1.252, Train Accuracy: 0.600
Train Loss: 1.233, Train Accuracy: 0.625
Train Loss: 1.322, Train Accuracy: 0.800
Train Loss: 1.404, Train Accuracy: 0.500
Train Loss: 1.142, Train Accuracy: 0.400
Train Loss: 1.484, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.400
Round 3
Train Loss: 1.287, Train Accuracy: 0.750
Train Loss: 1.093, Train Accuracy: 0.500
Train Loss: 1.034, Train Accuracy: 0.400
Train Loss: 1.242, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.625
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.425, Train Accuracy: 0.500
Train Loss: 1.132, Train Accuracy: 0.600
Train Loss: 1.580, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.400
Round 4
Train Loss: 1.401, Train Accuracy: 0.750
Train Loss: 1.095, Train Accuracy: 0.500
Train Loss: 1.031, Train Accuracy: 0.400
Train Loss: 1.336, Train Accuracy: 0.600
Train Loss: 1.244, Train Accuracy: 0.625
Train Loss: 1.319, Train Accuracy: 0.800
Train Loss: 1.452, Train Accuracy: 0.500
Train Loss: 1.194, Train Accuracy: 0.800
Train Loss: 1.562, Train Accuracy: 0.750
Train Loss: 1.207, Train Accuracy: 0.300
Round 5
Train Loss: 1.392, Train Accuracy: 0.750
Train Loss: 1.092, Train Accuracy: 0.500
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.296, Train Accuracy: 0.600
Train Loss: 1.216, Train Accuracy: 0.625
Train Loss: 1.314, Train Accuracy: 0.800
Train Loss: 1.476, Train Accuracy: 0.500
Train Loss: 1.178, Train Accuracy: 0.200
Train Loss: 1.698, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.600
Round 6
Train Loss: 1.327, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.357, Train Accuracy: 0.600
Train Loss: 1.272, Train Accuracy: 0.625
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.486, Train Accuracy: 0.500
Train Loss: 1.139, Train Accuracy: 0.600
Train Loss: 1.704, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.500
Round 7
Train Loss: 1.425, Train Accuracy: 0.750
Train Loss: 1.098, Train Accuracy: 0.500
Train Loss: 1.024, Train Accuracy: 0.600
Train Loss: 1.315, Train Accuracy: 0.600
Train Loss: 1.264, Train Accuracy: 0.625
Train Loss: 1.319, Train Accuracy: 0.800
Train Loss: 1.484, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.600
Train Loss: 1.724, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.400
Round 8
Train Loss: 1.481, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 1.358, Train Accuracy: 0.600
Train Loss: 1.266, Train Accuracy: 0.625
Train Loss: 1.368, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 0.500
Train Loss: 1.149, Train Accuracy: 0.600
Train Loss: 1.688, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.300
Round 9
Train Loss: 1.215, Train Accuracy: 0.750
Train Loss: 1.080, Train Accuracy: 0.500
Train Loss: 1.017, Train Accuracy: 0.200
Train Loss: 1.337, Train Accuracy: 0.600
Train Loss: 1.274, Train Accuracy: 0.625
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.509, Train Accuracy: 0.500
Train Loss: 1.203, Train Accuracy: 0.600
Train Loss: 1.621, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.300
Round 10
Train Loss: 1.449, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.400
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.381, Train Accuracy: 0.600
Train Loss: 1.261, Train Accuracy: 0.625
Train Loss: 1.355, Train Accuracy: 0.800
Train Loss: 1.516, Train Accuracy: 1.000
Train Loss: 1.240, Train Accuracy: 0.800
Train Loss: 1.741, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.400
Round 11
Train Loss: 1.421, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.400
Train Loss: 1.012, Train Accuracy: 0.400
Train Loss: 1.401, Train Accuracy: 0.800
Train Loss: 1.271, Train Accuracy: 0.625
Train Loss: 1.304, Train Accuracy: 0.800
Train Loss: 1.542, Train Accuracy: 0.750
Train Loss: 1.193, Train Accuracy: 0.600
Train Loss: 1.846, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.300
Round 12
Train Loss: 1.324, Train Accuracy: 0.500
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.329, Train Accuracy: 0.600
Train Loss: 1.273, Train Accuracy: 0.625
Train Loss: 1.373, Train Accuracy: 0.800
Train Loss: 1.569, Train Accuracy: 0.750
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.684, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.400
Round 13
Train Loss: 1.193, Train Accuracy: 0.750
Train Loss: 1.070, Train Accuracy: 0.600
Train Loss: 1.003, Train Accuracy: 0.400
Train Loss: 1.338, Train Accuracy: 0.600
Train Loss: 1.217, Train Accuracy: 0.625
Train Loss: 1.289, Train Accuracy: 0.800
Train Loss: 1.556, Train Accuracy: 0.750
Train Loss: 1.205, Train Accuracy: 0.600
Train Loss: 1.733, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.400
Round 14
Train Loss: 1.516, Train Accuracy: 0.500
Train Loss: 1.064, Train Accuracy: 0.500
Train Loss: 1.004, Train Accuracy: 0.600
Train Loss: 1.360, Train Accuracy: 0.600
Train Loss: 1.262, Train Accuracy: 0.625
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.545, Train Accuracy: 1.000
Train Loss: 1.196, Train Accuracy: 0.600
Train Loss: 1.837, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.500
Round 15
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.500
Train Loss: 1.008, Train Accuracy: 0.400
Train Loss: 1.401, Train Accuracy: 0.800
Train Loss: 1.219, Train Accuracy: 0.750
Train Loss: 1.321, Train Accuracy: 0.800
Train Loss: 1.604, Train Accuracy: 0.500
Train Loss: 1.138, Train Accuracy: 0.400
Train Loss: 1.799, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.600
Round 16
Train Loss: 1.290, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.500
Train Loss: 0.991, Train Accuracy: 0.400
Train Loss: 1.375, Train Accuracy: 0.600
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 1.347, Train Accuracy: 0.800
Train Loss: 1.596, Train Accuracy: 0.500
Train Loss: 1.199, Train Accuracy: 0.800
Train Loss: 1.737, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 0.300
Round 17
Train Loss: 1.479, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.500
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.381, Train Accuracy: 0.800
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.604, Train Accuracy: 0.500
Train Loss: 1.104, Train Accuracy: 0.400
Train Loss: 1.804, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.700
Round 18
Train Loss: 1.361, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.500
Train Loss: 0.996, Train Accuracy: 0.400
Train Loss: 1.373, Train Accuracy: 0.800
Train Loss: 1.192, Train Accuracy: 0.625
Train Loss: 1.358, Train Accuracy: 0.800
Train Loss: 1.641, Train Accuracy: 0.750
Train Loss: 1.100, Train Accuracy: 0.600
Train Loss: 1.721, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.400
Round 19
Train Loss: 1.361, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.600
Train Loss: 0.980, Train Accuracy: 0.400
Train Loss: 1.379, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.750
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.555, Train Accuracy: 1.000
Train Loss: 1.161, Train Accuracy: 0.600
Train Loss: 1.783, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.300
Round 20
Train Loss: 1.404, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.600
Train Loss: 0.976, Train Accuracy: 0.400
Train Loss: 1.280, Train Accuracy: 0.600
Train Loss: 1.169, Train Accuracy: 0.500
Train Loss: 1.411, Train Accuracy: 0.800
Train Loss: 1.604, Train Accuracy: 0.750
Train Loss: 1.143, Train Accuracy: 0.800
Train Loss: 1.720, Train Accuracy: 0.750
Train Loss: 1.226, Train Accuracy: 0.900
Round 21
Train Loss: 1.331, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.700
Train Loss: 0.990, Train Accuracy: 0.400
Train Loss: 1.333, Train Accuracy: 0.800
Train Loss: 1.202, Train Accuracy: 0.750
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.625, Train Accuracy: 0.500
Train Loss: 1.092, Train Accuracy: 0.800
Train Loss: 1.801, Train Accuracy: 0.750
Train Loss: 1.137, Train Accuracy: 0.300
Round 22
Train Loss: 1.283, Train Accuracy: 0.750
Train Loss: 1.053, Train Accuracy: 0.700
Train Loss: 0.991, Train Accuracy: 0.600
Train Loss: 1.387, Train Accuracy: 0.600
Train Loss: 1.202, Train Accuracy: 0.750
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.616, Train Accuracy: 0.750
Train Loss: 1.233, Train Accuracy: 0.800
Train Loss: 1.821, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.800
Round 23
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.700
Train Loss: 0.961, Train Accuracy: 0.200
Train Loss: 1.435, Train Accuracy: 0.800
Train Loss: 1.187, Train Accuracy: 0.750
Train Loss: 1.239, Train Accuracy: 0.800
Train Loss: 1.577, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.800
Train Loss: 1.827, Train Accuracy: 0.750
Train Loss: 1.172, Train Accuracy: 0.700
Round 24
Train Loss: 1.237, Train Accuracy: 0.750
Train Loss: 1.037, Train Accuracy: 0.600
Train Loss: 0.963, Train Accuracy: 0.400
Train Loss: 1.408, Train Accuracy: 1.000
Train Loss: 1.168, Train Accuracy: 0.875
Train Loss: 1.312, Train Accuracy: 0.800
Train Loss: 1.512, Train Accuracy: 1.000
Train Loss: 1.045, Train Accuracy: 0.400
Train Loss: 1.805, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.700
Round 25
Train Loss: 1.501, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.300
Train Loss: 0.955, Train Accuracy: 0.400
Train Loss: 1.415, Train Accuracy: 0.600
Train Loss: 1.204, Train Accuracy: 0.875
Train Loss: 1.376, Train Accuracy: 0.800
Train Loss: 1.579, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 0.600
Train Loss: 1.917, Train Accuracy: 0.750
Train Loss: 1.141, Train Accuracy: 0.500
Round 26
Train Loss: 1.356, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.700
Train Loss: 0.957, Train Accuracy: 0.400
Train Loss: 1.509, Train Accuracy: 1.000
Train Loss: 1.173, Train Accuracy: 0.875
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.528, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.600
Train Loss: 1.809, Train Accuracy: 0.750
Train Loss: 1.139, Train Accuracy: 0.800
Round 27
Train Loss: 1.429, Train Accuracy: 0.750
Train Loss: 1.011, Train Accuracy: 0.600
Train Loss: 0.944, Train Accuracy: 0.600
Train Loss: 1.517, Train Accuracy: 0.800
Train Loss: 1.170, Train Accuracy: 0.750
Train Loss: 1.380, Train Accuracy: 0.800
Train Loss: 1.541, Train Accuracy: 0.250
Train Loss: 1.108, Train Accuracy: 0.600
Train Loss: 1.847, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.600
Round 28
Train Loss: 1.340, Train Accuracy: 0.750
Train Loss: 1.012, Train Accuracy: 0.500
Train Loss: 0.983, Train Accuracy: 0.800
Train Loss: 1.420, Train Accuracy: 0.800
Train Loss: 1.194, Train Accuracy: 0.625
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.617, Train Accuracy: 1.000
Train Loss: 1.151, Train Accuracy: 0.600
Train Loss: 1.866, Train Accuracy: 0.750
Train Loss: 1.122, Train Accuracy: 0.600
Round 29
Train Loss: 1.245, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.600
Train Loss: 0.930, Train Accuracy: 0.600
Train Loss: 1.439, Train Accuracy: 0.800
Train Loss: 1.234, Train Accuracy: 0.375
Train Loss: 1.339, Train Accuracy: 0.800
Train Loss: 1.594, Train Accuracy: 0.750
Train Loss: 1.114, Train Accuracy: 0.600
Train Loss: 1.720, Train Accuracy: 0.750
Train Loss: 1.121, Train Accuracy: 0.500
Round 30
Train Loss: 1.270, Train Accuracy: 0.750
Train Loss: 1.011, Train Accuracy: 0.500
Train Loss: 0.978, Train Accuracy: 0.600
Train Loss: 1.364, Train Accuracy: 0.400
Train Loss: 1.269, Train Accuracy: 0.625
Train Loss: 1.268, Train Accuracy: 0.800
Train Loss: 1.456, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.400
Train Loss: 1.727, Train Accuracy: 0.500
Train Loss: 1.179, Train Accuracy: 0.800
Round 31
Train Loss: 1.231, Train Accuracy: 0.750
Train Loss: 0.989, Train Accuracy: 0.700
Train Loss: 0.920, Train Accuracy: 0.400
Train Loss: 1.293, Train Accuracy: 1.000
Train Loss: 1.145, Train Accuracy: 0.625
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.603, Train Accuracy: 1.000
Train Loss: 1.148, Train Accuracy: 0.800
Train Loss: 1.672, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Round 32
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.600
Train Loss: 0.910, Train Accuracy: 0.600
Train Loss: 1.256, Train Accuracy: 0.800
Train Loss: 1.142, Train Accuracy: 0.875
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.508, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 1.686, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.800
Round 33
Train Loss: 1.436, Train Accuracy: 0.750
Train Loss: 0.981, Train Accuracy: 0.600
Train Loss: 0.926, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.800
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.287, Train Accuracy: 0.800
Train Loss: 1.609, Train Accuracy: 0.750
Train Loss: 1.150, Train Accuracy: 0.600
Train Loss: 1.983, Train Accuracy: 1.000
Train Loss: 1.213, Train Accuracy: 0.500
Round 34
Train Loss: 1.342, Train Accuracy: 1.000
Train Loss: 0.982, Train Accuracy: 0.500
Train Loss: 0.897, Train Accuracy: 0.800
Train Loss: 1.314, Train Accuracy: 0.800
Train Loss: 1.219, Train Accuracy: 0.750
Train Loss: 1.304, Train Accuracy: 0.800
Train Loss: 1.659, Train Accuracy: 0.750
Train Loss: 0.992, Train Accuracy: 0.600
Train Loss: 1.781, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.700
Round 35
Train Loss: 1.365, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.600
Train Loss: 0.893, Train Accuracy: 0.600
Train Loss: 1.320, Train Accuracy: 1.000
Train Loss: 1.276, Train Accuracy: 0.875
Train Loss: 1.230, Train Accuracy: 0.800
Train Loss: 1.787, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.400
Train Loss: 1.926, Train Accuracy: 0.750
Train Loss: 1.108, Train Accuracy: 0.600
Round 36
Train Loss: 1.180, Train Accuracy: 0.750
Train Loss: 0.955, Train Accuracy: 0.700
Train Loss: 0.893, Train Accuracy: 0.400
Train Loss: 1.255, Train Accuracy: 1.000
Train Loss: 1.091, Train Accuracy: 0.750
Train Loss: 1.348, Train Accuracy: 0.800
Train Loss: 1.689, Train Accuracy: 1.000
Train Loss: 1.017, Train Accuracy: 0.600
Train Loss: 1.823, Train Accuracy: 0.750
Train Loss: 1.100, Train Accuracy: 0.800
Round 37
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 0.968, Train Accuracy: 0.800
Train Loss: 0.883, Train Accuracy: 0.600
Train Loss: 1.390, Train Accuracy: 1.000
Train Loss: 1.221, Train Accuracy: 0.750
Train Loss: 1.193, Train Accuracy: 0.800
Train Loss: 1.616, Train Accuracy: 1.000
Train Loss: 0.984, Train Accuracy: 0.800
Train Loss: 1.666, Train Accuracy: 0.750
Train Loss: 1.238, Train Accuracy: 0.600
Round 38
Train Loss: 1.305, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.600
Train Loss: 0.906, Train Accuracy: 0.600
Train Loss: 1.228, Train Accuracy: 1.000
Train Loss: 1.200, Train Accuracy: 0.875
Train Loss: 1.257, Train Accuracy: 1.000
Train Loss: 1.643, Train Accuracy: 1.000
Train Loss: 1.196, Train Accuracy: 0.600
Train Loss: 1.606, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.700
Round 39
Train Loss: 1.406, Train Accuracy: 1.000
Train Loss: 0.985, Train Accuracy: 0.700
Train Loss: 0.893, Train Accuracy: 0.400
Train Loss: 1.253, Train Accuracy: 1.000
Train Loss: 1.120, Train Accuracy: 0.500
Train Loss: 1.281, Train Accuracy: 0.800
Train Loss: 1.584, Train Accuracy: 0.500
Train Loss: 1.173, Train Accuracy: 0.400
Train Loss: 1.631, Train Accuracy: 0.750
Train Loss: 1.200, Train Accuracy: 0.600
Round 40
Train Loss: 1.315, Train Accuracy: 0.750
Train Loss: 0.971, Train Accuracy: 0.700
Train Loss: 0.958, Train Accuracy: 0.600
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.169, Train Accuracy: 0.375
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.517, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.800
Train Loss: 2.007, Train Accuracy: 1.000
Train Loss: 1.038, Train Accuracy: 0.800
Round 41
Train Loss: 1.174, Train Accuracy: 0.750
Train Loss: 0.951, Train Accuracy: 0.600
Train Loss: 0.911, Train Accuracy: 0.800
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.202, Train Accuracy: 0.625
Train Loss: 1.222, Train Accuracy: 0.800
Train Loss: 1.493, Train Accuracy: 1.000
Train Loss: 1.201, Train Accuracy: 0.400
Train Loss: 2.108, Train Accuracy: 1.000
Train Loss: 1.272, Train Accuracy: 0.500
Round 42
Train Loss: 1.193, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.700
Train Loss: 0.857, Train Accuracy: 0.600
Train Loss: 1.270, Train Accuracy: 0.600
Train Loss: 1.174, Train Accuracy: 0.750
Train Loss: 1.120, Train Accuracy: 0.800
Train Loss: 1.470, Train Accuracy: 1.000
Train Loss: 1.240, Train Accuracy: 0.600
Train Loss: 1.918, Train Accuracy: 1.000
Train Loss: 1.061, Train Accuracy: 0.800
Round 43
Train Loss: 1.217, Train Accuracy: 0.750
Train Loss: 0.918, Train Accuracy: 0.700
Train Loss: 0.879, Train Accuracy: 0.400
Train Loss: 1.237, Train Accuracy: 1.000
Train Loss: 1.154, Train Accuracy: 0.500
Train Loss: 1.316, Train Accuracy: 0.800
Train Loss: 1.625, Train Accuracy: 0.750
Train Loss: 0.918, Train Accuracy: 0.600
Train Loss: 1.879, Train Accuracy: 1.000
Train Loss: 0.917, Train Accuracy: 0.600
Round 44
Train Loss: 1.030, Train Accuracy: 0.750
Train Loss: 0.925, Train Accuracy: 0.700
Train Loss: 0.851, Train Accuracy: 0.400
Train Loss: 1.400, Train Accuracy: 0.800
Train Loss: 1.100, Train Accuracy: 0.500
Train Loss: 1.201, Train Accuracy: 0.800
Train Loss: 1.697, Train Accuracy: 1.000
Train Loss: 0.943, Train Accuracy: 0.600
Train Loss: 1.721, Train Accuracy: 1.000
Train Loss: 1.367, Train Accuracy: 0.500
Round 45
Train Loss: 1.384, Train Accuracy: 1.000
Train Loss: 0.922, Train Accuracy: 0.800
Train Loss: 0.885, Train Accuracy: 0.600
Train Loss: 1.270, Train Accuracy: 0.600
Train Loss: 1.193, Train Accuracy: 0.625
Train Loss: 1.236, Train Accuracy: 0.800
Train Loss: 1.434, Train Accuracy: 1.000
Train Loss: 1.012, Train Accuracy: 0.800
Train Loss: 1.447, Train Accuracy: 0.750
Train Loss: 0.911, Train Accuracy: 0.400
Round 46
Train Loss: 1.254, Train Accuracy: 0.750
Train Loss: 0.902, Train Accuracy: 0.700
Train Loss: 0.852, Train Accuracy: 0.400
Train Loss: 1.222, Train Accuracy: 0.800
Train Loss: 1.177, Train Accuracy: 0.750
Train Loss: 1.250, Train Accuracy: 0.800
Train Loss: 1.749, Train Accuracy: 0.750
Train Loss: 0.940, Train Accuracy: 0.600
Train Loss: 1.877, Train Accuracy: 0.750
Train Loss: 1.262, Train Accuracy: 0.500
Round 47
Train Loss: 1.221, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.600
Train Loss: 0.816, Train Accuracy: 0.800
Train Loss: 1.189, Train Accuracy: 0.600
Train Loss: 1.135, Train Accuracy: 0.750
Train Loss: 1.256, Train Accuracy: 0.800
Train Loss: 1.755, Train Accuracy: 1.000
Train Loss: 0.994, Train Accuracy: 0.800
Train Loss: 1.819, Train Accuracy: 0.750
Train Loss: 0.976, Train Accuracy: 0.800
Round 48
Train Loss: 1.393, Train Accuracy: 1.000
Train Loss: 0.964, Train Accuracy: 0.400
Train Loss: 0.850, Train Accuracy: 0.200
Train Loss: 1.307, Train Accuracy: 0.400
Train Loss: 1.091, Train Accuracy: 0.750
Train Loss: 1.086, Train Accuracy: 0.800
Train Loss: 1.586, Train Accuracy: 0.750

(FLClient pid=2775439) 2025-05-02 19:06:42,134 - INFO - Epoch   2| Train Loss: 0.610| Train Accuracy: 0.700 [repeated 387x across cluster]
(FLClient pid=2775439) 2025-05-02 19:06:42,140 - INFO - Epoch   2| Validation Loss: 0.702, Validation Accuracy: 0.625 [repeated 129x across cluster]

Results saved to Pubmed_results474/Pubmed_full_GCN/results_Pubmed_full_GCN.txt

Running experiment with data_loading_option: adjacency, model_type: GCN
DEVICE: cuda
Data loading option is adjacency
Model type is GCN

2025-05-02 19:06:45,844	INFO worker.py:1816 -- Started a local Ray instance.

data_loading_option: adjacency
Data loaded
Device is cuda
Pubmed()
10

(FLClient pid=2778313) 2025-05-02 19:06:52,484 - INFO - Epoch   0| Train Loss: 1.089| Train Accuracy: 0.250
(FLClient pid=2778313) 2025-05-02 19:06:52,488 - INFO - Epoch   1| Train Loss: 0.868| Train Accuracy: 0.750
(FLClient pid=2778313) 2025-05-02 19:06:52,495 - INFO - Epoch   2| Train Loss: 0.758| Train Accuracy: 0.750
(FLClient pid=2778313) 2025-05-02 19:06:52,504 - INFO - Epoch   2| Validation Loss: 1.213, Validation Accuracy: 0.295
(FLClient pid=2778313) 2025-05-02 19:06:57,527 - INFO - Epoch   2| Train Loss: 0.653| Train Accuracy: 0.750 [repeated 360x across cluster]
(FLClient pid=2778313) 2025-05-02 19:06:57,532 - INFO - Epoch   2| Validation Loss: 1.389, Validation Accuracy: 0.295 [repeated 120x across cluster]
(FLClient pid=2778313) 2025-05-02 19:07:02,658 - INFO - Epoch   2| Train Loss: 0.536| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2778313) 2025-05-02 19:07:02,665 - INFO - Epoch   2| Validation Loss: 1.324, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2778313) 2025-05-02 19:07:07,811 - INFO - Epoch   2| Train Loss: 0.650| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2778313) 2025-05-02 19:07:07,819 - INFO - Epoch   2| Validation Loss: 1.218, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2778313) 2025-05-02 19:07:12,966 - INFO - Epoch   2| Train Loss: 0.385| Train Accuracy: 1.000 [repeated 450x across cluster]
(FLClient pid=2778313) 2025-05-02 19:07:12,974 - INFO - Epoch   2| Validation Loss: 1.125, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2778313) 2025-05-02 19:07:18,119 - INFO - Epoch   2| Train Loss: 0.326| Train Accuracy: 1.000 [repeated 450x across cluster]
(FLClient pid=2778313) 2025-05-02 19:07:18,122 - INFO - Epoch   2| Validation Loss: 0.915, Validation Accuracy: 0.477 [repeated 150x across cluster]
(FLClient pid=2778313) 2025-05-02 19:07:23,252 - INFO - Epoch   2| Train Loss: 0.360| Train Accuracy: 1.000 [repeated 450x across cluster]
(FLClient pid=2778313) 2025-05-02 19:07:23,256 - INFO - Epoch   2| Validation Loss: 1.382, Validation Accuracy: 0.295 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.213, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 1.203, Train Accuracy: 0.600
Train Loss: 1.195, Train Accuracy: 0.625
Train Loss: 1.239, Train Accuracy: 0.800
Train Loss: 1.363, Train Accuracy: 0.500
Train Loss: 1.150, Train Accuracy: 0.400
Train Loss: 1.432, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.300
Round 2
Train Loss: 1.255, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 1.281, Train Accuracy: 0.600
Train Loss: 1.205, Train Accuracy: 0.625
Train Loss: 1.248, Train Accuracy: 0.800
Train Loss: 1.383, Train Accuracy: 0.250
Train Loss: 1.149, Train Accuracy: 0.600
Train Loss: 1.485, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.500
Round 3
Train Loss: 1.222, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 1.297, Train Accuracy: 0.600
Train Loss: 1.217, Train Accuracy: 0.625
Train Loss: 1.281, Train Accuracy: 0.800
Train Loss: 1.421, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.600
Train Loss: 1.551, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.300
Round 4
Train Loss: 1.245, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.034, Train Accuracy: 0.400
Train Loss: 1.306, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.281, Train Accuracy: 0.800
Train Loss: 1.430, Train Accuracy: 0.750
Train Loss: 1.136, Train Accuracy: 0.400
Train Loss: 1.585, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.700
Round 5
Train Loss: 1.291, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.024, Train Accuracy: 0.400
Train Loss: 1.354, Train Accuracy: 0.800
Train Loss: 1.264, Train Accuracy: 0.625
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.443, Train Accuracy: 0.500
Train Loss: 1.176, Train Accuracy: 0.200
Train Loss: 1.660, Train Accuracy: 0.750
Train Loss: 1.199, Train Accuracy: 0.400
Round 6
Train Loss: 1.348, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.021, Train Accuracy: 0.200
Train Loss: 1.325, Train Accuracy: 0.600
Train Loss: 1.238, Train Accuracy: 0.625
Train Loss: 1.265, Train Accuracy: 0.800
Train Loss: 1.414, Train Accuracy: 0.750
Train Loss: 1.140, Train Accuracy: 0.600
Train Loss: 1.665, Train Accuracy: 0.750
Train Loss: 1.228, Train Accuracy: 0.600
Round 7
Train Loss: 1.326, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.338, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.469, Train Accuracy: 0.500
Train Loss: 1.149, Train Accuracy: 0.600
Train Loss: 1.684, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.400
Round 8
Train Loss: 1.308, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.500
Train Loss: 1.020, Train Accuracy: 0.400
Train Loss: 1.348, Train Accuracy: 0.600
Train Loss: 1.223, Train Accuracy: 0.625
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.446, Train Accuracy: 0.500
Train Loss: 1.181, Train Accuracy: 0.800
Train Loss: 1.787, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.300
Round 9
Train Loss: 1.307, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.800
Train Loss: 1.334, Train Accuracy: 0.600
Train Loss: 1.243, Train Accuracy: 0.750
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.581, Train Accuracy: 0.500
Train Loss: 1.156, Train Accuracy: 0.800
Train Loss: 1.679, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.400
Round 10
Train Loss: 1.259, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.485, Train Accuracy: 0.800
Train Loss: 1.248, Train Accuracy: 0.625
Train Loss: 1.321, Train Accuracy: 0.800
Train Loss: 1.547, Train Accuracy: 1.000
Train Loss: 1.205, Train Accuracy: 0.400
Train Loss: 1.656, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.400
Round 11
Train Loss: 1.319, Train Accuracy: 0.750
Train Loss: 1.059, Train Accuracy: 0.700
Train Loss: 1.009, Train Accuracy: 0.400
Train Loss: 1.387, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.625
Train Loss: 1.293, Train Accuracy: 0.800
Train Loss: 1.567, Train Accuracy: 0.750
Train Loss: 1.134, Train Accuracy: 0.200
Train Loss: 1.988, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.700
Round 12
Train Loss: 1.236, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.500
Train Loss: 1.032, Train Accuracy: 0.600
Train Loss: 1.385, Train Accuracy: 0.600
Train Loss: 1.232, Train Accuracy: 0.500
Train Loss: 1.337, Train Accuracy: 0.800
Train Loss: 1.492, Train Accuracy: 1.000
Train Loss: 1.210, Train Accuracy: 0.600
Train Loss: 1.782, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.600
Round 13
Train Loss: 1.389, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.500
Train Loss: 1.002, Train Accuracy: 0.800
Train Loss: 1.435, Train Accuracy: 0.800
Train Loss: 1.257, Train Accuracy: 0.750
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.525, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.800
Train Loss: 1.722, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.300
Round 14
Train Loss: 1.376, Train Accuracy: 0.750
Train Loss: 1.063, Train Accuracy: 0.500
Train Loss: 1.004, Train Accuracy: 0.600
Train Loss: 1.418, Train Accuracy: 0.800
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.575, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.400
Train Loss: 1.930, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.500
Round 15
Train Loss: 1.253, Train Accuracy: 0.750
Train Loss: 1.055, Train Accuracy: 0.600
Train Loss: 1.013, Train Accuracy: 0.600
Train Loss: 1.364, Train Accuracy: 0.600
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.342, Train Accuracy: 0.800
Train Loss: 1.658, Train Accuracy: 0.500
Train Loss: 1.091, Train Accuracy: 0.600
Train Loss: 2.006, Train Accuracy: 0.750
Train Loss: 1.131, Train Accuracy: 0.500
Round 16
Train Loss: 1.371, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 0.500
Train Loss: 1.007, Train Accuracy: 0.400
Train Loss: 1.421, Train Accuracy: 0.800
Train Loss: 1.207, Train Accuracy: 0.750
Train Loss: 1.379, Train Accuracy: 0.800
Train Loss: 1.473, Train Accuracy: 0.250
Train Loss: 1.118, Train Accuracy: 0.600
Train Loss: 1.834, Train Accuracy: 0.750
Train Loss: 1.255, Train Accuracy: 0.600
Round 17
Train Loss: 1.306, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.700
Train Loss: 0.990, Train Accuracy: 0.800
Train Loss: 1.333, Train Accuracy: 0.400
Train Loss: 1.215, Train Accuracy: 0.750
Train Loss: 1.367, Train Accuracy: 0.800
Train Loss: 1.631, Train Accuracy: 0.500
Train Loss: 1.172, Train Accuracy: 0.400
Train Loss: 1.866, Train Accuracy: 0.750
Train Loss: 1.211, Train Accuracy: 0.500
Round 18
Train Loss: 1.298, Train Accuracy: 0.750
Train Loss: 1.040, Train Accuracy: 0.800
Train Loss: 0.992, Train Accuracy: 0.400
Train Loss: 1.339, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.574, Train Accuracy: 0.250
Train Loss: 1.113, Train Accuracy: 0.600
Train Loss: 1.893, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.500
Round 19
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 0.978, Train Accuracy: 0.400
Train Loss: 1.327, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.875
Train Loss: 1.327, Train Accuracy: 0.800
Train Loss: 1.476, Train Accuracy: 0.750
Train Loss: 1.124, Train Accuracy: 0.800
Train Loss: 1.801, Train Accuracy: 0.750
Train Loss: 1.116, Train Accuracy: 0.700
Round 20
Train Loss: 1.346, Train Accuracy: 0.750
Train Loss: 1.034, Train Accuracy: 0.700
Train Loss: 0.979, Train Accuracy: 0.600
Train Loss: 1.387, Train Accuracy: 0.600
Train Loss: 1.187, Train Accuracy: 0.750
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.552, Train Accuracy: 0.500
Train Loss: 1.160, Train Accuracy: 0.600
Train Loss: 1.932, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.400
Round 21
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 1.027, Train Accuracy: 0.500
Train Loss: 0.988, Train Accuracy: 0.400
Train Loss: 1.341, Train Accuracy: 1.000
Train Loss: 1.210, Train Accuracy: 0.625
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.509, Train Accuracy: 1.000
Train Loss: 1.079, Train Accuracy: 0.400
Train Loss: 1.878, Train Accuracy: 0.750
Train Loss: 1.238, Train Accuracy: 0.700
Round 22
Train Loss: 1.345, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.500
Train Loss: 0.968, Train Accuracy: 0.800
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.236, Train Accuracy: 0.625
Train Loss: 1.347, Train Accuracy: 0.800
Train Loss: 1.578, Train Accuracy: 0.750
Train Loss: 1.275, Train Accuracy: 0.400
Train Loss: 1.788, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.500
Round 23
Train Loss: 1.395, Train Accuracy: 0.750
Train Loss: 1.025, Train Accuracy: 0.700
Train Loss: 0.997, Train Accuracy: 0.600
Train Loss: 1.374, Train Accuracy: 0.600
Train Loss: 1.188, Train Accuracy: 0.750
Train Loss: 1.423, Train Accuracy: 0.800
Train Loss: 1.760, Train Accuracy: 0.750
Train Loss: 1.121, Train Accuracy: 0.800
Train Loss: 1.839, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.600
Round 24
Train Loss: 1.438, Train Accuracy: 0.750
Train Loss: 1.025, Train Accuracy: 0.500
Train Loss: 0.986, Train Accuracy: 0.600
Train Loss: 1.411, Train Accuracy: 0.800
Train Loss: 1.193, Train Accuracy: 0.750
Train Loss: 1.313, Train Accuracy: 0.800
Train Loss: 1.538, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.600
Train Loss: 1.929, Train Accuracy: 1.000
Train Loss: 1.083, Train Accuracy: 0.400
Round 25
Train Loss: 1.245, Train Accuracy: 0.750
Train Loss: 1.009, Train Accuracy: 0.700
Train Loss: 0.965, Train Accuracy: 0.600
Train Loss: 1.350, Train Accuracy: 1.000
Train Loss: 1.177, Train Accuracy: 0.750
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.646, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.600
Train Loss: 1.692, Train Accuracy: 0.750
Train Loss: 1.111, Train Accuracy: 0.500
Round 26
Train Loss: 1.369, Train Accuracy: 0.750
Train Loss: 1.004, Train Accuracy: 0.600
Train Loss: 0.957, Train Accuracy: 0.800
Train Loss: 1.479, Train Accuracy: 0.800
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 1.402, Train Accuracy: 0.800
Train Loss: 1.549, Train Accuracy: 0.750
Train Loss: 1.105, Train Accuracy: 0.600
Train Loss: 2.010, Train Accuracy: 1.000
Train Loss: 1.186, Train Accuracy: 0.600
Round 27
Train Loss: 1.164, Train Accuracy: 0.750
Train Loss: 0.999, Train Accuracy: 0.600
Train Loss: 0.970, Train Accuracy: 0.600
Train Loss: 1.519, Train Accuracy: 0.800
Train Loss: 1.171, Train Accuracy: 0.750
Train Loss: 1.350, Train Accuracy: 0.800
Train Loss: 1.704, Train Accuracy: 1.000
Train Loss: 1.105, Train Accuracy: 0.600
Train Loss: 1.716, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.500
Round 28
Train Loss: 1.324, Train Accuracy: 0.750
Train Loss: 0.994, Train Accuracy: 0.600
Train Loss: 0.953, Train Accuracy: 0.400
Train Loss: 1.373, Train Accuracy: 1.000
Train Loss: 1.181, Train Accuracy: 0.750
Train Loss: 1.383, Train Accuracy: 0.800
Train Loss: 1.700, Train Accuracy: 0.500
Train Loss: 1.149, Train Accuracy: 0.600
Train Loss: 1.825, Train Accuracy: 0.750
Train Loss: 1.283, Train Accuracy: 0.600
Round 29
Train Loss: 1.426, Train Accuracy: 0.750
Train Loss: 1.024, Train Accuracy: 0.700
Train Loss: 0.958, Train Accuracy: 0.800
Train Loss: 1.460, Train Accuracy: 1.000
Train Loss: 1.211, Train Accuracy: 0.625
Train Loss: 1.372, Train Accuracy: 0.800
Train Loss: 1.469, Train Accuracy: 0.750
Train Loss: 1.157, Train Accuracy: 0.400
Train Loss: 1.885, Train Accuracy: 0.750
Train Loss: 1.217, Train Accuracy: 0.600
Round 30
Train Loss: 1.306, Train Accuracy: 0.750
Train Loss: 0.982, Train Accuracy: 0.600
Train Loss: 0.967, Train Accuracy: 0.600
Train Loss: 1.387, Train Accuracy: 0.800
Train Loss: 1.104, Train Accuracy: 0.875
Train Loss: 1.391, Train Accuracy: 0.800
Train Loss: 1.609, Train Accuracy: 1.000
Train Loss: 1.165, Train Accuracy: 0.600
Train Loss: 2.102, Train Accuracy: 0.750
Train Loss: 1.286, Train Accuracy: 0.700
Round 31
Train Loss: 1.290, Train Accuracy: 0.750
Train Loss: 1.005, Train Accuracy: 0.600
Train Loss: 0.954, Train Accuracy: 0.400
Train Loss: 1.345, Train Accuracy: 0.800
Train Loss: 1.147, Train Accuracy: 0.750
Train Loss: 1.336, Train Accuracy: 0.800
Train Loss: 1.651, Train Accuracy: 0.500
Train Loss: 1.118, Train Accuracy: 0.600
Train Loss: 1.948, Train Accuracy: 0.750
Train Loss: 1.167, Train Accuracy: 0.800
Round 32
Train Loss: 1.288, Train Accuracy: 0.750
Train Loss: 0.992, Train Accuracy: 0.600
Train Loss: 0.982, Train Accuracy: 0.600
Train Loss: 1.576, Train Accuracy: 0.600
Train Loss: 1.176, Train Accuracy: 0.500
Train Loss: 1.300, Train Accuracy: 0.800
Train Loss: 1.528, Train Accuracy: 0.500
Train Loss: 1.030, Train Accuracy: 0.800
Train Loss: 1.817, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.700
Round 33
Train Loss: 1.292, Train Accuracy: 0.750
Train Loss: 0.979, Train Accuracy: 0.800
Train Loss: 0.922, Train Accuracy: 0.600
Train Loss: 1.337, Train Accuracy: 1.000
Train Loss: 1.194, Train Accuracy: 0.500
Train Loss: 1.336, Train Accuracy: 0.800
Train Loss: 1.583, Train Accuracy: 0.500
Train Loss: 1.073, Train Accuracy: 0.600
Train Loss: 1.841, Train Accuracy: 0.750
Train Loss: 1.155, Train Accuracy: 0.700
Round 34
Train Loss: 1.249, Train Accuracy: 0.750
Train Loss: 0.974, Train Accuracy: 0.700
Train Loss: 0.976, Train Accuracy: 0.600
Train Loss: 1.370, Train Accuracy: 1.000
Train Loss: 1.133, Train Accuracy: 0.500
Train Loss: 1.293, Train Accuracy: 0.800
Train Loss: 1.652, Train Accuracy: 1.000
Train Loss: 1.099, Train Accuracy: 1.000
Train Loss: 1.970, Train Accuracy: 0.750
Train Loss: 1.351, Train Accuracy: 0.600
Round 35
Train Loss: 1.425, Train Accuracy: 1.000
Train Loss: 0.974, Train Accuracy: 0.700
Train Loss: 0.934, Train Accuracy: 1.000
Train Loss: 1.361, Train Accuracy: 1.000
Train Loss: 1.218, Train Accuracy: 0.500
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.547, Train Accuracy: 0.500
Train Loss: 1.073, Train Accuracy: 0.400
Train Loss: 2.182, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.500
Round 36
Train Loss: 1.168, Train Accuracy: 0.750
Train Loss: 0.973, Train Accuracy: 0.400
Train Loss: 0.933, Train Accuracy: 0.600
Train Loss: 1.505, Train Accuracy: 0.800
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.295, Train Accuracy: 0.800
Train Loss: 1.493, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 1.000
Train Loss: 1.972, Train Accuracy: 0.750
Train Loss: 1.333, Train Accuracy: 0.600
Round 37
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 0.978, Train Accuracy: 0.600
Train Loss: 0.899, Train Accuracy: 0.400
Train Loss: 1.469, Train Accuracy: 0.600
Train Loss: 1.200, Train Accuracy: 0.500
Train Loss: 1.343, Train Accuracy: 0.800
Train Loss: 1.464, Train Accuracy: 1.000
Train Loss: 1.054, Train Accuracy: 0.600
Train Loss: 1.947, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.700
Round 38
Train Loss: 1.274, Train Accuracy: 0.750
Train Loss: 0.968, Train Accuracy: 0.700
Train Loss: 0.894, Train Accuracy: 0.400
Train Loss: 1.274, Train Accuracy: 1.000
Train Loss: 1.158, Train Accuracy: 0.750
Train Loss: 1.358, Train Accuracy: 0.800
Train Loss: 1.547, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.800
Train Loss: 2.043, Train Accuracy: 1.000
Train Loss: 1.099, Train Accuracy: 0.600
Round 39
Train Loss: 1.198, Train Accuracy: 0.750
Train Loss: 0.969, Train Accuracy: 0.600
Train Loss: 0.986, Train Accuracy: 0.600
Train Loss: 1.388, Train Accuracy: 1.000
Train Loss: 1.154, Train Accuracy: 0.250
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.477, Train Accuracy: 1.000
Train Loss: 1.065, Train Accuracy: 0.600
Train Loss: 1.881, Train Accuracy: 0.750
Train Loss: 0.984, Train Accuracy: 0.700
Round 40
Train Loss: 1.156, Train Accuracy: 0.750
Train Loss: 0.955, Train Accuracy: 0.600
Train Loss: 0.914, Train Accuracy: 0.800
Train Loss: 1.586, Train Accuracy: 0.600
Train Loss: 1.251, Train Accuracy: 0.625
Train Loss: 1.160, Train Accuracy: 0.800
Train Loss: 1.534, Train Accuracy: 1.000
Train Loss: 1.098, Train Accuracy: 1.000
Train Loss: 1.793, Train Accuracy: 0.750
Train Loss: 1.253, Train Accuracy: 0.400
Round 41
Train Loss: 1.205, Train Accuracy: 0.750
Train Loss: 0.997, Train Accuracy: 0.700
Train Loss: 0.933, Train Accuracy: 0.800
Train Loss: 1.340, Train Accuracy: 1.000
Train Loss: 1.133, Train Accuracy: 0.500
Train Loss: 1.351, Train Accuracy: 0.800
Train Loss: 1.805, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.600
Train Loss: 1.927, Train Accuracy: 1.000
Train Loss: 1.389, Train Accuracy: 0.700
Round 42
Train Loss: 1.460, Train Accuracy: 0.750
Train Loss: 0.955, Train Accuracy: 0.600
Train Loss: 0.926, Train Accuracy: 0.600
Train Loss: 1.670, Train Accuracy: 0.800
Train Loss: 1.282, Train Accuracy: 0.625
Train Loss: 1.291, Train Accuracy: 0.800
Train Loss: 1.596, Train Accuracy: 1.000
Train Loss: 0.997, Train Accuracy: 0.600
Train Loss: 2.152, Train Accuracy: 1.000
Train Loss: 1.128, Train Accuracy: 0.800
Round 43
Train Loss: 1.218, Train Accuracy: 0.750
Train Loss: 0.970, Train Accuracy: 0.600
Train Loss: 0.941, Train Accuracy: 0.800
Train Loss: 1.379, Train Accuracy: 1.000
Train Loss: 1.117, Train Accuracy: 0.500
Train Loss: 1.278, Train Accuracy: 0.800
Train Loss: 1.434, Train Accuracy: 1.000
Train Loss: 1.063, Train Accuracy: 0.400
Train Loss: 1.976, Train Accuracy: 1.000
Train Loss: 1.388, Train Accuracy: 0.500
Round 44
Train Loss: 1.151, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.600
Train Loss: 1.007, Train Accuracy: 0.600
Train Loss: 1.370, Train Accuracy: 0.800
Train Loss: 1.141, Train Accuracy: 0.750
Train Loss: 1.301, Train Accuracy: 0.800
Train Loss: 1.692, Train Accuracy: 0.750
Train Loss: 1.004, Train Accuracy: 0.600
Train Loss: 2.234, Train Accuracy: 1.000
Train Loss: 1.069, Train Accuracy: 0.500
Round 45
Train Loss: 1.063, Train Accuracy: 0.750
Train Loss: 1.086, Train Accuracy: 0.700
Train Loss: 0.903, Train Accuracy: 0.800
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.147, Train Accuracy: 0.500
Train Loss: 1.256, Train Accuracy: 0.800
Train Loss: 1.635, Train Accuracy: 0.750
Train Loss: 0.996, Train Accuracy: 0.600
Train Loss: 1.739, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.600
Round 46
Train Loss: 1.297, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.700
Train Loss: 0.849, Train Accuracy: 0.400
Train Loss: 1.310, Train Accuracy: 1.000
Train Loss: 1.237, Train Accuracy: 0.750
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.494, Train Accuracy: 1.000
Train Loss: 0.984, Train Accuracy: 0.600
Train Loss: 1.893, Train Accuracy: 0.750
Train Loss: 1.336, Train Accuracy: 0.500
Round 47
Train Loss: 1.202, Train Accuracy: 0.750
Train Loss: 0.926, Train Accuracy: 0.600
Train Loss: 0.909, Train Accuracy: 0.400
Train Loss: 1.611, Train Accuracy: 0.800
Train Loss: 1.081, Train Accuracy: 0.375
Train Loss: 1.338, Train Accuracy: 0.800
Train Loss: 1.468, Train Accuracy: 1.000
Train Loss: 0.946, Train Accuracy: 0.600
Train Loss: 1.743, Train Accuracy: 0.750
Train Loss: 1.106, Train Accuracy: 0.700
Round 48
Train Loss: 1.273, Train Accuracy: 0.750
Train Loss: 0.905, Train Accuracy: 0.800
Train Loss: 0.979, Train Accuracy: 0.200
Train Loss: 1.471, Train Accuracy: 1.000
Train Loss: 1.138, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.800
Train Loss: 1.663, Train Accuracy: 0.750

(FLClient pid=2778314) 2025-05-02 19:07:35,170 - INFO - Epoch   0| Train Loss: 1.096| Train Accuracy: 0.500 [repeated 388x across cluster]
(FLClient pid=2778323) 2025-05-02 19:07:27,356 - INFO - Epoch   2| Validation Loss: 1.302, Validation Accuracy: 0.250 [repeated 129x across cluster]
(FLClient pid=2778314) 2025-05-02 19:07:40,133 - INFO - Epoch   2| Train Loss: 0.718| Train Accuracy: 0.750 [repeated 392x across cluster]
(FLClient pid=2778314) 2025-05-02 19:07:40,141 - INFO - Epoch   2| Validation Loss: 1.139, Validation Accuracy: 0.295 [repeated 131x across cluster]
(FLClient pid=2778314) 2025-05-02 19:07:45,288 - INFO - Epoch   2| Train Loss: 0.509| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2778314) 2025-05-02 19:07:45,295 - INFO - Epoch   2| Validation Loss: 1.342, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2778314) 2025-05-02 19:07:50,426 - INFO - Epoch   2| Train Loss: 0.545| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2778314) 2025-05-02 19:07:50,431 - INFO - Epoch   2| Validation Loss: 1.181, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2778318) 2025-05-02 19:07:55,535 - INFO - Epoch   0| Train Loss: 0.844| Train Accuracy: 0.600 [repeated 448x across cluster]
(FLClient pid=2778324) 2025-05-02 19:07:55,225 - INFO - Epoch   2| Validation Loss: 1.356, Validation Accuracy: 0.156 [repeated 149x across cluster]
(FLClient pid=2778314) 2025-05-02 19:08:00,681 - INFO - Epoch   1| Train Loss: 0.390| Train Accuracy: 0.750 [repeated 451x across cluster]
(FLClient pid=2778324) 2025-05-02 19:08:00,359 - INFO - Epoch   2| Validation Loss: 1.523, Validation Accuracy: 0.172 [repeated 150x across cluster]
(FLClient pid=2778314) 2025-05-02 19:08:05,815 - INFO - Epoch   1| Train Loss: 0.395| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2778324) 2025-05-02 19:08:05,490 - INFO - Epoch   2| Validation Loss: 0.926, Validation Accuracy: 0.516 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 1.081, Train Accuracy: 0.500
Train Loss: 1.070, Train Accuracy: 0.200
Train Loss: 1.227, Train Accuracy: 0.600
Train Loss: 1.198, Train Accuracy: 0.625
Train Loss: 1.279, Train Accuracy: 0.800
Train Loss: 1.305, Train Accuracy: 0.250
Train Loss: 1.143, Train Accuracy: 0.600
Train Loss: 1.388, Train Accuracy: 0.750
Train Loss: 1.164, Train Accuracy: 0.300
Round 2
Train Loss: 1.274, Train Accuracy: 0.750
Train Loss: 1.083, Train Accuracy: 0.500
Train Loss: 1.057, Train Accuracy: 0.400
Train Loss: 1.247, Train Accuracy: 0.600
Train Loss: 1.202, Train Accuracy: 0.625
Train Loss: 1.287, Train Accuracy: 0.800
Train Loss: 1.345, Train Accuracy: 0.250
Train Loss: 1.158, Train Accuracy: 0.600
Train Loss: 1.484, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.400
Round 3
Train Loss: 1.288, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Train Loss: 1.056, Train Accuracy: 0.400
Train Loss: 1.271, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.252, Train Accuracy: 0.800
Train Loss: 1.389, Train Accuracy: 0.500
Train Loss: 1.163, Train Accuracy: 0.400
Train Loss: 1.544, Train Accuracy: 0.750
Train Loss: 1.203, Train Accuracy: 0.400
Round 4
Train Loss: 1.336, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.040, Train Accuracy: 0.400
Train Loss: 1.291, Train Accuracy: 0.600
Train Loss: 1.221, Train Accuracy: 0.625
Train Loss: 1.259, Train Accuracy: 0.800
Train Loss: 1.438, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.600
Train Loss: 1.548, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.400
Round 5
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.500
Train Loss: 1.045, Train Accuracy: 0.600
Train Loss: 1.297, Train Accuracy: 0.600
Train Loss: 1.235, Train Accuracy: 0.625
Train Loss: 1.268, Train Accuracy: 0.800
Train Loss: 1.443, Train Accuracy: 0.250
Train Loss: 1.171, Train Accuracy: 0.600
Train Loss: 1.614, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.400
Round 6
Train Loss: 1.321, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.400
Train Loss: 1.040, Train Accuracy: 0.400
Train Loss: 1.320, Train Accuracy: 0.600
Train Loss: 1.232, Train Accuracy: 0.625
Train Loss: 1.285, Train Accuracy: 0.800
Train Loss: 1.430, Train Accuracy: 0.500
Train Loss: 1.178, Train Accuracy: 0.400
Train Loss: 1.702, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 0.400
Round 7
Train Loss: 1.290, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.350, Train Accuracy: 0.600
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.298, Train Accuracy: 0.800
Train Loss: 1.466, Train Accuracy: 0.750
Train Loss: 1.193, Train Accuracy: 0.600
Train Loss: 1.741, Train Accuracy: 0.750
Train Loss: 1.170, Train Accuracy: 0.500
Round 8
Train Loss: 1.381, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Train Loss: 1.040, Train Accuracy: 0.600
Train Loss: 1.324, Train Accuracy: 0.600
Train Loss: 1.260, Train Accuracy: 0.625
Train Loss: 1.272, Train Accuracy: 0.800
Train Loss: 1.497, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.600
Train Loss: 1.688, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.600
Round 9
Train Loss: 1.347, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.600
Train Loss: 1.031, Train Accuracy: 0.400
Train Loss: 1.361, Train Accuracy: 0.600
Train Loss: 1.260, Train Accuracy: 0.625
Train Loss: 1.305, Train Accuracy: 0.800
Train Loss: 1.500, Train Accuracy: 0.500
Train Loss: 1.206, Train Accuracy: 0.800
Train Loss: 1.705, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.500
Round 10
Train Loss: 1.260, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 1.347, Train Accuracy: 0.600
Train Loss: 1.254, Train Accuracy: 0.625
Train Loss: 1.321, Train Accuracy: 0.800
Train Loss: 1.476, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.200
Train Loss: 1.746, Train Accuracy: 0.750
Train Loss: 1.204, Train Accuracy: 0.500
Round 11
Train Loss: 1.383, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.400
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.424, Train Accuracy: 0.800
Train Loss: 1.258, Train Accuracy: 0.625
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.462, Train Accuracy: 0.500
Train Loss: 1.166, Train Accuracy: 0.600
Train Loss: 1.811, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.400
Round 12
Train Loss: 1.280, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.500
Train Loss: 1.015, Train Accuracy: 0.400
Train Loss: 1.352, Train Accuracy: 0.600
Train Loss: 1.266, Train Accuracy: 0.625
Train Loss: 1.360, Train Accuracy: 0.800
Train Loss: 1.458, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.600
Train Loss: 1.784, Train Accuracy: 0.750
Train Loss: 1.208, Train Accuracy: 0.700
Round 13
Train Loss: 1.244, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Train Loss: 1.015, Train Accuracy: 0.400
Train Loss: 1.352, Train Accuracy: 0.600
Train Loss: 1.261, Train Accuracy: 0.500
Train Loss: 1.261, Train Accuracy: 0.800
Train Loss: 1.542, Train Accuracy: 0.250
Train Loss: 1.169, Train Accuracy: 0.600
Train Loss: 1.885, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.500
Round 14
Train Loss: 1.139, Train Accuracy: 0.750
Train Loss: 1.066, Train Accuracy: 0.500
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.323, Train Accuracy: 0.600
Train Loss: 1.277, Train Accuracy: 0.625
Train Loss: 1.313, Train Accuracy: 0.800
Train Loss: 1.517, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.200
Train Loss: 1.859, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.700
Round 15
Train Loss: 1.193, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.500
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.473, Train Accuracy: 0.600
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.561, Train Accuracy: 0.500
Train Loss: 1.174, Train Accuracy: 0.400
Train Loss: 1.822, Train Accuracy: 0.750
Train Loss: 1.146, Train Accuracy: 0.400
Round 16
Train Loss: 1.433, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.500
Train Loss: 1.000, Train Accuracy: 0.600
Train Loss: 1.394, Train Accuracy: 0.600
Train Loss: 1.233, Train Accuracy: 0.625
Train Loss: 1.264, Train Accuracy: 0.800
Train Loss: 1.551, Train Accuracy: 0.500
Train Loss: 1.176, Train Accuracy: 0.800
Train Loss: 1.792, Train Accuracy: 0.750
Train Loss: 1.265, Train Accuracy: 0.500
Round 17
Train Loss: 1.306, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.500
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 1.371, Train Accuracy: 0.600
Train Loss: 1.246, Train Accuracy: 0.625
Train Loss: 1.306, Train Accuracy: 0.800
Train Loss: 1.479, Train Accuracy: 0.500
Train Loss: 1.187, Train Accuracy: 0.400
Train Loss: 1.833, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.500
Round 18
Train Loss: 1.347, Train Accuracy: 0.750
Train Loss: 1.057, Train Accuracy: 0.500
Train Loss: 1.013, Train Accuracy: 0.400
Train Loss: 1.446, Train Accuracy: 1.000
Train Loss: 1.252, Train Accuracy: 0.625
Train Loss: 1.345, Train Accuracy: 0.800
Train Loss: 1.533, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.600
Train Loss: 1.761, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.600
Round 19
Train Loss: 1.333, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.700
Train Loss: 0.995, Train Accuracy: 0.600
Train Loss: 1.380, Train Accuracy: 0.800
Train Loss: 1.197, Train Accuracy: 0.750
Train Loss: 1.372, Train Accuracy: 0.800
Train Loss: 1.494, Train Accuracy: 0.500
Train Loss: 1.171, Train Accuracy: 0.000
Train Loss: 1.987, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.300
Round 20
Train Loss: 1.263, Train Accuracy: 0.750
Train Loss: 1.044, Train Accuracy: 0.500
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.383, Train Accuracy: 0.600
Train Loss: 1.167, Train Accuracy: 0.625
Train Loss: 1.345, Train Accuracy: 0.800
Train Loss: 1.524, Train Accuracy: 0.500
Train Loss: 1.250, Train Accuracy: 0.800
Train Loss: 1.827, Train Accuracy: 0.750
Train Loss: 1.179, Train Accuracy: 0.600
Round 21
Train Loss: 1.330, Train Accuracy: 0.750
Train Loss: 1.045, Train Accuracy: 0.700
Train Loss: 0.992, Train Accuracy: 0.400
Train Loss: 1.265, Train Accuracy: 0.600
Train Loss: 1.239, Train Accuracy: 0.625
Train Loss: 1.332, Train Accuracy: 0.800
Train Loss: 1.431, Train Accuracy: 0.250
Train Loss: 1.157, Train Accuracy: 0.800
Train Loss: 1.959, Train Accuracy: 1.000
Train Loss: 1.172, Train Accuracy: 0.600
Round 22
Train Loss: 1.329, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.500
Train Loss: 0.997, Train Accuracy: 0.400
Train Loss: 1.321, Train Accuracy: 0.600
Train Loss: 1.215, Train Accuracy: 0.750
Train Loss: 1.310, Train Accuracy: 0.800
Train Loss: 1.571, Train Accuracy: 0.500
Train Loss: 1.153, Train Accuracy: 0.600
Train Loss: 1.797, Train Accuracy: 0.750
Train Loss: 1.094, Train Accuracy: 0.300
Round 23
Train Loss: 1.409, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.600
Train Loss: 0.989, Train Accuracy: 0.400
Train Loss: 1.372, Train Accuracy: 1.000
Train Loss: 1.208, Train Accuracy: 0.750
Train Loss: 1.445, Train Accuracy: 1.000
Train Loss: 1.529, Train Accuracy: 1.000
Train Loss: 1.107, Train Accuracy: 0.800
Train Loss: 1.823, Train Accuracy: 0.750
Train Loss: 1.168, Train Accuracy: 0.300
Round 24
Train Loss: 1.230, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.500
Train Loss: 0.986, Train Accuracy: 0.400
Train Loss: 1.385, Train Accuracy: 0.600
Train Loss: 1.222, Train Accuracy: 0.750
Train Loss: 1.408, Train Accuracy: 0.800
Train Loss: 1.493, Train Accuracy: 0.500
Train Loss: 1.220, Train Accuracy: 0.800
Train Loss: 1.852, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.600
Round 25
Train Loss: 1.301, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.500
Train Loss: 0.970, Train Accuracy: 0.600
Train Loss: 1.347, Train Accuracy: 1.000
Train Loss: 1.180, Train Accuracy: 0.875
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.506, Train Accuracy: 0.500
Train Loss: 1.181, Train Accuracy: 0.800
Train Loss: 1.881, Train Accuracy: 0.750
Train Loss: 1.133, Train Accuracy: 0.500
Round 26
Train Loss: 1.414, Train Accuracy: 0.750
Train Loss: 1.033, Train Accuracy: 0.400
Train Loss: 0.983, Train Accuracy: 0.400
Train Loss: 1.305, Train Accuracy: 0.800
Train Loss: 1.247, Train Accuracy: 0.625
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.506, Train Accuracy: 1.000
Train Loss: 1.095, Train Accuracy: 0.600
Train Loss: 2.066, Train Accuracy: 0.750
Train Loss: 1.276, Train Accuracy: 0.400
Round 27
Train Loss: 1.305, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.600
Train Loss: 0.959, Train Accuracy: 0.400
Train Loss: 1.286, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.750
Train Loss: 1.419, Train Accuracy: 0.800
Train Loss: 1.535, Train Accuracy: 1.000
Train Loss: 1.138, Train Accuracy: 0.600
Train Loss: 1.926, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.400
Round 28
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.500
Train Loss: 0.962, Train Accuracy: 0.800
Train Loss: 1.362, Train Accuracy: 0.800
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.461, Train Accuracy: 0.750
Train Loss: 1.171, Train Accuracy: 0.600
Train Loss: 1.721, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.500
Round 29
Train Loss: 1.342, Train Accuracy: 0.750
Train Loss: 1.003, Train Accuracy: 0.400
Train Loss: 0.967, Train Accuracy: 0.400
Train Loss: 1.254, Train Accuracy: 0.800
Train Loss: 1.164, Train Accuracy: 0.875
Train Loss: 1.318, Train Accuracy: 0.800
Train Loss: 1.530, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.600
Train Loss: 2.065, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.500
Round 30
Train Loss: 1.406, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.400
Train Loss: 0.974, Train Accuracy: 0.800
Train Loss: 1.487, Train Accuracy: 1.000
Train Loss: 1.183, Train Accuracy: 0.750
Train Loss: 1.260, Train Accuracy: 0.800
Train Loss: 1.521, Train Accuracy: 0.750
Train Loss: 1.092, Train Accuracy: 0.600
Train Loss: 1.869, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.800
Round 31
Train Loss: 1.218, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.500
Train Loss: 0.985, Train Accuracy: 0.400
Train Loss: 1.417, Train Accuracy: 0.800
Train Loss: 1.153, Train Accuracy: 0.750
Train Loss: 1.369, Train Accuracy: 0.800
Train Loss: 1.344, Train Accuracy: 0.500
Train Loss: 1.060, Train Accuracy: 0.800
Train Loss: 1.912, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.700
Round 32
Train Loss: 1.275, Train Accuracy: 0.750
Train Loss: 1.017, Train Accuracy: 0.700
Train Loss: 0.953, Train Accuracy: 0.400
Train Loss: 1.342, Train Accuracy: 1.000
Train Loss: 1.135, Train Accuracy: 0.750
Train Loss: 1.345, Train Accuracy: 0.800
Train Loss: 1.773, Train Accuracy: 0.500
Train Loss: 1.171, Train Accuracy: 0.600
Train Loss: 1.871, Train Accuracy: 0.750
Train Loss: 1.286, Train Accuracy: 0.400
Round 33
Train Loss: 1.357, Train Accuracy: 0.750
Train Loss: 1.013, Train Accuracy: 0.500
Train Loss: 0.957, Train Accuracy: 0.400
Train Loss: 1.295, Train Accuracy: 1.000
Train Loss: 1.189, Train Accuracy: 0.750
Train Loss: 1.360, Train Accuracy: 0.800
Train Loss: 1.515, Train Accuracy: 0.750
Train Loss: 1.098, Train Accuracy: 0.800
Train Loss: 1.686, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.700
Round 34
Train Loss: 1.310, Train Accuracy: 0.750
Train Loss: 0.976, Train Accuracy: 0.700
Train Loss: 0.949, Train Accuracy: 0.600
Train Loss: 1.286, Train Accuracy: 1.000
Train Loss: 1.166, Train Accuracy: 0.625
Train Loss: 1.327, Train Accuracy: 0.800
Train Loss: 1.413, Train Accuracy: 1.000
Train Loss: 1.087, Train Accuracy: 0.600
Train Loss: 2.072, Train Accuracy: 0.750
Train Loss: 1.288, Train Accuracy: 0.600
Round 35
Train Loss: 1.322, Train Accuracy: 1.000
Train Loss: 0.988, Train Accuracy: 0.600
Train Loss: 0.970, Train Accuracy: 0.400
Train Loss: 1.366, Train Accuracy: 1.000
Train Loss: 1.187, Train Accuracy: 0.625
Train Loss: 1.342, Train Accuracy: 0.800
Train Loss: 1.616, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.800
Train Loss: 2.159, Train Accuracy: 0.750
Train Loss: 1.203, Train Accuracy: 0.500
Round 36
Train Loss: 1.216, Train Accuracy: 0.750
Train Loss: 0.986, Train Accuracy: 0.700
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.263, Train Accuracy: 1.000
Train Loss: 1.111, Train Accuracy: 0.625
Train Loss: 1.319, Train Accuracy: 0.800
Train Loss: 1.445, Train Accuracy: 0.500
Train Loss: 1.153, Train Accuracy: 0.800
Train Loss: 1.887, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.400
Round 37
Train Loss: 1.188, Train Accuracy: 0.750
Train Loss: 0.966, Train Accuracy: 0.600
Train Loss: 0.949, Train Accuracy: 0.600
Train Loss: 1.243, Train Accuracy: 0.800
Train Loss: 1.093, Train Accuracy: 0.750
Train Loss: 1.345, Train Accuracy: 0.800
Train Loss: 1.448, Train Accuracy: 0.750
Train Loss: 1.101, Train Accuracy: 0.600
Train Loss: 1.912, Train Accuracy: 0.750
Train Loss: 1.111, Train Accuracy: 0.700
Round 38
Train Loss: 1.196, Train Accuracy: 0.750
Train Loss: 0.980, Train Accuracy: 0.600
Train Loss: 0.953, Train Accuracy: 0.800
Train Loss: 1.377, Train Accuracy: 1.000
Train Loss: 1.130, Train Accuracy: 0.375
Train Loss: 1.251, Train Accuracy: 0.800
Train Loss: 1.695, Train Accuracy: 0.500
Train Loss: 1.071, Train Accuracy: 0.800
Train Loss: 1.843, Train Accuracy: 0.750
Train Loss: 1.106, Train Accuracy: 0.700
Round 39
Train Loss: 1.253, Train Accuracy: 0.750
Train Loss: 1.023, Train Accuracy: 0.400
Train Loss: 0.906, Train Accuracy: 0.600
Train Loss: 1.453, Train Accuracy: 1.000
Train Loss: 1.226, Train Accuracy: 0.625
Train Loss: 1.315, Train Accuracy: 0.800
Train Loss: 1.448, Train Accuracy: 0.500
Train Loss: 1.152, Train Accuracy: 0.600
Train Loss: 1.888, Train Accuracy: 0.750
Train Loss: 1.022, Train Accuracy: 0.400
Round 40
Train Loss: 1.208, Train Accuracy: 1.000
Train Loss: 0.950, Train Accuracy: 0.700
Train Loss: 0.920, Train Accuracy: 1.000
Train Loss: 1.286, Train Accuracy: 1.000
Train Loss: 1.192, Train Accuracy: 0.625
Train Loss: 1.448, Train Accuracy: 0.800
Train Loss: 1.383, Train Accuracy: 0.500
Train Loss: 1.004, Train Accuracy: 0.800
Train Loss: 2.100, Train Accuracy: 1.000
Train Loss: 1.301, Train Accuracy: 0.600
Round 41
Train Loss: 1.214, Train Accuracy: 0.750
Train Loss: 0.949, Train Accuracy: 0.600
Train Loss: 0.916, Train Accuracy: 0.600
Train Loss: 1.308, Train Accuracy: 0.800
Train Loss: 1.110, Train Accuracy: 0.750
Train Loss: 1.361, Train Accuracy: 0.800
Train Loss: 1.418, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.800
Train Loss: 2.250, Train Accuracy: 1.000
Train Loss: 1.083, Train Accuracy: 0.700
Round 42
Train Loss: 1.410, Train Accuracy: 0.750
Train Loss: 0.994, Train Accuracy: 0.800
Train Loss: 0.947, Train Accuracy: 0.600
Train Loss: 1.505, Train Accuracy: 1.000
Train Loss: 1.201, Train Accuracy: 0.750
Train Loss: 1.329, Train Accuracy: 0.800
Train Loss: 1.472, Train Accuracy: 1.000
Train Loss: 1.070, Train Accuracy: 0.600
Train Loss: 2.252, Train Accuracy: 1.000
Train Loss: 1.027, Train Accuracy: 0.600
Round 43
Train Loss: 1.291, Train Accuracy: 0.750
Train Loss: 0.959, Train Accuracy: 0.800
Train Loss: 0.882, Train Accuracy: 0.800
Train Loss: 1.399, Train Accuracy: 1.000
Train Loss: 1.355, Train Accuracy: 0.625
Train Loss: 1.394, Train Accuracy: 0.800
Train Loss: 1.683, Train Accuracy: 0.500
Train Loss: 1.081, Train Accuracy: 0.800
Train Loss: 2.042, Train Accuracy: 0.750
Train Loss: 1.189, Train Accuracy: 0.600
Round 44
Train Loss: 1.181, Train Accuracy: 0.750
Train Loss: 0.944, Train Accuracy: 0.700
Train Loss: 0.920, Train Accuracy: 0.600
Train Loss: 1.249, Train Accuracy: 0.800
Train Loss: 1.095, Train Accuracy: 0.500
Train Loss: 1.435, Train Accuracy: 0.800
Train Loss: 1.406, Train Accuracy: 1.000
Train Loss: 1.082, Train Accuracy: 0.600
Train Loss: 1.804, Train Accuracy: 0.750
Train Loss: 0.972, Train Accuracy: 0.600
Round 45
Train Loss: 1.410, Train Accuracy: 0.750
Train Loss: 0.954, Train Accuracy: 0.600
Train Loss: 0.882, Train Accuracy: 0.600
Train Loss: 1.281, Train Accuracy: 1.000
Train Loss: 1.073, Train Accuracy: 0.625
Train Loss: 1.305, Train Accuracy: 0.800
Train Loss: 1.560, Train Accuracy: 0.500
Train Loss: 1.018, Train Accuracy: 1.000
Train Loss: 2.117, Train Accuracy: 1.000
Train Loss: 1.319, Train Accuracy: 0.600
Round 46
Train Loss: 1.184, Train Accuracy: 0.750
Train Loss: 1.022, Train Accuracy: 0.400
Train Loss: 0.926, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 1.000
Train Loss: 1.128, Train Accuracy: 0.875
Train Loss: 1.332, Train Accuracy: 1.000
Train Loss: 1.371, Train Accuracy: 0.750
Train Loss: 1.286, Train Accuracy: 0.600
Train Loss: 2.102, Train Accuracy: 0.750
Train Loss: 1.000, Train Accuracy: 0.800
Round 47
Train Loss: 1.292, Train Accuracy: 0.750
Train Loss: 0.928, Train Accuracy: 0.700
Train Loss: 0.955, Train Accuracy: 0.800
Train Loss: 1.519, Train Accuracy: 1.000
Train Loss: 1.132, Train Accuracy: 0.500
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.668, Train Accuracy: 0.500
Train Loss: 1.100, Train Accuracy: 0.800
Train Loss: 2.137, Train Accuracy: 0.750
Train Loss: 1.110, Train Accuracy: 0.800
Round 48
Train Loss: 1.459, Train Accuracy: 0.750
Train Loss: 0.960, Train Accuracy: 0.700
Train Loss: 0.941, Train Accuracy: 0.800
Train Loss: 1.260, Train Accuracy: 0.800
Train Loss: 1.064, Train Accuracy: 0.375
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.606, Train Accuracy: 0.500

(FLClient pid=2778324) 2025-05-02 19:08:09,582 - INFO - Epoch   2| Train Loss: 0.586| Train Accuracy: 0.600 [repeated 358x across cluster]
(FLClient pid=2778324) 2025-05-02 19:08:09,588 - INFO - Epoch   2| Validation Loss: 1.274, Validation Accuracy: 0.250 [repeated 120x across cluster]

Results saved to Pubmed_results474/Pubmed_adjacency_GCN/results_Pubmed_adjacency_GCN.txt

Running experiment with data_loading_option: diffusion, model_type: GCN
DEVICE: cuda
Data loading option is diffusion
Model type is GCN

2025-05-02 19:08:13,142	INFO worker.py:1816 -- Started a local Ray instance.

data_loading_option: diffusion
Data loaded
Device is cuda
Pubmed()
10

(FLClient pid=2781111) 2025-05-02 19:08:38,648 - INFO - Epoch   0| Train Loss: 1.097| Train Accuracy: 0.250
(FLClient pid=2781111) 2025-05-02 19:08:38,652 - INFO - Epoch   1| Train Loss: 0.906| Train Accuracy: 0.750
(FLClient pid=2781111) 2025-05-02 19:08:38,655 - INFO - Epoch   2| Train Loss: 0.747| Train Accuracy: 0.750
(FLClient pid=2781111) 2025-05-02 19:08:38,664 - INFO - Epoch   2| Validation Loss: 1.167, Validation Accuracy: 0.295
(FLClient pid=2781111) 2025-05-02 19:08:43,771 - INFO - Epoch   2| Train Loss: 0.645| Train Accuracy: 0.750 [repeated 360x across cluster]
(FLClient pid=2781111) 2025-05-02 19:08:43,779 - INFO - Epoch   2| Validation Loss: 1.307, Validation Accuracy: 0.295 [repeated 120x across cluster]
(FLClient pid=2781111) 2025-05-02 19:08:48,884 - INFO - Epoch   2| Train Loss: 0.759| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2781111) 2025-05-02 19:08:48,891 - INFO - Epoch   2| Validation Loss: 1.163, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2781111) 2025-05-02 19:08:54,024 - INFO - Epoch   2| Train Loss: 0.742| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2781111) 2025-05-02 19:08:54,031 - INFO - Epoch   2| Validation Loss: 1.350, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2781111) 2025-05-02 19:08:59,154 - INFO - Epoch   2| Train Loss: 0.507| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2781111) 2025-05-02 19:08:59,162 - INFO - Epoch   2| Validation Loss: 1.281, Validation Accuracy: 0.295 [repeated 150x across cluster]
(FLClient pid=2781111) 2025-05-02 19:09:04,276 - INFO - Epoch   2| Train Loss: 0.534| Train Accuracy: 0.750 [repeated 450x across cluster]
(FLClient pid=2781111) 2025-05-02 19:09:04,282 - INFO - Epoch   2| Validation Loss: 0.983, Validation Accuracy: 0.523 [repeated 150x across cluster]
(FLClient pid=2781113) 2025-05-02 19:09:09,365 - INFO - Epoch   0| Train Loss: 0.652| Train Accuracy: 0.900 [repeated 448x across cluster]
(FLClient pid=2781106) 2025-05-02 19:09:09,056 - INFO - Epoch   2| Validation Loss: 0.799, Validation Accuracy: 0.578 [repeated 149x across cluster]

Training done
Round 1
Train Loss: 1.167, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.061, Train Accuracy: 0.400
Train Loss: 1.221, Train Accuracy: 0.600
Train Loss: 1.188, Train Accuracy: 0.625
Train Loss: 1.216, Train Accuracy: 0.800
Train Loss: 1.315, Train Accuracy: 0.500
Train Loss: 1.125, Train Accuracy: 0.400
Train Loss: 1.384, Train Accuracy: 0.750
Train Loss: 1.165, Train Accuracy: 0.500
Round 2
Train Loss: 1.186, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.058, Train Accuracy: 0.400
Train Loss: 1.285, Train Accuracy: 0.600
Train Loss: 1.212, Train Accuracy: 0.625
Train Loss: 1.217, Train Accuracy: 0.800
Train Loss: 1.372, Train Accuracy: 0.250
Train Loss: 1.152, Train Accuracy: 0.400
Train Loss: 1.530, Train Accuracy: 0.750
Train Loss: 1.177, Train Accuracy: 0.400
Round 3
Train Loss: 1.226, Train Accuracy: 0.750
Train Loss: 1.082, Train Accuracy: 0.500
Train Loss: 1.044, Train Accuracy: 0.400
Train Loss: 1.294, Train Accuracy: 0.600
Train Loss: 1.219, Train Accuracy: 0.625
Train Loss: 1.229, Train Accuracy: 0.800
Train Loss: 1.382, Train Accuracy: 0.750
Train Loss: 1.151, Train Accuracy: 0.400
Train Loss: 1.564, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.300
Round 4
Train Loss: 1.244, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.038, Train Accuracy: 0.400
Train Loss: 1.353, Train Accuracy: 0.600
Train Loss: 1.229, Train Accuracy: 0.625
Train Loss: 1.235, Train Accuracy: 0.800
Train Loss: 1.435, Train Accuracy: 0.500
Train Loss: 1.151, Train Accuracy: 0.200
Train Loss: 1.631, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.600
Round 5
Train Loss: 1.248, Train Accuracy: 0.750
Train Loss: 1.074, Train Accuracy: 0.500
Train Loss: 1.037, Train Accuracy: 0.400
Train Loss: 1.358, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 0.625
Train Loss: 1.266, Train Accuracy: 0.800
Train Loss: 1.452, Train Accuracy: 0.250
Train Loss: 1.228, Train Accuracy: 0.400
Train Loss: 1.729, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 0.600
Round 6
Train Loss: 1.270, Train Accuracy: 0.750
Train Loss: 1.078, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.406, Train Accuracy: 0.600
Train Loss: 1.241, Train Accuracy: 0.625
Train Loss: 1.258, Train Accuracy: 0.800
Train Loss: 1.429, Train Accuracy: 0.500
Train Loss: 1.176, Train Accuracy: 0.800
Train Loss: 1.748, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 0.400
Round 7
Train Loss: 1.282, Train Accuracy: 0.750
Train Loss: 1.073, Train Accuracy: 0.500
Train Loss: 1.045, Train Accuracy: 0.400
Train Loss: 1.425, Train Accuracy: 0.600
Train Loss: 1.236, Train Accuracy: 0.625
Train Loss: 1.297, Train Accuracy: 0.800
Train Loss: 1.514, Train Accuracy: 0.500
Train Loss: 1.215, Train Accuracy: 0.400
Train Loss: 1.795, Train Accuracy: 0.750
Train Loss: 1.214, Train Accuracy: 0.400
Round 8
Train Loss: 1.319, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.600
Train Loss: 1.032, Train Accuracy: 0.200
Train Loss: 1.416, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.462, Train Accuracy: 0.750
Train Loss: 1.190, Train Accuracy: 0.200
Train Loss: 1.858, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.400
Round 9
Train Loss: 1.269, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.500
Train Loss: 1.025, Train Accuracy: 0.600
Train Loss: 1.405, Train Accuracy: 0.600
Train Loss: 1.203, Train Accuracy: 0.625
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.486, Train Accuracy: 0.750
Train Loss: 1.145, Train Accuracy: 0.800
Train Loss: 1.821, Train Accuracy: 0.750
Train Loss: 1.198, Train Accuracy: 0.500
Round 10
Train Loss: 1.328, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.500
Train Loss: 1.026, Train Accuracy: 0.800
Train Loss: 1.465, Train Accuracy: 0.600
Train Loss: 1.275, Train Accuracy: 0.625
Train Loss: 1.309, Train Accuracy: 0.800
Train Loss: 1.488, Train Accuracy: 0.500
Train Loss: 1.228, Train Accuracy: 0.600
Train Loss: 1.836, Train Accuracy: 0.750
Train Loss: 1.163, Train Accuracy: 0.400
Round 11
Train Loss: 1.326, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.032, Train Accuracy: 0.200
Train Loss: 1.403, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.625
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.499, Train Accuracy: 0.500
Train Loss: 1.163, Train Accuracy: 0.400
Train Loss: 1.774, Train Accuracy: 0.750
Train Loss: 1.228, Train Accuracy: 0.400
Round 12
Train Loss: 1.307, Train Accuracy: 0.750
Train Loss: 1.067, Train Accuracy: 0.400
Train Loss: 1.033, Train Accuracy: 0.400
Train Loss: 1.428, Train Accuracy: 0.800
Train Loss: 1.243, Train Accuracy: 0.625
Train Loss: 1.352, Train Accuracy: 0.800
Train Loss: 1.530, Train Accuracy: 0.750
Train Loss: 1.127, Train Accuracy: 0.400
Train Loss: 1.814, Train Accuracy: 0.750
Train Loss: 1.169, Train Accuracy: 0.500
Round 13
Train Loss: 1.307, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.500
Train Loss: 1.021, Train Accuracy: 0.600
Train Loss: 1.445, Train Accuracy: 0.600
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.342, Train Accuracy: 0.800
Train Loss: 1.468, Train Accuracy: 0.500
Train Loss: 1.143, Train Accuracy: 0.600
Train Loss: 1.881, Train Accuracy: 0.750
Train Loss: 1.185, Train Accuracy: 0.300
Round 14
Train Loss: 1.285, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.400
Train Loss: 1.452, Train Accuracy: 0.600
Train Loss: 1.221, Train Accuracy: 0.500
Train Loss: 1.272, Train Accuracy: 0.800
Train Loss: 1.470, Train Accuracy: 0.500
Train Loss: 1.179, Train Accuracy: 0.400
Train Loss: 1.896, Train Accuracy: 0.750
Train Loss: 1.194, Train Accuracy: 0.600
Round 15
Train Loss: 1.459, Train Accuracy: 0.750
Train Loss: 1.072, Train Accuracy: 0.500
Train Loss: 1.022, Train Accuracy: 0.200
Train Loss: 1.428, Train Accuracy: 0.600
Train Loss: 1.248, Train Accuracy: 0.625
Train Loss: 1.361, Train Accuracy: 0.800
Train Loss: 1.483, Train Accuracy: 0.500
Train Loss: 1.142, Train Accuracy: 0.200
Train Loss: 1.957, Train Accuracy: 0.750
Train Loss: 1.186, Train Accuracy: 0.500
Round 16
Train Loss: 1.334, Train Accuracy: 0.750
Train Loss: 1.054, Train Accuracy: 0.500
Train Loss: 1.026, Train Accuracy: 0.600
Train Loss: 1.483, Train Accuracy: 0.600
Train Loss: 1.243, Train Accuracy: 0.625
Train Loss: 1.346, Train Accuracy: 0.800
Train Loss: 1.434, Train Accuracy: 0.750
Train Loss: 1.180, Train Accuracy: 0.400
Train Loss: 1.794, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.500
Round 17
Train Loss: 1.322, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.600
Train Loss: 1.011, Train Accuracy: 0.400
Train Loss: 1.442, Train Accuracy: 0.600
Train Loss: 1.210, Train Accuracy: 0.625
Train Loss: 1.344, Train Accuracy: 0.800
Train Loss: 1.462, Train Accuracy: 0.500
Train Loss: 1.165, Train Accuracy: 0.600
Train Loss: 1.777, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.500
Round 18
Train Loss: 1.360, Train Accuracy: 0.750
Train Loss: 1.049, Train Accuracy: 0.600
Train Loss: 1.028, Train Accuracy: 0.200
Train Loss: 1.452, Train Accuracy: 0.600
Train Loss: 1.249, Train Accuracy: 0.625
Train Loss: 1.363, Train Accuracy: 0.800
Train Loss: 1.505, Train Accuracy: 0.500
Train Loss: 1.092, Train Accuracy: 0.600
Train Loss: 1.906, Train Accuracy: 0.750
Train Loss: 1.205, Train Accuracy: 0.600
Round 19
Train Loss: 1.263, Train Accuracy: 0.750
Train Loss: 1.061, Train Accuracy: 0.600
Train Loss: 1.014, Train Accuracy: 0.600
Train Loss: 1.403, Train Accuracy: 0.600
Train Loss: 1.251, Train Accuracy: 0.625
Train Loss: 1.383, Train Accuracy: 0.800
Train Loss: 1.483, Train Accuracy: 1.000
Train Loss: 1.187, Train Accuracy: 0.600
Train Loss: 1.813, Train Accuracy: 0.750
Train Loss: 1.232, Train Accuracy: 0.700
Round 20
Train Loss: 1.363, Train Accuracy: 0.750
Train Loss: 1.056, Train Accuracy: 0.500
Train Loss: 1.024, Train Accuracy: 0.400
Train Loss: 1.474, Train Accuracy: 0.600
Train Loss: 1.231, Train Accuracy: 0.625
Train Loss: 1.312, Train Accuracy: 0.800
Train Loss: 1.581, Train Accuracy: 1.000
Train Loss: 1.174, Train Accuracy: 0.600
Train Loss: 1.920, Train Accuracy: 0.750
Train Loss: 1.192, Train Accuracy: 0.500
Round 21
Train Loss: 1.268, Train Accuracy: 0.750
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 1.010, Train Accuracy: 0.200
Train Loss: 1.542, Train Accuracy: 1.000
Train Loss: 1.216, Train Accuracy: 0.750
Train Loss: 1.367, Train Accuracy: 0.800
Train Loss: 1.495, Train Accuracy: 0.500
Train Loss: 1.267, Train Accuracy: 0.800
Train Loss: 1.873, Train Accuracy: 0.750
Train Loss: 1.192, Train Accuracy: 0.400
Round 22
Train Loss: 1.325, Train Accuracy: 0.750
Train Loss: 1.038, Train Accuracy: 0.600
Train Loss: 1.001, Train Accuracy: 0.400
Train Loss: 1.484, Train Accuracy: 0.800
Train Loss: 1.228, Train Accuracy: 0.625
Train Loss: 1.386, Train Accuracy: 0.800
Train Loss: 1.514, Train Accuracy: 1.000
Train Loss: 1.192, Train Accuracy: 0.600
Train Loss: 1.764, Train Accuracy: 0.750
Train Loss: 1.255, Train Accuracy: 0.700
Round 23
Train Loss: 1.398, Train Accuracy: 0.750
Train Loss: 1.048, Train Accuracy: 0.600
Train Loss: 0.992, Train Accuracy: 0.600
Train Loss: 1.490, Train Accuracy: 0.800
Train Loss: 1.211, Train Accuracy: 0.750
Train Loss: 1.327, Train Accuracy: 0.800
Train Loss: 1.469, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.600
Train Loss: 1.978, Train Accuracy: 0.750
Train Loss: 1.253, Train Accuracy: 0.600
Round 24
Train Loss: 1.422, Train Accuracy: 0.750
Train Loss: 1.030, Train Accuracy: 0.600
Train Loss: 0.996, Train Accuracy: 0.200
Train Loss: 1.431, Train Accuracy: 0.600
Train Loss: 1.213, Train Accuracy: 0.625
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.459, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 0.800
Train Loss: 1.920, Train Accuracy: 0.750
Train Loss: 1.112, Train Accuracy: 0.500
Round 25
Train Loss: 1.338, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.600
Train Loss: 1.000, Train Accuracy: 0.200
Train Loss: 1.353, Train Accuracy: 0.600
Train Loss: 1.209, Train Accuracy: 0.625
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.468, Train Accuracy: 0.750
Train Loss: 1.158, Train Accuracy: 0.400
Train Loss: 1.972, Train Accuracy: 0.750
Train Loss: 1.147, Train Accuracy: 0.400
Round 26
Train Loss: 1.314, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.600
Train Loss: 0.988, Train Accuracy: 0.400
Train Loss: 1.315, Train Accuracy: 0.600
Train Loss: 1.214, Train Accuracy: 0.625
Train Loss: 1.356, Train Accuracy: 0.800
Train Loss: 1.482, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.400
Train Loss: 2.088, Train Accuracy: 0.750
Train Loss: 1.076, Train Accuracy: 0.600
Round 27
Train Loss: 1.352, Train Accuracy: 0.750
Train Loss: 1.026, Train Accuracy: 0.600
Train Loss: 0.987, Train Accuracy: 0.800
Train Loss: 1.390, Train Accuracy: 0.600
Train Loss: 1.224, Train Accuracy: 0.625
Train Loss: 1.345, Train Accuracy: 0.800
Train Loss: 1.601, Train Accuracy: 0.750
Train Loss: 1.154, Train Accuracy: 0.200
Train Loss: 2.068, Train Accuracy: 0.750
Train Loss: 1.144, Train Accuracy: 0.600
Round 28
Train Loss: 1.163, Train Accuracy: 0.750
Train Loss: 1.032, Train Accuracy: 0.600
Train Loss: 0.978, Train Accuracy: 0.400
Train Loss: 1.416, Train Accuracy: 0.800
Train Loss: 1.180, Train Accuracy: 0.750
Train Loss: 1.349, Train Accuracy: 0.800
Train Loss: 1.589, Train Accuracy: 0.500
Train Loss: 1.213, Train Accuracy: 0.600
Train Loss: 2.126, Train Accuracy: 0.750
Train Loss: 1.109, Train Accuracy: 0.700
Round 29
Train Loss: 1.371, Train Accuracy: 0.750
Train Loss: 1.017, Train Accuracy: 0.600
Train Loss: 0.985, Train Accuracy: 0.600
Train Loss: 1.387, Train Accuracy: 0.800
Train Loss: 1.172, Train Accuracy: 0.750
Train Loss: 1.257, Train Accuracy: 0.800
Train Loss: 1.563, Train Accuracy: 0.500
Train Loss: 1.060, Train Accuracy: 0.200
Train Loss: 2.070, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.300
Round 30
Train Loss: 1.298, Train Accuracy: 0.750
Train Loss: 1.025, Train Accuracy: 0.800
Train Loss: 0.973, Train Accuracy: 0.600
Train Loss: 1.325, Train Accuracy: 0.800
Train Loss: 1.221, Train Accuracy: 0.625
Train Loss: 1.431, Train Accuracy: 0.800
Train Loss: 1.569, Train Accuracy: 0.500
Train Loss: 1.170, Train Accuracy: 0.800
Train Loss: 1.899, Train Accuracy: 0.750
Train Loss: 1.097, Train Accuracy: 0.600
Round 31
Train Loss: 1.412, Train Accuracy: 0.750
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 0.970, Train Accuracy: 0.600
Train Loss: 1.358, Train Accuracy: 0.800
Train Loss: 1.157, Train Accuracy: 0.750
Train Loss: 1.353, Train Accuracy: 0.800
Train Loss: 1.456, Train Accuracy: 0.500
Train Loss: 1.204, Train Accuracy: 0.600
Train Loss: 1.992, Train Accuracy: 0.750
Train Loss: 1.102, Train Accuracy: 0.600
Round 32
Train Loss: 1.397, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.400
Train Loss: 0.959, Train Accuracy: 0.600
Train Loss: 1.409, Train Accuracy: 0.800
Train Loss: 1.186, Train Accuracy: 0.750
Train Loss: 1.328, Train Accuracy: 0.800
Train Loss: 1.544, Train Accuracy: 0.500
Train Loss: 1.136, Train Accuracy: 0.400
Train Loss: 1.990, Train Accuracy: 0.750
Train Loss: 1.160, Train Accuracy: 0.600
Round 33
Train Loss: 1.255, Train Accuracy: 0.750
Train Loss: 1.009, Train Accuracy: 0.600
Train Loss: 0.978, Train Accuracy: 0.400
Train Loss: 1.407, Train Accuracy: 0.400
Train Loss: 1.200, Train Accuracy: 0.625
Train Loss: 1.293, Train Accuracy: 0.800
Train Loss: 1.577, Train Accuracy: 0.500
Train Loss: 1.215, Train Accuracy: 0.600
Train Loss: 1.884, Train Accuracy: 0.750
Train Loss: 1.129, Train Accuracy: 0.500
Round 34
Train Loss: 1.283, Train Accuracy: 0.750
Train Loss: 1.006, Train Accuracy: 0.500
Train Loss: 0.965, Train Accuracy: 0.400
Train Loss: 1.398, Train Accuracy: 1.000
Train Loss: 1.199, Train Accuracy: 0.750
Train Loss: 1.352, Train Accuracy: 0.800
Train Loss: 1.601, Train Accuracy: 1.000
Train Loss: 1.149, Train Accuracy: 0.800
Train Loss: 2.039, Train Accuracy: 0.750
Train Loss: 1.187, Train Accuracy: 0.800
Round 35
Train Loss: 1.321, Train Accuracy: 0.750
Train Loss: 1.041, Train Accuracy: 0.300
Train Loss: 0.954, Train Accuracy: 0.600
Train Loss: 1.542, Train Accuracy: 0.600
Train Loss: 1.165, Train Accuracy: 0.875
Train Loss: 1.292, Train Accuracy: 0.800
Train Loss: 1.474, Train Accuracy: 1.000
Train Loss: 1.023, Train Accuracy: 0.400
Train Loss: 1.919, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.600
Round 36
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 1.018, Train Accuracy: 0.600
Train Loss: 0.969, Train Accuracy: 0.400
Train Loss: 1.440, Train Accuracy: 0.800
Train Loss: 1.188, Train Accuracy: 0.750
Train Loss: 1.272, Train Accuracy: 0.800
Train Loss: 1.474, Train Accuracy: 1.000
Train Loss: 1.175, Train Accuracy: 1.000
Train Loss: 2.086, Train Accuracy: 0.750
Train Loss: 1.129, Train Accuracy: 0.700
Round 37
Train Loss: 1.299, Train Accuracy: 0.750
Train Loss: 1.009, Train Accuracy: 0.500
Train Loss: 0.935, Train Accuracy: 0.600
Train Loss: 1.422, Train Accuracy: 0.800
Train Loss: 1.134, Train Accuracy: 0.625
Train Loss: 1.330, Train Accuracy: 0.800
Train Loss: 1.628, Train Accuracy: 0.750
Train Loss: 1.149, Train Accuracy: 0.600
Train Loss: 2.219, Train Accuracy: 0.750
Train Loss: 1.146, Train Accuracy: 0.700
Round 38
Train Loss: 1.269, Train Accuracy: 0.750
Train Loss: 0.996, Train Accuracy: 0.700
Train Loss: 0.950, Train Accuracy: 0.600
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.158, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.800
Train Loss: 1.596, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 1.000
Train Loss: 2.110, Train Accuracy: 0.750
Train Loss: 1.107, Train Accuracy: 0.600
Round 39
Train Loss: 1.277, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.500
Train Loss: 0.950, Train Accuracy: 0.600
Train Loss: 1.428, Train Accuracy: 1.000
Train Loss: 1.137, Train Accuracy: 0.625
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.678, Train Accuracy: 0.500
Train Loss: 1.049, Train Accuracy: 0.800
Train Loss: 2.195, Train Accuracy: 1.000
Train Loss: 1.120, Train Accuracy: 0.500
Round 40
Train Loss: 1.179, Train Accuracy: 0.750
Train Loss: 0.994, Train Accuracy: 0.700
Train Loss: 0.916, Train Accuracy: 0.400
Train Loss: 1.272, Train Accuracy: 0.800
Train Loss: 1.097, Train Accuracy: 0.750
Train Loss: 1.366, Train Accuracy: 0.800
Train Loss: 1.820, Train Accuracy: 0.500
Train Loss: 1.148, Train Accuracy: 0.600
Train Loss: 1.838, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.700
Round 41
Train Loss: 1.312, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.500
Train Loss: 0.943, Train Accuracy: 0.400
Train Loss: 1.280, Train Accuracy: 0.800
Train Loss: 1.130, Train Accuracy: 0.625
Train Loss: 1.462, Train Accuracy: 0.800
Train Loss: 1.604, Train Accuracy: 0.500
Train Loss: 1.137, Train Accuracy: 0.400
Train Loss: 2.119, Train Accuracy: 0.750
Train Loss: 1.052, Train Accuracy: 0.500
Round 42
Train Loss: 1.281, Train Accuracy: 0.750
Train Loss: 0.972, Train Accuracy: 0.700
Train Loss: 0.909, Train Accuracy: 0.600
Train Loss: 1.303, Train Accuracy: 0.800
Train Loss: 1.103, Train Accuracy: 0.750
Train Loss: 1.389, Train Accuracy: 0.800
Train Loss: 1.518, Train Accuracy: 0.750
Train Loss: 1.115, Train Accuracy: 0.600
Train Loss: 1.790, Train Accuracy: 0.750
Train Loss: 0.994, Train Accuracy: 0.500
Round 43
Train Loss: 1.350, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.700
Train Loss: 0.923, Train Accuracy: 0.400
Train Loss: 1.508, Train Accuracy: 0.800
Train Loss: 1.211, Train Accuracy: 0.250
Train Loss: 1.388, Train Accuracy: 0.800
Train Loss: 1.551, Train Accuracy: 0.500
Train Loss: 1.137, Train Accuracy: 0.800
Train Loss: 1.967, Train Accuracy: 0.750
Train Loss: 1.341, Train Accuracy: 0.600
Round 44
Train Loss: 1.266, Train Accuracy: 0.750
Train Loss: 1.021, Train Accuracy: 0.300
Train Loss: 0.902, Train Accuracy: 0.600
Train Loss: 1.356, Train Accuracy: 1.000
Train Loss: 1.116, Train Accuracy: 0.625
Train Loss: 1.263, Train Accuracy: 0.800
Train Loss: 1.502, Train Accuracy: 1.000
Train Loss: 1.117, Train Accuracy: 0.800
Train Loss: 2.115, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.700
Round 45
Train Loss: 1.190, Train Accuracy: 0.750
Train Loss: 1.030, Train Accuracy: 0.400
Train Loss: 0.995, Train Accuracy: 0.600
Train Loss: 1.483, Train Accuracy: 0.600
Train Loss: 1.104, Train Accuracy: 0.500
Train Loss: 1.292, Train Accuracy: 0.800
Train Loss: 1.718, Train Accuracy: 0.750
Train Loss: 1.107, Train Accuracy: 0.800
Train Loss: 2.254, Train Accuracy: 0.750
Train Loss: 1.328, Train Accuracy: 0.500
Round 46
Train Loss: 1.185, Train Accuracy: 0.750
Train Loss: 0.998, Train Accuracy: 0.800
Train Loss: 0.923, Train Accuracy: 0.800
Train Loss: 1.437, Train Accuracy: 0.800
Train Loss: 1.182, Train Accuracy: 0.750
Train Loss: 1.363, Train Accuracy: 0.800
Train Loss: 1.644, Train Accuracy: 1.000
Train Loss: 0.990, Train Accuracy: 0.400
Train Loss: 2.136, Train Accuracy: 0.750
Train Loss: 0.962, Train Accuracy: 0.700
Round 47
Train Loss: 1.566, Train Accuracy: 1.000
Train Loss: 0.961, Train Accuracy: 0.600
Train Loss: 0.931, Train Accuracy: 0.600
Train Loss: 1.559, Train Accuracy: 0.600
Train Loss: 1.167, Train Accuracy: 0.500
Train Loss: 1.222, Train Accuracy: 0.800
Train Loss: 1.549, Train Accuracy: 0.750
Train Loss: 1.077, Train Accuracy: 0.600
Train Loss: 1.927, Train Accuracy: 0.750
Train Loss: 1.236, Train Accuracy: 0.600
Round 48
Train Loss: 1.148, Train Accuracy: 0.750
Train Loss: 1.014, Train Accuracy: 0.400
Train Loss: 0.890, Train Accuracy: 0.600
Train Loss: 1.265, Train Accuracy: 0.800
Train Loss: 1.052, Train Accuracy: 0.625
Train Loss: 1.392, Train Accuracy: 1.000
Train Loss: 1.357, Train Accuracy: 1.000

(FLClient pid=2781103) 2025-05-02 19:09:39,914 - INFO - Epoch   2| Train Loss: 0.695| Train Accuracy: 0.750 [repeated 392x across cluster]
(FLClient pid=2781103) 2025-05-02 19:09:39,923 - INFO - Epoch   2| Validation Loss: 1.359, Validation Accuracy: 0.295 [repeated 131x across cluster]
(FLClient pid=2781107) 2025-05-02 19:09:45,177 - INFO - Epoch   2| Train Loss: 0.967| Train Accuracy: 0.500 [repeated 390x across cluster]
(FLClient pid=2781107) 2025-05-02 19:09:45,185 - INFO - Epoch   2| Validation Loss: 1.096, Validation Accuracy: 0.533 [repeated 130x across cluster]
(FLClient pid=2781107) 2025-05-02 19:09:50,321 - INFO - Epoch   2| Train Loss: 0.983| Train Accuracy: 0.500 [repeated 450x across cluster]
(FLClient pid=2781107) 2025-05-02 19:09:50,329 - INFO - Epoch   2| Validation Loss: 1.002, Validation Accuracy: 0.467 [repeated 150x across cluster]
(FLClient pid=2781107) 2025-05-02 19:09:55,467 - INFO - Epoch   2| Train Loss: 0.920| Train Accuracy: 0.500 [repeated 450x across cluster]
(FLClient pid=2781107) 2025-05-02 19:09:55,475 - INFO - Epoch   2| Validation Loss: 1.001, Validation Accuracy: 0.467 [repeated 150x across cluster]
(FLClient pid=2781107) 2025-05-02 19:10:00,593 - INFO - Epoch   2| Train Loss: 0.911| Train Accuracy: 0.400 [repeated 450x across cluster]
(FLClient pid=2781107) 2025-05-02 19:10:00,601 - INFO - Epoch   2| Validation Loss: 0.973, Validation Accuracy: 0.467 [repeated 150x across cluster]
(FLClient pid=2781107) 2025-05-02 19:10:05,703 - INFO - Epoch   0| Train Loss: 0.856| Train Accuracy: 0.700 [repeated 448x across cluster]
(FLClient pid=2781125) 2025-05-02 19:10:05,393 - INFO - Epoch   2| Validation Loss: 1.646, Validation Accuracy: 0.302 [repeated 149x across cluster]
(FLClient pid=2781107) 2025-05-02 19:10:10,852 - INFO - Epoch   2| Train Loss: 0.721| Train Accuracy: 0.600 [repeated 452x across cluster]
(FLClient pid=2781125) 2025-05-02 19:10:10,512 - INFO - Epoch   2| Validation Loss: 2.436, Validation Accuracy: 0.233 [repeated 150x across cluster]

Training done
Round 1
Train Loss: 1.359, Train Accuracy: 0.750
Train Loss: 1.083, Train Accuracy: 0.500
Train Loss: 1.067, Train Accuracy: 0.400
Train Loss: 1.179, Train Accuracy: 0.600
Train Loss: 1.192, Train Accuracy: 0.625
Train Loss: 1.372, Train Accuracy: 0.800
Train Loss: 1.248, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.800
Train Loss: 1.286, Train Accuracy: 0.750
Train Loss: 1.158, Train Accuracy: 0.400
Round 2
Train Loss: 1.369, Train Accuracy: 0.750
Train Loss: 1.097, Train Accuracy: 0.500
Train Loss: 1.052, Train Accuracy: 0.400
Train Loss: 1.233, Train Accuracy: 0.600
Train Loss: 1.206, Train Accuracy: 0.625
Train Loss: 1.326, Train Accuracy: 0.800
Train Loss: 1.331, Train Accuracy: 0.500
Train Loss: 1.164, Train Accuracy: 0.400
Train Loss: 1.372, Train Accuracy: 0.750
Train Loss: 1.176, Train Accuracy: 0.500
Round 3
Train Loss: 1.332, Train Accuracy: 0.750
Train Loss: 1.089, Train Accuracy: 0.400
Train Loss: 1.060, Train Accuracy: 0.400
Train Loss: 1.234, Train Accuracy: 0.600
Train Loss: 1.220, Train Accuracy: 0.625
Train Loss: 1.340, Train Accuracy: 0.800
Train Loss: 1.375, Train Accuracy: 0.500
Train Loss: 1.176, Train Accuracy: 0.000
Train Loss: 1.540, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.400
Round 4
Train Loss: 1.337, Train Accuracy: 0.750
Train Loss: 1.091, Train Accuracy: 0.500
Train Loss: 1.039, Train Accuracy: 0.400
Train Loss: 1.272, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.282, Train Accuracy: 0.800
Train Loss: 1.382, Train Accuracy: 0.500
Train Loss: 1.175, Train Accuracy: 0.400
Train Loss: 1.592, Train Accuracy: 0.750
Train Loss: 1.202, Train Accuracy: 0.400
Round 5
Train Loss: 1.291, Train Accuracy: 0.750
Train Loss: 1.096, Train Accuracy: 0.500
Train Loss: 1.049, Train Accuracy: 0.200
Train Loss: 1.320, Train Accuracy: 0.600
Train Loss: 1.273, Train Accuracy: 0.625
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.436, Train Accuracy: 0.750
Train Loss: 1.178, Train Accuracy: 0.600
Train Loss: 1.567, Train Accuracy: 0.750
Train Loss: 1.209, Train Accuracy: 0.400
Round 6
Train Loss: 1.491, Train Accuracy: 0.750
Train Loss: 1.092, Train Accuracy: 0.400
Train Loss: 1.047, Train Accuracy: 0.400
Train Loss: 1.349, Train Accuracy: 0.600
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.293, Train Accuracy: 0.800
Train Loss: 1.425, Train Accuracy: 0.500
Train Loss: 1.163, Train Accuracy: 0.200
Train Loss: 1.617, Train Accuracy: 0.750
Train Loss: 1.195, Train Accuracy: 0.600
Round 7
Train Loss: 1.373, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.500
Train Loss: 1.032, Train Accuracy: 0.400
Train Loss: 1.313, Train Accuracy: 0.600
Train Loss: 1.242, Train Accuracy: 0.625
Train Loss: 1.396, Train Accuracy: 0.800
Train Loss: 1.466, Train Accuracy: 0.250
Train Loss: 1.190, Train Accuracy: 0.400
Train Loss: 1.608, Train Accuracy: 0.750
Train Loss: 1.183, Train Accuracy: 0.400
Round 8
Train Loss: 1.486, Train Accuracy: 0.750
Train Loss: 1.085, Train Accuracy: 0.500
Train Loss: 1.035, Train Accuracy: 0.400
Train Loss: 1.309, Train Accuracy: 0.600
Train Loss: 1.239, Train Accuracy: 0.625
Train Loss: 1.290, Train Accuracy: 0.800
Train Loss: 1.478, Train Accuracy: 0.750
Train Loss: 1.182, Train Accuracy: 0.400
Train Loss: 1.703, Train Accuracy: 0.750
Train Loss: 1.188, Train Accuracy: 0.500
Round 9
Train Loss: 1.345, Train Accuracy: 0.750
Train Loss: 1.079, Train Accuracy: 0.500
Train Loss: 1.046, Train Accuracy: 0.400
Train Loss: 1.327, Train Accuracy: 0.600
Train Loss: 1.272, Train Accuracy: 0.625
Train Loss: 1.377, Train Accuracy: 0.800
Train Loss: 1.457, Train Accuracy: 0.500
Train Loss: 1.165, Train Accuracy: 0.200
Train Loss: 1.701, Train Accuracy: 0.750
Train Loss: 1.146, Train Accuracy: 0.400
Round 10
Train Loss: 1.363, Train Accuracy: 0.750
Train Loss: 1.071, Train Accuracy: 0.500
Train Loss: 1.036, Train Accuracy: 0.400
Train Loss: 1.324, Train Accuracy: 0.600
Train Loss: 1.251, Train Accuracy: 0.625
Train Loss: 1.380, Train Accuracy: 0.800
Train Loss: 1.471, Train Accuracy: 0.000
Train Loss: 1.170, Train Accuracy: 0.400
Train Loss: 1.683, Train Accuracy: 0.750
Train Loss: 1.206, Train Accuracy: 0.600
Round 11
Train Loss: 1.374, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.500
Train Loss: 1.023, Train Accuracy: 0.400
Train Loss: 1.336, Train Accuracy: 0.800
Train Loss: 1.223, Train Accuracy: 0.625
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.580, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.600
Train Loss: 1.701, Train Accuracy: 0.750
Train Loss: 1.201, Train Accuracy: 0.500
Round 12
Train Loss: 1.388, Train Accuracy: 0.750
Train Loss: 1.069, Train Accuracy: 0.400
Train Loss: 1.016, Train Accuracy: 0.400
Train Loss: 1.336, Train Accuracy: 0.600
Train Loss: 1.300, Train Accuracy: 0.625
Train Loss: 1.314, Train Accuracy: 0.800
Train Loss: 1.552, Train Accuracy: 0.500
Train Loss: 1.240, Train Accuracy: 0.400
Train Loss: 1.813, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.600
Round 13
Train Loss: 1.345, Train Accuracy: 0.750
Train Loss: 1.087, Train Accuracy: 0.600
Train Loss: 1.065, Train Accuracy: 0.400
Train Loss: 1.356, Train Accuracy: 0.600
Train Loss: 1.250, Train Accuracy: 0.625
Train Loss: 1.287, Train Accuracy: 0.800
Train Loss: 1.478, Train Accuracy: 0.750
Train Loss: 1.216, Train Accuracy: 0.200
Train Loss: 1.812, Train Accuracy: 0.750
Train Loss: 1.243, Train Accuracy: 0.400
Round 14
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 1.096, Train Accuracy: 0.500
Train Loss: 1.010, Train Accuracy: 0.400
Train Loss: 1.359, Train Accuracy: 0.600
Train Loss: 1.269, Train Accuracy: 0.750
Train Loss: 1.282, Train Accuracy: 0.800
Train Loss: 1.490, Train Accuracy: 0.500
Train Loss: 1.142, Train Accuracy: 0.600
Train Loss: 1.808, Train Accuracy: 0.750
Train Loss: 1.184, Train Accuracy: 0.400
Round 15
Train Loss: 1.314, Train Accuracy: 0.750
Train Loss: 1.064, Train Accuracy: 0.400
Train Loss: 1.029, Train Accuracy: 0.400
Train Loss: 1.392, Train Accuracy: 1.000
Train Loss: 1.300, Train Accuracy: 0.625
Train Loss: 1.460, Train Accuracy: 0.800
Train Loss: 1.491, Train Accuracy: 0.500
Train Loss: 1.183, Train Accuracy: 0.400
Train Loss: 1.833, Train Accuracy: 0.750
Train Loss: 1.192, Train Accuracy: 0.300
Round 16
Train Loss: 1.292, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.600
Train Loss: 1.006, Train Accuracy: 0.400
Train Loss: 1.406, Train Accuracy: 0.600
Train Loss: 1.222, Train Accuracy: 0.750
Train Loss: 1.341, Train Accuracy: 0.800
Train Loss: 1.473, Train Accuracy: 0.250
Train Loss: 1.167, Train Accuracy: 0.600
Train Loss: 1.857, Train Accuracy: 0.750
Train Loss: 1.117, Train Accuracy: 0.500
Round 17
Train Loss: 1.371, Train Accuracy: 0.750
Train Loss: 1.058, Train Accuracy: 0.400
Train Loss: 1.003, Train Accuracy: 0.600
Train Loss: 1.389, Train Accuracy: 0.600
Train Loss: 1.248, Train Accuracy: 0.750
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.548, Train Accuracy: 0.500
Train Loss: 1.176, Train Accuracy: 0.400
Train Loss: 1.754, Train Accuracy: 0.750
Train Loss: 1.162, Train Accuracy: 0.300
Round 18
Train Loss: 1.475, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.500
Train Loss: 1.018, Train Accuracy: 0.400
Train Loss: 1.308, Train Accuracy: 0.600
Train Loss: 1.210, Train Accuracy: 0.625
Train Loss: 1.387, Train Accuracy: 0.800
Train Loss: 1.411, Train Accuracy: 0.500
Train Loss: 1.207, Train Accuracy: 0.800
Train Loss: 1.768, Train Accuracy: 0.750
Train Loss: 1.139, Train Accuracy: 0.600
Round 19
Train Loss: 1.304, Train Accuracy: 0.750
Train Loss: 1.050, Train Accuracy: 0.400
Train Loss: 1.005, Train Accuracy: 0.400
Train Loss: 1.346, Train Accuracy: 0.800
Train Loss: 1.256, Train Accuracy: 0.625
Train Loss: 1.281, Train Accuracy: 0.800
Train Loss: 1.536, Train Accuracy: 0.750
Train Loss: 1.166, Train Accuracy: 0.800
Train Loss: 1.790, Train Accuracy: 0.750
Train Loss: 1.116, Train Accuracy: 0.500
Round 20
Train Loss: 1.406, Train Accuracy: 0.750
Train Loss: 1.042, Train Accuracy: 0.700
Train Loss: 1.015, Train Accuracy: 0.200
Train Loss: 1.372, Train Accuracy: 0.800
Train Loss: 1.195, Train Accuracy: 0.625
Train Loss: 1.331, Train Accuracy: 0.800
Train Loss: 1.591, Train Accuracy: 0.750
Train Loss: 1.108, Train Accuracy: 0.400
Train Loss: 1.904, Train Accuracy: 0.750
Train Loss: 1.173, Train Accuracy: 0.400
Round 21
Train Loss: 1.247, Train Accuracy: 0.750
Train Loss: 1.047, Train Accuracy: 0.400
Train Loss: 0.999, Train Accuracy: 0.400
Train Loss: 1.301, Train Accuracy: 0.600
Train Loss: 1.244, Train Accuracy: 0.750
Train Loss: 1.379, Train Accuracy: 0.800
Train Loss: 1.509, Train Accuracy: 1.000
Train Loss: 1.174, Train Accuracy: 0.400
Train Loss: 1.828, Train Accuracy: 0.750
Train Loss: 1.119, Train Accuracy: 0.400
Round 22
Train Loss: 1.244, Train Accuracy: 0.750
Train Loss: 1.031, Train Accuracy: 0.700
Train Loss: 0.987, Train Accuracy: 0.600
Train Loss: 1.378, Train Accuracy: 0.800
Train Loss: 1.226, Train Accuracy: 0.750
Train Loss: 1.343, Train Accuracy: 0.800
Train Loss: 1.510, Train Accuracy: 0.750
Train Loss: 1.196, Train Accuracy: 0.600
Train Loss: 1.848, Train Accuracy: 0.750
Train Loss: 1.190, Train Accuracy: 0.300
Round 23
Train Loss: 1.423, Train Accuracy: 0.750
Train Loss: 1.065, Train Accuracy: 0.600
Train Loss: 1.018, Train Accuracy: 0.400
Train Loss: 1.240, Train Accuracy: 0.800
Train Loss: 1.210, Train Accuracy: 0.750
Train Loss: 1.470, Train Accuracy: 0.800
Train Loss: 1.482, Train Accuracy: 0.750
Train Loss: 1.126, Train Accuracy: 0.600
Train Loss: 1.888, Train Accuracy: 0.750
Train Loss: 1.103, Train Accuracy: 0.600
Round 24
Train Loss: 1.374, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.500
Train Loss: 0.977, Train Accuracy: 0.400
Train Loss: 1.348, Train Accuracy: 0.800
Train Loss: 1.256, Train Accuracy: 0.625
Train Loss: 1.315, Train Accuracy: 0.800
Train Loss: 1.416, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.800
Train Loss: 1.913, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.300
Round 25
Train Loss: 1.293, Train Accuracy: 0.750
Train Loss: 1.020, Train Accuracy: 0.500
Train Loss: 0.986, Train Accuracy: 0.400
Train Loss: 1.259, Train Accuracy: 0.600
Train Loss: 1.174, Train Accuracy: 0.750
Train Loss: 1.348, Train Accuracy: 0.800
Train Loss: 1.570, Train Accuracy: 0.500
Train Loss: 1.105, Train Accuracy: 0.600
Train Loss: 1.760, Train Accuracy: 0.750
Train Loss: 1.159, Train Accuracy: 0.700
Round 26
Train Loss: 1.458, Train Accuracy: 0.750
Train Loss: 1.025, Train Accuracy: 0.400
Train Loss: 0.981, Train Accuracy: 0.400
Train Loss: 1.291, Train Accuracy: 0.800
Train Loss: 1.217, Train Accuracy: 0.750
Train Loss: 1.225, Train Accuracy: 0.800
Train Loss: 1.560, Train Accuracy: 0.500
Train Loss: 1.146, Train Accuracy: 0.600
Train Loss: 1.905, Train Accuracy: 0.750
Train Loss: 1.189, Train Accuracy: 0.500
Round 27
Train Loss: 1.404, Train Accuracy: 0.750
Train Loss: 1.092, Train Accuracy: 0.600
Train Loss: 0.980, Train Accuracy: 0.400
Train Loss: 1.299, Train Accuracy: 0.800
Train Loss: 1.245, Train Accuracy: 0.625
Train Loss: 1.382, Train Accuracy: 0.800
Train Loss: 1.510, Train Accuracy: 1.000
Train Loss: 1.144, Train Accuracy: 0.800
Train Loss: 1.956, Train Accuracy: 0.750
Train Loss: 1.191, Train Accuracy: 0.600
Round 28
Train Loss: 1.284, Train Accuracy: 0.750
Train Loss: 1.008, Train Accuracy: 0.400
Train Loss: 1.021, Train Accuracy: 0.600
Train Loss: 1.448, Train Accuracy: 0.800
Train Loss: 1.258, Train Accuracy: 0.625
Train Loss: 1.375, Train Accuracy: 0.800
Train Loss: 1.520, Train Accuracy: 1.000
Train Loss: 1.208, Train Accuracy: 0.400
Train Loss: 1.856, Train Accuracy: 0.750
Train Loss: 1.239, Train Accuracy: 0.600
Round 29
Train Loss: 1.267, Train Accuracy: 0.500
Train Loss: 1.002, Train Accuracy: 0.500
Train Loss: 0.955, Train Accuracy: 0.600
Train Loss: 1.327, Train Accuracy: 0.800
Train Loss: 1.141, Train Accuracy: 0.625
Train Loss: 1.434, Train Accuracy: 0.800
Train Loss: 1.550, Train Accuracy: 0.750
Train Loss: 1.233, Train Accuracy: 0.600
Train Loss: 1.737, Train Accuracy: 0.750
Train Loss: 1.189, Train Accuracy: 0.300
Round 30
Train Loss: 1.435, Train Accuracy: 0.750
Train Loss: 1.015, Train Accuracy: 0.700
Train Loss: 0.969, Train Accuracy: 0.400
Train Loss: 1.303, Train Accuracy: 0.600
Train Loss: 1.164, Train Accuracy: 0.875
Train Loss: 1.269, Train Accuracy: 0.800
Train Loss: 1.397, Train Accuracy: 0.750
Train Loss: 1.135, Train Accuracy: 0.600
Train Loss: 2.001, Train Accuracy: 0.750
Train Loss: 1.370, Train Accuracy: 0.600
Round 31
Train Loss: 1.206, Train Accuracy: 0.750
Train Loss: 0.993, Train Accuracy: 0.700
Train Loss: 0.946, Train Accuracy: 0.400
Train Loss: 1.340, Train Accuracy: 0.600
Train Loss: 1.240, Train Accuracy: 0.750
Train Loss: 1.323, Train Accuracy: 0.800
Train Loss: 1.506, Train Accuracy: 0.750
Train Loss: 1.068, Train Accuracy: 0.400
Train Loss: 1.898, Train Accuracy: 0.750
Train Loss: 1.102, Train Accuracy: 0.700
Round 32
Train Loss: 1.368, Train Accuracy: 0.750
Train Loss: 1.046, Train Accuracy: 0.500
Train Loss: 0.968, Train Accuracy: 0.400
Train Loss: 1.181, Train Accuracy: 0.800
Train Loss: 1.107, Train Accuracy: 0.625
Train Loss: 1.502, Train Accuracy: 0.800
Train Loss: 1.562, Train Accuracy: 0.750
Train Loss: 1.106, Train Accuracy: 0.800
Train Loss: 1.943, Train Accuracy: 1.000
Train Loss: 1.089, Train Accuracy: 0.400
Round 33
Train Loss: 1.281, Train Accuracy: 0.750
Train Loss: 0.995, Train Accuracy: 0.600
Train Loss: 0.945, Train Accuracy: 0.800
Train Loss: 1.467, Train Accuracy: 0.600
Train Loss: 1.279, Train Accuracy: 0.625
Train Loss: 1.317, Train Accuracy: 0.800
Train Loss: 1.574, Train Accuracy: 1.000
Train Loss: 1.154, Train Accuracy: 0.800
Train Loss: 2.174, Train Accuracy: 1.000
Train Loss: 1.149, Train Accuracy: 0.500
Round 34
Train Loss: 1.202, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.800
Train Loss: 0.942, Train Accuracy: 0.400
Train Loss: 1.311, Train Accuracy: 0.600
Train Loss: 1.169, Train Accuracy: 0.500
Train Loss: 1.438, Train Accuracy: 0.800
Train Loss: 1.583, Train Accuracy: 1.000
Train Loss: 1.043, Train Accuracy: 0.600
Train Loss: 1.814, Train Accuracy: 0.750
Train Loss: 1.035, Train Accuracy: 0.800
Round 35
Train Loss: 1.436, Train Accuracy: 0.750
Train Loss: 0.980, Train Accuracy: 0.700
Train Loss: 0.947, Train Accuracy: 0.400
Train Loss: 1.306, Train Accuracy: 1.000
Train Loss: 1.184, Train Accuracy: 0.750
Train Loss: 1.462, Train Accuracy: 0.800
Train Loss: 1.531, Train Accuracy: 1.000
Train Loss: 1.094, Train Accuracy: 1.000
Train Loss: 2.099, Train Accuracy: 1.000
Train Loss: 1.194, Train Accuracy: 0.500
Round 36
Train Loss: 1.361, Train Accuracy: 0.750
Train Loss: 0.968, Train Accuracy: 0.600
Train Loss: 0.955, Train Accuracy: 0.400
Train Loss: 1.547, Train Accuracy: 0.800
Train Loss: 1.173, Train Accuracy: 0.750
Train Loss: 1.376, Train Accuracy: 0.800
Train Loss: 1.432, Train Accuracy: 0.500
Train Loss: 1.145, Train Accuracy: 0.600
Train Loss: 1.991, Train Accuracy: 0.750
Train Loss: 1.207, Train Accuracy: 0.700
Round 37
Train Loss: 1.454, Train Accuracy: 0.750
Train Loss: 0.978, Train Accuracy: 0.500
Train Loss: 0.926, Train Accuracy: 0.600
Train Loss: 1.264, Train Accuracy: 0.800
Train Loss: 1.171, Train Accuracy: 0.750
Train Loss: 1.311, Train Accuracy: 0.800
Train Loss: 1.561, Train Accuracy: 0.500
Train Loss: 1.028, Train Accuracy: 0.200
Train Loss: 1.874, Train Accuracy: 0.750
Train Loss: 1.096, Train Accuracy: 0.400
Round 38
Train Loss: 1.513, Train Accuracy: 0.750
Train Loss: 0.970, Train Accuracy: 0.600
Train Loss: 0.923, Train Accuracy: 0.600
Train Loss: 1.225, Train Accuracy: 0.800
Train Loss: 1.237, Train Accuracy: 0.625
Train Loss: 1.437, Train Accuracy: 0.800
Train Loss: 1.501, Train Accuracy: 0.500
Train Loss: 1.038, Train Accuracy: 0.600
Train Loss: 1.925, Train Accuracy: 0.750
Train Loss: 1.298, Train Accuracy: 0.600
Round 39
Train Loss: 1.163, Train Accuracy: 0.750
Train Loss: 0.961, Train Accuracy: 0.600
Train Loss: 0.950, Train Accuracy: 0.600
Train Loss: 1.343, Train Accuracy: 1.000
Train Loss: 1.183, Train Accuracy: 0.500
Train Loss: 1.285, Train Accuracy: 0.800
Train Loss: 1.652, Train Accuracy: 0.500
Train Loss: 1.144, Train Accuracy: 0.800
Train Loss: 1.801, Train Accuracy: 0.750
Train Loss: 1.210, Train Accuracy: 0.600
Round 40
Train Loss: 1.398, Train Accuracy: 0.750
Train Loss: 0.959, Train Accuracy: 0.700
Train Loss: 0.935, Train Accuracy: 0.400
Train Loss: 1.393, Train Accuracy: 0.600
Train Loss: 1.242, Train Accuracy: 0.625
Train Loss: 1.306, Train Accuracy: 0.800
Train Loss: 1.380, Train Accuracy: 0.500
Train Loss: 1.025, Train Accuracy: 0.600
Train Loss: 1.692, Train Accuracy: 0.750
Train Loss: 0.977, Train Accuracy: 0.600
Round 41
Train Loss: 1.381, Train Accuracy: 0.750
Train Loss: 1.011, Train Accuracy: 0.700
Train Loss: 0.984, Train Accuracy: 0.800
Train Loss: 1.430, Train Accuracy: 0.800
Train Loss: 1.213, Train Accuracy: 0.750
Train Loss: 1.285, Train Accuracy: 0.800
Train Loss: 1.741, Train Accuracy: 1.000
Train Loss: 1.089, Train Accuracy: 0.800
Train Loss: 1.789, Train Accuracy: 0.750
Train Loss: 1.213, Train Accuracy: 0.700
Round 42
Train Loss: 1.287, Train Accuracy: 0.750
Train Loss: 0.990, Train Accuracy: 0.400
Train Loss: 0.946, Train Accuracy: 0.600
Train Loss: 1.305, Train Accuracy: 1.000
Train Loss: 1.144, Train Accuracy: 0.625
Train Loss: 1.361, Train Accuracy: 0.800
Train Loss: 1.658, Train Accuracy: 0.750
Train Loss: 1.051, Train Accuracy: 1.000
Train Loss: 1.986, Train Accuracy: 0.750
Train Loss: 1.181, Train Accuracy: 0.600
Round 43
Train Loss: 1.091, Train Accuracy: 0.750
Train Loss: 1.002, Train Accuracy: 0.500
Train Loss: 0.996, Train Accuracy: 0.800
Train Loss: 1.260, Train Accuracy: 1.000
Train Loss: 1.220, Train Accuracy: 0.625
Train Loss: 1.254, Train Accuracy: 0.800
Train Loss: 1.558, Train Accuracy: 0.750
Train Loss: 1.016, Train Accuracy: 0.800
Train Loss: 2.069, Train Accuracy: 1.000
Train Loss: 1.012, Train Accuracy: 0.500
Round 44
Train Loss: 1.396, Train Accuracy: 0.750
Train Loss: 1.001, Train Accuracy: 0.500
Train Loss: 0.879, Train Accuracy: 0.600
Train Loss: 1.253, Train Accuracy: 1.000
Train Loss: 1.127, Train Accuracy: 0.750
Train Loss: 1.308, Train Accuracy: 1.000
Train Loss: 1.491, Train Accuracy: 1.000
Train Loss: 1.046, Train Accuracy: 0.400
Train Loss: 1.946, Train Accuracy: 0.750
Train Loss: 1.257, Train Accuracy: 0.600
Round 45
Train Loss: 1.255, Train Accuracy: 0.750
Train Loss: 0.988, Train Accuracy: 0.600
Train Loss: 0.920, Train Accuracy: 0.600
Train Loss: 1.472, Train Accuracy: 0.600
Train Loss: 1.311, Train Accuracy: 0.875
Train Loss: 1.320, Train Accuracy: 0.800
Train Loss: 1.685, Train Accuracy: 0.500
Train Loss: 1.071, Train Accuracy: 0.400
Train Loss: 1.638, Train Accuracy: 0.750
Train Loss: 1.383, Train Accuracy: 0.500
Round 46
Train Loss: 1.282, Train Accuracy: 0.750
Train Loss: 0.991, Train Accuracy: 0.700
Train Loss: 0.888, Train Accuracy: 0.600
Train Loss: 1.541, Train Accuracy: 0.600
Train Loss: 1.104, Train Accuracy: 0.500
Train Loss: 1.345, Train Accuracy: 0.800
Train Loss: 1.884, Train Accuracy: 0.750
Train Loss: 1.142, Train Accuracy: 0.800
Train Loss: 1.879, Train Accuracy: 0.750
Train Loss: 0.988, Train Accuracy: 0.600
Round 47
Train Loss: 1.217, Train Accuracy: 0.750
Train Loss: 0.996, Train Accuracy: 0.600
Train Loss: 0.955, Train Accuracy: 0.600
Train Loss: 1.274, Train Accuracy: 0.800
Train Loss: 1.220, Train Accuracy: 0.750
Train Loss: 1.335, Train Accuracy: 0.800
Train Loss: 1.388, Train Accuracy: 0.750
Train Loss: 1.112, Train Accuracy: 1.000
Train Loss: 1.973, Train Accuracy: 0.750
Train Loss: 1.075, Train Accuracy: 0.800
Round 48
Train Loss: 1.093, Train Accuracy: 0.750
Train Loss: 1.028, Train Accuracy: 0.600
Train Loss: 0.901, Train Accuracy: 0.600
Train Loss: 1.600, Train Accuracy: 0.800
Train Loss: 1.207, Train Accuracy: 0.375
Train Loss: 1.353, Train Accuracy: 0.800
Train Loss: 1.567, Train Accuracy: 0.750

(FLClient pid=2781125) 2025-05-02 19:10:14,626 - INFO - Epoch   2| Train Loss: 0.815| Train Accuracy: 0.750 [repeated 357x across cluster]
(FLClient pid=2781125) 2025-05-02 19:10:14,633 - INFO - Epoch   2| Validation Loss: 1.475, Validation Accuracy: 0.395 [repeated 120x across cluster]

Results saved to Pubmed_results474/Pubmed_diffusion_GCN/results_Pubmed_diffusion_GCN.txt

In [25]:
import os
import ast # To safely evaluate string literal as dictionary
import pandas as pd
import logging # Using logging for better error reporting

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

def process_results_folder(main_folder_path):
    """
    Processes experiment results stored in subfolders of a main directory.

    Reads .txt files containing dictionary-like strings, parses them,
    and organizes the configuration and summary data into a Pandas DataFrame.

    Args:
        main_folder_path (str): The path to the main results folder
                                (e.g., 'Central_results2').

    Returns:
        pandas.DataFrame: A DataFrame containing the structured results,
                          with each row representing an experiment.
                          Returns an empty DataFrame if the folder is not found
                          or no valid results are processed.
    """
    all_results_data = [] # List to hold data for each valid experiment

    # --- Input Validation ---
    if not os.path.isdir(main_folder_path):
        logging.error(f"Folder not found at '{main_folder_path}'")
        return pd.DataFrame() # Return empty DataFrame

    logging.info(f"Starting processing for folder: '{main_folder_path}'")

    # --- Iterate Through Subfolders ---
    try:
        subfolder_names = os.listdir(main_folder_path)
    except OSError as e:
        logging.error(f"Could not list directory contents for '{main_folder_path}': {e}")
        return pd.DataFrame()

    for item_name in subfolder_names:
        subfolder_path = os.path.join(main_folder_path, item_name)

        # Check if it's actually a directory
        if not os.path.isdir(subfolder_path):
            logging.debug(f"Skipping non-directory item: '{item_name}'")
            continue

        logging.info(f"Processing subfolder: '{item_name}'")

        # --- Find the .txt File ---
        txt_file_path = None
        try:
            files_in_subfolder = os.listdir(subfolder_path)
            for filename in files_in_subfolder:
                if filename.endswith(".txt"):
                    # Assume only one relevant .txt file per subfolder
                    txt_file_path = os.path.join(subfolder_path, filename)
                    logging.debug(f"Found results file: '{filename}'")
                    break # Stop searching in this subfolder once found
            if not txt_file_path:
                 logging.warning(f"No .txt file found in subfolder '{item_name}'. Skipping.")
                 continue
        except OSError as e:
            logging.warning(f"Could not list files in subfolder '{item_name}': {e}. Skipping.")
            continue

        # --- Read and Parse File Content ---
        try:
            with open(txt_file_path, 'r', encoding='utf-8') as f:
                content = f.read()

            # Safely parse the string content into a Python dictionary
            # ast.literal_eval is safer than eval() for untrusted input
            data = ast.literal_eval(content)

            if not isinstance(data, dict):
                 logging.warning(f"Parsed content from '{txt_file_path}' is not a dictionary. Skipping.")
                 continue

        except FileNotFoundError:
            # This might happen in rare race conditions if the file is deleted
            # between listing and opening
            logging.warning(f"File '{txt_file_path}' found initially but could not be opened. Skipping.")
            continue
        except (SyntaxError, ValueError) as e:
            logging.warning(f"Error parsing content in file '{txt_file_path}': {e}. Skipping.")
            continue
        except Exception as e:
            logging.error(f"An unexpected error occurred reading/parsing '{txt_file_path}': {e}. Skipping.")
            continue

        # --- Extract Data ---
        # Use .get() for safer access in case keys are missing
        config = data.get('experiment_config', {})
        summary = data.get('summary', {})

        if not config or not summary:
             logging.warning(f"Missing 'experiment_config' or 'summary' key in '{txt_file_path}'. Skipping file.")
             continue

        # Create a flat dictionary for the DataFrame row
        # Start with configuration parameters
        row_data = config.copy()

        # Add summary results, prefixing keys if needed to avoid clashes (optional)
        # Example: prefix summary keys with 'summary_'
        # summary_prefixed = {f'summary_{k}': v for k, v in summary.items()}
        # row_data.update(summary_prefixed)

        # Or just update directly if keys are distinct
        row_data.update(summary)

        # Add an identifier for the experiment (using subfolder name)
        row_data['experiment_id'] = item_name
        # You could also add the filename if needed:
        # row_data['source_file'] = os.path.basename(txt_file_path)

        # Remove potentially large list/dict columns if not needed directly in the summary table
        # Adjust these based on what you want in the final table
        row_data.pop('global_results', None) # Remove list of all global results per round
        row_data.pop('client_results', None) # Remove list of all client results per round
        row_data.pop('rounds', None)         # Remove the detailed rounds data

        all_results_data.append(row_data)
        logging.debug(f"Successfully processed data for experiment '{item_name}'")

    # --- Create DataFrame ---
    if not all_results_data:
        logging.warning("No valid experiment data found to create a DataFrame.")
        return pd.DataFrame()

    try:
        results_df = pd.DataFrame(all_results_data)
        logging.info(f"Successfully created DataFrame with {len(results_df)} rows.")

        # Optional: Reorder columns for better readability
        id_col = ['experiment_id']
        config_cols = list(data.get('experiment_config', {}).keys())
        summary_cols = list(k for k in data.get('summary', {}).keys() if k not in ['global_results', 'client_results']) # Get summary keys added
        # Filter out columns that might not exist in all rows if parsing failed partially
        existing_cols = [col for col in id_col + config_cols + summary_cols if col in results_df.columns]
        results_df = results_df[existing_cols]

        # Optional: Set experiment_id as the DataFrame index
        # results_df.set_index('experiment_id', inplace=True)

    except Exception as e:
        logging.error(f"Failed to create DataFrame from processed data: {e}")
        return pd.DataFrame()


    return results_df

# --- Example Usage ---
# Note: Replace 'Central_results2' with the actual path to your folder.
# If running this script, make sure the folder exists relative to the script
# or provide an absolute path.

# Create dummy structure for demonstration if needed
def create_dummy_structure(base_dir="Central_results2_demo"):
    if not os.path.exists(base_dir):
        os.makedirs(base_dir)
    # Sample data similar to the user's example
    experiments_data = {
        "Pubmed_adjacency_GCN": {'experiment_config': {'device': 'cuda', 'data_loading_option': 'adjacency', 'model_type': 'GCN', 'dataset': 'Pubmed', 'num_clients': 10, 'beta': 1, 'hop': 1, 'fulltraining_flag': False}, 'rounds': [{'round': 1, 'global_result': 0.715, 'client_result': 0.724}, {'round': 2, 'global_result': 0.67, 'client_result': 0.698}], 'summary': {'global_results': [0.715, 0.67], 'client_results': [0.724, 0.698], 'average_global_result': 0.6925, 'average_client_result': 0.711, 'std_global': 0.0225, 'std_client': 0.013}},
        "Pubmed_diffusion_GCN": {'experiment_config': {'device': 'cuda', 'data_loading_option': 'diffusion', 'model_type': 'GCN', 'dataset': 'Pubmed', 'num_clients': 10, 'beta': 1, 'hop': 2, 'fulltraining_flag': False}, 'rounds': [], 'summary': {'average_global_result': 0.701, 'average_client_result': 0.715, 'std_global': 0.021, 'std_client': 0.012}},
        "Cora_full_SAGE": {'experiment_config': {'device': 'cpu', 'data_loading_option': 'full', 'model_type': 'SAGE', 'dataset': 'Cora', 'num_clients': 1, 'beta': 0, 'hop': 0, 'fulltraining_flag': True}, 'rounds': [], 'summary': {'average_global_result': 0.81, 'average_client_result': 0.81, 'std_global': 0.0, 'std_client': 0.0}},
        "Folder_With_Invalid_Txt": "This is not a dictionary string", # Test invalid content
        "Folder_With_No_Txt": {}, # Test missing txt file
        "Folder_With_Missing_Keys": {'experiment_config': {'device': 'cpu'}, 'summary': {}} # Test missing keys
    }
    logging.info(f"Creating dummy structure in '{base_dir}'...")
    for folder_name, data in experiments_data.items():
        subfolder_path = os.path.join(base_dir, folder_name)
        if not os.path.exists(subfolder_path):
            os.makedirs(subfolder_path)

        if folder_name == "Folder_With_No_Txt":
            # Create an empty file or a file with a different extension
            with open(os.path.join(subfolder_path, "other_file.log"), 'w') as f:
                f.write("Log data")
            continue # Don't create the specific .txt file

        # Create the results text file
        txt_filename = f"results_{folder_name}.txt"
        txt_filepath = os.path.join(subfolder_path, txt_filename)
        try:
            with open(txt_filepath, 'w', encoding='utf-8') as f:
                if isinstance(data, dict):
                    # Convert dict to string representation for the file
                    f.write(str(data))
                else:
                    # Write invalid data directly
                    f.write(data)
        except IOError as e:
            logging.error(f"Failed to write dummy file {txt_filepath}: {e}")
    logging.info("Dummy structure created.")


# --- Main execution block ---
if __name__ == "__main__":
    # Create dummy data for testing
    dummy_folder_path = "Central_results2_demo"
    create_dummy_structure(dummy_folder_path)

    # Process the results folder
    results_dataframe = process_results_folder(dummy_folder_path)

    # Display the results
    if not results_dataframe.empty:
        print("\n--- Processed Results DataFrame ---")
        # Configure pandas display options for better readability
        pd.set_option('display.max_columns', None) # Show all columns
        pd.set_option('display.width', 1000)       # Adjust width
        print(results_dataframe)
    else:
        print("\nNo DataFrame was generated. Check log messages for details.")

    # Clean up dummy structure (optional)
    # import shutil
    # try:
    #     shutil.rmtree(dummy_folder_path)
    #     logging.info(f"Cleaned up dummy directory: '{dummy_folder_path}'")
    # except OSError as e:
    #     logging.error(f"Error removing dummy directory '{dummy_folder_path}': {e}")

2025-05-02 19:11:05,878 - INFO - Creating dummy structure in 'Central_results2_demo'...
2025-05-02 19:11:05,880 - INFO - Dummy structure created.
2025-05-02 19:11:05,880 - INFO - Starting processing for folder: 'Central_results2_demo'
2025-05-02 19:11:05,880 - INFO - Processing subfolder: 'Folder_With_Missing_Keys'
2025-05-02 19:11:05,881 - WARNING - Missing 'experiment_config' or 'summary' key in 'Central_results2_demo/Folder_With_Missing_Keys/results_Folder_With_Missing_Keys.txt'. Skipping file.
2025-05-02 19:11:05,881 - INFO - Processing subfolder: 'Folder_With_No_Txt'
2025-05-02 19:11:05,882 - WARNING - No .txt file found in subfolder 'Folder_With_No_Txt'. Skipping.
2025-05-02 19:11:05,882 - INFO - Processing subfolder: 'Folder_With_Invalid_Txt'
2025-05-02 19:11:05,882 - WARNING - Error parsing content in file 'Central_results2_demo/Folder_With_Invalid_Txt/results_Folder_With_Invalid_Txt.txt': invalid syntax (<unknown>, line 1). Skipping.
2025-05-02 19:11:05,883 - INFO - Processing subfolder: 'Cora_full_SAGE'
2025-05-02 19:11:05,883 - INFO - Processing subfolder: 'Pubmed_adjacency_GCN'
2025-05-02 19:11:05,884 - INFO - Processing subfolder: 'Pubmed_diffusion_GCN'
2025-05-02 19:11:05,885 - INFO - Successfully created DataFrame with 3 rows.

--- Processed Results DataFrame ---
          experiment_id device data_loading_option model_type dataset  num_clients  beta  hop  fulltraining_flag  average_global_result  average_client_result  std_global  std_client
0        Cora_full_SAGE    cpu                full       SAGE    Cora            1     0    0               True                 0.8100                  0.810      0.0000       0.000
1  Pubmed_adjacency_GCN   cuda           adjacency        GCN  Pubmed           10     1    1              False                 0.6925                  0.711      0.0225       0.013
2  Pubmed_diffusion_GCN   cuda           diffusion        GCN  Pubmed           10     1    2              False                 0.7010                  0.715      0.0210       0.012

In [27]:
results_folder = "Pubmed_results474"
df = process_results_folder(results_folder)

2025-05-02 19:11:20,545 - INFO - Starting processing for folder: 'Pubmed_results474'
2025-05-02 19:11:20,546 - INFO - Processing subfolder: 'Pubmed_full_GCN'
2025-05-02 19:11:20,547 - INFO - Processing subfolder: 'Pubmed_adjacency_GCN'
2025-05-02 19:11:20,547 - INFO - Processing subfolder: 'Pubmed_diffusion_GCN'
2025-05-02 19:11:20,548 - INFO - Successfully created DataFrame with 3 rows.

In [28]:
df

          experiment_id device data_loading_option model_type dataset  num_clients   beta  hop  fulltraining_flag  average_global_result  average_client_result  std_global  std_client
0       Pubmed_full_GCN   cuda                full        GCN  Pubmed           10  10000    1              False                 0.7225               0.720676      0.0265    0.027055
1  Pubmed_adjacency_GCN   cuda           adjacency        GCN  Pubmed           10  10000    1              False                 0.7005               0.678560      0.0385    0.063565
2  Pubmed_diffusion_GCN   cuda           diffusion        GCN  Pubmed           10  10000    1              False                 0.6685               0.663217      0.0485    0.074739

In [18]:
results_folder2 = "Central_results3"
df2 = process_results_folder(results_folder2)
df2

2025-05-02 18:57:29,204 - ERROR - Folder not found at 'Central_results3'

Empty DataFrame
Columns: []
Index: []

In [19]:
results_folder3 = "Central_results4"
df3 = process_results_folder(results_folder3)
df3

2025-05-02 18:57:31,187 - ERROR - Folder not found at 'Central_results4'

Empty DataFrame
Columns: []
Index: []